### ISSUE TITLE
[doc][crypto] Document use of ZK api

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/sui#10029]
How ZK api can be used in Move, with a simple example, recommendations on how to generate proofs (use fastcrypto for tooling)

**Comment by GrapeBaBa** [comment]
Is this correct? We just use it in our project https://github.com/CubicGames/battleship/blob/master/sources/board_verifier.move#L14

**Comment by kchalkias** [comment]
@jonas-lj is working on the Sui/learn docs (mostly for devs to get familiar with functionality, no api change)
https://github.com/MystenLabs/sui/pull/11450

**Comment by kchalkias** [comment]
done in https://github.com/MystenLabs/sui/pull/11450
