### ISSUE TITLE
[docs.sui.io] UI dropdown issue re menu items

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/sui#10026]
Cryptography dropdown includes irrelevant menu-items, see link: https://docs.sui.io/learn/cryptography

Screenshot:
<img width="687" alt="Screen Shot 2023-03-28 at 1 26 43 PM" src="https://user-images.githubusercontent.com/25659162/228359408-7f918df8-5fc8-4e90-aad6-76c3bf93c2d5.png">

**Comment by randall-Mysten** [comment]
Thanks @kchalkias This was resolved but the site didn't build due to an error
