### ISSUE TITLE
Don't run rust tests when only docs change

### ISSUE THREAD

**Issue by todd-mystenlabs** [MystenLabs/sui#1005]
I'm not sure if there are cases where this would be *wrong*, but it would be great to avoid running tests when we're just changing dev portal and root-dir files like CONTRIBUTING.md, ISSUES.md, etc.

Right now I'm waiting 15+ minutes for the test suite to run on content that changes CONTRIBUTING.md.

**Comment by gdanezis** [comment]
More over I am not sure if we can skip the review process for doc only / .md files. I am not sure if the usual process we do for code is the best for fixing text.

**Comment by todd-mystenlabs** [comment]
@bmwill - did you say you addressed this?  We can close it out if so.

**Comment by gdanezis** [comment]
Done!
