### ISSUE TITLE
【ts-sdk】makeMoveVec not support empty vector

### ISSUE THREAD

**Issue by devlb1024** [MystenLabs/sui#10076]
the dependencies is : 
"@mysten/bcs":  "0.7.0",
"@mysten/sui.js": "0.30.0",

the contract code is:
![image](https://user-images.githubusercontent.com/101561247/228469035-f98b19d6-9ae1-4012-87eb-295478017ec1.png)
the ts code  is: 
![image](https://user-images.githubusercontent.com/101561247/228469163-87f57cc0-6194-4a96-9844-f502a772cbe5.png)

ruselt:
when coin_object_ids_bhas is empty vector, get an error:
![image](https://user-images.githubusercontent.com/101561247/228469500-a49cefdb-3482-4237-af38-f6f724b37b22.png)

**Comment by devlb1024** [comment]
this transactions input is : 

coin_object_ids_a:
 {                                                                                                                                                                                                        
      kind: 'MakeMoveVec',
      type: { None: null },
      objects: [
        {
          kind: 'Input',
          value: '0x1432019716ecf2d328abc8d4662356c35832d084e31ccafd9add6e96215e1b4a',
          index: 2,
          type: 'object'
        }
      ]
    }

coin_object_ids_b:
   { kind: 'MakeMoveVec', type: { None: null }, objects: [] }

this all args
{                                                                                                                                                                                                        
      kind: 'MoveCall',
      target: '0xa5b7b10130081fcfab08b8751da7a320265e4211deac23f44c256e0f5c03f045::pool_script::swap',
      arguments: [
        {
          kind: 'Input',
          value: '0x39140f2facfc5e709c152f1d1448c1c87a21b8bdb18945b9077da996d9b791fa',
          index: 0,
          type: 'pure'
        },
        {
          kind: 'Input',
          value: '0xda5b27566e4442d8f1047921f802c6d5fd116369b145211221884df57255fa94',
          index: 1,
          type: 'pure'
        },
        { kind: 'Result', index: 0 },
        { kind: 'Result', index: 1 },
        { kind: 'Input', value: true, index: 3, type: 'pure' },
        { kind: 'Input', value: true, index: 4, type: 'pure' },
        { kind: 'Input', value: '100', index: 5, type: 'pure' },
        { kind: 'Input', value: '0', index: 6, type: 'pure' },
        { kind: 'Input', value: '4295048016', index: 7, type: 'pure' },
        {
          kind: 'Input',
          value: '0x0000000000000000000000000000000000000000000000000000000000000006',
          index: 8,
          type: 'pure'
        }
      ],
      typeArguments: [
        '0xd099999e160c756a9e67da62f8eea05fc131006a4a73c96e0fd4baa56692a3f9::usdc::USDC',
        '0xd099999e160c756a9e67da62f8eea05fc131006a4a73c96e0fd4baa56692a3f9::usdt::USDT'
      ]
    }

**Comment by siliconvalley001** [comment]
How to use makeMoveVec, is there an example?

**Comment by Jordan-Mysten** [comment]
@devlb1024 Is there any reason you couldn't just take in a single coin and avoid the move vec all together? With Programmable Transaction Blocks, you should be able to use `mergeCoin` and `splitCoin` transactions to manage the coin objects into a single object.

@tnowacki I'm curious what the expected behavior is here for empty move vecs.

**Comment by amnn** [comment]
@Jordan-Mysten, the issue is that with a `MakeMoveVec` that has no elements, a type needs to be supplied (in the case where it's initialised non-empty, the type is inferred), and that doesn't seem to be happening here.

**Comment by devlb1024** [comment]
@Jordan-Mysten   when swap the direction is a2b,  在b方向需要传空vector

**Comment by tnowacki** [comment]
>  the type is inferred

Noe the type is only inferred for objects. So the type needs to be provided for pure and empty

**Comment by devlb1024** [comment]
> > the type is inferred
> 
> Noe the type is only inferred for objects. So the type needs to be provided for pure and empty

how to set the type   when the vector is  empty,  has typescript code example?

**Comment by Jordan-Mysten** [comment]
@devlb1024 It should be `builder.makeMoveVec({ type: 'some_type_here', objects: [] })`
