### ISSUE TITLE
Sui doc content issue or request

### ISSUE THREAD

**Issue by anandp1005** [MystenLabs/sui#10138]
Hi,
Recently I have installed the Sui Wallet through my browser and started using it.
Below are the addresses that were created.

0xe705a09fede084be250014547ca48f5dc00994b2

&
0xb7fafba18bebedc6824d364a57650d60b093833e
I have made lot of transactions on those address interacting with various Apps.  However I found that the explorer today gives no history of any transactions. I am bit a lot as if all the data is deleted. Is this meant to be like this. I thought all the transactions are on chain and will not be deleted.  Just wondering if this was a bug & moreover I have seen your most recent tweet (https://twitter.com/SuiNetwork/status/1641190388869263362) which kind of makes me think that there is a bug.   

It is much appreciated if you look into this & give an update as required.    
                                                                                                       
 Many Thanks.   
  Andy

**Comment by randall-Mysten** [comment]
Data on the network resets when a new release is deployed. This is normal and expected for a test network. We did release permanent Testnet where data will persist. Until Sui Mainnet nothing on the network is real, it's jsut test data.
