### ISSUE TITLE
testnet tokens not adding 

### ISSUE THREAD

**Issue by Starlew77** [MystenLabs/sui#10133]
hi

i have tried nemerous times to get testnet tokens via gitbash as you advised  and inputted the new walet addess aswell but its still coming back with errors and not adding tokens please see attached 
![20230330_113757](https://user-images.githubusercontent.com/116558527/228811226-d513982e-0ddc-4549-b3bb-0d633d22fcc0.jpg)

**Comment by randall-Mysten** [comment]
Did you change the wallet to use testnet? The command you ran is for devnet. Change devnet to testnet and make sure your wallet is set to testnet and the address matches

**Comment by Starlew77** [comment]
i have put new address in and changed to testnet but still get error message 
alos when i request tokens from wallet i get this error message 
![20230330_183816](https://user-images.githubusercontent.com/116558527/228921002-33cc2a19-93b9-4b69-b6fc-169ae190a22e.jpg)
![20230330_184253](https://user-images.githubusercontent.com/116558527/228921025-cb7e77d7-4d07-4a06-938e-ea95ea6fd690.jpg)
![20230330_184004](https://user-images.githubusercontent.com/116558527/228921046-f80a8313-818b-44dc-9bf0-5fdccc8f86ea.jpg)

**Comment by randall-Mysten** [comment]
I am seeing errors as well, must be the network. But your request is missing ' marks:

curl --location --request POST 'https://faucet.testnet.sui.io/gas' \
--header 'Content-Type: application/json' \
--data-raw '{
    "FixedAmountRequest": {
        "recipient": "0x46fcca79f567859db077dfe4740f3ce7f0187c208f7a8c30b0fdcbef6af69b7d"
    }
}'

**Comment by Starlew77** [comment]
hi ya 

i copied and pasted the above into gitbash but still no joy :(

saying command not found 

![20230330_201403](https://user-images.githubusercontent.com/116558527/228940737-57b23ead-83a3-4d95-accf-7a02c1004dc9.jpg)

**Comment by stefan-mysten** [comment]
The correct command for requesting tokens from the devnet or testnet faucet is here.
https://docs.sui.io/guides/developer/getting-started/get-coins#request-test-tokens-through-curl
