### ISSUE TITLE
[ts-sdk] fetch error

### ISSUE THREAD

**Issue by liuyepiaoxiang** [MystenLabs/sui#10140]
### environment 
I am using @mysten/sui.js verrsion ^0.30.0

### Code 
```
import { JsonRpcProvider, devnetConnection } from '@mysten/sui.js';
// connect to Devnet
const provider = new JsonRpcProvider(devnetConnection);
// get tokens from the Devnet faucet server
await provider.requestSuiFromFaucet(
  '<YOUR SUI ADDRESS>'
);
```
### Run
```
node index.js
```

## Expected Result
Get faucet on devnet

## Actual Result
Turns out error with

```typescript
node_modules/@mysten/sui.js/dist/index.mjs:2326
  const res = await fetch(endpoint, {
              ^
ReferenceError: fetch is not defined
```

## System Information

* OS: Ubuntu 20.0.4
* Compiler: nodejs 16.18.0; npm 8.19.2

**Comment by mattsu2020** [comment]
fetch api requires node.js version 18 or higher. Please implement the version upgrade.

**Comment by HenryNguyen5** [comment]
You can also use https://www.npmjs.com/package/isomorphic-fetch if you'd like to stay with node < 18
