### ISSUE TITLE
how  to connect  the  sui wallet  by click "connect button"?

### ISSUE THREAD

**Issue by soulToken** [MystenLabs/sui#10199]
I use  
import { JsonRpcProvider, devnetConnection } from '@mysten/sui.js';
const provider = new JsonRpcProvider(devnetConnection);
console.log(provider);

I want to use  sui  api  to do  like  this?
![image](https://user-images.githubusercontent.com/30686262/229037196-cb7b2d3e-160c-4dcf-81e7-43c0aba1c0f9.png)
 what  should  I do ?

**Comment by Jordan-Mysten** [comment]
You can use a wallet adapter or a connection UI to handle this. We recommend Sui Wallet Kit, which is built for this use-case: https://sui-wallet-kit.vercel.app/
