### ISSUE TITLE
devnet-panic error 

### ISSUE THREAD

**Issue by mattsu2020** [MystenLabs/sui#10192]
## Steps to Reproduce Issue
I am reporting a panic error with the latest version of devnet.

・git commit id
d6ebeaa32137d4768f97dde14ab04f51d86226b7
・branch
devnet

```
2023-03-31T02:39:53.980917Z ERROR execute_checkpoint{seq=203680 epoch=2}: telemetry_subscribers: panicked at '0x2c1f3defd4e64ea5cfd701d760242a8f34db561245d206fcdd0d09b5930c392c', crates/sui-core/src/state_accumulator.rs:181:21 panic.file="crates/sui-core/src/state_accumulator.rs" panic.line=181 panic.column=21
thread 'tokio-runtime-worker' panicked at '0x2c1f3defd4e64ea5cfd701d760242a8f34db561245d206fcdd0d09b5930c392c', crates/sui-core/src/state_accumulator.rs:181:21
stack backtrace:
   0:     0x55afc0b68e30 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb070b7fa7e3175df
   1:     0x55afc0b9320e - core::fmt::write::hd5207aebbb9a86e9
   2:     0x55afc0b61125 - std::io::Write::write_fmt::h3bd699bbd129ab8a
   3:     0x55afc0b6a7b3 - std::panicking::default_hook::{{closure}}::h04cca40023d0eeca
   4:     0x55afc0b6a49f - std::panicking::default_hook::haa3ca8c310ed5402
   5:     0x55afbf424215 - telemetry_subscribers::set_panic_hook::{{closure}}::hf7dd2647599847a2
   6:     0x55afc0b6aefd - std::panicking::rust_panic_with_hook::h7b190ce1a948faac
   7:     0x55afc0b6ad57 - std::panicking::begin_panic_handler::{{closure}}::hbafbfdc3e1b97f68
   8:     0x55afc0b692dc - std::sys_common::backtrace::__rust_end_short_backtrace::hda93e5fef243b4c0
   9:     0x55afc0b6aa72 - rust_begin_unwind
  10:     0x55afbe80f653 - core::panicking::panic_fmt::h8d17ca1073d9a733
  11:     0x55afbf31a6b5 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h684e563c4a8f373c
  12:     0x55afbf2dc7be - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::hdffea9c43e66dabf
  13:     0x55afbf3340a5 - sui_core::state_accumulator::StateAccumulator::accumulate_effects::h1fe756cdc2298b6d
  14:     0x55afbf33344f - sui_core::state_accumulator::StateAccumulator::accumulate_checkpoint::h95509e47295bbdc6
  15:     0x55afbf12a102 - sui_core::checkpoints::checkpoint_executor::finalize_checkpoint::h6d11e944ac731e3e
  16:     0x55afbf1906a0 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h8c03ea977896f5e9
  17:     0x55afbf39c6c9 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::hf3dfed552e1c473f
  18:     0x55afbf1af052 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf2d3f7f4b71df574
  19:     0x55afbf38c3c8 - tokio::runtime::task::core::Core<T,S>::poll::h5db577809d4bc707
  20:     0x55afbf2fba29 - tokio::runtime::task::harness::Harness<T,S>::poll::hd8b6141c931952a4
  21:     0x55afc0a40cde - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h482d26258ce6fbd6
  22:     0x55afc0a403ce - tokio::runtime::scheduler::multi_thread::worker::Context::run::h84e89ac13faf15fe
  23:     0x55afc0a3ff10 - tokio::runtime::scheduler::multi_thread::worker::run::h1023028e3d3211d9
  24:     0x55afc0a32515 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hc1ce46902b1f805a
  25:     0x55afc0a2b560 - tokio::runtime::task::core::Core<T,S>::poll::hc634c21f31efeca8
  26:     0x55afc0a45127 - tokio::runtime::task::harness::Harness<T,S>::poll::hf42ee223a36ac67c
  27:     0x55afc0a35834 - tokio::runtime::blocking::pool::Inner::run::hfdc5aba39c1ee91d
  28:     0x55afc0a3205d - std::sys_common::backtrace::__rust_begin_short_backtrace::h985ed863350259d7
  29:     0x55afc0a4368d - core::ops::function::FnOnce::call_once{{vtable.shim}}::h53b5665eb012660f
  30:     0x55afc0b711f3 - std::sys::unix::thread::Thread::new::thread_start::h62ca48b42d48a8fc
  31:     0x7fb51833db43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  32:     0x7fb5183cfa00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  33:                0x0 - <unknown>
Aborted
```

## Expected Result
```
        let wrapped_objects_to_remove: Vec<WrappedObject> = all_unwrapped
            .iter()
            .filter_map(|(id, seq_num)| {
                let objref = self
                    .authority_store
                    .get_object_ref_prior_to_key(id, *seq_num)
                    .expect("read cannot fail");

                objref.map(|(id, version, digest)| {
                    assert!(digest.is_wrapped(), "{:?}", id);
                    WrappedObject::new(id, version)
                })
            })
            .collect();
```

## System Information

* OS: "Ubuntu 22.04.2 LTS"
* Compiler: cargo 1.65.0 (4bc8f24d3 2022-10-20)

**Comment by mattsu2020** [comment]
The target IDs are address and object.
There does not seem to be any special processing.

https://explorer.sui.io/object/0x2c1f3defd4e64ea5cfd701d760242a8f34db561245d206fcdd0d09b5930c392c?network=devnet

https://explorer.sui.io/address/0x2c1f3defd4e64ea5cfd701d760242a8f34db561245d206fcdd0d09b5930c392c?network=devnet

**Comment by batcoder1** [comment]
Same error in my node. 
`fullnode_1  | 2023-04-04T14:54:54.819758Z ERROR execute_checkpoint{seq=203680 epoch=2}: telemetry_subscribers: panicked at '0x2c1f3defd4e64ea5cfd701d760242a8f34db561245d206fcdd0d09b5930c392c', crates/sui-core/src/state_accumulator.rs:181:21 panic.file="crates/sui-core/src/state_accumulator.rs" panic.line=181 panic.column=21
fullnode_1  | thread 'tokio-runtime-worker' panicked at '0x2c1f3defd4e64ea5cfd701d760242a8f34db561245d206fcdd0d09b5930c392c', crates/sui-core/src/state_accumulator.rs:181:21
fullnode_1  | stack backtrace:
fullnode_1  |    0:     0x560e108ff4e0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb070b7fa7e3175df
fullnode_1  |    1:     0x560e109298be - core::fmt::write::hd5207aebbb9a86e9
fullnode_1  |    2:     0x560e108f77d5 - std::io::Write::write_fmt::h3bd699bbd129ab8a
fullnode_1  |    3:     0x560e10900e63 - std::panicking::default_hook::{{closure}}::h04cca40023d0eeca
fullnode_1  |    4:     0x560e10900b4f - std::panicking::default_hook::haa3ca8c310ed5402
fullnode_1  |    5:     0x560e0f1c107c - telemetry_subscribers::set_panic_hook::{{closure}}::hf7dd2647599847a2
fullnode_1  |    6:     0x560e109015ad - std::panicking::rust_panic_with_hook::h7b190ce1a948faac
fullnode_1  |    7:     0x560e10901407 - std::panicking::begin_panic_handler::{{closure}}::hbafbfdc3e1b97f68
fullnode_1  |    8:     0x560e108ff98c - std::sys_common::backtrace::__rust_end_short_backtrace::hda93e5fef243b4c0
fullnode_1  |    9:     0x560e10901122 - rust_begin_unwind
fullnode_1  |   10:     0x560e0e5900a3 - core::panicking::panic_fmt::h8d17ca1073d9a733
fullnode_1  |   11:     0x560e0f0b3fce - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h684e563c4a8f373c
fullnode_1  |   12:     0x560e0f07658e - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::hdffea9c43e66dabf
fullnode_1  |   13:     0x560e0f0cd974 - sui_core::state_accumulator::StateAccumulator::accumulate_effects::h1fe756cdc2298b6d
fullnode_1  |   14:     0x560e0f0cccca - sui_core::state_accumulator::StateAccumulator::accumulate_checkpoint::h95509e47295bbdc6
fullnode_1  |   15:     0x560e0eebc9a5 - sui_core::checkpoints::checkpoint_executor::finalize_checkpoint::h6d11e944ac731e3e
fullnode_1  |   16:     0x560e0ef247df - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h8c03ea977896f5e9
fullnode_1  |   17:     0x560e0f13667e - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::hf3dfed552e1c473f
fullnode_1  |   18:     0x560e0ef43d92 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf2d3f7f4b71df574
fullnode_1  |   19:     0x560e0f1261cc - tokio::runtime::task::core::Core<T,S>::poll::h5db577809d4bc707
fullnode_1  |   20:     0x560e0f095809 - tokio::runtime::task::harness::Harness<T,S>::poll::hd8b6141c931952a4
fullnode_1  |   21:     0x560e107d8bae - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h482d26258ce6fbd6
fullnode_1  |   22:     0x560e107d82de - tokio::runtime::scheduler::multi_thread::worker::Context::run::h84e89ac13faf15fe
fullnode_1  |   23:     0x560e107d7e33 - tokio::runtime::scheduler::multi_thread::worker::run::h1023028e3d3211d9
fullnode_1  |   24:     0x560e107ca562 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hc1ce46902b1f805a
fullnode_1  |   25:     0x560e107c370e - tokio::runtime::task::core::Core<T,S>::poll::hc634c21f31efeca8
fullnode_1  |   26:     0x560e107dd02a - tokio::runtime::task::harness::Harness<T,S>::poll::hf42ee223a36ac67c
fullnode_1  |   27:     0x560e107cd843 - tokio::runtime::blocking::pool::Inner::run::hfdc5aba39c1ee91d
fullnode_1  |   28:     0x560e107ca0ac - std::sys_common::backtrace::__rust_begin_short_backtrace::h985ed863350259d7
fullnode_1  |   29:     0x560e107db597 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h53b5665eb012660f
fullnode_1  |   30:     0x560e109078a3 - std::sys::unix::thread::Thread::new::thread_start::h62ca48b42d48a8fc
fullnode_1  |   31:     0x7f4bdb5e1ea7 - start_thread
fullnode_1  |   32:     0x7f4bdb3b5a2f - clone
fullnode_1  |   33:                0x0 - <unknown>`

**Comment by adacapo21** [comment]
I don't know if the below error is the same with this one, but seems relevant:
` thread 'tokio-runtime-worker' panicked at 'Do not expect the channel to be closed', crates/sui-core/src/quorum_driver/reconfig_observer.rs:118:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 `
![image](https://user-images.githubusercontent.com/9395707/230010744-04cf2dbb-56c7-4447-97ed-fd995d326af0.png)

**Comment by stefan-mysten** [comment]
I expect that this has been fixed since March. Closing the issue for now but feel free to create a fresh issue if you're still encountering problems @adacapo21
