### ISSUE TITLE
Issue with "deleted" objects on account

### ISSUE THREAD

**Issue by ldback-aftermath** [MystenLabs/sui#10208]
## Steps to Reproduce Issue

1. Deploy the following contract using version `sui testnet-0.29.1`

```move
module snd::some {
    use sui::tx_context::{Self, TxContext};
    use sui::object::{UID, Self};
    use sui::transfer;

    struct SomePublic has key, store{
        id: UID,
        obj: SomeObj,
    }

    struct SomeObj has key, store {
        id: UID
    }

    fun init(ctx: &mut TxContext) {
        let obj = SomeObj{
            id: object::new(ctx),
        };
        let sender = tx_context::sender(ctx);
        transfer::transfer(obj, sender);
    }

    public entry fun snd(some_obj: SomeObj, ctx: &mut TxContext) {
        let publ = SomePublic {
            id: object::new(ctx),
            obj: some_obj,
        };
        transfer::public_share_object(publ);
    }
}
```
2. Call `snd()` method from CLI:

```bash
sui client call \
	--package $PACKAGE \
	--module some \
	--function snd \
	--gas-budget 50000 \
	--args \
		$SOME_OBJ
```
where 

- `$PACKAGE` is the deployed package address; 
- `$SOME_OBJ` is an address of the object transferred to the user account during the package deployment.

3. Try to run:
```bash
sui client objects
```

## Expected Result

A list of owned objects.

## Actual Result

```bash
$ sui client objects
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Deleted { object_id: 0xd57c1a970f6f8b81a4b2bd25840fec3752a399cb07d5f64ca06179e467979ee0, version: SequenceNumber(5), digest: o#6ws1bVyu3F8wGy1fPHhrc2v8UyWiGbRAAuek8SwikKPD }', crates/sui/src/client_commands.rs:1438:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

## System Information

* OS:  
`Linux 6.2.7-200.fc37.x86_64  x86_64 GNU/Linux`

Fedora 52

* Compiler: sui 0.29.0-82c9c80c1
sui-move 0.1.0

## Remarks

On the `sui 0.28.0-1815e099f` this example works fine.

**Comment by ldback-aftermath** [comment]
Additional info: 

If one try to call methods shown below, in the same manner,  one will observe following situation:
When we call `snd_coin()` everything works fine. 
Once we call `snd_wrapper_coin()`, we obtain the same  panic message when we try to run `sui client objects`.

```move
     public entry fun snd_coin(coin: Coin<SUI>, addr: address) {
        transfer::public_transfer(coin, addr);
    }

    public entry fun snd_wrapped_coin(coin: Coin<SUI>, addr: address, ctx: &mut TxContext) {
        let publ = SomeWrapper {
            id: object::new(ctx),
            coin,
        };
        transfer::public_transfer(publ, addr);
    }
```

It looks like the key point her is wrapping.

**Comment by crypto-trekker** [comment]
I confirm the problem with the 'sui client' after wrapping objects.
In my case, after wrapping an object and sending it to another address, the following occurs:
- The Sui Explorer shows the object ID as unknown
- The sui client is not able anymore to list objects, panicking with the following message:
`$ sui client objects
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Deleted { object_id: 0x49d619e242cff993446692ad55d46895c6f8c4583176c8b8d4219616c76afea1, version: SequenceNumber(5043), digest: o#6ws1bVyu3F8wGy1fPHhrc2v8UyWiGbRAAuek8SwikKPD }', crates/sui/src/client_commands.rs:1438:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)`

**Comment by stefan-mysten** [comment]
I assume this is both obsolete and that it works now, @ldback-aftermath feel free to re-open if this is still an issue.
#spring-cleanup
