### ISSUE TITLE
SDK sui.js v0.30.0 crash bug

### ISSUE THREAD

**Issue by Azard** [MystenLabs/sui#10266]
v0.29 is ok, but v0.30.0 crash

`require('@mysten/sui.js')` will crash on production mode

`mapToCurveSimpleSWU`

Uncaught TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at b (main.7431cdc0.js:2:171278)
    at t.mapToCurveSimpleSWU (main.7431cdc0.js:2:178392)
    at 9958 (main.7431cdc0.js:2:184137)
    at n (main.7431cdc0.js:2:1263140)
    at 2312 (main.7431cdc0.js:2:254114)
    at n (main.7431cdc0.js:2:1263140)
    at 7503 (main.7431cdc0.js:2:85982)
    at n (main.7431cdc0.js:2:1263140)
    at 8620 (main.7431cdc0.js:2:20932)

![93550985ec495c901ee59d3ca6826d1](https://user-images.githubusercontent.com/3364650/229279686-3a1d163a-335b-4220-8d1a-ad82b385e655.png)

![7fb6d794570617df117339f748053b4](https://user-images.githubusercontent.com/3364650/229279677-21275cc3-958d-4a6f-95f1-a9ebf0266d3c.png)

**Comment by Azard** [comment]
https://github.com/paulmillr/noble-curves/issues/25

**Comment by Azard** [comment]
@noble/curve not compatible with frontend

**Comment by ycg5250** [comment]
@Azard So, is this problem solved?

**Comment by Shaik-Sirajuddin** [comment]
How did you fix this issue ?

**Comment by okxiaoxu** [comment]
How did you fix this issue ?

**Comment by Shaik-Sirajuddin** [comment]
To fix this issue , update your package.json file 

```
"browserslist": {
    "production": [
      "chrome >= 67",
      "edge >= 79",
      "firefox >= 68",
      "opera >= 54",
      "safari >= 14"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
```

**Comment by Shaik-Sirajuddin** [comment]
https://github.com/MystenLabs/sui/issues/10266#issuecomment-1551122346
Check this
