### ISSUE TITLE
Error while installing Sui binaries

### ISSUE THREAD

**Issue by pantemon** [MystenLabs/sui#10273]
## Steps to Reproduce Issue

1. Reproduce all the steps from the following tutorial (for Linux) until: https://docs.sui.io/build/install#install-sui-binaries
2. Run `https://docs.sui.io/build/install#install-sui-binaries`

## Expected Result

Installed Sui binaries.

## Actual Result

I constantly get the following: `error: could not compile diesel`, `error: could not compile ark-ff`, `error: could not compile move-compiler`, and `error: failed to run custom build command for jemalloc-sys v0.5.2+5.3.0-patched`. I also get the message that the process didn't exit successfully for each of them.

## System Information

* OS: ![image](https://user-images.githubusercontent.com/96831202/229310362-9db78653-3b88-47be-a6f5-680d2cece423.png)
* Compiler: ![image](https://user-images.githubusercontent.com/96831202/229310380-666dcc41-b11b-4356-8028-760d8351e466.png)

**Comment by mevichi15** [comment]
Have you found a solution yet? 

Having the same issue.

**Comment by stefan-mysten** [comment]
This has been fixed since it was reported, so I will close the issue for now. Feel free to create a new issue if you still encounter any problems when installing Sui.
