### ISSUE TITLE
Sui Wallet should export `window.suiWallet` object again

### ISSUE THREAD

**Issue by Azard** [MystenLabs/sui#10294]
One month ago, our project AnimeSwap connects Sui Wallet vai `window.suiWallet`

The latest Sui Wallet only support SDK connection with React framework, its not developer friendly.

Not all builders building with React and want to install the SDK.

Martian Wallet can connect with `window.martian.sui` its nice for developers

We have no way to connect Sui Wallet any more

Why remove `window.suiWallet`, very bad for developers

**Comment by Jordan-Mysten** [comment]
We support the [Wallet Standard](https://github.com/wallet-standard/wallet-standard) for all wallet interactions. If you don't use React, you can use the Wallet Kit Core, or an ecosystem project that supports the wallet standard.
