### ISSUE TITLE
DISCORD ISSUE 

### ISSUE THREAD

**Issue by grayson62** [MystenLabs/sui#10308]
Hello Team 
today i  open my discord i see i was disconnect to discord sui server   again i try to join with your official twitter account  then he show me this unable to accept invites what issue i can face bcz i am crypto airdrop hunter on twitter i have almost 1000+ followers we are working with team up and help eachother  can u please guess me what problem i face  my discord username grayson#2543   please fix it i am old member almost testnet 1 dev 
![sui discord eror](https://user-images.githubusercontent.com/129719320/229421193-5677f25e-b5bb-4950-8cf4-c477a5e613c6.png)

**Comment by Richardweb1** [comment]
I can't rejoin to the discord account. I was in before I changed my laptop and now I can't back even I'm supporting the project from the beginning. I wish I can resolve this situation my ID is : RICHARD09#6877 .you can check and you will find I'm a member of all the our partners. Thank you
