### ISSUE TITLE
Can I show my domain NFT key in my wallet?

### ISSUE THREAD

**Issue by yanghelong1** [MystenLabs/sui#10328]
Can I show my domain NFT key in my wallet?

**Comment by sikaCee** [comment]
For now only staking is ongoing inside the sui wallet and the staking nft can be seen on the explorer. Hopefully SUI team fixes it to be seen in-app.
Moreso, suiNS and other projects seen in-app previously are not active/functioning currently. We are waiting for various teams to deploy their project on the permanent testnet. Hope this was helpful.

**Comment by pchrysochoidis** [comment]
Is this about showing the suins registration object in wallet, in assets page? It is visible now, so I will close the ticket but feel free to reopen it in case it is about something else!
