### ISSUE TITLE
Cannot install Sui

### ISSUE THREAD

**Issue by chiaoyuan1991** [MystenLabs/sui#10367]
### Steps to Reproduce Issue
after i ran 
`cargo install --locked --git https://github.com/MystenLabs/sui.git --branch devnet sui`
### Actual result
``  Compiling secp256k1 v0.26.0
    Building [================>      ] 1395/1786: lz4-sys(build), bzip2-sys(b   Compiling outref v0.5.1                                                  .   Compiling vsimd v0.8.0
   Compiling bytes-utils v0.1.3
   Compiling base64-simd v0.8.0
   Compiling aws-smithy-types v0.54.4
   Compiling aws-smithy-async v0.54.4
   Compiling narwhal-types v0.1.0 (C:\Users\86137\.cargo\git\checkouts\sui-6ac459c53b1b685a\d6ebeaa\narwhal\types)
   Compiling aws-types v0.54.1
   Compiling aws-smithy-http v0.54.4
   Compiling aws-credential-types v0.54.1
   Compiling aws-smithy-http-tower v0.54.4
error: failed to run custom build command for `narwhal-types v0.1.0 (C:\Users\86137\.cargo\git\checkouts\sui-6ac459c53b1b685a\d6ebeaa\narwhal\types)`

Caused by:
  process didn't exit successfully: `C:\Users\86137\AppData\Local\Temp\cargo-installv9nzft\release\build\narwhal-types-7a026a07841fbc49\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=proto/narwhal.proto
  cargo:rerun-if-changed=proto

  --- stderr
  thread 'main' panicked at 'Could not find `protoc` installation and this build crate cannot proceed without
      this knowledge. If `protoc` is installed and this crate had trouble finding
      it, you can set the `PROTOC` environment variable with the specific path to your
      installed `protoc` binary.You can download it from https://github.com/protocolbuffers/protobuf/releases or from your package manager.

  For more information: https://docs.rs/prost-build/#sourcing-protoc
  ', C:\Users\86137\.cargo\registry\src\github.com-1ecc6299db9ec823\prost-build-0.11.8\src\lib.rs:1434:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `sui v0.29.1 (https://github.com/MystenLabs/sui.git?branch=devnet#d6ebeaa3)`, intermediate artifacts can be found at `C:\Users\86137\AppData\Local\Temp\cargo-installv9nzft`

``

**Comment by aaabigfish** [comment]
How to solve it ?

**Comment by chiaoyuan1991** [comment]
What problem have you encountered? Please describe it to me in detail, and I will try my best to answer it for you.













&nbsp;


511593548
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月1日(星期四) 下午4:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MystenLabs/sui] Cannot install Sui (Issue #10367)





 
How to solve it ?

**Comment by stefan-mysten** [comment]
@chiaoyuan1991 thanks for reporting this problem. Since then, this has been fixed, so I will close this issue. Feel free to create a new issue if you still encounter problems.
