### ISSUE TITLE
Local RPC configuration of http://0.0.0.0:9000 is not working for Windows 

### ISSUE THREAD

**Issue by teohaik** [MystenLabs/sui#10371]
## Steps to Reproduce Issue

1. Install sui on Windows
2. Start a local node 
3. Try to run a cli command, eg `sui client gas`

## Expected Result

The gas coin list

## Actual Result

```
PS C:\Users\teoha> sui client gas
Networking or low-level protocol error: HTTP error: error trying to connect: tcp connect error: The requested address is not valid in its context. (os error 10049)

Caused by:
    HTTP error: error trying to connect: tcp connect error: The requested address is not valid in its context. (os error 10049)

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
```

if client.yaml file is changed to 
```
  - alias: localnet
    rpc: "http://127.0.0.1:9000"
```

commands work fine:
```
PS C:\Users\teoha> sui client gas
                             Object ID                              |  Gas Value
----------------------------------------------------------------------------------
 0x774f93c3823ea31d1265f53f604c9ee1a370c70523ead28c33ffeb742ae6b806 | 30000000000000000
 0xb9dbbe8c96e0a0a11d12347223615e228bcf1f4bed42d7c1826d29f5dc009e3e | 30000000000000000
 0xd803cb790861dfcd7cc606b3878f40465fa7317253be312b909b9a7682737746 | 30000000000000000
 
```

**Comment by stefan-mysten** [comment]
@teohaik, do you know if this is still a problem? I

**Comment by teohaik** [comment]
@stefan-mysten  yes it still exists. just reproduced it:

 Details : Networking or low-level protocol error: HTTP error: error trying to connect: tcp connect error: The requested address is not valid in its context. (os error 10049)

Caused by:
    HTTP error: error trying to connect: tcp connect error: The requested address is not valid in its context. (os error 10049)

**Comment by stefan-mysten** [comment]
@teohaik This should be fixed now, if you do a `sui start` or `sui genesis` when there's no `sui/sui_config` directory. It will correctly generate the `client.yaml` file with the IP address 127.0.0.1 for localnet.
