### ISSUE TITLE
[Wallet] Will throw error when using the `TransactionBlock.publish`

### ISSUE THREAD

**Issue by anthony-leung-hk** [MystenLabs/sui#10370]
## Steps to Reproduce Issue

When the `TransactionBlock` includes the `publish` and calls the `signAndExecuteTransactionBlock`, it will throw the Error:

`Something went wrong
Can not use 'in' operator to search for 'None' in 161`

## Expected Result

Should return the transaction response

## Actual Result

Will throw the Error in the Wallet:
`Something went wrong
Can not use 'in' operator to search for 'None' in 161`

I found the reason is in the `PublishTransaction`, the `modules` type is number[][],

But when the Wallet tries to convert the command argument, because `'None' in arg` and `'Some' in arg` (In `src/ui/app/pages/approval-request/transaction-request/TransactionDetails/Command.tsx`)  is only can use an object type, but the publish modules is `number[][]`, will throw this Error.

Suggest Example:
`if ('None' in arg) {` change to `if (typeof arg === 'object' && 'None' in arg) {`
`if ('Some' in arg) {` change to ` if (typeof arg === 'object' && 'Some' in arg) {`

And add a handle in `convertCommandArgumentToString` to show the number[][] display.

**Comment by anthony-leung-hk** [comment]
https://github.com/MystenLabs/sui/pull/10376

**Comment by Jordan-Mysten** [comment]
Fixed by #10399
