### ISSUE TITLE
[ts-sdk] @Mysten/sui.js

### ISSUE THREAD

**Issue by MatthewByun** [MystenLabs/sui#10380]
Everything fine when i'm using in my local, but when i'm run build, i'm get this error:
<img width="632" alt="Screenshot 2023-04-04 at 17 59 03" src="https://user-images.githubusercontent.com/97074012/229771643-aa47ef4d-e55c-4171-adff-b135f52ba4e0.png">

**Comment by Jordan-Mysten** [comment]
The code error location looks like it exists outside of the SDK, can you share the code that's causing the error?.

**Comment by MatthewByun** [comment]
this is some of my code, i'm just using aroung those method
<img width="933" alt="Screenshot 2023-04-05 at 08 34 04" src="https://user-images.githubuse
<img width="713" alt="Screenshot 2023-04-05 at 08 35 51" src="https://user-images.githubusercontent.com/97074012/229958771-a2610d32-2534-4564-a470-c302dcdd7c17.png">
rcontent.com/97074012/229958664-4b11eb18-9c25-4139-8c7d-173c5ac6321d.png">

**Comment by MatthewByun** [comment]
i think the problem come from Ed25519Keypair, when i'm not import { Ed25519Keypair } it's fine.
but i want to use Ed25519Keypair, can you show me how to fix it

**Comment by Jordan-Mysten** [comment]
@MatthewByun What bundler is your project using?

**Comment by MatthewByun** [comment]
> 

i'm using webpack

**Comment by MatthewByun** [comment]
<img width="996" alt="Screenshot 2023-04-06 at 10 17 05" src="https://user-images.githubusercontent.com/97074012/230263761-19b5e95f-1f9b-419d-be0b-24642f97e3af.png">

this is more details when i clicked in weierstrass.ts from first picture

**Comment by Jordan-Mysten** [comment]
I tried a minimal webpack setup and wasn't able to repro this, can you get me a minimal repro?

**Comment by MatthewByun** [comment]
thank you, i'm tried again with new webpack setup + @mysten/sui.js verion 0.31.0  and everything is fine
