### ISSUE TITLE
[Sui Wallet] Packages Publishing problem & solution

### ISSUE THREAD

**Issue by hvietdo99** [MystenLabs/sui#10420]
## Steps to Reproduce Issue

When the `TransactionBlock` includes the packages publishing and calls the `signAndExecuteTransactionBlock`, it will throw the Error:
`Something went wrong! Can not use 'in' operator to search for 'None' in 161`

![Screen Shot 2023-04-05 at 10 50 03](https://user-images.githubusercontent.com/85572641/229976806-21017f66-284a-4bba-9cbf-eda448c96bd0.png)

## Expected Result

Should return transaction arguments and response.

e.g.
Expected <other function call> to return 42.

## Actual Result

Throwing the Error in the Wallet:
`Something went wrong! Can not use 'in' operator to search for 'None' in 161`

I figured out the cause is in the `PublishTransaction`, the modules type is `number[][]`.

When the Wallet tries to convert the command arguments (In `apps/wallet/src/ui/app/pages/approval-request/transaction-request/TransactionDetails/Command.tsx/convertCommandArgumentToString()`), `'None'` and `'Some'` in arg can only use for an `object` type, but the publishing module is `number[][]`, which leads to this error.

Proposed solutions: 
```
In function convertCommandArgumentToString(
  arg:
    | string
    | string[] |
    - Add a type to the input argument: number[][]
    | TransactionArgument
    | TransactionArgument[]
    | MakeMoveVecTransaction['type']
): string | null {
  ...

  - Add a validation command for number[][]: 
  // Case for the PublishTransaction
  if (Array.isArray(arg) && isNumberNestArray(arg)) {
    return `[Bytes]`;
  }
  
  ...

  - if ('None' in arg) { change to if (typeof arg === 'object' && 'None' in arg) {}
  - if ('Some' in arg) { change to if (typeof arg === 'object' && 'Some' in arg) {}

  ...
}
```

The full code snippet should be:
```
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function isNumberNestArray(arg: any): arg is number[][] {
  return (
    Array.isArray(arg) &&
    arg.every(
      (item) =>
        Array.isArray(item) && item.every((item) => typeof item === 'number')
    )
  );
}

...

function convertCommandArgumentToString(
  arg:
    | string
    | string[]
    | number[][]
    | TransactionArgument
    | TransactionArgument[]
    | MakeMoveVecTransaction['type']
): string | null {
  if (!arg) return null;
  if (typeof arg === 'string') return arg;

  // Case for the PublishTransaction
  if (Array.isArray(arg) && isNumberNestArray(arg)) {
    return `[Bytes]`;
  }

  if (typeof arg === 'object' && 'None' in arg) {
    return null;
  }

  if (typeof arg === 'object' && 'Some' in arg) {
    return arg.Some;
  }

  if (Array.isArray(arg)) {
    return `[${arg
      .map((argVal) => convertCommandArgumentToString(argVal))
      .join(', ')}]`;
  }

  switch (arg.kind) {
    case 'GasCoin':
      return 'GasCoin';
    case 'Input':
      return `Input(${arg.index})`;
    case 'Result':
      return `Result(${arg.index})`;
    case 'NestedResult':
      return `NestedResult(${arg.index}, ${arg.resultIndex})`;
    default:
      // eslint-disable-next-line no-console
      console.warn('Unexpected command argument type.', arg);
      return null;
  }
}
```

**Comment by web3labdao** [comment]
I got the same error and looking for the solution.

**Comment by Jordan-Mysten** [comment]
We recently resolved this and will release an updated wallet soon.
