### ISSUE TITLE
[explorer] Display Move Smart Contracts 

### ISSUE THREAD

**Issue by Andrew47** [MystenLabs/sui#1043]
This issue relates to wiring up the smart contract UI that has been built in the Object Results page to a backend API that delivers smart contract data. This issue is to be met once the backend provides such data.

The README could also detail how a Move Programming Language script might be converted into string data to be displayed.

```js
const fs = require('fs');

const contents = fs.readFileSync('./Example.move', { encoding: 'utf8' }); 

const data = JSON.stringify({ data: contents }); 

fs.writeFileSync('moveExample.json', data);
```

**Comment by sblackshear** [comment]
A note: Move bytecode is what actually gets stored on-chain. In the long run, we may also want to allow users to upload source files (`.move` extension), but I think that should be a secondary priority. There are a lot of things we can do to show the existing bytecode in a human-readable form: e.g., we can show function signatures, type definitions, decompile the code of functions, etc.

**Comment by Andrew47** [comment]
Further aspects to consider from @bwann52: 

* Need for a description of the smart contract: https://github.com/MystenLabs/sui/issues/1199
* See list of NFTs created by smart contract: https://github.com/MystenLabs/sui/issues/1200
* See creator's address of the smart contract: https://github.com/MystenLabs/sui/issues/1198

**Comment by Andrew47** [comment]
@awelc --> Having looked into objects `0x1` and `0x2`, these both have as the owner `SharedImmutable`. This characteristic can be used to identify that the object relates to a library, triggering a distinct UI experience. In terms of how that UI experience works, the below video shows the simplest approach, which would be to place the bytecode in a scrollable box. Are there rules that could be applied to print this text in a more legible fashion?

https://user-images.githubusercontent.com/11377188/161830162-f6986c5c-f8fe-4295-b6d6-f0fb4804de87.mp4

**Comment by awelc** [comment]
> Are there rules that could be applied to print this text in a more legible fashion?

Yes. The Move language has a facility to take the bytecode and disassemble it into source code. It will be a bit different than original source code  as the bytecode does not preserve certain types of source code info (e.g., names of the function parameters are not stored in the bytecode so they will be named differently in the disassembled source code vs original source code).

**Comment by Andrew47** [comment]
@awelc --> We've got buy-in for bytecode to be converted into disassembled source code in the backend and then for this info to be added to the data served by the API for the objects 0x1 and 0x2. I'll start work on creating a UI based on mock data. Could you start putting the backend together, or are there further requirements that need to be met?

**Comment by awelc** [comment]
> @awelc --> We've got buy-in for bytecode to be converted into disassembled source code in the backend and then for this info to be added to the data served by the API for the objects 0x1 and 0x2. I'll start work on creating a UI based on mock data. Could you start putting the backend together, or are there further requirements that need to be met?

I will start looking into it once I am done with my current PR. I don't think there any additional requirements that need to be met, at least I am not aware of any at this point, but this may change after I look at the code.

One question I have is why do we plan to restrict ourselves to objects 0x1 and 0x2 - users will publish source code as well and package objects representing this code will have different ID. We want to display code for these the same way, don't we?

**Comment by awelc** [comment]
@Andrew47 - it seems like at this point we are still debating what to do here exactly, but I think there are some simple things at the UI level that would help even if we don't change the actual data:
-  perhaps instead of current "boxes" that display the whole "content" part of the JSON message, we can display just the key (e.g, "Coin", "Collection") that represents the module name and display the rest on-click in an expanded "box"
- it does not look like end-of-line ("\n") is properly handled when the JSON content is displayed, which results in a more chaotic-looking output than it really should be

**Comment by awelc** [comment]
A bit of additional info on this - it seems like conversion to JSON in `/object_info` is currently broken due to changes in the rest server. In the process of putting it back in, we will likely at least simplify what is being displayed and limit it to function signatures and defined types (tagging @patrickkuo who is the most likely person to work on this).

**Comment by awelc** [comment]
@Andrew47 - it seems like my comment about UI improvements was a bit redundant as you already suggested a solution with a scrollable box, which takes care of my first suggestion. The second one still stands, though - I think that end-of-lines are not handled correctly which does not help legibility of the output.

In terms of how to identify objects representing Move code, I would say that using owner JSON field is not going to work, as may "regular" objects will have the same type of ownership (`SharedImmutable`).

@stella3d provided sample output for JSON the explorer client receives in Slack, and here is the beginning of it:

```json
{"owner":"SharedImmutable","version":"1","id":"0000000000000000000000000000000000000002","readonly":"true","objType":"Unknown Type" ... }
```
Arguably, JSON representation of package objects should not have `Type` field as `Unknow Type` but rather something like `Package Object`, as this information is available in the object itself and can be easily JSON-ified.

@patrickkuo is bringing back JSON encoding of package object contents so hopefully he can take care of this bit as well - this way we'd have an easy way of identifying when we are displaying code and where we are not.

**Comment by Andrew47** [comment]
@awelc --> I've looked into the end-of-line handling issue and found a way to render `\n` that improves the formatting of the code. I've updated the code branch associated with this issue. For convenience, the below video shows the code change in action: 

https://user-images.githubusercontent.com/11377188/163440469-e5ff99ea-ae0a-43f8-894b-8d05c11918d2.mov

 It looks like the next step will be to see what changes are made to the JSON - particularly with the setting of `objType` to `"Package Object"`.

**Comment by awelc** [comment]
> @awelc --> I've looked into the end-of-line handling issue and found a way to render `\n` that improves the formatting of the code. I've updated the code branch associated with this issue.

This looks much, much better!

**Comment by Andrew47** [comment]
I've created a draft PR and rebased the code on the latest main branch. The main remaining blocker left is how the UI knows that an object represents a smart contract. Currently the UI examines the `owner` field and checks if this is equal to `'SharedImmutable'` --> see line 25 of `explorer/client/src/pages/object-result/ObjectLoaded.tsx`.

**Comment by patrickkuo** [comment]
@Andrew47 I will take a look, should be able to add the object type in quite easily

**Comment by 666lcz** [comment]
@Andrew47 @patrickkuo is the backend support for this ready?

**Comment by 666lcz** [comment]
From @patrickkuo : This has been supported in https://github.com/MystenLabs/sui/pull/1556 . @Andrew47 do you see any more blockers?

**Comment by Andrew47** [comment]
This issue is closed by PR https://github.com/MystenLabs/sui/pull/1802
