### ISSUE TITLE
Steps to build sui using clang vs gcc on Fedora due to rocksdb compile issue

### ISSUE THREAD

**Issue by DaveWK** [MystenLabs/sui#10431]
When attempting to build on fedora, the rocksdb compilation steps utilizing gcc fail due to a dependency mismatch. 

In order to work around this, I ended up using clang/clang++ instead of gcc. 

I added the following to my .bashrc and re logged in, and successfully built using `cargo build --release`:
```
export USE_CLANG=1
export RUSTC_LINKER=lld
export RUSTFLAGS="-C linker=clang -C link-arg=-fuse-ld=lld -C link-arg=-lc++ -C link-arg=-lc++abi"
export CXXFLAGS=-stdlib=libc++
export LDFLAGS="-stdlib=libc++"
export CC="clang"
export CXX="clang++"
```

**Comment by chinggg** [comment]
Thanks for the work-around and it works! I hope it can be added to the official document.

**Comment by stefan-mysten** [comment]
@ronny-mysten should we add this to our docs? This seems useful in a section like `Debugging Installation Errors`?
