### ISSUE TITLE
sui_multiGetObjects error: "RPC call failed: Field value link cannot be found in struct"

### ISSUE THREAD

**Issue by gavrushoves** [MystenLabs/sui#10443]
## Steps to Reproduce Issue

1. Get suix_getOwnedObjects by address "0x26cf364a0b2d11b1ca0314ce50c532e852bb64e407cddfebcb5cf82a23675922"

`{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "suix_getOwnedObjects",
    "params": [
        "0x26cf364a0b2d11b1ca0314ce50c532e852bb64e407cddfebcb5cf82a23675922",
        {},
        null,
        null
    ]
}`

2.Collect hashes of owned objects and get their details

`{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "sui_multiGetObjects",
    "params": [
        [
            "0x00016a5fea3e971f39d807719a48c01276ca6e926c5114881af36cd45c6e91d3",
            "0x050d20ff177a95cf3169ad2ff040ade327f280b653a169813c5ec496f26e3182",
            "0x0d8eaa1149e0010a7c78f96bab2a4202d7587d64030eb245994ddb63f5646d6a",
            "0x15d133c83d46628d8ddc4e36b9d90fd04c0277a99b4ff98899acad454d49a4c5",
            "0x2c31ba1940b50d7c9d1d93b2821551f7821118a464c0ea1403668c32c68e78a2",
            "0x3da4539c08b3c0c0c0ad7d7c7f218553e5a013e8c960340dc67bb8be16094da8",
            "0x40df04d0785076cc770a86601ef3a4e81c3463ed39a4ee2cd0685e3b1903be91",
            "0x52c5748f132ae21161ff1265555f322ae7502b2ee12d8b163e085a0cede09b9e",
            "0x5bdc28c5979b53ca7dd112dc448646f88f56e4f7ea5fc9cd1bd091f659a3943f",
            "0x5d0023791ed735c3efe035f303173b6edc287d15eef1ff985b97eac83ffcb39a",
            "0x7bdf37946e1473d5cd4b831c1b391d7a28d90e6731f4f388077aef0c100c27af",
            "0x83d6a4a0792f5d4ce5b8e55a280073e1d0cb1c6b40192f7f6a7d3293583b8b7f",
            "0x8a78bcea32d34fdd748aec29b6881a46362d0fe4b177c065b24e999b634c5baa",
            "0x92791ec22147dd307050d7602f333986032bb59d46e043d11b96a30385429d15",
            "0x92c62b226d273b73b35266397acde0c62c1e5c758569c64ecedcff2a3b32b46f",
            "0x9435a34cd01cc7ddd531c384ef47cd8b091e7f54aa68ec50c112ab0229ef676b",
            "0x9a8cff970e38fa5ecbb1203191d845193c720924cf8117ae6983e236cc258ba1",
            "0x9f8fc530172f82d3f798fbc1bcfea818947b0c193cdfb94010d80da6ffac24ef",
            "0xa02e57abaab00ea5dc2ee1bd4b16401c2680254802b5266723146a81d221feb0",
            "0xa97a7a20ccec59f0c83d27a98e34407e88ad9a1c070a68a1f6b6b3782ec463ff",
            "0xad2490987adb3f3c8063588ce5e0d05877179f7c79a9976abdc63d6e350af9e0",
            "0xb2f68d015c76832d5a25edd9a39c324db9bffb3fcb33f4332398b6c2adb0f84e",
            "0xb7fe3568d7023df5473f0372cb2d3649fe332ec0952595e0359deb8f9277657d",
            "0xb853e46bdbc306ae3a30dc0abb2505c2a23889dd5bd0830dc1b159d2a18b520c",
            "0xc3c8e84c08cdb10827f964af868ceac6c4b373b10eab91d872c969af2bfb2349",
            "0xcb2f192810278b861e1377159c5ee544221905e59fc5b52fb7e3d656be49065f",
            "0xcc0eeaca212d1e1a0145b746ea9da74938d674b310d9101e2f88aa8a241e2345",
            "0xce14c75075cd772daa7cd9cd5f98493bd55a6c920c9054661bec1d2c0f81a0e3",
            "0xd2c51e776377a7e09814a0f49585147b528fa154a0da41f4c1079f4ca430cf0e",
            "0xddc721ddf4adfab18c59e5957f331ddf6e3b6c970a79c597f5d8194b75b759f4",
            "0xdfcd8734a693d386b395244e2cb96ca27d25b2578e7a8e935346d1f714068dd4",
            "0xe2a72498d1f3d831c558c3866cad57c40253960ae311ca249f623731a9f2dc26",
            "0xe3544a15628e13a6657f29b30a96a837f2dc10636d5bf0c290c4d77d18ebfe29",
            "0xf86532c723b131d76980fdcc1b15ddca5a0cf36794dba65b62b3d9d8d965a251",
            "0xf9ce0df3e241cd43f5ac8d2a4927376a080b4abd1dfbb05bbe0d2c031039f9a5"
        ],
        {
            "showType": true,
            "showOwner": true,
            "showPreviousTransaction": true,
            "showDisplay": true,
            "showContent": true,
            "showBcs": false,
            "showStorageRebate": true
        }
    ]
}`
## Expected Result

I`d like the request not to crash, but to return a valid response with the details of the objects, if one of the objects has an error, then this should be shown in its details. Right now we can't show valid user objects as the whole request crashes

## Actual Result

_responce.error.message: "RPC call failed: Field value link cannot be found in struct"_

I got all the objects of this address, then I tried to get each one separately. I found that one of the objects gives the error **_"Field value link cannot be found in struct"_** I have not seen such an error before. Here is the hash of this object **'0xce14c75075cd772daa7cd9cd5f98493bd55a6c920c9054661bec1d2c0f81a0e3'** I think this object breaks **_method: 'sui_multiGetObjects'_** after getting **_method: 'suix_getOwnedObjects'_**. All other objects of this address are valid.

**method: 'suix_getOwnedObjects'**
Does not work if at least one of the objects from the list of objects that we request has such an error. 
## System Information

I got this error in https://explorer.sui.io and from different nodes.

**Comment by healthydeve** [comment]
https://github.com/MystenLabs/sui/pull/10321

This should be fixed in the next update.
