### ISSUE TITLE
Remove sync API from Gateway/REST API

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1045]
Today there is an API in Gateway exposed through REST to sync all objects owned by an address. This will quickly run into issues once we have accounts that own hundreds of thousands of objects. We should start removing it soon.
There are a few blockers to this.
The first being the genesis objects and faucet gas objects. Right now we insert genesis objects directly to the authority store, and use sync to download them. Similarly, with faucet, we also insert the gas objects directly into the authority store, and rely on sync to download them.
We will need to figure out a different way to update the gateway regarding genesis and gas objects.
For genesis objects, there are two ways to go about it:
1. We also insert these objects directly to the gateway. This will become very easy once we are sharing the same store implementation between gateway and authority.
2. We turn every generation of genesis objects into actual transactions. i.e. after the network boot up, a few transactions are sent to generate these genesis objects. This is ideal because then every node in the network can reproduce the object history simply by replaying every transaction in history.

For faucet gas objects, we should certainly be able to do it through transactions. We just need an admin account address that has a lot of gas and can mint gas arbitrarily. However, this will require the batch follower to be properly implemented on the gateway as well so that it can observe the gas objects being sent over.

**Comment by oxade** [comment]
Agreed that this should not be exposed to users, or at least users should not need to call sync.

I think the proper solution is to implement follower in Gateway and we can make sync implicit.
The work being done [here](https://github.com/MystenLabs/sui/issues/729) by @laura-makdah should enable us remove sync.

In the short term, we can try other tricks to ensure data consistency.

**Comment by gdanezis** [comment]
I have a feeling this is related to #297 and #1136 -- ie related to events.
