### ISSUE TITLE
fetch is not defined

### ISSUE THREAD

**Issue by auspicious-one** [MystenLabs/sui#10466]
## Steps to Reproduce Issue

fetch is not defined

/node_modules/@mysten/sui.js/src/rpc/client.ts:71:31
e.g.
1. Call function <getAllBalances><getBalances>.
2. Use return value and call <other function call>.

## System Information

* OS: <ubuntu>
* Compiler: <typescript>

**Comment by auspicious-one** [comment]
/node_modules/@mysten/sui.js/src/rpc/client.ts:71:31
look this, fetch cannot import

**Comment by Jordan-Mysten** [comment]
You either need to use node >= 18 (which defines fetch globally), or polyfill it.
