### ISSUE TITLE
Example 2 in rust-sdk.md is wrong

### ISSUE THREAD

**Issue by liuerfire** [MystenLabs/sui#10471]
https://github.com/MystenLabs/sui/blob/devnet-0.29.0/doc/src/build/rust-sdk.md#example-2---create-and-execute-transaction

The `crypto::{FileBasedKeystore, Keystore}` modules are no longer available in the `crates/sui-sdk`. Instead, the `sui_keys::keystore::{AccountKeystore, FileBasedKeystore, Keystore}` modules should be used. 

Additionally, when signing a transaction, `crates/sui-keys` and `crates/shared-crypto`  are needed, therefore I think they should also be re-exported in sui-sdk.

**Comment by randall-Mysten** [comment]
Thank you @liuerfire Looks like we missed updating a few places after all of the changes in the last few releases. Appreciate you taking time to let us know, cheers!
