### ISSUE TITLE
Investigation on authority network errors 

### ISSUE THREAD

**Issue by arun-koshy** [MystenLabs/sui#1047]
`2022-03-22T20:46:54.428669Z ERROR sui_network::transport: Failed to send query response: Broken pipe (os error 32)`

`2022-03-22T22:50:02.126295Z ERROR sui_network::transport: Failed to send query response: Connection reset by peer (os error 104)`

These [errors](https://github.com/MystenLabs/sui/blob/main/sui_core/src/authority_server.rs#L345) are routinely seen in the the rest server logs, would like to understand what is causing this. Let me know what additional information I can help gather.

**Comment by todd-mystenlabs** [comment]
Convo with @gdanezis :

George:
```
Ok, this means the client/gateway has dropped the connection:
        time::timeout(self.recv_timeout, async {
            stream.read_data().await.transpose()
        })
Which I think is now configured to happen within 4 seconds of sending a request:
recv_timeout: Duration::from_micros(4000000),
So now the question is: does that happen because the server is too slow to answer? Or because the client is to slow to handle them?

This is the client/gateway <-> authority link.
```

Todd:
```
Okay. 4 seconds is an awful long time for intra-compute-node communication. Let me find out what class of AWS machine it’s running on.
(Might be a .tiny or something)
```

@adeabiodun / @arun-koshy - what class of compute node is the rest server running on?

**Comment by adeabiodun** [comment]
I didn’t set any of this up. Check with Ade

**Comment by gdanezis** [comment]
My current theory is that these are either:
(1) Caused by the receiver client timeout of 4 seconds, or
(2) Caused by the authority aggregator logic that waits on 2f+1 authorities, and then waits for a short time after that only. However we seem to be waiting for 10 to 60 secs on these.

**Comment by todd-mystenlabs** [comment]
Seems like this is going to dove-tail into improvement of our networking stack capabilities.
