### ISSUE TITLE
Sui ts sdk documentation sample error, request fix

### ISSUE THREAD

**Issue by wenre** [MystenLabs/sui#10524]
https://github.com/MystenLabs/sui/tree/main/sdk/typescript#move-call

![image](https://user-images.githubusercontent.com/13760469/230570368-a4d323d0-6e15-43ac-a06c-a228fc7e1242.png)

split coins second arg is an array no obj.

example is wrong

**Comment by stefan-mysten** [comment]
Thanks for flagging this @wenre. The example has been rewritten now, and I've also double checked that the example that calls `splitCoins` does pass correctly an array.
