### ISSUE TITLE
balance changes are not balanced in json rpc result

### ISSUE THREAD

**Issue by eerun101** [MystenLabs/sui#10529]
take this as an example:

```
curl --location 'https://wallet-rpc.testnet.sui.io/' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "sui_getTransactionBlock",
    "params": [
        "Gd4CvyUK57backuDmwZg2WL3cSk4iPAzr67s7kYR1qGD",
        {
            "showInput": true,
            "showRawInput": false,
            "showEffects": true,
            "showEvents": true,
            "showObjectChanges": false,
            "showBalanceChanges": true
        }
    ]
}'|jq
```

we can see that `gasUsed` shows:

```
      "gasUsed": {
        "computationCost": "1000000",
        "storageCost": "125",
        "storageRebate": "103",
        "nonRefundableStorageFee": "0"
      },
```

which means gas cost is `1000000 + 125 - 103` = `1000022`, but in `balanceChanges` section we see:

```
    "balanceChanges": [
      {
        "owner": {
          "AddressOwner": "0x51cdbd0e2ec2bf5a83234cc5b1710095fe39ff1ef59256868e117f8f912667fe"
        },
        "coinType": "0x2::sui::SUI",
        "amount": "-4501000023"
      },
      {
        "owner": {
          "AddressOwner": "0xdeda6fbdeab63874e720ea3258f9f6220055a63a4055439c70137c576aa086cd"
        },
        "coinType": "0x2::sui::SUI",
        "amount": "4500000000"
      }
    ],
```

but `-4501000023 + 1000022 + 4500000000` is `-1` not `0`, i guess `0` should be the right number here.

or where did this `1` come from?

**Comment by sblackshear** [comment]
Thanks for this report!!

There was a known bug in Sui protocol version 2 that caused an inconsistency between `balanceChanges` and `gasUsed` related to how each calculates `nonRefundableStorageFee`. Earlier today, the on-chain upgrade to version 3 (which contains a fix for this issue) went through. After this happened, I tried calling the same function as your original transaction and everything adds up: https://suiscan.xyz/testnet/tx/AcesWrDnBeBEc9avtWV3GHgGJokTB7ixPovwydzFsp5c. There are no longer any known inconsistencies, but please don't hesitate to report anything that doesn't look right to you.
