### ISSUE TITLE
Problem with @mysten/wallet-standard

### ISSUE THREAD

**Issue by Pawel-Szydlo** [MystenLabs/sui#10531]
I have created a class that implements Wallet with wallet-standard.
In addition, the class has its private fields for example _nightlyEventsMap , metadata. 

![image](https://user-images.githubusercontent.com/89639506/230600554-a296757a-d691-4fc0-bdc5-b1baa1ea48cd.png)

It then registers the wallet using the registerWallet() function.

![image](https://user-images.githubusercontent.com/89639506/230601558-2a5f65e2-e939-45ba-a2d3-aac892e913ba.png)

when I call the connect function using wallet-kit, I have instances of the class but only with connect and version.
Why is there no signAndExecuteTransactionBlock etc. here?
Could someone explain how registerWallet works and why my class instance is overridden?

**Comment by Jordan-Mysten** [comment]
Where are you seeing this object logged?

**Comment by Jordan-Mysten** [comment]
Ah I see what you mean. This `this` value will be the feature definition in the `features` object. If you want to use the `this` value of the class instance, you can use a class property instead of a method:

```
connect: StandardConnectMethod = () => {
    // Your wallet's connect implementation
};
```

**Comment by Pawel-Szydlo** [comment]
Thank you for your help
