### ISSUE TITLE
sui test wallet error notstaking 

### ISSUE THREAD

**Issue by Starlew77** [MystenLabs/sui#10548]
i tried staking with another porvider but i got this error message 
![20230407_204247](https://user-images.githubusercontent.com/116558527/230671275-5d01eae3-bd2f-4d29-b4bf-ef8bbdf195a0.jpg)

then wallet went blank and i had to reinstall twice waleet taking 5-10mins to load aswell
![20230407_205300](https://user-images.githubusercontent.com/116558527/230671328-5970442d-def3-4641-bf4b-b5ccf3bc1f6b.jpg)
aand now i cant stake anymore get this error message 
![20230407_205849](https://user-images.githubusercontent.com/116558527/230671480-b8ef00d4-d9fa-4711-bbb0-a23717358660.jpg)

how many people can you stake with is this causing issue because i have done a few i thought you could stake with loads

**Comment by stefan-mysten** [comment]
@Starlew77 thanks for flagging this. By now probably this has been fixed, so I will close it for now. Feel free to file a new issue if you encounter any problems.
