### ISSUE TITLE
how to transfer sui with rust when i have only one object

### ISSUE THREAD

**Issue by polariseye** [MystenLabs/sui#10566]
hello.
 i have not found the doc or example to transfer object when i only have one object. could you give me some code. such as this address 0x0d7a86dd4d05813873a29d7b4b305af70b14112524fdd0cb63f3bceddd4a696b

**Comment by randall-Mysten** [comment]
To transfer a single object you can use the Sui Client CLI: https://docs.sui.io/devnet/build/cli-client#transfer-objects

**Comment by polariseye** [comment]
i have resolved . thanks
