### ISSUE TITLE
Sui Code Bug or Feature Request for sui keytool

### ISSUE THREAD

**Issue by Staking7pc** [MystenLabs/sui#10595]
`SUi keytool generate ed25519` generates a address and outputs  Base64 encoded of 33-byte `flag || privkey` for keyscheme ed25519.

Request for a feature to get the mnemonics of the address from the  Base64 encoded of 33-byte `flag || privkey`  value to be abe to import the address into wallets.

**Comment by amanjui45** [comment]
> `SUi keytool generate ed25519` generates a address and outputs Base64 encoded of 33-byte `flag || privkey` for keyscheme ed25519.
> 
> Request for a feature to get the mnemonics of the address from the Base64 encoded of 33-byte `flag || privkey` value to be abe to import the address into wallets.

**Comment by kchalkias** [comment]
cc @joyqvq per your recent PR

**Comment by joyqvq** [comment]
https://github.com/MystenLabs/sui/pull/11699 this is landed to show the mnemonics when using keytool generate on new generated private keys. mnemonics cannot be derived for exisiting private keys
