### ISSUE TITLE
Sui doc content issue or request

### ISSUE THREAD

**Issue by Mathman14** [MystenLabs/sui#10622]
my sui wallet seems to be taking long to load up and even token balance disappear hope you guys could help with that’s am on permanent testnet already and the wallet is not loading the token balance even taking time to load up 

Thank you for taking the time to let us know about the issue or request. We triage all new issues and requests within 2 business days. We will follow up if we need additional information.

**Comment by randall-Mysten** [comment]
Sorry @Mathman14 The network is indeed slow currently, they are literally working on it around the clock to resolve.
