### ISSUE TITLE
Wallet dont show balances, and dont running well.

### ISSUE THREAD

**Issue by abourassimon** [MystenLabs/sui#10686]
Hello, due to the difficulties we are experiencing in the wallet, I wanted to report the following:the wallet does not show the balances correctly although I have already claimed twice, when clicking on the NFTs function it shows an error and also when clicking on the ACTIVITY function it shows error 503.
![IMG_20230410_175811](https://user-images.githubusercontent.com/130408729/231007075-12518896-5f67-4f42-8dda-5d013a7a47b8.jpg)
![IMG_20230410_175835](https://user-images.githubusercontent.com/130408729/231007110-0ce90880-f3d1-44a6-a0be-8d002b50c941.jpg)
![IMG_20230410_175851](https://user-images.githubusercontent.com/130408729/231007161-1c4492b4-a8d3-42d8-8738-a00e5464aee5.jpg)

**Comment by stefan-mysten** [comment]
The wallet received many improvements since April, so closing the issue for now. @abourassimon feel free to create a fresh issue if you encounter any problems with the Wallet.
