### ISSUE TITLE
Sui doc content issue or request

### ISSUE THREAD

**Issue by SAP2468** [MystenLabs/sui#10753]
Thing 1.Suit wallet dapps such as Turbos, movex, are not connecting with wallets when try to connect both apps redirect it to Google extension page for remove extension already installed, 

2. NFTs minted are not shown in dapps for creating collections or for listing

**Comment by stefan-mysten** [comment]
Thanks for flagging this @SAP2468. A lot of things have happened since April, so I would assume most of these things have been fixed by now. Feel free to file a new issue if you're still encountering problems.
