### ISSUE TITLE
Interactive shell crashes when trying to query an account address with 'object' command

### ISSUE THREAD

**Issue by chinesco** [MystenLabs/sui#1078]
## Steps to Reproduce Issue
Create an account:
```
sui>-$ new-address
Created new keypair for address : E0AF5099B793FD54273D54F3BA277CA166F55C02
```
Verify it is created and has no objects
```
sui>-$ objects --address E0AF5099B793FD54273D54F3BA277CA166F55C02
Showing 0 results.
```
Call the object command on the address ID
```
sui>-$ object --id E0AF5099B793FD54273D54F3BA277CA166F55C02
thread 'main' panicked at 'a formatting trait implementation returned an error: Error', library/alloc/src/fmt.rs:597:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Expected Result
Although the ```object``` command expects an object ID instead of an address, it should not crash the terminal.

```object``` command should handled the wrong parameter gracefully, return a meaningful error and not kill the shell

## Actual Result

Shell crashes with message 
```
thread 'main' panicked at 'a formatting trait implementation returned an error: Error', library/alloc/src/fmt.rs:597:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

## System Information

* OS: MacOS 12.3
* Compiler: sui local 0.1.0

**Comment by patrickkuo** [comment]
Hi @chinesco, welcome to Sui!

This issue will be fixed by [PR 1082](https://github.com/MystenLabs/sui/pull/1082)

Many thanks for the bug report!
