### ISSUE TITLE
Sui Wallet BUG

### ISSUE THREAD

**Issue by 1000layla** [MystenLabs/sui#10795]
Sync Bug in SUI Wallet  - NOT working anymore all tokens and NFTs etc gone

Sync error (data might be outdated)
Error fetching owned object: Error: RPC Error: Method not found for address 0x24e100f1b948085ced743001ca58eea90a4f88c5

**Comment by iber3509** [comment]
{"stack":"Error: Transaction failed with the following error. RPC Error\n    at chrome-extension://opcgpfmipidbgpenhmajoajpbobppdil/dapp-interface.js:2:265289\n    at chrome-extension://opcgpfmipidbgpenhmajoajpbobppdil/dapp-interface.js:2:263438\n    at a._next (chrome-extension://opcgpfmipidbgpenhmajoajpbobppdil/dapp-interface.js:2:262746)\n    at e.next (chrome-extension://opcgpfmipidbgpenhmajoajpbobppdil/dapp-interface.js:2:260811)\n    at chrome-extension://opcgpfmipidbgpenhmajoajpbobppdil/dapp-interface.js:2:265205\n    at a._next (chrome-extension://opcgpfmipidbgpenhmajoajpbobppdil/dapp-interface.js:2:262746)\n    at e.next (chrome-extension://opcgpfmipidbgpenhmajoajpbobppdil/dapp-interface.js:2:260811)\n    at chrome-extension://opcgpfmipidbgpenhmajoajpbobppdil/dapp-interface.js:2:263431\n    at a._next (chrome-extension://opcgpfmipidbgpenhmajoajpbobppdil/dapp-interface.js:2:262746)\n    at e.next (chrome-extension://opcgpfmipidbgpenhmajoajpbobppdil/dapp-interface.js:2:260811)","message":"Transaction failed with the following error. RPC Error"} bu mesajı alıyorum

**Comment by stefan-mysten** [comment]
This has probably been fixed by now as the Sui Wallet has gone through several improvements, so will close this. Feel free to file a new issue @1000layla  if you encounter any issues.
