### ISSUE TITLE
Is it reasonable to use BigInt instead of uint64 for all cases? (#10129)

### ISSUE THREAD

**Issue by Gkirito** [MystenLabs/sui#10802]
## Steps to Reproduce Issue

Fill this in with the concrete steps needed to reproduce the bug. When providing code in the reproduction steps, use the smallest snippet of code that demonstrates the issue, removing any extraneous details.

Use sui new testnet version for json-rpc server

## Expected Result

Specify what outcome you expected should have resulted, but didn't.

## Actual Result

Specify what the actual unexpected outcome was.

## System Information

* OS: <specify OS version>
* Compiler: <specify compiler version>

I have more questions about this PR #10129 
Ex. 
In this [code block](https://github.com/MystenLabs/sui/blob/defb2ab6f9f24a690919e84ddebb419327687cb2/crates/sui-json-rpc-types/src/sui_move.rs#L290-L304) change `u64` to `BigInt`. 
Then If my move contract has this struct 
``` move
    struct TestStruct has key, store {
        id: UID,
        profile: vector<u8>,
        owner: address
    }
```
the field `profile`'s type is `vector<u8>`, the json-rpc server will return the data like this normally 
``` json
"fields": {
          "id": {
            "id": "0x30484cae408a610b0db774ec4f323af0accf6e55abf607ae816d0f2e9285d444"
          },
          "owner": "0x3b79d34f887baf8c0dc4a48c727b2e7d4b7456796a4ed39f4b17c629dc0f19f3",
          "profile": [
            123,
            34,
            110,
            97,
            109,
            101,
            34,
            58,
            34,
            67,
            104
          ]
        }
```
But it will return like this after having this [code](https://github.com/MystenLabs/sui/blob/defb2ab6f9f24a690919e84ddebb419327687cb2/crates/sui-json-rpc-types/src/sui_move.rs#L290-L304)
``` json
"fields": {
          "id": {
            "id": "0x30484cae408a610b0db774ec4f323af0accf6e55abf607ae816d0f2e9285d444"
          },
          "owner": "0x3b79d34f887baf8c0dc4a48c727b2e7d4b7456796a4ed39f4b17c629dc0f19f3",
          "profile": [
            "123",
            "34",
            "110",
            "97",
            "109",
            "101",
            "34",
            "58",
            "34",
            "67",
            "104"
          ]
        }
```
If I want to decode this `profile` field, I need to convert all `string` to `uint8` 

Did you run enough tests before merging Pull Request #10129?

**Comment by Gkirito** [comment]
CC: @patrickkuo

**Comment by patrickkuo** [comment]
Thanks for reporting this! 

Looking at the code, SuiJsonValue is converting all u64 to string already, so changing Number serialisation to BigInt is not necessary, I will add a test for this case and push out a fix.

Apology for introducing this bug.
