### ISSUE TITLE
[TS SDK] SuiObjectData bcs field type is wrong

### ISSUE THREAD

**Issue by kklas** [MystenLabs/sui#10809]
## Steps to Reproduce Issue

```
const res = provider.getObject({
  '<id>',
  options: { showBcs: true }
})

console.log(res.data!.bcs.bcsBytes))
```

The `bcs` field (`SuiRawData`) of the response (`SuiObjectData`) is of the wrong type:
![image](https://user-images.githubusercontent.com/7824233/231480467-1dd5403a-1a3a-4f14-a7ae-33a2c9e8d589.png)

while the RPC response returns a different set of fields:

![image](https://user-images.githubusercontent.com/7824233/231480600-87de7bf6-e0ba-4f1f-92ee-c29afd49c216.png)

This causes an error on `getObject` call: ` StructError: At path: data.bcs -- Expected the value to satisfy a union of 'object | object', but received: [object Object]`
And also causes typescript type errors when trying to access those fields.

Version: `@mysten/sui.js v0.32.1`, `sui v0.31.0`

**Comment by stefan-mysten** [comment]
Given that the TS SDK received a major revision, I assume this has been fixed. Closing the issue for now.
