### ISSUE TITLE
[TS SDK] SuiObjectResponseError type doesn't match the RPC response

### ISSUE THREAD

**Issue by kklas** [MystenLabs/sui#10810]
[`SuiObjectResponseError` ](https://github.com/MystenLabs/sui/blob/fc346addd9aa3f2db8fb32fdca9d766cacb50420/sdk/typescript/src/types/objects.ts#L114-L120) type doesn't match the [RPC response](https://github.com/MystenLabs/sui/blob/fc346addd9aa3f2db8fb32fdca9d766cacb50420/crates/sui-types/src/error.rs#L202-L223) (it's missing the `code` field for example).

**Comment by hayes-mysten** [comment]
This should be fixed now, the types for SuiClient are now generated from the open-rpc spec so they should more accurately represent the actual data
