### ISSUE TITLE
*new* error when staking 

### ISSUE THREAD

**Issue by Starlew77** [MystenLabs/sui#10865]
Hi 
I am getting this error message no matter what value i put in for staking within my avaliable balance , its happining with each validator i try  and keep getting same error message :)

![20230413_103913](https://user-images.githubusercontent.com/116558527/231720667-eab8934b-934a-4456-9200-8dc4f30244d3.jpg)
![20230413_103556](https://user-images.githubusercontent.com/116558527/231720677-1cdf563c-2ad9-4d63-80ae-db634931dc50.jpg)
![20230413_103300](https://user-images.githubusercontent.com/116558527/231720705-b8529603-ef9e-4382-ac3d-f82648d28e59.jpg)

**Comment by randall-Mysten** [comment]
Might be an issue with the network, but do you have more balance in the wallet than the amount staked plus gas fees? I am able to stake with multiple different validators using Testnet. You must also stake at least 1.0 SUI per stake.

**Comment by Starlew77** [comment]
Yes I tried 2 and had balance of 3,  but also when requesting testnet
tokens error message coming up aswell

**Comment by stefan-mysten** [comment]
@Starlew77 I assume this is working by now, so I will close the issue. Feel free to create a fresh issue if you're still encountering problems.
