### ISSUE TITLE
How should the front-end activate the suiWallet by means of js?

### ISSUE THREAD

**Issue by e274426380** [MystenLabs/sui#10897]
I’m a Vue developer and can’t use React related components.
Before the update, I was able to call out the suiWallet plugin in my browser using `window.suiWallet`, but now it doesn’t work.
Can you tell me what to do now?
It would be good to tell me again where I can see the change in the suiWallet interface.

**Comment by randall-Mysten** [comment]
The wallet kit is here: https://sui-wallet-kit.vercel.app/
Wallet source code is here: https://github.com/MystenLabs/sui/tree/main/apps/wallet

**Comment by e274426380** [comment]
> The wallet kit is here: https://sui-wallet-kit.vercel.app/ Wallet source code is here: https://github.com/MystenLabs/sui/tree/main/apps/wallet

Sorry, but wallet kit is a component of react.
Maybe I'm too new to find out from https://github.com/MystenLabs/sui/tree/main/apps/wallet to find the answer to this.
I just want to know how I can use suiWallet in my project by way of javascript.
Before that I usually used window.suiWallet, but for some reason it doesn't work now

**Comment by randall-Mysten** [comment]
@Jordan-Mysten Any info you can provide here?
