### ISSUE TITLE
Sui  Bug, Staking, Reqest tokens, ethos game 

### ISSUE THREAD

**Issue by Starlew77** [MystenLabs/sui#10899]
Hello 

Error report when requesing  test net tokens unable to stakle on any valdator same error as reported yesterday via docs

Ethos game took 10 mins loading without actually loading 

After a couple of attempts entered game to play game for everymove you make its now takes a transaction fee for each move , is this correct as before you only paid fees for minting , now everymove costs money and is a transaction
![20230414_125114](https://user-images.githubusercontent.com/116558527/232037571-26c072b0-1e65-4e49-9386-13ed7f143de7.jpg)
![20230414_125245](https://user-images.githubusercontent.com/116558527/232037591-f44b4552-22ce-4087-8b4f-b8882b0cfcf5.jpg)

**Comment by Jordan-Mysten** [comment]
You can report any issues with the ethos game to that team, we do not maintain that project

**Comment by Starlew77** [comment]
Hi Jordan

But it's on your network for testing and  surely if new customers use it
thet will think its to do with your network as is taking fees on every move
that will affect your future customers as alot of people will think its to
do with you , its a bug as it never did it before  , I'm just making you
aware  sorry if I am wrong but just trying to help 👍

Kind regards

Steve
