### ISSUE TITLE
Sui doc content issue or request

### ISSUE THREAD

**Issue by ZitroLeugim18** [MystenLabs/sui#10936]
If this is an issue with existing content, provide the URL or GitHub path to the topic. Otherwise, use **New**.

We need more information of how we can become a earlier supporters, there are many people that doesn´t have experience in crypto therefore is importan inclued something related with this aspect in the docs, so many people will know what is the correct form to be part of the project, however good job

**Comment by stefan-mysten** [comment]
Good suggestion @ZitroLeugim18, thank you!
