### ISSUE TITLE
Sui cannot publish

### ISSUE THREAD

**Issue by eliomain** [MystenLabs/sui#10943]
sui client publish --gas-budget 10000

console:
Could not read a dependency's on-chain object: RpcError(ParseError(Error("invalid type: string "1", expected u64", line: 1, column: 102)))

**Comment by eliomain** [comment]
[warn] Client/Server api version mismatch, client api version : 0.29.1, server api version : 0.31.0
UPDATING GIT DEPENDENCY https://github.com/MystenLabs/sui.git
INCLUDING DEPENDENCY Sui
INCLUDING DEPENDENCY MoveStdlib
BUILDING my_first_package
Could not read a dependency's on-chain object: RpcError(ParseError(Error("invalid type: string \"1\", expected u64", line: 1, column: 102)))

**Comment by threewebcode** [comment]
Your version is not correct so that the data type is not matched.
