### ISSUE TITLE
[TS SDK] getDynamicFieldObject failed

### ISSUE THREAD

**Issue by xiegudong45** [MystenLabs/sui#10950]
## Steps to Reproduce Issue

I'm trying to use getDynamicFieldObject func to get actual data which stored in a dynamic object. The code continued to run successfully until today. I tried both devnet  & testnet, but it didn't work.

Here's my code: 
![image](https://user-images.githubusercontent.com/30063330/232250457-b4d6e88e-cae1-4eab-9fdd-99da09798794.png)

And here's the error: 
![image](https://user-images.githubusercontent.com/30063330/232250472-9a939e94-4432-4c6a-abb9-ca452ea3b803.png)

The @mysten/sui.js version is: @0.32.1
Develop Environment: Macbook Pro late2022 w/ M1 Pro, OS: 13.3.1。NodeJS：18.12.1

**Comment by stefan-mysten** [comment]
I assume this has been fixed since April, so I will close the issue for now. @xiegudong45 Feel free to create a fresh issue if you encounter any problems. Thanks.
