### ISSUE TITLE
Sui wallet loading error 

### ISSUE THREAD

**Issue by Starlew77** [MystenLabs/sui#10972]
Hi 

When loading sui wallet its taking between  5 minutes to 10 minutes to load wallet a first i have just a blank wallet but after time does load but i get an eror message that flashes up then vanishes saying wallet error 

i staked on a number of validators, does this affect the wallets loading features ?

Also with sui apps transactions processing but not completing on a number 0f the apps :) but completing on some after  about a number of minutes
but then loads blank wallet 

![20230417_102643](https://user-images.githubusercontent.com/116558527/232445783-e0117fd3-04d3-46cf-b9c6-82c881f35c84.jpg)
![20230417_102
![20230417_102807](https://user-images.githubusercontent.com/116558527/232445824-08204ca6-b09a-4985-9bf5-34b5d8e7abaf.jpg)
519](https://user-images.githubusercontent.com/116558527/232445804-6ac768b7-8860-48bc-a2aa-1b4437281295.jpg)

**Comment by threewebcode** [comment]
It would be more convenient if you open developer console in your browser and provide some network and error information.

**Comment by Starlew77** [comment]
How do I do that please 🙏

I Been screenshotting all errors so you have a visual of the problems 👍

Kind regards

Steve
