### ISSUE TITLE
Develop diagrams depicting common flows

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#1102]
See the steps in:
https://github.com/MystenLabs/sui/blob/main/doc/src/learn/how-sui-works.md#common-transactions
https://github.com/MystenLabs/sui/blob/main/doc/src/learn/how-sui-works.md#support-for-complex-contracts

**Comment by Clay-Mysten** [comment]
Adding the team for guidance and review once I'm underway.

**Comment by Clay-Mysten** [comment]
I'm noting @huitseeker has a related request in:
https://github.com/MystenLabs/narwhal/issues/179#issuecomment-1111009722

I will try to make time for this work soon.

**Comment by huitseeker** [comment]
@Clay-Mysten This is not urgent, as the new components are not productionized yet, and the diagram update is a task perhaps best left to their authors.

**Comment by Clay-Mysten** [comment]
Thank you, @huitseeker! That is a relief to hear, my friend. Just wrapped up a bunch of intranet work in:
https://github.com/MystenLabs/Prose/issues/15

And the issues it references. Now turning back to the white paper:
https://github.com/MystenLabs/sui/issues/1368

Review of the Narwhal Benchmark remote tests now that I have AWS set up:
https://github.com/MystenLabs/Prose/issues/12

And then refactoring the Learn and Build sections:
https://github.com/MystenLabs/sui/issues/1363
https://github.com/MystenLabs/sui/issues/1362

Re-triaging accordingly. Thanks again!

**Comment by Clay-Mysten** [comment]
I'm adding Evan as I caught some incredibly useful diagrams in his presentation on storage today in our Blockchain Workshop. Evan, please point me to that ReactJS preso. :-)

**Comment by Clay-Mysten** [comment]
Let's consider some of the text too. Can file a distinct issue for that (storage docs) if Evan agrees. Thanks!

**Comment by Clay-Mysten** [comment]
Also asking Ade for guidance. He notes we should avoid diagrams that show an object going into multiple TXes with the same version as confusing.

**Comment by Clay-Mysten** [comment]
I'm noting Evan has cleansed diagrams found at:
https://app.golinks.io/sui-storage

**Comment by Clay-Mysten** [comment]
Hi team,

I finally got a chance to extract Evan's diagrams to a Markdown file for previewing and evaluation for our docs:
https://github.com/MystenLabs/Prose/blob/main/object-diagrams.md

Please take a look and let me know what you think. Thanks!

**Comment by Clay-Mysten** [comment]
Adding @lxfind and @awelc to evaluate the diagrams above for inclusion in our docs.

**Comment by velvia** [comment]
Hey @Clay-Mysten ... I would definitely get rid of the "Hot Data vs Cold Data" one... that was just my idea.   The others....  are mostly OK, though I guess the one that drew box around objects as a checkpoint, might be misleading, but I'm not sure how to correct it.  Basically a checkpoint is really all the transactions, but there's no way to draw a box around just the transactions.

**Comment by Clay-Mysten** [comment]
Thanks @velvia! I have removed the "Hot Data vs Cold Data" diagram. All, WDYT of the rest?

**Comment by Clay-Mysten** [comment]
Adding Koh, Jen and Bauer for their thoughts on these diagrams:
https://github.com/MystenLabs/Prose/blob/main/object-diagrams.md

**Comment by Clay-Mysten** [comment]
Team, is there any appetite for these diagrams or some versions of them? I've added @randall-Mysten in case he wants to pursue them.

**Comment by Clay-Mysten** [comment]
Moving back to a TODO state while we evaluate these diagrams.

**Comment by Clay-Mysten** [comment]
Per Xun, we can flip the checkpoint locations to be the transactions rather than objects in:
https://github.com/MystenLabs/Prose/blob/main/object-diagrams.md#checkpoints

**Comment by randall-Mysten** [comment]
Closing this general issue. Will address images per topic as content we make updates
