### ISSUE TITLE
Sui Code Bug or Feature Request

### ISSUE THREAD

**Issue by swift-mx** [MystenLabs/sui#11031]
## Steps to Reproduce Issue

![image](https://user-images.githubusercontent.com/80231732/232750081-0622a5c0-c9a1-46ff-866f-5d4984dfa79c.png)

## Expected Result

Expected <other function call> to return success result.

## Actual Result

![image](https://user-images.githubusercontent.com/80231732/232753301-32a7adf7-3a62-4520-806f-96798a52d3a4.png)

## System Information

* OS: <specify OS version>
* Compiler: <specify compiler version>

**Comment by samlaf** [comment]
@kchalkias why was this closed? I’m still seeing the same error.

seems to come from https://github.com/MystenLabs/sui/blob/c70453ed0d63653dc158634fd4ed1558b28f0ab4/crates/sui-core/src/authority.rs#L2954

**Comment by FrankC01** [comment]
Ditto, tried in 1.0.0, 1.1.0 and 1.2.0

**Comment by nathanramli** [comment]
it seems like this feature hasn't been supported
do you happen to have any updates?
