### ISSUE TITLE
How to call sui's nft contract through python

### ISSUE THREAD

**Issue by calvin-yang** [MystenLabs/sui#11067]
How to call sui's nft contract through python

**Comment by zhenfeng-zhu** [comment]
Now sui doesn't provide official python sdk.

**Comment by FrankC01** [comment]
Take a look at [pysui](https://github.com/FrankC01/pysui)

**Comment by ooeooo** [comment]
> Why not provide a Python SDK?

**Comment by ooeooo** [comment]
> They just released a TS SDK. Python may be in the works, but there is PySui available as mentioned above.

But using a third-party one carries risks, as it involves private key operations. So I hope there can be an official version of the Python SDK, which can reassure developers with such concerns.

**Comment by FrankC01** [comment]
@ooeooo `pysui` does not use private keys unless you want to do so.

**Comment by ooeooo** [comment]
> @ooeooo `pysui` does not use private keys unless you want to do so.

Thank you!
