### ISSUE TITLE
TS SDK: How to split coins correctly?

### ISSUE THREAD

**Issue by ThreeAndTwo** [MystenLabs/sui#11074]
// Error: The following input objects are not invalid: 0x3859ce88cdd4dbfc4be4ec04a85e024f0000c5eb5a27b66dfcfa741e7f34c1a3

       const signer = new RawSigner(account, provider);
        const tx = new TransactionBlock();
        const splitUSDT = tx.splitCoins(
            tx.object('0x3859ce88cdd4dbfc4be4ec04a85e024f0000c5eb5a27b66dfcfa741e7f34c1a3'),
            [tx.pure(amount)])

        tx.transferObjects(
            [splitUSDT],
            tx.pure(receipter),
        );

        const result = await signer.signAndExecuteTransactionBlock({
            transactionBlock: tx,
            options: {
                showEffects: true,
                showObjectChanges: true,
            },
        });

**Comment by wlmyng** [comment]
Closing as this is not really a doc issue, and as linked above we do have docs demonstrating how to use the ts sdk for building transactions like splitting coins.

**Comment by OlexBeatable** [comment]
In the docs there is demonstrated only how to split gas coins, but no single example how to work with other coins
