### ISSUE TITLE
[Document] Draft a table comparing serialization frameworks

### ISSUE THREAD

**Issue by bholc646** [MystenLabs/sui#1108]
Ideally listing the major pros/cons/features etc. of each serialization framework. The idea is we will add an additional format to our existing REST API offering, not replace it. This doc will be used to make a decision in the next week or so.
- Doc will focus on JSON RPC, gRPC, websockets, and any other suggestions people have

**Comment by arun-koshy** [comment]
@666lcz added some documentation around [REST vs RPC](https://www.notion.so/mystenlabs/RFC-REST-v-s-RPC-5c680cc0a5cd41379f8a8c2b50dfd195?d=a3b75a38250648a88a0e77f45405651f#eac48985888d48fe81527dcd2f54423c) and explored some of the benefits of JSON RPC & gRPC. Just wanted to track that here as well
