### ISSUE TITLE
[Wallet] Add support for returning values from Move calls to the Wallet

### ISSUE THREAD

**Issue by awelc** [MystenLabs/sui#1112]
We have recently added support for returning values from Move calls (#784) but did not integrate it at the user-level. This task it to track adding this support to the Wallet.

**Comment by gdanezis** [comment]
How is this going? Are we still not having this feature?

**Comment by awelc** [comment]
The original implementation of the entry functions returning values has been reverted as it wasn't quit general enough but more importantly it was deemed somewhat superfluous with respect to the event mechanism.

**Comment by gdanezis** [comment]
ok, closing!
