### ISSUE TITLE
[REST API] Add support for returning values from Move calls to REST API

### ISSUE THREAD

**Issue by awelc** [MystenLabs/sui#1113]
We have recently added support for returning values from Move calls (#784) but did not integrate it at the user-level. This task it to track adding this support to the REST API.

**Comment by 666lcz** [comment]
@awelc In https://docs.sui.io/build/move#move-functions, it still says 

```
In general, an entry function, must satisfy the following properties:

- have no return value

```

Should we update that?

**Comment by awelc** [comment]
> @awelc In https://docs.sui.io/build/move#move-functions, it still says
> 
> ```
> In general, an entry function, must satisfy the following properties:
> 
> - have no return value
> ```
> 
> Should we update that?

We should once user-facing changes are in. Otherwise it would be confusing - docs would say one thing and the user experience would be another thing.
