### ISSUE TITLE
deepbook event

### ISSUE THREAD

**Issue by honeywest** [MystenLabs/sui#11170]
Would it be better to change OrderFilled to OrderMatch?
add OrderDone Event.
https://github.com/MystenLabs/sui/blob/b7adb0735895f2a429527e180d348ba971cb97e6/crates/sui-framework/packages/deepbook/sources/clob.move#L116-L130

**Comment by 0xaslan** [comment]
Fill is a common term in trading, I believe it is appropriately named.
