### ISSUE TITLE
deepbook lot_size error in func match_bid_with_quote_quantity

### ISSUE THREAD

**Issue by honeywest** [MystenLabs/sui#11189]
lot_size has no effect in func match_bid_with_quote_quantity
optimize:
add code
 filled_base_quantity = filled_base_quantity - (filled_base_quantity % lot_size)
and add another condition to end the loop
https://github.com/MystenLabs/sui/blob/021a40dc2536fa7698b9faecbad86d3278869d43/crates/sui-framework/packages/deepbook/sources/clob.move#L377

**Comment by honeywest** [comment]
@sblackshear see

**Comment by stefan-mysten** [comment]
@0xaslan @leecchh I assume this is not relevant anymore, but wanted to flag it anyway! If it's all good, we can close the issue. Thanks!

**Comment by 0xaslan** [comment]
Thanks @stefan-mysten , yes this is not relevant anymore. Closing the issue. All new changes will be shipped with DeepBook v3.
