### ISSUE TITLE
[Feature Request] Multiple simulate a transaction

### ISSUE THREAD

**Issue by JackyWYX** [MystenLabs/sui#11246]
## Description

Currently, the transaction simulation with dry run can be only executed once. The second run of the simulation will report an error:

```
The transaction inputs contain duplicated ObjectRef's
```

However, it's quite common for user to simulate the same transaction twice, and it's possible that the two simulation will yield different results at certain time. 

### Requested change

Allow multiple transaction simulation.

**Comment by Linhnef** [comment]
@JackyWYX  are u fixed it? I get the same error.

**Comment by reinisb123** [comment]
guys did you find the solution?
