### ISSUE TITLE
Can't get coin metadata

### ISSUE THREAD

**Issue by huythansau30** [MystenLabs/sui#11300]
I am trying to get metadata via getCoinMetadata. But not work

Code:
```
const provider = new JsonRpcProvider(testnetConnection)
const metadata = await provider.getCoinMetadata({
  coinType: '0x2::sui::SUI',
})
```

Response:
```{"jsonrpc":"2.0","error":{"code":-32000,"message":"Cannot find object [0x2::coin::CoinMetadata<0x2::sui::SUI>] from [0x0000000000000000000000000000000000000000000000000000000002 ] package event."},"id":"9c8b39c5-8c2b-4d28-81f6-da2a7451c99f"}```

**Comment by stefan-mysten** [comment]
This has been fixed since April, so I will be closing this issue.
