### ISSUE TITLE
[RPC Bug] Get error from RPC when requestType is WaitForEffectsCert even with showEffects: false

### ISSUE THREAD

**Issue by bruceeewong** [MystenLabs/sui#11301]
## Steps to Reproduce Issue

According to the [Sui doc](https://docs.sui.io/sui-jsonrpc#sui_executeTransactionBlock), requestType WaitForEffectsCert should work with showEffects: false.

I am using TS SDK @mysten/sui.js version 0.32.1, to initiate the request.

![uTools_1682390952597](https://user-images.githubusercontent.com/17715132/234165837-0313846a-6ae0-4298-a0c2-cc8657abcd01.png)

Notice that I've set `requestType` to `WaitForEffectsCert` and `showEffects` to `false`, but still get an error from RPC: 

![uTools_1682390966587](https://user-images.githubusercontent.com/17715132/234165842-b866630c-72bb-41cc-81ca-ad62434c20d7.png)

## Expected Result

RPC should work with `requestType`: `WaitForEffectsCert`,  `showEffects`: `false`.

## Actual Result

RPC rejects the executeTransaction request for the above reason in the screenshot.

I found it only works when I change `requestType` to null, which is pretty wired to me.

e.g.
<other function call> returned 41.

## System Information

* OS: <specify OS version>
* Compiler: <specify compiler version>
* TS SDK @mysten/sui.js version 0.32.1

**Comment by Jordan-Mysten** [comment]
The error is incorrect, `showBalanceChanges` and `showObjectChanges` is what requires `WaitForLocalExecution`

**Comment by bruceeewong** [comment]
> The error is incorrect, `showBalanceChanges` and `showObjectChanges` is what requires `WaitForLocalExecution`

Alright, then I guess the doc should get updated. I think now it's too simple to understand what params should be passes.

**Comment by stefan-mysten** [comment]
This has been fixed since April, so closing it for now.
