### ISSUE TITLE
Publish move-core-types v0.0.4

### ISSUE THREAD

**Issue by plafer** [MystenLabs/sui#11308]
Branch: `testnet`

I'm trying to build a [`StructTag`](https://github.com/MystenLabs/sui/blob/133fd85bcd79ed048a897be3a3f3bd4a2e9c616a/external-crates/move/move-core/types/src/language_storage.rs#L117), however I have no way to import the type, since all sui crates use the unpublished `move-core-types` v0.0.4 crates. 

Publishing it would allow me to depend on it. Or, is the crate re-exported somewhere by one of the sui crates?

EDIT: Are we expected to have this in our Cargo.toml?

```toml
move-core-types = {git = "https://github.com/MystenLabs/sui", branch = "testnet"}
```

**Comment by stefan-mysten** [comment]
Hi @plafer, I assume you managed to figure it out, but if not, please feel free to create a new issue. Closing this #cleanup,
