### ISSUE TITLE
Sui documentation lacks GAS fees for the duration of storage

### ISSUE THREAD

**Issue by luav** [MystenLabs/sui#11336]
The [Budget Consumption](https://github.com/MystenLabs/sui/blob/main/doc/src/build/sui-gas-charges.md#budget-consumption) section lacks information about the GAS fees for the storage duration, i.e., whether the price for 1 MB of the on-chain storage for 1 minute and 1 year is the same or how is it calculated depending on the time duration.

Thus, the current description:
> * **Storage Price:** set up in the system and intended to be more stable than RGP, it is a multiplier for the number of bytes written to storage. Initial Storage Price at genesis is 76 MISTS.

should be extended with explanations about the storage costs for the storage duration interval, or it should be explicitly mentioned that the storage duration time is not subject for the GAS fees.

**Comment by randall-Mysten** [comment]
Thanks for the feedback @luav

**Comment by randall-Mysten** [comment]
Sorry for the delay in following up, it is correct that the duration time is unlimited

**Comment by luav** [comment]
> it is correct that the duration time is *unlimited*

Cool!  

Would you or @ronny-mysten document the fact of GAS-free storage duration?!  
That clarification might be actual for many other users, and such a storage policy is a huge advantage for the SUI blockchain compared to ICP and some others that claim cheap on-chain storage but charge for the storage duration.

**Comment by randall-Mysten** [comment]
Yep, multiple updates coming for tomorrow
