### ISSUE TITLE
Could not compile diesel 

### ISSUE THREAD

**Issue by mahdishoghli** [MystenLabs/sui#11363]
During the installation of the SUI client, in the installation of 1041 and during the installation of Diesel, this error is encountered many times .. 

![2023 04 26-18_17_02](https://user-images.githubusercontent.com/122424890/234647377-43127837-6a5d-4d08-ae6b-8483f01dc914.png)

**Comment by SmartDev-0205** [comment]
I get this error too.

**Comment by SmartDev-0205** [comment]
ram should be more than 4G - > This is solution

**Comment by wayneenigma** [comment]
My ram is 8G and still getting this error.

**Comment by mahdishoghli** [comment]
After I used a system with 8 GB of RAM and 4 cores, this problem was solved !
@wayneenigma
