### ISSUE TITLE
Wallet Kit: Lack of Support for Wallet Standard of Multichain Wallet

### ISSUE THREAD

**Issue by sunny0529** [MystenLabs/sui#11457]
## Description 
Based on the Wallet Standard,
- Wallets store the account information for all multiple chains, that support the Wallet Standard, all at once.
- Account information includes chain name(ex. sui), network name(ex. testnet), and a list of features that DApps can execute through the wallet standard.

So when returning accounts from the wallet, such as when connecting to a wallet, wallets should return account information for all multiple chains that support the wallet standard. Then, DApps should select the account for the desired chain(ex. sui) using the network information provided in the returned account information from the wallet.

But, Wallet Kit does not have the logic to filter the desired chain's account.

Therefore, a wallet that aims to support the Wallet Standard for multiple chains cannot even begin to connect with Dapps that use @mysten/wallet-kit (ex. Sui Explorer).

## Steps to Reproduce Issue
1. Connect with the wallet using Wallet Standard in Dapps that use @mysten/wallet-kit(ex. Sui Explorer).
ex. 
![suiexplorer](https://user-images.githubusercontent.com/49579003/235112719-25a5c01c-b64b-43e1-a55d-1c96c8156fd8.png)
2. Check how for Wallet Kit to process the account information returned from the wallet after connecting to the wallet.

## Expected Result
Wallet Kit should select the accounts of the Sui chain among the multi-chain accounts and proceed with the next steps using the selected accounts, which may all belongs to Sui.

## Actual Result
Wallet Kit uses the account information returned by the wallet as is, which may include account information from other chains.

## Suggestion
https://github.com/MystenLabs/sui/blob/4d2ef9071d8bda02d624b3892f759e1d297e3007/sdk/wallet-adapter/wallet-kit-core/src/index.ts#L249-L252
In the above code, instead of simply using the 0th element of the `accounts` array, It seems better to filter only Sui's account using the `chains` in the account information.

The type of `accounts` is `WalletAccount[]`.
```
interface WalletAccount {
    /** Address of the account, corresponding with a public key. */
    readonly address: string;

    /** Public key of the account, corresponding with a secret key to use. */
    readonly publicKey: Uint8Array;

    /**
     * Chains supported by the account.
     *
     * This must be a subset of the {@link Wallet.chains | chains} of the Wallet.
     */
    readonly chains: IdentifierArray; // <-- (SUI_DEVNET_CHAIN = 'sui:devnet', SUI_TESTNET_CHAIN = 'sui:testnet'
)

    /**
     * Feature names supported by the account.
     *
     * This must be a subset of the names of {@link Wallet.features | features} of the Wallet.
     */
    readonly features: IdentifierArray;

    /** Optional user-friendly descriptive label or name for the account. This may be displayed by the app. */
    readonly label?: string;

    /** Optional user-friendly icon for the account. This may be displayed by the app. */
    readonly icon?: WalletIcon;
}
```

The `chains` value in `WalletAccount` can contain the values from the link attached below,
https://github.com/MystenLabs/sui/blob/main/sdk/wallet-adapter/wallet-standard/src/chains.ts#L4-L11

It seems like a selection process is needed like the following code,
```
const suiAccounts = accounts.filter(account => account.chains.split(':')[0] === 'sui'));

setState({ accounts: suiAccounts, currentAccount: suiAccounts[0] ?? null });
```

**Comment by Jordan-Mysten** [comment]
This is a good callout, thanks for reporting! We'll make sure that this gets addressed.
