### ISSUE TITLE
Sui Wallet doesn't support connect to different wallet.

### ISSUE THREAD

**Issue by AaricChen** [MystenLabs/sui#11534]
## Steps to Reproduce Issue

I have connected my first account 0xbb891426d1cb1120ab1773de0e9c59001213317170dfa488b32121092a2413b4 and it is a success.
But when I disconnect and switch the account to 0x65221bd71e9b81191a95bd3ddd93b042f810577200f4c555c39b96397c6c593e.

It will still connect to the previous one. 

https://user-images.githubusercontent.com/117256086/235390032-e5cc189d-5c75-4144-8179-7901e98baeae.mov

**Comment by Jordan-Mysten** [comment]
Sui Wallet does not sync the currently-connected account state between the wallet and the dapp. Instead, we allow users of the dapp to select from the accounts they have connected. We recently added support for account switching in the Wallet Kit packages that are published in this repo. I'm not sure what wallet kit UI this project is using, but this should be reported there instead. Sui Wallet
