### ISSUE TITLE
Request: Implement catchup command

### ISSUE THREAD

**Issue by Lusitaniae** [MystenLabs/sui#11558]
Would be good to have something similar to `solana catchup`

It basically checks the node against the network, slots per second and estimated time to catchup

```
solana@sg54:~$ catchup 
⠠ 3719 slot(s) behind (us:191476591 them:191480310), our node is falling behind at -1.4 slots/second (AVG: -1.0 slots/second (falling))
```

See Solana implementation:
https://github.com/solana-labs/solana/pull/6935/files

**Comment by linuskendall** [comment]
Made a basic version of this utility here: https://github.com/rpcpool/sui-catchup

**Comment by randall-Mysten** [comment]
thanks to you both!
