### ISSUE TITLE
Broken link in the docs

### ISSUE THREAD

**Issue by Lusitaniae** [MystenLabs/sui#11627]
This page:
https://docs.sui.io/devnet/learn/cryptography/sui-signatures

Has a broken link here:
See more authority key toolings in Validator Tool https://docs.sui.io/devnet/learn/cryptography/undefined

The source code is:
https://github.com/MystenLabs/sui/blob/main/doc/src/learn/cryptography/sui-signatures.md

Which correctly links to the proper page:
https://github.com/MystenLabs/sui/blob/main/nre/validator_tool.md

**Comment by randall-Mysten** [comment]
Thank you @Lusitaniae

**Comment by randall-Mysten** [comment]
Hi @joyqvq Looks like a partial sentence in this topic with an incomplete link
