### ISSUE TITLE
SUI RUST SDK - Parse Error at Get Coins Call. Expected u64

### ISSUE THREAD

**Issue by felipepimsil** [MystenLabs/sui#11630]
Some methods like get_coins is crashing due a parse error. The balance field returns an `string`, but the SDK expect an `u64`, which ends in a application crash.

## Steps to Reproduce Issue

To reproduce, only call get_coins or get_balance with some RPC.

```
#[tokio::main]
fn main() -> eyre::Result<()> {
    let node_url: &str = "";
    let sui_connection = SuiClientBuilder::default().build(node_url).await?;
    let balance_information = sui_connection
                .coin_read_api()
                .get_coins(SIGNER, Some(SUI_COIN_TYPE.to_string()), None, None)
                .await?;

}

```

Ends in `Parse error: invalid type: string "18918967", expected u64 at line 1 column 141`

## Expected Result

Should return an `u64` in `balance` field, parsing a `String` to `u64`.

## Actual Result

The RPC returns a string, but the parser isn't handling it, crashing the application.

## System Information

OS: Ubuntu-22.04 - 5.15.90.1-microsoft-standard-WSL2
Cargo: cargo 1.66.1 (ad779e08b 2023-01-10)
Rustup: rustup 1.25.1 (bb60b1e89 2022-07-12)
SUI-SDK: v0.30.0 (https://github.com/MystenLabs/sui#2ab975bd)

**Comment by stefan-mysten** [comment]
@felipepimsil this has been fixed since the issue was reported. If you still have a problem with it, please create a new issue.
