### ISSUE TITLE
sui-wallet-specs.md - add description for the BIP32 cases secp256k1 and r1

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/sui#11643]
Make a clear warning re the last two elements not requiring the `'` symbol ie `m/...'/784'/0'/0/0`
@joyqvq please crosscheck that slip10 and bip32 differ on that by providing some reference.

**Comment by stefan-mysten** [comment]
@kchalkias @joyqvq is this still something we need to address? This is what I found in our new docs https://docs.sui.io/concepts/cryptography/transaction-auth/keys-addresses#example

**Comment by joyqvq** [comment]
the derivation path is explained [here](https://docs.sui.io/concepts/cryptography/transaction-auth/keys-addresses#key-derivation-path) with reference to slip10 and bip32 links
