### ISSUE TITLE
Sui wallet mnemonics, how do I export their private keys

### ISSUE THREAD

**Issue by zerozzz1** [MystenLabs/sui#11741]
I have generated several wallets using the sui wallet mnemonic, how do I get their private keys?

**Comment by zerozzz1** [comment]
Or, how do I retrieve my private key using the mnemonic?

**Comment by Leena8686** [comment]
Go to Coinmaker Cap tracker and follow the instructions. or Coin Track.

**Comment by kchalkias** [comment]
cc: @pchrysochoidis re export private key
