### ISSUE TITLE
How to connect the sui dapp on webview for mobile app ？

### ISSUE THREAD

**Issue by Mike-bel** [MystenLabs/sui#11758]
In mobile wallet app, when opening a sui dapp on webview, how to program to connect the dapp and wallet app? Is there some dapp provider examples for sui dapp?

**Comment by randall-Mysten** [comment]
Have you seen these?
https://www.npmjs.com/package/@mysten/wallet-kit
https://sui-wallet-kit.vercel.app/

**Comment by Mike-bel** [comment]
> Have you seen these? https://www.npmjs.com/package/@mysten/wallet-kit https://sui-wallet-kit.vercel.app/

oh, I don't develop the sui dapp, I develop a native mobile wallet app, and I want to develop a webview provider to connect any sui dapp that opened by this webview.

Now I dont't know how to provide interface for sui dapp, is there any standard protocol or example for webview provder?
