### ISSUE TITLE
How to make Programmable Transaction using RUST-SDK?

### ISSUE THREAD

**Issue by felipepimsil** [MystenLabs/sui#11764]
I searched in discord/here about programmable transaction examples in rust and didn't find nothing. Only saw an issue about it, but was from Feb 19 and is still open.

Was this implemented in RUST?

**Comment by losman0s** [comment]
A bit late maybe but: https://open.substack.com/pub/mrgn/p/suis-programmable-transaction-blocks?r=2gmj29&utm_campaign=post&utm_medium=web

**Comment by stefan-mysten** [comment]
For posterity and if other folks search through the issues, we have [examples](https://github.com/MystenLabs/sui/blob/main/crates/sui-sdk/examples/) on how to use the Rust SDK and create [programmable transactions](https://github.com/MystenLabs/sui/blob/main/crates/sui-sdk/examples/programmable_transactions_api.rs).
