### ISSUE TITLE
docs: Link to s3 bucket is outdated?

### ISSUE THREAD

**Issue by Lusitaniae** [MystenLabs/sui#11804]
https://github.com/MystenLabs/sui/blob/docs-mainnet/doc/src/build/snapshot.md

https://docs.sui.io/build/snapshot

According to the docs, the testnet bucket is: `s3://mysten-testnet-snapshots/` but the last snapshot here is epoch 680

According to Discord chat, looks like the most up to date testnet bucket is `s3://suidb-snapshots`

Please clarify docs or ensure the bucket is up to date with recent snapshots (or future snapshots from new testnet genesis)

**Comment by petvaizAkhtar** [comment]
Rply

**Comment by johnjmartin** [comment]
Please use `s3://suidb-snapshots` until testnet is wiped later this week. After the wipe, and moving forward, `s3://mysten-testnet-snapshots/` will be the source of truth for testnet
