### ISSUE TITLE
How can I get object ID by object type?

### ISSUE THREAD

**Issue by Kinco4TC** [MystenLabs/sui#11909]
Can I get the object ID by object type? Is there any realation?

Like the object ID "0xcf994611fd4c48e277ce3ffd4d4364c914af2c3cbb05f7bf6facd371de688630" ,  and the type is 

0x1eabed72c53feb3805120a081dc15963c204dc8d091542592abaf7a35689b2fb::pool::Pool<0x5d4b302506645c37ff133b98c4b50a5ae14841659738d6d733d59d0d217a93bf::coin::COIN, 0x2::sui::SUI>

**Comment by jymchng** [comment]
What are you using? Typescript/Rust/Python SDK?

**Comment by Kinco4TC** [comment]
Typescript SDK
