### ISSUE TITLE
install Sui binaries from the devnet branch Get Error

### ISSUE THREAD

**Issue by BrainAxe88** [MystenLabs/sui#11945]
When i install this part i get error 
cargo install --locked --git https://github.com/MystenLabs/sui.git --branch devnet sui

error: could not compile sui-framework due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile sui v1.1.0 (https://github.com/MystenLabs/sui.git?branch=devnet#38c31cdd), intermediate artifacts can be found at /var/folders/td/gdb0t7p53nd78mqf1651l_y80000gn/T/cargo-installC2rJm0

**Comment by BrainAxe88** [comment]
My Mac is M2 Chip

**Comment by stefan-mysten** [comment]
@BrainAxe88 this has likely been fixed since. I only have a M1 so I cannot test for M2, but it does compile without errors on my M1. Feel free to create a new issue if you still encounter problems.
