### ISSUE TITLE
ConnectButton

### ISSUE THREAD

**Issue by windswrold** [MystenLabs/sui#11977]
hello,
I need to do something in the Connected and Disconnected section, please find the { ConnectButton, useWalletKit, } from "@mysten/wallet-kit".
ConnectButton and add the relevant callbacks

**Comment by petvaizAkhtar** [comment]
Reply

**Comment by windswrold** [comment]
yes



发自我的iPhone


------------------ Original ------------------
From: Jordan Gensler ***@***.***&gt;
Date: Tue,May 16,2023 0:35 AM
To: MystenLabs/sui ***@***.***&gt;
Cc: Wind ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [MystenLabs/sui] ConnectButton (Issue #11977)

**Comment by Jordan-Mysten** [comment]
You can use the `currentWallet` and `currentAccount` properties from `useWalletKit()`, and then use effects:

```ts
const { currentWallet, currentAccount } = useWalletKit();

useEffect(() => {
  console.log(currentWallet);
}, [currentWallet]);

useEffect(() => {
  console.log(currentAccount);
}, [currentAccount]);
```
