### ISSUE TITLE
error: failed to run custom build command for `librocksdb-sys v0.10.0+7.9.2`

### ISSUE THREAD

**Issue by tungegan** [MystenLabs/sui#11983]
I can't install Sui binaries. I have the lastest Rust version.
I follow this https://docs.sui.io/devnet/build/install#install-sui-binaries and install all the Linux prerequisites. 

i call cargo install --locked --git https://github.com/MystenLabs/sui.git --branch devnet sui

![image](https://github.com/MystenLabs/sui/assets/95173054/ceeca712-fc54-40ac-9706-b973cf98c2a5)

![image](https://github.com/MystenLabs/sui/assets/95173054/550e7046-57b2-4b53-9a7c-fd0c2dce0710)

* OS: <Fedora 38>
* Compiler: <specify compiler version>

**Comment by burhanuddin03** [comment]
Were you able to solve this? @mxtsns

**Comment by mxtsns** [comment]
@burhanuddin03 I have solved this. You can use suivm to install sui binaries 
https://github.com/Origin-Byte/suivm

**Comment by stefan-mysten** [comment]
Closing as the issue has been resolved.
