### ISSUE TITLE
Sui doc content issue or request

### ISSUE THREAD

**Issue by Mivleder** [MystenLabs/sui#12022]
I'm Brazilian and I'm using Google Translator to comunicante.
I'm having connection problems due to the wrong password. I created the wallet and deposited funds, but when saving the keyword, It was translated into my language ( Portuguese ) because l use Google Translation and l didn't pay attention to that. I saved the keyword in Portuguese and now the Translation into English is not working. . Could you help me? Here's a print of the transfere.

There is also a print of the keyword translated into my language and saved by me

Could you translate these words for me in yours system ?

**Comment by randall-Mysten** [comment]
I've seen a few reports about this. Sorry it happened. For one in Spanish, it actually used a different number of words as it translated English words into 2 words in Spanish. While it is potentially possible to translate the words and get the 12 word passphrase in English, doing so would compromise your account as we would see the passphrase. If you don't have any funds or assets in the account, I suggest just making a new wallet (after turning off translation) and using it instead.

**Comment by Mivleder** [comment]
I have funds in the wallet so I need support to access the wallet! This should not happen. They could never allow the translation of the keyword. Even doing the translation back to English doesn't work, I've tried several words and it doesn't work. I need support and I'm not finding it

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Mivleder** [comment]
Could you translate a few words for me in your system? It would help me a lot. I send the words out of sequence and you translate them for me.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Mivleder** [comment]
I can consult my funds in Suiscam but when importing the wallet the funds do not appear. Could you explain me better how to do this, maybe I'm doing it wrong. Please!

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by randall-Mysten** [comment]
Suiscam? Can you find your wallet address on Sui Explorer and see which objects / coins are owned by your address?

**Comment by Mivleder** [comment]
Yes

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Mivleder** [comment]
How do I import this portfolio, could you explain it better?

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by randall-Mysten** [comment]
Could you send me a link to your wallet on Sui Explorer?

**Comment by Mivleder** [comment]
How do I import this portfolio, could you explain it better?

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by randall-Mysten** [comment]
Display the Accounts page in the wallet
<img width="364" alt="image" src="https://github.com/MystenLabs/sui/assets/109545725/29070663-42a0-4e77-8190-7b1650c3b44e">

Click the down arrow to display the Export Private Key link. Click it, then enter your password
<img width="364" alt="image" src="https://github.com/MystenLabs/sui/assets/109545725/0baf018b-7837-4ca2-98fc-961cc7bbe665">

Click Copy.

Store the private somewhere so you can import it into a new wallet.

Turn off translation.

In a different browser, or on a different computer, create a new Sui Wallet.

Create the wallet, save the passphrase, set a password etc. Then go to the **Accounts** page again. Click **Import Private Key**. Paste in the key you copied from the other wallet. Click **Continue**. Enter your password.

The account shows up in your wallet with *Imported* next to it.
<img width="364" alt="image" src="https://github.com/MystenLabs/sui/assets/109545725/87c0c64d-5c48-40d7-9746-919ae1cc1eb7">

Go to the **Coins** tab in wallet and select the imported account as the active account.
<img width="364" alt="image" src="https://github.com/MystenLabs/sui/assets/109545725/e147aeaf-7283-4eac-a856-772e324848eb">

You should see the same tokens, coins, and assets you had in your previous wallet. You can then transfer them to the other address for the new wallet.

**Comment by randall-Mysten** [comment]
But I am not sure what you mean by "consult your funds on Suiscam." What is Suiscam? The word "scam" in the title causes concern :)

**Comment by agentmic487** [comment]
@randall-Mysten are you still having this issue or got it solved?

**Comment by randall-Mysten** [comment]
I didn't have an issue. The reporter was using a screen translator so his 12 word passphrase was not valid as it translated the words in the passphrase. In some cases it made the term 2 words instead of one when translated, so he couldn't restore the account with the passphrase. I provided guidance on exporting the private key to a new wallet so the address showed up there.
