### ISSUE TITLE
Explorer: enhance search capability for more types

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#1204]
Search accounts, transactions, smart contracts, NFTs, tokens by address

**Comment by todd-mystenlabs** [comment]
@Andrew47 @stella3d @Jibz1 @bwann52 - we do have a search bar right now. What makes up this task here?

**Comment by Andrew47** [comment]
@todd-mystenlabs --> the search bar enables the user to search for:

- [x] Accounts: https://explorer-demo.sui.io/addresses/09818aac3edf9cf9b006b70c36e7241768b26386
- [x] NFTs and tokens by address: https://explorer-demo.sui.io/objects/363124FB1BE19377C39C4356865A8C8430C6AE85

But not:
- [ ] Transactions
- [ ] Smart Contracts

Regarding transactions, @stella3d will need to approve the Preview Card PR  https://github.com/MystenLabs/sui/pull/1155 and update the mock transaction data PR https://github.com/MystenLabs/sui/pull/1269. @Jibz1 can then start on implementing the transactions functionality.
