### ISSUE TITLE
Explorer: switch network

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#1206]
allows user to switch between Local, DevNet, Custom URL, and (soon) TestNet, similar to [explorer.solana.com](https://explorer.solana.com/) (See top right corner)

**Comment by 666lcz** [comment]
@Andrew47 , would you love to take on this? I think it is very useful to have this that allows user to switch between Local, DevNet, and (soon) TestNet, similar to https://explorer.solana.com/ (See top right corner)

**Comment by Andrew47** [comment]
Sure - I'll have a look at this

**Comment by Andrew47** [comment]
Here's a screen recording showing progress:

https://user-images.githubusercontent.com/11377188/168891790-89a017f6-1d1e-414b-8cf4-c712ab7ad9a3.mp4

**Comment by stella3d** [comment]
@Andrew47 can we make the button / sidebar smaller ?  seems very large right now for this wide of a screen

**Comment by Andrew47** [comment]
@666lcz / @stella3d --> I've now implemented the ability to specify a custom URL. All seems to work well for objects and addresses (see below video). However, I am getting errors whenever transactions are searched for. Any thoughts on this would be much appreciated.

https://user-images.githubusercontent.com/11377188/169382303-cd9de4d7-543c-47a1-84f4-dce1de78fa6b.mp4

**Comment by stella3d** [comment]
It looks like the other network you're pointing at has no transactions, if objects and addresses work.

**Comment by Romainua** [comment]
Looks like it is done, status still to do https://github.com/MystenLabs/sui/projects/8#card-79995220

**Comment by Andrew47** [comment]
> Looks like it is done, status still to do https://github.com/MystenLabs/sui/projects/8#card-79995220

Thanks @Romainua , this is indeed done.
