### ISSUE TITLE
[Feature request][TS-SDK] More generalized Coin object type validation rule

### ISSUE THREAD

**Issue by JackyWYX** [MystenLabs/sui#12101]
## Steps to Reproduce Issue

Sui coin type has different definitions. Both the following types shall be considered as legit sui coin types:

1. `0x2::coin::Coin<...>`
2. `0x02::coin::Coin<...>`
3. `0x0000...02::coin::Coin<...>`

In the current implementation `Coin` module, the method to decide whether an object is coin is through RegEx, which is strictly:

```
export const COIN_TYPE_ARG_REGEX = /^0x2::coin::Coin<(.+)>$/;
``` 

Currently, the strict check is resulting in multiple breaking points accross SUI ecosystem since last SUI node update 1.1.0.

### Example

The content returned by getObjectById has type defined as:

```
0x0000...0002::coin::Coin
```

Which is not recognized as Coin as `SuiMoveObject`.

### Suggested update

Update the REGEX so that arbitrary number of extra zeros (need to be <63) are allowed in the coin type args.

**Comment by tapash32** [comment]
Please help me
