### ISSUE TITLE
Explorer: view historical activity of the NFT

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#1211]
Can see how mutability affects the NFT

Needs more design definition

**Comment by todd-mystenlabs** [comment]
If the NFT is getting modified at high frequency by, say, a game, this could be potentially many changes a minute.  There's the potential for this content to be very high density, in which case display affordances would be needed to handle that.  i.e. If there are 18,000 transactions on the NFT over the last week, there's got to be some way to aggregate/group that if you want to be able to drill down into it.
