### ISSUE TITLE
Is this a valid SUI objectType?

### ISSUE THREAD

**Issue by Ljzn** [MystenLabs/sui#12130]
Hello, we're using the sui RPC for a long time, and it works pretty well. But yesterday we got a new objectType like

```
"0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
```

in the response of `sui_getTransactionBlock`. The old objectType is `0x2::coin::Coin<0x2::sui::SUI>`, are they the same asset?

**Comment by sblackshear** [comment]
Yes, these are the same. We allow `0x2` as shorthand for `0x0000000000000000000000000000000000000000000000000000000000000002`
