### ISSUE TITLE
merge coin error,could not automatically determine a budget

### ISSUE THREAD

**Issue by leezijie** [MystenLabs/sui#12135]
`const ekp = Ed25519Keypair.fromSecretKey(Uint8Array.from(Buffer.from(prikey,'hex')));
   const signer = new RawSigner(ekp,provider);

    const tx = new TransactionBlock();
    let coin1 = tx.mergeCoins(tx.object('0x1cb31b622a75059e93fba2047bccf0e62b2bdda198ff6c41285a998b02ebaaf2'),[tx.object('0x187284224bf5d747179203e9c05b094ce39e4b21c151ae2c365b9ce076db8f96',)])
    tx.transferObjects([coin1], tx.pure(to,'address'));
    const result = await signer.signTransactionBlock({ transactionBlock: tx });`

get error: Error: Dry run failed, could not automatically determine a budget: CommandArgumentError { arg_idx: 0, kind: InvalidResultArity { result_idx: 0 } } in command 1

**Comment by Dylanma1994** [comment]
how to fix it? @julycanfly
