### ISSUE TITLE
Sui publish error

### ISSUE THREAD

**Issue by Garbage123King** [MystenLabs/sui#12140]
I enter:
sui client publish --gas-budget 20000

msg:
UPDATING GIT DEPENDENCY https://github.com/MystenLabs/sui.git
Failed to build Move modules: Failed to resolve dependencies for package 'nft_tutorial'

Caused by:
    0: Parsing manifest for 'Sui'
    1: Unable to find package manifest at "/root/.move/https___github_com_MystenLabs_sui_git_devnet/crates/sui-framework"
    2: No such file or directory (os error 2).

**Comment by stefan-mysten** [comment]
@Garbage123King - this has likely been fixed since May. I will close the issue for now and feel free to create a new one if it still does not work.
