### ISSUE TITLE
Explorer: display QR code for address

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#1215]
Easily scan to send transfers

**Comment by todd-mystenlabs** [comment]
Do we also expect the explorer to scan?  (I imagine this is both the generate/display and scan, but maybe the scanning is only for the wallet.)

**Comment by bwann52** [comment]
For this issue it is enough to just generate/display. Scanning is lower priority, but later on it would be very sweet to have the search bar enable QR code or text scanning.
