### ISSUE TITLE
Sui Code Bug or Feature Request

### ISSUE THREAD

**Issue by kyunghyunHan** [MystenLabs/sui#12176]
sui client call --gas-budget 3000000000 --package 
I'm trying to run this, but I keep getting an error. Is there any way?

RPC call failed: ErrorObject { code: ServerError(-32000), message: "Transaction has non recoverable errors from at least 1/3 of validators", data: Some(RawValue([[{"UserInputError":{"error":{"GasBudgetTooLow":{"gas_budget":1000,"min_budget":2000}}}},5000,["o6Gzz5Nuu1MoUCqROUph4EN4lw666c7YCQFccU356VMn1phpNQ4FpxYsEvjj5Zq4EXFf1OcomvA/rOJ9YHzteSsjLoNC75eT1SzvTtNEoDHx51/nnckbw6H4NLeCYFNC","o4W+at1Pt7zoEw5M1u0t1m485tQrFnKI7I990hjubnaJEBHYsDol/Oqy600YMy9GDkwR4qOaUeddDlml45JjB0pFHexMwTCPcEpyCi+1IYBkNFm0AjbDkHK9azeXKdij"]]])) }

**Comment by kyunghyunHan** [comment]
sui client call --gas-budget 1000 --package 0x4a1fe4ddbf0e546f81349cc898411dd750c1a8276b9f0a245a579930429cf0c7 --module "counter" --function "count_up" --args 0x6144c89430bf6cc88dd9d53f02b6224d5545afa9470635b4bf209b6efc936d60


I ran it, but the above error occurs

**Comment by polariseye** [comment]
i guess the gas calculate is wrong now. dry_run_transaction_block is always return the right gas budget

**Comment by stefan-mysten** [comment]
This should be working by now, closing as this issue is pretty old.
