### ISSUE TITLE
Explorer: list of transactions interacting with the smart contracts

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#1218]
On [Package page](https://explorer.devnet.sui.io/objects/0x0000000000000000000000000000000000000002), show a list of transactions that call the entry functions (i.e. `public (script)`) defined in the package.

The fullnode needs to support indexing [transactions](https://explorer.devnet.sui.io/transactions/Gm1Zn%2FvVhnqtHhzuWBxG6ie3XbnU3qchHLQQPgHlYvc%3D) by Package, Module, and Function.  
![CleanShot 2022-05-13 at 10 00 37](https://user-images.githubusercontent.com/76067158/168332693-b396fbbd-588d-4c5f-8d14-274677c9042d.png)

**Comment by todd-mystenlabs** [comment]
@bwann52 - could you spec this out a bit more? What would this look like (not from a UI standpoint, but more about what the data is.) The current description is a bit vague in my mind.

**Comment by 666lcz** [comment]
Hey @mystenmark , is there any update on this issue?

**Comment by velvia** [comment]
I can have a look at this, later this week.
