### ISSUE TITLE
Sui Wallet - Can't transfer OB NFTs

### ISSUE THREAD

**Issue by mistertoucan** [MystenLabs/sui#12206]
Hey,

I'm using the Sui Wallet and I can't transfer my Origin-byte based NFTs.
The problem is when trying to click SendNFT.

I attached a screenshot below.
Additionally, not all of my NFTs are appearing in my wallet.
https://imgur.com/a/xlh8oHC

Thank you,
Anthony

**Comment by Johnnyrickk** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me recover all my funds,message him on telegram his telegram username is  https://t.me/Blackhathacker111
