### ISSUE TITLE
ts sdk .     JsonRpcProvider

### ISSUE THREAD

**Issue by windswrold** [MystenLabs/sui#12219]
const provider = new JsonRpcProvider();
  console.log(provider);

![image](https://github.com/MystenLabs/sui/assets/13443539/7a29c10d-fd3c-4fd7-8a6f-d7050c40fc8e)

When using JsonRpcProvider to request data, it is found that it has always been devnet data. Is this a problem with the sdk or what?

**Comment by wlmyng** [comment]
You'll need to instantiate `JsonRpcProvider` with some values, by default it points to devnet.
https://github.com/MystenLabs/sui/blob/releases/sui-v1.2.0-release/sdk/typescript/src/providers/json-rpc-provider.ts#L120

**Comment by wlmyng** [comment]
As an example:
```ts
export const testnetConnection = new Connection({
  fullnode: 'https://fullnode.testnet.sui.io:443/',
  faucet: 'https://faucet.testnet.sui.io/gas',
});

const provider = new JsonRpcProvider(testnetConnection);
```

Replace `testnetConnection` as needed.

**Comment by windswrold** [comment]
![image](https://github.com/MystenLabs/sui/assets/13443539/2e238ca5-ca8b-4080-888e-3b55469c14a7)
If I set dev get data. But the sui wallet is currently the mainnet, how to deal with this situation?

**Comment by petvaizAkhtar** [comment]
Reply

**Comment by stefan-mysten** [comment]
The new TS SDK and Wallet should have fixed this issue. If not, feel free to create a fresh issue describing the problem.
