### ISSUE TITLE
[P2] [Umbrella] Create Custodial Wallet Backend

### ISSUE THREAD

**Issue by todd-mystenlabs** [MystenLabs/sui#1223]
Provide a simple custodial wallet underlying implementation (not a user interface).

Goals:
* Simple to use
* Usable by a game or app backend to store keys
* Can sign transactions

This is not intended to be an industrial-strength solution at this stage. It is useful to get devnet/testnet kick-started prior to having other industrial-strength solutions supporting Sui.  We plan to have game usage examples that will use this to simplify on-boarding of players.

Needs to be accessible by (at least):
* Rust
* C# (for Unity game usage)
* TypeScript

**Comment by todd-mystenlabs** [comment]
@kchalkias - just putting this on you until we finalize who will do it.

**Comment by todd-mystenlabs** [comment]
Based on [this thread](https://mysten-labs.slack.com/archives/C0393DWJD7X/p1649113083830539), I think some combo of @kchalkias and @patrickkuo are working on this. Are there more specific GitHub Issues covering those?  Looking to figure out what state this is in.

**Comment by todd-mystenlabs** [comment]
(There's a signing service task on Kostas and a gateway service task on Patrick.)

**Comment by todd-mystenlabs** [comment]
P2 for DevNet.

**Comment by kchalkias** [comment]
Deterministic key derivation - DONE - https://github.com/MystenLabs/sui/pull/1508
Signer RPC server - WIP in this branch: https://github.com/MystenLabs/sui/tree/kostas-deterministic-signer-rpc
