### ISSUE TITLE
Sui TS SDK issue on src/rpc/client.ts:70

### ISSUE THREAD

**Issue by andreidev1** [MystenLabs/sui#12236]
Installed @mysten/sui.js:0.34.1
Whenever I run this snippet code : 
```ts
import { JsonRpcProvider, devnetConnection } from '@mysten/sui.js';
const provider = new JsonRpcProvider(devnetConnection);
const objects = await provider.getOwnedObjects({
  owner: '0xcc2bd176a478baea9a0de7a24cd927661cc6e860d5bacecb9a138ef20dbab231',
});
```
I get : 
```/node_modules/@mysten/sui.js/src/rpc/client.ts:70
          let res: Response = await fetch(url, options);
                              ^

ReferenceError: fetch is not defined
```

I've checked your latest commits on `src/rpc/client.ts` and I see that you removed the `let res: Response = await fetch(url, options);` part
Any idea how can I get the latest version ? The changelog says latest version is 0.34.1 which I already installed

**Comment by Jordan-Mysten** [comment]
If you're running on an old version of node.js, you'll need to polyfill `fetch`. You can also update to the latest LTS of Node.js which will include the global `fetch` function.
