### ISSUE TITLE
Enable RPC for validator thru config flag

### ISSUE THREAD

**Issue by RdeWilde** [MystenLabs/sui#12283]
Currently the RPC endpoint is disabled for validators by default as for here:
https://github.com/MystenLabs/sui/blob/958854e1121ea746caff7b3bd2b3accb5076e370/crates/sui-node/src/lib.rs#L1309

We would like to enable RPC on the validator and make it accessible locally. This is mainly for monitoring. Currently there's no way to do such thing.

Request:
Please add a config flag to explicitly enable the RPC, even if it's a validator (overruling default 'off')

**Comment by RdeWilde** [comment]
@randall-Mysten any update/eta on this? We have to source external nodes now, while we would like to keeps things local on the validator.

**Comment by randall-Mysten** [comment]
Sorry, I overlooked this issue. Added some folks who can provide more info about your inquiry

**Comment by amnn** [comment]
Also adding @bmwill, who I know had similar thoughts about RPCs for monitoring on validators.

**Comment by bmwill** [comment]
I'm not sure we want to broadly expose the json rpc apis on validators, although I have been looking into adding a more stripped down interface to all nodes that would better help with simple monitoring and health checking
