### ISSUE TITLE
[move][sui framework] Distinguish between `Coin<T>` and `Balance<T>`

### ISSUE THREAD

**Issue by sblackshear** [MystenLabs/sui#1233]
A `Coin<T>` is a Sui object, and must have a `VersionedID`. But many uses of `Coin`'s (e.g., using a `Coin` as a struct field) don't need an ID (e.g., https://github.com/MystenLabs/sui/blob/main/sui_programmability/examples/defi/sources/FlashLender.move#L15).

One solution to this we discussed is to have separate types for a "Coin object" and a "Coin balance". Something like:

```
// Use this one inside structs that need to hold coins
struct Balance has store {
  value: u64
}

// Use this one to transfer coins across accounts
struct Coin has key, store {
  id: VersionedID,
  balance: Balance 
}
```

It's debatable whether `Coin` should continue to have `store` after this change. Getting rid of the ability makes it clearer when you ought to use `Balance` vs `Coin`. However, it may also require more conversions between `Coin` and `Balance`.  For example, if you want to send someone a `Coin` that they can only unlock if they take some action (e.g., via https://github.com/MystenLabs/sui/blob/main/sui_programmability/examples/basics/sources/Lock.move), this wouldn't be possible if `Coin` did not have `store`.

**Comment by lxfind** [comment]
Perhaps Coin and Balance can be friends?

**Comment by sblackshear** [comment]
> Perhaps Coin and Balance can be friends?

This is another way to do it that could also make sense.

**Comment by todd-mystenlabs** [comment]
@sblackshear - seems like something wrap up by Pre-DevNet?

**Comment by damirka** [comment]
I see few approaches to this issue, @lxfind @sblackshear @tnowacki @awelc, please tell me which one you find the best.

### 1. Balance as Wallet, Coin as a transferable object

- Balance/Wallet as something that people might have to store Coins. Then everyone will need to init their wallet with `create_wallet<T>`
- Coin as a transferable object, which can be used in flash loans or to pass somewhere. Should be used right away but we might want to keep `store` ability so it can be stored inside an offer/lock/some defi applications.

In human it makes sense: we take a Coin from Wallet and pass it to X.

```rs
struct Wallet<T> has key { id: VersionedID, value: u64 } 
struct Coin<T> has store { value: u64 }
```

**Pros**: reduces number of IDs in most of the cases, makes sense in terms of terminology
**Cons**: it is impossible to send coin directly as id doesn't have a `key` ability, hence can't be transferred to another account directly (only wrapped somehow). Also balance needs to be initialized.

### 2. Balance as a balance of something (eg of a liquidity pool), Coin as it is now

Version from the issue description.

```rs
struct Balance has store { value: u64 } // Use this one inside structs that need to hold coins
struct Coin has key, store { id: VersionedID, balance: Balance } // Use this one to transfer coins across accounts
```

**Pros**: DeFi apps and shops and any other apps can use balance without ID. Coin is as it is now, also good.
**Cons**: Not so clear, coin still be used as a balance if users are not reading documentation and trying to follow everything in it. Nit: additional struct inside a Coin, trickier serde.

 ### 3. Combo of 1 and 2: wallet, balance and transferable coin

This one is heavy on the rules but gives most benefits from the perspective of common sense and optimizations.

```rs
struct Coin { value: u64 } // hot potato
struct Balance has store {  value:  u64 } // non-wallet storage for coins
(private) struct Wallet has key { id: VersionedID, balance: Balance } // private wallet
``

**Pros**: A mix of most of the pros of the solutions above. Additionally Coin is a hot potato which can be used for fast swaps and can be put only to the balance or a wallet - forcing developers to use it in a right way.
**Cons**: Might seem a bit complicated, but given the set of abilities (but people won't really be able to use it in a wrong way).

**Comment by lxfind** [comment]
From clarity perspective, it still seems that (2) is the simplest.
But I want to take a step back to make sure we are all on the same page of the issue.
The core of the issue, is that we think using `Balance` in cases like FlashLoan where a balance object is  temporarily need during a transaction and doesn't need to live across transactions, is more convenient to code than using `Coin` directly. Is that right? Or are there more fundamental safety issues?

**Comment by sblackshear** [comment]
- I agree on (2).
- Yes, the problem this is solving is only a convenience/efficiency one. In cases where you only need a `Balance`, we can avoid generating/storing an object ID, often avoid passing around `TxContext` parameter, avoid destroying the object ID when merging `Balance` with another `Balance` or with `Coin`, etc.

**Comment by damirka** [comment]
Okay. Then let's settle on the 2nd. 👍

**Comment by tnowacki** [comment]
Bringing this back up from #1573. It feels very strange to me that "Coin" is non-fungible (at least sort of)

I would personally vote for 
```
struct Wallet<T> has key { id: VersionedID, value: u64 } 
struct Coin<T> has store { value: u64 }
``` 
A "wallet" is something in my pocket. It is mine and is different from yours. The coins/currency units in them are interchangeable.

**Comment by sblackshear** [comment]
I think the unfortunate thing about the term `Wallet` is that it's already so overloaded because of the frontend tool concept. For example: in our tutorial about Sui wallet, we would begin by talking about how to get `Wallet` objects associated with your address...

**Comment by sblackshear** [comment]
`Coin` is (IMO) a reasonable term, and it's also everywhere (e.g., the explorer and wallet CLI)--I would be hesitant to change it (especially this close to our devnet launch) without a strong motivation.
