### ISSUE TITLE
Install Sui failed on M1 Mac

### ISSUE THREAD

**Issue by alphafitz11** [MystenLabs/sui#12344]
## Command

`cargo install --locked --git https://github.com/MystenLabs/sui.git --branch devnet sui`

## Error

error: linking with `cc` failed: exit status: 1
······
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: could not compile `sui-framework` due to previous error

## System Information

* rustup: stable-aarch64-apple-darwin unchanged - rustc 1.70.0 (90c541806 2023-05-31)
* cmake: cmake version 3.26.4
* OS: macOS Ventura 13.4, Apple M1 Pro

So how can I fix this and install Sui?

**Comment by dustin6341** [comment]
> ## Command
> `cargo install --locked --git https://github.com/MystenLabs/sui.git --branch devnet sui`
> 
> ## Error
> error: linking with `cc` failed: exit status: 1 ······ ld: symbol(s) not found for architecture arm64 clang: error: linker command failed with exit code 1 (use -v to see invocation) error: could not compile `sui-framework` due to previous error
> 
> ## System Information
> * rustup: stable-aarch64-apple-darwin unchanged - rustc 1.70.0 (90c541806 2023-05-31)
> * cmake: cmake version 3.26.4
> * OS: macOS Ventura 13.4, Apple M1 Pro
> 
> So how can I fix this and install Sui?

**Comment by hello2jie** [comment]
It looks like a rust environment issue, not a sui issue.  
Try to add the following sections to your **~/.cargo/config** (if you don't have this file feel free to create):
```

[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
```

**Comment by MarcoDotIO** [comment]
Works for me! I'll let you know if I have any other issues.

**Comment by stefan-mysten** [comment]
@alphafitz11 Feel free to create a new issue if it still does not work for you.
