### ISSUE TITLE
Tools/instructions for pushing to staging and production

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#1236]

**Comment by Clay-Mysten** [comment]
Godwin has provided:
Deploy to production WITH CAUTION (results in temporary 404s):
https://us-central1-devportal-30dd0.cloudfunctions.net/deployToProd

Documented on:
https://www.notion.so/mystenlabs/e19c1300e086416796ace4d70e207def?v=9de1a71769554d4aa48e0530c63fa157

Noting that staging occurs on the hour.

**Comment by Clay-Mysten** [comment]
Godwin will supply a similar link for manual staging.

**Comment by bwann52** [comment]
4/7 update, has a way to manually push to production. Next is to have a way to manually push to staging.

**Comment by Clay-Mysten** [comment]
We also need notifications on when pushes break, such as from 404s.

Let's document that internally.

**Comment by todd-mystenlabs** [comment]
Is this done now?

**Comment by Jibz1** [comment]
@todd-mystenlabs methods to deploy to both staging or production are done. Email notification is done through GitHub subscription to the dev portal repo.

**Comment by Clay-Mysten** [comment]
> @todd-mystenlabs methods to deploy to both staging or production are done. Email notification is done through GitHub subscription to the dev portal repo.

And these methods are documented here in the Stage to production section:
https://www.notion.so/mystenlabs/e19c1300e086416796ace4d70e207def?v=9de1a71769554d4aa48e0530c63fa157

**Comment by Clay-Mysten** [comment]
Hmm,

I am detecting huge lags between GitHub and docs.sui.io, four days and counting. See:
https://docs.sui.io/build/install
https://github.com/MystenLabs/sui/blob/main/doc/src//build/install.md
https://github.com/MystenLabs/sui/commit/63d2f740e44c6412a3e6aab603aff3eb14d044c9
<img width="1532" alt="Screen Shot 2022-04-19 at 10 13 29 AM" src="https://user-images.githubusercontent.com/100217682/164058921-5a304ed6-5202-459b-b847-69245475325c.png">

https://docs.sui.io/contribute
https://github.com/MystenLabs/sui/blob/main/doc/src//contribute/index.md
https://github.com/MystenLabs/sui/commit/c1176eb25a8ff252892de55562dc9d7ed0b69a78
<img width="1532" alt="Screen Shot 2022-04-19 at 10 14 06 AM" src="https://user-images.githubusercontent.com/100217682/164059023-a8100400-f18d-4f98-a648-bdeb9f009dcf.png">

Godwin, what gives?

Also note the double slashes persist in our source code link URLs. Let me know if you want me to file a new issue for that.

**Comment by Jibz1** [comment]
@Clay-Mysten this seems correct, See the screenshot of the update
<img width="1257" alt="Screen Shot 2022-04-19 at 1 18 15 PM" src="https://user-images.githubusercontent.com/8676844/164059913-04c6f8cf-20da-4022-bb2a-ff903ce5c275.png">
<img width="852" alt="Screen Shot 2022-04-19 at 1 17 39 PM" src="https://user-images.githubusercontent.com/8676844/164059924-91249060-32f5-433d-9009-0c12b6a7a3d7.png">

**Comment by Clay-Mysten** [comment]
Look at the screenshots. I moved the git clone instructions and directory summaries from Contribute to Install.

**Comment by Clay-Mysten** [comment]
Right now, Install Sui merely says:

Contribute[#](https://docs.sui.io/build/install#contribute)
If you need to download and understand the Sui source code, follow [contributing to Sui](https://docs.sui.io/contribute).

**Comment by Clay-Mysten** [comment]
Did we determine the cause? How can we catch these delays automatically?
