### ISSUE TITLE
Distinguish between various headers (H4s, H3s, H2s) in ToCs

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#1237]

**Comment by Clay-Mysten** [comment]
See these screenshots for the issue:
<img width="1269" alt="Screen Shot 2022-04-06 at 10 43 15 AM" src="https://user-images.githubusercontent.com/100217682/162036040-d4bbc0ab-0f2b-4bcb-bc24-8c6b19c8bce9.png">
<img width="1269" alt="Screen Shot 2022-04-06 at 10 42 55 AM" src="https://user-images.githubusercontent.com/100217682/162036050-11fa91de-d5dd-4b67-8165-477f4118b1f9.png">

In GitHub's table of contents, sub-heads are indented. In our Dev Portal they are not, merely presented as a flat list. So a reader can't tell which is a subsection from that view.

**Comment by Clay-Mysten** [comment]
Awesome, Godwin! Thank you!

**Comment by bwann52** [comment]
@Clay-Mysten is this one complete?

**Comment by Clay-Mysten** [comment]
Thanks, Godwin!

**Comment by Clay-Mysten** [comment]
Yep
