### ISSUE TITLE
Determine whether to break lines in Markdown files or not?

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#1239]

**Comment by Clay-Mysten** [comment]
I'm working on this:
https://stackoverflow.com/questions/29955688/in-markdown-is-there-an-official-best-practice-as-relates-to-line-length

And finding no guidance:
https://docs.github.com/en/get-started/writing-on-github

We should decide as a team.

**Comment by Clay-Mysten** [comment]
I have determined GitHub editor just does the right thing. No need to manually break files.
