### ISSUE TITLE
[Rust SDK] Error: byte deserialization failed

### ISSUE THREAD

**Issue by RandyPen** [MystenLabs/sui#12405]
## Run Example Code 

```
cargo run --example get_owned_objects
```

## Actual Result

```
    Finished dev [unoptimized + debuginfo] target(s) in 1.20s
warning: the following packages contain code that will be rejected by a future version of Rust: nom v5.1.2
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 9`
     Running `/Users/xxx/Code/sui/target/debug/examples/get_owned_objects`
Error: byte deserialization failed
```

## System Information

* OS: macOS Ventura 13.4
* Compiler: rustc 1.70.0 (90c541806 2023-05-31)

**Comment by RandyPen** [comment]
The problem is caused by the address length is not compatible with new version.
Just replace a new address in example code.

**Comment by stefan-mysten** [comment]
The example has been reworked so there shouldn't be any problems now. https://github.com/MystenLabs/sui/blob/main/crates/sui-sdk/examples/read_api.rs
