### ISSUE TITLE
[Rust SDK] error[E0405]: cannot find trait `RowGatWorkaround` in module `diesel::row`

### ISSUE THREAD

**Issue by 0x6368616e67** [MystenLabs/sui#12421]
## Steps to Reproduce Issue

crate a empty cargo project with :

        cargo new --bin test

then add this to Cargo.toml:

    sui-simulator = { git="https://github.com/MystenLabs/sui.git", branch="mainnet"}
    sui-types = { git="https://github.com/MystenLabs/sui.git", branch="mainnet"}

test build then:
    
    cargo build

then you will got:

        error[E0405]: cannot find trait `RowGatWorkaround` in module `diesel::row`
          --> /Users/you/.cargo/registry/src/index.crates.io-6f17d22bba15001f/diesel-async-0.2.0/src/pg/row.rs:16:23
           |
        16 | impl<'a> diesel::row::RowGatWorkaround<'a, diesel::pg::Pg> for PgRow {
           |                       ^^^^^^^^^^^^^^^^ not found in `diesel::row`
        
        error[E0405]: cannot find trait `RowGatWorkaround` in module `diesel::row`
          --> /Users/you/.cargo/registry/src/index.crates.io-6f17d22bba15001f/diesel-async-0.2.0/src/pg/row.rs:30:39
           |
        30 |     ) -> Option<<Self as diesel::row::RowGatWorkaround<'b, diesel::pg::Pg>>::Field>
           |                                       ^^^^^^^^^^^^^^^^ not found in `diesel::row`

but if change to "main" branch  it will be OK.

        sui-simulator = { git="https://github.com/MystenLabs/sui.git", branch="main"}
        sui-types = { git="https://github.com/MystenLabs/sui.git", branch="main"}

this will build success.

## Expected Result

build success.

## Actual Result

build error with  "error[E0405]: cannot find trait `RowGatWorkaround` in module `diesel::row`"

* OS: MacOS
* Compiler: latest stable-x86_64-apple-darwin

**Comment by stefan-mysten** [comment]
This does not seem to be an issue anymore, so closing it for now.
