### ISSUE TITLE
Display Awesome Move in dev portal

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#1242]

**Comment by Clay-Mysten** [comment]
This is something for me and Sam to figure out:
How to make the Awesome Move docs more visible.
Bring them into the Dev Portal directly?
Unite with the central Move docs?
Take the latter on too in a central location?

**Comment by Clay-Mysten** [comment]
See the related request in:
https://github.com/MystenLabs/Prose/issues/13
