### ISSUE TITLE
Sui doc content issue or request

### ISSUE THREAD

**Issue by joe-stifler** [MystenLabs/sui#12430]
Under `A collaborative approach to transaction submission` section in the sui docs [here](https://docs.sui.io/learn/sui-compared), Proof of Stake link is actually pointing to [Proof of Work](https://en.wikipedia.org/wiki/Proof_of_work) instead of [Proof of Stake](https://en.wikipedia.org/wiki/Proof_of_stake). Is that correct?

**Comment by Snach13** [comment]
is this issue still open ?

**Comment by randall-Mysten** [comment]
Sorry, I pushed an update the day you filed it and neglected to resolve. This is updated/fixed.
