### ISSUE TITLE
Handle API versioning

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#1244]
What facilities does our system have for handling versioning, such as API references? Something like: https://docusaurus.io/docs/versioning

**Comment by todd-mystenlabs** [comment]
(renaming some of these to make it clear from the title without consulting the labels -- API versioning is a loaded term that means a lot of things!)

**Comment by bwann52** [comment]
@Clay-Mysten for more context

**Comment by Clay-Mysten** [comment]
I think this is a no-op given our API reference docs appear to be versioned already:
https://app.swaggerhub.com/apis/MystenLabs/sui-api/

The only decision to be made here is to determine if we might somehow need to let users toggle to older docs on our tools, say Wallet and Sui. (Xun and I ran into this yesterday where I was using a command argument from an older version of Wallet.)

Frankly, I default to showing only the latest set of instructions and encourage users to upgrade. After all, the docs themselves are in GitHub revision control and so can therefore be found if an older version is absolutely needed.

Closing unless someone wants to reopen. I've added Xun and Adam in passing just in case they see a missed use case here. Thanks, all.

**Comment by lxfind** [comment]
I don't know if our API is versioned. Could someone else confirm? @patrickkuo

**Comment by Clay-Mysten** [comment]
I can:
https://app.swaggerhub.com/apis/MystenLabs/sui-api/0.2
https://app.swaggerhub.com/apis/MystenLabs/sui-api/0.1

**Comment by Clay-Mysten** [comment]
This is becoming an issue, for sure.

**Comment by Clay-Mysten** [comment]
Examples where deltas are biting us:
https://github.com/MystenLabs/sui/pull/1743
https://github.com/MystenLabs/sui/pull/1791
https://github.com/MystenLabs/sui/pull/1630
https://github.com/MystenLabs/sui/pull/1611
https://github.com/MystenLabs/sui/pull/1588
https://github.com/MystenLabs/sui/issues/1639
https://github.com/MystenLabs/sui/issues/1733
https://github.com/MystenLabs/sui/issues/1605

**Comment by 666lcz** [comment]
Synced with @patrickkuo offline, he will come up with a comprehensive plan for API Versioning

**Comment by Clay-Mysten** [comment]
This is becoming increasingly important. See:
https://mysten-labs.slack.com/archives/C034XH78HNU/p1653512456833269

I've added Lu for thoughts on this longer-term goal. See that thread for intermediary steps we can take.

**Comment by Clay-Mysten** [comment]
See real-life examples of why we need to recommend folks contribute to `main` and not `devnet` in:
https://github.com/MystenLabs/sui/pull/2105
https://github.com/MystenLabs/sui/pull/2218

**Comment by Clay-Mysten** [comment]
@Jibz1 in speaking with @sblackshear  today, he says we should plan on serving multiple versions of docs with devnet, testnet, and mainnet coexisting. Please proceed with working on this, please. 

Making this a high priority for mainnet.

**Comment by Clay-Mysten** [comment]
Ideally, we have something in place by testnet.

**Comment by Jibz1** [comment]
@Clay-Mysten, @sblackshear I need clarification. Is this dependent on the folder/ file structure, meaning are you going to have separate directories within the main branch called `devnet` and `testnet`. I have to understand where we are serving those content from.

**Comment by Clay-Mysten** [comment]
> @Clay-Mysten, @sblackshear I need clarification. Is this dependent on the folder/ file structure, meaning are you going to have separate directories within the main branch called `devnet` and `testnet`. I have to understand where we are serving those content from.

Yes, we should have parallel directories for each version.

**Comment by Jibz1** [comment]
Perfect. Please create the parallel directories in the root of the docs folder leaving src directory as is.

**Comment by Clay-Mysten** [comment]
> Perfect. Please create the parallel directories in the root of the docs folder leaving src directory as is.

Sure thing! I've started with `devnet`:
https://github.com/MystenLabs/sui/pull/2277

I figure once we get that sorted, we can replicate the setup across the other directories. Thanks, Godwin!

**Comment by bwann52** [comment]
@janetwu11 need your advice on this. Could you share what's the latest plan on version control?

**Comment by Clay-Mysten** [comment]
@bhenhsi for input, as well.

**Comment by Clay-Mysten** [comment]
@punwai has more feedback requesting this in:
https://github.com/MystenLabs/sui/issues/1362#issuecomment-1191125990

**Comment by mystie711** [comment]
@Clay-Mysten here's Figma design to use for reference,
https://www.figma.com/file/VQpnxWPq67KNDhFGwbohXw/on-the-go-assistance?node-id=2%3A9

**Comment by Clay-Mysten** [comment]
> @Clay-Mysten here's Figma design to use for reference, https://www.figma.com/file/VQpnxWPq67KNDhFGwbohXw/on-the-go-assistance?node-id=2%3A9

Thank you, Abhi! Godwin, please let us know how we can help.

**Comment by Clay-Mysten** [comment]
@Jibz1  has a fix in place. See the Devnet and Latest build toggle at top left of the site. Thank you!

@patrickkuo is asking we also remove the references on the left to the API docs:
https://docs.sui.io/sui-jsonrpc

But Patrick, I still feel like this is a useful access point. It's incredibly visible. I just need to link to it more from the bodies of related docs. Can you help us understand why you would like it removed from the left nav, such as on?
https://docs.sui.io/build/json-rpc

Is it confusing? I will be working on splitting up the latter page per your recent input (making startup separate and linking to the sui-jsonrpc output from the Sui JSON-RPC methods section for the latest reference until we merge the two).

What else am I missing? Thanks!

**Comment by patrickkuo** [comment]
> @Jibz1 has a fix in place. See the Devnet and Latest build toggle at top left of the site. Thank you!
> 
> @patrickkuo is asking we also remove the references on the left to the API docs: https://docs.sui.io/sui-jsonrpc
> 
> But Patrick, I still feel like this is a useful access point. It's incredibly visible. I just need to link to it more from the bodies of related docs. Can you help us understand why you would like it removed from the left nav, such as on? https://docs.sui.io/build/json-rpc
> 
> Is it confusing? I will be working on splitting up the latter page per your recent input (making startup separate and linking to the sui-jsonrpc output from the Sui JSON-RPC methods section for the latest reference until we merge the two).
> 
> What else am I missing? Thanks!

I am ok with keeping the api ref on the left hand side menu... currently if you click on it, it brings you to the OpenRpc docs and the RPC API menu disappears.... it's a bit strange and we should fix this if we want to keep it there.

https://user-images.githubusercontent.com/1888654/182220424-726e2475-b2e0-4296-8e5b-99ee6bd71b12.mov

**Comment by Jibz1** [comment]
@patrickkuo I did that intentionally because I felt it is a bit redundant to have both side menus showing the same thing

**Comment by Clay-Mysten** [comment]
> @patrickkuo I did that intentionally because I felt it is a bit redundant to have both side menus showing and doing the same thing.

Godwin, can we restore it and see what that looks like again? Thanks!

**Comment by patrickkuo** [comment]
> > @patrickkuo I did that intentionally because I felt it is a bit redundant to have both side menus showing and doing the same thing.
> 
> Godwin, can we restore it and see what that looks like again? Thanks!

I though that was a bug lol... If that's intentional, I will leave the UX judgment to you guys :)

**Comment by Jibz1** [comment]
@patrickkuo and @Clay-Mysten please see Slack

**Comment by Clay-Mysten** [comment]
Hi team,

I would say we can close this issue. But we now have a related request from Sam in:
https://github.com/MystenLabs/sui/issues/3877

Let's discuss.

**Comment by Clay-Mysten** [comment]
Closing in favor of:
https://github.com/MystenLabs/sui/issues/3877
