### ISSUE TITLE
Have code owners for auto review

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#1245]
Can we employ code owners for auto-assigned reviews?
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by Clay-Mysten** [comment]
Godwin already has contributors listed at the bottoms of all pages. Perhaps we can trigger review requests from that list.

**Comment by Clay-Mysten** [comment]
Adding @huitseeker to see what he thinks.

**Comment by huitseeker** [comment]
We already have a CODEOWNERS file, and the auto-assignment already works. Please contribute to it (submit a PR that edits it) to set up auto-assignments as you please.

**Comment by Clay-Mysten** [comment]
Ack. Can we assign owners by subdirectory?

**Comment by huitseeker** [comment]
Yes, as indicated in the doc linked above.

**Comment by Clay-Mysten** [comment]
Cool. Leaving as low priority. This will be more relevant once we better split up our contents into subdirectories.

**Comment by huitseeker** [comment]
As far as I'm concerned this is done: there's a mechanism in place to add reviewers per directory, it's tested and used today, and you have a clear pathway to customize it to your needs. Please reopen if this is not the case.
