### ISSUE TITLE
Create public FAQ in Dev Portal and include answered and approved entries in FAQ Discord channel

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#1246]

**Comment by Clay-Mysten** [comment]
Here is the draft:
https://docs.google.com/document/d/11SrRYXUg3BBucHY339ShZTXSI8GwakPgMtTXgVNBt0Q/edit#

Will work with Jennifer and Kyle to finalize and iterate.

**Comment by Clay-Mysten** [comment]
Adding Koh as she asked for us to add a link to typeform to collect inbound partner requests. We need the link.

**Comment by Clay-Mysten** [comment]
Reopening to track integration of the FAQ in the site.
