### ISSUE TITLE
How can i split Coin without ts-sdk?

### ISSUE THREAD

**Issue by weixuefeng** [MystenLabs/sui#12482]
**New**
I use flutter to develop a sui wallet, but I don't know how to implement splitCoin. For example, I have 5 sui, divided into 5 objects, and I want to send 4.5 sui to other addresses. How can I implement it? Is something like utxo calculated by the server? Or is there some rpc way for me to call?

**Comment by Jordan-Mysten** [comment]
For languages that don't have an SDK, you'll need to build the transaction bytes to BCS, which is the format that the network understands. I'm not sure if Flutter supports calling other binaries, or building native code from rust, in which case it could be possible to incorporate the Sui binary code to generate the transaction bytes.

There are `unsafe_` endpoints that does basic transaction building but these are not recommended because of the security implications of it.

**Comment by weixuefeng** [comment]
thanks for reply!
for `security implications`, can you give me more information about it？ I currently have no basis for evaluation。
there is my code, i need your suggestion.
```

  Future<BigInt> calculateFee(
      String targetAddress, String signerAddress, String amount) async {
    var suiCoinInfo = await getCoins(signerAddress);
   /// calculate 'utxo'
    var objectId = calculateObject(amount, suiCoinInfo);
    var balance = await getBalance(signerAddress);
    var gas = balance - BigInt.parse(amount);
    /// call unSafaPaySui for get txBytes.
    var txBytes = await unSafePaySui(
        targetAddress, signerAddress, amount, objectId!, gas.toString());
    return dryRunTransactionBlock(txBytes);
  }

Future<String> sendSUI(String targetAddress, String signerAddress,
      String amount, String privateKeyHex) async {
    /// call sui_getCoins rpc, get signer sui's coinObjectIds.
    var suiCoinInfo = await getCoins(signerAddress);
    /// calculate gasBudge
    var fee = await calculateFee(targetAddress, signerAddress, amount);
    var objectId =
        calculateObject((BigInt.parse(amount) + fee).toString(), suiCoinInfo);
    var txBytes = await unSafePaySui(
        targetAddress, signerAddress, amount, objectId!, fee.toString());
   /// sign transaction...
    Sui.SigningInput input = Sui.SigningInput(
        privateKey: privateKeyHex.toUint8List(),
        signDirectMessage: Sui.SignDirect(unsignedTxMsg: txBytes));
    Sui.SigningOutput output = Sui.SigningOutput.fromBuffer(
        AnySigner.sign(input.writeToBuffer(), TWCoinType.TWCoinTypeSui)
            .toList());
    return sendTransaction(output.unsignedTx, output.signature);
  }
  
  List<String>? calculateObject(String amount, SuiCoinInfoList list) {
    var amountInt = BigInt.parse(amount);
    List<String> objects = [];
    var temp = BigInt.zero;
    if (list.data == null) {
      return objects;
    }
    for (var element in list.data!) {
      temp += BigInt.parse(element.balance);
      objects.add(element.coinObjectId);
      if (temp >= amountInt) {
        break;
      }
    }
    return objects;
  }
```

**Comment by vipbooy2019** [comment]
> **Tôi mới** sử dụng rung để phát triển ví sui, nhưng tôi không biết cách triển khai splitCoin. Ví dụ tôi có 5 sui, chia thành 5 đối tượng và tôi muốn gửi 4,5 sui đến các địa chỉ khác. Làm thế nào tôi có thể thực hiện nó? Là một cái gì đó giống như utxo được tính toán bởi máy chủ? Hoặc có một số cách rpc để tôi gọi?

0x140DB3CED09B697151F8f121306406C435a10588

**Comment by tuncatunc** [comment]
I would use rust sdk and bridge the rust library.

**Comment by tuncatunc** [comment]
I would use rust sdk and flutter rust bridge.

**Comment by wlmyng** [comment]
Closing as questions like these are better suited for the [developer forums](https://forums.sui.io/) or [Sui discord](https://discord.com/channels/916379725201563759/1006322742620069898)
