### ISSUE TITLE
Develop object focused tutorial series as codelab

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#1248]
Copied from slack:
from @lxfind 
Sui being a object-centric chain and most people's first series of questions on how to program it will be around when to choose different types of object relationships: wrapping vs owning, collection vs bag vs vector, shared vs owned, child object reference vs child object id and etc.
We have docs describing the concepts of each and the libraries, but it's hard to think about how to really use a combination of them in practice. Ideally they want to see them used in action and the trade-offs in code.
I am thinking about creating a "Programming with Objects" tutorial series, which is a series of tutorials on how to interact with objects with real examples, from the basics to advanced topics, e.g. from basic object transfers, to object wrapping, to object owning objects, to how to use collection/bag and etc. Each chapter will be focusing on one topic, and the difficulty level should build up.
What do you think?

**Comment by bwann52** [comment]
Empty files are causing errors when publishing, need a solution. @Jibz1 suggests: do not add incomplete content/files to the main branch.
cc @lxfind @Clay-Mysten

**Comment by lxfind** [comment]
Yeah we can remove the empty ones for now for sure

**Comment by Clay-Mysten** [comment]
Hi Xun, I'm slotting this in the TestNet milestone while triaging. Please feel free to move as you desire. Thanks!

**Comment by Clay-Mysten** [comment]
Let's rename move.md to Smart Contracts with Move Quick start:
https://docs.sui.io/build/move

This will be our codelab.

**Comment by Clay-Mysten** [comment]
+Godwin

Hi Xun,

I've created these PRs to replace relative links into example source files with absolute links:
https://github.com/MystenLabs/sui/pull/1902
https://github.com/MystenLabs/sui/pull/1903
https://github.com/MystenLabs/sui/pull/1904
https://github.com/MystenLabs/sui/pull/1905

Not sure why I can't add this issue to the Development field of those PRs. See this text file for the reported issues:
[404s-in-live-site.txt](https://github.com/MystenLabs/sui/files/8673663/404s-in-live-site.txt)

I've also added Godwin for this reported issue:
```
URL        `/img/Sui-logo-blue.png'
Parent URL https://docs.sui.io/_nuxt/css/9baafdd.css, line 4, col 70228
Real URL   https://docs.sui.io/img/Sui-logo-blue.png
Check time 2.864 seconds
Size       1KB
Result     Error: 404 Not Found
```
That image does exist on the main site though:
https://sui.io/img/Sui-logo-blue.png

Godwin, let me know if you want a distinct issue for that.

**Comment by Clay-Mysten** [comment]
And here is that one to link up chapter 4:
https://github.com/MystenLabs/sui/pull/1893

**Comment by Clay-Mysten** [comment]
Hi @lxfind , I am wondering if we should remove references to the later chapters since I recall you saying it will be hard to get to them soon. We can do that and close this out as complete, adding new material later as time allows. WDYT? Thanks!
