### ISSUE TITLE
Im lost my sui 

### ISSUE THREAD

**Issue by Linhnef** [MystenLabs/sui#12511]
because some reason when with draw my sui i transfer it to my private key, can i get my money. 
sorry i can't join sui discord to ask .
but i see the private key not a wallet but the transaction still success.

**Comment by Linhnef** [comment]
@randall-Mysten please support me, can i get my money

**Comment by Linhnef** [comment]
@bwann52 bw

**Comment by Linhnef** [comment]
no one support ?

**Comment by randall-Mysten** [comment]
you could try the Support Discord: https://discord.com/invite/mysten
