### ISSUE TITLE
Explorer: have a backend to fetch data for front end to display

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#1261]

**Comment by todd-mystenlabs** [comment]
I think for DevNet, we're just fetching straight from the Gateway Service (@stella3d, @lxfind - this is where we landed, right?)

I think for Pre-DevNet, we want to fetch from a replica node (@bmwill).

I don't think the production way of handling this is with an entirely different server.  I know there are some thoughts that the kind of data a Sui Explorer may want may benefit from being indexed differently, but I wouldn't add the complexity of another server just yet.  It's possible we can have a different indexing strategy (@lxfind / @velvia / @mystenmark) and maybe that will cover it as a slightly differently-configured replica or something.

Alternatively, maybe this represents a developer-only (and not a Sui Node) feature like @Jibz1 had been talking about?

**Comment by velvia** [comment]
Right, I think the intention is for the replica/fullnode to be able to serve queries on past data such as old Tx's, old objects at checkpoints, and events.  As such would expect for example event indexing in the storage layer, although maybe pubsub would be fine for a long time.

**Comment by lxfind** [comment]
One specific example, something that we want maybe right after devnet 
(refer to discussions in https://mysten-labs.slack.com/archives/C03ANU0BSGL/p1649713649021339) is to fetch all transactions that involve a specific account address (i.e. all transactions that touch an object owned by a specific address).
This definitely requires a secondary indexing/processing.

**Comment by bwann52** [comment]
in our triage process, would something like this count as feature enhancement or major feature? @todd-mystenlabs

**Comment by 666lcz** [comment]
@stella3d I'm closing this per our discussion in today's meeting as we are going to reuse Fullnode Read API as the backend instead of a dedicated Explorer backend
