### ISSUE TITLE
[explorer] Create Test Suite for Transaction Results

### ISSUE THREAD

**Issue by stella3d** [MystenLabs/sui#1264]
We need some example transactions for the explorer front-end to be developed with.

Get the data from these DBMaps in authority stores:
```effects: DBMap<TransactionDigest, TransactionEffectsEnvelope<S>>```
and
```certificates: DBMap<TransactionDigest, CertifiedTransaction>```

**Comment by todd-mystenlabs** [comment]
@stella3d, @Jibz1 - is this one covered?

**Comment by stella3d** [comment]
we have real data now, so the existing mock data needs to be updated

**Comment by Andrew47** [comment]
The Transactions Results are now connected to live data, which removes the short-term need that mock transaction data was required in creating the UI. There is still a need for mock transaction dataset which, as with addresses and objects, would be useful in supporting a testing suite for the Transaction Results UI. This issue has hence been broadened to cover the creation of a test suite for the Transaction Results.
