### ISSUE TITLE
Shared Object Deletion

### ISSUE THREAD

**Issue by lavindir** [MystenLabs/sui#12653]
### Deleting Shared objects

This feature will allow shared objects to be deleted whereas previously, only single owner objects had the ability to be deleted. This will allow the storage rebate to be claimed for unused shared objects. The storage rebate will be given to entity that submits the transaction that successfully deletes the shared object. 

In order to delete a shared object, we will have the ability to define an entry function that takes the shared object in by value. From within this function, authorization logic can be added to define who can delete the object, and under what circumstances it can be deleted. For example, the function which deletes a certain shared object may also take as input a designated single owner object whose possession allows the given user the ability to call the deletion function. 

Alternatively, a shared object may have the ability to be deleted by any user, but only after a specific attribute on the object itself has been added or meets a certain requirement. For example, a shared object might have a field that records the last updated time, or last accessed time. The deletion function can then check for a certain duration of inactivity on the object before allowing deletion. 

If multiple transactions were submitted concurrently that both delete and mutate a given shared object, the execution order of these transactions will be decided by consensus, and if a mutation was sequenced after the deletion, the transaction that mutates the previously deleted object will fail execution. The default base gas fee will be charged for this failed transaction in line with the standard pricing of transactions that fail execution.

### Implications for existing objects

If there is a module that defines an object type, and some of the instances of this type are shared, while some instances are owned, there may already be functions defined that take this object by value. Currently, if a transaction calls such a function with a shared object input, there will be a runtime error. After this feature is introduced, shared objects will also be allowed as input objects by value, so no runtime error will occur. This would now allow deletion of those shared objects if such logic was currently written in an existing function that deletes that input object. Besides this particular instance of object types that have both shared and owned instances and functions implemented that delete the owned instances, no changes to existing behavior will occur. 

### Limitations

While shared object will now have the ability to be deleted in the standard way, ie calling `object::delete(id)` they will not have the ability to be deleted via wrapping or to be transferred to a single owner. If we were to define a function that takes a shared object S as input by value and does something like `Wrapper { id: object::new(context), S }` this would case a runtime error, likewise if we were to attempt to transfer this object to a single owner `transfer::transfer(S, tx_context::sender(context))` this would also cause an error. We will also not support freezing of shared objects. If a shared object S was taken in by value but not deleted in the function, since shared objects do not have the drop ability, it must be “re-shared” within the function body via `transfer::share_object(S)` or `transfer::public_share_object(S)`.

**Comment by stefan-mysten** [comment]
This is now implemented and available, so closing this issue.
