### ISSUE TITLE
base64 encoding for Sui bytes in json

### ISSUE THREAD

**Issue by stella3d** [MystenLabs/sui#1266]
Currently, we encode Sui byte array types in JSON as `number[]`, but we could make this significantly more efficient network-wise if we switch to base64 strings.

32 byte signature:
as JSON array: **91 bytes**
```
[137,135,78,119,134,159,210,75,181,108,134,129,59,191,120,30,200,235,33,93,77,245,255,153,104,25,227,78,153,65,62,1]
```
as base64 string:  **52 bytes**
```
"iYdOd4af0ku1bIaBO794HsjrIV1N9f+ZaBnjTplBPgE="
```
which is **%57.1 of the size**.

base64's size overhead can also largely be [mitigated by gzip compression](https://blog.virtual-void.net/base64-vs-gzip/), so it compresses well.

**Comment by todd-mystenlabs** [comment]
@bmwill, @patrickkuo, @lxfind, @oxade, @stella3d  - we discussed this in the last couple weeks.  Did we end up resolving it? (i.e. Do we still have anything to do here?)

**Comment by gdanezis** [comment]
I suspect this is done and we can close this?

**Comment by patrickkuo** [comment]
> I suspect this is done and we can close this?

yes this is done!
