### ISSUE TITLE
[Move] Categorize MoveVM errors

### ISSUE THREAD

**Issue by tnowacki** [MystenLabs/sui#1270]
https://github.com/MystenLabs/sui/blob/6544c55a97eb571c2bbef9190e99a5c3b3325c04/sui_types/src/error.rs#L283

Errors from the Move VM should be categorized and dealt with based on the category. The code for the relevant category can be found:
https://github.com/diem/move/blob/main/language/move-core/types/src/vm_status.rs
This also indicates whether it should be a keep or a discard.

**Comment by todd-mystenlabs** [comment]
@tnowacki - what does keep or discard mean in this context?

**Comment by tnowacki** [comment]
Unsure if the terminology is used in Sui, but:
- Kept transactions modify the state/ledger 
  - If successful, some objects might be modified
  - If failed, no state changes are made
  - But in either case, the transaction is charged gas and it is recorded in the ledger 
- Discarded transactions make no modifications and are not recorded in any form

Based on my discussions with @oxade, I am actually unsure to what extent this happens at all in Sui right now, but it definitely is not happening correctly for errors coming from the MoveVM

**Comment by lxfind** [comment]
@tnowacki Could you give an example on what might lead to a Discarded transaction, and if we don't charge gas in that case, how to prevent DDos attack utilizing it?

**Comment by tnowacki** [comment]
cc @sblackshear since he can likely phrase all this better but...

> Could you give an example on what might lead to a Discarded transaction, and if we don't charge gas in that case, how to prevent DDos attack utilizing it?

The VM has a bug, hits some UNKNOWN_INVARIANT_VIOLATION_ERROR. You definitely don't want to charge for gas, because who knows what happened in the VM.
Gas is not *really* a DoS prevention mechanism, it is a sort of "pay for compute" mechanism that incentives efficient code, which as an effect might save you from some DoS attacks. But there are all sorts of cases where this doesn't hold up (really wealthy attacker, inaccurate gas costs, VM bugs, accounting bugs, etc).
You need to have other DoS prevention mechanisms, especially for the cases when things go wrong.

**Comment by tnowacki** [comment]
@bmwill, do you think this is sufficiently done in #2474?
I think we are good based on your PR, but just checking there isn't some other set of lingering issues here.

**Comment by bmwill** [comment]
Yes from the perspective of the VM and what errors we capture onchain we should be good. there is a larger question around what we want to do with SuiError but that can be looked at separately.
