### ISSUE TITLE
DevPortal: automatically catch and fix URL link errors

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#1274]
add email notification when checks fail, include Clay to email notification.

**Comment by todd-mystenlabs** [comment]
@Jibz1 - I think you and @Clay-Mysten may have worked this out already.  Is this Issue covered?

**Comment by Clay-Mysten** [comment]
> @Jibz1 - I think you and @Clay-Mysten may have worked this out already. Is this Issue covered?

Godwin is definitely catching broken links. I still need to be notified.

**Comment by Jibz1** [comment]
@Clay-Mysten you can subscribe to the https://github.com/MystenLabs/sui_dev_portal

**Comment by Clay-Mysten** [comment]
> @Clay-Mysten you can subscribe to the https://github.com/MystenLabs/sui_dev_portal

And what does that do? Can we start to write this stuff down somewhere?

**Comment by Clay-Mysten** [comment]
Let's also reconsider breaking site updates because of broken links. Makes this whole system fragile and impossible to stage forthcoming updates.

**Comment by bwann52** [comment]
Note: the fix does not impact external links and side menus

**Comment by huitseeker** [comment]
This is a template for a Github action that checks such links:
https://github.com/MystenLabs/sui/pull/1766
(it probably requires configuration & tuning for the dev portal)

**Comment by Clay-Mysten** [comment]
Thanks, Francois. This is now documented under Link check at:
https://app.golinks.io/dev-portal-work

**Comment by Clay-Mysten** [comment]
For example:
https://github.com/MystenLabs/sui_dev_portal/runs/6563235132?check_suite_focus=true
