### ISSUE TITLE
Sui doc content issue or request

### ISSUE THREAD

**Issue by traitmeta** [MystenLabs/sui#12831]
**New**.

https://docs.sui.io/build/programming-with-objects/ch2-using-objects
Option 2. Transfer the object

bug code: 
```move
{
    let object = test_scenario::take_from_sender<ColorObject>(scenario);;
    transfer(object, recipient);
    color_object::transfer(object, recipient);
};
```

**Comment by randall-Mysten** [comment]
Thanks @traitmeta - https://github.com/MystenLabs/sui/issues/12831
