### ISSUE TITLE
How do I get module's bytecode?

### ISSUE THREAD

**Issue by HappyTsing** [MystenLabs/sui#12877]
Only the disassembled bytecode can be seen in sui browser, and the disassembled code is also obtained through API sui_getObject. May I ask how to obtain the Package bytecode deployed on sui? I want to do some analysis on it.
I can get bytecode in Ethereum and aptos, but not in sui.

**Comment by amnn** [comment]
@HappyTsing , if you are using the `sui_getObject` RPC API, use the `showBcs` option to get the raw form of the bytecode (it will be base64 encoded as well), see for example this curl command to get the bytecode for the `sui::coin` module on testnet:

```
curl -LX POST  "https:/fullnode.testnet.sui.io:443" \
    --header 'Content-Type: application/json' \
    --data-raw '{
        "jsonrpc": "2.0",
        "method": "sui_getObject",
        "id": 1,
        "params": ["0x2", { "showBcs": true }]
}' | jq  -r .result.data.bcs.moduleMap.coin | base64 -d > /tmp/coin.mv
```

If you call `sui move disassemble /tmp/coin.mv` after running the command above, you can confirm it is the right module.

**Comment by HappyTsing** [comment]
> @HappyTsing , if you are using the `sui_getObject` RPC API, use the `showBcs` option to get the raw form of the bytecode (it will be base64 encoded as well), see for example this curl command to get the bytecode for the `sui::coin` module on testnet:
> 
> ```
> curl -LX POST  "https:/fullnode.testnet.sui.io:443" \
>     --header 'Content-Type: application/json' \
>     --data-raw '{
>         "jsonrpc": "2.0",
>         "method": "sui_getObject",
>         "id": 1,
>         "params": ["0x2", { "showBcs": true }]
> }' | jq  -r .result.data.bcs.moduleMap.coin | base64 -d > /tmp/coin.mv
> ```
> 
> If you call `sui move disassemble /tmp/coin.mv` after running the command above, you can confirm it is the right module.

Thank you very much! I used to think that BCS was also disassembled code, but just now I successfully obtained the bytecode using base64.b64decode(<bcs_code>) in Python! Thanks again.
