### ISSUE TITLE
Cannot retrieve balance changes: Error checking transaction input objects ...

### ISSUE THREAD

**Issue by nacrit** [MystenLabs/sui#12910]
## sui_getTransactionBlock: Cannot retrieve balance changes

RPC request exception, Request transaction cannot obtain balance change, Actually, This transaction has a change in balance.

### request:
`curl -X POST 'https://wallet-rpc.mainnet.sui.io' \
-H 'Content-Type: application/json' \
-d '{"jsonrpc":"2.0","id":1,"method":"sui_getTransactionBlock","params": ["6DNWZoxKc8Dbbsm6eqRhowk8YUV155SqJ3bLDkGVa9XW",{"showBalanceChanges": true}]}'`

### response:
`{"jsonrpc":"2.0","result":{"digest":"6DNWZoxKc8Dbbsm6eqRhowk8YUV155SqJ3bLDkGVa9XW","timestampMs":"1688745043522","checkpoint":"7066825","errors":["Cannot retrieve balance changes: Error checking transaction input objects: ObjectNotFound { object_id: 0x2f86921bf880424bf63830f1bea58a0e8b3be9255d0c495f08fbd68bfa1bf8f1, version: Some(SequenceNumber(6971160)) }"]},"id":1}`

**Comment by wlmyng** [comment]
Fullnodes with pruning enabled will be unable to serve historical data reliably, including object and balance changes.
