### ISSUE TITLE
Split up sui-types crate

### ISSUE THREAD

**Issue by kevinheavey** [MystenLabs/sui#12916]
I don't think this is news to anyone here but I didn't find an issue for it. The sui-types crate has a humongous list of dependencies, which is a problem if you just wanna use it for something small like parsing a Sui address.

My preferred solution would be to split up this crate into smaller crates and re-export those crates in sui-types

**Comment by mwtian** [comment]
cc @lxfind I think contributions are also welcome!

**Comment by stefan-mysten** [comment]
This has been slowly been addressed by @bmwill in https://github.com/MystenLabs/sui-rust-sdk/ but it is not fully integrated yet.
