### ISSUE TITLE
How much memory usage for stable running sui node?

### ISSUE THREAD

**Issue by lcgogo** [MystenLabs/sui#12921]
I see the sui node memory usage is more than 22GB and restart after it reaches the threshold I set for sui node

![image](https://github.com/MystenLabs/sui/assets/8175573/98dc25b4-b350-4294-82b5-dd40b3fe7b1f)

**Comment by blocknodehub** [comment]
seem problem, i found that 32gb was also not enough

**Comment by stefan-mysten** [comment]
You might need 128 GB according to the docs. 
https://docs.sui.io/guides/operator/sui-full-node#hardware-requirements

**Comment by lassikin** [comment]
Is there an ongoing expectancy for the required ram to double yearly? can anyone provide actual results of how much ram they have to run the node?

**Comment by stefan-mysten** [comment]
It shouldn't be the case. 

Could you try the steps in this comment?
https://github.com/MystenLabs/sui/issues/19180#issuecomment-2695867204
