### ISSUE TITLE
[MoveLib] Allow transferring a child object to Bag or Collection

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1294]
A child object is coupled with a ChildRef. Typically when we transfer this child object to another object or an account address, we have APIs that would consume the existing ChildRef.
However if we want to add this object to a Bag, Bag doesn't have an API that can take in a child ref.
Similar issues exist in Collection.

**Comment by todd-mystenlabs** [comment]
@lxfind - I think this issue is closed by the referenced PR, is that right?
