### ISSUE TITLE
New - request for a collaborative YouTube playlist on the Sui Network channel

### ISSUE THREAD

**Issue by georgescharlesbrain** [MystenLabs/sui#12978]
I manage a [collaborative YouTube playlist](https://www.youtube.com/playlist?list=PLIQc7_iETjBw-SNAbhrfB7RDufbJ5Bi21) that features high-quality YouTube videos from non-Sui Network accounts. I discovered these videos over time through Twitter, Discord, and blog posts. It is possible for anyone to add a video to my collaborative YT playlist using [this separate link](https://www.youtube.com/playlist?list=PLIQc7_iETjBw-SNAbhrfB7RDufbJ5Bi21&jct=bSpcs3u6yDDSSXqbrN0KASHid0vQnA).

Why did I create this list?  
It is a nuisance to find quality content by doing a [YouTube search for "Sui Network"](https://www.youtube.com/results?search_query=sui+network).

What is my suggestion?  
As a Sui user and developer, I would find it helpful if the Sui Network channel created a collaborative playlist of community-driven content. This would make it easier for me to find the best YouTube videos without having to sift through clickbait-filled search results. The [collaborative playlist feature](https://support.google.com/youtube/answer/6109639?hl=en) allows the playlist owner to have the final say over the content, so I don't anticipate any issues there.

All feedback welcome

**Comment by georgescharlesbrain** [comment]
Ow, it seems I actually did post the idea before but never got feedback. Apologies for that :).

**Comment by randall-Mysten** [comment]
I may have overlooked it, apologies
