### ISSUE TITLE
Improve the efficiency of Authority Aggregator

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1298]
The Authority Aggregator was not yet efficient because it would query pretty much everything in every case.
Obvious ones:
1. It doesn't consult the data we already have in the gateway, and hence will tend to query data that's already in the gateway
2. It doesn't attempt to optimize which authority to pick in each case when querying data, when for example we know which authority has the data we want and we could query that one specifically

Long-term ones:
1. We always query a quorum without sampling synchronously. This will become a problem when we have 100s of authorities
2. Certs are sent to all authorities, which is probably a over-kill in the long run

**Comment by todd-mystenlabs** [comment]
Any specifics here, @lxfind ?

**Comment by gdanezis** [comment]
This is an optimisation, that is not blocking -- but should happen when we have a full node / gateway client architecture.
