### ISSUE TITLE
[wallet CLI] Improve transaction results information

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1300]
1. Instead of showing ObjectRef, should we just show the Object ID? Do people actually care about version number and digest? We could also maybe allow configuring this through a verbose option (advanced devs like us might want to see the full ref, but typical users may just want to see the ID
2. "List of objects created by running module initializers:" can be confusing when this list is empty. We should make it explicit when it's empty.

**Comment by sblackshear** [comment]
+1 to not showing the ref. This information (especially digest) is not likely to be useful to a human.

**Comment by awelc** [comment]
I agree. Let's remember to update docs once this lands (@Clay-Mysten)

**Comment by oxade** [comment]
> has been talking with @oxade, he suggested we should return a ObjectSummary object (maybe ObjectRef + object type + other high level info) instead of just ObjectRef for more informative result.

@patrickkuo I actually have no personal opinion on this.
I would ideally prefer reducing over-the-wire tx, but from user feedback, some folks wanted a bit more info especially w.r.t created objects so they dont have to make another call to determine which object types.
So I would agree we need a default (object id only) and verbose (plus more fields) options.

**Comment by Clay-Mysten** [comment]
> I agree. Let's remember to update docs once this lands (@Clay-Mysten)

Thanks, Adam! Yes, please. Keep me posted, and I will work with you to take care of updates. Thanks, Xun!
