### ISSUE TITLE
[Rust SDK] Break dependency on storage and other core crates

### ISSUE THREAD

**Issue by nizam-supraoracles** [MystenLabs/sui#13018]
During the compilation of sui-sdk, it uses another internal library and then rocksdb as well.
It takes more time to compile, and my main concern here is the rocksdb library. It slows down the whole compiling process even though I don't need it

**Comment by stefan-mysten** [comment]
Thanks for flagging this @nizam-supraoracles. We're aware of the situation and we're trying to improve it.

**Comment by philipglazman** [comment]
+1 Running into really long compile times as well when trying to use `sui-sdk` and `sui-types` and seems that rocks-db is the big reason why

**Comment by wlmyng** [comment]
Thanks to @joyqvq 's efforts, `rocks-db` has been removed as a dependency from `sui-sdk` and `sui-types`. https://github.com/MystenLabs/sui/pull/15945
