### ISSUE TITLE
Move call failed

### ISSUE THREAD

**Issue by 0xAdherent** [MystenLabs/sui#13056]
[{"UserInputError":{"error":{"ObjectVersionUnavailableForConsumption":{"provided_obj_ref":["0x4842c54c048d099f635299584156a7ec48113d6eb5349a6ccf6932feb8dd6e6a",8698266,"C69F6gXNvwDdqh6RTFM1BdDbfSrjKnz7U6zeJg3zrsDn"],"current_version":8698267}}}}

**Comment by stefan-mysten** [comment]
@0xAdherent - is this still an issue?
