### ISSUE TITLE
[wallet CLI] use --no-shell by default

### ISSUE THREAD

**Issue by sblackshear** [MystenLabs/sui#1305]
By default, running `./wallet` drops into an interactive session. Many common uses of the wallet and tutorial are single-shot commands that all require `--no-shell` to avoid this behavior. Let's make `--no-shell` the default and use an explicit `--interactive` or `-i` to drop into a session.

**Comment by awelc** [comment]
Let's make sure we update the docs once this lands (@Clay-Mysten)
