### ISSUE TITLE
[wallet CLI] Display Owner and TransactionDigest as hex

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1306]
When running `wallet --no-shell object --id <ID> --json`:
Wallet CLI displays Owner address and TransactionDigest as an array of numbers.
We should just display a hex string for both of them.

**Comment by patrickkuo** [comment]
this PR fixes all bytes array serialisation problem for human readable serialiser https://github.com/MystenLabs/sui/pull/1304
