### ISSUE TITLE
docs navigation setup issue

### ISSUE THREAD

**Issue by georgescharlesbrain** [MystenLabs/sui#13092]
I have the impression that for a month or so, the "next button" is replaced with the "top of page button" on the docs.

e.g. When Im on the "Why Move?" page, I can't go to the next page via the buttons at the bottom. Are my UX expectations wrong?

![image](https://github.com/MystenLabs/sui/assets/72499006/fb62e62c-4f8b-4e71-bf1d-45b665547489)

**Comment by randall-Mysten** [comment]
Hi @georgescharlesbrain You're not wrong, the doc build is broken and has been for some time. Many of the links to source code go to the wrong branch as well. Sorry for this, but they've kind of paused updates on the site while awaiting a new site that has been delayed.

**Comment by ronny-mysten** [comment]
This is addressed with updated site.
