### ISSUE TITLE
@mysten/wallet-kit doesn't detect OKX wallet extension even it is installed.

### ISSUE THREAD

**Issue by rebelinnovator** [MystenLabs/sui#13114]
Hi. I use this code to detect installed wallet extension.

```
import { useWalletKit } from '@mysten/wallet-kit';
...
const { wallets } = useWalletKit();
console.log(wallets)
```

Unfortunately this can't detect OKX wallet extension even it is installed. Why is it?

**Comment by MapleDev423** [comment]
wallet-kit can't detect OKX wallet even OKX wallet code has been already injected.

![image](https://github.com/MystenLabs/sui/assets/67868337/01a4bba9-8a58-4074-a7f5-a4fccecf40b1)
![image](https://github.com/MystenLabs/sui/assets/67868337/d8bb47b9-a37d-4050-88a5-9cd14af27c3a)
![image](https://github.com/MystenLabs/sui/assets/67868337/5087d119-a8b9-464e-8bf4-e1a0b27a9542)

How could this happen?

**Comment by pchrysochoidis** [comment]
Hi @MapleDev423, I've tried to reproduce this but works fine for me using the latest [OKX wallet](https://chrome.google.com/webstore/detail/okx-wallet/mcohilncbfahbmgdjkbpemcciiolgcge) (2.55.2). 

<img width="394" alt="Screenshot 2023-07-24 at 16 36 00" src="https://github.com/MystenLabs/sui/assets/10210143/68841de3-5b9f-4eee-b193-2862457acbcc">


I used the example app for the wallet-adapters that can be found [here](https://github.com/MystenLabs/sui/tree/main/sdk/wallet-adapter/example) and I just added [here](https://github.com/MystenLabs/sui/blob/main/sdk/wallet-adapter/example/src/App.tsx#L10) the code to log the wallets.

Do you have some minimal repo, or a way for me to reproduce it?

**Comment by MapleDev423** [comment]
Could you kindly check this app? https://app.movex.exchange/

OKX wallet can't be detected. 

One thing strange is that same code is deployed to another Domain and OKX can be detected there.
https://movex-frontend.vercel.app/

Do you think what the root reason is?

**Comment by MapleDev423** [comment]
It works on local as well. @pchrysochoidis 

![image](https://github.com/MystenLabs/sui/assets/67868337/760ae7db-8f47-4fcb-91c8-2a2dd48b0faa)
