### ISSUE TITLE
[suix_multiTransactionBlocks] too many transactions.

### ISSUE THREAD

**Issue by bohyun-korbit** [MystenLabs/sui#13110]
Hi, Most of the transactions in the last block are game_8192. It takes too long to find the transfer history.

I'd like to filter game_8192 from the json-rpc API below and inquire.

Is there a filter function?
suix_queryTransactionBlocks
suix_multiTransactionBlocks

I want to inquire about transaction items except game_8192. (checkpoint: 8170899)

**Comment by coboywei** [comment]
i have the same trouble too, waiting for solution

**Comment by wlmyng** [comment]
You can filter transaction blocks on `MoveFunction`, but not the negation. Is it possible for you to adjust your filter? We also don't recommend using the public json rpc service for more intense work - it is meant more as a playground to familiarize with rpc endpoints. A dedicated rpc provider would be better suited for this task.
