### ISSUE TITLE
[Sui System] Please adding some getters to get read-only references of `ValidatorSet/Validator/StakingPool` instances

### ISSUE THREAD

**Issue by kevinz678911** [MystenLabs/sui#13118]
## Issue

In the SIP6, Sui added the below new getter method, and it's useful. But it only returns the validator addresses, not the Validator objects. So there is a gap between this getter and the public getters in module `validator_set\validator\staking_pool`, which require an object as input para. 

There are already some test-only getter methods which are `ValidatorSet/Validator` related in sui_system module, and they're very useful. However, we can't use them in product codes, for they're test-only.

```
    /// Getter returning addresses of the currently active validators.
    public fun active_validator_addresses(wrapper: &mut SuiSystemState): vector<address> {
        let self = load_system_state(wrapper);
        sui_system_state_inner::active_validator_addresses(self)
    }
```

## Request

For composability, we suggest to remove the test-only annotation, and at least adding these methods in sui_system module:
  1.  adding getters to get instance of `ValidatorSet`, so developers can utilize the public getters in module `validator_set`.
  2.  adding getters to get instance of `Validator`, so developers can utilize the public getters in module `validator`.
  3.  adding getters to get instance of `StakingPool`, so developers can utilize the public getters in module `staking_pool`.

**Comment by emmazzz** [comment]
Hey there! The reason we don't have public getters returning these types is for better upgradeability. Right now, types like `ValidatorSet`, `Validator` and `StakiingPool` are internal to the `sui_system` package. That means we can freely "upgrade" these structures by introducing new types. However, if public getters are introduced, we are committed to returning these types and won't be able to upgrade them easily (struct definitions cannot be changed during a package upgrade). Therefore we are very cautious about adding public functions in general, and especially if the function returns non-primitive types. 

We can still add getters that return specific fields of these structs though! Do you have anything specific in mind?
