### ISSUE TITLE
[RPC] - Gateway should deserialize object contents

### ISSUE THREAD

**Issue by kyleqian** [MystenLabs/sui#1313]
Currently the rest server outputs raw `ObjectRead` data for /api/object_info, as in:
```
"contents": "OFd2cCAFyXlxzUXP/dMQmHG+k1QAAAAAAAAAAKCGAQAAAAAA"
```

Ideally it should serialize to something readable, like json, similar to what the wallet CLI already does.

**Comment by todd-mystenlabs** [comment]
Are we keeping the rest server endpoints for devnet? I thought we were dropping the rest endpoints and going with json-rpc over https? 
cc: @lxfind @patrickkuo

**Comment by patrickkuo** [comment]
This endpoint will be port to JSON-RPC, instead of /api/object_info, the same functionality will be accessible via json RPC. We will remove the rest server after JSON-RPC is ready.

**Comment by gdanezis** [comment]
Ok, so we will never do this? Should we close the issue?

**Comment by kyleqian** [comment]
This isn't specific to REST api - it's about returning object contents in a readable format to clients.

**Comment by patrickkuo** [comment]
Lets keep this open to make sure we fix this in RPC

**Comment by patrickkuo** [comment]
Related to this https://github.com/MystenLabs/sui/issues/237

**Comment by patrickkuo** [comment]
this is fixed by https://github.com/MystenLabs/sui/pull/1440
