### ISSUE TITLE
Public S3 Bucket should not require credentials

### ISSUE THREAD

**Issue by philip-cbc** [MystenLabs/sui#13141]
## Steps to Reproduce Issue

1. Setup archival fallback with access to public S3 buckets without credentials

## Expected Result

Expected the SUI node to access the public S3 bucket but it errors stating that valid credentials with permissions are required

```
Jul 25 07:32:22 sui-xxx sui-node[44752]: 2023-07-25T07:32:22.767965Z ERROR sui_storage::object_store::util: Failed to read file from object store with error: Generic { store: "S3", source: GetRequest { source: Error { retries: 0, message: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>91J3389X5JW80Y7R</RequestId><HostId>vnSzMd6F9ZTBGFAr7Ru1dZwTW9NkzUdX26+hX9TSZp9jZ6AjgbXnqlgZwIvMJ4R3steijoMz2D4=</HostId></Error>", source: Some(reqwest::Error { kind: Status(403), url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("s3.us-west-2.amazonaws.com")), port: None, path: "/mysten-mainnet-archives/MANIFEST", query: None, fragment: None } }) }, path: "MANIFEST" } }
```

## Actual Result

Sui should be able to access public S3 buckets with no credentials

**Comment by mwoodson-cb** [comment]
It appears that the data from these S3 buckets are exposed publically.  Here is a URL

[Testnet](https://mysten-testnet-archives.s3.us-west-2.amazonaws.com/)

[Mainnet](https://mysten-mainnet-archives.s3.us-west-2.amazonaws.com/)

Having to use credentials is an unnecessary requirement.
