### ISSUE TITLE
Sui documentation is outdated & does not work

### ISSUE THREAD

**Issue by csknk** [MystenLabs/sui#13180]
[Re https://docs.sui.io/devnet/build/rust-sdk](https://docs.sui.io/devnet/build/rust-sdk#example-1---get-all-objects-owned-by-an-address)

The code example does not work - `get_owned_objects` now requires 4 parameters, rather than a single `address` argument.

**Comment by randall-Mysten** [comment]
Hi @csknk, Sorry, we are actively working on a whole new set of examples for the Rust SDK. We definitely missed updating some of the code samples in docs to align with the significant changes to Sui in the last few months. Thanks for taking time to let us know, and also for your patience.

**Comment by stefan-mysten** [comment]
Some basic examples on how to use the Rust SDK should come in a few days. I will post here when they're merged into the main branch. Thanks for your patience!

**Comment by stefan-mysten** [comment]
The basic examples for the Rust SDK has been merged into main (#13047). Check out the examples folder in the [sui-sdk](https://github.com/MystenLabs/sui/tree/main/crates/sui-sdk) crate.
