### ISSUE TITLE
Change object storage to use ObjectDigest or (ObjectID, version) as primary key

### ISSUE THREAD

**Issue by velvia** [MystenLabs/sui#1318]
Currently, the objects table in SuiDataStore uses `objectID` as the primary key.    Since objects have many different versions, it means that this table only keeps the "latest" objects.    There are some issues with the current setup:

* **Writes are not idempotent**.  This is a safety issue, because it means replaying an old transaction could result in an older object overwriting a newer object.   Code must be written to ensure proper ordering of writes, which adds complication.
    * This is currently protected using a critical region and locks.  However, as the system scales out, critical regions and locks become more difficult to maintain.
    * Idempotent writes are critical for modularity and separating out components such as a lock service.  It means things may be stored in different components and batches can no longer be used everywhere.
    * Idempotent writes means ordering matters much less.
* **Locking is required to protect writes**.  See issue above.  Locks also can create performance problems, though this is not a current bottleneck.
* **objectID is not cacheable**.  Lets say we were to use a distributed object store and wanted to cache object reads.  If we use objectID by itself, one does not know the version of the object one is getting back.  This makes caching impossible because one cannot know when the underlying object changes.
* **checkpoint support**.  Supporting checkpoints will require storing multiple versions of objects.   This could be done with another table but that makes things messy, because to read a checkpoint objects one might have to span two tables then.
* Gateway stores all versions of objects currently and requires a separate table and separate code.  

The proposal here is to move to one of the following as a primary key for the objects table:
1. `(ObjectID, SequenceNumber)`
2. ObjectDigest

The primary key must be guaranteed unique for any possible new object.  It is possible that a weaker guarantee is fine for the subset of objects that lives together at the same time in one authority/gateway/etc.

When we write a new object, we would have a policy that decides whether to delete the older object. 
* Gateways would not delete the old object
* When we make a checkpoint, we would just not delete the older object.  One way of checking this is that if the current checkpoint number is higher than the checkpoint number in the object, we would just not delete it in the authority.
* Otherwise delete the old object

/cc @sblackshear @lxfind @oxade @gdanezis

**Comment by velvia** [comment]
So the key question here is which one we should use for the primary key.

(ObjID, version) has the advantage that one could scan through all the versions of a given ObjID quickly.

**Comment by lxfind** [comment]
Overall the idea makes sense to me.
One thing you might find it challenging to deal with is object deletions. Currently when an object is deleted we just remove it from the `objects` table and it's easy to tell. But with (ID, Version) key I think it would be a bit tricky.

**Comment by velvia** [comment]
@lxfind 

> we just remove it from the objects table and it's easy to tell. But with (ID, Version) key I think it would be a bit tricky.

I guess the question is how we want to expose object deletions to a user.  Maybe through events?

**Comment by lxfind** [comment]
Not just about what to expose to a user (which is the easier part, we already have it in the transaction effects). It's about when authority receive a new transaction, it needs to check whether an object is in the store.
I think you will hit this once you start working on it and the issue will be clearer.

**Comment by gdanezis** [comment]
Yes, I like this proposal. In fact this is how we intended the validator to operate to start with, but the objectID indexing was used instead to also allow for latest object indexing and deleting older objects, in a unified way. Now, we would benefit from disentangling these for all the reasons mentioned.

**Comment by gdanezis** [comment]
In terms of the option 1 vs option 2: I have a mild preference for `(ObjectID, SequenceNumber)`. This allows us to garbage collect older objects, as well as potentially down the line do object based sync using the keys only, rather than having to deserialize full objects. This is mild however.
