### ISSUE TITLE
How to get current storage cost constants programmatically?

### ISSUE THREAD

**Issue by Yolley** [MystenLabs/sui#13225]
In the documentation https://docs.sui.io/build/sui-gas-charges#transaction-output-gascostsummary you provide a formula for storage costs calculation, and there are couple of constants - `storage_normalizer` and `storage_price`. These may be changed at some point, and in the doc it's not clear whether it's possible to get updated values programmatically (either via JSON rpc call or ideally inside a contract). These values may be needed if we want to calculate expected storage fees needed to store an object create by a contract. Is it possible to get these values somehow inside a contract or at least via JSON rpc call?

**Comment by dariorussi** [comment]
@oxade @amnn should be able to provide mechanism for now and the future around this.
Those should all be retireved by loading the protocol config info

**Comment by oxade** [comment]
> @oxade @amnn should be able to provide mechanism for now and the future around this. Those should all be retrieved by loading the protocol config info

Indeed you can get the protocol config info via RPC. See [sui_getProtocolConfig](https://docs.sui.io/sui-jsonrpc#sui_getProtocolConfig).
However @dariorussi regarding the constants `storage_normalizer` and `storage_price`  which @Yolley asked for:
I see `storage_gas_price` in the protocol config but not `storage_normalizer`

**Comment by oxade** [comment]
> I see, thank you. So it is possible to get these options via RPC, but inside a Smart Contract it's not?

Correct.
You can always get the value from RPC and pass it into your function/smart-contract.
