### ISSUE TITLE
[Move devex] Make module initializer statically verifiable

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1323]
Currently we dynamically check if a Move function satisfies the conditions of being an initializer, and if so, we run it during module publish.
This is error-prone and could lead to bugs/surprises.
We should just enforce that all module initializers must have a special name, like `__init__`, and it can be `public` so that we could also call it in tests.

**Comment by todd-mystenlabs** [comment]
@tnowacki - I think you're already doing this, right?  I thought I saw a PR fly by that added the requirement to flag initializers explicitly.

@lxfind - also assigned to you to make sure this covers what you were looking for.

**Comment by lxfind** [comment]
@tnowacki added explicit entry function declarations.
We should also make module initializers explicitly defined and statically verifiable, which is this issue. So I think it hasn't been done yet.

**Comment by awelc** [comment]
Implemented in https://github.com/MystenLabs/sui/pull/1532
