### ISSUE TITLE
[sui client] sui client upgrade upgrade_error: PackageIDDoesNotMatch since testnet sui 1.6.2

### ISSUE THREAD

**Issue by kevinz678911** [MystenLabs/sui#13246]
## Steps to Reproduce Issue

execute the below command, and got `upgrade_error: PackageIDDoesNotMatch`, these commands can work in older versions.

```
$ sui client upgrade --gas-budget 300000000 --upgrade-capability 0xc75e785879dc55cddf476f71a944d03856a79e122252cd4561bbbcf97d5fs protocol
......
Successfully verified dependencies on-chain against source.
Error executing transaction: Failure {
    error: "PackageUpgradeError { upgrade_error: PackageIDDoesNotMatch { package_id: 0xf086e1bc894beb1c60c42d681dedfd27f1ec40e147d6a1b32fa3d47ae85, ticket_id: 0xe95f811df417b1e5789273f5e96d4c700f6a2c63c8ff13c7840f27bf7ad } } in command 1",
}


```

## System Information

* OS: Mac

**Comment by bityou88888** [comment]
so why? i have same condition

**Comment by stefan-mysten** [comment]
Hi @bityou88888 
Could you please share a few more details about your setup? 
OS, Move.toml, network, sui version (`sui -V`). 

Thanks!

**Comment by bityou88888** [comment]
@stefan-mysten 
I have solved this problem. It seems that the problem is that Move.lock is not synchronized with the latest packageID. It can be solved by deleting Move.lock or manually updating the address in the file.
Tks！
