### ISSUE TITLE
[bug] Unable to compile Move project due to `coin.move` 

### ISSUE THREAD

**Issue by shouc** [MystenLabs/sui#13263]
## Steps to Reproduce Issue

`sui move build` any project

Introduced by this commit: https://github.com/MystenLabs/sui/commit/5e6d2332308d8a425c4e057e89af93733e772f47

## Expected Result

Sucessfully build the project 

## Actual Result

```
error[E10003]: invalid attribute value
    ┌─ /root/.move/https___github_com_MystenLabs_sui_git_main/crates/sui-framework/packages/sui-framework/sources/coin.move:421:7
    │
421 │     #[allow(unused_field)]
    │       ^^^^^^^^^^^^^^^^^^^ Unknown warning filter 'unused_field'

Failed to build Move modules: Compilation error.
```

## System Information

* OS: macOS & Ubuntu
* Compiler: sui-move 0.1.0

**Comment by lwhile** [comment]
Upgrade sui cli can solve this problem.

**Comment by sblackshear** [comment]
Indeed, re-running `cargo install --path ~/sui/crates/sui` should fix this
