### ISSUE TITLE
[MoveLib] Properly authenticate owner in TestScenario::remove_nested_object

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1328]
The current native implementation of `TestScenario::remove_nested_object` doesn't authenticate the owner of the parent object. We should do that.

**Comment by todd-mystenlabs** [comment]
@lxfind - what's the scope of where TestScenario is used? Is it part of our test framework?  Trying to figure out where this slots into milestones.

**Comment by lxfind** [comment]
Yes it is part of our test framework.
None of the Move related tasks blocks DevNet I guess. I considered this one high priority among move devex tasks because I have seen our own engineers have bugs in Move example code because of this issue.

**Comment by lxfind** [comment]
This is done
