### ISSUE TITLE
[Move devex] Rename all module names to lower case

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1329]
Something like `use Sui::TxContex::{Self, TxContext}` could be confusing, as the module name is the same as the struct name in it.
This is everywhere throughout our framework.
Most languages (Rust, Python, Java and etc.) try to have module name lower case to not confuse with type names.
We should do the same for both Sui framework and Stdlib.

**Comment by tnowacki** [comment]
@lxfind, not sure what you want to do about this. 

We can do this, but it will be tricky for starcoin, depending if/when they want to update their stdlib

**Comment by tnowacki** [comment]
@awelc and @sblackshear, not sure if either of you have anything to add from this discussion from last external Move sync

**Comment by lxfind** [comment]
Yeah at this point, I don't know if the value would be worth the churn, given there is already production Move code.

**Comment by tnowacki** [comment]
I think we should still try to push for it if we can. Maybe worth pinging star coin folks about about it. Because it affects the only if they are updating modules on chain

**Comment by tnowacki** [comment]
(and theoretically they could just publish both versions...)
