### ISSUE TITLE
Error executing `cargo install` command: No function or associated item named `random_for_testing_only`

### ISSUE THREAD

**Issue by apollx-apx** [MystenLabs/sui#13473]
## Steps to Reproduce Issue

1. Execute command: `cargo install --git https://github.com/MystenLabs/sui sui --branch main`

## Expected Result

Expected the command to successfully install the package.

## Actual Result

Error encountered during installation:

```
error[E0599]: no function or associated item named `random_for_testing_only` found for struct `SuiAddress` in the current scope
   --> crates/sui/src/zklogin_commands_util.rs:109:25
    |
109 |             SuiAddress::random_for_testing_only(),
    |                         ^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `SuiAddress`
```

## System Information

* OS: MacOS 13.4.1
* Compiler: cargo 1.71.1

**Comment by dalveytech-zero** [comment]
I had the same problem

**Comment by dalveytech-zero** [comment]
I had the same problem, bro, have you found a solution

**Comment by narutomanchester** [comment]
Me too,i got the same issues. Anyone have a solution yet

**Comment by AleksanderBorovoy** [comment]
the same problem on ubuntu

**Comment by AleksanderBorovoy** [comment]
it has been fixed with  https://github.com/MystenLabs/sui/releases/tag/devnet-v1.8.1
