### ISSUE TITLE
Suggested Release Statement

### ISSUE THREAD

**Issue by fylsan3** [MystenLabs/sui#13499]
When publishing a version, you can add a note in the statement that this is a minor optional version or a version that must be updated! to remind us that it is time to update the version in advance.

**Comment by randall-Mysten** [comment]
Hi @fylsan3 Thanks for submitting your idea.

@ebmifa Do we release optional updates for Mainnet?

**Comment by ebmifa** [comment]
@randall-Mysten no we don't. All updates to mainnet are required, especially after the epoch change.
