### ISSUE TITLE
[wallet CLI][devnet] new-address causes wallet CLI to stop working

### ISSUE THREAD

**Issue by kyleqian** [MystenLabs/sui#1350]
When connected to devnet, running `wallet new-address` (which succeeds) causes every subsequent `wallet` command to result in the following:
```
Error: Too many authority errors were detected: [(k#4b3a2565f82edb628c7411e0f5a2d93753cc358aa0cc287f0649e63ad5cd284f, InvalidDecoding), (k#bf96d38a584bca4fc3824373cf238998467e7e6b566bc4b9da5b692dc875dc1e, InvalidDecoding), (k#b05dd3049a4c27488fd8138cadc0692f845f0d0fb194e66dc60a51ff66185f28, InvalidDecoding), (k#e63e4cfbd2cb9caebcf24c16a27f5d152d57c781f4df8a50bccf86bdba0cd316, InvalidDecoding)]
```

Repro steps:
* Start with an empty Sui config directory at `~/.sui/sui_config`
* Create a new `wallet.conf` file in there as specified in [this devnet doc](https://docs.google.com/document/d/1Pskfn_jf_eOhHDTNe0DnWNI90iEULBP_37HAJBLw3hU/edit#)
* Run `wallet new-address`, and observe it complete without an error
* Run any `wallet` command afterwards and observe the above error

**Comment by todd-mystenlabs** [comment]
@patrickkuo - any thoughts on what's happening here?

**Comment by oxade** [comment]
@todd-mystenlabs  this is also a known issue
There is a fix Kyle and I found. Will talk to @patrickkuo about it.

**Comment by oxade** [comment]
PR fix here https://github.com/MystenLabs/sui/pull/1448
