### ISSUE TITLE
[devnet] faucet is broken

### ISSUE THREAD

**Issue by kyleqian** [MystenLabs/sui#1351]
The [devnet faucet](https://docs.google.com/document/d/1Pskfn_jf_eOhHDTNe0DnWNI90iEULBP_37HAJBLw3hU/edit#heading=h.ai81cve0yn92) seems to be broken.

```
> curl "http://52.73.103.71:8080/give_gas?recipient=51B57E507886B91E6DDF1AFAF66E7DE347552EB8"

curl: (7) Failed to connect to 52.73.103.71 port 8080: Connection refused
```

Not sure if the error is related to #1350, where I can't properly create a new address.

**Comment by todd-mystenlabs** [comment]
Hey all - any thoughts on what's going on here? Is there a service we're supposed to be running that has either changed or is not running?

**Comment by mystenmark** [comment]
The only thing I've heard about a devnet faucet is that "it would probably be a good idea to have one". I had no idea there already was one. For that matter, there isn't really even a devnet yet, so why would we expect this to work already?

Adding @oxade

**Comment by lxfind** [comment]
Context of the current faucet: https://mysten-labs.slack.com/archives/C02GD7J9HUM/p1647834788607009

**Comment by oxade** [comment]
@todd-mystenlabs 
Faucet being down is known issue. It was taken down while we redesign devnet setup
I simply asked Kyle to create this issue for tracking purposes.
Please do not be alarmed.

**Comment by 666lcz** [comment]
Duplicate with https://github.com/MystenLabs/sui/issues/1387
