### ISSUE TITLE
Sui chrome wallet feature request

### ISSUE THREAD

**Issue by georgescharlesbrain** [MystenLabs/sui#13569]
product feature request
I would like to be able to name an address in the wallet.

**Comment by pchrysochoidis** [comment]
Closing this as account nicknames are implemented in the latest release `v23.9.25.0`


https://github.com/MystenLabs/sui/assets/10210143/2dd6b519-e5f2-4dd4-9628-c3240c100633


https://github.com/MystenLabs/sui/assets/10210143/60518953-3738-4bcd-93d9-8f2d8db6f5b6
