### ISSUE TITLE
Explorer: Update Instructions for Connecting SuiExplorer to localnet

### ISSUE THREAD

**Issue by Andrew47** [MystenLabs/sui#1357]
This follows up on an issue raised by @kyleqian regarding the instructions here: https://github.com/MystenLabs/sui/tree/main/explorer#data-source--rpc-url

**Comment by Andrew47** [comment]
@kyleqian provided the following error message:

![image](https://user-images.githubusercontent.com/11377188/163226058-2b4430bc-910e-4ed6-8285-2d1591171a26.png)


@kyleqian --> To fix this issue, we will need details on how to replicate the above error message. We will then be able to trial several approaches to find a solution. In particular, we will need details on:

* What is the SuiExplorer URL that raises the described error? 
* Which API are you trying to connect to?
* What JSON data does the API deliver when given a correct query?

The error `data.objects.map` is not a function suggests there is something unexpected regarding the structure of the JSON data being returned by the API.

**Comment by kyleqian** [comment]
Repro:
1. Start local Sui via `sui genesis` and `sui start`
2. Start local rest server via `ACCESS_CONTROL_ALLOW_ORIGIN=* rest_server`
3. Start local explorer
4. Visit `http://localhost:3000/?rpc=http%3A%2F%2F127.0.0.1%3A5001%2Fapi`
5. Search any object id (I used one of my address's gas objects)
6. I believe for that specific error, I was expecting an empty array, because it lists owned objects of that object, which were were none.

Deviation from instructions:
1. Appended `api` to the end of the RPC address
2. Used port 5001 instead of 5000
3. The site didn't seem to "remember" my RPC setting between refreshes, so I had to make sure the the RPC address in the url params was there every time I searched

**Comment by Andrew47** [comment]
@kyleqian --> The problem is that there is a mismatch between the deployed endpoints for the https://demo-rpc.sui.io API and the local endpoints when `rest_server` is run. The SuiExplorer Website was created based on the API endpoints for https://demo-rpc.sui.io/.

Take for example how the objects on an address are found. 

For demo-rpc.sui.io, the following endpoint works: https://demo-rpc.sui.io/objects?address=09818aac3edf9cf9b006b70c36e7241768b26386.

For `rest_server`, the successful endpoint is instead http://127.0.0.1:5001/api/objects?address=8EB212D032C99CDCA910E42E63985A7257C45828.

The solution is to restore consistency between what is delivered locally by `./sui/src/rest_server.rs`, deployed across the Internet by `https://demo-rpc.sui.io` and expected by SuiExplorer at `explorer/client/src/utils/api/SuiRpcClient.ts`.

@stella3d --> We will require one of the Backend API Engineers to take a look at this. It looks like one possible solution could be to remove the added `api` strings from file `./sui/src/rest_server.rs`. For example switching `"/api/objects"` for `"/objects"` in line 174 and `"/api/object_info"` for `"/object_info"` in line 258. This would avoid the need for downtime for the deployed website.

**Comment by todd-mystenlabs** [comment]
This feels like a DevNet fix.

**Comment by todd-mystenlabs** [comment]
@stella3d / @Andrew47  - do we have a GitHub issue filed for the backend side of this?

**Comment by 666lcz** [comment]
@stella3d assigning this to you per [Andrew's comment](https://github.com/MystenLabs/sui/issues/1357#issuecomment-1099337857) above. Let me know if you are not the right owner

**Comment by Clay-Mysten** [comment]
Hi team,

I'm working on:
https://github.com/MystenLabs/Prose/issues/23

And noting the call to link to Explorer URLs and docs. For reference, from:
https://docs.sui.io/explore#sui-explorer

We link to:
https://github.com/MystenLabs/sui/tree/explorer-rest/explorer
https://github.com/MystenLabs/sui/tree/explorer-rest/explorer/client

It looks like we should instead link into:
https://github.com/MystenLabs/sui/tree/main/explorer
https://github.com/MystenLabs/sui/tree/main/explorer/client

If so, I can take care of that. Please confirm. Yet I can see many references still to REST in the first README. Will those change? We are replacing them everywhere else, as in:
https://github.com/MystenLabs/sui/issues/1672

Further, Sam is linking to these URLs from a forthcoming announcement:
http://gateway.devnet.sui.io/
http://explorer.devnet.sui.io/

And I want to make sure they will be live as I will also link to them from the page coming in:
https://github.com/MystenLabs/sui/pull/1723

Please advise. Thanks!

**Comment by 666lcz** [comment]
https://github.com/MystenLabs/sui/pull/1771 closes this issue.

> It looks like we should instead link into:
[https://github.com/MystenLabs/sui/tree/main/explorer](https://github.com/MystenLabs/sui/tree/main/explorer?rgh-link-date=2022-05-02T22%3A36%3A51Z)
[https://github.com/MystenLabs/sui/tree/main/explorer/client](https://github.com/MystenLabs/sui/tree/main/explorer/client?rgh-link-date=2022-05-02T22%3A36%3A51Z)


@Clay-Mysten , I removed the client doc and you can change the following paragraph in https://docs.sui.io/explore#sui-explorer

Navigate the [Sui Explorer](https://github.com/MystenLabs/sui/tree/explorer-rest/explorer) and [Sui Explorer Client](https://github.com/MystenLabs/sui/blob/explorer-rest/explorer/client) to see the latest blocks, transactions, and cluster statistics.

to 

Navigate the [Sui Explorer](https://github.com/MystenLabs/sui/tree/main/explorer/client#readme) to see the latest transactions and objects.

where it now points to https://github.com/MystenLabs/sui/tree/main/explorer/client#readme
