### ISSUE TITLE
[MoveLib] `TestScenario::remove_object_by_id` is not usable

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1358]
`TestScenario::remove_object_by_id` requires knowing the object ID to call it.
However, most of the time when we create a new object (if the object type is not defined in the test module), we don't actually know the object ID. Hence there is no way to call it.
We likely need a native function that can return the newly created object ID from the inventory.

**Comment by todd-mystenlabs** [comment]
Any guess as to which milestone we want this for?

**Comment by lxfind** [comment]
Probably DevNet given I already have a PR pending
