### ISSUE TITLE
There's something wrong with the compilation. It wasn't there before.

### ISSUE THREAD

**Issue by ybeetle8** [MystenLabs/sui#13614]
cargo install --locked --git https://github.com/MystenLabs/sui.git --branch main sui

error:

running: cd "/tmp/cargo-install6nKCYM/release/build/jemalloc-sys-1b5a40304b1640ba/out/build" && "make" "-j" "56"

  --- stderr
  thread 'main' panicked at 'failed to execute command: No such file or directory (os error 2)', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jemalloc-sys-0.5.2+5.3.0-patched/build.rs:326:19
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to compile `sui v1.10.0 (https://github.com/MystenLabs/sui.git?branch=main#43df66ad)`, intermediate artifacts can be found at `/tmp/cargo-install6nKCYM`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by ybeetle8** [comment]
The system I'm using is ubuntu.

**Comment by randall-Mysten** [comment]
have you confirmed that you have the latest version of Rust installed?
`rustup update stable`

**Comment by stefan-mysten** [comment]
@ybeetle8 are you still running into issues when trying to compile?

**Comment by stefan-mysten** [comment]
@ybeetle8 If this is still a problem, please do let us know. I will close the issue for now.
