### ISSUE TITLE
Refactor Build documents to match common flow

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#1362]
While working through the critical user journeys of our users in issue #1065, we settled upon an ideal flow for primary audience, app developers, and will now set about making these changes from the current list from a flat list of:
Build
- Install Sui
- Write Smart Contracts with Move
- Create Sui Wallet
- Use Sui REST Server
- Employ SuiJSON Format
- Understand Authorities
- Manage Objects
- Conduct Transactions

To an ordered list of:
1. Install binaries
2. Start local network (rename or split from REST Server)
3. Connect to network with Wallet
4. Write Smart Contracts with Move
   a. Write a package
   b. Test a package
   c. Debug a package
   d. Publish a package
5. Programming with Objects (new tutorial series from Xun)
    a. All chapter sub-pages
    b. Existing tutorial
    c. Solana-like tutorial? (Kyle investigating)
6. Build dApps
7. Use Sui REST Server
8. Employ SuiJSON Format

See details in:
app.golinks.io/programming-objects-series-notes

Note, this will require searching (grep) through all files for each section header, as well as file, affected since we link deeply into our Learn and Build contents.

Much more to come.

**Comment by Clay-Mysten** [comment]
Godwin, I'm adding you to this and PR #1363 to ensure we can indeed have three levels in the left navigation.

**Comment by Clay-Mysten** [comment]
I've started with the Build index. How does this look?
https://github.com/MystenLabs/sui/pull/1530

**Comment by Clay-Mysten** [comment]
Noting more work to do while in here. Thanks to Xun for highlighting it. From:
https://mysten-labs.slack.com/archives/C02GD7J9HUM/p1652297426678019

Damir asked how to run a local node and a gateway. Xun referred him to:
https://github.com/MystenLabs/sui/blob/main/doc/src/build/wallet.md#starting-the-network

But noted that doc is now mixing steps between connecting a wallet to the DevNet network and starting the network locally, which we should separate.

Related, Chris offered up:
https://docs.sui.io/build/json-rpc

So I will make sure we properly link to it when addressing this flow.

**Comment by Clay-Mysten** [comment]
Related to the comments above, we agreed in our Sui Tools Ecosystem Sync meeting today:
* If a user connects to DevNet now, they need only wallet binary
* If they want to conduct local development, they need the wallet and sui binaries

Sam suggests wallet is renamed to:
Sui

And Sui becomes:
Sui-node

Adding @sblackshear to correct me if I got that wrong. (Patrick is already on this issue.)

**Comment by Clay-Mysten** [comment]
I'm noting we moved the Objects, Validators, and Transactions pages to the Learn section (sub-sections, rather) tracked in:
https://github.com/MystenLabs/sui/issues/1363

**Comment by Clay-Mysten** [comment]
Lu has excellent input here that should feed our Build docs work:
https://app.golinks.io/local-net-flow

**Comment by Clay-Mysten** [comment]
@longbowlu let's revisit:
https://app.golinks.io/local-net-flow

Perhaps we can take it up in our one-one-one tomorrow.

In related news, I got the go ahead from Xun today (and previously, Adam) to break up the `move.md` file. So I have captured the links into the file and its sections in the attachments here:
[move-file-refs.txt](https://github.com/MystenLabs/sui/files/8953255/move-file-refs.txt)
[move-file-anchors.txt](https://github.com/MystenLabs/sui/files/8953259/move-file-anchors.txt)

They will need updating as part of this work. We should add a redirect from `build/move.md` to `build/move/index.md` too.

**Comment by Clay-Mysten** [comment]
And see related `wallet.md` discussions in:
https://github.com/MystenLabs/sui/issues/2058#issuecomment-1166052928

**Comment by Clay-Mysten** [comment]
Per our CUJ meeting:

Xun says to join Write Smart Contracts with Move and Program with Objects contents in the same section

And work with Damir on reorganization going forward.

I'm also asking Todd N. to review the Move docs too.

**Comment by Clay-Mysten** [comment]
Also, similar to Lu's doc above, we have this external doc:
https://cryptech-nodes.medium.com/sui-installation-bff21222bcad

@randall-Mysten is going to reach out to the author to see how we might work with them to keep it updated. Then we can cross link to it ourselves and further the ecosystem. Thanks, Randall!

**Comment by Clay-Mysten** [comment]
Here I am starting to break down Move doc into sub-pages #3319:
https://github.com/MystenLabs/sui/pull/3319/files

We will still need to:
1. Update navigation and the landing page.
2. Update inline links to all sub-sections.
3. Announce on Learn > See what's new and perhaps Discord to mitigate confusion.

**Comment by Clay-Mysten** [comment]
Alright team, here are the three initial PRs to split up the move.md file into sub-pages:
https://github.com/MystenLabs/sui/pull/3319
https://github.com/MystenLabs/sui/pull/3347
https://github.com/MystenLabs/sui/pull/3348

I have no doubt I am missing things. We can follow up with more grep and fix. Asking @randall, @Adam, @Xun Li, @Patrick Kuo to review plus @Godwin Jibs on the nav PR (#3348). Also, @Godwin Jibs, I am respectfully requesting a redirect from doc/src/build/move to doc/src/build/move/index in this file:
https://github.com/MystenLabs/sui_dev_portal/blob/main/firebase.json
Thanks!

**Comment by Clay-Mysten** [comment]
> I left a comment on the article as I saw no one to direct message.

**Comment by punwai** [comment]
In the Build section of the Sui docs, we should, IMO replace every instance of 'main' with 'devnet.' It is really confusing for people that certain files are devnet (i.e. suggested binaries), and others are main (e.g. when you do `sui move new` it references the `sui` module on main). I can attest that this is a problem that I myself, and 2 other friends have faced, and it all took us a while (for my friend it took him several hours because he didn't understand Sui's code) to fix this.

**Comment by punwai** [comment]
I think it doesn't matter which branch we reference, we just cannot have users install two conflicting versions of sui on any piece of tooling.

**Comment by punwai** [comment]
IMO, same with the content we push onto the site, for example, while devnet was still in VersionedID, the docs was mentioning about using Info.

**Comment by Clay-Mysten** [comment]
> In the Build section of the Sui docs, we should, IMO replace every instance of 'main' with 'devnet.' It is really confusing for people that certain files are devnet (i.e. suggested binaries), and others are main (e.g. when you do `sui move new` it references the `sui` module on main). I can attest that this is a problem that myself, and 2 other friends have faced, and it all took us a while (for my friend it took him several hours because he didn't understand Sui's code) to fix this.

Yeah, we tried the inverse first and then users were trying to fix all of the errors in the `devnet` world we had long fixed in the `main` branch. See this issue for the real fix:
https://github.com/MystenLabs/sui/issues/1244
Adding @Jibz1 for urgency.

**Comment by Jibz1** [comment]
👀

**Comment by Clay-Mysten** [comment]
Related work:
https://github.com/MystenLabs/sui/pull/3386

**Comment by Clay-Mysten** [comment]
Move docs are now broken down:
https://docs.sui.io/build/move
https://docs.sui.io/build/move/write-package
https://docs.sui.io/build/move/build-test
https://docs.sui.io/build/move/debug-publish
https://docs.sui.io/build/move/sui-move-library


Next up, Sui CLI client:
https://docs.sui.io/build/cli-client

Finally, we need to reconcile Smart Contracts with Move and Program with Objects tutorials.

**Comment by Clay-Mysten** [comment]
P.S. We still need to consider:
Lu has excellent input here that should feed our Build docs work:
https://app.golinks.io/local-net-flow

And the external blog in Randall's list:
https://github.com/MystenLabs/sui/issues/1362#issuecomment-1189619899
@randall-Mysten , we can always peel that off into a distinct issue. Thanks!

**Comment by Clay-Mysten** [comment]
More work underway in the following PR to create a Talk (comms) subsection under Build for the Rust SDK and related docs:
https://github.com/MystenLabs/sui/pull/3746

**Comment by Clay-Mysten** [comment]
Next:
Split network startup out of cli-client.md and RPC startup out of json-rpc.md and put in new page at top of Build section.
Move/keep remainder of those docs in Talk section.
Split remaining CLI Client into sub-pages?

**Comment by Clay-Mysten** [comment]
Also from @patrickkuo , we should remove redundant contents from `json-rpc.md` now covered by our generated API docs. We should compare and move over unique contents before deleting the entries in Markdown.

**Comment by Clay-Mysten** [comment]
@patrickkuo and I had an excellent meeting where we ironed out the Build workflow, most notably agreeing we should make Devnet the default choice for experimentation and moving starting a local network to the bottom of the Build section (and perhaps Explore in time). So I will:

Split up the Sui CLI Client doc:
https://docs.sui.io/build/cli-client
Merge in Devnet content into existing Devnet page and move it in navigation (only for now) to follow Install Sui and precede Create Smart Contracts in the Build menu:
https://docs.sui.io/explore/devnet

Move the rest of CLI client to a Start a Local Sui Network section and explain this is an advanced alternative to Devnet.
https://docs.sui.io/build/cli-client
In time, I will split that contents into sub-pages and a new sub-menu.

Move up Customize genesis section to Genesis.

Update Build index to reflect latest flow and new Talk (comms) menu:
https://docs.sui.io/build 
Ex. Move start local network to bottom 

See related Build docs work in:
https://github.com/MystenLabs/sui/pull/3811

**Comment by Clay-Mysten** [comment]
@patrickkuo , here is the PR to move aside CLI Client docs in favor of connecting to Devnet directly within the Build section:
https://github.com/MystenLabs/sui/pull/4009

I am noting here we still need to replace references to gateway with fullnode when the time comes. I may file a distinct issue for that if it will be some time from now. Thanks!

**Comment by Clay-Mysten** [comment]
More progress:
https://github.com/MystenLabs/sui/pull/4012

Once the flow is settled, I still need to update the Build and Comms (Talk) indexes.

**Comment by Clay-Mysten** [comment]
And now we have:
https://github.com/MystenLabs/sui/pull/4023

**Comment by Clay-Mysten** [comment]
With this being the final PR for now:
https://github.com/MystenLabs/sui/pull/4026

**Comment by Clay-Mysten** [comment]
I'm declaring this work done. Thanks, all.
