### ISSUE TITLE
ID system requirements for developers and validators

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#1367]
We say absolutely nothing about the hardware and software required to work with Sui:
https://docs.sui.io/build/install
https://docs.sui.io/contribute

I imagine we should and likely must in time as we ramp up validators. Ally is working on it.

Let’s figure this out for all audience types.

**Comment by Clay-Mysten** [comment]
Here is an example request in Discord #discuss:
GuruWP_ — Yesterday at 1:56 PM
Hello, I can't find any document on the specificity of the hardware for running on the testnet or on the mainnet, do you have any documentation on this subject? Thank you

I'm envisioning something like:
https://source.android.com/setup/build/requirements

As I said to Sam in Slack, we can always differentiate between minimum and recommended system requirements. And as I say above, we should have this for each primary audience/user type.

**Comment by Clay-Mysten** [comment]
See a start on docs and related tasks in:
[go/fullnode-overview](https://app.golinks.io/fullnode-overview) 
[go/fullnode-setup](https://app.golinks.io/fullnode-setup) 
[go/fullnode-docnotes](https://app.golinks.io/fullnode-docnotes)

Please contribute your knowledge.

**Comment by Clay-Mysten** [comment]
This is coming back up in:
https://github.com/MystenLabs/sui/pull/2495

All, let's settle the OSes we support/recommend.

**Comment by Clay-Mysten** [comment]
Progress in:
https://github.com/MystenLabs/sui/issues/1493#issuecomment-1190729748

**Comment by Clay-Mysten** [comment]
Closing this as a dupe of:
https://github.com/MystenLabs/sui/issues/1493

**Comment by Clay-Mysten** [comment]
Reopening as we should revisit fullnode specs too.

**Comment by Clay-Mysten** [comment]
See:
https://github.com/MystenLabs/sui/issues/3908

Admittedly, that was caused by an issue on our side. Still, they are using 32GB RAM and we recommend just 8GB. Should that change? What about storage? We still say 50GB...

And what can we say for validators?

**Comment by Clay-Mysten** [comment]
Per here:
https://sui.io/resources-sui/validator-registration-open/
We say: m5.2xlarge (8vCPU, 32GB RAM) + 128GB SSD

**Comment by rsilvestre** [comment]
I use a m6gd.large
<img width="948" alt="Image PNG 3" src="https://user-images.githubusercontent.com/213663/185764395-816feb9b-21a9-46aa-9fc3-734a7780eff9.png">
 
but it continuously crash due to a deadlock. It can take days, but it append all the time.

**Comment by randall-Mysten** [comment]
Closing as sys reqs is one section in the topics for node and validator, so included in those issues
