### ISSUE TITLE
How could i pass moveCall with vector<object>

### ISSUE THREAD

**Issue by qxyanda** [MystenLabs/sui#13802]
my module function is this:

```
    entry fun remove_liquidity_(
        pool: &mut Pool,
        bankers:vector<Banker>,
        ctx: &mut TxContext
    ) {
        let length = vector::length(&bankers);
        let i = 0;
        while (i < length) {
            let banker = vector::borrow_mut(&mut bankers,length);
            let sui = remove_liquidity(pool, banker,ctx);
            let sender = tx_context::sender(ctx);
            transfer::public_transfer(sui, sender);
            let banker_to_delete = vector::remove(&mut bankers,length);
            delete_banker(banker_to_delete);
            i = i + 1
        };
        vector::destroy_empty(bankers);
    }
```

and my ts code like this:

```
      let resData;
      const tx = new TransactionBlock();
      tx.moveCall({
        target: `${global.contractAddress}::${contractModule}::${contractMethod}`,
        arguments: [
          tx.pure(global.pool_1),
          tx.makeMoveVec({ objects: bankers.map((id) => tx.object(id)), type: `${global.contractAddress}::${contractModule}::Banker` }),
        ]
      })
      resData = await wallet.signAndExecuteTransactionBlock({
        transactionBlock: tx,
      });
```

bug shows this:

`Dry run failed, could not automatically determine a budget: MovePrimitiveRuntimeError(MoveLocationOpt(Some(MoveLocation { module: ModuleId { address: b0c5e352c761d38b87edebc86b02e05005049b2bd26cb2b434fa308ae6e3f777, name: Identifier("dice_game") }, function: 6, instruction: 12, function_name: Some("remove_liquidity_") }))) in command 1 (code: -1)`

please help!!

**Comment by qxyanda** [comment]
@tnowacki Could you please help me,thx

**Comment by tnowacki** [comment]
As far as I can tell, your `makeMoveVec` call is working fine! This seems to be more of an issue with dry run not determining a budget since your transaction failed. 
It looks like these `Banker` objects don't have enough liquidity? I'm not sure about the specifics of these functions though, so it's just a guess based on where the abort occurred :)

**Comment by stefan-mysten** [comment]
@qxyanda hopefully you got it sorted by now. If not, feel free to create a new issue. Closing it for now.
