### ISSUE TITLE
[P0] [Umbrella] Publicly-accessible Sui Network

### ISSUE THREAD

**Issue by todd-mystenlabs** [MystenLabs/sui#1382]
# Details

## Goals
* Four validators.
* One gateway.
* Gateway capable of serving latest transaction data.
    * Notes on Gateway transaction-serving [here](https://docs.google.com/document/d/1CP0hOcRZC4ivcj71pinFs9Ac8S9RzdiREpBEhdkCFuQ/edit?usp=sharing) (Xun's approach).
    * Used by Sui Explorer.

## Non-Goals
* Replica / full-read service.
* Strict backwards compatibility at the protocol level.

i.e. We're not targeting full-node support for DevNet.

## P1 Stretch
* Seven nodes

# Dependent Tasks
* _TODO_ add these
* #1393
* #1161
* #1351 
* #1350 
* #1349 
* #1279

**Comment by gdanezis** [comment]
This is now done
