### ISSUE TITLE
[P0] [Umbrella] Operational Must-haves

### ISSUE THREAD

**Issue by todd-mystenlabs** [MystenLabs/sui#1383]
# Goals
* Load testing
* Deployment
* Logging
* Monitoring
* On-call Rotation
* Debuggability

# Dependent Tasks
* MystenLabs/devnet#3
* MystenLabs/devnet#4
* MystenLabs/devnet#5
* #398 -- outdated?

**Comment by velvia** [comment]
Adding some issues for dev.net observability:

- https://github.com/MystenLabs/sui/issues/1455
- https://github.com/MystenLabs/sui/issues/1458 (Dashboards)
- https://github.com/MystenLabs/sui/issues/1459 (Monitoring)
- https://github.com/MystenLabs/sui/issues/1461 (Logging aggregation/UI)

**Comment by lxfind** [comment]
Debuggability:
- [ ] https://github.com/MystenLabs/sui/issues/1502
- [ ] Improve error message
