### ISSUE TITLE
Sui Code Bug or Feature Request

### ISSUE THREAD

**Issue by jymchng** [MystenLabs/sui#13853]
## Steps to Reproduce Issue

`Cargo.toml`
```
[package]
name = "suimev-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sui-sdk = { git = "https://github.com/MystenLabs/sui.git", version = "1.11.0", rev = "8749911a789c72e6b8be507575e1161cac5ff6bc" }
sui-types = { git = "https://github.com/MystenLabs/sui.git", version = "0.1.0", rev = "8749911a789c72e6b8be507575e1161cac5ff6bc" }
```

`src/main.rs`
```
fn main() {
    // sui_literal!();
}
```

## Expected Result

It should compile.

## Actual Result

```
error[E0433]: failed to resolve: use of undeclared crate or module `move_binary_format`
 --> C:\Users\...\.cargo\git\checkouts\sui-6ac459c53b1b685a\8749911\external-crates\move\move-vm\config\src\runtime.rs:5:5
  |
5 | use move_binary_format::file_format_common::VERSION_MAX;
  |     ^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `move_binary_format`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `move-vm-config` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error[E0433]: failed to resolve: use of undeclared crate or module `move_binary_format`
 --> C:\Users\...\.cargo\git\checkouts\sui-6ac459c53b1b685a\8749911\external-crates\move\move-ir-compiler\move-bytecode-source-map\src\mapping.rs:7:5
  |
7 | use move_binary_format::binary_views::BinaryIndexedView;
  |     ^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `move_binary_format`

error[E0433]: failed to resolve: use of undeclared crate or module `move_binary_format`
 --> C:\Users\...\.cargo\git\checkouts\sui-6ac459c53b1b685a\8749911\external-crates\move\move-ir-compiler\move-bytecode-source-map\src\marking.rs:5:5
  |
5 | use move_binary_format::file_format::{
  |     ^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `move_binary_format`

error[E0433]: failed to resolve: use of undeclared crate or module `move_binary_format`
 --> C:\Users\...\.cargo\git\checkouts\sui-6ac459c53b1b685a\8749911\external-crates\move\move-ir-compiler\move-bytecode-source-map\src\source_map.rs:6:5
  |
6 | use move_binary_format::{
  |     ^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `move_binary_format`

error: could not compile `move-bytecode-source-map` (lib) due to 3 previous errors
```

e.g.
<other function call> returned 41.

## System Information

* OS: <specify OS version> Windows
* Compiler: <specify compiler version> v1.11.0

**Comment by jymchng** [comment]
@patrickkuo Can you help me to take a look?

**Comment by crazybits** [comment]
same issue here on MacOS depends on sui-sdk `main` branch

**Comment by ebmifa** [comment]
@jymchng what command did you run to produce this error?

**Comment by jymchng** [comment]
@ebmifa I was running `cargo check`.

**Comment by stefan-mysten** [comment]
Thanks for reporting this. I have localized the error and trying to fix it asap. 
There is an issue with a Cargo.lock file / Cargo.toml file in our repo which generates two versions of `move-binary-format`, a `0.1.0` and the correct `0.3.0`. Until I can push a fix up, you can also manually fix it by going to the `Cargo.lock` file that was generated after `cargo build` or `cargo check`, and removing the whole entry for the `name = "move-binary-format"` that has a field with version 0.1.0, and then changing all the references of `move-binary-format 0.1.0` or `move-binary-format 0.3.0` to `move-binary-format`. This will compile. 
Hope to bring a fix asap.

**Comment by stefan-mysten** [comment]
@ebmifa could you take the git release version question?
@jymchng I think I found the fix, just need to double check to make sure I don't break anything else. I'll reply back here when I push the fix up.

**Comment by stefan-mysten** [comment]
@jymchng I pushed a fix, but it will take a while until it gets cherry-picked into the existing releases. 
You can try this until then: 
```
[package]
name = "suimev-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sui-sdk = { git = "https://github.com/MystenLabs/sui.git", version = "1.11.0", rev = "446c1e58dbb5193f1a3e7be9f80021e6187cf368" }
sui-types = { git = "https://github.com/MystenLabs/sui.git", version = "0.1.0", rev = "446c1e58dbb5193f1a3e7be9f80021e6187cf368" }
```

**Comment by stefan-mysten** [comment]
@jymchng I pushed a fix, but it will take a while until it gets cherry-picked into the existing releases. 
You can try this until then: 
```
[package]
name = "suimev-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sui-sdk = { git = "https://github.com/MystenLabs/sui.git", version = "1.11.0", rev = "446c1e58dbb5193f1a3e7be9f80021e6187cf368" }
sui-types = { git = "https://github.com/MystenLabs/sui.git", version = "0.1.0", rev = "446c1e58dbb5193f1a3e7be9f80021e6187cf368" }
```

**Comment by jymchng** [comment]
@stefan-mysten That sounded real cool, thanks for this fix. Btw, if you don't mind, I actually don't understand how the error occured at Sui's end, I hope if it doesn't take up too much of your time that you would provide some details as to why it happened.

Thank you.

**Comment by jymchng** [comment]
>  There is an issue with a Cargo.lock file / Cargo.toml file in our repo which generates two versions of move-binary-format, a 0.1.0 and the correct 0.0.3. 

Like how can cargo actually generates 2 versions of the same crate in the same cargo.lock file?

**Comment by jymchng** [comment]
> @stefan-mysten That sounded real cool, thanks for this fix. Btw, if you don't mind, I actually don't understand how the error occured at Sui's end, I hope if it doesn't take up too much of your time that you would provide some details as to why it happened.
> 
> Thank you.

@stefan-mysten

**Comment by stefan-mysten** [comment]
@jymchng - if you look into the fix, you'll see that one of our crates was reworked to support wasm, and it was copied in another folder (in the sdk folder). When Rust builds the whole dependency tree, we now had two crates named `move-binary-format`, so it creates two `[package]` entries with the same name `move-binary-format`, but with the versions fields and dependencies that are specified in their respective `Cargo.toml` files. So the `Cargo.lock` file ends up with something like this:
```
[[package]]
name = "move-binary-format"
version = "0.0.3"
dependencies = [...]

[[package]]
name = "move-binary-format"
version = "0.1.0"
dependencies = [...]
```
If you want to "replicate" this, on the commit you were trying to build Sui, you can try building again and then check the Cargo.lock file that gets generated. There you'll see these two move-binary-format entries. So, it seems that crate names should be unique to avoid confusing the compiler. Hope this helps!

**Comment by jymchng** [comment]
> @jymchng - if you look into the fix, you'll see that one of our crates was reworked to support wasm, and it was copied in another folder (in the sdk folder). When Rust builds the whole dependency tree, we now had two crates named `move-binary-format`, so it creates two `[package]` entries with the same name `move-binary-format`, but with the versions fields and dependencies that are specified in their respective `Cargo.toml` files. So the `Cargo.lock` file ends up with something like this:
> 
> ```
> [[package]]
> name = "move-binary-format"
> version = "0.0.3"
> dependencies = [...]
> 
> [[package]]
> name = "move-binary-format"
> version = "0.1.0"
> dependencies = [...]
> ```
> 
> If you want to "replicate" this, on the commit you were trying to build Sui, you can try building again and then check the Cargo.lock file that gets generated. There you'll see these two move-binary-format entries. So, it seems that crate names should be unique to avoid confusing the compiler. Hope this helps!

Really thankful to you @stefan-mysten for fixing and answering my question for the cause of this. :)

**Comment by stefan-mysten** [comment]
@jymchng my pleasure!
