### ISSUE TITLE
[P0] [Umbrella] Validator Read/Query Support

### ISSUE THREAD

**Issue by todd-mystenlabs** [MystenLabs/sui#1385]
# Details
* Publicly-accessible.

## P1 stretch - full node
* *If* we got a full node, where the full node contains a replica for reading, *then* we would want the validators to be write-only.

# Dependent Tasks
* todo?

**Comment by todd-mystenlabs** [comment]
@sblackshear - talk to @lxfind about this

**Comment by lxfind** [comment]
I am closing this one because it really depends on how we want full nodes to follow validators.
