### ISSUE TITLE
failed to build when depends on sui sdk

### ISSUE THREAD

**Issue by crazybits** [MystenLabs/sui#13873]
## Steps to Reproduce Issue

`cargo build -p `

## Expected Result

build successfully

## Actual Result

failed with the following error:
```
Compiling narwhal-types v0.1.0 (https://github.com/MystenLabs/sui?branch=mainnet#81b6f1ce)
Compiling typed-store-derive v0.3.0 (https://github.com/MystenLabs/sui?branch=mainnet#81b6f1ce)
error: failed to run custom build command for `narwhal-types v0.1.0 (https://github.com/MystenLabs/sui?branch=mainnet#81b6f1ce)`

Caused by:
  process didn't exit successfully: `/Users/develop/rust/target/debug/build/narwhal-types-36f0f8f8be7bafdb/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=proto/narwhal.proto
  cargo:rerun-if-changed=proto

  --- stderr
  Error: Custom { kind: Other, error: "protoc failed: /Users/develop/rust/target/debug/build/protobuf-src-78dc1facddcd3743/out/install/bin/protoc: /Users/develop/rust/target/debug/build/protobuf-src-78dc1facddcd3743/out/install/bin/protoc: cannot execute binary file\n" }
```

tried to execute the `protoc` manually with error `zsh: exec format error: ./protoc`, looks like the `protoc` is no macOS format.

below is my cargo.toml

> 
> [dependencies]
> sui-sdk = { git = "https://github.com/MystenLabs/sui", branch = "mainnet" }
> move-core-types =  { git = "https://github.com/MystenLabs/sui", branch = "mainnet" }
> sui-json-rpc-types =  { git = "https://github.com/MystenLabs/sui", branch = "mainnet" } 
> sui-types=  { git = "https://github.com/MystenLabs/sui", branch = "mainnet" } 
> bcs = "0.1.4"
> anyhow = "1.0.57"
> futures = "0.3.24"
> hex = "0.4.3"
> serde = "1.0.147"
> url = "2.3.1"
> actix-rt = "*"
> clap = "4.0.22"
> primitive-types = "0.12.1"
> async-trait = "0.1.58"
> tokio = { version = "1.32.0", features = ["full"] }
> env_logger = "0.10.0"
> log = "0.4.20"
> 

## System Information

* OS: macOS Ventura 13.2.1 
* Compiler:  rustc 1.70.0

**Comment by jymchng** [comment]
Yeah, they should tag their SDK with versions.

**Comment by stefan-mysten** [comment]
It looks like you're missing the ProtoBuf compiler. 
Try to install it following these instructions: https://github.com/stepancheg/rust-protobuf/blob/master/protobuf-codegen/README.md#how-to-use-protoc-gen-rust

**Comment by stefan-mysten** [comment]
@crazybits did you manage to make it work?

**Comment by crazybits** [comment]
my Mac already installed the Protobuf compiler，but seems sui still build from source to incorrect target OS，copy my system compiler to target folder would workaround the issue。

**Comment by stefan-mysten** [comment]
That's interesting, and sorry you had to deal with it. Our `Cargo.toml` file uses these crates and versions related to protobuf, so no idea why this is happening.
```
protobuf = { version = "2.28", features = ["with-bytes"] }
protobuf-src = "1.1.0"
```
