### ISSUE TITLE
[P2] [Umbrella] Functional TypeScript SDK

### ISSUE THREAD

**Issue by todd-mystenlabs** [MystenLabs/sui#1389]
# Goal
* Developer can write an app in TypeScript or JavaScript that interacts with the Sui public devnet node.

# Dependent Tasks
- https://github.com/MystenLabs/sui/issues/1568
- https://github.com/MystenLabs/sui/issues/1569
- https://github.com/MystenLabs/sui/issues/1570
- https://github.com/MystenLabs/sui/issues/1578
* #1143 
* #1145 
* #1146

**Comment by gdanezis** [comment]
I assume all this is done?
