### ISSUE TITLE
Update docs to reflect switch to public(script) for Sui Move entry points

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#1391]
Todd made enhancements in PR #1333 we should make clear in the docs:
https://github.com/MystenLabs/sui/pull/1333

He's already taken care of the code examples in the docs. We need to work together to update the instructions.

Thankfully, Xun has offered to update the tutorials (assuming programming with objects) to reflect this change. Adding him here for credit as a reviewer.

Todd says he's still making updates to the functionality, so we should wait for updates to the docs. Todd, I'm ready to help when you are and will ready through the PR above.

**Comment by Clay-Mysten** [comment]
I'm adding Adam as I think he may have taken care of this in:
https://github.com/MystenLabs/sui/pull/1653#event-6516906348

**Comment by awelc** [comment]
> I'm adding Adam as I think he may have taken care of this in: [#1653 (comment)](https://github.com/MystenLabs/sui/pull/1653#event-6516906348)

I only fixed Move quickstart (move.md). I think @lxfind either already did or was at least planning to similarly update the extended tutorial.

**Comment by lxfind** [comment]
I have fixed the object tutorial already.
btw @awelc we also no longer require ordering of arguments, so we want to reflect that change in move.md as well

**Comment by Clay-Mysten** [comment]
Adam, this is now done with the latest work in:
https://github.com/MystenLabs/sui/pull/1653

Correct?

**Comment by randall-Mysten** [comment]
closing this issue to clear the stale backlog. Please create a new issue if something is unresolved
