### ISSUE TITLE
[Gateway] Implement transaction retry logic in various layers

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1393]
A transaction when executed on a Gateway, will first lock all input objects, and after receiving signed effects from a quorum, would unlock them and commit the effects to the local store.
However, the process can fail due to various reasons, such as network failure, temporary authority failure and etc.
When this happens, the gateway will be stuck in limbo, with all input objects locked.
To solve this problem, we need to be able to retry transactions, so that we can overcome the temporary failures. The retry can happen at 4 different places:
1. In network communication with authorities, if the network channel failed, we should give it a chance to retry.
2. In authority aggregator, when we received some valid effects, but not enough to form a quorum, we should retry on the failed ones and see if we could form a quorum
3. In gateway service, we need to be able to retry failed transactions.
4. In applications such as wallet, we need to be able to retry failed transaction.

(1) and (2) lowers the probability of the issue happening, we should have them asap but not blocking;
One of (3) and (4) is required for devnet, to make sure we don't end up having objects locked up. Ideally we want (3), but we can live with (4) for now.

**Comment by oxade** [comment]
We decided to de-scope this for now to only include item (3).
This has merged here https://github.com/MystenLabs/sui/pull/1765
If we want retries across more areas, we will revisit
