### ISSUE TITLE
[programmability MVP][umbrella] end-to-end demo of "heroes of blockchain and magic" game

### ISSUE THREAD

**Issue by sblackshear** [MystenLabs/sui#14]
This is an umbrella task for the developer experience MVP that we are building towards (see https://github.com/MystenLabs/fastnft/pull/4#discussion_r753080920 for the genesis of this goal):

"Heros of Blockchain and Magic" concept: You make a hero with a sword (onchain), and log in the game server (offchain) proving you own this hero. The game server does a read about the version of your hero to make sure you do not double-play. Then you explore around the map, and find boars and potions of different strength. Once the user chooses (in the UI) to interact with a a portion or boar on-chain, the game server will send the object to the user, triggering an event for the user indicating what sort of object has been received. The user's wallet will then craft a signed transaction that drinks the potion or slays the boar. The wallet should do this automatically upon getting the event--the user already gave consent via the interaction in the UI. After the user signals an intent to fight the boar in the UI, they can continue to walk around in the game UI finding more potions/boars while the transactions to send the boar/fight it get created and committed in the background.

At a high level, what we want is to build out everything required for a game player and game studio to interact with [this](https://github.com/MystenLabs/fastnft/blob/main/fastx_programmability/examples/Hero.move) blockchain game running on fastNFT network backed by 1 to N nodes.

**Comment by gdanezis** [comment]
i think this is now done?
