### ISSUE TITLE
Fix installing the move-analyzer language server cargo command

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#1401]
From here:
https://docs.sui.io/build/install#ide

We suggest and link to:
https://marketplace.visualstudio.com/items?itemName=move.move-analyzer

That recommends:
```
cargo install --git https://github.com/diem/diem move-analyzer to install the move-analyzer 
```

Which yields this error:
```
claymurphy@Clays-MacBook-Pro sections % cargo install --git https://github.com/diem/diem move-analyzer
    Updating git repository `https://github.com/diem/diem`
error: could not find `move-analyzer` in https://github.com/diem/diem with version `*`
```

So I found the move-analyzer in our newly moved Move docs repo here:
https://github.com/move-language/move/tree/main/language/move-analyzer

And attempted to install with either:
```
cargo install --git https://github.com/move-language/move/tree/main/language move-analyzer
```
Or:
```
cargo install --git https://github.com/move-language/move/tree/main/language/move-analyzer move-analyzer
```

But both result in a network error:
```
Updating git repository `https://github.com/move-language/move/tree/main/language`
warning: spurious network error (2 tries remaining): unexpected http status code: 404; class=Http (34)
warning: spurious network error (1 tries remaining): unexpected http status code: 404; class=Http (34)
error: failed to fetch into: /Users/claymurphy/.cargo/git/db/language-d657c5b4a82ca85f

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  unexpected http status code: 404; class=Http (34)
```

So there is likely some user error on my part in attempting this fix. But the existing command definitely does not work as intended.

Adding Sam, Adam and Xun for guidance as we should be able to update the marketplace page above. If not, we should provide an alternative that works on our site and link to that instead.

Marking this medium priority given the option to download and build does exist. Noting the vscode extension install does work as intended, just not the language server install.

**Comment by huitseeker** [comment]
The correct comment is `cargo install --git https://github.com/diem/move move-analyzer`: the move repo location changed

**Comment by todd-mystenlabs** [comment]
@Clay-Mysten - does @huitseeker's comment address this?

**Comment by Clay-Mysten** [comment]
> @Clay-Mysten - does @huitseeker's comment address this?

Yes, thanks Francois and Todd. Fixed in:
https://github.com/MystenLabs/sui/pull/1428

We may need Sam's guidance to update the Marketplace page.

**Comment by Clay-Mysten** [comment]
Sam, if I can help with that Marketplace page command fix, let me know.

**Comment by Clay-Mysten** [comment]
I added a comment to help users there:
https://marketplace.visualstudio.com/items?itemName=move.move-analyzer&ssr=false#review-details
