### ISSUE TITLE
[P1] [Umbrella] Protocol Stabilization for DevNet

### ISSUE THREAD

**Issue by todd-mystenlabs** [MystenLabs/sui#1409]
# Details

# Dependent Tasks
* #729
* stretch from Pre-TestNet: #1419 
* Add network ID #1402
* #312
* #182
* #394
* #248 
* #271

**Comment by sblackshear** [comment]
I think follower API + full node support are a P1. We can launch devnet without them, but would like to have them up ASAP afterward.

**Comment by velvia** [comment]
Hey everyone, there are tons of items under "Protocol Stabilization" wiki: 
https://www.notion.so/mystenlabs/Protocol-Stabilization-3df9c5c1e2d14961a169dba7d6c75d74

I guess most of these items are not for dev-net?

In particular, stabilization of core types issues like this; #218

**Comment by lxfind** [comment]
Close this one as it's broken down to individual issues.
