### ISSUE TITLE
A method for finding balance of an Sui address at a specific checkpoint

### ISSUE THREAD

**Issue by IftequarIffu** [MystenLabs/sui#14137]
I don't find any way to get the balance of an SUI address on a specific checkpoint number.

Is there any way to do so?

**Comment by wlmyng** [comment]
One way is to query for the transaction blocks signed by the address, and transaction blocks where the address was a receiver, and look at the balance changes for the address at the last applicable transaction of a specific checkpoint number. Alternatively, you can index an unpruned fullnode to collect history up to that specific checkpoint number. But there is no straightforward rpc method that can deliver this information.
