### ISSUE TITLE
HTTP error: error trying to connect: can not use sui client gas

### ISSUE THREAD

**Issue by chen4903** [MystenLabs/sui#14158]
## Steps to Reproduce Issue

I enter this command: `sui client gas`, although I have tried to use `clash for windows` to make a proxy.

## Expected Result

show how much I own

## Actual Result

    Networking or low-level protocol error: HTTP error: error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution

    Caused by:
    HTTP error: error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution

    Caused by:
    HTTP error: error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution`

and then, I try this command to get some coin but doesn't work: 

     curl --location --request POST 'https://faucet.devnet.sui.io/gas' --header 'Content-Type: application/json' --data-raw '{"FixedAmountRequest":{"recipient":"0xec911544413fb29c98e564c1bae9a64e324d60d443a587d61844b3969faa0090"}}'

the result is that :

     curl: (6) Could not resolve host: faucet.devnet.sui.io
## System Information

* OS: windows11 - wsl2 - ubuntu20.04
* Compiler: sui 1.11.0-5942ebdd2

**Comment by stefan-mysten** [comment]
Is this still an issue? I just tried your `curl` command and it worked without a problem.

**Comment by chen4903** [comment]
I have solved it. Maybe it was my network problems.
