### ISSUE TITLE
Validator Requirement Collection/Documentation

### ISSUE THREAD

**Issue by todd-mystenlabs** [MystenLabs/sui#1416]
# Details
Collect requirements for running validators:
* ~Minimum system specs. @oxade provided these.~
* Public containers?  Need to determine if we're providing these.  @tharbert 
* Docs for deploying a node from containers.  @Clay-Mysten - we've got a starting point for this in the (private) sui-operations repo README.md (might be in the k8s directory if not top level).

# Dependent Tasks
* #1367

**Comment by todd-mystenlabs** [comment]
@oxade, do you have any GitHub Issues already filed for tracking the machine-spec, benchmark-collection work we've started looking at more closely in the last few days?

**Comment by oxade** [comment]
@todd-mystenlabs nope. I just began writing a script which can iterate through all pertinent AWS machines and run benches.
Should I create an issue or do you have one for me?

**Comment by Clay-Mysten** [comment]
Ade reminded me of the Slack post containing the latest minimum spec:
https://mysten-labs.slack.com/archives/C03AVQW1Y68/p1650485440146589?thread_ts=1650307821.766949&cid=C03AVQW1Y68

t2.micro running Ubuntu Server
CPUs: 1
RAM: 1GB
Disk: 16GB EBS
Cost/hr: $0.01
Latencies:
2.5s @100k tps load
1.3ms @ 10k tps load
1.27ms @ 1k tps load
Beyond about 20k tps, we’re basically just measuring queue time of the backed up system. Sustained tps was about 18k

**Comment by tfiala** [comment]
> @todd-mystenlabs nope. I'm still in early stages. Was thinking to write a script which can iterate through all pertinent AWS machines and run benches. Should I create an issue or do you have I should use?

@oxade - please create an issue.

**Comment by tfiala** [comment]
@Clay-Mysten - we'll want @longbowlu, @lxfind and @bmwill .  I'll add them if I can to the meeting; otherwise, you may need to.

**Comment by randall-Mysten** [comment]
closing this as duplicate to other similar issues
