### ISSUE TITLE
The UID must come directly from sui::object::new

### ISSUE THREAD

**Issue by TheStarBoys** [MystenLabs/sui#14165]
## Steps to Reproduce Issue

1. Prepare any contract
2. sui move build
3. compilation failed

## Expected Result

no errors

## Actual Result

<img width="689" alt="image" src="https://github.com/MystenLabs/sui/assets/41286328/b3b8e003-2d68-4e53-b3cb-8fd79d16efd8">

## System Information

* OS: macOS 12.0.1 (21A559)
* Compiler:
  - sui 1.8.0-a583613cb
  - sui-move 0.1.0

**Comment by stefan-mysten** [comment]
Thanks for flagging this issue. Could you write a minimal replicable example in Move code to understand better where this error comes from?

**Comment by inanisvitae** [comment]
Have similar issue 
   │  
53 │           let self = Random {
   │ ╭────────────────────^
54 │ │             id: object::randomness_state(),
   │ │             --  -------------------------- Non fresh UID from this position
   │ │             │    
   │ │             The UID must come directly from sui::object::new. Or for tests, it can come from sui::test_scenario::new_object
55 │ │             inner: versioned::create(version, inner, ctx),
56 │ │         };
   │ ╰─────────^ Invalid object creation without a newly created UID.

Failed to build Move modules: Compilation error.

**Comment by qiaopengjun5162** [comment]
53 │           let self = Random {
   │ ╭────────────────────^
54 │ │             id: object::randomness_state(),
   │ │             --  -------------------------- Non fresh UID from this position
   │ │             │    
   │ │             The UID must come directly from sui::object::new. Or for tests, it can come from sui::test_scenario::new_object
55 │ │             inner: versioned::create(version, inner, ctx),
56 │ │         };
   │ ╰─────────^ Invalid object creation without a newly created UID.

**Comment by qiaopengjun5162** [comment]
https://github.com/MystenLabs/sui/issues/15239

**Comment by stefan-mysten** [comment]
You need to update your Sui version (1.2x.x)!
