### ISSUE TITLE
Broken link to zklogin circuit repo

### ISSUE THREAD

**Issue by alilloig** [MystenLabs/sui#14501]
The link on the zklogin docs points to a non existent [repo](https://github.com/MystenLabs/sui/blob/de78b3f5f68efd043001fb515bd31b289fb1161d/doc/src/build/zk_login.md?plain=1#L21C52-L21C52). Haven't been able to find the repo on mystenlabs or sui foundation

**Comment by stefan-mysten** [comment]
Hi, we launched the new docs website and the ZkLogin docs are up at this link: https://docs.sui.io/concepts/cryptography/zklogin

@alilloig  @mangoplane hopefully, that's what you were looking for, but if not, please feel free to leave an update here.

**Comment by joyqvq** [comment]
the circuit is currently not open sourced. anyone can verify the proof correctness locally.

**Comment by doutv** [comment]
Why not open source the circuit code? 

Sui Bounty page https://hackenproof.com/sui/sui-protocol list zklogin circuit repo https://github.com/sui-foundation/zklogin-circuit
How can I audit the circuit without the source code?

**Comment by joyqvq** [comment]
thanks for pointing it out. it's removed from the bug bounty site.
