### ISSUE TITLE
Coin.getCoinSymbol is incorrect

### ISSUE THREAD

**Issue by Tzal3x** [MystenLabs/sui#14533]
# Description

In `@mysten/sui.js/src/framework/framework.ts`, `Coin.getCoinSymbol` instead of returning `SUI` returns `SUI>`

As a result this also affects  `Coin.isSUI`.

## Steps to Reproduce Issue

```typescript
import { Coin } from '@mysten/sui.js/dist/cjs/framework/framework';

const objectType = "0x2::coin::Coin<0x2::sui::SUI>"
Coin.getCoinSymbol(objectType) // returns "SUI>"
Coin.isSUI(objectType) // returns false
```

## Expected Result

Expected `Coin.getCoinSymbol(objectType)` to return `'SUI'`

## Actual Result

The actual outcome was `SUI>`

## System Information

* OS: macOS 14.0 23A344 arm64
* Compiler: `tsc -v # Version 5.2.2`

**Comment by Jordan-Mysten** [comment]
This code is legacy code that is intended to be removed here; https://github.com/MystenLabs/sui/pull/14691
