### ISSUE TITLE
Add metrics to Sui

### ISSUE THREAD

**Issue by velvia** [MystenLabs/sui#1455]
The goal of this task is to add initial metrics to Sui for dev.net alerting and dashboarding.   The metrics should go to Prometheus and either be exposed via a REST endpoint or be pushed into a Prometheus push-gateway.

Some initial metrics that would be great to get:
- Metrics for API calls (maybe with the specific command or route instrumented as a tag) into:
    - authority/validator
    - gateway
    - rest-server
- Histogram for number of input objects, number of input shared objects
- Histogram for batch size
- Number of transactions declined due to various reasons

One framework to target is https://crates.io/crates/tokio-metrics

We could also use https://crates.io/crates/prometheus if Tokio-metrics is too rough (it is only 0.1.0 and might not have enough backend support)

**Comment by velvia** [comment]
Going to use the prometheus-exporter crate.  This lets us set up a tiny HTTP server for Prometheus scrape, and makes it super easy to get metrics manually too.

**Comment by bmwill** [comment]
Closed by https://github.com/MystenLabs/sui/pull/1910
