### ISSUE TITLE
Minor security flaw in the Sui Wallet.

### ISSUE THREAD

**Issue by nastari** [MystenLabs/sui#14593]
In my view, Sui Wallet exhibits a security flaw when the wallet is locked, unlike other wallets that have a more central and restrictive template regarding the unlock password. Sui Wallet has a more functional and dynamic design when locked, still allowing some functionalities. Up to this point, I don't see a problem. However, even from outside the wallet, I can access the balance and other sensitive information of wallet assets because 1. the entire address string is displayed. 2. Additionally, Sui Wallet provides a link to the explorer.

This is not a severe security issue, perhaps not even a moderate one, but I believe a hacker might pay more attention to an attack if they know what type of assets are stored there. It's not uncommon for users to have 3 or 4 wallets in different browsers.

Suggestion: My solution is simple, not to provide the complete address string, only shortened ones (disabling the direct link to the explorer as well). After all, asset owners will reasonably know how to connect the resources to their shortened addresses, and the hacker won't have more information about the specific assets in that address. Of course, if the hacker has access to the computer, other measures are necessary, but this is still very helpful.

In this case, the restriction on copying and searching for the address through the explorer can be limited only when the user is locked. I imagine it should be a simple pull request if there is a dedicated engineer available, or I can do it myself if needed and if you believe that the raised issue makes sense in the future.

<img width="353" alt="Screen Shot 2023-11-01 at 05 43 45" src="https://github.com/MystenLabs/sui/assets/48503371/52aded8d-7971-442f-bc79-d0950b63a64e">

**Comment by nastari** [comment]
I placed the changes for analysis in the pull request https://github.com/MystenLabs/sui/pull/14594.

**Comment by lei0gre** [comment]
It's as if it were a glass safe, a significant security flaw.

**Comment by pchrysochoidis** [comment]
Hey @nastari, thank you for your feedback. This was a product decision that currently is not expected to change. I understand your concern about any privacy issues but if an attacker/hacker has access to the wallet on an unlocked pc I would say probably it's already too late!

I will close this issue for now but we will consider it in any future updates. Thank you again!
