### ISSUE TITLE
[Store] Remove signed transactions from authority store after cert commit?

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1463]
Right now we keep signed transactions even after we commit the cert.
But I don't see us ever need the signed transaction again? Especially given that we already have a cert.
Should we delete the signed transaction after we commit the cert?
@gdanezis

**Comment by gdanezis** [comment]
I think that for any transaction we have received we either need to signed transaction or the certified transaction or the effects certificate (if we get one of these). We can indeed delete / substitute the previous form with a newer form indeed.

**Comment by GrapeBaBa** [comment]
Is this an active issue? Can I take it?

**Comment by lxfind** [comment]
It is not. Sorry for not closing earlier.
