### ISSUE TITLE
Gas Payment Object not enough : InsufficientCoinBalance in command 0

### ISSUE THREAD

**Issue by kecson** [MystenLabs/sui#14696]
## Steps to Reproduce Issue

Send Sui failed.
e.g.
1.  
  ```
    const tx = new TransactionBlock();
    tx.transferObjects([tx.gas],tx.pure("recipient"));
  ```
or  
 ```
    const tx = new TransactionBlock();
    const [coin] = txb.splitCoins(txb.gas, [txb.pure( large amount )]);
    tx.transferObjects([coin],tx.pure("recipient"));
  ```
2. Gas Payment size default is 50, also set to max value 256,  but it may be not enough to send the amount 
3. 
![telegram-cloud-photo-size-5-6217533634697607100-y](https://github.com/MystenLabs/sui/assets/10434414/dfac54bd-6686-4065-99b0-99272d71e546)
![telegram-cloud-photo-size-5-6217533634697607101-y](https://github.com/MystenLabs/sui/assets/10434414/3444a986-f796-441d-846a-7105cfbc2570)

4. TxBlock: 
send Gas:  https://suiscan.xyz/testnet/tx/7QS8uV3HoRW9Jh3kPhU7E31TufeAyQQtDDAUrVDa6qBd
send large amount SUI: https://suiscan.xyz/testnet/tx/DVqFnJhTiA6pqpY3TzsoM6oJKJRvUHyJmhNjAAA8BZkh

## Expected Result

should success, but failed.

**Comment by stefan-mysten** [comment]
The gas budget that was set seems to be quite lower than the cost. 
```
Gas Budget: 0.003976 SUI (3,976,000 MIST)
Gas Fee:     -0.046918 SUI 
```

Try increasing the gas budget? Alternatively, try calling dryRun to get an estimate of the total gas cost.

**Comment by kecson** [comment]
> The gas budget that was set seems to be quite lower than the cost.
> 
> ```
> Gas Budget: 0.003976 SUI (3,976,000 MIST)
> Gas Fee:   -0.046918 SUI 
> ```
> 
> Try increasing the gas budget? Alternatively, try calling dryRun to get an estimate of the total gas cost.

```
 const tx = new TransactionBlock();
  tx.transferObjects([tx.gas],tx.pure("recipient"));
```
Even if I set the gas budget to be a bit bigger, I can't send all my SUI，
It's not a matter of gas budget size, it's that when I want to send all SUI is that TransactionBlock#prepareGasPayment only gets 50 SUI Objects.

![](https://user-images.githubusercontent.com/10434414/280962320-dfac54bd-6686-4065-99b0-99272d71e546.jpg)

**Comment by stefan-mysten** [comment]
I see, so just to understand what you are trying to do, is to send all your 857 coin objects to another address? 
If yes, then you will have to use the returned `cursor` to fetch the next page until you get all the coins. 
See the docs: https://docs.sui.io/sui-api-ref#suix_getcoins -- check the Example and the Response. You will see that there is a `nextCursor` field and a `hasNextPage` field. As long as `hasNextPage` is true, you will need to continue to keep calling this method and provide the value from `nextCursor` as the `cursor` field for the `suix_getCoins` method.

**Comment by kecson** [comment]
> I see, so just to understand what you are trying to do: you are trying to send all your 857 coin objects that are owned by address `0x7d20dcdb2bca4f508ea9613994683eb4e76e9c4ed371169677c1be02aaf0b58e` to another address? If yes, then you will have to use the returned `nextCursor` field to fetch the next page until you get all the coins. See the docs: https://docs.sui.io/sui-api-ref#suix_getcoins -- check the Example and the Response. You will see that there is a `nextCursor` field and a `hasNextPage` field. As long as `hasNextPage` is true, you will need to continue to keep calling this method and provide the value from `nextCursor` as the `cursor` field for the `suix_getCoins` method.

when I just want to send all Sui, I will use : `tx.transferObjects([tx.gas],tx.pure("recipient"));` . then TypeScript SDK should fetch all gas Coin , but it's only fetch 50 objects now.  so I think this is bug on TypeScript SDK.

**Comment by stefan-mysten** [comment]
This is not possible for a number of reasons. The current default value for automatically fetching gas objects is 50. If you want to transfer all of them, you have to manually use the pagination and get all coins, as I explained above.
