### ISSUE TITLE
[Gas Mechanism] Gas metering for module verification during publish

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1476]
Some module verification passes can take non-linear time to finish. We currently charge publish based on the number of bytes. But for those non-linear passes (e.g. anything that uses abstract interpretation), we should do some kind of metering (doesn't need to accurate, just need to be deterministic across validators) for this.

**Comment by bholc646** [comment]
Need to discuss further and decide on a solution

**Comment by oxade** [comment]
Decided on flat fee
