### ISSUE TITLE
TypeScript SDK `devInspectTransactionBlock` `gasPrice` parameter not useable

### ISSUE THREAD

**Issue by aaronTufts** [MystenLabs/sui#14763]
## Steps to Reproduce Issue

Call the method filling in the parameter, for example (this targets a testnet package):

```
await client.devInspectTransactionBlock({
    sender: "0xa39edfb89e6a21e89570711845c6c8f412d86bb208e571faf6ea1fc6470172d7",
    transactionBlock: "AAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAQAAAAAAAAAAAQD6DngDC9FmchdMLWzEzV0dFCPQPCinSQmyoUjtqLzKFgVjbG9jawZhY2Nlc3MAAQEAAA==",
    gasPrice: 1000,
    epoch: "211"
  });
```

You'll get the following error: `code: -32602 JSONRPCError: invalid type: integer `1000`, expected a string at line 1 column 4`.

This is because the RPC service expects a string, and indeed you'll have success using the above with the `call` method and passing a string value: 
```
await nodeClient.call(
  "sui_devInspectTransactionBlock",
  [
    "0xa39edfb89e6a21e89570711845c6c8f412d86bb208e571faf6ea1fc6470172d7",
"AAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAQAAAAAAAAAAAQD6DngDC9FmchdMLWzEzV0dFCPQPCinSQmyoUjtqLzKFgVjbG9jawZhY2Nlc3MAAQEAAA==",
    "1000",
    "211"
  ]
);
```

The issue is that the [SDK method](https://github.com/MystenLabs/sui/blob/12b10dab0730143d17cf7de2784b164d48207096/sdk/typescript/src/client/client.ts#L559) takes epoch as a number or BigInt, defined by it's [parameter set type](https://github.com/MystenLabs/sui/blob/12b10dab0730143d17cf7de2784b164d48207096/sdk/typescript/src/client/types/params.ts#L26)  but does to translate it to a string when [executing the call](https://github.com/MystenLabs/sui/blob/12b10dab0730143d17cf7de2784b164d48207096/sdk/typescript/src/client/client.ts#L580).

**Comment by hayes-mysten** [comment]
Thanks for reporting this, just opened a PR to address the issue
