### ISSUE TITLE
How to start a private sui network throught  genesis-ceremony generate..[genesis.blob --> fullnode.yaml]

### ISSUE THREAD

**Issue by oday0311** [MystenLabs/sui#14769]
## Steps to Reproduce Issue
1. compile sui project, 
2. using sui genesis-ceremony tool to generate a genesis.blob. [a lot of details ]
3. after ceremony finalize, we can get a private genesis.blob.
4. but we start a network using sui start with config file , we still need fullnode.yaml, network.yaml, keystore and some other file.

## Expected Result

we can start a sui private network by using some tool and command, 

## Actual Result

we can get a private genesis.blob file, but still far away from start a private network, [except we dive into the cli command, change the data cli generate which bring too much of risk of missing or mistake.]

## System Information

* OS: <specify OS version>
* Compiler: <specify compiler version>

==================================

any information or tool can help with this step? thanks so much..

normal workable local config files.
<img width="575" alt="1" src="https://github.com/MystenLabs/sui/assets/892644/51803cfd-ad22-4075-8f4c-5d927296cffa">

ceremony generate results, which lack of network.yaml, fullnode.yaml and some other files, 
<img width="436" alt="2" src="https://github.com/MystenLabs/sui/assets/892644/3c5f5378-c42f-4cb4-b3ed-721e339418bb">

**Comment by stefan-mysten** [comment]
Could you add a few more details of what you are trying to achieve? Is it that you're only trying to start a private local network, or you want to have a specific configuration? 

In the docs it is explained that the easiest way to start a network is to run `sui-test-validator` command, after you have installed Sui. 
https://docs.sui.io/guides/developer/getting-started/local-network

After you have your local network running (http://127.0.0.1:9000), you can do some requests:
```shell
$ curl --location --request POST 'http://127.0.0.1:9000' \
--header 'Content-Type: application/json' \
--data-raw '{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "sui_getTotalTransactionBlocks",
  "params": []
}'

{"jsonrpc":"2.0","result":"8","id":1}
```

**Comment by oday0311** [comment]
thanks for response.

actually I know there are two ways to start a test local net, 1) sui start --config fullnode.yam. 2) sui-test-validator..

but what I want to do is start a customize sui net with nodes locate in different place.
So I first generate a custom genesie.blob using 
1)sui genesis-ceremony init 
2)sui genesis-ceremony add-validator
3)sui genesis-ceremony build-unsigned-checkpoin
4)sui  genesis-ceremony verify-and-sign
5)sui genesis-ceremony validate-state
6)sui genesis-ceremony finalize

===========above this lead to a custiomize genesis.blob files, also with some fold name committee 

<img width="436" alt="2" src="https://github.com/MystenLabs/sui/assets/892644/de24a20b-cd7f-4c73-8c55-a6a99e42757e">


my question is , how can I use this generate result to start my private net ?

**Comment by stefan-mysten** [comment]
Thanks for the explanation. I would try to generate the config files using `sui genesis --write-config my_config.yaml` and then use `sui genesis --from-config` pointing to the config file. 
The `network.yaml` `sui.keystore` `client.yaml` can be generated by using `sui genesis`, and you could probably reuse those an adapting them to your needs (e.g., addresses, networks, etc). 

Hope this helps!
