### ISSUE TITLE
Uniform cryptography for Narwhal and Sui

### ISSUE THREAD

**Issue by asonnino** [MystenLabs/sui#1486]
The Narwhal and Sui codebase can both use dalek-ed25519 cryptography but they each burry it under different layers of abstractions. It would be nice to have a single crypto crate in Mysten-Infra (or something like that) to avoid tacky conversions in the codebases.

**Comment by kchalkias** [comment]
Resolved in https://github.com/MystenLabs/sui/pull/2994
