### ISSUE TITLE
zkLogin wallet: Signature verification

### ISSUE THREAD

**Issue by hiendaovinh** [MystenLabs/sui#14914]
Hi,
Since Sui Wallet supports zkLogin already, does Sui SDK offer any verification helper for signatures generated by zkLogin wallets?
Documentation here is not enough: https://docs.sui.io/concepts/cryptography/zklogin

So far, I can only parseZKLoginSignature but stuck with the verification of the ephemeral ed25519 public key.
https://github.com/MystenLabs/sui/blob/main/sdk/typescript/src/verify/index.ts#L72-L74
https://github.com/MystenLabs/sui/blob/main/sdk/typescript/src/cryptography/signature.ts#L74-L93

How do I sign the message?
```
wallet.features['sui:signMessage']?.signMessage
```

**Comment by joyqvq** [comment]
there is currently limitation on the GPL license on snarkjs library for sui sdk (under apache) to include this. we had provided server alternative here: https://docs.sui.io/concepts/cryptography/zklogin#how-to-verify-a-zklogin-signature-offchain
