### ISSUE TITLE
Create a Validator Guide for Wave 1 Testnet

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#1493]
Related Issues: 
sui #1367 

This issue builds upon work accomplished in:
Document our binaries in a README:
https://github.com/MystenLabs/sui/issues/370 

Review and edit Narwhal docs, help generate blog post:
https://github.com/MystenLabs/Prose/issues/12

Francois has supplied excellent input in issue #370 we should act upon. From him:

---

Those docs have been written with a user in mind that's the user of a blockchain that wants to transact with it. That's all well and good, but we are going to need a different set of docs for a node runner (i.e. somebody running a sui authority + a narwhal authority) That's an entirely new section of the website!
We'll need documentation that's closer to the code too, e.g. rustdoc.
So, to list some of the things that are documented nowhere:

- how to run a validator, pass it a genesis config, pass its private key info (or generate it), where to get the genesis config in the first place,
- how to run a narwhal node, link it to the same config and key information, choose a scale-out topology,
- what's in the config, and what parameters there one should tweak when co-deploying Narwhal + Sui.

---

I know we have a validator onboarding program in the works. And I myself have been suggesting we supply at least some basic system requirements:
https://github.com/MystenLabs/sui/issues/1367

Adding Sam, Todd and Francois for guidance on whom to work with to gather the information requested above (and likely much, much more). Adding Ally as she's already been working to gather system requirements for validators.

**Comment by todd-mystenlabs** [comment]
For minimum specs: @oxade has been collecting data there.  An AWS t2.micro was surprisingly performant on single-validator benchmarks IIRC.

For running the Sui side of things: @mystenmark has been looking at it from a GCP side and maybe from an AWS side (depends on timing). If AWS does not get covered by Mark (quite likely), then it may be @velvia, @longbowlu or possibly @bmwill.

**Comment by oxade** [comment]
> For minimum specs: @oxade has been collecting data there. An AWS t2.micro was surprisingly performant on single-validator benchmarks IIRC.
> 
> For running the Sui side of things: @mystenmark has been looking at it from a GCP side and maybe from an AWS side (depends on timing). If AWS does not get covered by Mark (quite likely), then it may be @velvia, @longbowlu or possibly @bmwill.
> 
> On the Narwhal side, I would imagine @huitseeker is going to be your best bet, but possibly @asonnino as he is getting this integrated with Sui now-ish.

@todd-mystenlabs 
I'm updating the minimum required machine to t2.large (8GB RAM and 2CPUs) if we want to use containers just because of the docker overhead.
The t2.micro (1GB RAM) only worked well with validator running as a process

**Comment by huitseeker** [comment]
If this is for devnet, then narwhal is out of the picture (given how we run narwhal in-process), but we still very much need to document how to run a Sui validator (on Sui terms).

**Comment by Clay-Mysten** [comment]
See progress from our meetings in:
[go/sui-validator-onboarding](https://app.golinks.io/sui-validator-onboarding)

**Comment by Clay-Mysten** [comment]
We are starting to gather information in:
[go/validator-performance](https://app.golinks.io/validator-performance)

**Comment by ebmifa** [comment]
Have created a run book for setting up and running validator here https://www.notion.so/mystenlabs/Setting-up-and-running-a-validator-1135afef1b494832aa6d63eb11f5c746

**Comment by randall-Mysten** [comment]
Nice, thanks. Do we want to add some intro/explanatory text about this? Perhaps some info about what to do if something fails to complete? Like if the sudo docker-compose up fails, can they just rerun it, or do they need to redo any of the preceding steps?

**Comment by Clay-Mysten** [comment]
> Have created a run book for setting up and running validator here https://www.notion.so/mystenlabs/Setting-up-and-running-a-validator-1135afef1b494832aa6d63eb11f5c746

Great work, Eugene. I will work with you to build this out when closer to release time. Please keep me posted. Thanks!

**Comment by ebmifa** [comment]
> Nice, thanks. Do we want to add some intro/explanatory text about this? Perhaps some info about what to do if something fails to complete? Like if the sudo docker-compose up fails, can they just rerun it, or do they need to redo any of the preceding steps?

Great points, will add more info.

**Comment by Clay-Mysten** [comment]
A public request for these docs in:
https://github.com/MystenLabs/sui/issues/3775

Also @huitseeker is saying to use the `sui-node` binary, yet I see no reference to it in the docs above. Nor do we call for its installation yet in our central Install docs:
 https://docs.sui.io/devnet/build/install#binaries

Where we have users run:
`$ cargo install --locked --git https://github.com/MystenLabs/sui.git --branch "devnet" sui sui-gateway`

@ebmifa and team, the internal doc is shaping up. Please let us know when to begin our edits and conversion to public docs. Thanks!

**Comment by Clay-Mysten** [comment]
Per @kohkim and @bhenhsi , @randall-Mysten is going to be handling the validator docs.
