### ISSUE TITLE
[fe] Move to more ideal Turborepo setup

### ISSUE THREAD

**Issue by Jordan-Mysten** [MystenLabs/sui#14967]
We currently use Turborepo, which is great for coordinating tasks, however we've run into a couple issues getting it setup with an ideal configuration. We should improve this to avoid some of the issues we've have (outlined below) and improve the developer experience with our apps and SDKs.

#### Goals of this:

- Easily start developing from a clean checkout. The developer shouldn't have a series of commands they need to remember to run to get the repo into a good state.
- Should be able to run the dev process scoped to just one app in the repo. Running all apps at the same time is one possible solution but we don't want to kill our CPU by running 10 apps at the same time. 
- The workspace dependencies should (generally) use the built versions of themselves, not the source versions. There are some exceptions like `@mysten/ui` which is not published to `npm` but this should be simple because this doesn't have a `build` script and `main` in the package.json just points to src.
- It is not required to have the dependencies build watcher run when I run the app's dev process. This is just a nice to have but we're totally fine giving it up.

---

One explicit callout with this work is that _**we're fine if the commands we need to run are different**_. Right now we have these magic pnpm aliases that make `pnpm explorer dev` roughly alias to `pnpm --filter sui-explorer dev`, but it's fine if the workflows around development / building / testing are different, so long as they are **consistent** (i.e. all projects in the repo should work the same way) and documented. 

---

Some issues that exist in today's setup:

- Apps that watch both their own code and dependency code requires using concurrently. This means two runners which is just annoying.
- We've observed an issue with the "first-build" when running `dev`, where dependencies are not yet built. This causes node modules resolution errors when devving on a clean checkout.
- Tests need to have their workspace dependencies built, or aliased in `vitest`, otherwise the tests run into node module resolution errors. We run tests outside of turbo right now, too, which means tests actually can have nested turbo, because we added a `turbo build` into the test script to make this work.

**Comment by Jordan-Mysten** [comment]
@anthonyshew

**Comment by anthonyshew** [comment]
Rewriting requirements more tersely here for my own sake:
- [x] `test` script is currently wonky
- [x] Run dev commands scoped to app of interest

Scripts tested from cold:
- [x] `turbo build`
- [x] `turbo test`
- [x] `pnpm explorer`
- [x] `pnpm wallet`
- [ ] ` pnpm sdk` (I'm not quite grokking what this task is meant to do as it doesn't have as the `sdk` package doesn't have a `dev` script
- [x] `pnpm bcs`
