### ISSUE TITLE
**New** Stake Balance Query

### ISSUE THREAD

**Issue by charlie-bit** [MystenLabs/sui#14985]
Hi team, there is no way to found the API about `/account/balance`, and could you help share doc link about it?  thanks

In addition, is there any way to get stake balance by specific validator address and delegated address with RPC API?

**Comment by stefan-mysten** [comment]
> In addition, is there any way to get stake balance by specific validator address and delegated address with RPC API?

You can use the [`suix_getStakes` RPC](https://docs.sui.io/sui-api-ref#suix_getstakes) and provide the validator's address. This will yield all the staked SUI objects, from which you can compute the balance (sum up all the principal values). 

> Hi team, there is no way to found the API about /account/balance, and could you help share doc link about it? thanks

The [`suix_getAllBalances` RPC](https://docs.sui.io/sui-api-ref#suix_getallbalances) will give you the balance for each coin owned by the address. However, with this API you will not get the balance of staked objects. For that, use the API above.
