### ISSUE TITLE
SuiDataStore debug tool

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1502]
A tool that is able to dump human-readable data from `SuiDataStore`. This tool can then be used to debug validator, gateway, fullnode because they all share the same db implementation.

**Comment by gdanezis** [comment]
Idea: should we implement a 'raw read' API: where we get a key in bytes and return the value in bytes from all our tables? Then we can build a utility to display and query?

**Comment by velvia** [comment]
@gdanezis the "raw read" API is already there.  RocksDB has a tool called rocksdb_ldb, which is how I got stats on DB size, key size, etc.  It can dump out binary keys and values in hex.

**Comment by velvia** [comment]
Ade implemented a tool.

**Comment by lxfind** [comment]
The tool was not yet finished/merged.

**Comment by todd-mystenlabs** [comment]
Hey @oxade! Can you point out where your tool is and where we can find the code? Thanks!  This will really come in handy when we need to debug the state of a running cluster.

**Comment by patrickkuo** [comment]
https://github.com/MystenLabs/sui/pull/3188
