### ISSUE TITLE
[crypto] Unify crypto traits between Sui and Narwhal repos

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/sui#1504]
Narwhal's repo crypto structure and design is modular allowing for multiple signature schemes, on the other hand Sui's `crypto.rs` is ed25519 specific. Sui's cryptographic agility (i.e., validator BLS, user multi-sig and ECDSA) plan requires the use of various signature schemes, and thus Narwhal's crypto crate should be reused in both projects (with any modifications/refactoring required). 

This will also allow for removing converter functions, such as `make_narwhal_keypair`, and enable more modular deterministic custodial signature implementations (i.e., based on seeds, BIP32 variants etc). Finally, maintaining one crypto repo is a no-brainer.

**Comment by huitseeker** [comment]
Duplicate of #1486
