### ISSUE TITLE
New bcs type inference errors on generics

### ISSUE THREAD

**Issue by kklas** [MystenLabs/sui#15139]
When defining bcs types with generics using the new library, type inferrence fails when the type is exported. Here's the error with the generic example from the docs:

![image](https://github.com/MystenLabs/sui/assets/7824233/75ac4091-49b9-47c9-8679-b2cc918f7e0f)

The error is:
```
The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed. ts(7056)
```

Because this only happens when the type is exported I assume this has something to do with generating declaration files?

Also, when you have generic bcs type definitions in your codebase, the type checker in vscode is slow and laggy.

I alleviated both issues by circumventing the inner type to `any` like this:

```
  static get bcs(): (k: BcsType<any>) => BcsType<any> {
    return bcs.generic(['K'], K =>
      bcs.struct('DynamicFields<K>', {
        names: bcs.vector(K),
      })
    )
  }
```

cc @hayes-mysten

**Comment by hayes-mysten** [comment]
@kklas great catch... I spent some time looking into a better way around this, and I think we may just need to remove the generic helper, and document an alternative.

Here is what I would recommend for now:

```ts
function DynamicFields<K extends BcsType<any>>(K: K) {
	return bcs.struct(`DynamicFields<${K.name}>`, {
		fields: bcs.vector(K),
	});
}

const StringFields = DynamicFields(bcs.string());
```

This is effectively exactly the same as what the helper was doing, and is still type safe, it's just slightly more manual

**Comment by hayes-mysten** [comment]
If this makes sense to you, I can update the documentation and deprecate the `generic` method.  I think I was a little too ambitious with making that work
