### ISSUE TITLE
Add size limit to Move objects

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1514]
We should come up with a reasonable limit for Move objects. We can also consider having different limits for objects and packages.
note: we may want to special handle the object 0x5 as it's the system object

**Comment by todd-mystenlabs** [comment]
I think this needs to be in by Testnet wave 1.

@sblackshear, @lxfind  - I think we want to make this no larger than aggregate size of 1 MB for an object, but we can discuss if it might need to be lower.

**Comment by oxade** [comment]
From talking to @sblackshear  it seems the current proposal is 2MB now.

**Comment by SuiSunbeam** [comment]
Closed with https://github.com/MystenLabs/sui/pull/6328?
