### ISSUE TITLE
Feedback for “Install Sui TypeScript SDK”

### ISSUE THREAD

**Issue by yuanfeng-net** [MystenLabs/sui#15251]
![image](https://github.com/MystenLabs/sui/assets/19276615/47b4c6eb-69d8-43bc-8f6b-724ed48d17ed)
TypeError: fetch is not a function

**Comment by stefan-mysten** [comment]
Thanks @yuanfeng-net for reporting this issue. Could you provide more context or minimal replicable example so that we have a clear understanding of what's wrong?

**Comment by Jordan-Mysten** [comment]
@yuanfeng-net the SDK requires fetch to be defined in the global environment. Newer versions of Node.js do this, but you can also use `node-fetch` to do this
