### ISSUE TITLE
Start sui-test-validator (local network) inside docker container

### ISSUE THREAD

**Issue by thaonx** [MystenLabs/sui#15279]
I want to setup a Sui local network inside a Docker container utilizing the sui-test-validator binary. However, a challenge arises as the sui-test-validator exclusively listens on `127.0.0.1`, resulting inaccessible from the host machine.

https://github.com/MystenLabs/sui/blob/main/crates/sui-test-validator/src/main.rs#L139C9-L139C25
```
  fullnode_address: Some(format!("127.0.0.1:{}", fullnode_rpc_port)),
```
To address this limitation, I propose the addition of a configurable option `fullnode_rpc_host`, within the sui-test-validator. This enhancement would allow users to set `fullnode_rpc_host` to 0.0.0.0, enabling binding to all available network interfaces and facilitating accessibility from the host machine.

**Comment by stefan-mysten** [comment]
The change was merged. @thaonx  let us know if it does not work as expected!

**Comment by stefan-mysten** [comment]
@qpb8023 thanks for raising this up. I have not tried it, can you provide a dockerfile?

**Comment by stefan-mysten** [comment]
Thanks @qpb8023, I'll look into it.

**Comment by stefan-mysten** [comment]
I don't have a cloud server to try, but running it locally I get 
```
🚀 sui % sui-test-validator          
Graphql port not provided. Graphql service will not run.
`with_indexer` flag unset. Indexer service will not run.
Starting Sui validator with config: ClusterTestOpt {
    env: NewLocal,
    faucet_address: Some(
        "127.0.0.1:9123",
    ),
    fullnode_address: Some(
        "0.0.0.0:9000",
    ),
    epoch_duration_ms: Some(
        60000,
    ),
    indexer_address: None,
    use_indexer_v2: false,
    pg_address: postgres:*****@localhost:5432/sui_indexer,
    use_indexer_experimental_methods: false,
    config_dir: None,
    graphql_address: None,
}
```
And doing a `cURL` I get:
```
🚀 ~ %  curl --location --request POST 'http://0.0.0.0:9000' \
--header 'Content-Type: application/json' \
--data-raw '{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "sui_getChainIdentifier",
  "params": []
}' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   131  100    44  100    87   8316  16443 --:--:-- --:--:-- --:--:--  127k
{
  "jsonrpc": "2.0",
  "result": "bfa5779f",
  "id": 1
}
```
When you say local access to the server and access through the external network are still unavailable, which local access are you referring to, and what server? Are you saying that when issuing the command on the server you cannot query the network?

**Comment by thaonx** [comment]
> @thaonx @stefan-mysten I am using the latest code and this problem still exists. Have you verified it?
> 
> ```
> Starting Sui validator with config: ClusterTestOpt {
>     env: NewLocal,
>     faucet_address: Some(
>         "127.0.0.1:9123",
>     ),
>     fullnode_address: Some(
>         "0.0.0.0:9000",
>     ),
>     epoch_duration_ms: Some(
>         60000,
>     ),
>     indexer_address: None,
>     use_indexer_v2: false,
>     pg_address: postgres:*****@localhost:5432/sui_indexer,
>     use_indexer_experimental_methods: false,
>     config_dir: None,
>     graphql_address: None,
> }
> 
> Fullnode RPC URL: http://127.0.0.1:9000
> Faucet URL: http://0.0.0.0:9123
> ```

hi @qpb8023, I have tried this yet, still waiting for the release. But I have found alternative solution to start a Localnet in docker.  Just run `sui genesis` then `sui start` , it listens on 0.0.0.0 by default.
I am not quite sure what is the difference with `sui-test-validator`, it it works for me.

**Comment by stefan-mysten** [comment]
> > @thaonx @stefan-mysten I am using the latest code and this problem still exists. Have you verified it?
> > ```
> > Starting Sui validator with config: ClusterTestOpt {
> >     env: NewLocal,
> >     faucet_address: Some(
> >         "127.0.0.1:9123",
> >     ),
> >     fullnode_address: Some(
> >         "0.0.0.0:9000",
> >     ),
> >     epoch_duration_ms: Some(
> >         60000,
> >     ),
> >     indexer_address: None,
> >     use_indexer_v2: false,
> >     pg_address: postgres:*****@localhost:5432/sui_indexer,
> >     use_indexer_experimental_methods: false,
> >     config_dir: None,
> >     graphql_address: None,
> > }
> > 
> > Fullnode RPC URL: http://127.0.0.1:9000
> > Faucet URL: http://0.0.0.0:9123
> > ```
> 
> hi @qpb8023, I have tried this yet, still waiting for the release. But I have found alternative solution to start a Localnet in docker. Just run `sui genesis` then `sui start` , it listens on 0.0.0.0 by default. I am not quite sure what is the difference with `sui-test-validator`, it it works for me.

`sui-test-validator` starts a faucet too, so if you do not need a faucet @qpb8023 you can indeed use `sui genesis` and `sui start`.

**Comment by stefan-mysten** [comment]
@thaonx If I understand correctly, it works for you now. 
@qpb8023 are you still encountering issues when following the other approach described by @thaonx?

**Comment by stefan-mysten** [comment]
Thanks for confirming this. We have some upcoming work on these commands, so I put a note to have a look at this!

**Comment by tbocek** [comment]
I'm also running into this issue. It says:

local-sui-1  | Fullnode RPC URL: http://127.0.0.1:9000
local-sui-1  | Faucet URL: http://0.0.0.0:9123

And the commit https://github.com/MystenLabs/sui/commit/fd09307bb3ba48950f93c414b9c73f1090b27e7f makes the Faucet work, but not yet the Fullnode RPC, which is still 127.0.0.1

**Comment by stefan-mysten** [comment]
Sorry about this. Now `sui start` starts by default all services on `0.0.0.0` and their respective ports. See #18607.
