### ISSUE TITLE
[Sui Rust SDK] - Build and publish sui-sdk crate

### ISSUE THREAD

**Issue by patrickkuo** [MystenLabs/sui#1537]
The crate should contain `RpcGatewayClient`, signer api and helper functions for creating transactions and interact with the sui network.

**Comment by todd-mystenlabs** [comment]
Scope this down to a small set of crates that we can deploy first, and unblock Rust developers.  This could lead to more engagement/usage by the Rust community.

**Comment by Clay-Mysten** [comment]
Just noting we have `rustdoc` output at the bottom of this section now thanks to @huitseeker :
https://docs.sui.io/build/install#source-code

https://mystenlabs.github.io/sui/ - the Sui blockchain
https://mystenlabs.github.io/narwhal/ - the Narwhal and Tusk consensus engine
https://mystenlabs.github.io/mysten-infra/ - Mysten Labs infrastructure

**Comment by Clay-Mysten** [comment]
+a slew of people to guide and help

Hi Patrick,

I am reopening this to track our end of the bargain. Thanks so much for providing documentation along with this feature to make the product complete.

I see we already have a page for docs.sui.io that is live:
https://docs.sui.io/build/rust-sdk

And an associated README with a cool Tic-Tac-Toe demo:
https://github.com/MystenLabs/sui/tree/main/crates/sui-sdk

So we need to:
1. Edit and test both docs.
2. Add the rustdoc output links above to rust-sdk.
3. Link reciprocally between them (and fix the Larger Examples link at the bottom of rust-sdk)
4. Add rust-sdk to site navigation.
5. Introduce it in logical locations, such as: https://docs.sui.io/build/json-rpc#sui-json-rpc-api
6. Announce it on both the landing page and Learn > See what's new.

I see on go/mysten-launch-cal, this feature is set to go live August 1st, so we have some time. I've copied @sblackshear , @lxfind and @awelc for guidance on #4 above. Do we want to build out some table with all of the ways (SDKs) folks may interact with us over RPC?

I added this note for TypeScript in the json-rpc page and section above:
Tip: If your application is written in JavaScript or TypeScript, follow the TypeScript SDK documentation and reference files.

So now we have Rust and TypeScript, as well as JSON-RPC calls. What else am I missing? :-)

I've also added @randall-Mysten in case he wants to take on something like this.

**Comment by Clay-Mysten** [comment]
I'm starting to tackle this list with:
https://github.com/MystenLabs/sui/pull/3486
https://github.com/MystenLabs/sui/pull/3487

Next up, I need to get the rust-sdk file in nav and link to it. Finally, we announce. Please Patrick and team take a look. Peer testing needed. Thanks!

**Comment by Clay-Mysten** [comment]
Ack. Announced on landing page and in:
https://docs.sui.io/learn
