### ISSUE TITLE
Sui dApp Kit Wallet Provider Issue - "localstorage is not defined"

### ISSUE THREAD

**Issue by RevanthGundala** [MystenLabs/sui#15488]
## Steps to Reproduce Issue

Spin up a React Application and follow "Setting up Providers": https://sdk.mystenlabs.com/dapp-kit

## Expected Result

WalletProvider Context should be defined (no errors)

## Actual Result

When WalletProvider is used, error is "localstorage is not defined".

## System Information

* OS: macOS Ventura

**Comment by hayes-mysten** [comment]
Can you share more about the environment this is running in?

If you are trying to use this in server side rendered code, localstorage won't be available.  You can provide your own storage implementation using the `storage` prop, and passing an object that matches the following type:

```ts
export interface StateStorage {
    getItem: (name: string) => string | null | Promise<string | null>;
    setItem: (name: string, value: string) => void | Promise<void>;
    removeItem: (name: string) => void | Promise<void>;
}
```
