### ISSUE TITLE
`cryptography/groth16` docs error

### ISSUE THREAD

**Issue by chrisyy2003** [MystenLabs/sui#15516]
I have successfully generated the public input and proof through ark library and it passes the verification, but I can't pass it in the move module after serializing them as bytes, please help me thanks!

![image](https://github.com/MystenLabs/sui/assets/63803385/3c91fdd9-fb7a-478d-a2c3-4b6ce6e91bd4)

**Comment by lightning-li** [comment]
Do you solve this issue? @chrisyy2003

**Comment by dusmart** [comment]
You closed this issue. Did you solve this issue? @chrisyy2003

**Comment by dusmart** [comment]
@mskd12 @joyqvq Did you solve this issue?

**Comment by chrisyy2003** [comment]
I think there is some confusion here in the docs, when serializing proof inputs for the cases in the docs should serialize `inputs[0]`.
@dusmart @lightning-li

**Comment by joyqvq** [comment]
can you paste the bytes from the screenshot: vk, public_inputs_bytes and the proof_bytes for us to reproduce?
