### ISSUE TITLE
Node crash log, version 1.15.1

### ISSUE THREAD

**Issue by imaiops** [MystenLabs/sui#15511]
2023-12-31T13:47:12.195798Z  INFO sui_node: Sui JSON-RPC server listening on 0.0.0.0:9000 local_addr=0.0.0.0:9000
2023-12-31T13:47:12.195908Z  INFO sui_node: SuiNode started!
2023-12-31T13:47:12.195952Z  INFO narwhal_network::connectivity: Spawning future narwhal/network/src/connectivity.rs:ConnectionMonitor
2023-12-31T13:47:12.196030Z  INFO sui_node: Sui chain identifier: 35834a8a
2023-12-31T13:47:12.196144Z  INFO sui_node::admin: starting admin server filter=info address=127.0.0.1:1337

thread '2023-12-31T13:47:15.971755Z ERROR execution_driver{tx_digest=TransactionDigest(DkNocpwm1w8C96EhKx7VdLmRXB5hWdoEcFPJ9fZJriUq)}: telemetry_subscribers: panicked at /home/runner/work/sui/sui/crates/sui-core/src/authority.rs:1829:26:
try_create_dynamic_field_info should not fail.: ObjectSerializationError { error: "Could not find module" } panic.file="/home/runner/work/sui/sui/crates/sui-core/src/authority.rs" panic.line=1829 panic.column=26
sui-node-runtime' panicked at /home/runner/work/sui/sui/crates/sui-core/src/authority.rs:1829:26:
try_create_dynamic_field_info should not fail.: ObjectSerializationError { error: "Could not find module" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by panlilu** [comment]
+1

**Comment by claudijd** [comment]
Duplicates: #15510

**Comment by claudijd** [comment]
also duplicates: #15500, which has even more context.

**Comment by zhy827827** [comment]
+1

**Comment by stefan-mysten** [comment]
Thanks for reporting. This was fixed in ##15501 and it's recommended to update to `sui-v1.15.0-release`.

**Comment by Ljzn** [comment]
> Thanks for reporting. This was fixed in ##15501 and it's recommended to update to `sui-v1.15.0-release`.

Hello, @stefan-mysten , there isn't a v1.15.0 mainnet release. Could your make a new release?

**Comment by stefan-mysten** [comment]
You can find this release in this branch: https://github.com/MystenLabs/sui/tree/releases/sui-v1.15.0-release
