### ISSUE TITLE
Failed to sign transaction by quorum of validator 

### ISSUE THREAD

**Issue by Degen-Player** [MystenLabs/sui#15532]
Impossible to make a transactions 

error from Sui wallet while trying to send Sui to another wallet : "Failed to sign transaction by a quorum of validators because of locked objects. Retried a conflicting transaction None, success: None"

Any help how ot solve this ?

**Comment by Degen-Player** [comment]
@stefan-mysten  hey any help please

**Comment by stefan-mysten** [comment]
@Degen-Player will need a bit more context. Are you trying to send SUI from your wallet to an address? Is this under a Typescript project, or directly from the Chrome browser extension?

**Comment by Degen-Player** [comment]
> @Degen-Player will need a bit more context. Are you trying to send SUI from your wallet to an address? Is this under a Typescript project, or directly from the Chrome browser extension?

i'am actually using https://chromewebstore.google.com/detail/sui-wallet/opcgpfmipidbgpenhmajoajpbobppdil in my wallet i have x Sui which i would like to transfer to another address but failled to do this due to the error in first message

**Comment by stefan-mysten** [comment]
Are you staking your SUI that you're trying to send?

**Comment by Degen-Player** [comment]
> Are you staking your SUI that you're trying to send? Are you trying to do this on mainnet or on other networks?

no i'm not staking them, yes from mainnet

**Comment by stefan-mysten** [comment]
@Degen-Player many users seem to have hit this issue. On TG @sblackshear wrote that _"This means there was equivocation on an owned object included in the transaction. Typically (but not always), this is because two concurrent transactions are trying to use the same gas object"_
So if an object is locked, the lock lasts for an epoch and it will be unblocked at the next epoch.

**Comment by Degen-Player** [comment]
> @Degen-Player many users seem to have hit this issue. On TG @sblackshear wrote that _"This means there was equivocation on an owned object included in the transaction. Typically (but not always), this is because two concurrent transactions are trying to use the same gas object"_ So if an object is locked, the lock lasts for an epoch and it will be unblocked at the next epoch.

i don't know what object means here, same for epoch..

What i'am supposed to do please? (:

**Comment by Degen-Player** [comment]
look like object are main thing in sui transaction, ref : https://docs.sui.io/concepts/object-model

**Comment by Degen-Player** [comment]
okay so i would wait expiration of the transaction to use back my wallet ? https://docs.sui.io/concepts/transactions

based on this "Expiration: An epoch reference that sets a deadline after which validators will no longer consider the transaction valid. The optional expiration epoch reference enables users to define transactions that either execute and commit by a set time (current epoch less than or equal to expiration epoch), or never execute after the deadline passes. By default, there is no deadline for when a transaction must execute."

**Comment by stefan-mysten** [comment]
Either you can wait until the next epoch change, or create a new address, add Sui to it, and then try again to mint.
