### ISSUE TITLE
How to interact with sui smart contract with rust?

### ISSUE THREAD

**Issue by Degen-Player** [MystenLabs/sui#15538]
hey guys, i'm trying for more 1 mounth right now to found a way to interact with Sui chain with rust but i don't found anything. Please can you guys share me a way to interact with sui chain ? from provider to a way to interact with smart contract (read and write function). 

Thank you guys.

**Comment by stefan-mysten** [comment]
If I understand you correctly, you want to use Rust code to interact with the Sui blockchain. We have a Rust SDK that you can use, so start here:
https://github.com/MystenLabs/sui/tree/main/crates/sui-sdk

Some examples you can find here:
https://github.com/MystenLabs/sui/tree/main/crates/sui-sdk/examples
Start with `coin_read_api.rs`, and `read_api.rs` and go from there.

**Comment by Degen-Player** [comment]
T

> If I understand you correctly, you want to use Rust code to interact with the Sui blockchain. We have a Rust SDK that you can use, so start here: https://github.com/MystenLabs/sui/tree/main/crates/sui-sdk
> 
> Some examples you can find here: https://github.com/MystenLabs/sui/tree/main/crates/sui-sdk/examples Start with `coin_read_api.rs`, and `read_api.rs` and go from there.

Those example doesn't show you how to interact with smart contract

**Comment by Degen-Player** [comment]
@stefan-mysten hey, i need support to understand plaese how to interact with move smart contract with rust if possible please

**Comment by Degen-Player** [comment]
> Check out the PTB example here, https://github.com/MystenLabs/sui/blob/main/crates/sui-sdk/examples/programmable_transactions_api.rs Particularly, you'll want to look for the Command type, and figure out how to write a Command that calls a smart contract - for this, you need to use the Command::MoveCall type and pass the right arguments to it.

this is not what i'am looking for. This is really high level interface of making things. I'm def not looking for this. What i'am looking for is a way to use function that are called in smart contract to encode it and send transaction for it

Let's say you have a dex called Name1 and this dex has a function SwapExactSuiForExactToken, what i want is to encode this function and put it into transaction data and send it.. It's not possible to do something like this in Sui .. or what?


I have been looking for this more then 1 mounth..

**Comment by stefan-mysten** [comment]
What do you mean by encode this function `SwapExactSuiForExactToken`? Encode to what? What is the end result of encoding?

**Comment by Degen-Player** [comment]
> What do you mean by encode this function `SwapExactSuiForExactToken`? Encode to what? What is the end result of encoding?

If you take look on how to interact in ethereum smart contract, you have various ways for that. The modular one is abigen which generate solidity binding at runtime. So to call a function from a smart contract you have to call a function that you want and then send the transaction


What's the way to do this in sui ? The example doesn't show this..

**Comment by stefan-mysten** [comment]
Ok, so I assume what you want to do is actually call the function X from smart contract Y. In Sui, you have `module::package::function`, so you'd have to find the module name, package name, and function name and then use MoveCall. You can do this with programmable transaction blocks (PTBs): https://docs.sui.io/guides/developer/sui-101/building-ptb#available-transactions. While this shows code in Typescript SDK, it is similar for Rust. You'll need to use MoveCall, and pass the module, package, function, and then the arguments you need to pass for that function, sign the transaction, and then execute it.

**Comment by Degen-Player** [comment]
> Ok, so I assume what you want to do is actually call the function X from smart contract Y. In Sui, you have `module::package::function`, so you'd have to find the module name, package name, and function name and then use MoveCall. You can do this with programmable transaction blocks (PTBs): https://docs.sui.io/guides/developer/sui-101/building-ptb#available-transactions. While this shows code in Typescript SDK, it is similar for Rust. You'll need to use MoveCall, and pass the module, package, function, and then the arguments you need to pass for that function, sign the transaction, and then execute it.

Okay so i'm supposed to use this https://github.com/MystenLabs/sui/blob/2ba23be291c9dfed9f27dc2fe2315d359f20edd8/crates/sui-types/src/execution.rs#L260 ?

I will try, and will come back to you. Thank you for your support. Also, does i need to import the full crate ? Since sui sdk doesn't have all crate.. i'am supposed ot import now each crate like sui type, mempool etc etc ?

**Comment by stefan-mysten** [comment]
You'll need to likely import this and probably `sui-types` for `ProgrammableMoveCall`.
```
sui-sdk = { git = "https://github.com/mystenlabs/sui", package = "sui-sdk"}
tokio = { version = "1.2", features = ["full"] }
anyhow = "1.0"
```
Under `sui-sdk` you'll find `sui_sdk::types::transaction::Command` (see this example that I referred to earlier: https://github.com/MystenLabs/sui/blob/main/crates/sui-sdk/examples/programmable_transactions_api.rs). 

You'll have to create a mutable PTB with this line:
```rust
    // programmable transactions allows the user to bundle a number of commands into one transaction
    let mut ptb = ProgrammableTransactionBuilder::new();
```
Then, you'll have to build the Command::MoveCall part:
```
ptb.command(Command::MoveCall(Box::new(
sui_types::transaction::ProgrammableMoveCall { 
    package:, 
    module: , 
    function: , 
    type_arguments: , 
    arguments:  
})));
```
Then you'll need to call `ptb.finish()` to build the PTB, and then sign the tx and execute it. https://github.com/MystenLabs/sui/blob/main/crates/sui-sdk/examples/programmable_transactions_api.rs#L64-L92

Before executing, you'll need to fetch your gas coin to pay for the fees.

I hope this helps! If time permits, I'll try to add an example soon.

**Comment by stefan-mysten** [comment]
The other way, is to use this ProgrammableTransactionBuilder stuff [**sui_transaction_builder::TransactionBuilder**](https://mystenlabs.github.io/sui/sui_transaction_builder/struct.TransactionBuilder.html)

**Comment by Degen-Player** [comment]
> You'll need to likely import this and probably `sui-types` for `ProgrammableMoveCall`.
> 
> ```
> sui-sdk = { git = "https://github.com/mystenlabs/sui", package = "sui-sdk"}
> tokio = { version = "1.2", features = ["full"] }
> anyhow = "1.0"
> ```
> 
> Under `sui-sdk` you'll find `sui_sdk::types::transaction::Command` (see this example that I referred to earlier: https://github.com/MystenLabs/sui/blob/main/crates/sui-sdk/examples/programmable_transactions_api.rs).
> 
> You'll have to create a mutable PTB with this line:
> 
> ```rust
>     // programmable transactions allows the user to bundle a number of commands into one transaction
>     let mut ptb = ProgrammableTransactionBuilder::new();
> ```
> 
> Then, you'll have to build the Command::MoveCall part:
> 
> ```
> ptb.command(Command::MoveCall(Box::new(
> sui_types::transaction::ProgrammableMoveCall { 
>     package:, 
>     module: , 
>     function: , 
>     type_arguments: , 
>     arguments:  
> })));
> ```
> 
> Then you'll need to call `ptb.finish()` to build the PTB, and then sign the tx and execute it. https://github.com/MystenLabs/sui/blob/main/crates/sui-sdk/examples/programmable_transactions_api.rs#L64-L92
> 
> Before executing, you'll need to fetch your gas coin to pay for the fees.
> 
> I hope this helps! If time permits, I'll try to add an example soon.

Thank you for your help, what kind of example i could add ? Swappping SUI & USDC could be good one ? :)   

if thi sis okay for you, i'll open pr when it's done

**Comment by stefan-mysten** [comment]
> Swappping SUI & USDC could be good one

Yes, that's a great example.

> if thi sis okay for you, i'll open pr when it's done

Absolutely, thanks for willing to contribute!
