### ISSUE TITLE
Bug: Unable to query token supply with suix_getTotalSupply once treasury cap is wrapped or deleted

### ISSUE THREAD

**Issue by Jamchello** [MystenLabs/sui#15599]
## Steps to Reproduce Issue

1. Create a new currency via `coin::create_currency`
2. Mint some coins for this currency
3. Wrap the treasury cap inside a different object, e.g. WrappedTreasury:
```move
struct WrappedTreasury <phantom T: drop> has key {
        id: UID,
        supply: TreasuryCap<T>,
    }
```
4. Share the wrapped treasury: `transfer::share_object(wrapped_treasury)`
5. Attempt to query the total supply via the rpc:
```bash
curl --location 'https://fullnode.devnet.sui.io' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "suix_getTotalSupply",
    "params": [
        "CURRENCY ID HERE"
    ]
}'
```

## Expected Result

Expected to receive the total supply of the currency.

## Actual Result

```bash
Cannot find object [0x2:🪙:XXX>] from [PACKAGE_ID] package event.
```

**Note:** I also tried minting some tokens in the init function, and then using an admin-only function to wrap the treasury cap in a seperate transaction - this results in a slightly different error:

```bash
"Object deleted at reference (0xbd910f2dbf0f43517e152d6546b6c60ae532163a47d49ea5b15fee1ee5163f2f, SequenceNumber(37), o#6ws1bVyu3F8wGy1fPHhrc2v8UyWiGbRAAuek8SwikKPD)."
```

## System Information

* OS:  macOS 14.0
* Compiler: Latest version in testnet branch

**Comment by amnn** [comment]
Hi @Jamchello, thanks for reporting this issue.  Unfortunately, this is the nature of wrapping an object -- it is no longer possible to access it at its ID (until it's unwrapped again), so if you want to read an object off-chain, it can't be wrapped.  You can imagine wrapping as a kind of "temporary deletion" or "hiding" operation.

**Comment by amnn** [comment]
The best way to do that is to freeze the `TreasuryCap` just after you create it (using `sui::transfer::public_freeze_object`).  This will make the object immutable, but still accessible via its ID.

Note that you cannot reverse this operation -- once an object is made immutable, it exists forever in its current state.
