### ISSUE TITLE
store/event/lock placeholder

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1562]

**Comment by lxfind** [comment]
@velvia I was hoping you could help scope what we plan to get done by DevNet time :)

**Comment by velvia** [comment]
Oh got it.  Yes absolutely, will be added soon.

**Comment by lxfind** [comment]
@velvia Please take a look and flesh out more details on the plans/issues in this domain. Thanks!

**Comment by velvia** [comment]
@lxfind yes 100% but dev.net deploys is taking up all my spare time.

**Comment by velvia** [comment]
Done.

**Comment by velvia** [comment]
FWIW I have roadmap of Storage related tasks here: https://www.notion.so/mystenlabs/Sui-Storage-Roadmap-Tasks-Timeline-b68bfedcfefc42c6a96e39af983c2c67
