### ISSUE TITLE
Error runnig token creation 

### ISSUE THREAD

**Issue by babygingerr** [MystenLabs/sui#15702]
`module mm::token {
    use std::option;
    use sui::coin;
    use sui::transfer;
    use sui::tx_context::{Self, TxContext};

    struct TOKEN has drop {}

    fun init(witness: TOKEN, ctx: &mut TxContext) {
        let (treasury, metadata) = coin::create_currency(witness, 9, b"TOKEN", b"TOKEN", b"", option::none(), ctx);
        transfer::public_freeze_object(metadata);
        transfer::public_transfer(treasury, tx_context::sender(ctx))
    }

}`

invalid object construction
    ┌─sui/crates/sui-framework/packages/sui-framework/sources/deny_list.move:138:32
    │  
138 │           let deny_list_object = DenyList {
    │ ╭────────────────────────────────^
139 │ │             id: object::sui_deny_list_object_id(),
    │ │             --  --------------------------------- Non fresh UID from this position
    │ │             │    
    │ │             The UID must come directly from sui::object::new. Or for tests, it can come from sui::test_scenario::new_object
140 │ │             lists,
141 │ │         };
    │ ╰─────────^ Invalid object creation without a newly created UID.

error[E10003]: invalid attribute value
  ┌─ sui/crates/sui-framework/packages/move-stdlib/sources/type_name.move:4:3
  │
4 │ #[allow(implicit_const_copy)]
  │   ^^^^^^^^^^^^^^^^^^^^^^^^^^ Unknown warning filter 'implicit_const_copy'

Failed to build Move modules: Compilation error.

**Comment by stefan-mysten** [comment]
Hi @babygingerr, thanks for reporting this issue. What version of `sui move build` do you have -- run `sui --version` or `sui move --version`?

**Comment by mekhakrishnanm** [comment]
I am also facing the same issue. Any update on what the issue is? @stefan-mysten 
My sui move version is:
sui-move 1.16.2-11511718

**Comment by tzakian** [comment]
Hi @babygingerr and @mekhakrishnanm!

This is due to a change in the latest release, but because of this there's a mismatch between what is currently allowed on the particular network (devnet in this case), and your local CLI (which us running the `mainnet` release). 

Two ways you can resolve this error are either to:
1. Point your `Sui` dependency in your `Move.toml` to `framework/mainnet` if that would work for your development efforts. You will need to update your CLI once `mainnet` is updated next week though; or 
2. You can build/install the CLI from the `devnet` branch and this should resolve the issues that you're encountering here as well:
```
cargo install --locked --git https://github.com/MystenLabs/sui.git --branch devnet sui
```

**Comment by CaoThien96** [comment]
You applied solution 1 and it worked fine until this morning. The error has reappeared again.

**Comment by upendra-eth** [comment]
Hi @babygingerr and @mekhakrishnanm 

I wanted to share my experience with this issue, as I faced a similar problem recently.

What worked for me was:

1. Updating the Sui CLI tool: It's important to keep it up-to-date with the latest changes. You can usually do this by running

 `cargo install --locked --git https://github.com/MystenLabs/sui.git --branch testnet sui`

2. Setting the active environment to testnet: This ensures compatibility with the current testnet release. You can use the following command:

`sui client set-active-env testnet`

3. Updating the Sui dependency in Move.toml:

```move
[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
```
Remember to rebuild your Move modules after making these changes.

I hope this helps!
