### ISSUE TITLE
[RPC] RPC Server deployment

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#1572]

**Comment by todd-mystenlabs** [comment]
I don't think this needs to be automated for our initial devnet date.

**Comment by mystenmark** [comment]
I believe it does - its a critical part of a functional devnet. Its already done on gcp (https://github.com/MystenLabs/sui-operations/pull/12) and shouldn't be at all difficult to include in the AWS deployment.

**Comment by velvia** [comment]
This is done now.  Functional RPC server is at gateway.devnet.sui.io
