### ISSUE TITLE
Document how to create and run a fullnode

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#1576]
Running a full node is a prerequisite for becoming a validator. Further, we expect non-validators to run full nodes. So we need these instructions outside of the validator documentation being formed in:
https://github.com/MystenLabs/sui/issues/1493

And similarly, all of this depends upon us nailing down system requirements:
https://github.com/MystenLabs/sui/issues/1367

All of this is part of:
[go/sui-validator-onboarding](https://app.golinks.io/sui-validator-onboarding)

**Comment by Clay-Mysten** [comment]
Adding Brandon as I caught reference to him having a doc in our meeting on this topic today. Brandon, please send it my way!

**Comment by Clay-Mysten** [comment]
Brandon has an excellent start on documentation in:
https://app.golinks.io/sui-fullnode

**Comment by Clay-Mysten** [comment]
See a start on docs and related tasks in:
[go/fullnode-overview](https://app.golinks.io/fullnode-overview) 
[go/fullnode-setup](https://app.golinks.io/fullnode-setup) 
[go/fullnode-docnotes](https://app.golinks.io/fullnode-docnotes)

Please contribute your knowledge.

**Comment by Clay-Mysten** [comment]
See the PRs above for the changes needed to announce the full node docs.

**Comment by Clay-Mysten** [comment]
+Tom, Evan, Lu and Alonso.

This work is largely done:
https://github.com/MystenLabs/sui/blob/main/doc/src/build/fullnode.md

Except:
1. Dockerfile inclusion and linking
2. Storage specification

Tom has the former in the works. And the second is now at "a handful of GBs" which is vague and small.

Lu, Evan and Alonso had a healthy discussion about the size and economics of the situation in:
[go/fullnode-setup](https://app.golinks.io/fullnode-setup)

But now that those contents have been published, I'm not sure much will be done with that discussion. So raising the issue here. Let's sort the storage spec out.

**Comment by tharbert** [comment]
Continuing on the conversation from here: 

https://docs.google.com/document/d/1dqAxraShsxSa90HHMcv3JyOpn8IamJra6SXP5oWeo_Y/edit?disco=AAAAZIeDxeo

Do we want to leverage this docker compose config i have built and tested for this?

https://github.com/MystenLabs/sui/tree/tharbert/docker_fullnode/docker/fullnode

**Comment by Clay-Mysten** [comment]
> Continuing on the conversation from here:
> 
> https://docs.google.com/document/d/1dqAxraShsxSa90HHMcv3JyOpn8IamJra6SXP5oWeo_Y/edit?disco=AAAAZIeDxeo
> 
> Do we want to leverage this docker compose config i have built and tested for this?
> 
> https://github.com/MystenLabs/sui/tree/tharbert/docker_fullnode/docker/fullnode

@bmwill what do you think? And will we link into Tom's branch or main?

**Comment by Clay-Mysten** [comment]
> +Tom, Evan, Lu and Alonso.
> 
> This work is largely done: https://github.com/MystenLabs/sui/blob/main/doc/src/build/fullnode.md
> 
> Except:
> 
> 1. Dockerfile inclusion and linking
> 2. Storage specification
> 
> Tom has the former in the works. And the second is now at "a handful of GBs" which is vague and small.
> 
> Lu, Evan and Alonso had a healthy discussion about the size and economics of the situation in: [go/fullnode-setup](https://app.golinks.io/fullnode-setup)
> 
> But now that those contents have been published, I'm not sure much will be done with that discussion. So raising the issue here. Let's sort the storage spec out.

I'm noting we are taking on storage specification in:
https://github.com/MystenLabs/sui/pull/2591

**Comment by Clay-Mysten** [comment]
> I'm adding @allan-bailey here as Allan suggests we add a note about how to configure and expose the metrics endpoint in the Monitoring section of our fullnode doc. @velvia can you help? Thanks!

I see this:
```
metrics-address: "127.0.0.1:9184"
```
In:
https://github.com/MystenLabs/sui/blob/main/crates/sui-config/data/fullnode-template.yaml

What next?

**Comment by Clay-Mysten** [comment]
@velvia is now suggesting in go/fullnode-setup we recommend 100GB in storage. When you all decide, please edit the file directly and send me the PR to review:

**Comment by Clay-Mysten** [comment]
Tom added the Docker solution in:
https://github.com/MystenLabs/sui/pull/2618

I'm editing that in:
https://github.com/MystenLabs/sui/pull/2640

And linking to it from the fullnode doc in:
https://github.com/MystenLabs/sui/pull/2641

Note, I included some TODOs with questions in PR #2640. Team, please advise.

**Comment by tharbert** [comment]
Thank you @Clay-Mysten - I added some comments under the TODO's.

Do we need to get docker/fullnode from main into the devnet branch?

**Comment by Clay-Mysten** [comment]
Reopening to announce the Docker change once tested.

**Comment by Clay-Mysten** [comment]
We announced Docker:
https://docs.sui.io/learn#see-whats-new
https://discord.com/channels/916379725201563759/968392942517649438/989990506803114014

Now closing this out.
