### ISSUE TITLE
[documentation][TypeScript SDK] Add documentation for SDK

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#1578]

**Comment by Andrew47** [comment]
Thank you for setting up this issue. As well as documenting the different pieces of functionality this SDK provides, it would be great if example commands were provided that give valid object and address results which would help with testing.

**Comment by 666lcz** [comment]
Hi @Andrew47 , I added some example commands in https://github.com/MystenLabs/sui/pull/1646 as well as a demo app in https://github.com/MystenLabs/sdk-test-app. Let me know if you have any feedback

**Comment by Clay-Mysten** [comment]
Chris is making great progress. We agree to link to the contents from the Dev Portal docs in the post DevNet push.

**Comment by Clay-Mysten** [comment]
Hi Chris,

We don't yet link to these docs. Should we yet? I recall you saying to wait yet forget where we are tracking that addition. Thanks!

**Comment by Clay-Mysten** [comment]
@666lcz see:
https://github.com/MystenLabs/sui/pull/2359#issuecomment-1158245542
