### ISSUE TITLE
Add shared object version in Signed Effect Transaction

### ISSUE THREAD

**Issue by asonnino** [MystenLabs/sui#1580]
If we don't do it we aren't able to sync and the client cannot really make sense of the execution result.

**Comment by gdanezis** [comment]
More context for this issue:
* The exact shared object version and digest is not know to the creator of the transaction unlike the owned or immutable objects, at the time of the transaction creation. 
* Instead the object version is determined once the certificate is sequenced by consensus and assigned by validators, and is known (a prerequisite) at the time the ceritficate can be processed.
* At that time we need to take the shared object referenced used as inputs, and add them to the effects certificate, to allow anyone with an effects certificate to fully reproduce the execution of the transaction. 
* That should include the the sequence of shared object IDs, their version and the digest at that version.

**Comment by lxfind** [comment]
One challenge that I foresee in the Gateway is, even with the effects, to be able to re-execute it we also need the input objects. For shared objects, it's unclear to me where to get the objects.
