### ISSUE TITLE
[TS SDK] TransactionBlock `object(...)` doesn't respect the `mutable` value for shared objects on subsequent calls

### ISSUE THREAD

**Issue by kklas** [MystenLabs/sui#15821]
Suppose I create a transaction block and add a shared object reference to it as a `ObjectCallArg` but with `mutable` set to `false`.

 ```ts
const txb = new TransactionBlock()

const objArg1 = Object: { Shared: { objectId: '0x123', initialSharedVersion: 5, mutable: false } }
txb.object(objArg1)
```

and then later I add the same object but with `mutable` set to `true`

```ts
const objArg2 = Object: { Shared: { objectId: '0x123', initialSharedVersion: 5, mutable: true } }
txb.object(objArg2)
```

In this case the resulting object reference in the TransactionBlock won't be updated to `true` but remain `false`. This will fail the transaction e.g. when composing a txb with multiple different calls that reference the same object but some as mutable and some as not.

The problem is here https://github.com/MystenLabs/sui/blob/main/sdk/typescript/src/builder/TransactionBlock.ts#L309-L323. When subsequent calls are made with an `ObjectCallArg` of the same id, it will just keep the existing value instead of updating the `mutable` value if needed.

cc @hayes-mysten

**Comment by Jordan-Mysten** [comment]
@kklas I think I have a fix here, we basically upgrade the mutable whenever shared object refs are added: https://github.com/MystenLabs/sui/pull/15854/files#diff-0bbc88bc7d3326c826a543599c232f71e1aee2389c644ac1fc35a05b32cf0668R321
