### ISSUE TITLE
Unable to publish or interact with contract through multisig address

### ISSUE THREAD

**Issue by Ayushoo07** [MystenLabs/sui#15829]
## Description
While exploring the multi-signature documentation in SUI, I successfully tested an example involving the transfer of funds from a multi-signature address, following the provided documentation. However, when I extended my exploration to publish a contract using a multi-signature address, I encountered an issue. Despite diligently following the documented steps
### the execution of the command:
sui client execute-signed-tx --tx-bytes <TX_BYTES> --signatures <SERIALIZED-MULTISIG>
### i am getting error :
RPC call failed: ErrorObject { code: ServerError(-32002), message: "Invalid user signature: Required Signature from 0x059596e023f208ca86c039401ec6abf1ff49eae0b51195b61a137e340febb2bb is absent [\"0x5553365094688a48825fd379abea9d3f351969a708f5ec23006be0dc871d83d1\"].", data: None }
Caused by:
    RPC call failed: ErrorObject { code: ServerError(-32002), message: "Invalid user signature: Required Signature from 0x059596e023f208ca86c039401ec6abf1ff49eae0b51195b61a137e340febb2bb is absent [\"0x5553365094688a48825fd379abea9d3f351969a708f5ec23006be0dc871d83d1\"].", data: None }

even after inclusion of signatures above threshold wieght

### Expected Result
The contract was expected to be published successfully. 

## System Information

* OS: ubantu 20.04.6
* Compiler: sui 1.16

**Comment by joyqvq** [comment]
please follow up more details regarding steps to reproduce. please share the full command you tried to run, ie. tx-bytes, signature, public keys and its weight constructing the multisig, and its multisig address. feel free to go into discord and tag @joyqvq if you do not wish to share the info over github.

**Comment by Ayushoo07** [comment]
##Steps are mentioned below :
### Step 1: Generated a Multi-Signature address :
 
sui keytool multi-sig-address --pks AEXu9wq8FzpVKRs11ERam1WmMT3EsEj+9AGjXoNGymLR AQJKUWc3vabBsnKzvYPYymwLl+HBDUdoNGFcT4feNaPQTA== AQJ2Gg+luhfx57HVFtkzNCYZCgeEEesxjsstKg3hlIQttA== --weights 1 2 3 --threshold 3

#### output
╭─────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────╮
│ multisigAddress │  0x5553365094688a48825fd379abea9d3f351969a708f5ec23006be0dc871d83d1                            │
│ multisig        │ ╭────────────────────────────────────────────────────────────────────────────────────────────╮ │
│                 │ │ ╭─────────────────┬──────────────────────────────────────────────────────────────────────╮ │ │
│                 │ │ │ address         │  0x3c1c95b3bf1d7a5f411c6691c7bf223255d75a6998fbeb6477769b29d36d2246  │ │ │
│                 │ │ │ publicBase64Key │  AEXu9wq8FzpVKRs11ERam1WmMT3EsEj+9AGjXoNGymLR                        │ │ │
│                 │ │ │ weight          │  1                                                                   │ │ │
│                 │ │ ╰─────────────────┴──────────────────────────────────────────────────────────────────────╯ │ │
│                 │ │ ╭─────────────────┬──────────────────────────────────────────────────────────────────────╮ │ │
│                 │ │ │ address         │  0xcaf589faa6191533a85f1a44c6142afd35c8bc5b0a580a0998367360f438e4bb  │ │ │
│                 │ │ │ publicBase64Key │  AQJKUWc3vabBsnKzvYPYymwLl+HBDUdoNGFcT4feNaPQTA==                    │ │ │
│                 │ │ │ weight          │  2                                                                   │ │ │
│                 │ │ ╰─────────────────┴──────────────────────────────────────────────────────────────────────╯ │ │
│                 │ │ ╭─────────────────┬──────────────────────────────────────────────────────────────────────╮ │ │
│                 │ │ │ address         │  0xf1e916bb8903aefa2ae6abef283adc13cde6fe9809b548502b7fe786c1438bf6  │ │ │
│                 │ │ │ publicBase64Key │  AQJ2Gg+luhfx57HVFtkzNCYZCgeEEesxjsstKg3hlIQttA==                    │ │ │
│                 │ │ │ weight          │  3                                                                   │ │ │
│                 │ │ ╰─────────────────┴──────────────────────────────────────────────────────────────────────╯ │ │
│                 │ ╰────────────────────────────────────────────────────────────────────────────────────────────╯ │

### Step 2: Generated an unsigned transaction to publish my contract :

sui client publish --gas-budget 100000000 --serialize-unsigned-transaction
#### Output :
Successfully verified dependencies on-chain against source.
AAABACA8HJWzvx16X0EcZpHHvyIyVddaaZj762R3dpsp020iRgIEAZIJoRzrCwYAAAALAQAQAhAyA0JeBKABFAW0Ad4BB5IDvAIIzgVgBq4GXQqLBw0MmAfCAQ3aCAIAHwEZAgoCDgIYAiECIgIjAAUCAAAEDAABAwcBAAACAAQBAAEDAQwBAAEDAgwBAAEDBgwBAAEECAQABgcCAAcJBwAAEwABAAARAgMAAA0EAQAAFAUBAAAMBgEAACAHCAABFwELAQADCxobAQADDB4IAQADDw0OAQIDFRgBAQADHhwdAQADIB8IAQAEFhQVAAUbEAEBDAUcEwEBDAYdEQMABgoJDA4PDxIPFgoMBwwLDAgMDAwCCAAHCAgAAgcIAQcICAEFBAsGAQgACAEFBggIBAcLBgEIAAMFBwgIBAcLBgEIAAcLBAEIAAMHCAgBBwsGAQgAAQMCCwUBCAALBgEIAAEICQELAgEJAAEIAAcJAAIKAgoCCgILAgEICQcICAILBgEJAAsFAQkAAQsFAQgAAQkAAQYICAELBgEIAAIJAAUBBwgIAQgHAQgBAgUFBAcLBgEJAAMFBwgIAQsEAQgAAQcLBAEJAAEHCwMBCQADBwsDAQkAAwcICAELBAEJAAIHCwYBCQALBAEJAAEGCwYBCQAHQmFsYW5jZQRDb2luDENvaW5NZXRhZGF0YQZPcHRpb24FT3duZXIFVE9LRU4LVHJlYXN1cnlDYXAJVHhDb250ZXh0A1VJRANVcmwHYmFsYW5jZQtiYWxhbmNlX211dARidXJuDGNoYW5nZV9vd25lcgRjb2luD2NyZWF0ZV9jdXJyZW5jeQtkdW1teV9maWVsZBFnZXRfb3duZXJfYWRkcmVzcwJpZARpbml0BG1pbnQRbWludF9hbmRfdHJhbnNmZXIDbmV3BG5vbmUGb2JqZWN0Bm9wdGlvbgVvd25lchRwdWJsaWNfZnJlZXplX29iamVjdA9wdWJsaWNfdHJhbnNmZXIGc2VuZGVyBHRha2UFdG9rZW4MdG90YWxfc3VwcGx5CHRyYW5zZmVyCnR4X2NvbnRleHQDdXJsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAQEAAwgBAAAAAAAAAAUgPSCjDZAgSa855vAslE5W67sKR9tdttxaaZlg4CVMINoKAgMCSEMKAgsKSFlEUk9fQ09JTgoCFxZVdGlsaXR5IENvaW4gZm9yIEhZRFJPAAIBEAEBAgISCAcaBQAAAAAJJgsAMQkHAwcEBwU4AAoBOAEMAgwDCwI4AgsDCgEuERA4AwoBEQ0KAS4REBIBCgEuERA4BAoBEQ0KAS4REBIBCwEuERA4BAIBAQQAAQQLABAAFAICAQQAFxkLAxEQDAUOARAAFAwECwULBCEEDAUOBwEnCgINAQ8AFQsBCgI4BAsACwI4AwIDAQQAAQYLAAsBCwILAzgFAgQBBAAZCwsBOAYLAgsDOAcMBAsACwQ4CAECBQEEAAEECwAuOAkCAQEAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIBAQIAAAEAADwclbO/HXpfQRxmkce/IjJV11ppmPvrZHd2mynTbSJGAXm2lqorQHnj/N/bgTesruJp1Y1Ulc/NuidDpotjgjrmeFIPAAAAAAAg84gOcaS2y5/Nu1IDsmhdWNWKg7/Vi5O/k4BzWPpWjnU8HJWzvx16X0EcZpHHvyIyVddaaZj762R3dpsp020iRugDAAAAAAAAAOH1BQAAAAAA

### Step 3: Signed the txn with : 0x3c1c95b3bf1d7a5f411c6691c7bf223255d75a6998fbeb6477769b29d36d2246 (ed25519 ) weight: 1
sui keytool sign --address 0x3c1c95b3bf1d7a5f411c6691c7bf223255d75a6998fbeb6477769b29d36d2246  --data AAABACA8HJWzvx16X0EcZpHHvyIyVddaaZj762R3dpsp020iRgIEAZIJoRzrCwYAAAALAQAQAhAyA0JeBKABFAW0Ad4BB5IDvAIIzgVgBq4GXQqLBw0MmA
fCAQ3aCAIAHwEZAgoCDgIYAiECIgIjAAUCAAAEDAABAwcBAAACAAQBAAEDAQwBAAEDAgwBAAEDBgwBAAEECAQABgcCAAcJBwAAEwABAAARAgMAAA0EAQAAFAUBAAAMBgEAACAHCAABF
wELAQADCxobAQADDB4IAQADDw0OAQIDFRgBAQADHhwdAQADIB8IAQAEFhQVAAUbEAEBDAUcEwEBDAYdEQMABgoJDA4PDxIPFgoMBwwLDAgMDAwCCAAHCAgAAgcIAQcICAEFBAsGAQgA
CAEFBggIBAcLBgEIAAMFBwgIBAcLBgEIAAcLBAEIAAMHCAgBBwsGAQgAAQMCCwUBCAALBgEIAAEICQELAgEJAAEIAAcJAAIKAgoCCgILAgEICQcICAILBgEJAAsFAQkAAQsFAQgAAQk
AAQYICAELBgEIAAIJAAUBBwgIAQgHAQgBAgUFBAcLBgEJAAMFBwgIAQsEAQgAAQcLBAEJAAEHCwMBCQADBwsDAQkAAwcICAELBAEJAAIHCwYBCQALBAEJAAEGCwYBCQAHQmFsYW5jZQ
RDb2luDENvaW5NZXRhZGF0YQZPcHRpb24FT3duZXIFVE9LRU4LVHJlYXN1cnlDYXAJVHhDb250ZXh0A1VJRANVcmwHYmFsYW5jZQtiYWxhbmNlX211dARidXJuDGNoYW5nZV9vd25lc
gRjb2luD2NyZWF0ZV9jdXJyZW5jeQtkdW1teV9maWVsZBFnZXRfb3duZXJfYWRkcmVzcwJpZARpbml0BG1pbnQRbWludF9hbmRfdHJhbnNmZXIDbmV3BG5vbmUGb2JqZWN0Bm9wdGlv
bgVvd25lchRwdWJsaWNfZnJlZXplX29iamVjdA9wdWJsaWNfdHJhbnNmZXIGc2VuZGVyBHRha2UFdG9rZW4MdG90YWxfc3VwcGx5CHRyYW5zZmVyCnR4X2NvbnRleHQDdXJsAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAQEAAwgBAAAAAAAAAA
UgPSCjDZAgSa855vAslE5W67sKR9tdttxaaZlg4CVMINoKAgMCSEMKAgsKSFlEUk9fQ09JTgoCFxZVdGlsaXR5IENvaW4gZm9yIEhZRFJPAAIBEAEBAgISCAcaBQAAAAAJJgsAMQkHA
wcEBwU4AAoBOAEMAgwDCwI4AgsDCgEuERA4AwoBEQ0KAS4REBIBCgEuERA4BAoBEQ0KAS4REBIBCwEuERA4BAIBAQQAAQQLABAAFAICAQQAFxkLAxEQDAUOARAAFAwECwULBCEEDAUO
BwEnCgINAQ8AFQsBCgI4BAsACwI4AwIDAQQAAQYLAAsBCwILAzgFAgQBBAAZCwsBOAYLAgsDOAcMBAsACwQ4CAECBQEEAAEECwAuOAkCAQEAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIBAQIAAAEAADwclbO/HXpfQRxmkce/IjJV11ppmPvrZHd2mynTbSJGAXm2lqorQHnj/N/bgTesruJp1Y1Ulc
/NuidDpotjgjrmeFIPAAAAAAAg84gOcaS2y5/Nu1IDsmhdWNWKg7/Vi5O/k4BzWPpWjnU8HJWzvx16X0EcZpHHvyIyVddaaZj762R3dpsp020iRugDAAAAAAAAAOH1BQAAAAAA

### Step 4: Signed the txn with : 0xf1e916bb8903aefa2ae6abef283adc13cde6fe9809b548502b7fe786c1438bf6 (secp256k1) weight :3 

sui keytool sign --address 0xf1e916bb8903aefa2ae6abef283adc13cde6fe9809b548502b7fe786c1438bf6  --data AAABACA8HJWzvx16X0EcZpHHvyIyVddaaZj762R3dpsp020iRgIEAZIJoRzrCwYAAAALAQAQAhAyA0JeBKABFAW0Ad4BB5IDvAIIzgVgBq4GXQqLBw0MmA
fCAQ3aCAIAHwEZAgoCDgIYAiECIgIjAAUCAAAEDAABAwcBAAACAAQBAAEDAQwBAAEDAgwBAAEDBgwBAAEECAQABgcCAAcJBwAAEwABAAARAgMAAA0EAQAAFAUBAAAMBgEAACAHCAABF
wELAQADCxobAQADDB4IAQADDw0OAQIDFRgBAQADHhwdAQADIB8IAQAEFhQVAAUbEAEBDAUcEwEBDAYdEQMABgoJDA4PDxIPFgoMBwwLDAgMDAwCCAAHCAgAAgcIAQcICAEFBAsGAQgA
CAEFBggIBAcLBgEIAAMFBwgIBAcLBgEIAAcLBAEIAAMHCAgBBwsGAQgAAQMCCwUBCAALBgEIAAEICQELAgEJAAEIAAcJAAIKAgoCCgILAgEICQcICAILBgEJAAsFAQkAAQsFAQgAAQk
AAQYICAELBgEIAAIJAAUBBwgIAQgHAQgBAgUFBAcLBgEJAAMFBwgIAQsEAQgAAQcLBAEJAAEHCwMBCQADBwsDAQkAAwcICAELBAEJAAIHCwYBCQALBAEJAAEGCwYBCQAHQmFsYW5jZQ
RDb2luDENvaW5NZXRhZGF0YQZPcHRpb24FT3duZXIFVE9LRU4LVHJlYXN1cnlDYXAJVHhDb250ZXh0A1VJRANVcmwHYmFsYW5jZQtiYWxhbmNlX211dARidXJuDGNoYW5nZV9vd25lc
gRjb2luD2NyZWF0ZV9jdXJyZW5jeQtkdW1teV9maWVsZBFnZXRfb3duZXJfYWRkcmVzcwJpZARpbml0BG1pbnQRbWludF9hbmRfdHJhbnNmZXIDbmV3BG5vbmUGb2JqZWN0Bm9wdGlv
bgVvd25lchRwdWJsaWNfZnJlZXplX29iamVjdA9wdWJsaWNfdHJhbnNmZXIGc2VuZGVyBHRha2UFdG9rZW4MdG90YWxfc3VwcGx5CHRyYW5zZmVyCnR4X2NvbnRleHQDdXJsAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAQEAAwgBAAAAAAAAAA
UgPSCjDZAgSa855vAslE5W67sKR9tdttxaaZlg4CVMINoKAgMCSEMKAgsKSFlEUk9fQ09JTgoCFxZVdGlsaXR5IENvaW4gZm9yIEhZRFJPAAIBEAEBAgISCAcaBQAAAAAJJgsAMQkHA
wcEBwU4AAoBOAEMAgwDCwI4AgsDCgEuERA4AwoBEQ0KAS4REBIBCgEuERA4BAoBEQ0KAS4REBIBCwEuERA4BAIBAQQAAQQLABAAFAICAQQAFxkLAxEQDAUOARAAFAwECwULBCEEDAUO
BwEnCgINAQ8AFQsBCgI4BAsACwI4AwIDAQQAAQYLAAsBCwILAzgFAgQBBAAZCwsBOAYLAgsDOAcMBAsACwQ4CAECBQEEAAEECwAuOAkCAQEAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIBAQIAAAEAADwclbO/HXpfQRxmkce/IjJV11ppmPvrZHd2mynTbSJGAXm2lqorQHnj/N/bgTesruJp1Y1Ulc
/NuidDpotjgjrmeFIPAAAAAAAg84gOcaS2y5/Nu1IDsmhdWNWKg7/Vi5O/k4BzWPpWjnU8HJWzvx16X0EcZpHHvyIyVddaaZj762R3dpsp020iRugDAAAAAAAAAOH1BQAAAAAA

### Step 5 : Combine individual signatures into a multisig

sui keytool multi-sig-combine-partial-sig --pks AEXu9wq8FzpVKRs11ERam1WmMT3EsEj+9AGjXoNGymLR AQJKUWc3vabBsnKzvYPYymwLl+HBDUdoNGFcT4feNaPQTA== AQJ2Gg+luhfx57HVFtkzNCYZCgeEEesxjsstKg3hlIQttA== --weights 1 2 3 --threshold 3
 --sigs AEbyc5kku1n+H2FXxj1XJ/NQmD1fa8q1bjspeofy4FB8TIWYTznl9M7pHXp+gV7B9qyxzUGDREIgviuyXRkP/w5F7vcKvBc6VSkbNdREWptVpjE9xLBI/vQBo16DRspi0Q=
= AZISWTRlW/y7H93wn2HYVX9/SvDkVg6zUl/XeFRFOsOPKKqav2KbAcWIaTCzbyjUgP0DY86IEyHCvyUCYiwy608CdhoPpboX8eex1RbZMzQmGQoHhBHrMY7LLSoN4ZSELbQ=

#### output : 
╭────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ multisigAddress    │  0x5553365094688a48825fd379abea9d3f351969a708f5ec23006be0dc871d83d1                                                                                                                                                                                                                                                                    │
│ multisigParsed     │  AwIARvJzmSS7Wf4fYVfGPVcn81CYPV9ryrVuOyl6h/LgUHxMhZhPOeX0zukden6BXsH2rLHNQYNEQiC+K7JdGQ//DgGSElk0ZVv8ux/d8J9h2FV/f0rw5FYOs1Jf13hURTrDjyiqmr9imwHFiGkws28o1ID9A2POiBMhwr8lAmIsMutPBQADAEXu9wq8FzpVKRs11ERam1WmMT3EsEj+9AGjXoNGymLRAQECSlFnN72mwbJys72D2MpsC5fhwQ1HaDRhXE+H3jWj0EwCAQJ2Gg+luhfx57HVFtkzNCYZCgeEEesxjsstKg3hlIQttAMDAA==  │
│ multisigSerialized │  AwIARvJzmSS7Wf4fYVfGPVcn81CYPV9ryrVuOyl6h/LgUHxMhZhPOeX0zukden6BXsH2rLHNQYNEQiC+K7JdGQ//DgGSElk0ZVv8ux/d8J9h2FV/f0rw5FYOs1Jf13hURTrDjyiqmr9imwHFiGkws28o1ID9A2POiBMhwr8lAmIsMutPBQADAEXu9wq8FzpVKRs11ERam1WmMT3EsEj+9AGjXoNGymLRAQECSlFnN72mwbJys72D2MpsC5fhwQ1HaDRhXE+H3jWj0EwCAQJ2Gg+luhfx57HVFtkzNCYZCgeEEesxjsstKg3hlIQttAMDAA==  │
╰────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

### Step 6 : Execute a transaction with multisig

sui client execute-signed-tx --tx-bytes AAABACA8HJWzvx16X0EcZpHHvyIyVddaaZj762R3dpsp020iRgIEAZIJoRzrCwYAAAALAQAQAhAyA0JeBKABFAW0Ad4BB5IDvAIIzgVgBq4GXQqLBw0MmAfCAQ3aCAIAHwEZAgoCDgIYAiECIgIjAAUCAAAEDAABAwcBAAACAAQBAAEDAQwBAAEDAgwBAAEDBgwBAAEECAQABgcCAAcJBwAAEwABAAARAgMAAA0EAQAAFAUBAAAMBgEAACAHCAABFwELAQADCxobAQADDB4IAQADDw0OAQIDFRgBAQADHhwdAQADIB8IAQAEFhQVAAUbEAEBDAUcEwEBDAYdEQMABgoJDA4PDxIPFgoMBwwLDAgMDAwCCAAHCAgAAgcIAQcICAEFBAsGAQgACAEFBggIBAcLBgEIAAMFBwgIBAcLBgEIAAcLBAEIAAMHCAgBBwsGAQgAAQMCCwUBCAALBgEIAAEICQELAgEJAAEIAAcJAAIKAgoCCgILAgEICQcICAILBgEJAAsFAQkAAQsFAQgAAQkAAQYICAELBgEIAAIJAAUBBwgIAQgHAQgBAgUFBAcLBgEJAAMFBwgIAQsEAQgAAQcLBAEJAAEHCwMBCQADBwsDAQkAAwcICAELBAEJAAIHCwYBCQALBAEJAAEGCwYBCQAHQmFsYW5jZQRDb2luDENvaW5NZXRhZGF0YQZPcHRpb24FT3duZXIFVE9LRU4LVHJlYXN1cnlDYXAJVHhDb250ZXh0A1VJRANVcmwHYmFsYW5jZQtiYWxhbmNlX211dARidXJuDGNoYW5nZV9vd25lcgRjb2luD2NyZWF0ZV9jdXJyZW5jeQtkdW1teV9maWVsZBFnZXRfb3duZXJfYWRkcmVzcwJpZARpbml0BG1pbnQRbWludF9hbmRfdHJhbnNmZXIDbmV3BG5vbmUGb2JqZWN0Bm9wdGlvbgVvd25lchRwdWJsaWNfZnJlZXplX29iamVjdA9wdWJsaWNfdHJhbnNmZXIGc2VuZGVyBHRha2UFdG9rZW4MdG90YWxfc3VwcGx5CHRyYW5zZmVyCnR4X2NvbnRleHQDdXJsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAQEAAwgBAAAAAAAAAAUgPSCjDZAgSa855vAslE5W67sKR9tdttxaaZlg4CVMINoKAgMCSEMKAgsKSFlEUk9fQ09JTgoCFxZVdGlsaXR5IENvaW4gZm9yIEhZRFJPAAIBEAEBAgISCAcaBQAAAAAJJgsAMQkHAwcEBwU4AAoBOAEMAgwDCwI4AgsDCgEuERA4AwoBEQ0KAS4REBIBCgEuERA4BAoBEQ0KAS4REBIBCwEuERA4BAIBAQQAAQQLABAAFAICAQQAFxkLAxEQDAUOARAAFAwECwULBCEEDAUOBwEnCgINAQ8AFQsBCgI4BAsACwI4AwIDAQQAAQYLAAsBCwILAzgFAgQBBAAZCwsBOAYLAgsDOAcMBAsACwQ4CAECBQEEAAEECwAuOAkCAQEAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIBAQIAAAEAADwclbO/HXpfQRxmkce/IjJV11ppmPvrZHd2mynTbSJGAXm2lqorQHnj/N/bgTesruJp1Y1Ulc/NuidDpotjgjrmeFIPAAAAAAAg84gOcaS2y5/Nu1IDsmhdWNWKg7/Vi5O/k4BzWPpWjnU8HJWzvx16X0EcZpHHvyIyVddaaZj762R3dpsp020iRugDAAAAAAAAAOH1BQAAAAAA --signatures AwIARvJzmSS7Wf4fYVfGPVcn81CYP
V9ryrVuOyl6h/LgUHxMhZhPOeX0zukden6BXsH2rLHNQYNEQiC+K7JdGQ//DgGSElk0ZVv8ux/d8J9h2FV/f0rw5FYOs1Jf13hURTrDjyiqmr9imwHFiGkws28o1ID9A2POiBMhwr8lAmIsMutPBQADAEXu9wq8FzpVKRs11ERam1WmMT3EsEj+9AGjXoNGymLRAQECSlFnN72mwbJys72D2MpsC5fhwQ1HaD
RhXE+H3jWj0EwCAQJ2Gg+luhfx57HVFtkzNCYZCgeEEesxjsstKg3hlIQttAMDAA==

#### Output : 

RPC call failed: ErrorObject { code: ServerError(-32002), message: "Invalid user signature: Required Signature from 0x3c1c95b3bf1d7a5f411c6691c7bf223255d75a6998fbeb6477769b29d36d2246 is absent [\"0x5553365094688a48825fd379abea9d3f351969a708f5ec23006be0dc871d83d1\"].", data: None }

Caused by:
    RPC call failed: ErrorObject { code: ServerError(-32002), message: "Invalid user signature: Required Signature from 0x3c1c95b3bf1d7a5f411c6691c7bf223255d75a6998fbeb6477769b29d36d2246 is absent [\"0x5553365094688a48825fd379abea9d3f351969a708f5ec23006be0dc871d83d1\"].", data: None }

**Comment by joyqvq** [comment]
`sui client publish --gas-budget 100000000 --serialize-unsigned-transaction`

this commands defaults to set the transaction sender as the active address of your wallet if you do not provide the gas object in the cli arg: https://github.com/MystenLabs/sui/blob/1607d721801a7b8600f00aac52497c50c36efd45/crates/sui/src/client_commands.rs#L856

this throws the error bc a multisig tx is expecting the sender to be the multisig address (0x55...) but the default active address assumed by this command is 0x3c...

so one way to get around it is to actually pass in the gas object in the arg`sui publish --gas 0x..` and makes sure the gas object owner is indeed the multisig address 0x55...

**Comment by Ayushoo07** [comment]
i tried to change my active address to that multi-sig address but it was showing "address not added in wallet"  and i am not getting any private key for that address .

is there any command to change that active address to multi-sig address

**Comment by joyqvq** [comment]
``` one way to get around it is to actually pass in the gas object in the arg sui publish --gas 0x.. and makes sure the gas object owner is indeed the multisig address 0x55...
```
