### ISSUE TITLE
Cannot automatically connect to wallet

### ISSUE THREAD

**Issue by EnettyTech** [MystenLabs/sui#15822]
### Cannot automatically connect to wallet
 My dapp cannot automatically connect to Sui Wallet when reloaded even though.
I have set `autoConnect=true` in `WalletProvider`. 
```
import { SuiClientProvider,WalletProvider } from '@mysten/dapp-kit';
import { getFullnodeUrl } from '@mysten/sui.js/client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { darkTheme } from './theme';

const queryClient = new QueryClient();
const networks = {
  devnet: { url: getFullnodeUrl('devnet') },
  testnet: { url: getFullnodeUrl('testnet') },
  mainnet: { url: getFullnodeUrl('mainnet') },
};

export function SuiModalProvider({ children }: any) {
  return (
    <QueryClientProvider client={queryClient} >
      <SuiClientProvider networks={networks} defaultNetwork="devnet" >
        <WalletProvider theme={darkTheme} autoConnect>{children}</WalletProvider>
      </SuiClientProvider>
    </QueryClientProvider>
  );
}
```

The state of the `useAutoConnectWallet` hook returns `attempted`.

Dependencies:

- `@mysten/dapp-kit: ^0.11.1`
- `@mysten/sui.js: ^0.49.1`
- `@tanstack/react-query: ^5.17.15`
- `react": ^18.2.0`

**Comment by Jordan-Mysten** [comment]
@EnettyTech Have you connected to the wallet at least once beforehand? The auto connect code will only attempt to connect if you've successfully connected beforehand, otherwise it will consider itself as `attempted` because there is nothing for it to do.

**Comment by EnettyTech** [comment]
> @EnettyTech Have you connected to the wallet at least once beforehand? The auto connect code will only attempt to connect if you've successfully connected beforehand, otherwise it will consider itself as `attempted` because there is nothing for it to do.

Yes, I had successfully connected to the my wallet beforehand. In button address had show my wallet balance.

**Comment by EnettyTech** [comment]
Is anyone here? I'm still having this issue with `@mysten/dapp-kit`. I tried using `@suiet/wallet-kit` and everything works fine, the auto connect state is triggered after page reload.

**Comment by Jordan-Mysten** [comment]
Are you able to make a minimal repro of this, our test cases seem to indicate this is working and I'm unable to reproduce this locally.

**Comment by EnettyTech** [comment]
After a period of rechecking, I have found the cause. I will close this issue.
