### ISSUE TITLE
Gas calculations overflow with a very large gas_budget

### ISSUE THREAD

**Issue by tnowacki** [MystenLabs/sui#1594]
Made a transaction with the gas budget set to u64::MAX. This causes an overflow in move-core/types/src/gas_schedule.rs:206:31

Not sure if we should do some verification (or already do and my tests are bypassing it) on transactions, or fix it on the Move side of things?

**Comment by lxfind** [comment]
Passing back to confirm

**Comment by stefan-mysten** [comment]
@tnowacki I assume we can close this. Please reopen if needed.
