### ISSUE TITLE
Compile first_package example failed by 1.16.2

### ISSUE THREAD

**Issue by lispking** [MystenLabs/sui#15970]
## Steps to Reproduce Issue

* brew tap mystenlabs/tap
* brew install mystenlabs/tap/sui
* write a new package: https://docs.sui.io/guides/developer/first-app/write-package
* code copy from: https://github.com/MystenLabs/sui/tree/main/examples/move/first_package
* sui move build
* `mainnet` build ok, but `devnet` and `testnet` build failed

## Expected Result

* build successfully

## Actual Result

Specify what the actual unexpected outcome was.

<img width="940" alt="image" src="https://github.com/MystenLabs/sui/assets/4446580/e6c205ba-7c74-48f7-9d81-a64b9d2a7ead">

## System Information

* OS: mac m1
* Compiler: sui 1.16.2-11511718

**Comment by lispking** [comment]
If I replace sui with manual installation with devnet or testnet, it will function normally. Why does sui need to be compiled from source code in so many different versions? What is the reason for this design?

**Comment by stefan-mysten** [comment]
@lispking Thanks for reporting this. The issue is that `brew` installs the most stable version, which corresponds to mainnet. Rarely, the `testnet` and `devnet` might introduce changes that break the CLI mainnet, which is what happened now because of the move verifier that was updated. We're actively working on ways to prevent this issue happening in the future. 

As of now, we're updating `brew` to use the `testnet` version of the CLI.

**Comment by jojoo-eth** [comment]
> @lispking Thanks for reporting this. The issue is that `brew` installs the most stable version, which corresponds to mainnet. Rarely, the `testnet` and `devnet` might introduce changes that break the CLI mainnet, which is what happened now because of the move verifier that was updated. We're actively working on ways to prevent this issue happening in the future.
> 
> As of now, we're updating `brew` to use the `testnet` version of the CLI.

Hello, is there any update regarding this error? What should I do now to avoid this error? Are there any command-line instructions or guidance? I've been stuck on this issue for two days.

**Comment by lispking** [comment]
> > @lispking Thanks for reporting this. The issue is that `brew` installs the most stable version, which corresponds to mainnet. Rarely, the `testnet` and `devnet` might introduce changes that break the CLI mainnet, which is what happened now because of the move verifier that was updated. We're actively working on ways to prevent this issue happening in the future.
> > As of now, we're updating `brew` to use the `testnet` version of the CLI.
> 
> Hello, is there any update regarding this error? What should I do now to avoid this error? Are there any command-line instructions or guidance? I've been stuck on this issue for two days.

The design of Sui is such that, at present, it is necessary to switch between different environments to compile code. 

For example, if you plan to deploy contracts to `devnet`, you will need to use the Sui from the `devnet` environment for compilation. 

Please note that contracts compiled in the `devnet` environment can only be deployed to `devnet`. 

If you need to deploy contracts to `testnet`, you will need to switch to the `testnet` environment and recompile using the Sui from there. In this way, the issue is resolved.

**Comment by lispking** [comment]
Personally, I find such a design to be quite cumbersome for the software itself. 

I would recommend consolidating the three environmental packages into one and introducing a command-line parameter, perhaps named `--network`, to address this issue. 

By handling the environmental complexities within the tool, we can spare all developers from having to navigate this clunky switching process.

**Comment by jojoo-eth** [comment]
> > Hello, is there any update regarding this error? What should I do now to avoid this error? Are there any command-line instructions or guidance? I've been stuck on this issue for two days.
> 
> @jojoo-eth
> 
> The design of Sui is such that, at present, it is necessary to switch between different environments to compile code.
> 
> For example, if you plan to deploy contracts to `devnet`, you will need to use the Sui from the `devnet` environment for compilation.
> 
> Please note that contracts compiled in the `devnet` environment can only be deployed to `devnet`.
> 
> If you need to deploy contracts to `testnet`, you will need to switch to the `testnet` environment and recompile using the Sui from there. In this way, the issue is resolved.

thanks, I resolved it following the guidance from this rider. https://github.com/MystenLabs/sui/issues/16063#issuecomment-1923303380

**Comment by lispking** [comment]
> Personally, I find such a design to be quite cumbersome for the software itself.
> 
> I would recommend consolidating the three environmental packages into one and introducing a command-line parameter, perhaps named `--network`, to address this issue.
> 
> By handling the environmental complexities within the tool, we can spare all developers from having to navigate this clunky switching process.

@jojoo-eth I prefer this design, or perhaps in the compilation process, the branch suitable for the `Move.toml` configuration file is found, which automatically switches if the network is `testnet`. 

cc @stefan-mysten

**Comment by stefan-mysten** [comment]
Thanks for the feedback @lispking. I added this on our internal discussion.
