### ISSUE TITLE
Feedback for “useSignPersonalMessage”

### ISSUE THREAD

**Issue by 0xGoenka** [MystenLabs/sui#16133]
Hi :)

How do we then check that the signature is valid ?

`const { mutate: signPersonalMessage,  } = useSignPersonalMessage();`

I can see in the deps that function exist, but idk how to access it in react

`./.vite/deps/@mysten_dapp-kit.js:  async verify(message, signature) {`

My goal is to be able to verify ownership of a wallet, to allow login with wallet, maybe this is not the proper way to do it anyway ?

Thank you for your time

**Comment by 0xGoenka** [comment]
I want to check that the user is really who he say he is (for context)

**Comment by williamrobertson13** [comment]
Hi @0xGoenka! The `useSignPersonalMessage` hook can be used to prompt a user to sign a message with their wallet, but you'll need to leverage the `verifyPersonalMessage` function from our TypeScript SDK to verify ownership of a particular wallet address. 

Check out our documentation at https://sdk.mystenlabs.com/typescript and https://sdk.mystenlabs.com/typescript/cryptography/keypairs#verifying-signatures-without-a-key-pair 🙂

**Comment by 0xGoenka** [comment]
Thank you boss !

**Comment by 0xGoenka** [comment]
It seems like it's not working with ZkLogin yet, do you have an ETA for this feature ?

Else what is the way to check ownership of an userAccount ?
