### ISSUE TITLE
Reduce image sizes in Panzerdogs x Sui and SoWork

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#1617]
I noticed while reviewing the site the images on this page take a long time to load:
https://docs.sui.io/explore/panzerdogs

Sure enough, they are quite oversized. This one is 4.2 MB!
https://docs.sui.io/suipanzerdogs3.png

We should scale each image down to only the size needed, in this case likely no more than 1600 pixels wide. That would cut the image size in more than half.

Bauer, let me know if you need guidance.

**Comment by Clay-Mysten** [comment]
This may also apply here:
https://docs.sui.io/explore/sowork

**Comment by bwann52** [comment]
@econmysten do you still have the original images? Sounds like we just need to do a quick replacement for this @Clay-Mysten right?

**Comment by Clay-Mysten** [comment]
Totally. You could even reduce the existing .png files with some admitted lossiness/fuzziness. Just download them, load them in Preview and scale to 1600 pixels wide. Even that is huge but better.

**Comment by econmysten** [comment]
have uploaded reduced files and requested review

**Comment by Clay-Mysten** [comment]
Bauer, it looks like the same image here:
https://docs.sui.io/explore/sowork

**Comment by randall-Mysten** [comment]
clearing the backlog. We will replace or remove images with subsequent updates of the topic.
