### ISSUE TITLE
private key with Secp256k1Keypair is not correct

### ISSUE THREAD

**Issue by ManutdGTA** [MystenLabs/sui#16189]
https://sdk.mystenlabs.com/typescript/cryptography/keypairs

the content `The Sui TypeScript SDK supports three signing schemes:`
The content in the second and third rows of the table is the same.

<img width="743" alt="image" src="https://github.com/MystenLabs/sui/assets/25993649/655411c0-9f9d-4722-88bf-313e9cad9d02">

Using an Ed25519Keypair, the private key can be normally outputted and correctly imported into a Sui wallet. 

```
const mnemonic = bip39.generateMnemonic();
const keypair = Ed25519Keypair.deriveKeypair(mnemonic); 
const privateKeyHex = Object.values(keypair.keypair.secretKey)
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
const address = keypair.getPublicKey().toSuiAddress();
```

When I imported the private key, the wallet displayed `Importing Hex encoded Private Key will soon be deprecated, please use Bech32 encoded private key that starts with "suiprivkey" instead` so I switched to a different method.

However, the private key generated with a Secp256k1Keypair cannot be correctly imported into the wallet.
`Invalid keypair schema undefined`
Is there anything incorrect in my usage?
```
const mnemonic = bip39.generateMnemonic();
const keypair = Secp256k1Keypair.deriveKeypair(mnemonic); 
const privateKeyHex = Object.values(keypair.keypair.secretKey)
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
const privateKeyBytes = Buffer.from(privateKeyHex, "hex");
const bech32EncodedPrivateKey = bech32.encode(
    "suiprivkey",
    bech32.toWords(privateKeyBytes)
  );
const address = keypair.getPublicKey().toSuiAddress(); 
```

**Comment by SuiSunbeam** [comment]
The second line is the curve used by Bitcoin, Ethereum, etc; Secp256k1Keypair, the third line is the R1 curve.
I missed it at first too!

Take a look at https://github.com/sui-foundation/sips/pull/15/files?short_path=4eb6eb2#diff-4eb6eb2f7f9823b5aaf48cb02ef562c5569f2073cbcfa1d504a311d707cb7de7
If you use the "Display the rich diff" button near the top on the right it's much nicer to read.
Judging from this comment https://github.com/sui-foundation/sips/pull/15#issuecomment-1886187909, this bit of devex will be smoothed out very soon!

I'm not affiliated with MystenLabs btw.

**Comment by hayes-mysten** [comment]
Your privateKeyBytes are missing the scheme flag, basically 1 byte that indicates which keypair scheme the private key is for.

Here's an quick example of decoding/re-encoding the private key: https://stackblitz.com/edit/typescript-dpxtew?file=index.ts

You can see the implementation for encoding a the privateKey to bech32 here: https://github.com/MystenLabs/sui/blob/874bdc3976709be9dbe4811b286d5ae7bb165d3d/sdk/typescript/src/cryptography/keypair.ts#L142-L149
