### ISSUE TITLE
Remove second slash from URLs in Source Code links

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#1625]
From the Dev Portal, scrolling to the bottom of any page, you can access the source file from the Source Code link. For some reason, these always contain double forward slashes, say from:
https://docs.sui.io/explore/tutorials

To:
https://github.com/MystenLabs/sui/blob/main/doc/src//explore/tutorials.md

Note the double slashes before explore. Not sure what's causing this. Since the links work, this isn't burning. Just an oddity we should fix eventually.

**Comment by Jibz1** [comment]
@Jibz1 got it

**Comment by Clay-Mysten** [comment]
Thanks so much, Godwin!

**Comment by gdanezis** [comment]
Assume this is done?

**Comment by Clay-Mysten** [comment]
Yes. Thanks, George and Godwin.
