### ISSUE TITLE
Document meaning of trust when dealing with objects

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#1627]
The Eng team had a hearty discussion on the meaning of trust when it comes to Sui objects. The results could provide clarity for our users. It sounds like the idea is a work in progress. I'm capturing key points made for easy reference later.

Xun's example:
https://mysten-labs.slack.com/archives/C02GD7J9HUM/p1651018746551519?thread_ts=1651016045.325879&cid=C02GD7J9HUM

Sam's summary:
https://mysten-labs.slack.com/archives/C02GD7J9HUM/p1651025334763089?thread_ts=1651016045.325879&cid=C02GD7J9HUM

**Comment by Clay-Mysten** [comment]
Also let's harvest Sam's podcast on the topic:
https://zeroknowledge.fm/228-2/

**Comment by randall-Mysten** [comment]
Closing as duplicate
