### ISSUE TITLE
compute ZkLogin Address is difference  by  toZkLoginPublicIdentifier

### ISSUE THREAD

**Issue by kecson** [MystenLabs/sui#16289]
## Steps to Reproduce Issue

compute ZkLogin Address is difference.

```
const addressSeed=BigInt('53110360415019126669828230553024112923320218327104649889517367679479126096');
const iss='https://accounts.google.com';
```
e.g.
1. `const address1 = computeZkLoginAddressFromSeed(addressSeed,iss);`
2. `const address2 = toZkLoginPublicIdentifier(addressSeed,iss).toSuiAddress();`
3. `expect(address1).toEqual(address2);`

## Expected Result

the `address1 / address2` should be the same. but it's not.

## Actual Result

but the `address1 / address2` is difference.

**Comment by SuiSunbeam** [comment]
Is there documentation beyond what I can see here?
[computeZkLoginAddressFromSeed](https://pub.dev/documentation/sui/latest/zklogin_address/computeZkLoginAddressFromSeed.html)
[toZkLoginPublicIdentifier](https://pub.dev/documentation/sui/latest/zklogin_publickey/toZkLoginPublicIdentifier.html)

I can see `computeZkLoginAddressFromSeed` has a `blake2b` hashing step that `toZkLoginPublicIdentifier` does not.
Am interested to hear why these are different.

I'm assuming you're talking about methods of @mofalabs/sui, btw?

**Comment by kecson** [comment]
> Is there documentation beyond what I can see here? [computeZkLoginAddressFromSeed](https://pub.dev/documentation/sui/latest/zklogin_address/computeZkLoginAddressFromSeed.html) [toZkLoginPublicIdentifier](https://pub.dev/documentation/sui/latest/zklogin_publickey/toZkLoginPublicIdentifier.html)
> 
> I can see `computeZkLoginAddressFromSeed` has a `blake2b` hashing step that `toZkLoginPublicIdentifier` does not. Am interested to hear why these are different.
> 
> I'm assuming you're talking about methods of @mofalabs/sui, btw?
> 
> (I'm not affiliated with Mysten Labs)


computeZkLoginAddressFromSeed:
https://github.com/MystenLabs/sui/blob/94817f787a6b6b2c33a9cdf2d94397a2d9022504/sdk/typescript/src/zklogin/address.ts#L11

toZkLoginPublicIdentifier:    
https://github.com/MystenLabs/sui/blob/94817f787a6b6b2c33a9cdf2d94397a2d9022504/sdk/typescript/src/zklogin/publickey.ts#L67

**Comment by SuiSunbeam** [comment]
https://sdk.mystenlabs.com/typescript/zklogin states "To compute the address for a given address seed and iss you can use computeZkLoginAddressFromSeed", whereas the latter function `toZkLoginPublicIdentifier ` doesn't appear to be mentioned in the docs (when I searched at https://sdk.mystenlabs.com/typescript or with google ["site:sdk.mystenlabs.com toZkLoginPublicIdentifier"](https://www.google.com/search?q=site%3Asdk.mystenlabs.com+toZkLoginPublicIdentifier)..

Perhaps the latter, that does not have the hashing step, will be marked as deprecated? Intuitively it seems there should be one canonical way to do this. In the meantime I'd use the documented one if it suits your needs, good catch I'd say.

**Comment by mskd12** [comment]
@Jordan-Mysten what is the purpose of the `toZkLoginPublicIdentifier` function? Seems like it is doing something very similar to `computeZkLoginAddressFromSeed` but with crucial differences: e.g., it [doesn't modify google's iss](https://github.com/MystenLabs/sui/blob/main/sdk/typescript/src/zklogin/address.ts#L13).

**Comment by kecson** [comment]
I thinks it's cause by addressSeed padding zero.

**Comment by joyqvq** [comment]
@SuiSunbeam @kecson 

you do not need to use toZkLoginPublicIdentifier - thats used to compute multisig that contains a zklogin key. 

regardless, Sui protocol allows for both address derivations if you are using zklogin without multisig. 

@mskd12 Sui protocol also does not allow the alternative iss, this is also fine
