### ISSUE TITLE
[doc, UX] split our binaries from the Sui crate by use case

### ISSUE THREAD

**Issue by huitseeker** [MystenLabs/sui#1639]
```
huitseeker@dapple.local➜~/tmp/sui(main)» ls sui/src/bin                                                                                                                                                                                             [20:04:15]
bench.rs       key_tool.rs    rest-server.rs rpc-server.rs  sui-move.rs    sui.rs         validator.rs   wallet.rs
huitseeker@dapple.local➜~/tmp/sui(main)» rg -A3 '\[\[bin\]\]'                                                                                                                                                                                       [20:04:19]
faucet/Cargo.toml
29:[[bin]]
30-name = "sui-faucet"
31-path = "src/main.rs"
```

I count 7 binary targets outside of the `faucet` crate. So :
- the command in the doc is correct, what comes after "this will put three binaries" isn't,
- where as we were mentioning three binaries being installed, we should now list and document up to 7,
- except some of those are probably not useful to most (e.g. validator, bench),
- so we should separate our binaries by use-case first, and then update the doc on how they work.

One easy first iteration would be to group the 3 binaries we were documenting already (sui, wallet, rest-server) in a separate crate, and the rest elsewhere.

_Originally posted by @huitseeker in https://github.com/MystenLabs/sui/pull/1611#discussion_r860335449_

**Comment by gdanezis** [comment]
Q: is there value in always shipping validator binary, (or at least full node) to reinforce the message this is a decentralized network?

**Comment by Clay-Mysten** [comment]
Doc issue here:
https://github.com/MystenLabs/sui/issues/1733
