### ISSUE TITLE
Wallet: connect to Sui Wallet from iframe

### ISSUE THREAD

**Issue by phips28** [MystenLabs/sui#16464]
We have a stake-widget for our clients hosted inside an iframe, but now we have the problem that we cannot connect to Sui Wallet within an iframe.

Is there a way to do this?

**Comment by Jordan-Mysten** [comment]
Hey @phips28, support for iFrames is intentionally not supported right now because of some issues with how we manage trust of origins. We've talked about potentially changing this at some point in the future, but it hasn't been planned yet.

**Comment by phips28** [comment]
We would really like to see this change, as we building a website staking widget where we aggregate all different chains and wallets.
