### ISSUE TITLE
[documentation] Add instructions about how to connect to DevNet

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#1651]

**Comment by Clay-Mysten** [comment]
How to connect the Wallet CLI to DevNet.

We also need to link to updated instructions for using the DevNet Explorer:
https://github.com/MystenLabs/sui/issues/1357
https://github.com/MystenLabs/sui/issues/1417

**Comment by Clay-Mysten** [comment]
Chris has excellent progress in:
http://go/cli-devnet

**Comment by Clay-Mysten** [comment]
And:
https://github.com/MystenLabs/sui-operations

**Comment by Clay-Mysten** [comment]
And more progress from Lu:
https://app.golinks.io/devnet-journeys

**Comment by Clay-Mysten** [comment]
Hi Chris,

I'm wondering on the status of:
[go/cli-devnet](http://go/cli-devnet)

Will it be ready to go live soon? Coordinating with others in:
https://github.com/MystenLabs/Prose/issues/23

And am still not sure what is expected then. Thanks!

**Comment by Clay-Mysten** [comment]
For posterity, noting:
draft - go/dogfood-devnet
live doc - https://docs.sui.io/explore/devnet

Great work, all!
