### ISSUE TITLE
Nested Table

### ISSUE THREAD

**Issue by RevanthGundala** [MystenLabs/sui#16581]
## Steps to Reproduce Issue
I am trying to creating a table whose key value is another table:
```
FileCollection {
                id: object::new(ctx),
                hashes: table::new<String, table::new<vector<u8>, bool>>(ctx)
            }
```

## Actual Result
I am receiving the following error:
```
 hashes: table::new<String, table::new<vector<u8>, bool>>(ctx)
   │                                            ^^^^^^^^^^ Invalid module access. Unbound struct 'new' in module 'sui::table'
   ```
   
  I have also tried to define the table earlier:
  ```
  let filehashes: Table<vector<u8>, bool> = table::new<vector<u8>, bool>(ctx);
        transfer::share_object(
            FileCollection {
                id: object::new(ctx),
                hashes: table::new<String, filehashes>(ctx)
            }
        )
 ```
        
But I am receiving the following error:
```
  hashes: table::new<String, filehashes>(ctx)
   │                                            ^^^^^^^^^^ Unbound type 'filehashes' in current scope
```
## System Information

* OS: MacOS
* Compiler: sui 1.18.1

**Comment by tnowacki** [comment]
`new` is a function with two type arguments, the key `K` of the table and the value `V` of the table. 

So `table::new(ctx)`, creates a new table for all types `K` and `V`. So if you had a table `Table<String, Table<vector<u8>, bool>>`, you could create a new table of that type with a single call, for example:
`let filehashes: Table<String, Table<vector<u8>, bool>> = table::new(ctx)`
