### ISSUE TITLE
Replace links to Swaggerhub API throughout Dev Portal

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#1672]
See:
https://github.com/MystenLabs/sui/pull/1654

Yet we link to:
https://app.swaggerhub.com/apis/MystenLabs/sui-api/

From:
https://docs.sui.io/learn#use-supporting-sites

The footers of:
https://docs.sui.io/

And likely a few other places in the bodies of pages.

This is supposed to be the replacement:
https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/MystenLabs/sui/189d61df846f7c3676c1215cc41fb970ee9e22b5/sui/open_rpc/spec/openrpc.json

Let's figure out the final home and make the switch.

**Comment by Clay-Mysten** [comment]
Patrick, please let me know when the new API link is permanent.

We should also discuss whether we should pose this as a direct replacement. Or are there deltas we should point out? Thanks!

**Comment by Clay-Mysten** [comment]
Thanks, Patrick. I'm starting this process. Two questions:
1. Should we be concerned anonymous editing is allowed on the playground site? Can others alter the view we offer?
2. Is that playground link reliable/persistent enough to link from our various locations for some perpetuity? Or will it change frequently?

**Comment by Clay-Mysten** [comment]
All done here. Thanks for the collaboration, Patrick!

**Comment by Clay-Mysten** [comment]
Noting I staged these changes, and they LGTM. For example, see the SDK link in the footer here:
https://devportal-qa.web.app/

**Comment by Clay-Mysten** [comment]
In the left nav of docs.sui.io, we still link from API V 0.1 to:
https://app.swaggerhub.com/apis/MystenLabs/sui-api/

Shouldn't it go to?
https://playground.open-rpc.org/?uiSchema%5BappBar%5D%5Bui:splitView%5D=false&schemaUrl=https://raw.githubusercontent.com/MystenLabs/sui/main/sui/open_rpc/spec/openrpc.json&uiSchema%5BappBar%5D%5Bui:input%5D=false

@Jibz1 , what do you think? (Caught by a link checker.)

**Comment by Jibz1** [comment]
@Clay-Mysten I will update it

**Comment by Jibz1** [comment]
@Clay-Mysten @patrickkuo with the rpc playground all the links go to a single [location]( https://playground.open-rpc.org/?uiSchema%5BappBar%5D%5Bui:splitView%5D=false&schemaUrl=https://raw.githubusercontent.com/MystenLabs/sui/main/sui/open_rpc/spec/openrpc.json&uiSchema%5BappBar%5D%5Bui:input%5D=false). Also on the docs, do I show the schemas or the methods.

**Comment by Jibz1** [comment]
@Clay-Mysten this is done.

**Comment by Clay-Mysten** [comment]
Hmm. From:
https://docs.sui.io/learn

In left nav, I go to:
https://app.swaggerhub.com/apis/MystenLabs/sui-api/0.1#/CallRequest

Is that correct?

**Comment by patrickkuo** [comment]
just noticed this.... the `sui` prefix in the JSON-RPC method name should be lowercase 
<img width="379" alt="image" src="https://user-images.githubusercontent.com/1888654/168898674-8b76a00a-5af9-4fa1-81d7-4bdf9ef48336.png">

**Comment by Jibz1** [comment]
@patrickkuo Ok. I will update it

**Comment by Jibz1** [comment]
@patrickkuo this is done.

**Comment by Clay-Mysten** [comment]
Thanks, Godwin! I assume the links will automatically go to the latest version this time. The swaggerhub links had an older version hardcoded.
