### ISSUE TITLE
[Suggestion] Support combining filters in queryEvents api

### ISSUE THREAD

**Issue by ea-dungn** [MystenLabs/sui#16872]
Hi all, as I was using the `suix_queryEvents` api provided by the json-rpc fullnodes, I got the error that the combinatorial filters such as `All`, `Any`, `And`, `Or` does not work when querying events, which is kinda odd because it should be quite straightforward to be able to do so.

After inspecting the code I saw that we are storing multiple indexes:

```rust
// crates/sui-storage/src/indexes.rs

event_order: DBMap<EventId, EventIndex>,
event_by_move_module: DBMap<(ModuleId, EventId), EventIndex>,
event_by_move_event: DBMap<(StructTag, EventId), EventIndex>,
event_by_sender: DBMap<(SuiAddress, EventId), EventIndex>,
event_by_time: DBMap<(u64, EventId), EventIndex>,
```

I wonder if we can implement the combinatorial filters by inverting the index as a kind of intermediate representation and then combine them?

For example if we had filtered out the events emitted in a time range:

```rust
let time_iter = event_by_time
    .unbounded_iter()
    .skip_to(&(start_time, (tx_seq, event_seq)))?
    .take_while(|((m, _), _)| m <= &end_time)
```

and the same thing with events emitted by a module:

```rust
let module_iter = event_by_move_module
    .unbounded_iter()
    .skip_to(&(module, (tx_seq, event_seq)))?
    .take_while(|((m, _), _)| m == key)
```

We can then invert the index and then merge the two iterators, maybe sort by timestamp afterwards.

```rust
time_iter.map(
    |((m, event_id), event_index)|
    (event_id, event_index)
).merge(
    module_iter.map(
        |((m, event_id), event_index)|
        (event_id, event_index)
    ))
```

As I am not very familiar with the codebase, I would really appreciate professionals like you to verify this idea. Thank you all for reading.

**Comment by gegaowp** [comment]
@ea-dungn sorry for the confusion, but All, Any, And, Or were never production ready, it's straight-forward to compose the query but it's really challenging to ensure the query perf, so we have decided to NOT support it on the graphql (also known as RPC 2.0)

we recommend not using All, Any, And, Or in any production codes and I am adding annotations to them too to make it more explicit on the existing JSON RPC (RPC 1.0)
