### ISSUE TITLE
An error occurred running the indexer

### ISSUE THREAD

**Issue by COLUD4** [MystenLabs/sui#16898]
I downloaded 3.6 terabytes of archive data for node startup, at which point the indexer could also start and write data from 0-15 years to the database.
version
sui-node 1.21.1-a67a73bcfab3

But the indexer suddenly the error: the 2024-03-27 T07: departed. 932668 z WARN sui_indexer: : framework: : fetcher: error downloading checkpoints: request failed with status 500 Internal Server Error

The reason I found is that the nodes were pruned:
The 2024-03-27 T06:20:58. 536926 z INFO sui_core: : authority: : authority_store_pruner: scheduling pruning for: 1582516
The 2024-03-27 T06:20:58. 547284 z INFO sui_core: : authority: : authority_store_pruner: scheduling pruning for: 1582517
The 2024-03-27 T06:20:58. 556668 z INFO sui_core: : authority: : authority_store_pruner: scheduling pruning for: 1582518
The 2024-03-27 T06:20:58. 566258 z INFO sui_core: : authority: : authority_store_pruner: scheduling pruning for: 1582519
The 2024-03-27 T06:20:58. 576455 z INFO sui_core: : authority: : authority_store_pruner: scheduling pruning for: 1582520
The 2024-03-27 T06:20:58. 636129 z INFO sui_core: : authority: : authority_store_pruner: scheduling pruning for: 1582521

This is my configuration file, I did not configure authority-store-pruning-config, but why is the node still pruning, and how should I set up the configuration file to run indexer perfectly:
value to the location you want Sui to store its database
db-path: "./"

network-address: "/dns/localhost/tcp/8080/http"
metrics-address: "0.0.0.0:9184"
json-rpc-address: "0.0.0.0:9000"
websocket-address: "0.0.0.0:9001"
enable-event-processing: true
enable-index-processing: true
enable-experimental-rest-api: true

genesis:
# Update this to the location of where the genesis file is stored
genesis-file-location: "./genesis.blob"
p2p-config:
seed-peers:

address: /dns/icn-00.mainnet.sui.io/udp/8084
peer-id: 303f1f35afc9a6f82f8d21724f44e1245f4d8eca0806713a07c525dadda95a66
address: /dns/icn-01.mainnet.sui.io/udp/8084
peer-id: cb7ce193cf7a41e9cc2f99e65dd1487b6314a57c74be42cc8c9225b203301812

**Comment by johnjmartin** [comment]
> This is my configuration file, I did not configure authority-store-pruning-config, but why is the node still pruning, and how should I set up the configuration file to run indexer perfectly:

If you don't set `authority-store-pruning-config` it will fall back to whatever the defaults are, which do apply pruning. 

take a look at https://docs.sui.io/guides/operator/data-management#pruning-policy-examples for more information
