### ISSUE TITLE
sui move build with v1.21.1 on windows found error

### ISSUE THREAD

**Issue by summertoo** [MystenLabs/sui#16953]
sui move build

FETCHING GIT DEPENDENCY https://github.com/MystenLabs/sui.git
INCLUDING DEPENDENCY Sui
INCLUDING DEPENDENCY MoveStdlib
BUILDING Tmove
Failed to build Move modules: 系统找不到指定的路径。 (os error 3).

It doesn’t work even after recompiling and installing it.

**Comment by stefan-mysten** [comment]
Thanks @summertoo 
There are a few workarounds in #16906 that you can try. Most likely, you'll have to use an older version of the CLI (1.19 seems to be fine), as we're currently investigating the issue.

**Comment by summertoo** [comment]
> Thanks @summertoo There are a few workarounds in #16906 that you can try. Most likely, you'll have to use an older version of the CLI (1.19 seems to be fine), as we're currently investigating the issue.

thanks !

**Comment by tnowacki** [comment]
https://github.com/MystenLabs/sui/issues/16906#issuecomment-2027793618
PowerShell might be a workaround

**Comment by summertoo** [comment]
@tnowacki 

thanks ! It seems that using Powershell is working properly
![usepowershell](https://github.com/MystenLabs/sui/assets/6514153/6a8778e5-f0e1-4c22-a9d4-abbac458adc6)
