### ISSUE TITLE
Provide a timestamp for each transaction for the explorer

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1696]
We will eventually need to display timestamp on explorer, and it needs to support transactions that haven't made into checkpoints yet. 

Initial proposa:
```
I think the best way to do this is to add timestamp to authority signatures (at the time of signing), and then when there is a certificate, make the time median time of all authority signatures.

https://github.com/MystenLabs/sui/pull/1686 introduced AuthorityQuorumSignInfo that would make this much easier to do.
Next we just need to add a timestamp field to both authority sign info.

What do people think about this? @gdanezis @huitseeker @kchalkias 
```

After some discussions, we think that adding a timestamp to the signature may not be the best idea. One reason is that at checkpoint, we will actually strip the signatures from all tx structures, which means the timestamp will be stripped.
We may have to add some local timestamp in a fullnode for each transaction when it first receives it to support explorer.

**Comment by kchalkias** [comment]
There are many ways to introduce timestamps to our protocol, all with their pros and cons.
a) user sets a timestamp or range as a tx input (or better sign it as metadata), and if validators receive it inside some threshold they also sign. Obviously this provides very relaxed guarantees.

b) validators add it to their fastX signatures (thus certified tx carries many timestamps, as each validator might pick a slightly different one). Cons: as quorum signatures are malleable and a cert can be of any combination of authsigs, again you cannot guarantee a single accurate  timestamp, thus we should play with median etc.

c) we add a single timestamp to each consensus block; thus, indirectly applied to all txs in the block. Obviously this timestamp introduces some latency compared to fastX certificates. This is what most BFT blockchains do.

**Comment by lxfind** [comment]
What timestamp do you think we should display in an explorer for each transaction?

**Comment by kchalkias** [comment]
Some explorers also add "time received" from their backing full node. That's the easiest atm for UI purposes.

**Comment by lxfind** [comment]
> There is another issue with this solution: now each validator signs a different message and if we go with BLS aggregation, there is extra cost to aggregated-sig verification.

I was thinking that we shouldn't sign the timestamp, as it comes with the signature which is malleable.

**Comment by gdanezis** [comment]
The issue with introducing a timestamp, particularly within the signature is that inevitably people will interpret it as having high integrity. I do wonder if for this use case a local timestamp, at the time of reception of the tx or checkpoint is not what we need. 

The bigger issue of a timestamp we can use within move is much more tricky.

**Comment by lxfind** [comment]
> The issue with introducing a timestamp, particularly within the signature is that inevitably people will interpret it as having high integrity.

Would it work if we name the field with something very explicit, like median_sign_time?

**Comment by huitseeker** [comment]
> The issue with introducing a timestamp, particularly within the signature is that inevitably people will interpret it as having high integrity

I'm not so sure. 
The drift tolerance for the block timestamp in Ethereum is [900 seconds](https://github.com/ethereum/wiki/blob/c02254611f218f43cbb07517ca8e5d00fd6d6d75/Block-Protocol-2.0.md#block-validation-algorithm), and in practice, discussions on the subject show people correctly interpret this value as malleable. [Other](https://docs.solana.com/implemented-proposals/validator-timestamp-oracle) [docs](https://docs.onflow.org/cadence/measuring-time/) clearly label their time as imprecise, and so far I haven't heard of this being a problem.

**Comment by sblackshear** [comment]
Should this be merged with https://github.com/MystenLabs/sui/issues/226?

**Comment by lxfind** [comment]
Let me rename this issue. I think they are different. This issue is less about on-chain time, but more about what time an explorer can use for display.

**Comment by lxfind** [comment]
Current approach: add timestamp on fullnode, the moment we see a tx from validator.

**Comment by Andrew47** [comment]
@longbowlu --> feel free to place the text for the tooltip in this thread and I'll create a PR implementing it.
