### ISSUE TITLE
Error [E01003]  struct NFT {   Invalid struct declaration. Internal struct declarations are not yet supported

### ISSUE THREAD

**Issue by UXSciGuy** [MystenLabs/sui#17079]
When running "sui move build" with the following code in my .move file:

```
/// Module: test_nft
module test_nft::test_nft {
    use sui::url::{Self, Url};
    use std::string;
    use sui::object::{Self, ID, UID};
    use sui::event;
    use sui::transfer;
    use sui::tx_context::{Self, TxContext};

    /// An example NFT that can be minted by anybody
    struct DevNetNFT has key, store {
        id: UID,
        /// Name for the token
        name: string::String,
        /// Description of the token
        description: string::String,
        /// URL for the token
        url: Url,
    }
}
```
 I get the following error message:

error[E01003]: invalid modifier
  ┌─ sources/simba_nft.move:4:5
  │
4 │     struct NFT {
  │     ^^^^^^ Invalid struct declaration. Internal struct declarations are not yet supported

I know that internal struct declarations are allowed. What is the issue? I've setup the sui environment per the documentation. Can some one help?

**Comment by mshakeg** [comment]
Your issue might be related to https://github.com/MystenLabs/sui/issues/17087

**Comment by gordonkoehn** [comment]
I am getting the same issue/warning when running the VS Code Studio language support plugin.

**Comment by stefan-mysten** [comment]
@UXSciGuy is this issue still ongoing?

**Comment by patchthecode** [comment]
well?

**Comment by patchthecode** [comment]
@stefan-mysten so... do i update? was it merged?

**Comment by stefan-mysten** [comment]
> well? im confused on what to to do. I followed documentation but got this error?

Sorry, which documentation have you followed? Could I get a link to what docs you've been following to try to replicate locally?

**Comment by patchthecode** [comment]
@stefan-mysten apologies.

It was the ai helper within the sui documentation site. Not the doc itself. So i guess the ai hallucinated.
Therefore, Ignore this. And thanks for the quick response.
