### ISSUE TITLE
example move code build failed

### ISSUE THREAD

**Issue by leihuhu** [MystenLabs/sui#17087]
## Steps to Reproduce Issue

Follow the doc: https://docs.sui.io/guides/developer/first-app/write-package
1. use the command: `sui move new my_first_package`
2. copy the code to `my_module.move` file
3. build my package with `sui move build`

## Expected Result
build success.

## Actual Result
```
error[E01003]: invalid modifier
  ┌─ sources/my_module.move:9:5
  │
9 │     struct Sword has key, store {
  │     ^^^^^^ Invalid struct declaration. Internal struct declarations are not yet supported
  │
  = Visibility annotations are required on struct declarations from the Move 2024 edition onwards.

error[E01003]: invalid modifier
   ┌─ sources/my_module.move:15:5
   │
15 │     struct Forge has key, store {
   │     ^^^^^^ Invalid struct declaration. Internal struct declarations are not yet supported
   │
   = Visibility annotations are required on struct declarations from the Move 2024 edition onwards.

Failed to build Move modules: Compilation error.
```

The [pachage] in Move.toml is:
```
[package]
name = "my_first_package"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]
```

**The edition should be annotated!!!**
## System Information

* OS: Linux version 5.15.0-101-generic (buildd@lcy02-amd64-032) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38)
* Compiler: sui 1.22.0-036299745

**Comment by summertoo** [comment]
change edition = "2024.beta"  to #edition = "2024.beta"  or add public struct
