### ISSUE TITLE
graphql how to get dynamic fields data

### ISSUE THREAD

**Issue by enoloo** [MystenLabs/sui#17081]
I have a table like : Table<address, Table<String, address>>

by graphql, how to get the inner table data?

thx.

**Comment by stefan-mysten** [comment]
@enoloo it's not very clear what you mean by that data structure? What were the queries you tried for fetching the dynamic field objects and did not work?

**Comment by wlmyng** [comment]
Hey @enoloo , do you have some example ids I can use? You may be able to reach it by `owner { dynamicFields { value { asMoveObject { dynamicFields { value` - note, pseudo-code - but would need to verify
