### ISSUE TITLE
[GraphQL] Is there SuiAddressArray?

### ISSUE THREAD

**Issue by enoloo** [MystenLabs/sui#17096]
```
const objects = gql(`
  query objects($id1:SuiAddress!, $id2:SuiAddress, $id3:SuiAddress, $id4:SuiAddress, $id5:SuiAddress, 
    $id6:SuiAddress, $id7:SuiAddress, $id8:SuiAddress, $id9:SuiAddress, $id10:SuiAddress, $id11:SuiAddress, $id12:SuiAddress) {
    objects(filter:{ objectIds:[
      $id1, $id2, $id3, $id4, $id5, $id6, $id7, $id8, $id9, $id10, $id11, $id12
    ]}
  ) {
    nodes {
...
```

Is there schema SuiAddressArray for using?

**Comment by stefan-mysten** [comment]
In our GraphQL you can do:
```objects(filter: {objectIds: ["address1", "address2"]}) ```
so I'd assume this would work in your example by using the correct syntax.

**Comment by stefan-mysten** [comment]
> Is there schema SuiAddressArray for using?

Your question is not very clear. Could you please rephrase or explain in more details what you want to achieve or what is not working with your example?

**Comment by amnn** [comment]
`[...]` is used to define array types:

```graphql
query ($ids: [SuiAddress!]!) {
  objects(filter: {objectIds: $ids}) {
    nodes {
      # ...
    }
  }
}
```
