### ISSUE TITLE
Add an Authority API that can query the cert+effect for a list of transaction digests

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1712]
For a fullnode following an authority, once it gets a list of tx digest through the follower API, it will want to know the exact certified transaction as well as the signed effects from the authority for each transaction. To make it more efficient (avoid querying tx by tx), we should provide an API that can query (cert+effect) tuple for a list of tx.
@gdanezis @laura-makdah What do you think?
@bmwill

**Comment by gdanezis** [comment]
One option is to have a batch request indeed. Another option is to have a streaming API to do all requests to authority with a set of streaming responses back. This is what we used to have. 

The batch approach is a little more compact, but I do wonder if we need to special case or support a generic batch request containing a number of requests internally, and returning a vec of their responses.

**Comment by laura-makdah** [comment]
I agree having a way to batch transactions or anything else for that matter would be handy.
