### ISSUE TITLE
BCS serialize error

### ISSUE THREAD

**Issue by enoloo** [MystenLabs/sui#17127]
I want to transfer vector<sale> to move contract：
```
    let bcs = new BCS(getSuiMoveConfig());
    bcs.registerStructType('sale', {
        item: BCS.STRING,
        price: BCS.U64,
        stock: BCS.U64,
    })

txb.movecall({
arguments: [txb.pure(bcs.ser('vector<sale>',  sales) ... ] // sales is {item, price, stock}[] type
})
```
Error: Dry run failed, could not automatically determine a budget: CommandArgumentError { arg_idx: 1, kind: InvalidUsageOfPureArg } in command 1

How to transfer vector\<struct\> to move contract? and in move, how to receive  the vector\<struct\>? Thks.

**Comment by hayes-mysten** [comment]
Pure arguments in move calls can't contain structs.  Object arguments need to either be passed as objects (eg via `txb.object(id)`) or as results of other move calls (eg. `const obj = txb.moveCall({ ... });  txb.moveCall({..., arguments: [obj] })`)
