### ISSUE TITLE
Use a separate table to store object metadata

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1714]
In `handle_transaction` step, we currently read all objects needed by the transaction. This can be expensive and unnecessary because we don't need the content of the objects at all until we execute them. This gets even tricky with shared objects: shared objects may be getting updated all the time, the shared object you read during `handle_transaction` phase may become immediately out-of-dated right after you read it. This also means that trying to read the objects will compete with shared object writes pretty much all the time.
We should create a separate table to store object metadata, things that are sufficient for input lock checks as long as we don't need execution. This will also allow us to think about gateways differently: the gateway can then advance its local state purely using the effects without tracking the object content. This will allow the gateway to be able to do transaction input checking without the objects or being able to do local execution.

Bonus: in the objects table, we could then consider only storing the object data without the metadata. This will then allow us to not have to mutate the objects table for transfers or simple owner/version changes that don't actually touch the object content. This can help significantly reduce gas cost for most operations.

Thoughts? @gdanezis @velvia @sblackshear

**Comment by velvia** [comment]
@lxfind I do like this idea.  That is being able to read the metadata quickly and modify it.  Really in a traditional table these would be separate fields which could be updated and read separately.

Note that this has a slight interaction with https://github.com/MystenLabs/sui/issues/1318

When the object table is changed to use (ObjID, version) keys, then you'll be able to read shared objects at some stable version and it won't change under you.  (well, until it's deleted).   Also having this separate table means both tables should have (ObjID, version) keys.

Should hold off on this change until the lock service one is merged.  If the lock service relies on this table (right now it doesn't rely on the objects table at all), then maybe it should be managed by the lock service.  I'm not sure that's necessary though.

**Comment by gdanezis** [comment]
The case of executing shared objects under high-concurrency is also overlapping with https://github.com/MystenLabs/sui/issues/1708 and yet another reason why shared object execution should probably be optimised for the fact that shared object transactions need to be executed in a known order, rather than trying to execute them all in parallel and filing for most of them most of the time.

**Comment by oxade** [comment]
What all constitutes metadata?

**Comment by lxfind** [comment]
I am thinking of the following:
ObjectRef, Owner and MoveType (if it's a Move object)

**Comment by gdanezis** [comment]
> ObjectRef, Owner and MoveType (if it's a Move object)

Maybe a flag on whether it is immutable, owned, or shared?

**Comment by lxfind** [comment]
> Maybe a flag on whether it is immutable, owned, or shared?

The `Owner` enum contains such information already.
