### ISSUE TITLE
Use type safety instead of a boolean flag when verifying transactions

### ISSUE THREAD

**Issue by bmwill** [MystenLabs/sui#1716]
see here for a code pointer: https://github.com/MystenLabs/sui/pull/1687/files/d4aa5493df34ab7a318eb03c2f166043a0084985#diff-9dc81331cd21e900d784f0b9cef27f5a9afdc7a6f577a622d73c43124f54e237R164

**Comment by gdanezis** [comment]
We would need to separate cryptographic checks (always true) from checks related to the composition of committee or validity of key at a particular time (change across epochs).
