### ISSUE TITLE
network: investigate sending back rich errors

### ISSUE THREAD

**Issue by bmwill** [MystenLabs/sui#1717]
The old networking stack would send back rich errors by serializing the actual SuiError in the response. During the migration to grpc this was eliminated, although it can be added back by serializing this error information into the `details` field of a grpc status.

**Comment by gdanezis** [comment]
How comes tests did not break as a result of this? I thought some of the gateway logic depends on the type of error returned to function correctly.

**Comment by bmwill** [comment]
🤷🏼 I guess there weren't tests that checked for this

**Comment by stefan-mysten** [comment]
@bmwill I assume this is outdated by now, so will close it; feel free to re-open if it's still needed.
