### ISSUE TITLE
The pruning node failed to obtain the specified address balance

### ISSUE THREAD

**Issue by COLUD4** [MystenLabs/sui#17198]
### expect
Hello! I am eager to get help from the project side and hope to use pruning nodes to obtain correct information.
### System information
Ubuntu 22.04.3
sui-node version: sui-node 1.22.0-2d07a1fd9f87

### Overview of the problem
I deployed two mainnet nodes, a full node and a pruned node. Node synchronization is completed, but the balance of the specified address obtained by the pruning node through the suix_getBalance method is incorrect.

**Get balance through pruning node**
curl --header 'Content-Type: application/json' --data '{ "params": [ "0xac5bceec1b789ff840d7d4e6ce4ce61c90d190a7f8c4f4ddf0bff6ee2413c33c", "0x2::sui::SUI" ], "jsonrpc": "2.0", "id": 1, "method": "suix_getBalance" }' --location 'http://127.0.0.1:9000' | jq
{
  "jsonrpc": "2.0",
  "result": {
    "coinType": "0x2::sui::SUI",
    "coinObjectCount": 0,
    "totalBalance": "0",
    "lockedBalance": {}
  },
  "id": 1
}
**Get balance through full node**
curl --header 'Content-Type: application/json' --data '{ "params": [ "0xac5bceec1b789ff840d7d4e6ce4ce61c90d190a7f8c4f4ddf0bff6ee2413c33c", "0x2::sui::SUI" ], "jsonrpc": "2.0", "id": 1, "method": "suix_getBalance" }' --location 'http://127.0.0.1:9000' | jq
{
  "jsonrpc": "2.0",
  "result": {
    "coinType": "0x2::sui::SUI",
    "coinObjectCount": 3,
    "totalBalance": "123782308033734945",
    "lockedBalance": {}
  },
  "id": 1
}
**Get balance through external node**
curl --header 'Content-Type: application/json' --data '{ "params": [ "0xac5bceec1b789ff840d7d4e6ce4ce61c90d190a7f8c4f4ddf0bff6ee2413c33c", "0x2::sui::SUI" ], "jsonrpc": "2.0", "id": 1, "method": "suix_getBalance" }' --location 'https://rpc.mainnet.sui.io' | jq
{
  "jsonrpc": "2.0",
  "result": {
    "coinType": "0x2::sui::SUI",
    "coinObjectCount": 3,
    "totalBalance": "123782308033734945",
    "lockedBalance": {}
  },
  "id": 1
}

### Reproduction Steps
**Start command** 
./sui-node --config-path=./conf/config.yaml
**Snapshot** 
./sui-tool download-formal-snapshot --epoch 367 --genesis ./genesis.blob --network mainnet --path ./ --num-parallel-downloads 100 --no-sign-request
**sui-node version** 
sui-node 1.22.0-2d07a1fd9f87
**genesis-file**
https://github.com/MystenLabs/sui-genesis/raw/main/mainnet/genesis.blob
**config.yaml** 
db-path: "./node/"
network-address: "/dns/localhost/tcp/8080/http"
metrics-address: "0.0.0.0:9184"
json-rpc-address: "0.0.0.0:9000"
websocket-address: "0.0.0.0:9001"

enable-event-processing: true
enable-index-processing: true
enable-experimental-rest-api: true

genesis:
  genesis-file-location: "./conf/genesis.blob"
authority-store-pruning-config:
  num-latest-epoch-dbs-to-retain: 3
  epoch-db-pruning-period-secs: 3600
  max-checkpoints-in-batch: 10
  max-transactions-in-batch: 1000

  num-epochs-to-retain: 10
  num-epochs-to-retain-for-checkpoints: 10
  periodic-compaction-threshold-days: 1

p2p-config:
  seed-peers:
    - address: /dns/mel-00.mainnet.sui.io/udp/8084
      peer-id: d32b55bdf1737ec415df8c88b3bf91e194b59ee3127e3f38ea46fd88ba2e7849
    - address: /dns/ewr-00.mainnet.sui.io/udp/8084
      peer-id: c7bf6cb93ca8fdda655c47ebb85ace28e6931464564332bf63e27e90199c50ee
    - address: /dns/ewr-01.mainnet.sui.io/udp/8084
      peer-id: 3227f8a05f0faa1a197c075d31135a366a1c6f3d4872cb8af66c14dea3e0eb66
    - address: /dns/lhr-00.mainnet.sui.io/udp/8084
      peer-id: c619a5e0f8f36eac45118c1f8bda28f0f508e2839042781f1d4a9818043f732c
    - address: /dns/sui-mainnet-ssfn-1.nodeinfra.com/udp/8084
      peer-id: 0c52ca8d2b9f51be4a50eb44ace863c05aadc940a7bd15d4d3f498deb81d7fc6
    - address: /dns/sui-mainnet-ssfn-2.nodeinfra.com/udp/8084
      peer-id: 1dbc28c105aa7eb9d1d3ac07ae663ea638d91f2b99c076a52bbded296bd3ed5c
    - address: /dns/sui-mainnet-ssfn-ashburn-na.overclock.run/udp/8084
      peer-id: 5ff8461ab527a8f241767b268c7aaf24d0312c7b923913dd3c11ee67ef181e45
    - address: /dns/sui-mainnet-ssfn-dallas-na.overclock.run/udp/8084
      peer-id: e1a4f40d66f1c89559a195352ba9ff84aec28abab1d3aa1c491901a252acefa6
    - address: /dns/ssn01.mainnet.sui.rpcpool.com/udp/8084
      peer-id: fadb7ccb0b7fc99223419176e707f5122fef4ea686eb8e80d1778588bf5a0bcd
    - address: /dns/ssn02.mainnet.sui.rpcpool.com/udp/8084
      peer-id: 13783584a90025b87d4604f1991252221e5fd88cab40001642f4b00111ae9b7e

**Comment by johnjmartin** [comment]
This is probably because you restored from a **formal snapshot** [docs](https://docs.sui.io/guides/operator/snapshots#formal-snapshots). formal snapshots do not contain the indexes needed to query balance changes. Try using a db snapshot for starting your node, those contain indexes
