### ISSUE TITLE
response failed error

### ISSUE THREAD

**Issue by TheFox** [MystenLabs/sui#17379]
I get a lot of those errors when I want to start a node:

```WARN request{route=/sui.StateSync/GetCheckpointSummary remote_peer_id=13783584 direction=outbound}: anemo_tower::trace::on_failure: response failed error=Error: closed latency=0 ms```

What does this mean? What can I do to resolve this?

**Comment by aschran** [comment]
It means your node was trying to download checkpoint information from a remote node and the connection was closed before the request completed. This is not in itself particularly a cause for concern. Do you have any functional issues aside from log messages?
