### ISSUE TITLE
zklogin sdk signTransactionBlock returns 404 

### ISSUE THREAD

**Issue by v1xingyue** [MystenLabs/sui#17392]
## Steps to Reproduce Issue

When I use zklogin on my app. signTransactionBlock works as expected. 
But when use signTransactionBlock ,it jumps to  

```
https://zksend.com/dapp/sign-personal-message?id=59399efe-0527-422e-b5e5-44f9fc34d82a&origin=http%3A%2F%2Flocalhost%3A5173&name=my-zk-send#bytes=C0hlbGxvIFdvcmxk&address=0x88f8e6538343a3b9c4530f6ce418beaa6a4f99d8f423fc1394ed6911d7bed623
```

and this page tells 404.

## Actual Result

Sign personal message result returns 404.

**Comment by pichtranst123** [comment]
same things but i got redirect to `https://zksend.com/dapp...` and see white page, when i re-load and get `404 not found`
