### ISSUE TITLE
telemetry breaks `sui move test` (also it would be nice if it were feature flagged)

### ISSUE THREAD

**Issue by skaunov** [MystenLabs/sui#17426]
## Steps to Reproduce Issue

Fill this in with the concrete steps needed to reproduce the bug. When providing code in the reproduction steps, use the smallest snippet of code that demonstrates the issue, removing any extraneous details.

e.g.
1. Follow <https://docs.sui.io/guides/developer/first-app/build-test#sui-specific-testing>.
2. Run `sui move test` in KVM.

## Expected Result

As per the guide describes it.

## Actual Result

```console
sui@pop-os:~/my_first_package$ sui move test
INCLUDING DEPENDENCY Sui
INCLUDING DEPENDENCY MoveStdlib
BUILDING my_first_package
thread 'main' panicked at external-crates/move/crates/move-compiler/src/sui_mode/id_leak.rs:158:56:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-04-30T21:36:00.039232Z ERROR telemetry_subscribers: panicked at external-crates/move/crates/move-compiler/src/sui_mode/id_leak.rs:158:56:
called `Option::unwrap()` on a `None` value panic.file="external-crates/move/crates/move-compiler/src/sui_mode/id_leak.rs" panic.line=158 panic.column=56
Aborted (core dumped)
```

## System Information

* OS: Pop OS (current version, upgraded)
* Compiler: 
```
sui@pop-os:~/my_first_package$ sui -V
sui 1.24.0-92ba3bc7a
```
Couple of previous versions also errored on "telemetry".

**Comment by amnn** [comment]
Thanks for the report @skaunov -- the issue here is not with telemetry, it's a panic in the compiler (and telemetry is logging that panic):

```
called `Option::unwrap()` on a `None` value panic.file="external-crates/move/crates/move-compiler/src/sui_mode/id_leak.rs" panic.line=158 panic.column=56
```

The panicking line is here:

https://github.com/MystenLabs/sui/blob/92ba3bc7a6cf446edb742b53ea539369e6d11ae3/external-crates/move/crates/move-compiler/src/sui_mode/id_leak.rs#L158

@skaunov, if you have it to hand, can you share the Move code that you sent to the compiler to get it to panic?

**Comment by skaunov** [comment]
Had to remove that instance. =( But the code was taken from the guide.

In a week I'll try to reinstate the thing, and get back here then.
