### ISSUE TITLE
Sui doc content issue or request - Link broken in README.md 

### ISSUE THREAD

**Issue by gordonkoehn** [MystenLabs/sui#17436]
A link in the _README.md_ leads to a _404 - page not found_

In the very last sentence of the [README.md](https://github.com/MystenLabs/sui/blob/main/README.md) section _Sui Overview_ the link to **peer-reviewed works** appears broken: 

> Sui is backed by a number of state-of-the-art [peer-reviewed works](https://github.com/MystenLabs/sui/blob/main/docs/content/references/research-papers.mdx) and years of open source development.

**Comment by amnn** [comment]
Thanks for flagging! I've updated the link in the attached PR! You can find the information about research papers here: https://github.com/MystenLabs/sui/blob/main/docs/content/concepts/research-papers.mdx

Or the same content on the docs site (nicer formatting) here: https://docs.sui.io/concepts/research-papers#bullshark

**Comment by gordonkoehn** [comment]
Fantastic, thanks for the links!
