### ISSUE TITLE
[graphql] How to get multi-owner data from one graphql query? 

### ISSUE THREAD

**Issue by enoloo** [MystenLabs/sui#17435]
```
query owner($ObjectID:SuiAddress!) 
```

I want a query like this:
```
query owner([$ObjectID:SuiAddress!]!) 
```

How to imp it? Thks.

**Comment by amnn** [comment]
Hi @enoloo, is the question about how to get owner information for multiple objects in one GraphQL query? If so, here's how:

```graphql
query owner($ids: [SuiAddress!]!, $after: String) {
  objects(filter: { objectIds: $ids }, after: $after) {
    pageInfo {
      hasNextPage
      endCursor
    }

    nodes {
      owner {
        __typename
      
        ... on Shared {
          initialSharedVersion
        }
      
        ... on AddressOwner {
          owner { address }
        }
      
        ... on Parent {
          parent { address }
        }
      }
    }
  }
}
```

Note that this query is [paginated](https://docs.sui.io/concepts/graphql-rpc#pagination), so I have also added a parameter to take a cursor for pagination, and added fields to check for a further page and return the end cursor as well.

**Comment by enoloo** [comment]
> Hi @enoloo, is the question about how to get owner information for multiple objects in one GraphQL query? If so, here's how:
> 
> ```graphql
> query owner($ids: [SuiAddress!]!, $after: String) {
>   objects(filter: { objectIds: $ids }, after: $after) {
>     pageInfo {
>       hasNextPage
>       endCursor
>     }
> 
>     nodes {
>       owner {
>         __typename
>       
>         ... on Shared {
>           initialSharedVersion
>         }
>       
>         ... on AddressOwner {
>           owner { address }
>         }
>       
>         ... on Parent {
>           parent { address }
>         }
>       }
>     }
>   }
> }
> ```
> 
> Note that this query is [paginated](https://docs.sui.io/concepts/graphql-rpc#pagination), so I have also added a parameter to take a cursor for pagination, and added fields to check for a further page and return the end cursor as well.

Thks.
