### ISSUE TITLE
Explorer search navigates to Object Error page for New Accounts

### ISSUE THREAD

**Issue by arun-koshy** [MystenLabs/sui#1746]
Figured out what the issue was with the new `accounts` not displaying on explorer. Think by default when you search using an address it tries to find the `account` via `/addresses` but if it cannot it will search for the `object` via `/objects`? So for an `account` without objects it will be default navigate you to the `/objects`  where it will return the following error.

```
There was an issue with the data on the following object
DF438519C31A2DAA1511FA61C2AA72581C5183D2
```

The issue here is that when I finally do transfer the object to this account my natural instinct is to refresh the page but the url will stay the same (i.e.` /objects/DF438519C31A2DAA1511FA61C2AA72581C5183D2`) which causes confusion if you don't know what to look for.

If I manually change the url to `/addresses/DF438519C31A2DAA1511FA61C2AA72581C5183D2`  I do see a page with an empty area for owned objects. Not sure how you would be able to do it but would be nice if this was the default behavior for new accounts. I am not sure how you would distinguish between a new account and an object that does not exist.

**Comment by Andrew47** [comment]
@arun-koshy / @stella3d --> has this problem been resolved? If not, the issue is likely to be that a new account has no objects and not having objects raises an error.
