### ISSUE TITLE
Better error message for "Attempt to transfer an object that's not a coin"

### ISSUE THREAD

**Issue by huitseeker** [MystenLabs/sui#1747]
Passing an NFT object ID through the wallet's `transfer` function results in the message:
```
RPC call failed: ErrorObject { code: ServerError(-32000), message: "Attempt to transfer an object that's not a coin.", data: None }
```
See
https://github.com/MystenLabs/sui/blob/c3ee146af546ccf3d049098551741fef54b00dd6/sui_types/src/error.rs#L55-L56

While the behavior is expected, this message could be more helpful, in pointing out that non-coin object transfers must go through a distinct Move call (and possibly helping me, the user, figure out how to craft that transaction).

**Comment by patrickkuo** [comment]
I have added transfer must go through move call in the error message in [this PR](https://github.com/MystenLabs/sui/pull/1762)

For more helps, maybe we should consider implementing error code and have a dedicated doc(or StackOverflow) for extra informations, can't put too much info in the error message...
