### ISSUE TITLE
Enoki SDK - 403 Forbidden

### ISSUE THREAD

**Issue by Sceat** [MystenLabs/sui#17486]
Trying to setup Enoki for the zklogin flow, the basic example with a testnet api key gives a

```
   POST https://api.enoki.mystenlabs.com/v1/zklogin/nonce 403 (Forbidden)
```

- tried without domain restriction
- tried with domain restriction

Should the app be published to work ? if So, how do we publish it ?

**Comment by Jordan-Mysten** [comment]
Can you make sure you're setting the network to testnet when using the Enoki APIs? If you have a snippet of the code you're using that would also help debug!

**Comment by Sceat** [comment]
We can improve the doc by specifying it here 

<img width="602" alt="image" src="https://github.com/MystenLabs/sui/assets/11330271/668b82fd-ef2c-4ec1-9714-b9199d019981">
