### ISSUE TITLE
[graphql] function filter could filter that the first function name of a PTB

### ISSUE THREAD

**Issue by enoloo** [MystenLabs/sui#17521]

**Comment by stefan-mysten** [comment]
@enoloo is this a feature request? If so, could you explain a bit more the requirements and use cases that you envision?

**Comment by enoloo** [comment]
> @enoloo is this a feature request? If so, could you explain a bit more the requirements and use cases that you envision?

query null here:
``` 
{
  transactionBlocks(
    filter: {function: "0x2ac68d34a400893f82a61d02a2c1f530088712f961e9b51ac557a6480affee0d::repository::policy_add"}
  ) {
    nodes {
      digest
      sender {
        defaultSuinsName
      }
    }
  }
}
```

but, actually see moveall 1 (0x2ac68d34a400893f82a61d02a2c1f530088712f961e9b51ac557a6480affee0d::repository::policy_add) here:
https://testnet.suivision.xyz/txblock/EG1iaeq365FsVKhMWtgPgmYdVMyj25SGXDMfk7rumpmf?tab=Overview

transactionBlocks  filter function does not work!

**Comment by amnn** [comment]
Thanks for the report @enoloo ! @wlmyng, could you investigate while you optimise these queries?

**Comment by enoloo** [comment]
> Thanks for the report @enoloo ! @wlmyng, could you investigate while you optimise these queries?

Thx

**Comment by amnn** [comment]
Cleaning up this issue as it has now been addressed on all networks with the latest release. Thanks for reporting @enoloo .
