### ISSUE TITLE
Wallet should try to pick a gas object that's currently not locked

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1756]
When running the wallet, the wallet has the ability to pick a gas object automatically.
However we currently don't filter on gas objects that are currently locked.
We could go as far as filtering this, or we could do something simple like always pick a random gas object so that we have better chance of not picking the locked object.
@patrickkuo @oxade

**Comment by oxade** [comment]
@lxfind locked by the validators or locked by gateway?

**Comment by lxfind** [comment]
By the gateway due to another tx
