### ISSUE TITLE
I would like to ask when will the random object 0x8 be available on the testnet?

### ISSUE THREAD

**Issue by summertoo** [MystenLabs/sui#17628]
**I would like to ask when will the random object 0x8 be available on the testnet?**

![when](https://github.com/MystenLabs/sui/assets/6514153/8613cf7d-2057-4cb7-bd7c-c6710af13ccf)

**Comment by stefan-mysten** [comment]
[This PR](https://github.com/MystenLabs/sui/pull/17601) will enable 0x8 on testnet with the new [testnet release](https://sui.io/networkinfo).
