### ISSUE TITLE
Sui On-Chain Randomness Update Mechanism not Documented

### ISSUE THREAD

**Issue by siphonelee** [MystenLabs/sui#17653]
Thanks for the great work, sui team!

I've read the doc about [sui on-chain randomness](https://docs.sui.io/guides/developer/advanced/randomness-onchain), and found the related [code](https://github.com/MystenLabs/sui/blob/16624f1dfa12f4afbf4c37eff40219b28dd1916b/crates/sui-framework/packages/sui-framework/sources/random.move#L90-L121), but it's not clearly stated how the randomness is updated, like in what scenarios or frequency etc. 

Why it's concerning to me is that it's related to how safely I can rely on the randomness. For example, attackers may predict the number if they call for the random number in a time window very close to mine, just because epoch/randomness_round were not updated timely, considering sui::random uses global randomness state.

Please update the doc for this. Thanks!

**Comment by aschran** [comment]
cc @benr-ml if you have anything you wanted to add here or on doc

**Comment by siphonelee** [comment]
@aschran Thank you, that solves my problem.
