### ISSUE TITLE
[Bug] TS SDK GraphQL schemas error.

### ISSUE THREAD

**Issue by lukema95** [MystenLabs/sui#17681]
## Steps to Reproduce Issue

I introduced the latest sui.js library in NestJS, but the startup error:

<img width="1481" alt="image" src="https://github.com/MystenLabs/sui/assets/32571952/50f6f22a-153b-48c6-b0da-99245597b18a">

It started normally after I chose to use version 0.51. I noticed that the graphQL upgrade was introduced in #17587  , and I think this upgrade is causing the error.

## System Information

* OS: MacOS
* Node Version: v22.1.0

**Comment by hayes-mysten** [comment]
I think you just need to update your version of typescript to support the new syntax

**Comment by lukema95** [comment]
> I think you just need to update your version of typescript to support the new syntax

Thanks, it works for me.
