### ISSUE TITLE
 Client-Side Exception Occurs for Wallet Components in SDK Documentation

### ISSUE THREAD

**Issue by karangoraniya** [MystenLabs/sui#17725]
After using the `wallet-provider` component from the Sui SDK, attempting to use any other wallet components (e.g., `ConnectButton`) results in an error. The issue seems to be related to the documentation.

**Steps to Reproduce:**

- Navigate to the Sui SDK documentation page for [Wallet Provider](https://sdk.mystenlabs.com/dapp-kit/wallet-provider).
- Follow the instructions to implement the wallet-provider component in your application.
- Attempt to use another wallet component, such as [ConnectButton](https://sdk.mystenlabs.com/dapp-kit/walletcomponents/ConnectButton), as per the documentation.
- Observe the error that occurs.

**Expected Behavior:**

The wallet components should integrate seamlessly, and the example code provided in the documentation should work without errors.

**Actual Behavior:**

When using any wallet component after the wallet-provider, the application throws an error:

```
Application error: a client-side exception has occurred (see the browser console for more information).
```

**Video for reference:**

Initial implementation of wallet-provider:

https://github.com/MystenLabs/sui/assets/61357747/9b702580-2311-42ca-9f3e-da77a54a5f8d

**Comment by hayes-mysten** [comment]
I think this should be fixed now! thanks for reporting this
