### ISSUE TITLE
Release 1.25 "sui" binary missing in macos-arm64 assets

### ISSUE THREAD

**Issue by mario4tier** [MystenLabs/sui#17770]
## Steps to Reproduce Issue
Download sui-testnet-v1.25.0-macos-arm64.tgz from Mysten Labs git https://github.com/MystenLabs/sui/releases

## Expected Result
I expect assets to include the "sui" binary.
(like the previous releases).

## Actual Result
Release 1.25 has only "move-analyzer" and "sui-debug" binaries.
Many binaries are missing.

## System Information

* OS: MacOS

**Comment by kkomelin** [comment]
Can confirm that it's quite an important issue which two user have already reported through different channels.

**Comment by stefan-mysten** [comment]
Thanks for flagging this @mario4tier & @kkomelin. 
We're working on fixing that asap.

**Comment by ebmifa** [comment]
https://github.com/MystenLabs/sui/releases/download/testnet-v1.25.0/sui-testnet-v1.25.0-macos-arm64.tgz and https://github.com/MystenLabs/sui/releases/download/devnet-v1.25.0/sui-devnet-v1.25.0-macos-arm64.tgz have been fixed now. Sorry about the breakage.
I have also put up a PR to fix this going forward.

**Comment by kkomelin** [comment]
Awesome @ebmifa. Thank you for your effort!
