### ISSUE TITLE
Feedback for “Sui Programmable Transaction Blocks Basics”

### ISSUE THREAD

**Issue by hz73219** [MystenLabs/sui#17817]
How to send non-sui tokens. I don't see instructions

**Comment by stefan-mysten** [comment]
Thanks for your suggestion @hz73219. We'll try to add that to the docs. 

In the meantime, I imagine you can transfer an object just like transferring a SUI coin. 
Have you tried some similar code and it did not work?
```
const obj_address = address_here;
txb.transferObjects([obj_address], '0xSomeSuiAddress');
```
