### ISSUE TITLE
How to receive assets inside of a bag

### ISSUE THREAD

**Issue by jorgemmsilva** [MystenLabs/sui#17847]
## Steps to Reproduce Issue

Scenario:
 - create a bag, fill it with N different coins
 - send that bag to an object
 - receive the assets on said bag

I would assume something like this should work:
```
transfer::public_transfer(bag.remove(key), someAddress);
```

## Expected Result

The object gets removed from the bag and transferred to `someAddress`

## Actual Result

error: `Could not infer this type. Try adding an annotation`

---

Is there a way to "instantiate" the type of an object saved to a dynamic field? I guess that would solve this problem.
I couldn't find a way to do that, even if the type_name is known/stored somewhere.

**Comment by tnowacki** [comment]
You need to know the type statically when pulling something out of a `Bag`

**Comment by jorgemmsilva** [comment]
Thanks @tnowacki . I understand that, but was hoping this could be made possible in the future somehow?

As it stands, as far as I understand, it is impossible to get a collection of assets out of a `Bag` . Seems a bit limiting :disappointed:

**Comment by tnowacki** [comment]
> it is impossible to get a collection of assets out of a Bag

I'm not sure I fully understand. Could you provide an example of what you are trying to do?

**Comment by jorgemmsilva** [comment]
a toy example to simplify things: suppose a `Gift` struct that contains a custom `AssetsBag`

```
    public struct Gift has key { 
        assets: AssetsBag, 
    }
```

this custom `AssetsBag` looks like this:

```
    public struct AssetsBag has key, store {
        id: UID,
        keys: vector<String>,
    }

    // ... 
    
    // the `add` function saves each asset under their "type name" key
   // the "type name" is stored in the `keys` vector, so we can iterate the bag later
    public fun add<V: key + store>(bag: &mut AssetsBag, asset: V) {
        let key = type_name::into_string(type_name::get<V>());
        field::add(&mut bag.id, key, asset);
        bag.keys.push_back(key); 
    }
    
    // ... 
```

Anyone can create a Gift object with an arbitrary amount of coins/nfts and send it to a `GiftCollector` object.
This `GiftCollector` object, has a `receive_gift` function that looks like the following:
```
    public fun receive_gift(gift_collector: &mut GiftCollector, received_gift: transfer::Receiving<Gift>, _ctx: &mut TxContext) {
        let gift = request::receive(&mut gift_collector.id, received_gift);
        let assets = gift.assets(); 
        let assets_keys = assets.keys(); 
        while (!assets_keys.is_empty()){
            let key = assets_keys.pop_back();
            transfer::public_transfer(assets.remove(key), gift_collector.addr()); // this won't work :(
        }; 
        gift::destroy_gift(gift);
    }
```

When trying to receive an asset from the bag, the type is lost and we cannot re-construct it.

Hope it is more clear now :pray:

**Comment by jorgemmsilva** [comment]
I understand that this stems from the fact that MoveVM does not allow dynamic dispatch. 
Maybe there is another way to send/receive an heterogeneous collection of assets?

**Comment by tnowacki** [comment]
You will not be able to do so in any scheme in Move without knowing the type of what you are sending/receiving statically. 

You could however, add a layer of indirection, which might help. That is, you don't need to actually unpack each asset to receive them
```move
public struct Gift has key { 
    id: UID,
    assets: vector<Asset>, 
}

public struct Asset has key, store {
    id: UID,
    ty: TypeName, 
}

const ASSET_KEY: u8 = 0;

public fun add<V: key + store>(gift: &mut Gift, v: V, ctx: &mut TxContext) {
    let ty = type_name::get<V>();
    let asset = Asset {
        id: object::new(ctx),
        ty,
    };
    field::add(&mut asset.id, ASSET_KEY, asset);
    gift.assets.push_back(asset);
}

public fun receive_assets(gift_collector: &mut GiftCollector, received_gift: transfer::Receiving<Gift>, _ctx: &mut TxContext) {
    let collector_id = gift_collector.id.to_address();
    let Gift { id, assets: mut assets } = transfer::receive(&mut gift_collector.id, received_gift);
    object::delete(id);
    while (!assets.is_empty()) transfer::public_transfer(assets.pop_back(), collector_id);
}

public fun receive_gift(gift_collector: &mut GiftCollector, received_gift: transfer::Receiving<Gift>, _ctx: &mut TxContext) {
    let collector_id = gift_collector.id.to_address();
    let gift = transfer::receive(&mut gift_collector.id, received_gift);
    while (!assets.is_empty()) transfer::public_transfer(gift, collector_id);
}
```

**Comment by jorgemmsilva** [comment]
thank you for the response.


I think there's an error in the `add` function above, where the `v` parameter doesn't get used. It should probably look like this?
```
public fun add<V: key + store>(gift: &mut Gift, v: V, ctx: &mut TxContext) {
    let ty = type_name::get<V>();
    let mut asset = Asset {
        id: object::new(ctx),
        ty,
    };
    field::add(&mut asset.id, ASSET_KEY, v);
    gift.assets.push_back(asset);
}
```

---

This method doesn't fully work for me, as I need to keep track of the received assets (like a Bag on the `GiftCollector`) so they can be re-used later.

I'm exploring doing the function composition as a PTB (the client is required to iterate the GiftBag and call a `receive` func for each asset)

Appreciate the attention, I think this issue can be closed as my idea was not possible to implement due to the design of the MoveVM.
