### ISSUE TITLE
GraphQL api returns no transactions newer then digest `HbpmSr97y9jv1Mo18fz974PwKypcUn33LoUqT8ibvg9i`

### ISSUE THREAD

**Issue by Valandur** [MystenLabs/sui#17869]
## Steps to Reproduce Issue

1. Go to https://sui-mainnet.mystenlabs.com/
2. Use the following query
```
query Test {
  epoch {
    epochId
    startTimestamp
    endTimestamp
  }
  checkpoints(last: 5) {
    nodes {
      digest
    }
  }
  transactionBlocks(
    last: 5
  ) {
    nodes {
      digest
    }
  }
}
```
3. Run the query

## Expected Result

GraphQL returns different digests (almost) every time, since there are new blocks being produced.

## Actual Result

The newest transaction block returned has digest `HbpmSr97y9jv1Mo18fz974PwKypcUn33LoUqT8ibvg9i` and no newer blocks are ever returned.

## Notes

Using the RPC API to retrieve the newest transaction blocks works as expected.

**Comment by stefan-mysten** [comment]
Thanks for the report @Valandur. We're aware of the situation and working hard to remediate it (some mishaps with the indexer DBs). I will update here when I have more info.

**Comment by stefan-mysten** [comment]
@Valandur this should have been fixed now, but the indexer needs to catch up, so the data is still behind.

**Comment by Valandur** [comment]
Thanks for taking care of this, looks good to me now 👍
