### ISSUE TITLE
Add Sui link to Explorer landing page

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#1786]
<img width="681" alt="image" src="https://user-images.githubusercontent.com/22014917/166738030-432b8e79-39d8-43b1-aff8-ef70342fe099.png">

Can we add either:
1) Add Sui before Mysten Labs (preferred)
or 
2) Replace Mysten Labs with Sui

**Comment by Jibz1** [comment]
@bwann52 this is done
