### ISSUE TITLE
[Enoki] `signPersonalMessage` inconsistencies 

### ISSUE THREAD

**Issue by Sceat** [MystenLabs/sui#17912]
When testing the `signPersonalMessage` feature in the Sui wallet and Enoki, I observed inconsistent behavior in the signed message output.

## Code Example:

**Sui Wallet:**

```js
const { bytes: suiBytes, signature: suiSignature } = await features['sui:signPersonalMessage'].signPersonalMessage({
  account: { address },
  message: new Uint8Array([0, 1, 2, 3]),
});

console.dir({ bytes: Buffer.from(suiBytes, 'base64') });

// bytes: [0,1,2,3]
```

**Enoki:**

```js
const keypair = await enokiflow.getKeypair({ network: NETWORK });
const { bytes: enokiBytes, signature: enokiSignature } = await keypair.signPersonalMessage(new Uint8Array([0, 1, 2, 3]));

console.dir({ bytes: Buffer.from(enokiBytes, 'base64') });

// bytes: [4,0,1,2,3]
```

## Expected Behavior:
The signed messages should be consistent and not include unexpected additional bytes.

It appears that Enoki's signPersonalMessage is adding an extra byte `4` to the beginning of the signed message. This discrepancy suggests a difference in the signing algorithm or implementation between the Sui wallet and Enoki.

Could you please investigate this inconsistency and provide guidance on how to ensure both implementations produce compatible signed messages?

Thank you.

**Comment by hayes** [comment]
This will be fixed in the 1.0 release of the typescript SDK, which we are hoping to publish next week

**Comment by Sceat** [comment]
It seems there are still issues verifying the signature, while the bytes are now correct in the latest sdk version, the `verifyPersonalMessageSignature` still fails for Enoki with:

```
Error: Signature is not valid for the provided message
    at verifyPersonalMessageSignature (@mysten_sui_verify.js?v=d4dbd704:2486:11)
```

It works fine without Enoki.

```js
import { verifyPersonalMessageSignature } from '@mysten/sui/verify'

const keypair = await enokiflow.getKeypair({ network: NETWORK });
const { bytes: enokiBytes, signature: enokiSignature } = await keypair.signPersonalMessage(new Uint8Array([0, 1, 2, 3]));

console.dir({ bytes: Buffer.from(enokiBytes, 'base64') });

// bytes: [0,1,2,3]

await verifyPersonalMessageSignature(fromB64(bytes), signature) // throws
```

**Comment by hayes-mysten** [comment]
I'm looking into this, and will see if I can figure out whats going on

**Comment by hayes-mysten** [comment]
It looks like the GraphQL API is timing out while trying to verify the signature

**Comment by Sceat** [comment]
@Jordan-Mysten is it intended that the sdk doesn't allow verification ?

**Comment by hayes-mysten** [comment]
verification was recently added to the sdk, using the GraphQL API as part of the verification flow, but there are currently performance issues with the GraphQL API that are causing the verification requests to timeout.  The underlying issues are being worked on, but it hasn't been resolved yet

**Comment by hayes-mysten** [comment]
The GraphQL API deployed a new version to mainnet with a fix for this issue.  Everything seems to be working well now, let me know if you are still having issues

**Comment by Sceat** [comment]
It seems to work through the Graphql endpoint, thanks!
It would be really convenient to have it supported by the sdk directly too tho

**Comment by hayes** [comment]
The SDK supports it, but internally uses the GraphQL endpoint.  Verification is not possible without a network request

**Comment by Sceat** [comment]
I don't get it, it's failing through the sdk on my side but works if I contact graphql directly, how do you do with the sdk then ?
