### ISSUE TITLE
Wallet interactive mode does not accept whitespaces in arguments

### ISSUE THREAD

**Issue by arun-koshy** [MystenLabs/sui#1792]
```
sui>-$ create-example-nft --url=https://user-images.githubusercontent.com/76067158/166136286-c60fe70e-b982-4813-932a-0414d0f55cfb.png --description="The greatest chef in the world" --name="Greatest Chef"
error: Found argument 'greatest' which wasn't expected, or isn't valid in this context

USAGE:
    create-example-nft [OPTIONS]

For more information try --help
```

From @longbowlu 

> in the interactive mode, it can't take args with whitespaces, even in quotes

> ```
> e.g.
> create-example-nft --name "test1" --description "test2"
> is good ,but
> create-example-nft --name "test 1" --description "test2"
> is not
> ```

**Comment by patrickkuo** [comment]
this is fixed by https://github.com/MystenLabs/sui/pull/1795
