### ISSUE TITLE
Restore Sui RPC Extended API

### ISSUE THREAD

**Issue by idan-david** [MystenLabs/sui#17969]
On April 12th 2023 the following indexer APIs were commented out in #10779.
The PR also stated this was done temporarily.
Would it be possible to restore this API?

## Steps to Reproduce Issue

1. Call `suix_getEpochs`
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "suix_getEpochs",
    "params": [300]
}
```

## Expected Result

Return a list of epochs

## Actual Result

Getting a method not found
```
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32601,
        "message": "Method not found"
    },
    "id": 1
}
```

**Comment by stefan-mysten** [comment]
The new RPC will provide this, but I do not think these will be restored for the JSON-RPC. Depending on your use case, you could try to use the GraphQL RPC: 
* https://sui-mainnet.mystenlabs.com/graphql
* https://sui-testnet.mystenlabs.com/graphql
* https://sui-devnet.mystenlabs.com/graphql

A query to get epoch 200 would look like this.

```graphql
{
  epoch(id: 200) {
    epochId
    referenceGasPrice
  }
}
```

For the last known epoch, you skip the `id:200`, like this:
```graphql
{
  epoch {
    epochId
    referenceGasPrice
  }
}
```

**Comment by idan-david** [comment]
Thank you for the response, this seems like a great solution to my need!

Currently I see that the new RPC is still catching up on indexing (I think it might be related to #17869).
It seems that the data is lagging about 12 hours behind the JSON-RPC.
Epoch returns 412, even though we are already in epoch 413.

Do you have an estimate as to when the indexer will catch up?

```
query Test {
  epoch {
    epochId
    startTimestamp
    endTimestamp
  }
  checkpoints(last: 2) {
    nodes {
      digest
      timestamp
      epoch {
        epochId
      }
    }
  }  
}
```

**Comment by stefan-mysten** [comment]
@idan-david happy we found a way to unblock you. 

Regarding your query, the data seems up-to-date. The `start_timestamp` is when the epoch started, and the last two checkpoints show up-to-date data. This query was ran on `mainnet`.
```graphql
{
  "data": {
    "epoch": {
      "epochId": 413,
      "startTimestamp": "2024-05-29T17:30:49.209Z",
      "endTimestamp": null
    },
    "checkpoints": {
      "nodes": [
        {
          "digest": "4JbHJwQCFszK5oGz9KutqTGsbTnNgmsaa23bJJ8FQAn3",
          "timestamp": "2024-05-30T15:05:21.702Z",
          "epoch": {
            "epochId": 413
          }
        },
        {
          "digest": "GsTka58A2K1JA3EQS2raAs9bdFoxtgZN1MxzwxvCp8ye",
          "timestamp": "2024-05-30T15:05:22.679Z",
          "epoch": {
            "epochId": 413
          }
        }
      ]
    }
  }
}
```

**Comment by idan-david** [comment]
Hey @stefan-mysten, thank you for the reply.
I am using `https://sui-mainnet.mystenlabs.com/graphql` as the endpoint, is this the correct endpoint?
I see that your request seems up to date, but on my end I still get outdated results.

At the time of writing this, it is now around `2024-06-02T13:02:29Z`

The following requests returns data for epoch **416**, with `timestampMs` set to the current time.
```bash
curl --location 'https://suiscan.xyz/api/sui/mainnet/' \
--header 'content-type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "sui_getCheckpoints",
    "params": [
        null,
        1,
        true
    ]
}'
```

```json
{
    "jsonrpc": "2.0",
    "result": {
        "data": [
            {
                "epoch": "416",
                "sequenceNumber": "35666415",
                "digest": "6e9uCLEaXxhRy77Gwpjsane7Qp81MQ4rv8T7UHpVSb4o",
                "networkTotalTransactions": "1685610456",
                "previousDigest": "4w5wUuQC9nxnbgJnyt8JBMnKVXhdWhNxZ3mZy9HnTYwH",
                "epochRollingGasCostSummary": {
                    "computationCost": "10172757674144",
                    "storageCost": "79866295446000",
                    "storageRebate": "75549214745928",
                    "nonRefundableStorageFee": "763123381272"
                },
                "timestampMs": "1717333401296",
                "transactions": [
                    "9AYncWexXDNLs79CoCzmB6xeFGPs4hurmN1ryvXabmLc",
                    "abbreviated"
                ],
                "checkpointCommitments": [],
                "validatorSignature": "q+qH/NdkRTDKQ5ko757H+knALDyA0uSnK0jkLcHcCf6LAiEyinAlkHLYCssjTRKr"
            }
        ],
        "nextCursor": "35666415",
        "hasNextPage": true
    },
    "id": 1
}
```


The result of the graphql query returns data for epoch **415**

```graphql
{
  "data": {
    "epoch": {
      "epochId": 415,
      "startTimestamp": "2024-05-31T17:31:00.656Z",
      "endTimestamp": null
    },
    "checkpoints": {
      "nodes": [
        {
          "digest": "EzrQCZ3p6ZhAsqXqtzFtpqRhzPFRDeQ3uhqy386qPc9F",
          "timestamp": "2024-06-01T09:30:13.528Z",
          "epoch": {
            "epochId": 415
          }
        },
        {
          "digest": "DiULV6NZpAt2jMDrq2s8YABYR4sSBSHGQ1iyZC3wEZba",
          "timestamp": "2024-06-01T09:30:14.494Z",
          "epoch": {
            "epochId": 415
          }
        }
      ]
    }
  }
}
```

**Comment by stefan-mysten** [comment]
Thanks @idan-david 

May I ask which region are you located in (Asia, North America, EU)?

**Comment by idan-david** [comment]
I am located in the middle east.
If there is any other info I can share that would be of help, I'd be happy to.

**Comment by stefan-mysten** [comment]
Thanks @idan-david. The issue might be with the fact that due to high traffic, there seems to be some delay in getting the data indexed in two locations (Asia, EU) and then served by the DB replicas. The NA server seems to have the up-to-date data. I will check with the team internally, but not sure what is the workaround for now to get you unblocked. 
Apologies for the inconvenience!

**Comment by idan-david** [comment]
Thanks @stefan-mysten, I just checked with a VPN and the data is up to date!
I'm closing the issue for now

**Comment by stefan-mysten** [comment]
@idan-david we updated our DB setups so now you should see up-to-date data in all regions, so no need for a VPN.

**Comment by idan-david** [comment]
@stefan-mysten 
Confirmed working, thank you for all your help!
