### ISSUE TITLE
what the content of <transaction contents> look like for @mysten/ledgerjs-hw-app-sui

### ISSUE THREAD

**Issue by ZanyuanYang** [MystenLabs/sui#18049]
I'm using `@mysten/ledgerjs-hw-app-sui`,
```
const publicKey = await sui.signTransaction("44'/784'/0'/0'/0'", '<transaction contents>');
```

For this code, someone know what the content of `<transaction contents>` look like

**Comment by Jordan-Mysten** [comment]
@ZanyuanYang It should be either a uint8array or a base64-encoded string of the raw transaction bytes.

**Comment by Jordan-Mysten** [comment]
That's expected for any transaction that isn't a simple transfer of coins. We're hoping to improve to recognized transactions as time goes on.
