### ISSUE TITLE
"sui start" process dies within ~24 hours

### ISSUE THREAD

**Issue by mario4tier** [MystenLabs/sui#18067]
## Steps to Reproduce Issue

On ubuntu, do `env RUST_LOG=error sui start --network.config $MY_NETWORK_CONFIG` 

Crash within ~24 hours after logging hundreds of errors for ~5 minutes.

This localnet is not under stress (mostly idle).

Using official binary: `sui-devnet-v1.26.0-ubuntu-x86_64.tgz`
sui --version : `sui 1.26.0-d709c305ebf3`

$MY_NETWORK_CONFIG is attached ( [network.yaml.txt](https://github.com/user-attachments/files/15571072/network.yaml.txt) ), but doubtful specific to the config (I use the same generated config for a long time).

## Expected Result
Run "forever"

## Actual Result

Process crash.

No OOM-Killer message in dmesg or /var/sys/syslog

"top" shows RES memory usage to be ~40GB

Only log outputs are all same errors in last ~5 minutes before dying. Excerpt:

`2024-06-04T20:43:25.557388Z ERROR mysten_metrics::histogram: Histogram data overflow - we receive histogram data for checkpoint_summary_age_ms faster then can process. Some histogram data is dropped`

... repeats 618 times until...

`2024-06-04T20:48:22.289513Z ERROR mysten_metrics::histogram: Histogram data overflow - we receive histogram data for last_executed_checkpoint_age_ms faster then can process. Some histogram data is dropped`

... no other logs before crash.

## System Information

* OS: Ubuntu 23.10 - Kernel 6.5.0-35-generic
* Compiler:  N/A

I always use latest binaries and started to observe this problem in the last ~2 weeks (I do not know which version it started for sure, can try to isolate further as needed).

**Comment by stefan-mysten** [comment]
Thanks for reporting this @mario4tier. The only alternative I have in mind is to use a testnet/mainnet binary instead of devnet, perhaps that is more stable? (unless you really need the latest features on devnet).

**Comment by mario4tier** [comment]
This is a localnet setup used to **detect early** if my project is still compatible with the next version in Mysten Labs pipeline... but I will verify with testnet 1.26.1 binary and let you know.

**Comment by stefan-mysten** [comment]
> This is a localnet setup used to **detect early** if my project is still compatible with the next version in Mysten Labs pipeline... but I will verify with testnet 1.26.1 binary and let you know.

Oh, I see, that makes sense then to use the `devnet` version. I'll relay this issue to our team.

**Comment by stefan-mysten** [comment]
Someone in the team started a local process on their machine and will leave it overnight (though I think on Mac), will keep you posted.

**Comment by mario4tier** [comment]
One more observation today, this time on a Mac M2 pro. 

Running devnet 1.26.0, there was a burst of the same error... but no crash (logged 143 times in the same ~1 millisecond)

Excerpt:
```
2024-06-05T19:26:51.426451Z ERROR mysten_metrics::histogram: Histogram data overflow - we receive histogram data for checkpoint_summary_age_ms faster then can process. Some histogram data is dropped
2024-06-05T19:26:51.426475Z ERROR mysten_metrics::histogram: Histogram data overflow - we receive histogram data for checkpoint_summary_age_ms faster then can process. Some histogram data is dropped
...
2024-06-05T19:26:51.428672Z ERROR mysten_metrics::histogram: Histogram data overflow - we receive histogram data for checkpoint_contents_age_ms faster then can process. Some histogram data is dropped```

**Comment by stefan-mysten** [comment]
Thanks for the new data point. How much RAM does the Ubuntu machine have?

**Comment by mario4tier** [comment]
Ubuntu testnet 1.26.1 crashed ~20 minutes ago.

The RES memory usage was slowly increasing (~29GB, last check ~1hour before the crash)

There was a burst of "Histogram" logs error (639 in 5 minutes), but this time it happened ~21 hours *before* the crash. So it is not clear if related.

![image](https://github.com/MystenLabs/sui/assets/4542410/b532ab94-a847-42d0-9496-0de9f7f20c97)

**Comment by mario4tier** [comment]
Today, there was two bursts of the same Histogram error on Mac 

The burst on Mac are different (~100 happening within a few milliseconds).

No crash on the Mac and there is no apparent memory useage increase.

Another hint that the Error and the crash might not be related?

**Comment by mario4tier** [comment]
All my setups were upgraded to latest 1.27 ~24 hours ago.

So far I have not seen the Histogram error, and no crash, but the memory usage is still slowly increasing (RES now at ~33GB).
![image](https://github.com/MystenLabs/sui/assets/4542410/315621c8-e768-46d1-b868-31582150b74a)

(I assume this would be a problem with setup with 16 or 32GB hosts).

**Comment by mystenmark** [comment]
@mario4tier I ran `sui start` locally for several days and didn't have any issues. But one thing you could try in order to reduce memory consumption is to run it as:

```
 env RUST_LOG=error OBJECTS_BLOCK_CACHE_MB=20 LOCKS_BLOCK_CACHE_MB=20 TRANSACTIONS_BLOCK_CACHE_MB=20 EFFECTS_BLOCK_CACHE_MB=20 EVENTS_BLOCK_CACHE_MB=20 INDIRECT_OBJECTS_BLOCK_CACHE_MB=20 sui start --network.config $MY_NETWORK_CONFIG
```

Let us know if that helps - if it does, we should probably make it the default for `sui start`. Right now the block cache sizes are tuned for validator performance.

**Comment by mario4tier** [comment]
@mystenmark

The memory usage is still slowly going up even with the proposed "env" changes. In both case, the rate seems to get slower with time.

Without the "env" after ~24 hours (ubuntu+Sui 1.27):
![image](https://github.com/MystenLabs/sui/assets/4542410/6581c64b-3948-4ae1-b78e-8fba83edcafc)

With the "env" (same setup) after ~18 hours:
![image](https://github.com/MystenLabs/sui/assets/4542410/6f145595-93d7-48c9-aeee-4c5f627f64fb)

As needed, I can next use a tool to monitor/graph the memory usage to see if there is a different "rate of consumption", but not sure if that will be helpful; It seems like a slow memory leak in both cases.

**Comment by stefan-mysten** [comment]
Any updates here @mario4tier? Do you still see issues with the process and memory?

**Comment by mario4tier** [comment]
Yes, but in short: you can close this issue.
===
Found another problem (ever growing disk space for full_node_db) and decided to work-around all these issues with a script to reboot/regenesis/delete full_node_db of localnet ~every other day.

**Comment by stefan-mysten** [comment]
Good to now! Regarding the space issue, we're planning to fix that with a new local network tool!
