### ISSUE TITLE
[CLI] Funky string escaping in arguments to Move call

### ISSUE THREAD

**Issue by sblackshear** [MystenLabs/sui#1808]
The need to escape for object ID's and addresses in `wallet call` is a bit funky. To transfer an object I had to do:

`--args \"0xA6544796122877011F17EE3A1518825D4623C48F\" \"0x3fc1d945c33ad47d123e3ac0fab854b3015f8e4d\"`
, whereas it would be nice to do something like

`--args 0xA6544796122877011F17EE3A1518825D4623C48 0x3fc1d945c33ad47d123e3ac0fab854b3015f8e4d`

Particularly because if you are missing the escapes, the error message is hard to decipher:

```
λ wallet call --package f41c72b116b2eba364aad3557fad60a18b46c09d --module PolyTransfer --function transfer_devnet_nft --gas-budget 30000 --args 0xA6544796122877011F17EE3A1518825D4623C48F
error: Invalid value "0xA6544796122877011F17EE3A1518825D4623C48F" for '--args <ARGS>...': trailing characters at line 1 column 2
```

**Comment by patrickkuo** [comment]
this is fixed by https://github.com/MystenLabs/sui/pull/1800
