### ISSUE TITLE
Testnet GraphQL server refusing queries (CORS)

### ISSUE THREAD

**Issue by chfarmdev** [MystenLabs/sui#18197]
## Steps to Reproduce Issue

All GraphQL queries are failing with CORS errors noted below. Both from local development and from my testnet hosted solution.

Access to fetch at 'https://fullnode.testnet.sui.io/' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

This started happening about 14 hours ago.

const { data, error, status, hasNextPage, fetchNextPage, isFetching } = useInfiniteQuery({
    queryKey: ['getwarlords', address, WarlordObjectType], 
    queryFn: async ({ pageParam = null }) => 
       
      request<WarlordQueryType>(
        GRAPHQL_URL,
        getWarlords,        
        {address: address, type: WarlordObjectType, cursor: pageParam},               
      ),      
      initialPageParam: undefined,
      getNextPageParam: (lastPage: WarlordQueryType) => {
      if (lastPage.address.objects.pageInfo.hasNextPage === true) {
        return lastPage.address.objects.pageInfo.endCursor;
      } else {
        return undefined;
      }      
    }  

  export const getWarlords = gql  

  query getWarlords(
	$address: String!,  
  $type: String!
  $cursor: String,	
) {
	address(address: $address) {
		objects(after: $cursor, first:10, filter: {
      type: $type
    } ) 
      {
			pageInfo{
				hasNextPage
				endCursor
			}
        nodes {
          contents{
            data                       
          }
	      }
			}
		}
	}

## Expected Result

Should be getting data back

## Actual Result

CORS Error

## System Information
sui 1.26.0-d709c305ebf3

Do I need some kind of auth token or did something change on the testnet graphQL instance?
https://sui-testnet.mystenlabs.com/graphql

**Comment by stefan-mysten** [comment]
Thanks for this report. Can you explain how are ou running this, is from the TypeScript SDK or just a normal query where the endpoint is `sui-testnet.mystenlabs.com/graphql`?

**Comment by stefan-mysten** [comment]
Can you also try out this command in a terminal and paste the reply?
`curl -X POST -H "Content-Type: application/json" --data '{ "query": "query { chainIdentifier }"}' https://sui-testnet.mystenlabs.com/graphql  -i`

**Comment by chfarmdev** [comment]
Normal query I built myself. Tanstack react query using graphql-request.

$ curl -X POST -H "Content-Type: application/json" --data '{ "query": "query { chainIdentifier }"}' https://sui-testnet.mystenlabs.com/graphql  -i
HTTP/2 200 
content-type: application/json
content-length: 39
x-sui-rpc-version: 2024.4.2-1a9a436182a6a45994cffeb48f0a88a1f5e1bc19
access-control-allow-origin: *
vary: origin
vary: access-control-request-method
vary: access-control-request-headers
date: Tue, 11 Jun 2024 18:55:33 GMT
via: 1.1 google
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

{"data":{"chainIdentifier":"4c78adac"}}

**Comment by stefan-mysten** [comment]
So that query seems to work. For testing purposes, can you try to craft your query in the online ID: https://sui-testnet.mystenlabs.com/graphql

**Comment by chfarmdev** [comment]
These are stable queries I've been using awhile. Appears to be good from the IDE. Example below.

query {
	address(address: "0x2a5406dff77a774786b733d62f994b8ce0df27a603a6087681458f3f977c70ed") {
		objects(first:10, filter: {
      type: "0x6eb24e3d8cf38417dadc19bfa940cdbf2e43a503b033700002d31b3c7432b287::warlord::SuiWarlordNFT"
    } ) 
      {
			pageInfo{
				hasNextPage
				endCursor
			}
        nodes {
          contents{
            data                       
          }
	      }
			}
		}
	}

**Comment by stefan-mysten** [comment]
Not sure what could be causing this. We just redeployed `testnet` today, but you were experiencing this already yesterday, so not sure. The issue with `fullnode.testnet.sui.io` is kinda strange, because it's not really tied to that endpoint, so I am a bit confused.

**Comment by chfarmdev** [comment]
Very strange, can a single wallet/address introduce issues or be blocked?

I created a new address, fauceted some SUI and it works fine.

Flip back to my primary test user. Can't query and can't even send SUI, using official wallet.

0x2a5406dff77a774786b733d62f994b8ce0df27a603a6087681458f3f977c70ed

**Comment by stefan-mysten** [comment]
That is bizzare indeed!

**Comment by chfarmdev** [comment]
Testing some more, there is definitely a pretty large lag in gql response right now. I'm fauceting individual SUI and it's taking well over a minute to update.

Usually it's under 4 seconds. But doesn't seem to be throwing CORS errors against this new account with very few objects.

**Comment by stefan-mysten** [comment]
GraphQL and faucet are two separate services. Maybe faucet is under heavy load.

So what is under 4s, faucet or GQL?

**Comment by chfarmdev** [comment]
GraphQL when running well/normal updates in under 4 seconds. I can send a transaction from UI (Mint/level/enhance/etc), fire a graphql query and get updated information 95% of the time.

I was timing the difference between the faucet SUI hitting my wallet, and then graphql query for balance info actually updating the UI.

**Comment by stefan-mysten** [comment]
I can confirm that all data is up-to-date and the GraphQL testnet should be working OK for your query. 
Regarding the CORS issue, it might be from the wallet or some other place that is using JSON-RPC, as GraphQL does not rely on `fullnode.testnet.sui.io`. 

I'd appreciate if you can try again and let me know if this issue persists.

**Comment by chfarmdev** [comment]
It's been better for a little bit. I think it was actually something with the SUI Wallet and that particular address. I was occasionally getting errors like cannot find balance and 502 errors in the wallet. So best I can guess, when I was calling useCurrentAccount() from the dapp-kit it may not have been populating correctly. There was a good chunk of time I could also not even send SUI from that address. It was very odd, not sure if related to all the bridge traffic today or just a one off.

**Comment by stefan-mysten** [comment]
Any updates on this, are you still encountering issues?

**Comment by chfarmdev** [comment]
@stefan-mysten It's been mostly stable, certainly slow at times today. I had some objects equivocated which has never happened before but was causing a lot of strange behavior in wallet.

It's been good today though and been doing a fair bit of traffic with gql.
