### ISSUE TITLE
sequence number should never overflow

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#182]
Incrementing sequence number on an object can fail due to overflow.
This will be a violation (the only violation I can think of) of the property that even failed transaction should consume gas (hence some object is mutated). This also creates opportunities for DOS because someone can keep using this almost-overflowed gas object and trigger tx failures without paying gas.
We could make a rule that when am object is at this max version we automatically rule it immutable. And be done with it.
Our version counters are 64 bits and all versions will have to be the result of transactions on chain. This is an astronomical number of transactions, on a single object.

**Comment by kchalkias** [comment]
@lxfind I'm happy with the 2nd option, do not allow a tx with `u64:MAX`.

**Comment by lxfind** [comment]
This is done.
