### ISSUE TITLE
Tokenomics Whitepaper on Docs Sui Site

### ISSUE THREAD

**Issue by losamsel** [MystenLabs/sui#1821]
Tokenomics whitepaper draft by Alonso was shared last month. Goal is to have a finalised version for public view.

Reference to Design Doc:
https://www.notion.so/mystenlabs/Sui-Tokenomics-Whitepaper-8358431553e040bd843dc0f3d2971a8d

Notion board will include specific checklist, timelines, etc. until they are ready for public view.

**Comment by losamsel** [comment]
Alonso is editing the final PDF.

We do have the draft PDF available. We have it attached in the Notion board for your full review.

Checklist in the Notion board outlined:

- Design Doc reference (https://www.notion.so/Sui-Tokenomics-Whitepaper-8358431553e040bd843dc0f3d2971a8d)
- GitHub request for updates sections (to be completed by @Jennifer Kye & @alonso by May 6, 2022)
- [ ]  Timelines:
    - [ ]  May 17: [[sui.io](http://sui.io/)](http://sui.io) & [[docs.sui.io](http://docs.sui.io/)](http://docs.sui.io) staging ready for review
    - [ ]  May 20: tokenomics paper complete (submitted by @alonso)
    - [ ]  May 23: publish tokenomics blog post (summary + key takeaways by @alonso)
    - [ ]  May 23: [[docs.sui.io](http://docs.sui.io/)](http://docs.sui.io) published
    - [ ]  May 23: social posts announcing tokenomics paper
    - [ ]  May 30: share Google Docs “comment-able” version for contributors to provide questions or feedback
    - [ ]  May 30: share Alonso explainer video (slide presentation with voiceover)
    - [ ]  June 3: close out Google Docs - no more contributor input
    - [ ]  June 8: Alonso to host AMA on Discord to discuss Tokenomics
- [ ]  [[docs.sui.io](http://docs.sui.io/)](http://docs.sui.io) updates
    - [ ]  See what's new section to include update on Sui Economics (@Jennifer Kye to provide @Clay Murphy with appropriate copy)
    - [ ]  Will need your help @alonso & @Clay Murphy on how to best categorise sections within the Sui Doc site
        - [ ]  “Sui Economics Overview & Deep Dive” can be under “Learn”
        - [ ]  Sui Tokenomics Whitepaper can be under Contribute > Research Papers
        - [ ]  Or do we only want to do a brief overview (without the deep dive) and have the complete whitepaper under Research Papers?

**Comment by losamsel** [comment]
@econmysten
- Can you get layout website completed by May 17th EOD? This can then be shared with @Clay-Mysten and others to begin staging.
- We can also get the blog post ready by May 17th as well; I can support with getting this draft up and running on Medium. We know the link from draft to final published changes, so this will impact link on Twitter threads.
- Twitter threads can be set by May 20th for publishing next week.

**Comment by Clay-Mysten** [comment]
Yes, please let me know when and where the tokenomics paper is ready for review. I have been holding for a rewrite Alonso was undertaking first. Thanks!

**Comment by Clay-Mysten** [comment]
Hi Alonso and Jen,

Congratulations on a wonderful, clear paper, Alonso. I truly enjoyed reading it and learned so much about our offering. I've finished my review of the Tokenomics paper V2, leaving comments along the way as requested.

I can try to export the contents to our website if you can provide me with the native format (perhaps) or something like .`tex`.

Please do let me know next steps regardless. I see above:
May 24: [[docs.sui.io](http://docs.sui.io/)](http://docs.sui.io/) published
Not sure what that entails. I also see:
“Sui Economics Overview & Deep Dive” can be under “Learn”

Let me know how I can help. Thanks!

**Comment by econmysten** [comment]
thank you for the kind comments clay! i don't think we need to convert the whitepaper, rather i think the gameplan is:
1) host the pdf on github just as the Sui whitepaper
2) create a new section on the "Learn" tab of docs.sui.io called "Tokenomics". I'll finalize the table of contents by tomorrow and then hopefully finish the copy by the end of the week.
The reason why I don't think we should simply host the same text in the PDF is that I want to make the material more accessible. Just like the Sui whitepaper is precise and technical while the documentation is more accessible, we should aim for the same on the tokenomics.

**Comment by Clay-Mysten** [comment]
Just noting Alonso finished the web contents, I reviewed and edited them, and have now converted them to Markdown in:
https://github.com/MystenLabs/sui/pull/2101
https://github.com/MystenLabs/sui/pull/2102

Alonso and Jen, once you and I refine the text there, I will split it up and add to navigation as we discussed. Thanks!
