### ISSUE TITLE
Transfer to object: On SUI transfer and claim the parent object still has coin as owned object

### ISSUE THREAD

**Issue by khatriamit** [MystenLabs/sui#18253]
### Problem
I transferred SUI to an object, and later I claimed the SUI back to my wallet. However, when I call client.getAllCoins for the object, it still shows a balance value. I was under the impression that this call should only return the balance of the owner.

### Observation
When tracking this in the explorer, I see that the coin object still exists under "own objects," even though the owner of the coin object has been transferred to my wallet address.

### Expected Behavior
Once the SUI is claimed back to the wallet, client.getAllCoins should no longer return a balance for the object, and the coin object should not appear in the "own objects" list of the original object.

### Steps to Reproduce
Transfer SUI to an object.
Claim the SUI back to the wallet.
Call client.getAllCoins for the object and observe the balance value.
Check the explorer for the ownership and presence of the coin object.
Additional Information
Client Version: "^0.54.1"
Explorer URL: https://explorer.polymedia.app/address/0xb5f1e9b5b0e10cc0bb79f7c5747e714bc652b110a865f2e49b35a20a486f6aea?network=testnet
Transaction Hash: 87MoSj7tVYjs7XrTDskFkzr5AZWWi38Etc9dujBCVt7U
Please look into this issue as it appears there is a discrepancy in the balance reporting and object ownership tracking.

Thank you.

**Comment by wlmyng** [comment]
Thanks for raising this. Before TTO, we only check `input_coins` to update our coin index. With TTO, we'd also need to check among the mutated objects. We have a fix in the pipeline.
