### ISSUE TITLE
Sui Code Bug or Feature Request

### ISSUE THREAD

**Issue by hapeeeeee** [MystenLabs/sui#18285]
We found that the `parse_file` function in `move-compiler::parser::syntax.rs` does not return `Result::Err()`. However, when calling this function, the case where `parse_file` returns `Result::Err()` is handled, and Diagnostics are generated. Is this expected behavior?

![image](https://github.com/MystenLabs/sui/assets/44502668/c05d76b3-3703-4113-89fb-2635af40da62)
![image](https://github.com/MystenLabs/sui/assets/44502668/c23202bc-f372-4225-829b-f5f31c20ffe7)

**Comment by stefan-mysten** [comment]
@awelc can we close this issue now?

**Comment by awelc** [comment]
Fixed in https://github.com/MystenLabs/sui/pull/18301
