### ISSUE TITLE
Experimental Rest Api - 500 response with Missing Input Object Key 

### ISSUE THREAD

**Issue by fl0ydj** [MystenLabs/sui#18305]
## Steps to Reproduce Issue

Call https://fullnode.mainnet.sui.io/rest/checkpoints/37042334/full with a relatively recent checkpoint number (this one was 20min ago for example)

## Expected Result

Receive checkpoint data. There should not be any pruning happening as the checkpoints in question are so recent

## Actual Result

500 response with error message similar to:
"missing input object key ObjectKey(0x0000000000000000000000000000000000000000000000000000000000000006, SequenceNumber(37042334)) from tx AzACazesNaGDvfCtzNwGH5GFv7TdL8jEbMMdem3ioy2s"

## System Information

-

**Comment by stefan-mysten** [comment]
By default objects are pruned aggressively, so 20 min old version of object can be pruned. 
Also, this API is not intended to be publicly used so not sure how you got around to using it. 

Try using the JSON RPC to get the checkpoint. https://docs.sui.io/sui-api-ref#sui_getcheckpoints

**Comment by phoenix-o** [comment]
You can also retrieve the same information (i.e., full checkpoint content) from the remote store. 
For instance: `https://checkpoints.mainnet.sui.io/37042334.chk`

**Comment by fl0ydj** [comment]
Whats the plan moving forward for the sui indexer then? Currently all sui indexer crates in the repo are based on the experimental rest api if I am not mistaken.
The RPC endpoint would mean querying for hundreds of tx digests resulting in dozens of requests.

The remote store looks interesting. Why is the sui indexer crate not using that one by default?

**Comment by fl0ydj** [comment]
Or actually, sui-data-ingestion-core does seem to allow for a remote store url which should work with https://checkpoints.mainnet.sui.io ? 

Why is the sui-indexer crate not using that one? We built our custom indexer using the sui-indexer crate as a basis

**Comment by phoenix-o** [comment]
sui-indexer was already migrated to `sui-data-ingestion-core` and primarily utilizes remote store for its work.
You can find more details in our docs: https://docs.sui.io/guides/developer/advanced/custom-indexer

**Comment by fl0ydj** [comment]
Have been running some tests with the endpoint. For testnet the average checkpoint lag is 15-20s. Are there plans to reduce this in the future?
