### ISSUE TITLE
Move Analyzer crashes upon examples/ build

### ISSUE THREAD

**Issue by thounyy** [MystenLabs/sui#18307]
## Steps to Reproduce Issue

Build a package in examples directory in a move project.

1. get the latest move analyzer
2. `git clone https://github.com/gmove-io/kraken`
3. `sui move build` in /package directory and in /package/examples directory
4. open any module and modify a value to activate the analyzer
5. wait for it to crash

## Expected Result

Normal functioning for modules in /sources and /examples (like when examples are not built).

## Actual Result

``` shell
created pre-compiled libs for "/package_directory"
compiled to parsed AST
compiled to typed AST
compiling to CFGIR
compilation to CFGIR failed
get_symbols loaded
thread '<unnamed>' panicked at external-crates/move/crates/move-analyzer/src/symbols.rs:1558:76:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Error - 3:46:42 PM] Server process exited with signal SIGABRT.
[Error - 3:46:42 PM] The Move server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

## System Information

* OS: latest projectbluefin (Fedora SilverBlue)
* Compiler: sui 1.27.2-homebrew

**Comment by awelc** [comment]
Thank you for the report! I will look into it as soon as I can!

**Comment by awelc** [comment]
Fixed some time over last month (can no longer be reproduced) but cannot recall the actual PR number...
