### ISSUE TITLE
suix_queryTransactionBlocks

### ISSUE THREAD

**Issue by beykery** [MystenLabs/sui#18330]
the rpc method : suix_queryTransactionBlocks , it's param : filter , setting like below: 

 filter: {
                    FromAddress:  'xxxxxx',
                    ToAddress: 'xxxxxxx',
                }
                
then result will be :

{
  "code": -32602,
  "message": "expected value at line 1 column 93"
}

**Comment by stefan-mysten** [comment]
Unfortunately, filters are known not to work well, and in this case, they might not be supported.
 
 From the error message, something else might be wrong here. Could you share a dummy example (not the actual addresses if you don't want to share them).
