### ISSUE TITLE
Make sure that unlocking equivocated objects at epoch boundary is cheap

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1839]
We don't prevent people from equivocating their own objects in general. At epoch boundaries, we expect locked objects to be unlocked (i.e. no longer equivocated) so that they can be continue used in the next epoch.
However, we need to make sure that unlocking them is a cheap operation. Otherwise, someone can just equivocate a massive number of objects every epoch which would DDoS our epoch boundary state change.

One idea that @bmwill suggested is that we also store the epoch ID in the transaction lock table. A transaction signed at a new epoch can always override the existing transaction lock from previous epochs. This way we don't have to unlock objects at epoch boundaries. When new transactions in new epochs are sent, they will just override old locks.
cc @gdanezis

**Comment by sblackshear** [comment]
Good callout! Couple of questions:

- This is probably naive, but would it work to simply drop the lock table at epoch boundaries
- In the proposed scheme, will old locks permanently sit in the DB if they are not explicitly overriden?

**Comment by sblackshear** [comment]
This also makes me think about equivocation as a potential DDOS vector--an equivocating attacker can add locks to every authority "for free", and then do it again each epoch.

**Comment by lxfind** [comment]
> * This is probably naive, but would it work to simply drop the lock table at epoch boundaries

Not in the current lock implementation. Today's transaction_lock table not just store transaction locks, but for every object known to the authority it contains an entry (set to None at first, and then to the transaction latter when it's really locked).
I don't quite remember why we need an entry per object here (we already have the objects table). I can ask George about it.

**Comment by lxfind** [comment]
Forgot to ask @gdanezis in our 1:1. 
Any downsides of breaking up the current transactions_lock table into two tables, where one tracks any known object refs, and one tracks refs locked by a transaction?
