### ISSUE TITLE
[Feature][Umbrella] Browser Extension Wallet

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#1849]
## Goal

Building a browser extension based wallet for early adopters and application developers to interact with Sui.

## Timeline
Released to public by TBD (May 20 - 27th)

## POCs
Eng: @pchrysochoidis @666lcz 
PM: @bwann52 
Docs: @Clay-Mysten 

## Design Doc

[go/browser-extension-wallet](http://go/browser-extension-wallet)

## Tasks

- [ ] https://github.com/MystenLabs/sui/issues/2185

**Comment by Clay-Mysten** [comment]
This looks related:
https://github.com/MystenLabs/sui/pull/1845

Trying to figure this out...

**Comment by 666lcz** [comment]
![CleanShot 2022-05-09 at 12 03 38](https://user-images.githubusercontent.com/76067158/167479610-82d88f40-29bb-4df7-8b21-b05b66c90372.png)

@Clay-Mysten  yes, #1845 is mentioned as part of the task as the first step to set up the project. We just kicked off the project and we are still working on the design doc. We will loop you in at the end of next week once we have more details.

**Comment by Clay-Mysten** [comment]
I'm noting we discussed the possibility of encouraging external wallet browser extension development. And if we do so, Pavlos indicated we need to point out the Typescript dependency. I have an outstanding request for @666lcz to see when we can document this:
https://github.com/MystenLabs/sui/issues/1578#issuecomment-1158245951

**Comment by Clay-Mysten** [comment]
Draft here:
https://app.golinks.io/wallet-ext
