### ISSUE TITLE
Remove events subscription sdk documentation

### ISSUE THREAD

**Issue by nikos-terzo** [MystenLabs/sui#18509]
Event websocket subscriptions are going to be deprecated.
The [sdk docs](https://github.com/MystenLabs/sui/blob/5506b09985b53cc6df96937429aed7afe75fed8e/sdk/docs/pages/typescript/sui-client.mdx?plain=1#L60C1-L60C40) should be updated.

I do not know if that is also the case with other web-socket subscriptions (eg. transaction-subscriptions)

**Comment by Jordan-Mysten** [comment]
PR for SDK bits: https://github.com/MystenLabs/sui/pull/18514 @nikos-terzo
