### ISSUE TITLE
Sui Code Bug https://github.com/MystenLabs/sui/tree/main/crates/sui-framework/packages/move-stdlib

### ISSUE THREAD

**Issue by jamesatomc** [MystenLabs/sui#18591]
```shell
sui move build
FETCHING GIT DEPENDENCY https://github.com/MystenLabs/sui.git
Failed to build Move modules: Failed to resolve dependencies for package 'KANARI LAPs'

Caused by:
    0: Parsing manifest for 'Sui'
    1: The system cannot find the path specified. (os error 3).
```

**Comment by stefan-mysten** [comment]
Thanks for reporting this @jamesatomc. There are a few things one can try, but first we'd need a few more details about your setup. 
- what is your CLI version: `sui -V`
- what network are you trying to deploy to: `sui client active-env`
- does your active network that you're trying to deploy to match the framework network set in your Move.toml file?
- can you share your Move toml file?
- you can try to clean the cache in your Move project folder, by removing the Move.lock file and the build directory.

**Comment by jamesatomc** [comment]
Mine is Sui v 1.28.3, even after updating it, 2 weeks ago I still deploy normally.
As for active-evm, I tried changing mainnet back to testnet, but still encountered the same problem.

The move.toml file has intelligence. I tried code that wasn't mine and it still didn't work.

**Comment by jamesatomc** [comment]
Mine is Sui v 1.28.3, even after updating it, 2 weeks ago I still deploy normally.
As for active-evm, I tried changing mainnet back to testnet, but still encountered the same problem.

The move.toml file has intelligence. I tried code that wasn't mine and it still didn't work.

**Comment by stefan-mysten** [comment]
Can you then share just the Sui dependency in your Move.toml file?
`[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }`

**Comment by jamesatomc** [comment]
https://github.com/jamesatomc/token_nft

**Comment by jamesatomc** [comment]
https://github.com/jamesatomc/token_nft

**Comment by jamesatomc** [comment]
my code

**Comment by jamesatomc** [comment]
Yes, I downloaded it from what you gave me, but still found it.

**Comment by stefan-mysten** [comment]
Also works with `v1.28.3`. Which OS are you using?

```
~/s/sa/token_nft  main !191 ?1  ./sui -V                             
sui 1.28.3-3781a7e6b56c
 ~/s/sa/token_nft  main !191 ?1  ./sui move build                    
UPDATING GIT DEPENDENCY https://github.com/MystenLabs/sui.git
INCLUDING DEPENDENCY Sui
INCLUDING DEPENDENCY MoveStdlib
BUILDING kanari
Total number of linter warnings suppressed: 1 (unique lints: 1)
 ~/s/sa/token_nft  main !191 ?2  ./sui move publish '.'              
error: unrecognized subcommand 'publish'

Usage: sui move [OPTIONS] <COMMAND>

For more information, try '--help'.
 ~/s/sa/token_nft  main !191 ?2  ./sui client publish '.'          
UPDATING GIT DEPENDENCY https://github.com/MystenLabs/sui.git
INCLUDING DEPENDENCY Sui
INCLUDING DEPENDENCY MoveStdlib
BUILDING kanari
Total number of linter warnings suppressed: 1 (unique lints: 1)
Successfully verified dependencies on-chain against source.
Transaction Digest: 6BEw138FitYTSqLzu5nn9KLxgw3DewCPVRV1YNVf9L8W
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Transaction Data                                                                                             │
├──────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Sender: 0x90f3e6d73b5730f16974f4df1d3441394ebae62186baf83608599f226455afa7                                   │
│ Gas Owner: 0x90f3e6d73b5730f16974f4df1d3441394ebae62186baf83608599f226455afa7                                │
│ Gas Budget: 53497600 MIST                                                                                    │
│ Gas Price: 1000 MIST                                                                                         │
│ Gas Payment:                                                                                                 │
│  ┌──                                                                                                         │
│  │ ID: 0x0ceaa79e4a6ba0b8df1cd8f769a5c6a22a76c6c5fa87e99f99dee2b8433bd0fc                                    │
│  │ Version: 3857047                                                                                          │
│  │ Digest: CG8yTMYjuF4rksK87W6ptYJjTcpvned9YXJBbi8oK2du                                                      │
│  └──                                                                                                         │
│                                                                                                              │
│ Transaction Kind: Programmable                                                                               │
│ ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │
│ │ Input Objects                                                                                            │ │
│ ├──────────────────────────────────────────────────────────────────────────────────────────────────────────┤ │
│ │ 0   Pure Arg: Type: address, Value: "0x90f3e6d73b5730f16974f4df1d3441394ebae62186baf83608599f226455afa7" │ │
│ ╰────────────────────────────────────────────────────────────────────────────

**Comment by jamesatomc** [comment]
Windows

**Comment by stefan-mysten** [comment]
Ok, so you use Powershell, Command Prompt, WSL, or other kind of terminal?

**Comment by stefan-mysten** [comment]
In principle, Windows has a few issues. One is that long paths are not supported by default, so you might need to enable that if your project sits in a very nested directory (e.g., C:/my_proj/test/new_project/Move_project/test). 

Here's what you can try:
- use Powershell with Administrator support, 
- move your Move project as close as possible to C:\
- delete the .move folder in your project, including any external crates folder, and any Move.lock files
- set longpaths in git: `git config --system core.longpaths true`
- run sui move build --skip-fetch-latest-git-deps

**Comment by jamesatomc** [comment]
Powershell I just ran into this problem today and I can't find it anywhere. I've been looking for the issue but it doesn't come from my machine.

**Comment by stefan-mysten** [comment]
Some folks encountered some similar errors before: https://github.com/MystenLabs/sui/issues/16906 Maybe something from there can help.

**Comment by jamesatomc** [comment]
It seems like this problem has been around since v.1.23, but back then I didn't see it.

**Comment by stefan-mysten** [comment]
I'll try on a Windows machine and see if I can reproduce.

**Comment by jamesatomc** [comment]
The solution is to use aptos move publish and then use sui move build at the beginning.  Why is it willing to download the sui lib? I've just encountered this. I've never had a bug like this before. If sui move build, I'll encounter the same problem.

**Comment by stefan-mysten** [comment]
Sui and Aptos CLIs do different things. They are not compatible. Why are you needing to use aptos move publish?

**Comment by jamesatomc** [comment]
Now it's gone. But in this case I consider it a bug because I haven't seen it since I wrote move sui.

**Comment by jamesatomc** [comment]
Now it's gone. But in this case I consider it a bug because I haven't seen it since I wrote move sui.
