### ISSUE TITLE
How to use sui move prove, I cano't find this subcommand

### ISSUE THREAD

**Issue by DaviRain-Su** [MystenLabs/sui#18718]
```
./sui-macos-arm64 move prove
error: unrecognized subcommand 'prove'

Usage: sui-macos-arm64 move [OPTIONS] <COMMAND>

For more information, try '--help'.
```

sui version is sui 1.21.1-a67a73bc and lastest version 

I am on the manual this https://www.movebit.xyz/blog/post/Move-Prover-Tutorial.html

**Comment by awelc** [comment]
Move prover is currently not available when developing Move contracts for Sui

**Comment by DaviRain-Su** [comment]
> Move prover is currently not available when developing Move contracts for Sui

can i source build move prover？

**Comment by awelc** [comment]
> > Move prover is currently not available when developing Move contracts for Sui
> 
> can i source build move prover？

You probably can but the prover will not support Sui-specific Move language features

**Comment by LeoMansini** [comment]
Hi @DaviRain-Su, were you able to make the move prover work?

**Comment by DaviRain-Su** [comment]
Build source code isn't working!
