### ISSUE TITLE
Install on Intel Mac Fails

### ISSUE THREAD

**Issue by FrankC01** [MystenLabs/sui#1874]
Install failing on macosx 12.3.1 (intel) 
```bash
fastfrank@~ $ cargo --version
cargo 1.60.0 (d1fd9fe2c 2022-03-01)
fastfrank@~ $ rustc --version
rustc 1.60.0 (7737e0b5c 2022-04-04)
```

when I cargo install --locked --git https://github.com/MystenLabs/sui.git --branch "devnet" sui with this error:
```bash
   Compiling tracing-core v0.1.26
   Compiling sharded-slab v0.1.4
   Compiling lock_api v0.3.4
   Compiling thread_local v1.1.4
error: failed to run custom build command for `memchr v2.5.0`

Caused by:
  process didn't exit successfully: `/var/folders/8g/zktzxl7j0gl403x93mn2mhwm0000gn/T/cargo-installYaVQFC/release/build/memchr-1bf6dc88aa0875d2/build-script-build` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `sui v0.1.0 (https://github.com/MystenLabs/sui.git?branch=devnet#94b8089d)`, intermediate artifacts can be found at `/var/folders/8g/zktzxl7j0gl403x93mn2mhwm0000gn/T/cargo-installYaVQFC`
```

**Comment by patrickkuo** [comment]
There are not enough information to workout why this is not working for you, can you try running the commands again with `RUST_BACKTRACE=1`?

Also please make sure you meet all the requirements in [prerequisites](https://docs.sui.io/build/install#prerequisites)

**Comment by longbowlu** [comment]
@FrankC01  can you run `cargo clean` and then the `cargo install` command?

**Comment by FrankC01** [comment]
@longbowlu Run these where? Do you mean after the failed install? What options? Also, for `cargo install` you are saying to run it again?

**Comment by patrickkuo** [comment]
Can you try checkout the project and try install it with the local repo?

`git clone --branch devnet https://github.com/MystenLabs/sui.git`
and then 
`cargo install --locked --path sui/crates/sui`

**Comment by FrankC01** [comment]
@patrickkuo 
```bash
   Compiling libloading v0.7.3
   Compiling instant v0.1.12
   Compiling tracing-core v0.1.26
   Compiling sharded-slab v0.1.4
   Compiling thread_local v1.1.4
error: failed to run custom build command for `parking_lot_core v0.9.3`
```

**Comment by longbowlu** [comment]
@FrankC01  the error message is unfortunately too vague to tell what went wrong. Can you run add `--version` to the command, aka: 
`cargo install --verbose --locked --git https://github.com/MystenLabs/sui.git --branch "devnet" sui` 

and paste the output?

**Comment by FrankC01** [comment]
@longbowlu 
[sui_out.txt](https://github.com/MystenLabs/sui/files/8889844/sui_out.txt)

Ran with:
`RUST_BACKTRACE=1 cargo install --verbose --locked --git https://github.com/MystenLabs/sui.git --branch "devnet" sui`

Results attached

**Comment by FrankC01** [comment]
@longbowlu Any insight from the run I did as you requested?

**Comment by FrankC01** [comment]
@longbowlu I haven't been checking for every release but I was able to successfully install devnet with the `0.6.1` release.
