### ISSUE TITLE
【TS-SDK】 (0 , import_valibot.string) is not a functio

### ISSUE THREAD

**Issue by devlb1024** [MystenLabs/sui#18750]
In the react project, "@mysten/sui": "^1.3.0" is referenced. After npm run start, the following error occurs:

ERROR
(0 , import_valibot.string) is not a function
TypeError: (0 , import_valibot.string) is not a function
    at ./node_modules/@mysten/sui/dist/cjs/transactions/data/internal.js (http://localhost:3000/static/js/bundle.js:228763:71)
    at options.factory (http://localhost:3000/static/js/bundle.js:413666:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:413050:32)
    at fn (http://localhost:3000/static/js/bundle.js:413324:21)
    at ./node_modules/@mysten/sui/dist/cjs/transactions/Commands.js (http://localhost:3000/static/js/bundle.js:227543:23)
    at options.factory (http://localhost:3000/static/js/bundle.js:413666:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:413050:32)
    at fn (http://localhost:3000/static/js/bundle.js:413324:21)
    at ./node_modules/@mysten/sui/dist/cjs/transactions/index.js (http://localhost:3000/static/js/bundle.js:230475:23)
    at options.factory (http://localhost:3000/static/js/bundle.js:413666:31)

**Comment by hayes-mysten** [comment]
Can you provide some details on how you are building your app?  It looks like whatever you are using to build your app isn't properly including the valibot package.   There are a lot of different bundlers with various methods for handling module resoution.

Without more details about your specific setup it will be hard to figure out whats going in.

**Comment by fum-is-chum** [comment]
Have you try adding `"valibot": "^0.36.0"` to your dependencies? @devlb1024

**Comment by theosudofi** [comment]
Seeing the same issue with our frontend app - we do have valibot at 0.36.0 in our yarn.lock

**Comment by hayes-mysten** [comment]
can you share what you are using to build/bundle your app code?  We haven't been able to reproduce this issue, and there isn't enough information in this issue to get a good idea of what might be going wrong

**Comment by theosudofi** [comment]
we are using webpack:

```
    "webpack": "^5.64.4",
 ```

the build function is pretty straightforward
```
// Create the production build and print the deployment instructions.
function build(previousFileSizes) {
  console.log('Creating an optimized production build...');

  const compiler = webpack(config);
  return new Promise((resolve, reject) => {
    compiler.run((err, stats) => {
      let messages;
      if (err) {
        if (!err.message) {
          return reject(err);
        }

        let errMessage = err.message;

        // Add additional information for postcss errors
        if (Object.prototype.hasOwnProperty.call(err, 'postcssNode')) {
          errMessage +=
            '\nCompileError: Begins at CSS selector ' +
            err['postcssNode'].selector;
        }

        messages = formatWebpackMessages({
          errors: [errMessage],
          warnings: [],
        });
      } else {
        messages = formatWebpackMessages(
          stats.toJson({ all: false, warnings: true, errors: true }),
        );
      }
      if (messages.errors.length) {
        // Only keep the first error. Others are often indicative
        // of the same problem, but confuse the reader with noise.
        if (messages.errors.length > 1) {
          messages.errors.length = 1;
        }
        return reject(new Error(messages.errors.join('\n\n')));
      }
      if (
        process.env.CI &&
        (typeof process.env.CI !== 'string' ||
          process.env.CI.toLowerCase() !== 'false') &&
        messages.warnings.length
      ) {
        // Ignore sourcemap warnings in CI builds. See #8227 for more info.
        const filteredWarnings = messages.warnings.filter(
          w => !/Failed to parse source map/.test(w),
        );
        if (filteredWarnings.length) {
          console.log(
            chalk.yellow(
              '\nTreating warnings as errors because process.env.CI = true.\n' +
                'Most CI servers set it automatically.\n',
            ),
          );
          return reject(new Error(filteredWarnings.join('\n\n')));
        }
      }

      const resolveArgs = {
        stats,
        previousFileSizes,
        warnings: messages.warnings,
      };

      if (writeStatsJson) {
        return bfj
          .write(paths.appBuild + '/bundle-stats.json', stats.toJson())
          .then(() => resolve(resolveArgs))
          .catch(error => reject(new Error(error)));
      }

      return resolve(resolveArgs);
    });
  });
}
```

**Comment by theosudofi** [comment]
We found out why, it's a webpack issue. valibot is compiled to .cjs format. Our webpack rule didn't cover cjs file.

```
              test: /\.(js|mjs|cjs)$/,
```

adding it to the test regex fixed it.

**Comment by hayes-mysten** [comment]
nice! glad you got it figured out
