### ISSUE TITLE
sui-data-ingestion-core is completely stuck on some specific checkpoints

### ISSUE THREAD

**Issue by piavgh** [MystenLabs/sui#18773]
## Steps to Reproduce Issue

Fill this in with the concrete steps needed to reproduce the bug. When providing code in the reproduction steps, use the smallest snippet of code that demonstrates the issue, removing any extraneous details.

EDIT: I added a video here for better understanding: https://go.screenpal.com/watch/cZiZn2VPvFh

1. Set up your project to use `sui-data-ingestion-core`, similar to the `suins-indexer` crate here https://github.com/MystenLabs/sui/tree/main/crates/suins-indexer

2. Implement Worker trait for your struct
```
#[async_trait]
impl Worker for TokenUtilityIndexerWorker {
    async fn process_checkpoint(&self, checkpoint: CheckpointData) -> Result<()> {
        let checkpoint_seq_number = checkpoint.checkpoint_summary.sequence_number;

        // every 1000 checkpoints, we will print the checkpoint sequence number
        // to the console to keep track of progress
        if checkpoint_seq_number % 1000 == 0 {
            info!("Checkpoint sequence number: {}", checkpoint_seq_number);
        }
        
        // check if the checkpoint sequence number is in the list of custom checkpoints and the checkpoint is smaller than the last checkpoint
        // if !self.custom_checkpoints.is_empty() && !self.custom_checkpoints.contains(&checkpoint_seq_number) && checkpoint_seq_number <= self.custom_checkpoints.last().unwrap().clone()
        // {
        //     return Ok(());
        // }

        self.indexer.process_checkpoint(&checkpoint).await;

        Ok(())
    }
}
```

3. Set a custom checkpoint in file `backfill_progress`, for example, I found some broken checkpoints:
- 89932453
- 89932746
- 89934246
- maybe there is more

4. Run your indexer

## Expected Result

I expect the indexer to continue to index further checkpoints

## Actual Result

The indexer is stuck there forever

## System Information

* OS: I tried 3 environments: my local machine (Mac OS 14.5), and 2 deployments on fly.io. The Dockerfile for fly.io is:
```
FROM lukemathwalker/cargo-chef:latest-rust-1 AS chef
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        libclang-dev
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json
# Build application
COPY . .
RUN cargo build --release --bin token-utility-indexer

# We do not need the Rust toolchain to run the binary!
FROM debian:bookworm-slim AS runtime
WORKDIR /app
COPY config config
COPY tmp tmp
COPY --from=builder /app/target/release/token-utility-indexer /usr/local/bin
ENTRYPOINT ["/usr/local/bin/token-utility-indexer"]
```

* Compiler: <specify compiler version>
➜ rustc --version           
rustc 1.81.0-nightly (d9284afea 2024-07-14)

**Comment by fl0ydj** [comment]
Not sure if related but for some checkpoints I have been getting ```remote reader transient error invalid value: integer 4, expected variant index 0 <= i < 4``` resulting in the indexer being stuck there

**Comment by phoenix-o** [comment]
> Not sure if related
@fl0ydj: please rebase on top of main. There are some changes in the sui core codebase. Indexer needs to be updated too

**Comment by phoenix-o** [comment]
> I found some broken checkpoints

Can you elaborate a little bit more what do you mean by broken checkpoint? What do you see?
Also is it mainnet or testnet?

**Comment by piavgh** [comment]
> Can you elaborate a little bit more what do you mean by broken checkpoint? What do you see?
> Also is it mainnet or testnet?

I captured a video here: https://go.screenpal.com/watch/cZiZn2VPvFh

Broken checkpoint = checkpoint that makes the indexer stuck forever

**Comment by piavgh** [comment]
I tried to add a breakpoint in the worker_pool.rs and it seems that it is stuck forever in this loop
![image](https://github.com/user-attachments/assets/499c83df-1372-47d9-93ca-1943fd87151d)

**Comment by piavgh** [comment]
The process does not stop at any of these checkpoints
![image](https://github.com/user-attachments/assets/6078aa09-2c14-4ee1-ac89-fb861860655e)

**Comment by phoenix-o** [comment]
I just ran the following gist locally and it passes for the checkpoint 89932453: https://gist.github.com/phoenix-o/cf8832ef05b476c264c88634fa5523db.
Also checkpoint 89932453 is not that big. It's ~80kb

**Comment by piavgh** [comment]
> I just ran the following gist locally and it passes for the checkpoint 89932453: https://gist.github.com/phoenix-o/cf8832ef05b476c264c88634fa5523db. Also, checkpoint 89932453 is not that big. It's ~80kb

It's weird, you can check my video, it is just stuck there.

By the way, if I'm using this in my Cargo.toml:
```
sui_data_ingestion_core = { git = "https://github.com/mystenlabs/sui", package = "sui-data-ingestion-core" }
```
Does it mean it will always get the latest version?

**Comment by phoenix-o** [comment]
worker pool breakpoints might not help in case if checkpoint's never fetched by the reader. 
Is there anything in the reader logs? For example: https://github.com/MystenLabs/sui/blob/8169f0529f477c52a2565404e406a70ce3aefa8e/crates/sui-data-ingestion-core/src/reader.rs#L228

**Comment by piavgh** [comment]
> worker pool breakpoints might not help in case if checkpoint's never fetched by the reader. Is there anything in the reader logs? For example:
> 
> https://github.com/MystenLabs/sui/blob/8169f0529f477c52a2565404e406a70ce3aefa8e/crates/sui-data-ingestion-core/src/reader.rs#L228

This is what I have in log:
![image](https://github.com/user-attachments/assets/35277461-c9bf-4aaa-b9c4-41330fff58d1)

**Comment by phoenix-o** [comment]
you can play with breakpoints in the reader.
That line is noisy, you can filter it out, but basically it means that checkpoint 89932453 was never fetched by the reader.
I wonder if it's getting negatively cached somehow between the bucket and your process.
Side question: do you have a FN that you operate?

**Comment by piavgh** [comment]
> Side question: do you have a FN that you operate?
No, I just connect directly to the remote storage at `https://checkpoints.testnet.sui.io`, and my indexer relies only on the remote storage, there is no full node

Let me try to debug in the reader

**Comment by piavgh** [comment]
> I wonder if it's getting negatively cached somehow between the bucket and your process

Can you please show me the code where is this caching mechanism is?

**Comment by phoenix-o** [comment]
The reason I ask, is that alternatively you can utilize a sufficiently unpruned FN if you have temporary issues with https://checkpoints.testnet.sui.io bucket.
The url can be changed to `https://<address_of_fn>:<port>/rest` if you have your own FN.

There's no caching logic in the data ingestion itself. That was just a speculation about networking stack on your machine. Maybe try to flush local DNS caches.

But try to debug this function https://github.com/MystenLabs/sui/blob/8169f0529f477c52a2565404e406a70ce3aefa8e/crates/sui-data-ingestion-core/src/reader.rs#L108

**Comment by piavgh** [comment]
@phoenix-o : I found the reason
It seems that in my Cargo.lock, I'm using an older version of sui-data-ingestion-core (https://gist.github.com/piavgh/0a1b60ed46d0a2123f2a00f6bc23fef3#file-cargo-lock-L6314 (commit at June 12th, 2024)
```
[[package]]
name = "sui-data-ingestion-core"
version = "0.1.0"
source = "git+https://github.com/mystenlabs/sui#7e33c3f4d4fb59ead85118b2b04ef95ec08f1bae"
```

After deleting the `Cargo.lock` and `/target` folder and rerun the app, it works properly now

There are too many commits from 12/06/2024 until now so I can not detect which commit fixed this issue, but thanks to that person anyway

**Comment by phoenix-o** [comment]
happy to hear it's fixed!

**Comment by piavgh** [comment]
@phoenix-o : this issue happened yesterday at checkpoint 82306070

**Comment by phips28** [comment]
This happens to me almost every second day. currently I see these 2 logs over and over again (with those exact checkpoints):
```
4|sui-indexer  | 2024-11-29T18:20:43.820613Z  INFO sui_data_ingestion_core::reader: Read from remote. Current checkpoint number: 85102994, pruning watermark: 85102873, new updates: 0
4|sui-indexer  | 2024-11-29T18:20:43.821886Z  INFO sui_data_ingestion_core::reader: Read from remote. Current checkpoint number: 85101745, pruning watermark: 85101574, new updates: 0
```

How to fix it?

**Comment by piavgh** [comment]
> Sui full node stuck on checkpoints #18901

Now it also happens on testnet for me (again)

**Comment by georgegoldman** [comment]
@piavgh please can you share your source code for your implementation especially the main.rs?
