### ISSUE TITLE
[Urgent] Enoki Typescript SDK Types Missing

### ISSUE THREAD

**Issue by djpimp2010** [MystenLabs/sui#18838]
When using the Enoki SDK (with react hooks), the function `enokiFlow.createAuthorizationURL` only accepts a small number of providers, instead of the full list on the Enoki docs site.

Can the typescript types please be updated to include "apple" as a provider? (and preferably the missing providers specified in Enoki Docs)

```
import { useEnokiFlow, useZkLogin } from "@mysten/enoki/react";

const EnokiSSO: FC<EnokiSSOProps> = ({...}) => {

  const enokiFlow = useEnokiFlow();
  const { address: suiAddress } = useZkLogin();

  const redirect_to = await enokiFlow.createAuthorizationURL({
    provider: "google", // No Apple listed as type
    ...otherArgs,
  });
}
```

**Comment by Jordan-Mysten** [comment]
The `EnokiFlow` class doesn't support the `apple` provider since Sign in with Apple does not support redirecting with the JWT directly. We're looking into building support into Enoki to manage this for you, but don't yet have an ETA.

**Comment by djpimp2010** [comment]
OK Thank you for the update :)

**Comment by djpimp2010** [comment]
OK I have a solution as I have managed to get Enoki to use Apple as an SSO provider, and successfully received a wallet address.

Apple have followed the OAuth OpenID specs, even though they don't use that terminology in their docs.

I forked the SUI repo and modded the Enoki SDK to allow apple (with some subtle changes to match their API) and sure enough, they let us SSO and return a code. Ordinarily the SSO provider would turn this into a JWT and do a redirect, but Apple don't. So I set up a simple API endpoint to capture the Apple SSO Auth Code and then hit their API to turn it into a JWT.

I have managed to get Enoki to use Apple SSO to create a wallet for users!!

I believe you should amend the SDK to match my amendments, to allow Apple as a provider, and then add to the docs an explanation of the extra endpoint the devs need to add, to catch the apple code and then request a JWT that can be used for redirection using the `#id_token=xyz.jwt.sig` format

Developers integrating Enoki must create API endpoints to interact with the SDK and its responses.

There is nothing stopping us from explaining how adding one more endpoint during integration can make Apple work.

**Comment by djpimp2010** [comment]
If you find the file `sdk/enoki/src/EnokiFlow.ts` you can modify it as follows

The definition for the type `AuthProvider` can be changed to match
`export type AuthProvider = 'google' | 'facebook' | 'twitch' | 'apple';`

In the function `EnokiFlow.createAuthorizationURL` you can amend the `URLSearchParams.scope` from `'openid',` to `input.provider === 'apple' ? '' : 'openid',`
This will stop the SDK from sending the scope `openid` with the apple URL request - they don't like that param

And then in the same function, there is a `switch()` statement to define the specific URLs for each provider.
You can add this:
```
			case 'apple': {
				params.set('response_mode', 'form_post');
				params.set('response_type', 'code');
				oauthUrl = `https://appleid.apple.com/auth/authorize?${params}`;
				break;
			}
```
and it will allow a URL to be crafted, that will do the correct redirect to Apple's SSO service

Here's the tricky part... Enoki expects the SSO provider to return to the `redirectUrl` with a JWT, using the URL hash parameter `https://domain.com/url-to-reach#id_token=<jwt>`

Apple does not complete the circle like Google does, and leaves you hanging with an OpenID Code.

A developer integrating with Enoki must set up at least one API endpoint to capture/handle some data - we need dev's on this anyway.

If the API has another endpoint created `eg: /sso/apple/return` then the Enoki SDK can be instructed to set the `redirectUrl` to hit the system API, with the OpenID code, and then hit the Apple API for changing that code into a JWT that can then be used by Enoki.

The API emits some javascript code along the lines of
```
  <script type="text/javascript">
    window.location.href = "https://<%= data.host %>/login#id_token=<%= data.jwt %>";
  </script>
```
which will then redirect the user to the react project that houses the code to capture the `#id_token` from the URL and parse the JWT to return a wallet address from zkLogin endpoint

It does work - yes, Apple have odd specs about their OpenID input and outputs, but a simple snippet of code can turn the Apple SSO return `code` string into a JWT that Enoki can handle

```
npm install apple-signin-auth

code:

const appleSignin = require("apple-signin-auth");

const privateKey = fs.readFileSync(`${dir}//AuthKey_ABC123XYZ.p8`, "utf-8");

const clientSecret = appleSignin.getClientSecret({
  clientID: env.APPLE.client_id, // Apple Client ID
  teamID: env.APPLE.team_id, // Apple Developer Team ID.
  privateKey, // private key associated with your client ID. -- Or provide a `privateKeyPath` property instead.
  keyIdentifier: env.APPLE.key_id, // identifier of the private key.
  // OPTIONAL
  expAfter: 15777000, // Unix time in seconds after which to expire the clientSecret JWT. Default is now+5 minutes.
});

const options = {
  clientID: env.APPLE.client_id, // Apple Client ID
  redirectUri: ` /sso/apple/return`, // use the same value which you passed to authorisation URL.
  clientSecret: clientSecret,
};

const tokenResponse = await appleSignin.getAuthorizationToken(postData.code, options);

// do stuff with tokenResponse
```

**Comment by djpimp2010** [comment]
Apple followed the OpenID standards **to the letter**, which means they allow us to submit a nonce in the URL for initialising OAuth. That's why the zkLogin concept can then continue at the end of the flow - because the custom nonce is returned in the JWT and can be verified.
