### ISSUE TITLE
Compilation Error: Type Annotations Needed for Box<_>

### ISSUE THREAD

**Issue by nova032** [MystenLabs/sui#18868]
## Description:
While attempting to compile the Sui project from the testnet branch, I encountered a type annotation error in the time crate. This error prevents successful compilation of the project.

```shell
error[E0282]: type annotations needed for `Box<_>`
  --> /home/nova/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.31/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++
```
## Steps to Reproduce
1. Update Rust to the latest version using `rustup update`.
2. run this `cargo install --locked --git https://github.com/MystenLabs/sui.git --branch testnet sui`
3. time-0.31.1 version

**Comment by stefan-mysten** [comment]
Thanks for reporting this @nova032. We'll have a look.

**Comment by chenrui333** [comment]
relates to https://github.com/time-rs/time/issues/693 just update to use time 0.3.36 should be good.

**Comment by chenrui333** [comment]
@nova032 @stefan-mysten this can be closed now. 

https://github.com/MystenLabs/sui/blob/23ee1e84a5859154084c5c80f52aae3233fce269/Cargo.lock#L15746-L15748
