### ISSUE TITLE
Configure and link to custom domain for Sui rustdoc

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#1887]
Following up on:
https://github.com/MystenLabs/sui/pull/1878

Francois suggests we employ a custom domain for:
https://mystenlabs.github.io/sui/
Which is now public and linked from:
https://docs.sui.io/build/install
https://docs.sui.io/contribute

Or rather will be after these are pushed to prod:
https://github.com/MystenLabs/sui/pull/1881
https://github.com/MystenLabs/sui/pull/1880

I've announced the update at go/mysten and am doing so publicly in:
https://github.com/MystenLabs/sui/pull/1886

Francois suggests we follow:
https://docs.github.com/en/enterprise-cloud@latest/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

Specifically:
1. We need to loop in whomever can set up a CNAME on our domain, ([@Kostas Chalkias](https://mysten-labs.slack.com/team/U02CZMXNJ6M)?)
2. There's 1 setting change to do on Github to link the pages to the subdomain ( founders, [@brandon](https://mysten-labs.slack.com/team/U038HV6ARSR) and myself can help)
3. The doc page is https://docs.github.com/en/enterprise-cloud@latest/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain

Once done, I will update links above to go directly to and reveal inline the custom domain. Thanks, all.

**Comment by Clay-Mysten** [comment]
Other background:
https://github.com/MystenLabs/mysten-infra/pull/71

**Comment by randall-Mysten** [comment]
Closing this issue. These changes are included in the site overhaul
