### ISSUE TITLE
Sui client publish (windows) error

### ISSUE THREAD

**Issue by 404ll** [MystenLabs/sui#18894]
sui move build succeed
but 
sui client publish
Committing lock file

Caused by:
    0: failed to persist temporary file: 拒绝访问。 (os error 5)
    1: 拒绝访问。 (os error 5)

**Comment by 404ll** [comment]
I have updated the new version of testnet.

**Comment by stefan-mysten** [comment]
@404ll Thanks for the report.

**Comment by 404ll** [comment]
> @404ll感谢您的报告。它是否在任何 Move 项目上都失败了，还是仅在特定项目上失败了？如果您尝试在其中一个示例中使用它`sui/examples/move`，它会成功吗？
> 在我之前部署成功过的所有项目上都失败了，目前切换到开发网可以成功部署。
> 另外，您有哪个版本`v1.30.1`？
testnet V 1.30.1-windows-x86 64.tgz

**Comment by stefan-mysten** [comment]
I see you are on Windows. What terminal do you use? Can you try the same thing using PowerShell in Admin mode?

**Comment by 404ll** [comment]
> 我看到您使用的是 Windows。您使用什么终端？您可以在管理员模式下使用 PowerShell 尝试同样的事情吗？

我使用的是powshell，采用过管理员模式，但是仍然不行；我采取了别人的建议“删除move.lock文件”，问题就解决了。

**Comment by stefan-mysten** [comment]
The `Move.lock` file was the culprit somehow. Deleting it resolved the issue.
