### ISSUE TITLE
'std::option' uses 'std::vector'. This 'use' relationship creates a dependency cycle.

### ISSUE THREAD

**Issue by shismart-cool** [MystenLabs/sui#18920]
## Steps to Reproduce Issue
create a move project and write:
```
module hello_move::hello_move {
    use std::ascii::{String, string};
    use sui::object::{Self,UID};
    use sui::transfer::transfer;
    use sui::tx_context::{TxContext, sender};

    public struct Hello has key{
        id:UID,
        say: String
    }

    fun init(ctx: &mut TxContext) {
        let hello_move = Hello {
            id:object::new(ctx),
            say: string(b"shismart-cool"),
        };
        transfer(hello_move, sender(ctx));
    }
}
```
run :sui client publish --gas-budget 100000000
it will report error:
error[E02004]: invalid 'module' declaration
    ┌─ /Users/.move/https___github_com_MystenLabs_sui_git_framework__testnet/crates/sui-framework/packages/move-stdlib/sources/vector.move:241:74
    │
241 │     public macro fun find_index<$T>($v: &vector<$T>, $f: |&$T| -> bool): Option<u64> {
    │                                                                          ^^^^^^^^^^^ 'std::option' uses 'std::vector'. This 'use' relationship creates a dependency cycle.
    │

**Comment by Bridgerz** [comment]
The fix for this should be in main already.

**Comment by stefan-mysten** [comment]
Please update your Sui CLI from the releases page https://github.com/MystenLabs/sui/releases
The `brew` package manager does not have the latest release yet.
