### ISSUE TITLE
Enum match statement STLOC_TYPE_MISMATCH_ERROR 

### ISSUE THREAD

**Issue by alexanderludwig** [MystenLabs/sui#18946]
## Steps to Reproduce Issue

The following code does not work:

```

public enum Proposal has store, copy, drop {
        ConfigProposalQuorum {approved: vector<u16>, rejected: vector<u16>},
        MpcTxProposalQuorum {approved: vector<u16>, rejected: vector<u16>},
        MpcTxProposalSpecific {require_approval_users: vector<u16>, threshold: u16, approved: vector<u16>, rejected: vector<u16>},
    }

  public(package) fun is_proposal_approved(proposal: &Proposal, users: &Users): bool{
      match (proposal) {
          Proposal::ConfigProposalQuorum{approved: approved, rejected: _} => {
              users.quorum_approves(approved)

          },
          Proposal::MpcTxProposalQuorum{approved:approved, rejected:_} => {
              users.quorum_approves(approved)
          },
          Proposal::MpcTxProposalSpecific{require_approval_users:_, threshold:threshold, approved: approved, rejected:_} => {
              
              // this does not work
              ((approved.length() as u16) >= *threshold)
              // this works
              // true
          }
      }
  }

```

Also getting the same error in another match block where matching some specific variants returns the same issue. Though there are no return types involved. Happy to give access to our codebase to reproduce this to whoever is working on this. 

## Expected Result

-
## Actual Result

Failed to verify the Move module, reason: "VMError with status STLOC_TYPE_MISMATCH_ERROR at location Module ModuleId { address: 0000000000000000000000000000000000000000000000000000000000000000, name: Identifier(\"proposal\") } at index 4 for function definition at code offset 44 in function definition 4". 

## System Information

mainnet-v1.30.1

**Comment by cgswords** [comment]
Thank you for the bug report. #18947 should fix it as expected
