### ISSUE TITLE
Pruning is enabled on your public GraphQL endpoint

### ISSUE THREAD

**Issue by artem-staked** [MystenLabs/sui#19045]
Since  `17.08.2024` (probably a bit earlier) it seems pruning has been enabled on https://sui-mainnet.mystenlabs.com/graphql

On `16.08.2024` I was able to get data for any epoch. For example, this simple query would work 
`{
  epoch(id: 0) {
    epochId
  }
}`

On `18.08.2024 18:07` I've posted on the Discord that I see data only starting from epoch 23

Now `20.08.2024 13:37` I can get data only starting from epoch 31.

Is it intentional or something went wrong? It looks like pruning works faster then new epochs are being added

**Comment by amnn** [comment]
Hi @artem-staked, yes pruning was enabled on this version of the database, so this is expected. The pruning target is 30 days, so that is why you are seeing pruning progressing faster than new epochs are added.
