### ISSUE TITLE
Transaction timed out

### ISSUE THREAD

**Issue by daihaojun554** [MystenLabs/sui#19068]
Debugger attached.
0x215ab9f946eb9568fc06d4d3d6f38c958e40170628f5999bdd750ef1464c04c4 sendTx error. error: Error: Transaction timed out before reaching finality

**Comment by stefan-mysten** [comment]
Hi @daihaojun554. Thanks for the report. Can you specify more information about this failed transaction? Which network? From which geographical location was this run? How did you run this transaction, via TS SDK, Rust SDK, CLI, other?
