### ISSUE TITLE
Sui CLI move build option

### ISSUE THREAD

**Issue by daoauth** [MystenLabs/sui#19114]
It's not a bug, but it would be great if there was an option to save the output to a file when running `sui move build --dump-bytecode-as-base64`. 

For example, to be able to save it like this:

```bash
sui move build --dump-bytecode-as-base64 bytecode.json
```

If no parameter is given, it would work as it currently does.

**Comment by manolisliolios** [comment]
hey @daoauth ,
You could theoretically pipe to an output file like this
```
sui move build --dump-bytecode-as-base64 > bytecode.json
```

Given that it is do-able that way, I am not certain a custom option in the CLI would add a lot of value, but I'll defer to @stefan-mysten for more thoughts on this!

**Comment by stefan-mysten** [comment]
A command for this seems like an overkill here, but we'll consider it for the future!
