### ISSUE TITLE
Sui_tryGetFastObject cannot view past versions of objects

### ISSUE THREAD

**Issue by Gessi12** [MystenLabs/sui#19116]
The current version and previousTransaction
![image](https://github.com/user-attachments/assets/5dc4a246-67f3-4b65-a982-d9637fa6bed6)

Previous version
![image](https://github.com/user-attachments/assets/08a56f62-5b2c-4e15-8e97-1ecece61c034)

You can view information using the current version
![image](https://github.com/user-attachments/assets/5a60da41-784e-436a-a6cc-c8e960da0dc9)

Cannot view information using the previous version
![image](https://github.com/user-attachments/assets/c683acb5-d717-4bed-8c3f-fa6a793f0591)

But I was able to succeed a while ago, but now I have tried several examples but have failed

**Comment by manolisliolios** [comment]
Hey @Gessi12 , that seems to be pruning related. 

The FN-backed or indexer-backed RPCs prune historical objects to reduce storage (each node could have its own custom pruning policy set). On a non-pruned node you'd expect these to return results indeed!

**Comment by Gessi12** [comment]
@manolisliolios 
Yes, I used other nodes and some of them were successful
