### ISSUE TITLE
Sir, How to get data from Mempool ?

### ISSUE THREAD

**Issue by MrReN** [MystenLabs/sui#19206]
When a user initiates a transaction, and it has been submitted to the blockchain but is not yet completed, is there a way to listen for or query it? For example, can it be queried from the Mempool? Is there a way to retrieve data for transactions in the pending state?

**Comment by nonvis** [comment]
@MrReN `sui_getTransactionBlock` can be called from a full node [Ref: https://docs.sui.io/sui-api-ref#sui_gettransactionblock] and if you use typescript, `client.waitForTransaction` can be used [Ref: https://sdk.mystenlabs.com/typescript/sui-client#waitfortransaction].

I think this question is not really suitable to ask in GH `Issues`. Could your direct inquiries to https://forums.sui.io/ for the future?
