### ISSUE TITLE
Passing Enum as parameter to method fails in txb

### ISSUE THREAD

**Issue by majoson-chen** [MystenLabs/sui#19269]
## Steps to Reproduce Issue

I defined an Enum in the contract, and encountered an error when passing in a public fun with `txb`

<img width="591" alt="image" src="https://github.com/user-attachments/assets/434d7d17-1fa8-4fa6-8e8b-8a24744a5e9e">

<img width="835" alt="image" src="https://github.com/user-attachments/assets/91243da8-70bc-4afd-bba9-be7d1091240f">

<img width="670" alt="image" src="https://github.com/user-attachments/assets/0c633160-61a5-4e2f-84c5-654e9a69560f">

<img width="731" alt="image" src="https://github.com/user-attachments/assets/c348ede2-c8cc-42ef-8eda-0703d71487bf">

## actual result
<img width="1572" alt="image" src="https://github.com/user-attachments/assets/db0f5d42-dfec-4517-91a3-7b28d0391292">

Can I pass an enum as a parameter to tx in txb? Or is this a bug?

## System Information

* os: MacOS Sonoma
* sui 1.32.0-homebrew
* ts-sdk: 1.8.0

**Comment by hayes-mysten** [comment]
Enums can't be passed into PTBs as pure values.  They can only be passed as results from other move calls

**Comment by tedks** [comment]
This is also the case for struct values, and both are not likely to be supported for the foreseeable future.

**Comment by majoson-chen** [comment]
thanks!
