### ISSUE TITLE
Stream shared-object certificates into consensus

### ISSUE THREAD

**Issue by asonnino** [MystenLabs/sui#1930]
The following function is blocking: it submits a transaction to consensus and then waits for a reply.
https://github.com/MystenLabs/sui/blob/a9943f7b8414d3fd9a4298aa0cec2ddc0e015899/sui_core/src/consensus_adapter.rs#L100-L103

We could instead make it accept a stream of certificates and return responses to the client as they are sequenced.

**Comment by gdanezis** [comment]
Wait a second, does that mean that we can only have a number of shared object transactions in flight equal to the number of cores / threads in the tokio runtime? Once they are all blocked, the whole runtime will block no? Is this not a liveness issue?

**Comment by asonnino** [comment]
Yes, we can have one shared-objects transaction  in flight per tokio task. I think it is the same for single-owner transactions, right? The difference is that shared-objects transactions take longer and so TPS is degraded if we don’t fix this issue. I would call it a perf issue rather than a lives issue, am I missing something?

**Comment by gdanezis** [comment]
hey @asonnino -- I think that this is not an issue any more right? As in this is no more a blocking but an async interface right?

**Comment by asonnino** [comment]
I think it is still an issue, the current interface at authority-server doesn't allow streaming. It is not a fundamental issue in the sense that the core can stream into consensus with no problems (eg. we stream checkpoints fragments and tx retries).

**Comment by stefan-mysten** [comment]
@asonnino is this still relevant?

**Comment by asonnino** [comment]
Not anymore
