### ISSUE TITLE
Graphql request speed issues

### ISSUE THREAD

**Issue by fovz** [MystenLabs/sui#19354]
Prior to September 4, graphql requests could be returned in less than a second,but now a request takes about four seconds.

I would like to know why this is happening, and is there any consideration to improve the situation, which is troubling me.

**Comment by stefan-mysten** [comment]
Sorry to hear you have troubles with GraphQL queries. Could you please share a query that used to be fast and now is slow?

**Comment by fovz** [comment]
I use this GraphQL query to obtain information for every block (both the testnet and mainnet)
`const chainIdentifierQuery = graphql(`
      query {
        checkpoint(id: { sequenceNumber: 41520104}) {
          digest
          sequenceNumber
          timestamp
          transactionBlocks(
            first:10,
            filter: {
              kind: "PROGRAMMABLE_TX",
            }
          ){
            pageInfo {
              endCursor
              hasNextPage
            }
            edges {
              node {
                digest
                sender {
                  address
                }
                gasInput {
                  gasPrice
                  gasBudget
                }
                effects {
                  status
                  gasEffects {
                    gasSummary {
                      computationCost
                      storageCost
                      storageRebate
                      nonRefundableStorageFee
                    }
                  }
                  balanceChanges {
                    edges {
                      node {
                        owner {
                          address
                        }
                        coinType {
                          repr
                        }
                        amount
                      }
                    }
                  }
                }
                kind {
                  __typename
                  ... on ProgrammableTransactionBlock {
                    inputs {
                      edges {
                        node {
                          __typename
                          ... on Pure {
                            bytes
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    `);
      const result = await suiGraphQLClient.query({
        query: chainIdentifierQuery,
        variables: undefined,
      });`

**Comment by stefan-mysten** [comment]
Thanks for sharing. This returns almost instant for me (US based), so I wonder if it is an issue on other nodes. What area (US, EU, Asia) are you calling this query from?

**Comment by fovz** [comment]
From Ireland

**Comment by stefan-mysten** [comment]
@fovz the reason you see a longer time to resolve the query is that we no longer have DBs for each region, and all requests are served by a DB that is in the US.
