### ISSUE TITLE
Explorer: Frontend Redesign Scoping

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#1948]
We will onboard a design agency soon to do a design revamp(desktop + mobile)

- [x] Home 
  - [x] Header & footer (Andrew, 0.5 weeks)
  - [x] transactions (0.5 week)
  - [ ] validators table (Stella, 2 day)
  - [ ] validator map (Ge, 2 day)
- [x] Transactions (Godwin, 1 week)
  - [x] TransferObject/TransferSui
  - [x] Move Call
  - [x] Publish
  - [ ] Batch Transaction
  - [ ] Change Epoch
- [x] Addresses (Andrew, 0.5 week)
- [ ] Package view (Andrew, 1 week)
- [ ] Move Object View (Andrew, 0.5 for layout, 0.5 for (optional) highlighting)
- [ ] Validator detailed view (Stella, 2~3 days)
- [ ] Staking (Stella, 1 week?)
- [ ] Search results (0.5 week?)
- [ ] Epochs view (~1 week?)
- [ ] Checkpoint view (Stella, ~0.5 week?)
- [ ] showing events in transaction detail page (Stella, 0.5 week)

**Comment by 666lcz** [comment]
We should discuss about feature gating

**Comment by Andrew47** [comment]
The following are the tasks required to implement the design as it currently stands. Note the time calculations are rough approximations.

* CSS Changes (each task 1/2 week):
    * New typefaces
    * Header and Footer
    * Network switch 
    * Transaction Results

* CSS and JavaScript Changes (each task 1 week):
    * Pop-out image on click present in transaction and object results
    * Transaction Tables across Home, Object and Address Results. User clicks to go to new page to see more transactions info.
    * Address Results have new layout with total NFT count

Considering that we can parallel-track, overall this is likely to take 2-4 weeks.
