### ISSUE TITLE
How to consolidate multiple transactions into one transaction

### ISSUE THREAD

**Issue by qxyanda** [MystenLabs/sui#19607]
For example, the following code:

```
import { AggregatorClient, Env } from "@cetusprotocol/aggregator-sdk";

      const routerTxBuy = new Transaction()
      const routerTxSell = new Transaction()

      const targetCoin = await client.routerSwap({
        routers: routerResBuy.routes,
        byAmountIn: true,
        txb: routerTxBuy,
        inputCoin: inputCoin,
        slippage: 0.01,
      })

      const finalCoin = await client.routerSwap({
        routers: routerResSell.routes,
        byAmountIn: true,
        txb: routerTxSell,
        inputCoin: targetCoin,
        slippage: 0.01,
      })

```

like the code above, 1st tx gives an ouput coin, which is as input to 2nd tx.

the function routerSwap() can only produce **a new Transaction**, i can not merge these 2 tx into one, thank you for help

@stefan-mysten 

---

**Comment by stefan-mysten** [comment]
@qxyanda I think some copy paste did not work well here. Could you revise the issue please?

**Comment by stefan-mysten** [comment]
I haven't used the cetus SDK, but that to me seems to be a limitation of their API.

**Comment by qxyanda** [comment]
> I haven't used the cetus SDK, but that to me seems to be a limitation of their API.

Sorry, what I meant was, the function in cetus-ag takes a new Transaction to build a tx. Is there a way for the Transaction type to stack another Transaction, perhaps using an official method from SUI, or maybe through byte operations or something similar?

**Comment by stefan-mysten** [comment]
Maybe this can help:
https://docs.sui.io/guides/developer/sui-101/building-ptb

**Comment by qxyanda** [comment]
> Maybe this can help: https://docs.sui.io/guides/developer/sui-101/building-ptb

thanks, let me try

**Comment by hayes-mysten** [comment]
You should be able to just use the same transaction:

```ts
import { AggregatorClient, Env } from "@cetusprotocol/aggregator-sdk";

      const txb = new Transaction()

      const targetCoin = await client.routerSwap({
        routers: routerResBuy.routes,
        byAmountIn: true,
        txb: txb,
        inputCoin: inputCoin,
        slippage: 0.01,
      })

      const finalCoin = await client.routerSwap({
        routers: routerResSell.routes,
        byAmountIn: true,
        txb: txb,
        inputCoin: targetCoin,
        slippage: 0.01,
      })
```
