### ISSUE TITLE
[FeatureRequest][indexer] surrealdb support

### ISSUE THREAD

**Issue by poelzi** [MystenLabs/sui#19667]
## Support Surrealdb

[surrealdb](https://surrealdb.com/) is a multimodal / object graph database that also support TiKV backend amount others.
Now as version 2 is out, they claim production ready performance.

Utilizing a modern object graph database should allow better indexes and search queries, especially considering graphql interfaces.

It supports typed and untyped node attributes, so best performance could be archived by deriving a surrealdb model from the move structure.

* can be added embedded for dev environments
* graph queries can run distributed via TiKV jobs
* scales better then rational databases
* allows complex primary index types, encoding object versions for example
* good namespace support
* runs as webassembly inside the browser and could be used as local browser cache for sui objects
* should scale to distributed PB indexes 

I see sui and surreadlb as a perfect fit in my opinion

## Expected Result

`cargo build --feature surrealdb`

builds with surrealdb index support

**Comment by gegaowp** [comment]
Hi @poelzi thanks for the pointer and very interesting idea! However, given our existing roadmap and cycles we have, I do not see our team spending meaningful cycles to support surrealdb anytime soon. You are more than welcome re-use current indexer codes and build one for surrealdb though. We might look to make indexer more generic and easier to extend to other DBs in the future, but we do not have concrete needs for this now and are not actively working on this either. Closing the issue for now.
