### ISSUE TITLE
Error: Subscription error : Subscription only supported by WebSocket client.

### ISSUE THREAD

**Issue by MingZoox** [MystenLabs/sui#19707]
I am trying to stream transaction in Sui network, currently using the `examples/transaction_subscription.rs` code in this repo.

But I got the error right away 
```
WS version "1.34.1"
Error: Subscription error : Subscription only supported by WebSocket client.
```

Appreciate any help. Thank you in advance.

```
// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

use futures::stream::StreamExt;
use sui_json_rpc_types::TransactionFilter;
use sui_sdk::SuiClientBuilder;

// This example showcases how to use the Read API to listen
// for transactions. It subscribes to the transactions that
// transfer SUI on the Sui testnet and prints every incoming
// transaction to the console. The program will loop until it
// is force stopped.

#[tokio::main]
async fn main() -> Result<(), anyhow::Error> {
    let ws = SuiClientBuilder::default()
        .ws_url("wss://rpc.testnet.sui.io:443")
        .build("https://fullnode.testnet.sui.io:443")
        .await?;
    println!("WS version {:?}", ws.api_version());

    let mut subscribe = ws
        .read_api()
        .subscribe_transaction(TransactionFilter::MoveFunction {
            package: "0x2".parse()?,
            module: Some("sui".to_owned()),
            function: Some("transfer".to_owned()),
        })
        .await?;

    loop {
        println!("{:?}", subscribe.next().await);
    }
}
```

**Comment by MingZoox** [comment]
seem like its just the ws url is not working

**Comment by stefan-mysten** [comment]
@MingZoox websocket subscriptions have been deprecated on fullnodes.

**Comment by MingZoox** [comment]
@stefan-mysten Hi so that mean I can not use websocket with `sui-sdk` anymore ? Can you provide any best practice other solutions for streaming transaction. Would love to have code example if you can

**Comment by stefan-mysten** [comment]
There might be fullnodes that still have websocket support enabled, but the public nodes operated by Mysten do not have it anymore.

It really depends on what you want to do. We've been recommending to poll for whatever you need (in this case probably an event that is a transaction) instead of using subscriptions, but it's really up to you.

**Comment by shrimpwtf** [comment]
> @MingZoox websocket subscriptions have been deprecated on fullnodes.

Why?! This is a seriously critical use case and part of the SDK??? I need to work with web sockets to keep up-to-date information about the chain for my use case. How can I forcibly enable it?

**Comment by stefan-mysten** [comment]
> For context, I'm hosting my own full node, and cannot for the life of me find where the toggle to enable it is. I've tried web socket-address: localhost:9001 with no success.

In general, we advocate for not using websockets, but if you're running your own node you can set 
```
jsonrpc-server-type: both
```
which should enable the websocket service.

**Comment by shrimpwtf** [comment]
> > For context, I'm hosting my own full node, and cannot for the life of me find where the toggle to enable it is. I've tried web socket-address: localhost:9001 with no success.
> 
> In general, we advocate for not using websockets, but if you're running your own node you can set
> 
> ```
> jsonrpc-server-type: both
> ```
> 
> which should enable the websocket service.

thanks for this. this solved it
