### ISSUE TITLE
RPC data is inconsistent with SuiExplorer

### ISSUE THREAD

**Issue by wowok-ai** [MystenLabs/sui#19726]
RPC digest： 
```
  {
    data: {
      objectId: '0x144505f483946bd4700f80ce02fa342ab4ad4866bd562b0662bebb8141165f17',
      version: '173123156',
      digest: '9MEe5yThKufjVG7vW6iHWJvKP6K1URuHc9x9LECGXyhs',
      content: [Object]
    }
  }
```
https://testnet.suivision.xyz/object/0x144505f483946bd4700f80ce02fa342ab4ad4866bd562b0662bebb8141165f17
DIGEST:  GAEgCnx6E6d7twANpVHW4ZhAE5rYSXXs3PTdwzhJmcrw

Why does this happen?

**Comment by stefan-mysten** [comment]
Can you share the command for getting the `RPC digest`?

**Comment by stefan-mysten** [comment]
In principle, the `digest` under `data` represents the `    /// Base64 string representing the object digest`. The `digest` you see in the link is the digest of the last transaction in which this object was used.
