### ISSUE TITLE
 How to pass 'vector<vector<u8>>' parameter?

### ISSUE THREAD

**Issue by wowok-ai** [MystenLabs/sui#19744]
```
// values is a Uint8Array[] type 
this.txb.pure.vector('vector<u8>', [].slice.call(values))
```

Does not work.  And how to pass 'vector<vector\<u8>>' parameter to MoveCall?

**Comment by stefan-mysten** [comment]
I assume you're using `TypeScript SDK`: https://sdk.mystenlabs.com/typescript/transaction-building/basics#pure-values
