### ISSUE TITLE
Unable to retrieve block content when querying the latest block with GraphQL

### ISSUE THREAD

**Issue by fovz** [MystenLabs/sui#19745]
When I use the following GraphQL to query the latest block content, the return is null. 

Currently, the block content that I can get through testing GraphQL is at least 300,000 blocks behind, and I found that this problem started occurring after October 6.

Can you help me? Thanks.

```
{
  checkpoint(id: { sequenceNumber: $currentBlockNumber }) {
    digest
    sequenceNumber
    validatorSignatures
    previousCheckpointDigest
    networkTotalTransactions
    rollingGasSummary {
      computationCost
      storageCost
      storageRebate
      nonRefundableStorageFee
    }
    epoch {
      epochId
      referenceGasPrice
      startTimestamp
      endTimestamp
    }
  }
}
```

**Comment by stefan-mysten** [comment]
@fovz we had some troubles with the db, so data is stale.
