### ISSUE TITLE
Explorer: Display nested struct and vec fields

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#1983]
Right now the Explorer just ignores these fields. This should become more straightforward after https://github.com/MystenLabs/sui/pull/1855. For the struct fields, we can just implement a collapsible JSON renderer using some library like https://github.com/mac-s-g/react-json-view

**Comment by Jibz1** [comment]
@666lcz can I Object ID with struct and vec fields information

**Comment by 666lcz** [comment]
Here's an example object with struct:

https://github.com/MystenLabs/fastnft/blob/3acaf2abcff381918fae4d4e2555ea8c7c0bf9ea/crates/sui-open-rpc/samples/objects.json#L75

**Comment by Jibz1** [comment]
This is done https://github.com/MystenLabs/sui/pull/2609
