### ISSUE TITLE
doc: sui-indexer start command is wrong

### ISSUE THREAD

**Issue by pymongo** [MystenLabs/sui#19844]
In the README is

https://github.com/MystenLabs/sui/blob/c5a0f83247438bfe5753ad4bd4868bc64f6cd22b/crates/sui-indexer/README.md?plain=1#L58-L67

in the latest version of indexer --db-url has rename to --database-url and require indexer subcommand

**Comment by stefan-mysten** [comment]
Thanks @pymongo. This `database-url` has an alias on it `db-url`, so using it like before (`sui-indexer --db-url "<DATABASE_URL>"`) is fine too.
