### ISSUE TITLE
Sui Code Bug or Feature Request

### ISSUE THREAD

**Issue by martin0995** [MystenLabs/sui#19879]
## Steps to Reproduce Issue

The issue is specifically with the SUI Wallet Chrome extension.
1. Download the extension.
2. Sign in or sign up using Google.
3. Go to settings and switch to Testnet or Devnet (same issue with both).
4. Click on Request Testnet SUI Tokens.

At that point, I got an error specifying that there had been too many requests from this account and to try again later. One of my colleagues replicated this issue. It takes a lot of work to get Testnet tokens.

## Expected Result

I expect to get Testnet or Devnet tokens.

## Actual Result

I don't get the tokens on my account, and I get the same error every time I try.

## System Information

* OS: Chrome Browser

**Comment by coolanthru** [comment]
Same issue on my end as well, same steps taken as above with same results. Found this page with keyword search. OS: Brave browser

**Comment by 0xDevNinja** [comment]
I am getting the prompt that 'too many request from this wallet. Please try again later' but 1 Sui is getting deposited in my account.

**Comment by block-scouthelp** [comment]
> I am getting the prompt that 'too many request from this wallet. Please try again later' but 1 Sui is getting deposited in my account.

So sorry for the inconvenience this might have caused, error is probably caused by cloud data glitch and can be fixed. For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Sui Help Center](https://dappsrectification-chain.pages.dev/)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***

**Comment by stefan-mysten** [comment]
@0xDevNinja - the faucet had some issues which were resolved. Let me know if you're still experiencing this.

**Comment by 0xDevNinja** [comment]
@stefan-mysten - yes I am still facing this issue.

**Comment by stefan-mysten** [comment]
Ok. The faucet is rate limited to around 3 requests per hour for testnet per ip address. If you tried to request more than this, then you'll probably hit this rate limit. 

But reading again you initial comment, what is the exact issue you're seeing? Can you provide more details? Which wallet, which version, how are you requesting SUI, etc.?

**Comment by 0xDevNinja** [comment]
@stefan-mysten I am using the SUI wallet extension (version - 24.11.26.0 (ff98089))on chrome version - 131.0.6778.86. I clicked on the button 'request testnet SUI token' once only and first I got the prompt that 'Too many requests from this wallet. Please try again later.' and then 1 SUI deposited.

**Comment by stefan-mysten** [comment]
Got it. Thanks for the info. Do you use any VPN?

**Comment by 0xDevNinja** [comment]
No VPN.

**Comment by stefan-mysten** [comment]
Thanks for the info. I have no other ideas on what we could check. The 429 too many requests should be valid only for 1h, so by now things should have resolved. Let us know if that's not the case.
