### ISSUE TITLE
ExecutionCancelledDueToSharedObjectCongestion

### ISSUE THREAD

**Issue by wowok-ai** [MystenLabs/sui#19887]
https://testnet.suivision.xyz/txblock/3gwkhNH8deHPVBsagv7fvssC1QgtUH2AGXUT1MXgMEAS

This error did not occur when executing this transaction before. What is happening?

**Comment by mwtian** [comment]
I think the recommendation would be to use a more accurate gas budget (0.0021 instead of 0.0217264). Right now the system is treating this as an expensive transaction.

**Comment by Programmierus** [comment]
You guys know, right, that under "not very many" fall indeed quite a few transactions that exchange aggregators produce with longer routes?

Impact example can be seen [here](https://suivision.xyz/package/0x7ea6e27ad7af6f3b8671d59df1aaebd7c03dddab893e52a714227b2f4fe91519?tab=Transaction+Blocks).

**Comment by mwtian** [comment]
@Programmierus yes we are aware of the issue and sorry for the problems this has caused. An new protocol upgrade targeting tomorrow is in the works to raise the limit to avoid affecting these transactions.

**Comment by mwtian** [comment]
This should have been fixed now.
