### ISSUE TITLE
Inconsistent Parameter Naming in getKiosk Method

### ISSUE THREAD

**Issue by userdarius** [MystenLabs/sui#19925]
I encountered an issue that caused unnecessary time loss due to inconsistent parameter naming in the `getKiosk` method in the kiosk client sdk https://github.com/MystenLabs/sui/blob/main/sdk/kiosk/src/client/kiosk-client.ts .

**Location**:  
Line 84, method definition:
```typescript
getKiosk({ id, options }: {
    id: string;
    options?: FetchKioskOptions;
}): Promise<KioskData>;
```

### Problem:
The TSDoc comments reference a `kioskId`, but the method itself expects an `id` parameter. This inconsistency between the documentation and the method signature can easily lead to confusion and errors during implementation.

### Proposed Solution:
For consistency and clarity, I recommend renaming the `id` parameter to `kioskId` in both the method signature and the corresponding TSDoc. This change would ensure uniformity across the codebase and reduce potential misunderstandings.

**Suggested modification**:
```typescript
getKiosk({ kioskId, options }: {
    kioskId: string;
    options?: FetchKioskOptions;
}): Promise<KioskData>;
```

This would align the documentation and code, improving the developer experience and preventing further confusion.

**Comment by manolisliolios** [comment]
Hey @userdarius,

I've opened this PR #20068 to fix the doc comment. We decided not to rename the `id` argument, as that would need to introduce a breaking change (and force us to keep both for backwards compatibility).

Thanks a lot for the report!

**Comment by userdarius** [comment]
No problem! Thanks a lot it was mostly a question of consistency which I appreciate you fixing.
