### ISSUE TITLE
[sui-move] duplicate `--path` options

### ISSUE THREAD

**Issue by yanganto** [MystenLabs/sui#20003]
Multiple options with the same alias make program panic in debug build, however there is no debug assertion in release build, so the product works well now.

We can use `default_value_if("package_path", builder::ArgPredicate::IsPresent, Some("true"))` to set up the option to follow the other option without using a conflict alias name.

I am happy to make a PR on it, if this looks good from your end.

## Steps to Reproduce Issue
Build `sui-move` in debug and call it directly
`cargo run --bin sui-move`

## Expected Result
Program works or return without panic.

## Actual Result
thread 'main' panicked at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.5.2/src/builder/debug_asserts.rs:97:17:
Command sui-move: Long option names must be unique for each argument, but '--path' is in use by both 'package_path' and 'run_bytecode_verifier'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

## System Information
* OS: NixOS
* Compiler: stable-1.81.0

### Code Snippet
https://github.com/MystenLabs/sui/blob/6b690129928ba7ae454a6c5962fca7ceb5613bed/crates/sui-move/src/main.rs#L26-L33

**Comment by stefan-mysten** [comment]
Thanks @yanganto for catching this. We'd be happy to review a PR and accept it, if you want to go that way. Thanks!

**Comment by yanganto** [comment]
By the way, debug build is not a total trivial thing, because the test coverage only work on debug build.
https://github.com/MystenLabs/sui/blob/1709d22fa258d4135e302e1673a79071566f68db/crates/sui-move/src/unit_test.rs#L40-L44

A contract developer, besides `sui` release binary, he would like to have an additional slim `sui-move` debug build for the usage of test coverage.  And then he will run into this bug when using a debug build `sui-move`.
