### ISSUE TITLE
sui move coverage issue

### ISSUE THREAD

**Issue by alexanderludwig** [MystenLabs/sui#20075]
## Steps to Reproduce Issue

When calling sui move coverage source --module xxx I get an error. The command works for all of my files except one. Happy to give access to our repo to whoever is working on this to reproduce. 

## Expected Result

Code coverage working.

## Actual Result

thread '2024-10-29T19:34:41.389857Z ERROR telemetry_subscribers: panicked at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/str/mod.rs:667:21:
byte index 16 is out of bounds of `` panic.file="/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/str/mod.rs" panic.line=667 panic.column=21
main' panicked at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/str/mod.rs:667:21:
byte index 16 is out of bounds of ``
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: core::str::slice_error_fail_rt
   3: core::str::slice_error_fail
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/str/mod.rs:92:9
   4: core::str::<impl str>::split_at
   5: move_coverage::source_coverage::SourceCoverageBuilder::compute_source_coverage
   6: move_cli::base::coverage::Coverage::execute
   7: sui_move::coverage::Coverage::execute
   8: sui_move::execute_move_command
   9: sui::sui_commands::SuiCommand::execute::{{closure}}
  10: sui::main::{{closure}}
  11: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
  12: tokio::runtime::park::CachedParkThread::block_on
  13: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
  14: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
  15: tokio::runtime::context::runtime::enter_runtime
  16: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  17: tokio::runtime::runtime::Runtime::block_on
  18: sui::main
  19: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

## System Information

Sui CLI: sui 1.35.4-86fa6e86b62a

**Comment by tzakian** [comment]
Sorry you're running into this issue. Would love to take a look if possible!

**Comment by alexanderludwig** [comment]
Thanks for fixing this @tzakian
