### ISSUE TITLE
Explorer: Sender, recipient naming standardization

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#2009]
We are using from/to as well as sender recipient inconsistently across the explorer when it comes to transactions.

@666lcz @Jibz1 Correct me if I'm wrong I remember in an earlier issue we aligned on using sender/recipient naming.

**Comment by 666lcz** [comment]
@bwann52 , there are three transaction types:
- TransferCoin
- Move Call
- Publish

Only the first type has the concept of  "sender" and "recipient", and for the second and third type, "Transaction Initiator"/"from" is a more appropriate term. Should we have different annotations(for first type we show: `sender` and `recipient`; for the other types we show `Initiator`/`from`) in the landing page, or should we just consistently use `from/to` everywhere?

![Image](https://user-images.githubusercontent.com/76067158/169748839-95e48e82-57af-4d32-9cd8-5edaa55e3551.png)

**Comment by bwann52** [comment]
@666lcz good call out.

In this case, I think using "By" is easier to understand than "Initiator"

For aggregated pages (for example, list of recent transactions), for all three let's use "By". And "To" when it makes sense (for transfer and publish)
TransferCoin: By/To
Move Call: By
Publish: By/To

For detailed view (once you click in):
TransferCoin:  Sender/Receiver
Move Call: Caller/Package Called
Publish: Publisher/Package Published

Let me know if the above make sense. The goal is to use human friendly language.

**Comment by 666lcz** [comment]
The source of truth is the design mockups
