### ISSUE TITLE
Transaction certificates

### ISSUE THREAD

**Issue by Godxia** [MystenLabs/sui#20159]
I modified the rpc node and added a method to request get_transaction_certification, trying to cache the transaction certificate to reduce latency. However, I found that the validator broadcasts the certificate and executes the transaction when requesting the certificate. Why is this, is this a bug? Do some validator nodes do this? Or do all validators do this?

**Comment by stefan-mysten** [comment]
Thanks @Godxia for your question. It's not exactly clear what your question is?

**Comment by Godxia** [comment]
```
async fn get_tx_cert(
&self,
tx_bytes: Base64,
signatures: Vec<Base64>,
opts: Option<SuiTransactionBlockResponseOptions>,
// request_type: Option<ExecuteTransactionRequestType>
)-> Result<AuthorityStrongQuorumSignInfo, Error> {}
```
I modified the rpc code and added the above function in TransactionExecutionApi, hoping to get only the certificate of the transaction and cache it for quick transactions in the future. I found that I could successfully get the transaction certificate, but the validator broadcasted the transaction I sent only to get the certificate about 1 minute later, which caused the cached transaction to be executed. I think this may be a bug because I only sent a request for the certificate, but the transaction was executed.

**Comment by lxfind** [comment]
Hi @Godxia, this is expected and not a bug. It is a feature called transaction finalizer. If transactions are signed by validators but not finalized, this could hurt user experience because objects in the transactions will be locked until end of epoch. So validators would help broadcast transactions if they are signed but not finalized.
