### ISSUE TITLE
The `event_api` example is not working

### ISSUE THREAD

**Issue by jacob-chia** [MystenLabs/sui#20153]
## Steps to Reproduce Issue

```sh
cargo run --example event_api 
```

## Expected Result

This example will continuously listen for incoming events and print them out.

## Actual Result

```log
WS version "1.36.2"
Error: Subscription error : Subscription only supported by WebSocket client.
```

## System Information

* OS: ubuntu 24.04
* Compiler: rustc 1.82.0 (f6e511eec 2024-10-15)

**Comment by stefan-mysten** [comment]
@jacob-chia thanks for reporting this issue. Unfortunately, Subscriptions are not supported on public full nodes (operated by us), so this example does not work. You might still find a full node that has subscriptions enabled.
As an alternative, we recommend to use polling for whatever events you need. 

I will make a note on the example that this is no longer supported.

Thanks for your understanding.

**Comment by jacob-chia** [comment]
@stefan-mysten 
Thank you for your response.

My `fullnode.yaml` is as follows, but I'm still encountering the same error. If I want to enable ws, what additional configuration should I add?

```yaml
# this address is also used for web socket connections
json-rpc-address: "0.0.0.0:9000"
enable-event-processing: true
```

**Comment by stefan-mysten** [comment]
In general, we advocate for not using websockets, but if you're running your own node you can set

`jsonrpc-server-type: both`

which should enable the websocket service.
