### ISSUE TITLE
Sui Code  can not build

### ISSUE THREAD

**Issue by join2017** [MystenLabs/sui#20178]
## while i  run : cargo install --git https://github.com/MystenLabs/sui.git anemo-benchmark

Compiling mysten-network v0.2.0 (/Users/tjb/.cargo/git/checkouts/sui-6ac459c53b1b685a/d38f141/crates/mysten-network)
error[E0599]: no method named `enable_http1` found for struct `HttpsConnectorBuilder` in the current scope
   --> crates/mysten-network/src/client.rs:150:22
    |
147 |                   let https = hyper_rustls::HttpsConnectorBuilder::new()
    |  _____________________________-
148 | |                     .with_tls_config(tls_config)
149 | |                     .https_only()
150 | |                     .enable_http1()
    | |_____________________-^^^^^^^^^^^^
    |
help: there is a method `enable_http2` with a similar name
    |
150 |                     .enable_http2()
    |                      ~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0599`.
error: could not compile `mysten-network` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `anemo-benchmark v0.0.0 (https://github.com/MystenLabs/sui.git#d38f1416)`, intermediate artifacts can be found at `/var/folders/t_/cnqv8p212x9d5x1jgc8cxlf00000gn/T/cargo-install2k
To reuse those artifacts with a future compilation, set the environment variable `CARGjoey:~

what do  i do?

**Comment by stefan-mysten** [comment]
Hi @join2017 

Why are you trying to install `anemo-benchmark`? Are you trying to install `Sui CLI` ?

**Comment by join2017** [comment]
@stefan-mysten   thank for your help. you are right. I make  a mistake.   only run  :argo install --locked --git https://github.com/MystenLabs/sui.git --branch testnet sui .
