### ISSUE TITLE
[sui move] Parity with Move CLI

### ISSUE THREAD

**Issue by tnowacki** [MystenLabs/sui#2019]
- The sui-move CLI tool is necessary for handling Sui specific aspects of Move
  - Located in sui/src/bin/sui-move.rs 
- However, most of the commands are attempting to replicate behavior already present in the move CLI
  - Located in the move repo [language/tools/move-cli/src/lib.rs](https://github.com/move-language/move/blob/main/language/tools/move-cli/src/lib.rs) 
 - In the short term, we should at least be using all of the `package` commands
 - In the longer term, it could be nice to handle the `sandbox` commands (outside of the resource viewing ones)
 
There are a few different ways of approaching this
A) Manually use the command structs from the move repo. Then call out to the functions as needed. (Custom entry point or driver helper functions might be needed)
B) Expose a bunch of custom entry logic via traits. This is how things are done in the transactional test framework (see [language/testing-infra/transactional-test-runner/src/tasks.rs](https://github.com/move-language/move/blob/main/language/testing-infra/transactional-test-runner/src/tasks.rs)

**Comment by tnowacki** [comment]
Priority:
- Package commands
- Prover integration
- Doc gen
- code cov

**Comment by tnowacki** [comment]
- dissassembler 
- bytecode viewer

**Comment by oxade** [comment]
* remove requirement for `--std`
