### ISSUE TITLE
Sui-tool download-db-snapshot is failing multiple times with panicked at /home/runner/work/sui/sui/crates/sui-tool/src/lib.rs:1104:35:

### ISSUE THREAD

**Issue by jay-ginco** [MystenLabs/sui#20206]
## Steps to Reproduce Issue

Spin up a new testnet server, and when trying to download db snapshot via below command
```
sui-tool download-db-snapshot --latest \
    --network testnet  --path /mnt/sui/snapshot_db \
    --num-parallel-downloads 25 \
    --no-sign-request
```

It fails after running for around 20 minutes with
```
thread 'main' panicked at /home/runner/work/sui/sui/crates/sui-tool/src/lib.rs:1104:35:
Task failed: Generic s3 error: error decoding response body
Caused by:
  0: error decoding response body
  1: error reading a body from connection
  2: stream error received: unexpected internal error encountered
```

## Expected Result

It should download the testnet snapshot with the latest epoch (541 in above case) without any failures

## System Information

* OS: ubuntu 22.04
* 16 vCPU 128 GB 

### Workaround

I observed there are GCS/s3 buckets hosted also for snapshots as mentioned here https://docs.sui.io/guides/operator/snapshots#bucket-names, kindly mention the cost estimation if I were to download snapshot from there, or please mention the bucket type (standara/archive) or the region so I can calculate on my own. What would be the data size also, is it more than 1 TB for testnet?

**Comment by stefan-mysten** [comment]
Hey @johnjmartin, do you have any idea what might be going on here?

**Comment by jay-ginco** [comment]
Thanks @stefan-mysten for replying, @johnjmartin any suggestions would be highly appreciated

**Comment by johnjmartin** [comment]
what `sui-tool` version are you running? `sui-tool -V`

**Comment by jay-ginco** [comment]
Its the binary from latest testnet 1.37.1 release, same as sui-node that is running.

**Comment by johnjmartin** [comment]
> I believe tweaking --num-parallel-downloads should get it to working, checking

Reducing the --num-parallel-downloads  can help in environments with less compute resources or less network bandwidth

> I observed there are GCS/s3 buckets hosted also for snapshots as mentioned here https://docs.sui.io/guides/operator/snapshots#bucket-names, kindly mention the cost estimation if I were to download snapshot from there, or please mention the bucket type (standara/archive) or the region for the gcs bucket so I can calculate on my own. What would be the data size also, is it more than 1 TB for testnet?

The data size for testnet snapshots is ~2TB at the moment. The cost will depend on if you're transferring data within google cloud or outside of it, see https://cloud.google.com/storage/docs/requester-pays for details

**Comment by jay-ginco** [comment]
Hi @johnjmartin thanks for the command,
`gsutil -u "my-project-id" du -sh gs://mysten-testnet-snapshots/epoch_549 (picking epoch_549`
 but the issue is still the same, I get 403 error, while my user has owner role assigned, so are there any steps required to get access to the gcs bucket

**Comment by jay-ginco** [comment]
Thank you very much @johnjmartin

**Comment by johnjmartin** [comment]
> The files to be dowloaded are very less, for testnet the number was in millions, any reason for that?

cloudflare snapshots are currently smaller than gcs snapshots as we prune the cloudflare ones more aggressively

**Comment by jay-ginco** [comment]
Ah, okay, so we need historical  data and also indexing, would that be possible with the snapshot?  We want to run the node in non-prune mode (will prune transactional data, but after downloading snpashot)

**Comment by johnjmartin** [comment]
I wouldn't expect much space to be reclaimed via compaction after you restore from a DB snapshot. the snapshots that are uploaded have already been compacted. I expect the disk usage will mostly increase
