### ISSUE TITLE
[Move objects] Expose structured representation of a disassembled package

### ISSUE THREAD

**Issue by sblackshear** [MystenLabs/sui#2029]
Today, the explorer shows a string representation of a disassembled Move package. This is very cool, but it would be even niftier if we could show a structured representation of the package that links to types and functions used elsewhere. To support this, we need to do the following:

Use a [`normalized::Module`](https://github.com/move-language/move/blob/main/language/move-binary-format/src/normalized.rs#L90) instead of a string representation of the disassembled module [here](https://github.com/MystenLabs/sui/blob/main/crates/sui-types/src/move_package.rs#L77) and ensure that it gets turned into nicely structured JSON that the explorer can understand

**Comment by gegaowp** [comment]
merged a PR #3852 and closing this one.
