### ISSUE TITLE
About Passkey test code

### ISSUE THREAD

**Issue by daoauth** [MystenLabs/sui#20324]
I noticed there are test codes related to SIP-9. Has SIP-9 been running on Testnet or Devnet? If so, is it ready for testing?

https://github.com/MystenLabs/sui/blob/main/crates/sui-types/src/unit_tests/passkey_authenticator_test.rs

**Comment by joyqvq** [comment]
its running in devnet. we hope to push to testnet and mainnet in q1 2025.

**Comment by joyqvq** [comment]
The branch is in active development and not ready to use. Please wait for till this PR is merged and released!
