### ISSUE TITLE
Formal snapshot missing on testnet since epoch 550

### ISSUE THREAD

**Issue by Sceat** [MystenLabs/sui#20327]
Working: > https://formal-snapshot.testnet.sui.io/epoch_549/MANIFEST

![image](https://github.com/user-attachments/assets/b73a6f3c-cacd-4092-a489-2ef383d434e8)

---

Not working: > https://formal-snapshot.testnet.sui.io/epoch_550/MANIFEST

![image](https://github.com/user-attachments/assets/d681bad1-dcb7-40f6-92e5-b5dd9305a954)

**Comment by stefan-mysten** [comment]
There is an issue with formal snapshots, hope it will be solved soon.

**Comment by johnjmartin** [comment]
Formal snapshots are fixed in testnet
