### ISSUE TITLE
[checkpoints] Connect checkpoint logic to consensus

### ISSUE THREAD

**Issue by gdanezis** [MystenLabs/sui#2036]
The functions `handle_receive_fragment` and `handle_internal_fragment` should be connected to consensus to inject and receive sequenced fragments respectively. We should also think there about how we connect the checkpoint object to the authority: is it right that the authority owns a Arc<Mutex<CheckpointStore>>, or should the coupling be looser with the checkpoint store owning an Arc<AuthorityStore> instead to access consensus?

**Comment by asonnino** [comment]
What should we do when the following function returns an error?
```rust
pub fn handle_internal_fragment(
        &mut self,
        _seq: u64,
        _fragment: CheckpointFragment,
) -> Result<(), FragmentInternalError> {
```

**Comment by asonnino** [comment]
Also I understand that `_seq` is provided by consensus. Do sequence numbers need to be consecutive?

**Comment by asonnino** [comment]
The consensus client is async while the trait `ConsensusSender` is not. How can we avoid blocking?
```
impl ConsensusSender for CheckpointSender {
    fn send_to_consensus(&self, fragment: CheckpointFragment) -> SuiResult {
        let transaction = ConsensusTransaction::Checkpoint(fragment);

        // Serialize the transaction in a way that is understandable to consensus (i.e., using
        // bincode) and it certificate to consensus.
        let serialized =
            bincode::serialize(&transaction).expect("Failed to serialize consensus tx");
        let bytes = Bytes::from(serialized);

        // Send the transaction to consensus.
        // TODO: Blocking on the function below is not great.
        futures::executor::block_on(
            self.consensus_client
                .clone()
                .submit_transaction(TransactionProto { transaction: bytes }),
        )
        .map_err(|e| SuiError::ConsensusConnectionBroken(format!("{:?}", e)))?;
        Ok(())
    }
}
```

**Comment by gdanezis** [comment]
On Q1: 

> Question 1: What should we do when the following function returns an error?

Note that there are two variants of errors:
```
#[derive(Debug)]
pub enum FragmentInternalError {
    Error(SuiError),
    Retry(Box<CheckpointFragment>),
}
```

On retry it means that the error is temporary, and the expectation is that the component driving `handle_internal_fragment` will retry this sequence number (in order). On other errors, log them and move on. The retires are on database errors, where we cannot know if somethings was written.

 I think we need to carefully audit `attempt_to_construct_checkpoint` since I think that there I was more loose on what is an error can should be logged versus retried.
 
 On Q2: 

> Question 2: I understand that the argument _seq of handle_internal_fragment is provided by consensus. Do these sequence numbers need to be strictly consecutive?

They need to be distinct and increasing but no need for them to be consecutive at all.

On Q3:

> Question 3: The consensus client is async while the trait ConsensusSender is not. How can we avoid blocking?

I am not sure why you call block_on in the code below:
```
        // Send the transaction to consensus.
        // TODO: Blocking on the function below is not great.
        futures::executor::block_on(
            self.consensus_client
                .clone()
                .submit_transaction(TransactionProto { transaction: bytes }),
        )
        .map_err(|e| SuiError::ConsensusConnectionBroken(format!("{:?}", e)))?;
```
There is no await / future in the block right?

I would use an mpsc channel in there with a large (but not unlimited capacity), and do 
https://docs.rs/tokio/latest/tokio/sync/mpsc/struct.Sender.html#method.try_send
on it when injecting a message. In case it is full its ok to return an error (the sender will have to send the fragment again).

Then on the other side I would have a tokio task that picks up the messages and puts them in consensus (that can be async and await all it wants).
