### ISSUE TITLE
Unstable API `subscribe_transaction`

### ISSUE THREAD

**Issue by jacob-chia** [MystenLabs/sui#20388]
## Steps to Reproduce Issue

My local node supports WebSocket as it is configured with `jsonrpc-server-type: both`.

- code:

```rs
    let ws = SuiClientBuilder::default()
        .ws_url("ws://localhost:9000")
        .build("http://localhost:9000")
        .await?;
    println!("WS version {:?}", ws.api_version());

    let mut sub = ws
        .read_api()
        .subscribe_transaction(TransactionFilter::MoveFunction {
            package: "0x1eabed72c53feb3805120a081dc15963c204dc8d091542592abaf7a35689b2fb"
                .parse()?,
            module: None,
            function: None,
        })
        .await?;

    while let Some(tx) = sub.next().await {
        println!("{:?}", tx);
    }
```
- cmd:

```sh
cargo run --example transaction_subscription
```

## Expected Result

Expected to receive new `SuiTransactionBlockEffects`

## Actual Result

Initially, this API was working, but after some time, it started returning the following error:

```log
WS version "1.37.0"
Error: RPC call failed: ErrorObject { code: InvalidParams, message: "Invalid params", data: None }

Caused by:
    RPC call failed: ErrorObject { code: InvalidParams, message: "Invalid params", data: None }
```

## System Information

* OS: Ubuntu 24.04
* Compiler: rustc 1.82.0 (f6e511eec 2024-10-15)

**Comment by stefan-mysten** [comment]
You might need to restart the service, it is known that at times it just fails. Another option is to look at the number of connections, and set it to something like 500?

**Comment by jacob-chia** [comment]
> You might need to restart the service, it is known that at times it just fails. Another option is to look at the number of connections, and set it to something like 500?

Thanks a lot! How do I set the max-connections? I can't find the setting in the [fullnode.yaml](https://github.com/MystenLabs/sui/blob/main/crates/sui-config/data/fullnode-template.yaml)

**Comment by stefan-mysten** [comment]
Try this?
```
indexer-max-subscriptions: 500
```
