### ISSUE TITLE
Error in Move Trace Debugger Documentation

### ISSUE THREAD

**Issue by daoauth** [MystenLabs/sui#20449]
There is an issue in the Move Trace Debugger documentation:

## Documentation Error

The documentation specifies the following command:

```bash
sui move test --trace-execution
```

However, executing this command results in an error.

```bash
error: unexpected argument '--trace-execution' found

  tip: to pass '--trace-execution' as a value, use '-- --trace-execution'

Usage: sui move test [OPTIONS] [filter]

For more information, try '--help'.
```

The correct command should be:

```bash
sui move test -- --trace-execution
```

`The -- must be included for the --trace-execution option to be recognized properly.`

## Command Palette Issue

When using the Command Palette option **`Move: Trace Move test execution`**, it asks for an additional filter value.
However, following the **`leave empty to trace all tests`** instruction and providing an empty string results in the same error.

https://github.com/MystenLabs/sui/blob/533043dfb56ca1475327b54a01b69708e951929c/external-crates/move/crates/move-analyzer/editors/code/src/main.ts#L120-L132

**Comment by daoauth** [comment]
The issue has been resolved after an upgrade.

**sui 1.38.1**

**Comment by stefan-mysten** [comment]
Great to hear @daoauth!
