### ISSUE TITLE
Move contracts upgrade issues

### ISSUE THREAD

**Issue by web3olalala** [MystenLabs/sui#20457]
PackageA has been deployed on Sui.
Suppose I write Package B, which references PackageA, and I also deploy it on Sui.

1. Does the upgrade of PackageA cause problems with PackageB ?
2. If PackageA has been upgraded and my PackageB also wants to be upgraded to use the methods added to PackageA, how do I upgrade my PackageB?

**Comment by stefan-mysten** [comment]
1. Unlikely, there are backward compatibility guarantees that a package upgrade will not break existing code used by other packages.
2. To upgrade Package B, you just point the dependency of Package A to be the new upgrade version (upgraded Package A will have a different ID than original package) - either as a local dependency or as a GitHub repository where upgraded package A lives, and then upgrade package B by passing in its upgrade cap.
