### ISSUE TITLE
 Issue with --dump-bytecode-as-base64 Option Requiring Config File

### ISSUE THREAD

**Issue by daoauth** [MystenLabs/sui#20458]
## Steps to Reproduce Issue

1. Update sui-cli to the latest version.
2. Run the following command without a configuration file present:
```bash
sui move build --dump-bytecode-as-base64
```
3. Observe the following prompt:
```bash
Config file ["client.yaml"] doesn't exist, do you want to connect to a Sui Full node server [y/N]?
```

## Expected Result

The `--dump-bytecode-as-base64` option should function as it did in previous versions of sui-cli, where it could generate a dump file without requiring a configuration file.

## Actual Result

The command fails to execute and prompts the user for a configuration file:

```bash
Config file ["client.yaml"] doesn't exist, do you want to connect to a Sui Full node server [y/N]?
```
This introduces a new and unexpected dependency on a config file, which complicates workflows that previously operated without it.

## System Information

* OS: mac os. github actions

**Comment by stefan-mysten** [comment]
Hi @daoauth 

We're aware of this little inconvenience with the `sui move build --dump-bytecode-as-base64`. It basically just needs to know which network you're trying to build against, so you can provide a dummy `client.yaml` file without actually creating a private key and the `sui.keystore` file, and that will work. I will try to see if I can fix this for a next release of Sui CLI, to have a flag that we can pass an unknown chain and just allow us to build the code and get the json from this `dump-bytecode-as-base64`.

**Comment by daoauth** [comment]
> Hi @daoauth
> 
> We're aware of this little inconvenience with the `sui move build --dump-bytecode-as-base64`. It basically just needs to know which network you're trying to build against, so you can provide a dummy `client.yaml` file without actually creating a private key and the `sui.keystore` file, and that will work. The reason for that is related to the needs of automated address management.
> 
> I will try to see if I can fix this for a next release of Sui CLI, to have a flag that we can pass an unknown chain and just allow us to build the code and get the json from this `dump-bytecode-as-base64`.

Could you kindly consider [this issue](https://github.com/MystenLabs/sui/issues/19114) as well? If possible, I would greatly appreciate your thoughts on it.

**Comment by stefan-mysten** [comment]
Sorry but I don't think such a feature is needed. `--dump-bytecode-as-base64` returns a JSON, so you need to just pipe it to a file using standard unix utils? Is that something not possible on your end?

**Comment by daoauth** [comment]
> Sorry but I don't think such a feature is needed. `--dump-bytecode-as-base64` returns a JSON, so you need to just pipe it to a file using standard unix utils? Is that something not possible on your end?

I was already performing the task of saving the JSON as you suggested. It's not a major issue, but when I use a pipeline to output, the color of the compile result prompt disappears, which is a bit unfortunate. I think this happens because ANSI color codes are disabled when output is redirected to a file or pipeline. So I wanted to mention this to see if there's any other solution or if a feature could be added to address this.
