### ISSUE TITLE
Error in module @mysten

### ISSUE THREAD

**Issue by MeoMunDep** [MystenLabs/sui#20522]
node:internal/modules/cjs/loader:647
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in .\node_modules\@mysten\sui\package.json

Node version: 22.11.0, NPM version: 10.9.0, NVM version: 1.1.12, @mysten version: Lastest - 0.54.1

**Comment by hayes-mysten** [comment]
If you are still using @mysten/sui.js you may need to upgrade to @mysten/sui:  https://sdk.mystenlabs.com/typescript/migrations/sui-1.0

**Comment by MeoMunDep** [comment]
Thank for the reply, but it still got the same error, even i try to download new version.
I also test in commonJS and ES6 but still not work 

const { SuiClient } = require('@mysten/sui');
import { SuiClient } from '@mysten/sui'

Both of them still not work

**Comment by hayes-mysten** [comment]
There isn't enough detail here to understand or reproduce the issue. 

If you could provide a small reproduction, or even more details about your setup, how you are running/building your code that could be helpful.

There is no stack trace in your error report, so we can't tell where this error originates.  So far I haven't been able to reproduce the issue with the given information

**Comment by MeoMunDep** [comment]
![Screenshot 2024-12-07 012413](https://github.com/user-attachments/assets/c9f5d140-336b-4a33-9b01-fc684bd9a257)
![Screenshot 2024-12-07 012413](https://github.com/user-attachments/assets/a6e189c3-6e88-476c-81b8-df584a0976f6)


Here, to be clear i just write simple like this, but it can not be run, again, thank you for reply.

**Comment by MeoMunDep** [comment]
And here is the package.json of @mysten/sui if you want to see more clear


{
  "name": "@mysten/sui",
  "author": "Mysten Labs <build@mystenlabs.com>",
  "description": "Sui TypeScript API(Work in Progress)",
  "homepage": "https://sdk.mystenlabs.com",
  "version": "1.16.0",
  "license": "Apache-2.0",
  "sideEffects": false,
  "files": [
    "CHANGELOG.md",
    "LICENSE",
    "README.md",
    "bcs",
    "builder",
    "client",
    "cryptography",
    "dist",
    "faucet",
    "graphql",
    "keypairs",
    "multisig",
    "src",
    "transactions",
    "utils",
    "verify",
    "zklogin"
  ],
  "engines": {
    "node": ">=18"
  },
  "type": "commonjs",
  "exports": {
    "./bcs": {
      "import": "./dist/esm/bcs/index.js",
      "require": "./dist/cjs/bcs/index.js"
    },
    "./client": {
      "import": "./dist/esm/client/index.js",
      "require": "./dist/cjs/client/index.js"
    },
    "./cryptography": {
      "import": "./dist/esm/cryptography/index.js",
      "require": "./dist/cjs/cryptography/index.js"
    },
    "./faucet": {
      "import": "./dist/esm/faucet/index.js",
      "require": "./dist/cjs/faucet/index.js"
    },
    "./graphql": {
      "import": "./dist/esm/graphql/index.js",
      "require": "./dist/cjs/graphql/index.js"
    },
    "./keypairs/ed25519": {
      "import": "./dist/esm/keypairs/ed25519/index.js",
      "require": "./dist/cjs/keypairs/ed25519/index.js"
    },
    "./keypairs/secp256k1": {
      "import": "./dist/esm/keypairs/secp256k1/index.js",
      "require": "./dist/cjs/keypairs/secp256k1/index.js"
    },
    "./keypairs/secp256r1": {
      "import": "./dist/esm/keypairs/secp256r1/index.js",
      "require": "./dist/cjs/keypairs/secp256r1/index.js"
    },
    "./multisig": {
      "import": "./dist/esm/multisig/index.js",
      "require": "./dist/cjs/multisig/index.js"
    },
    "./transactions": {
      "import": "./dist/esm/transactions/index.js",
      "require": "./dist/cjs/transactions/index.js"
    },
    "./utils": {
      "import": "./dist/esm/utils/index.js",
      "require": "./dist/cjs/utils/index.js"
    },
    "./verify": {
      "import": "./dist/esm/verify/index.js",
      "require": "./dist/cjs/verify/index.js"
    },
    "./zklogin": {
      "import": "./dist/esm/zklogin/index.js",
      "require": "./dist/cjs/zklogin/index.js"
    },
    "./graphql/schemas/2024.1": {
      "import": "./dist/esm/graphql/schemas/2024.1/index.js",
      "require": "./dist/cjs/graphql/schemas/2024.1/index.js"
    },
    "./graphql/schemas/2024.4": {
      "import": "./dist/esm/graphql/schemas/2024.4/index.js",
      "require": "./dist/cjs/graphql/schemas/2024.4/index.js"
    }
  },
  "bugs": {
    "url": "https://github.com/MystenLabs/sui/issues/new"
  },
  "publishConfig": {
    "access": "public"
  },
  "devDependencies": {
    "@0no-co/graphqlsp": "^1.12.11",
    "@graphql-codegen/add": "^5.0.3",
    "@graphql-codegen/cli": "^5.0.2",
    "@graphql-codegen/typed-document-node": "^5.0.9",
    "@graphql-codegen/typescript": "4.0.9",
    "@graphql-codegen/typescript-operations": "^4.2.3",
    "@iarna/toml": "^2.2.5",
    "@types/node": "^20.14.10",
    "@types/tmp": "^0.2.6",
    "@types/ws": "^8.5.10",
    "cross-env": "^7.0.3",
    "graphql-config": "^5.0.3",
    "msw": "^2.3.1",
    "tmp": "^0.2.3",
    "ts-retry-promise": "^0.8.1",
    "typescript": "^5.5.3",
    "vite": "^5.3.3",
    "vitest": "^2.0.1",
    "wait-on": "^7.2.0",
    "ws": "^8.18.0",
    "@mysten/build-scripts": "^0.0.0"
  },
  "dependencies": {
    "@graphql-typed-document-node/core": "^3.2.0",
    "@noble/curves": "^1.4.2",
    "@noble/hashes": "^1.4.0",
    "@scure/bip32": "^1.4.0",
    "@scure/bip39": "^1.3.0",
    "@suchipi/femver": "^1.0.0",
    "bech32": "^2.0.0",
    "gql.tada": "^1.8.2",
    "graphql": "^16.9.0",
    "jose": "^5.6.3",
    "poseidon-lite": "^0.2.0",
    "tweetnacl": "^1.0.3",
    "valibot": "^0.36.0",
    "@mysten/bcs": "1.1.1"
  },
  "scripts": {
    "clean": "rm -rf tsconfig.tsbuildinfo ./dist",
    "codegen:version": "node genversion.mjs",
    "build": "node genversion.mjs && pnpm build:package",
    "build:package": "build-package",
    "vitest": "vitest",
    "test": "pnpm test:typecheck && pnpm test:unit",
    "test:typecheck": "tsc -p ./test",
    "test:unit": "vitest run unit __tests__",
    "test:e2e": "wait-on http://127.0.0.1:9123 -l --timeout 180000 && vitest run e2e",
    "test:e2e:nowait": "vitest run e2e",
    "prepare:e2e": "docker-compose down && docker-compose up -d && cargo build --bin sui --profile dev && cross-env RUST_LOG=warn,sui=error,anemo_tower=warn,consensus=off ../../target/debug/sui start --with-faucet --force-regenesis --with-indexer --pg-port 5435 --pg-db-name sui_indexer_v2 --with-graphql",
    "size": "size-limit",
    "analyze": "size-limit --why",
    "prettier:check": "prettier -c --ignore-unknown .",
    "prettier:fix": "prettier -w --ignore-unknown .",
    "eslint:check": "eslint --max-warnings=0 .",
    "eslint:fix": "pnpm run eslint:check --fix",
    "lint": "pnpm run eslint:check && pnpm run prettier:check",
    "lint:fix": "pnpm run eslint:fix && pnpm run prettier:fix",
    "update-schemas": "pnpm tsx scripts/update-graphql-schemas.ts",
    "generate-schema": "gql.tada generate-output"
  }
}

**Comment by hayes-mysten** [comment]
I see.  Sorry, I wasn't familiar with this specific error, but now that I see the code, I know whats going on.

The sui sdk is broken up into multiple import paths, and you can't import directly form the root of the pacakge:

```ts
const { SuiClient } = require('@mysten/sui/client');
```

**Comment by Ia6368060** [comment]
[](url)const { SuiClient } = require('@mysten/sui/client');

**Comment by MeoMunDep** [comment]
I solved it now, thank you admin, appreciate this library to the community.
