### ISSUE TITLE
[benchmarking] Throughput Benchmark For Shared Objects

### ISSUE THREAD

**Issue by oxade** [MystenLabs/sui#2056]
From a recent thread:

@asonnino wrote: My intuition would be to make this benchmark in 3 steps:
- Benchmark the sequencing capabilities of narwhal+tusk/bullshark (No Sui, no execution)
- Benchmark shared objects without execution (no-op). This tests the stability of the bridge between consensus and Sui
- End-to-end benchmark of shared objects in Sui (as you describe above). If all goes well, execution will be the bottleneck

In other words, we should really have multiple benchmarks, ones that are more like unit microbenchmarks just for Sui->Narwhal integration.   Use onion strategy and gradually peel back the onion.   Then we can easily see what is taking up more time.

Also rely on metrics and runtime profiling of end to end testing.

Other notes:
- counter contract is sufficient to start
- be sure to use different gas for each transaction (but this becomes a really big limiting factor for longer benchmarks, and kind of unrealistic)
- Test single threaded (one counter object) vs many counter objects, or have a parameter

How about we can have a parameter be the number (or ratio) of counters?  1.00 = number of counters is same as number of callers, and 0.1 == 1/10th counters for callers (or each counter has 10 callers)

Second parameter for ratio of shared to owned transactions (for end to end testing)

**Comment by lxfind** [comment]
Has been running since last week
Found a few issues. stops working after a few mins, unable to recover
