### ISSUE TITLE
Object view in wallet should use --json by default

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/sui#2058]
At the moment CLI users have to specifically define `--json` when requesting object details from a wallet, i.e., `wallet object --json --id <id>`. 

Having `--json` as the default behavior (without the user typing it) should be supported, because the data we get without it is mostly not very interesting to a developer (ID maybe, but not hash or version), whereas the actual type-specific object data is very relevant. By experience, most devs are interested about object's field values and this is usually their first experiment when starting playing with Sui (many forget `--json` and ask for clarifications).

Per @sblackshear: "and a good time to switch now that we have this beautiful new JSON view @patrickkuo added without the cruft of --fields"

**Comment by Clay-Mysten** [comment]
Let's figure out all of the changes needed here. It sounds like we need to strip references to the --json flag as redundant too, correct? Patrick, please send me an update of the docs to review. Thanks!

**Comment by Clay-Mysten** [comment]
And please make those doc changes in the `main` branch too. Thanks!

**Comment by Clay-Mysten** [comment]
Or I can get to this in a few weeks, re-capturing the output you included as images in issue #2013. I'm up against the wall with tokenomics and full nodes now, both due ASAP.

Medium prio

**Comment by patrickkuo** [comment]
> Let's figure out all of the changes needed here. It sounds like we need to strip references to the --json flag as redundant too, correct? Patrick, please send me an update of the docs to review. Thanks!

We are keeping the --json flag, however I have enhanced the object command output so will need to update the doc, will work on it soon and add you for review

**Comment by Clay-Mysten** [comment]
> > Let's figure out all of the changes needed here. It sounds like we need to strip references to the --json flag as redundant too, correct? Patrick, please send me an update of the docs to review. Thanks!
> 
> We are keeping the --json flag, however I have enhanced the object command output so will need to update the doc, will work on it soon and add you for review

Thank you so much, Patrick! I appreciate it immensely.

**Comment by Clay-Mysten** [comment]
Let me take a run at this. I have other updates I want to make here. Will hit you up for help, Patrick. Thanks for offering.

**Comment by Clay-Mysten** [comment]
@patrickkuo I  am not going to be able to get to this anytime soon as we keep breaking ourselves:
https://mysten-labs.slack.com/archives/C034XH78HNU/p1653341567003489?thread_ts=1653341397.643429&cid=C034XH78HNU

Please help with this issue if you can. Or I will try sometime in the likely distant future.

**Comment by Clay-Mysten** [comment]
Hi @patrickkuo , did this get done? If not, I will get it back on my list. I want to work on splitting up the Wallet contents into sub-pages anyway. Thanks!

**Comment by patrickkuo** [comment]
> Hi @patrickkuo , did this get done? If not, I will get it back on my list. I want to work on splitting up the Wallet contents into sub-pages anyway. Thanks!

Oh this is not done yet.... I was planing to do this together with the Sui and wallet CLI binaries merge (will need to rename wallet CLI to Sui CLI after the changes), please feel free to start splitting, the binaries merging will take me a few more days.

**Comment by Clay-Mysten** [comment]
Let us work together. I'm jamming on the Wallet browser extension docs now and can see a path to split and deduping. Thanks, Patrick!

**Comment by Clay-Mysten** [comment]
> > Hi @patrickkuo , did this get done? If not, I will get it back on my list. I want to work on splitting up the Wallet contents into sub-pages anyway. Thanks!
> 
> Oh this is not done yet.... I was planing to do this together with the Sui and wallet CLI binaries merge (will need to rename wallet CLI to Sui CLI after the changes), please feel free to start splitting, the binaries merging will take me a few more days.

Hi @patrickkuo , may I ask for guidance on what should be split? Will all current `wallet` functions be carried out by the `sui` binary going forward? Will `wallet` go away entirely?

In:
https://github.com/MystenLabs/sui/issues/1362#issue-1203888698
We settled upon this initial flow:
1. Install binaries
2. Start local network (rename or split from RPC Server)
3. Connect to network with Wallet

Now that we have DevNet and Fullnode, I think we should re-evaluate this entire workflow. Can you and I work together to identify the ideal flow, decisions and everything? Any other takers? @xun and @awelc come to mind. :-)

I can even schedule a meeting if we can't sort this out here or in some draft.

**Comment by Clay-Mysten** [comment]
Hi @patrickkuo , let's revisit this in our meeting tomorrow.

**Comment by Clay-Mysten** [comment]
@patrickkuo confirms he has fixed this by providing more information in the default output:
https://docs.sui.io/devnet/build/cli-client
