### ISSUE TITLE
Example not updated for Transaction_subscription in rust

### ISSUE THREAD

**Issue by 0xDevNinja** [MystenLabs/sui#20607]
## Steps to Reproduce Issue

[transaction_subscription.rs](https://github.com/MystenLabs/sui/blob/main/crates/sui-sdk/examples/transaction_subscription.rs) is not updated according to the latest changes. 

Copy and run the program.

## Expected Result

Successful subscription

## Actual Result
Error: Subscription error : Subscription only supported by WebSocket client.

**Comment by stefan-mysten** [comment]
Thanks! WS is not supported on public full nodes operated by Mysten anymore, so I will remove the example.
