### ISSUE TITLE
How to use other package in my package

### ISSUE THREAD

**Issue by qxyanda** [MystenLabs/sui#20608]
I want to use a published package in my project. I know the package's address, as well as the module and function I want to call. How can I use it in my own package?

// Move.toml
```
[package]
name = "app"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Sui = { local = "../../../../crates/sui-framework/packages/sui-framework" }

[addresses]
app = "0x0"
```

**Comment by stefan-mysten** [comment]
You will need to have a link to the repository that contains the package, if that is not your own package that you have access to locally on your machine.
Find a few more information in the book: https://move-book.com/concepts/manifest.html#dependencies

**Comment by qxyanda** [comment]
> You will need to have a link to the repository that contains the package, if that is not your own package that you have access to locally on your machine. Find a few more information in the book: https://move-book.com/concepts/manifest.html#dependencies

thank you

**Comment by stefan-mysten** [comment]
You're very welcome. Feel free to ask any other questions you have here, on Discord, or on Telegram.

**Comment by qxyanda** [comment]
> You're very welcome. Feel free to ask any other questions you have here, on Discord, or on Telegram.非常不客气。如果您有任何其他问题，请随时在此处、Discord 或 Telegram 上提出。

Also, can I specify the package I want to reference at [addresses]?

**Comment by stefan-mysten** [comment]
Yes, you can as addresses are used for creating an alias for an address. In the code, you can then use the alias instead of using the whole address.

https://move-book.com/concepts/manifest.html#addresses

**Comment by qxyanda** [comment]
> Yes, you can as addresses are used for creating an alias for an address. In the code, you can then use the alias instead of using the whole address.是的，您可以，因为地址用于为地址创建别名。在代码中，您可以使用别名而不是使用整个地址。
> 
> https://move-book.com/concepts/manifest.html#addresses

What I mean is, can I call a published package like this without using a local repository or a Git repository in [dependencies]

**Comment by qxyanda** [comment]
> > > Yes, you can as addresses are used for creating an alias for an address. In the code, you can then use the alias instead of using the whole address.是的，您可以，因为地址用于为地址创建别名。在代码中，您可以使用别名而不是使用整个地址。
> > > https://move-book.com/concepts/manifest.html#addresses
> > 
> > 
> > What I mean is, can I call a published package like this without using a local repository or a Git repository in [dependencies]我的意思是，我可以在不使用本地存储库或 [依赖项] 中的 Git 存储库的情况下调用这样的已发布包吗？
> > Like this? 像这样？
> > ```
> > [addresses]
> > app = "0x0"
> > CetusClmm = "0x1eabed72c53feb3805120a081dc15963c204dc8d091542592abaf7a35689b2fb"
> > ```
> 
> No, you cannot. It needs the source code to compile it locally to be able to reference it in your code base.不，你不能。它需要源代码在本地进行编译，以便能够在您的代码库中引用它。 You will need to use the Cetus CLMM SDK: https://github.com/CetusProtocol/cetus-clmm-sui-sdk您需要使用 Cetus CLMM SDK： https://github.com/CetusProtocol/cetus-clmm-sui-sdk

Got it!

**Comment by qxyanda** [comment]
> You can create PTBs that call different functions from the Cetus CLMM package, but you cannot work with that package in Move without the source code.

Could you please let me know how to specify a specific contract version when referencing another package? 

For example, how can I specify an older version of the cetus-clmm contract instead of the latest version?

**Comment by stefan-mysten** [comment]
Each package that is deployed will have a version and a unique object id. You will have to find all the versions of the `cetus-clmm` smart contract, and pick the one you want to use by using that version's published package id.
