### ISSUE TITLE
[event][mvp] create event store abstraction & APIs

### ISSUE THREAD

**Issue by longbowlu** [MystenLabs/sui#2060]
* an abstraction decouples storage with other components and allows a switch of storage solution easily
* the APIs should support query by 
  * transaction hash
  * object id
  * address
  * smart contract
 
 See [details](https://docs.google.com/document/d/15akzMBaYT_4edRQzOwq1OtBqDhZ68_4dMFpWy1T0KcE/edit#bookmark=id.r7vodzz60v3z)

**Comment by velvia** [comment]
It's important to be able to look up a range of events by checkpoint.
Also, if recovery from last checkpoint is desired, that implies throwing away newer events that have been stored since the last checkpoint.

**Comment by velvia** [comment]
First PR is checked in, this is done.
