### ISSUE TITLE
[wallet] SUI Wallet on Ledger Stax and Flex

### ISSUE THREAD

**Issue by berbie** [MystenLabs/sui#20657]
Dear SUI Team,

I recently got hands on my shiny new Ledger Stax and was excited to use it, but I was disappointed to find that the SUI app is not yet available for these devices.

Could you share any information on the roadmap for SUI support on the Ledger Stax? Additionally, is this the right channel to address this request, or should I direct it elsewhere?

Thank you for your hard work and dedication to improving the Ledger with SUI experience. I look forward to your updates!

Best regards,
シ berbie

**Comment by Lisa238-Dev** [comment]
> Dear SUI Team,
> 
> I recently got hands on my shiny new Ledger Stax and was excited to use it, but I was disappointed to find that the SUI app is not yet available for these devices.
> 
> Could you share any information on the roadmap for SUI support on the Ledger Stax? Additionally, is this the right channel to address this request, or should I direct it elsewhere?
> 
> Thank you for your hard work and dedication to improving the Ledger with SUI experience. I look forward to your updates!
> 
> Best regards, シ berbie


Hello @berbie 
You’re experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID SUI12097
Please see the link below to our dedicated support line:
[Sui Network DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by williamrobertson13** [comment]
Hey @berbie! We're actively working on supporting the Ledger Stax and Flex, I don't have an exact timeline but it should be available in the new year around January or February!
