### ISSUE TITLE
Replace `tweetnacl` with `@noble/curves`

### ISSUE THREAD

**Issue by mahnunchik** [MystenLabs/sui#20661]
It would be great to replace the outdated module `tweetnacl` with modern `@noble/curves`.

**Comment by hayes-mysten** [comment]
Looks like we are only using tweetnacl in the ED25519 keypair implementation, and we already have @noble/curves as a dependency for the other keypair implementations.  This seems like a reasonable improvement to make.  We can add it it our list of future improvements for the sdk that we are working on early next year.
