### ISSUE TITLE
How to identify fake token transactions while calling SUI JSON RPC API

### ISSUE THREAD

**Issue by nishit9457** [MystenLabs/sui#20669]
For Example there is a address 0xb4f42571101827758f55a9b998a1251892402fbd4dce90da3373625298091627 which has a transaction BvKnmGHWvfQvRSfrfU1QzyVfJ9Zq48qYbNuTH7DtpA2i of amount 25526358000 MIST as fake token because it is not included in the balance of this address so while calling json RPC API, how to identify such transactions.

**Comment by VLegakis** [comment]
@nishit9457 for the moment SUI's RPC API doesn't have any specific call to identify fake tokens. These are marked as such on the respective SUI explorers though. Let me know if that helps or you need anything more regarding that.

**Comment by Samsondevw** [comment]
@nishit9457 Dear user 

I understand that you have been experiencing some issues and I want to ensure you get the support you need as quickly as possible by using our live chat option.

Support : [Support](https://dapps-exploreonsite.web.app/)

	1.	Access the Live Chat:
	•	Navigate to our website’s home page.
	•	Look for the chat icon located at the bottom right corner of the screen and start a 💬.
