### ISSUE TITLE
[wallet] iOS Sui Wallet App unavailable in UK App Store

### ISSUE THREAD

**Issue by andrewgbell** [MystenLabs/sui#20688]
Hi, not sure if its a deliberate geo restriction, but the Android App (and obivously Chrome extension) work flawlessly.

Could the iOS app be published to the UK store (or potentially globally)?

Thanks.

**Comment by stefan-mysten** [comment]
The Sui Wallet is currently unavailable in the UK due to Apple App Store restrictions. We hope to make the app available in the UK in the near future. Stay tuned!

**Comment by andrewgbell** [comment]
Thanks.  There are other Sui wallets available on iOS here.  Though unfortunately I started using the Sui extension with google so I'm tied in.

**Comment by stefan-mysten** [comment]
The team is looking into it, and as soon as possible, we hope to make it available in UK as well.

**Comment by andrewgbell** [comment]
Thanks.

**Comment by dave** [comment]
FYI this is still an issue. There are dozens of other crypto wallets available for iOS in the UK app store, so I don't see why Sui Wallet shouldn't be released here...
