### ISSUE TITLE
GC old versions of objects from validator (if necessary)

### ISSUE THREAD

**Issue by mystenmark** [MystenLabs/sui#2070]
https://github.com/MystenLabs/sui/pull/1953 changes authority_store to keep all old versions of objects.

My thinking is that, at a minimum, we will delete old object versions when there is an epoch change.

However, even the versions within an epoch may eventually be too much to store, and we may need to GC old object versions at some point. The first version within an epoch and the most recent versions should both be kept forever.

Note that deleting old versions may cause issues if certificates are replayed (which was the motivation for storing objects by version in the first place). We can delete input versions after processing a cert, but if the cert is replayed, we need to be able to distinguish between a) the cert is being replayed and b) there are missing dependencies before the cert can be processed.

**Comment by velvia** [comment]
If a cert is replayed, and its effects are available (which should be the case for the vast majority), then the effects is simply returned and there is no need to reprocess anything.  Thus the need for older objects would, in the vast majority of cases, not be present.
