### ISSUE TITLE
Sui doc content issue or request

### ISSUE THREAD

**Issue by jdbertron** [MystenLabs/sui#20703]
Ever since RawSigner got deprecated and TransactionBlock got renamed, I can't figure out how to deploy a contract. I have new code that seems to execute, but fails with  Error: No sui client passed to Transaction#build, but transaction data was not sufficient to build offline.

Please provide a working example. 

```typescript
import "dotenv/config"
import  { Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";
import { fromB64 } from "@mysten/sui.js/utils";
import { SuiClient } from "@mysten/sui.js/client";
import { TransactionBlock } from "@mysten/sui.js/transactions";
import path, { dirname } from "path";
import { execSync } from "child_process";
import { fileURLToPath } from "url";
import { Transaction } from "@mysten/sui/transactions";

const priv_key = process.env.PRIVATE_KEY;
if (!priv_key) {
    console.log("Error: Priv Key not set in env");
    process.exit(1);
}

const keypair = Ed25519Keypair.fromSecretKey(fromB64(priv_key).slice(1));

const node_url = process.env.NODE_URL ;
if (!node_url) {
    console.log("Error: Node url not found in env");
    process.exit(1);
}

const client = new SuiClient({ url: node_url });
const path_to_contract = path.join(dirname(fileURLToPath(import.meta.url)), "./contracts/sources");
console.log("Building contract")
const { dependencies, modules } = JSON.parse(execSync(
    `sui move build --dump-bytecode-as-base64  --path ${path_to_contract}`, 
    { encoding: "utf-8" }
));
console.log("Deploying contract");
console.log(`Deploying from: ${keypair.toSuiAddress()}`);

const deploy_trx = new Transaction();
deploy_trx.setSender(keypair.getPublicKey().toSuiAddress());

const [upgrade_cap] = deploy_trx.publish({
    modules, dependencies
});

const signedTransaction = await deploy_trx.sign({ signer: keypair });

function stringToUint8Array(str: string): Uint8Array {
    const buf = new ArrayBuffer(str.length);
    const bufView = new Uint8Array(buf);
    for (let i = 0, strLen = str.length; i < strLen; i++) {
        bufView[i] = str.charCodeAt(i);
    }
    return bufView;
}
const addressBytes = stringToUint8Array(keypair.getPublicKey().toSuiAddress());
deploy_trx.transferObjects([upgrade_cap], deploy_trx.pure(addressBytes));


const { objectChanges, balanceChanges } = await client.executeTransactionBlock({
    transactionBlock: signedTransaction.signature,
    options: {
        showBalanceChanges: true,
        showEffects: true,
        showEvents: true,
        showInput: true,
        showObjectChanges: true,
        showRawInput: false
    },
    signature: signedTransaction.bytes
});

console.log(objectChanges, balanceChanges);
```

**Comment by hayes-mysten** [comment]
```ts
import 'dotenv/config';
import { Ed25519Keypair } from '@mysten/sui/keypairs/ed25519';
import { fromBase64 } from '@mysten/sui/utils';
import { SuiClient } from '@mysten/sui/client';
import path, { dirname } from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';
import { Transaction } from '@mysten/sui/transactions';

const priv_key = process.env.PRIVATE_KEY;
if (!priv_key) {
	console.log('Error: Priv Key not set in env');
	process.exit(1);
}

const keypair = Ed25519Keypair.fromSecretKey(fromBase64(priv_key).slice(1));

const node_url = process.env.NODE_URL;
if (!node_url) {
	console.log('Error: Node url not found in env');
	process.exit(1);
}

const client = new SuiClient({ url: node_url });
const path_to_contract = path.join(dirname(fileURLToPath(import.meta.url)), './contracts/sources');
console.log('Building contract');
const { dependencies, modules } = JSON.parse(
	execSync(`sui move build --dump-bytecode-as-base64  --path ${path_to_contract}`, {
		encoding: 'utf-8',
	}),
);
console.log('Deploying contract');
console.log(`Deploying from: ${keypair.toSuiAddress()}`);

const deploy_trx = new Transaction();
deploy_trx.setSender(keypair.getPublicKey().toSuiAddress());

const [upgrade_cap] = deploy_trx.publish({
	modules,
	dependencies,
});

deploy_trx.transferObjects([upgrade_cap], keypair.getPublicKey().toSuiAddress());

const { objectChanges, balanceChanges } = await client.signAndExecuteTransaction({
	signer: keypair,
	transaction: deploy_trx,
	options: {
		showBalanceChanges: true,
		showEffects: true,
		showEvents: true,
		showInput: true,
		showObjectChanges: true,
		showRawInput: false,
	},
});

// If you want to sing and execute separately:
const { bytes, signature } = await keypair.signTransaction(await deploy_trx.build({ client }));
const { objectChanges, balanceChanges } = await client.executeTransactionBlock({
	transactionBlock: bytes,
	signature,
	options: {
		showBalanceChanges: true,
		showEffects: true,
		showEvents: true,
		showInput: true,
		showObjectChanges: true,
		showRawInput: false,
	},
});

console.log(objectChanges, balanceChanges);
```

**Comment by hayes-mysten** [comment]
the migration guide here might also be helpful: https://sdk.mystenlabs.com/typescript/migrations/sui-1.0

**Comment by stefan-mysten** [comment]
@jdbertron hope that the updated example from @hayes-mysten and the migration guide will help you here. Feel free to let us know otherwise.

**Comment by jdbertron** [comment]
Thanks. I'll apply the migratiin stuff tomorrow.   
  

  

  

  
  
  
  
  
>

**Comment by jdbertron** [comment]
That worked. Thanks.

**Comment by shareefirstdex** [comment]
I got an issue at signAndExecuteTransaction:
file:///C:/Users/JSON%20TECHNOLOGIES/projects/updates/node_modules/@mysten/sui/dist/esm/client/http-transport.js:59
      throw new JsonRpcError(data.error.message, data.error.code);
            ^

JsonRpcError: Internal error
at SuiHTTPTransport.request  {
  code: -32603,
  type: 'InternalError'
}

how can i resolve this
Node.js v22.19.0

import fs from 'fs';
import dotenv from 'dotenv'
import { bech32 } from 'bech32';
import { Ed25519Keypair } from '@mysten/sui/keypairs/ed25519';
import { SuiClient } from '@mysten/sui/client';
import { Transaction } from '@mysten/sui/transactions';

dotenv.config({})

const priv_key = process.env.PRIV_KEY || "suiprivkey1qr24cdhsj2unp2xquj386leten06qs4kksvxas0nhg39fnfj4he43j30fj4";
if (!priv_key) {
	console.log('Error: Priv Key not set in env');
	process.exit(1);
}

function decodeSuiPrivateKey(suiKey) {
	const { words } = bech32.decode(suiKey);
	const bytes = bech32.fromWords(words);
	return Uint8Array.from(bytes);
}

// Decode bech32 suiprivkey → bytes; drop the first byte (scheme flag)
const decodedKey = decodeSuiPrivateKey(priv_key);
const secretKey = decodedKey.slice(1, 33);
console.log('Secret Key bytes length:', secretKey.length);
const keypair = Ed25519Keypair.fromSecretKey(secretKey);

// // RPC
const RPC_URL = process.env.RPC_URL;

if (!RPC_URL) {
	console.log('Error: Node url not found in env');
	process.exit(1);
}

const client = new SuiClient({ url: RPC_URL });
// Load modules/dependencies from local file.json
const { modules, dependencies } = JSON.parse(
	fs.readFileSync('./file.json', 'utf8')
);
console.log('Deploying contract');
console.log(`Deploying from: ${keypair.toSuiAddress()}`);

const deploy_trx = new Transaction();
deploy_trx.setSender(keypair.getPublicKey().toSuiAddress());

const [upgrade_cap] = deploy_trx.publish({
	modules,
	dependencies,
});


deploy_trx.transferObjects([upgrade_cap], keypair.getPublicKey().toSuiAddress());
deploy_trx.setGasPrice(1000000000);
deploy_trx.setGasBudget(20000000000);


const { objectChanges, balanceChanges } = await client.signAndExecuteTransaction({
	signer: keypair,
	transaction: deploy_trx,
	options: {
				showBalanceChanges: true,
				showEffects: true,
				showEvents: true,
				showInput: true,
				showObjectChanges: true,
				showRawInput: false,
			},
});

// If you want to sign and execute separately:
// const { bytes, signature } = await deploy_trx.sign({client, signer:keypair});
// const { objectChanges, balanceChanges } = await client.executeTransactionBlock({
// 	transactionBlock: bytes,
// 	signature,
// 	options: {
// 		showBalanceChanges: true,
// 		showEffects: true,
// 		showEvents: true,
// 		showInput: true,
// 		showObjectChanges: true,
// 		showRawInput: false,
// 	},
// });

console.log(objectChanges, balanceChanges);
