### ISSUE TITLE
Support shared object in batch transaction

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#2071]
To make shared object transaction benchmarking comparable with owned object transactions, we probably want to support shared object in batch tx too.
This may not be that hard. Just need to confirm a few things.

@oxade @asonnino

**Comment by asonnino** [comment]
We probably need to support streaming on the authority. The authority currently processes one shared object transaction per TCP connection and blocks it until processing is completely done. Ideally, it should accept a stream of objects and send back replies as they become available.
