### ISSUE TITLE
[GraphQL] How to get a list of transactions by address?

### ISSUE THREAD

**Issue by mahnunchik** [MystenLabs/sui#20723]
If I understand correctly, RPC API is no longer being developed and now I have to use GraphQL.

I realized that neither [the documentation](https://docs.sui.io/guides/developer/getting-started/graphql-rpc) nor [the examples](https://github.com/MystenLabs/sui/tree/releases/sui-graphql-rpc-v2024.1.0-release/crates/sui-graphql-rpc/examples) have an answer to the logical question.

How to get a list of transactions?

* By single address
* Incoming and outgoing
* Sorted by date from newest to oldest
* Paginated
* Including basic information like: sender, recipient, amount, token, fee

My attempt here:

```graphql
query fff($affectedAddress: SuiAddress) {
  transactionBlocks(
    filter: { affectedAddress: $affectedAddress }
    last: 10
  ) {
    nodes {
      digest,
      sender {
        address
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
```

I don't understand yet how to get amount, token and fee.

---

I think the answer to such trivial question should be added to the documentation: https://docs.sui.io/guides/developer/getting-started/graphql-rpc

**Comment by mahnunchik** [comment]
Related issues:

* https://github.com/MystenLabs/sui/issues/20674
* https://github.com/MystenLabs/sui/issues/20718

**Comment by stefan-mysten** [comment]
@mahnunchik GraphQL is in beta and will not be ready for a while. We do not recommend to use it for production needs.

Thanks for the suggestion on more examples.

**Comment by stefan-mysten** [comment]
You're probably looking for `effects`, and then for `gasEffects` and `balanceChanges`

**Comment by mahnunchik** [comment]
@stefan-mysten Why it is closed? There is no example added yet. Please do not close the issue at least until a solution is proposed here.

**Comment by stefan-mysten** [comment]
Check the examples in the main branch: https://github.com/MystenLabs/sui/tree/main/crates/sui-graphql-rpc/examples/transaction_block_connection

We also welcome PRs, so feel free to submit one. 

It's closed because we do not track issues via GitHub, but we have our own internal tool where I created an item to look over this. Thanks!
