### ISSUE TITLE
Warnings prevent publishing

### ISSUE THREAD

**Issue by MaithreyaSitaraman** [MystenLabs/sui#2088]
While this is a minor issue, it is certainly an irritant to developers. A warning (no error in the code) will prevent a developer from publishing. 

A minimal example is a an empty smart contract with a single import, e.g:

module Games::Test {

use Sui::ID::VersionedID;

}

Attempting to publish this will raise the error: 

3 │ use Sui::ID::VersionedID;
  │              ^^^^^^^^^^^ Unused 'use' of alias 'VersionedID'. Consider removing it

and will fail to publish

**Comment by sblackshear** [comment]
Thanks for flagging this! It is a longstanding papercut that needs to be addressed in upstream Move, but we should fix it.
