### ISSUE TITLE
[gossip] Flaky Tests for `test_gossip_plain`

### ISSUE THREAD

**Issue by oxade** [MystenLabs/sui#2092]
Besides `authority_server::server_tests::test_subscription`, another test is failing randomly on local
```
authority_active::gossip::tests::test_gossip_plain

thread 'authority_server::server_tests::test_subscription' panicked at 'assertion failed: `(left == right)`
  left: `20`,
 right: `15`', sui_core/src/unit_tests/server_tests.rs:213:5
```

**Comment by gdanezis** [comment]
Yeah I think this is the test we are trying to stabilise, with the mysterious interval that fires multiple times. Thanks looking into it.

**Comment by gdanezis** [comment]
I have not seen flakyness in a while now, due to many fixes. Should we close this or is it still on? @lxfind @laura-makdah
