### ISSUE TITLE
`delete_child_object` allows bypassing object unpacking rules

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#2123]
Caught by @sblackshear :

I think this API is equivalent to a polymorphic delete, which we never want to have in Move because it takes away the ability to enforce conditions on the destruction of an object. For example, if I have a c: Coin<SUI> and want to burn the coin without decreasing total_value (thereby breaking the invariant that the sum of the value all Sui coins should be equal to TreasuryCap.total_value), I could do:
// in some previous tx, create a ChildRef that points at c, then
let ref = ... 
Transfer::delete_child_object(c, ref)
// there are value(c) fewer coins in the world, but the total_value remains the same
More generally, any module that wants to enforce some condition on the destruction of its objects (e.g., can only delete an empty Option or empty Vector) will be undermined by the existence of this API. I think we need to get rid of it and find another way to safely eliminate ChildRef's

**Comment by sblackshear** [comment]
Fixed by https://github.com/MystenLabs/sui/commit/d5befa26e8b7e1cb5e3626465a03d8bd8b5880db
