### ISSUE TITLE
Support tabs in Dev Portal

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#2141]
See the request:
https://mysten-labs.slack.com/archives/C02GD7J9HUM/p1653180336852319

And the solution:
https://docusaurus.io/docs/markdown-features/tabs

Eng sounds willing to provide the contents if we set up the infrastructure. Adding all requisite parties. Let me know how I can help.

**Comment by randall-Mysten** [comment]
Closing this issue - this is covered by other ongoing issues and projects
