### ISSUE TITLE
Explorer: Display Explorer specific statistics

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#2153]
Scope whether we want to support these by TestNet

- Number of objects stored on Sui
- Number of smart contracts/packages on Sui
- Number of bytes stored on Sui
- See top addresses (with most transactions sent/received)
- See top package (most used/called)

**Comment by bwann52** [comment]
tagging @oxade as he may have a recommended solution or more context

**Comment by oxade** [comment]
I think the easiest place to do these might not be in the explorer but in the full node (or the event subsystem) which has a more complete view of the system.

Here's a basic way it can be done in the full node

**Number of objects stored on Sui:** tracked by keeping a counter whenever full node db is updated
**Number of smart contracts/packages on Sui:** tracked by keeping a counter whenever full node package index db is updated 
**Number of bytes stored on Sui:** tracked by keeping a counter whenever full node db is updated
**See top addresses (with most transactions sent/received):** tracked by keeping a counter per address in input/outputs
**See top package (most used/called):** tracked by intercepting the package id at Move calls

**Comment by 666lcz** [comment]
@oxade thanks for the pointer! @mystenmark @bmwill do you think fullnode can/should support these?
