### ISSUE TITLE
[Sui Framework] Finalize programability

### ISSUE THREAD

**Issue by tnowacki** [MystenLabs/sui#2173]
https://www.notion.so/mystenlabs/Sui-Framework-Programming-Model-Finalization-dae87b3987cc4398962c52477eade9b8

Need decisions/designs on:
- Restricted transfers
- Wrapped objects
- Children of shared objects 
- Shared object deletion (#2083)

**Comment by bholc646** [comment]
@tnowacki can you give a brief update on where this is at? Or are we ready to close this out? Thanks!

**Comment by tnowacki** [comment]
I think we are ready to close this, thanks!
