### ISSUE TITLE
Wallet CLI: Simple command to publish a new Fungible Token Module

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#2192]
For example, the user should be able to
do `wallet create-new-token --symbol "USDC" 
 --total-supply 10000` to publish a new Move Module
similar to the[ th](https://github.com/MystenLabs/sui/blob/main/sui_programmability/framework/sources/SUI.move)e SUI Module

The existin[g ](https://docs.sui.io/build/wallet#creating-example-nfts)[`wallet create-example-nft` comma](https://docs.sui.io/build/wallet#creating-example-nfts)nd
is a good reference

**Comment by gegaowp** [comment]
@666lcz sry I dropped the ball here, do we have this now?
