### ISSUE TITLE
[Sui Framework] Remove modules that should not be in the framework

### ISSUE THREAD

**Issue by sblackshear** [MystenLabs/sui#2227]
These modules should be removed:
- `ObjectBasics` (should only be in tests
- `DevNetNFT` (the devnet release process should put this in genesis or publish it afterward, but it shouldn't be part of the mainnet or testnet framework)

For these, I'm not so sure:
- `ERC721Metadata` (might or might not want it. probably do want it)
- `Url` (audit, fix TODOs around `URLCommitment`, rename to `URL`)
- `Collection` and `Bag`: are these useful on their own, or are they design patterns that other code will need to copy?

**Comment by kayandra** [comment]
@sblackshear regarding the `DevNetNFT` being removed, I assume we get a proper `NFT` module?

Also, I would like to suggest adding a collection struct and some immutable meta data to the NFTs. 

For example, the NFT should directly hold the creator address, supply

```move
/// Save for the collection name, I think all the other properties should be immutable.
struct Collection has key, store {
	id: UID,
	/// Name of the collection
	name: string::String,
	/// Description of the collection
	description: string::String,
	/// Collection link??
	uri: string::String,
	/// Creator
	creator: address
	/// Supply
	max_supply: u64 
}

struct NFT has key, store {
	id: UID, 
	/// immutable or use a global dummy to signify the NFT doesn't belong in a collection
	collection: collection_object_id, 
	/// Creator 
	creator: address // immutable
	/// Name for the token
	name: string::String,
	/// Description of the token
	description: string::String,
	/// URL for the token
	url: Url,
	// TODO: allow custom attributes
}
```
