### ISSUE TITLE
wallet switch --gateway exists in docs, but is not a valid command

### ISSUE THREAD

**Issue by MaithreyaSitaraman** [MystenLabs/sui#2229]
I am trying publish to DevNet rather than my local machine. The docs here: https://docs.sui.io/build/wallet#manually-change-the-gateway-url, suggest that I can run the command 

`wallet switch --gateway https://gateway.devnet.sui.io:443` 

in order to do this. 

However, this command is not a registered command in sui. I get the error: 

`error: Found argument --gateway which wasn't expected, or isn't valid in this context. If you tried to supply --gateway as a value rather than a flag, use -- --gateway`

and indeed "wallet switch --help" confirms that there is no --gateway flag allowed

**Comment by oxade** [comment]
@MaithreyaSitaraman thanks for this feedback. What commit did you build the wallet off of?

**Comment by MaithreyaSitaraman** [comment]
I got it to work. The issue was that sui binaries were incorrectly installed. The re-installation of sui binaries did the trick.

Thanks so much once again, I would not have thought to reinstall the binaries.
