### ISSUE TITLE
Tests consistently failing due to libc crash, related to rocksdb

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#2230]
Now consistently seeing libc++ errors when running tests (i.e. every time on Mac). I assume this is rocksdb? I am curious why this is suddenly a problem now but not before.
There are a few variants:
 libc++abi: terminating
libc++abi: Pure virtual function called!

The error happens most often when running `lock_service::tests::test_lockservice_conc_acquire_init`
Also sometimes failing in CI (which means Linux is also affected):
https://github.com/MystenLabs/sui/runs/6584926388?check_suite_focus=true

**Comment by gdanezis** [comment]
These happen for me in tests that seem to open and close the DB and re-open it. Is there any special logic we need to call to cleanly close the DB or the DFs in the DB that we have not implemented?

**Comment by velvia** [comment]
RocksDB Rust API does not have an explicit close method, but seems to close on drop, which is really annoying.  However I have a PR out.

**Comment by velvia** [comment]
Fixed by @bmwill 's PR, though I had one out as well.
