### ISSUE TITLE
[validator] specify effectively shared objects as tx inputs with id, not (id, version)

### ISSUE THREAD

**Issue by sblackshear** [MystenLabs/sui#2249]
Today, we require effectively shared objects (i.e., objects owned directly or transitively be a shared object) to be specified as tx inputs using an `(id, version)` pair.
- This will lead to the "Cardano problem" where it is very difficult for users to craft non-failing transactions that are touching the same effectively shared object (since they will be unable to accurately predict the version, resulting in a failed tx whenever the version doesn't match).
- One solution is to require effectively shared objects to be specified as id inputs to txes (just like shared objects).

**Comment by bholc646** [comment]
Closing this in favor of https://github.com/MystenLabs/sui/issues/4203
