### ISSUE TITLE
[sui-core] Hitting an expect(...) in the store

### ISSUE THREAD

**Issue by gdanezis** [MystenLabs/sui#2253]
As part of the active checkpointing work I hit the expect here:
https://github.com/MystenLabs/sui/blob/495f307eea0b4c43e285712d5737a62d389aefe9/crates/sui-core/src/authority/authority_store.rs#L354-L373

Investigating why / how this is happening. Currently a workaround is:
```
    /// Read a transaction envelope via lock or returns Err(TransactionLockDoesNotExist) if the lock does not exist.
    pub async fn get_transaction_envelope(
        &self,
        object_ref: &ObjectRef,
    ) -> Result<Option<TransactionEnvelope<S>>, SuiError> {
        let transaction_option = self
            .lock_service
            .get_lock(*object_ref)
            .await?
            .ok_or(SuiError::TransactionLockDoesNotExist)?;

        match transaction_option {
            Some(tx_digest) => {
                return Ok(self.transactions
                    .get(&tx_digest)?);
                    // .expect("Stored a lock without storing transaction?"),
                },
            None => Ok(None),
        }
    }
```

**Comment by gdanezis** [comment]
hey @mystenmark / @velvia , this may or may not be related to what we were discussing about locks / other data consistency.

**Comment by velvia** [comment]
@gdanezis I'll put in a quick fix for this.  That expect shouldn't be there any more, because there is a possibility the transaction might not exist yet as the lock is being written first.  There is another issue about atomicity of transaction and locks.   The proper fix (without involving the atomicity thing) is just to retry, because most likely the read happened before the transaction was written.

**Comment by velvia** [comment]
Note this is affected by https://github.com/MystenLabs/sui/issues/1990
but I'll probably just put in a quick fix based on retries now.

**Comment by velvia** [comment]
PR is out: https://github.com/MystenLabs/sui/pull/2356

**Comment by lxfind** [comment]
@velvia Any updates on this?

**Comment by velvia** [comment]
There was a back and forth about how to resolve this in the long term, whether we should move the transactions table into lock service.  I think we are now leaning away from putting it in the lock service, I think that probably doesn't make sense for the long term.  Instead:
1) Will rebase this PR and improve on it as the solution for now, and also
2) have the transactions be deleted when new locks are initiated and old transactions finished  in validators/fullnodes.

**Comment by lxfind** [comment]
@velvia please file issues for any remaining long-term TODO and close this one.

**Comment by velvia** [comment]
It's been resolved by PRs that change the expect and retries, thus closing.
Can't think of long term TODO for this one yet, won't know about it until we do more exploratory refactoring.
