### ISSUE TITLE
API calls do not create objects even when successful (am I overlooking something silly, or is something not implemented yet?)

### ISSUE THREAD

**Issue by MaithreyaSitaraman** [MystenLabs/sui#2299]
I have a package on devnet (package id 092a8e7ad51997bf4ec4b925b1bf0a9f054ad32a).

I can call a function "single_input_mint" on this package the standard way and mint myself a DiscountCoupon by running:

`wallet call --function single_input_mint --module NFTHandler --package 0x092a8e7ad51997bf4ec4b925b1bf0a9f054ad32a --args 10 --gas-budget 1000`

and everything works great.

However, if I attempt to run the same function via an API call, namely: 

`curl --location --request POST 'https://gateway.devnet.sui.io:443' --header 'Content-Type: application/json' --data-raw '{"jsonrpc": "2.0", "method": "sui_moveCall", "params": ["aaf595adb8ec1c9f867f2cb6229b33aaf55e81e9", "092a8e7ad51997bf4ec4b925b1bf0a9f054ad32a", "NFTHandler", "single_input_mint", [], [10], "1eb58bd1268314d5cdaee7fbb6ebbb7bb4f43892", 1000], "id": 0}' | json_pp`

(note: here, aaf595adb8ec1c9f867f2cb6229b33aaf55e81e9 is my address and 1eb58bd1268314d5cdaee7fbb6ebbb7bb4f43892 is my gas id).

the response shows status code 200 (success), but there is no NFT minted on the DevNet. And I can confirm using the sui explorer. What do I need to do to make sure objects are created on the DevNet with an API call and what am I doing wrong? (or is this a bug / not yet operational)

_For your reference, the (successful) response I get from the API call is:_ 

`
{
   "jsonrpc" : "2.0",
   "result" : {
      "txBytes" : "VHJhbnNhY3Rpb25EYXRhOjoAAgkqjnrVGZe/TsS5JbG/Cp8FStMqAQAAAAAAAAAgWmURbqN3//E3KZl7LVhqrt3G98e1TssW6km/IePtZZMKTkZUSGFuZGxlchFzaW5nbGVfaW5wdXRfbWludAABAAEKqvWVrbjsHJ+Gfyy2IpszqvVegeketYvRJoMU1c2u5/u267t7tPQ4kgUAAAAAAAAAIFbb/H5/mbCOB2XNHSdjqhE+4Rl9wifnA8ni2wtWVC9n6AMAAAAAAAA=",
      "gas" : {
         "version" : 5,
         "objectId" : "0x1eb58bd1268314d5cdaee7fbb6ebbb7bb4f43892",
         "digest" : "Vtv8fn+ZsI4HZc0dJ2OqET7hGX3CJ+cDyeLbC1ZUL2c="
      },
      "inputObjects" : [
         {
            "MovePackage" : "0x092a8e7ad51997bf4ec4b925b1bf0a9f054ad32a"
         },
         {
            "ImmOrOwnedMoveObject" : {
               "digest" : "Vtv8fn+ZsI4HZc0dJ2OqET7hGX3CJ+cDyeLbC1ZUL2c=",
               "objectId" : "0x1eb58bd1268314d5cdaee7fbb6ebbb7bb4f43892",
               "version" : 5
            }
         }
      ]
   },
   "id" : 0
}

`

**Comment by 666lcz** [comment]
@MaithreyaSitaraman Thanks for submitting an issue! Would you mind sharing the source code of your Move package? It would be also helpful to republish the Move package to DevNet if possible(We did a data wipe recently so the package does not exist on DevNet anymore).

**Comment by patrickkuo** [comment]
@MaithreyaSitaraman, the “sui_moveCall” method creates an unsigned transaction, the response is the “txBytes” which will need to be signed, and submit to the server using “sui_executeTransaction” method to finalise the call, please see examples in https://docs.sui.io/build/json-rpc#sui_movecall

**Comment by MaithreyaSitaraman** [comment]
@666lcz @patrickkuo - Thanks for the responses!

 I did not realize that transactions need to be signed in this way. Will attempt the solution and close the issue once resolved.

Thanks once again!
