### ISSUE TITLE
Explorer: Add a "raw json" for debugging purposes

### ISSUE THREAD

**Issue by damirka** [MystenLabs/sui#2303]
## Problem

For Move development it is nice to be able to read the contents of the Object. Mainly to share and just verify that everything works as expected. 

## Suggested solution

Since we already fetch data and render it, perhaps we could add a button like "show raw json" (or with a different name), which toggles the full object description and renders it as a `<pre>` tag.

**Comment by 666lcz** [comment]
With https://github.com/MystenLabs/sui/issues/1983, we will render the full result as returned by the existing RPC endpoint using something like https://github.com/mac-s-g/react-json-view . Will this be sufficient? Or do you want the raw bytes?
