### ISSUE TITLE
Add hashing intent identifier to SuiAddress and ObjectID generation

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/sui#2305]
Atm we use plain hashing of PubKeyBytes to generate an address, but due to agility and mainly multi-sig (whose input payload is bigger), it is theoretically possible to provide pubKeys as inputs that match the bytes of an ObjectID hash input. We need a domain separation strategy.

**Comment by kchalkias** [comment]
Will work on this the week July 18-22

**Comment by lxfind** [comment]
@kchalkias will open another one
