### ISSUE TITLE
RPC: return string for Big numbers

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#2328]
RPC server right now returns almost all numbers as u64 while javascript `number` only supports up to 2^53. 

1. convert u64 in https://github.com/MystenLabs/sui/blob/main/crates/sui-json-rpc-types/src/lib.rs to string
2. remove the usage of LosslessJSON
3. beyond Sui JSON, we need to make sure all u64 numbers are strings (example for gas used)

**Comment by oxade** [comment]
Spoke to @patrickkuo who had plans for Sui JSON
I will make the minimal necessary changes, and while we decide on the best plan of action for Sui JSON as a whole particularly wrt SDK, RPC, CLI

**Comment by oxade** [comment]
Part 1: convert u64 in https://github.com/MystenLabs/sui/blob/main/crates/sui-json-rpc-types/src/lib.rs to string
PR: https://github.com/MystenLabs/sui/pull/6608

**Comment by oxade** [comment]
Spoke with @Jordan-Mysten, and we decided we decided on the following plan
**convert u64 in https://github.com/MystenLabs/sui/blob/main/crates/sui-json-rpc-types/src/lib.rs to string**
already merged.

**remove the usage of LosslessJSON**
will be handled by @Jordan-Mysten 

**replace the usage of the BN library with bigint**
not needed

**beyond Sui JSON, we need to make sure all u64 numbers are strings (example for gas used)**
will be phased in gradually.
