### ISSUE TITLE
[RPC API] data model w/ focus on read API’s: certs, objects

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#237]
- get object
- get certificate
- client service status/config

**Comment by todd-mystenlabs** [comment]
@stella3d , @patrickkuo, @lxfind  - what state is this in?

**Comment by todd-mystenlabs** [comment]
(Also, I'm taking a guess on the priority)

**Comment by patrickkuo** [comment]
Once JSON-RPC server PR is merged, we will need to work on OpenRPC documentation -- to replace Postman Documentation. Also we will need to refactor/simplify GatewayAPI's response objects to make it easier to be consumed by downstream, current model contains move object bytes and move objects layout etc, which might not be very useful to downstream systems.

**Comment by todd-mystenlabs** [comment]
Need more specific issues.  Closing this one, too general.
