### ISSUE TITLE
[checkpoints] Execute a block of transactions / effects within a checkpoint

### ISSUE THREAD

**Issue by gdanezis** [MystenLabs/sui#2405]
Currently, execution is done on the basis of a certificate for the current epoch. However, once checkpoints are formed, stored and retrieved a validator or full node may wish to execute a full checkpoint block even from a past epoch and without reference to the full certificate of each transaction. 

To enable this we must:
* [ ] Order transactions within checkpoints in a canonical causal execution order (not a set). This order should be the same for all validators creating the same checkpoint, and be protected by the collective signature.
* [ ] Allow the execution of a block of transactions with reference to a checkpoint block. That includes the corner cases of shared object transactions, where the locks are not created via consensus but instead via the checkpoint.
* [ ] Where normally certificates might be stored, store instead a reference to the checkpoint to authenticate the execution. When a cert sync is requested from another node, the checkpoint should be used to provide evidence of execution + correctness.

**Comment by mystenmark** [comment]
Execution is partially addressed by #2943 (for the case of an online validator running the checkpoint process), and I have a PR coming soon for syncing at startup (prior to starting checkpoint process).
