### ISSUE TITLE
Wallet-ext: [p0] Add a tab for showing transactions

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#2407]
Similar to https://github.com/MystenLabs/sui/issues/1191, add a tab to show all transactions related to the wallet address: https://github.com/MystenLabs/sui/issues/1191 in the wallet extension.

**Comment by gegaowp** [comment]
Does this include the NFT transactions as well?

**Comment by Jibz1** [comment]
Done https://github.com/MystenLabs/sui/pull/2529
