### ISSUE TITLE
Fullnode gossip to remember the last tx received from each validator

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#2416]
The current gossip implementation on full-node will always ask to follow from transaction sequence number 0 every 60s.
This is not scalable and will likely break soon once we have enough tx.
(note this seems not an issue for validator, as it always ask for the latest, but how does a validator deal with breakages?)

**Comment by gdanezis** [comment]
I think the solution to this is not to start at the last seen sequence number, but rather to start at the latest number by passing in None to the start index:
https://github.com/MystenLabs/sui/blob/50300a44bccc39a4ae74701d663e9a489b8b384a/crates/sui-core/src/authority_active/gossip/mod.rs#L46-L51

I believe this is already the case? Ie I see the index set to None, which means the authority substitutes it for the latest sequence number. We should confirm.

**Comment by gdanezis** [comment]
> (note this seems not an issue for validator, as it always ask for the latest, but how does a validator deal with breakages?)

For older Txs we should rely on checkpoints to catch up I think?

**Comment by lxfind** [comment]
> > (note this seems not an issue for validator, as it always ask for the latest, but how does a validator deal with breakages?)
> 
> For older Txs we should rely on checkpoints to catch up I think?

Once it catches up to the latest checkpoint, how does it get tx it missed after the latest checkpoint?
