### ISSUE TITLE
Total transaction count isn't accurate

### ISSUE THREAD

**Issue by bmwill** [MystenLabs/sui#2484]
After doing some debugging with @mystenmark we determined that the api for querying the total transaction count could be inaccurate and differ between fullnodes due to how a node determines how many transactions it has (IIRC it queries the next seq number but seq numbers could have gaps currently). We'll probably want to tighten that up so that its accurate.

**Comment by mystenmark** [comment]
IMO we should just stop reporting total transaction numbers. It's not a meaningful number for users.
