### ISSUE TITLE
[dev.net] centralized logging

### ISSUE THREAD

**Issue by tharbert** [MystenLabs/sui#2509]

**Comment by allan-bailey** [comment]
+1 for Loki (integrates with Grafana).

Also, we need to decide on a standard logging format.

**Comment by allan-bailey** [comment]
https://jsonlines.org/ I'll start recommending jsonlines format.  this would make it easy for loki+grafana to parse and do useful things.
The other option is something like <timestamp> <key1=val1> ...

**Comment by tharbert** [comment]
@bmwill / @mystenmark / @velvia / @huitseeker

Do we have a structured logging standard currently? (Is the Tokio tracing library just used in Sui?)

Any thoughts on @allan-bailey's suggestion of jsonlines?
