### ISSUE TITLE
Install on win11 + wsl2 (ubuntu22.04 LTS) fails

### ISSUE THREAD

**Issue by lshoo** [MystenLabs/sui#2521]
I follow the build docs (https://docs.sui.io/build/install) to insatll the sui, use the command to install binaries:
``` cargo install --locked --git https://github.com/MystenLabs/sui.git --branch "devnet" sui ``` ,
but get the error:
```
error: failed to get `mysten-network` as a dependency of package `sui v0.2.0 (/home/lshoo/.cargo/git/checkouts/sui-6ac459c53b1b685a/882516a/crates/sui)`

Caused by:
  failed to load source for dependency `mysten-network`

Caused by:
  Unable to update https://github.com/MystenLabs/mysten-infra?rev=988cad6aaafac84d52a93227a16867bf27c1ea4c#988cad6a

Caused by:
  failed to clone into: /home/lshoo/.cargo/git/db/mysten-infra-e26c6e4a001ad289

Caused by:
  process didn't exit successfully: `git fetch --tags --force --update-head-ok 'https://github.com/MystenLabs/mysten-infra' '+refs/heads/*:refs/remotes/origin/*' '+HEAD:refs/remotes/origin/HEAD'` (exit status: 128)
  --- stderr
  fatal: unable to access 'https://github.com/MystenLabs/mysten-infra/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
```
What happen?
and why the sui version is 0.2.0, not the latest 0.4.0?

OS: win11 + wls2 (ubuntu 22.04 LTS)
CPU: Intel i5-12500H

Thanks!

**Comment by longbowlu** [comment]
Hi @lshoo , this looks like a ssl issue (the git server terminated your connection for some reason). 
Can you try to uninstall and reinstall git? This may solve the problem. 
Reference: https://stackoverflow.com/a/52530617/4803911

**Comment by lshoo** [comment]
I‘ve tried more than 20 times，and installed successfully。
Thanks！@longbowlu

**Comment by lshoo** [comment]
Maybe my network problem in China, try the install command util install successfully.
I also require to install these extra:
``` sudo apt install clang ```
``` sudo apt-get install pkg-config libssl-dev https://docs.rs/openssl/latest/openssl ```
