### ISSUE TITLE
Figure out sender sig auditing issue

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#2536]
https://mysten-labs.slack.com/archives/C02GD7J9HUM/p1654875644603759

cc @bmwill
@kchalkias will write a doc first explaining the auditing issue

**Comment by kchalkias** [comment]
We had a long chat re user sigs and have documented all 4 possible solutions in Notion. There is still a decision to be made between the two best candidate options.

**Comment by lxfind** [comment]
may want to wait till consensus stabilizes before we do any major change
also a product decision
will follow up off-line

**Comment by kchalkias** [comment]
Done in https://github.com/MystenLabs/sui/pull/3586
