### ISSUE TITLE
[authority] Discussion about checking only quorum signatures in handle_confirmation vs also checking well-formedness

### ISSUE THREAD

**Issue by patrickkuo** [MystenLabs/sui#254]
> Also it's unnecessary to check the digest if the certificate is valid?

This is interesting and gets at a philosophical issue: should an authority commit *any* certificate that a quorum of validators have signed (even if, e.g., the certificate is obviously malformed), or only one that is both signed and also passes all well-formedness checks (e.g, this matching digest)? In theory, this distinction should only be observable in:
1. a system where the BFT assumption has been violated (hopefully unlikely)
2. a system where the authority running a buggy or outdated implementation of the protocol that rejects certificates that correct authorities would accept (much more likely). i.e., the authority on which the checks fail is accidentally Byzantine

We should probably have a broader discussion about this decision, but my preference is to perform all validity checks on a certificate in addition to checking the quorum signatures. This allows honest authorities to avoid committing bad certificates even in a system where the BFT assumption has been violated in the case of (1), and to detect a problem with the software they are running earlier in the case of (2).

> it might not make sense to have this check in handle_confirmation_order, this method is expected to receive old certificates and return and ok response, however we do not keep old object so it's hard to retrieve old object ref.

Ah, good point. We definitely don't want to keep the old object around to do this check. If we decide to include this check (pending the bigger discussion above), perhaps we can do it later so it won't run on the code path that returns an already-committed certificate.

_Originally posted by @sblackshear in https://github.com/MystenLabs/fastnft/issues/217#issuecomment-1019614849_

**Comment by gdanezis** [comment]
We are now going with checking all things in both phases, and the reconfig logic forces us to do this.
