### ISSUE TITLE
Explorer: non-https network requests blocked by Safari

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#2564]
![CleanShot 2022-06-14 at 15 35 12](https://user-images.githubusercontent.com/76067158/173720479-39ff8651-dfde-48e1-a50a-a1dde97c1f1d.png)

# Repro
1. start a local RPC server
2. Use Safari/Brave browser to visit https://explorer.devnet.sui.io/, and change the Network to "local"
3. Observe the error in the screenshot

**Comment by stella3d** [comment]
this is a browser policy issue, we can't change Safari's policy.  This is a non-issue for production as we use HTTPS.
