### ISSUE TITLE
Sui RPC Gateway options question

### ISSUE THREAD

**Issue by Romainua** [MystenLabs/sui#2600]
## Steps to Reproduce Issue
Build `rpc-server` binary

## Expected Result

I think options for `rpc-server` must be 
```
--config <CONFIG> informations here
    -h, --help               Print help information
        --host <HOST>        [default: 127.0.0.1]
        --port <PORT>        [default: 9000]
```

## Actual Result

Currently result is 
```
--config <CONFIG>
    -h, --help               Print help information
        --host <HOST>        [default: 127.0.0.1]
        --port <PORT>        [default: 5001]
```

**Comment by gdanezis** [comment]
Many thanks for the report -- I added @patrickkuo and @arun-koshy who can look into it.

**Comment by patrickkuo** [comment]
The current rpc-server(gateway) default port is correct (5001), port 9000 is reserved for full node
