### ISSUE TITLE
Node IP application, method `OPRTIONS` response doesn’t contains allowed methods

### ISSUE THREAD

**Issue by Romainua** [MystenLabs/sui#2612]
## Steps to Reproduce Issue

My node IP application is http://65.21.187.167:9000/, 

try to use method `OPRTIONS`

`curl -s -X OPTIONS http://65.21.187.167:9000/ -H 'Content-Type: application/json’`

## Expected Result

I think on response must be allowed method list 
`Allow: OPTIONS, POST`

## Actual Result
Currently response is 
`{"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"},"id":null}`

**Comment by patrickkuo** [comment]
Thanks for submitting this issue!

The Options request is for [CORS preflight checks ](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request)
The check requires the Origin header

Here is an example OPTIONS request
```
patrick@Patricks-MBPMax sui % curl --location --request OPTIONS -v 'http://65.21.187.167:9000/' --header 'Origin: https://foo.bar.org' 
*   Trying 65.21.187.167:9000...
* Connected to 65.21.187.167 (65.21.187.167) port 9000 (#0)
> OPTIONS / HTTP/1.1
> Host: 65.21.187.167:9000
> User-Agent: curl/7.79.1
> Accept: */*
> Origin: https://foo.bar.org
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< access-control-allow-origin: https://foo.bar.org
< access-control-allow-methods: POST
< access-control-allow-headers: *
< content-length: 0
< date: Fri, 17 Jun 2022 13:54:13 GMT
< 
* Connection #0 to host 65.21.187.167 left intact
```

**Comment by Romainua** [comment]
> requires

Got it, Thanks!
