### ISSUE TITLE
Decided what to do with `ALL_OBJ_VER` in SuiDataStore

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#2628]
Previously ALL_OBJ_VER is a boolean type template used to control whether to store all historic versions of objects.
However after changing the key to objects to ObjectKey, I think we are storing older versions of objects anyway. This makes ALL_OBJ_VER redundant at the moment. Do we still need it?

**Comment by velvia** [comment]
Yeah, we should remove it as we store all versions right now.   Need to re-organize object storage a little bit but can definitely do this quickly right now.

**Comment by velvia** [comment]
Merged and closed
