### ISSUE TITLE
[sui framework] Add entrypoints for Coin minting / burning

### ISSUE THREAD

**Issue by damirka** [MystenLabs/sui#2654]
We can simplify life of Sui enthusiasts by giving them an option to do Coin minting / burning with the wallet.

**Comment by kchalkias** [comment]
As we don't want to deprecate or remove the current public functions, do you suggest just adding new entry functions, like `transfer_to_sender` which unlike the original `public transfer` it won't return anything?
Btw is there a good naming naming convention when we maintain similar functions where one is just `public` and the other `public entry`?
