### ISSUE TITLE
[Doc Bug] sending multiple txns simultaneously

### ISSUE THREAD

**Issue by emmazzz** [MystenLabs/sui#2673]
### What are the existing URLs containing the issue, if any?
https://docs.sui.io/learn/sui-compared#suis-approach-to-validating-new-transactions

### How would you describe the issue? (What needs changing?)
The first paragraph of this section claims that each sender can only send one transaction at a time. This is not true because a sender can send multiple transactions at a time as long as the transactions access different objects.

**Comment by Clay-Mysten** [comment]
Thanks, Emma! Asking @sblackshear and @huitseeker for guidance here.
