### ISSUE TITLE
Improve MiscellaneousError

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#2678]
Currently for a list of runtime execution errors we all return ExecutionFailureStatus::MiscellaneousError. This makes it difficult to know what went wrong. We will need to return a more accurate error message.

**Comment by lxfind** [comment]
Will follow up with @tnowacki on the list of errors we want to store on-chain

**Comment by lxfind** [comment]
@tnowacki to confirm if this has been fixed

**Comment by bmwill** [comment]
This should have been improved in https://github.com/MystenLabs/sui/pull/3166
