### ISSUE TITLE
Add RPC methods to check Sync Status

### ISSUE THREAD

**Issue by janetwu11** [MystenLabs/sui#2701]
if the node is still syncing/catching up or is fully synced – should return “true/false”;

If the status of the syncing is false, it should show how far behind the node is.

Node version to remotely check the sw version the respective node is running.

**Comment by lxfind** [comment]
Depend on checkpoints

**Comment by janetwu11** [comment]
Full node does not currently use checkpoints to sync. This is a prerequisite to enabling the checkpoint API.

**Comment by amanjui45** [comment]
checkpoints
