### ISSUE TITLE
Reconfiguration to use network information from on-chain state

### ISSUE THREAD

**Issue by laura-makdah** [MystenLabs/sui#2706]
Read Network configuration that is used in the ActiveAuthority / NetworkAuthorityClient from the chain at reconfiguration time and when creating a new node. Currently when creating a new node, we read the information from the genesis config, but for new nodes joining the network after reconfiguration is enabled, they will have already registered themselves and so their network information will be available in a Move Object instead of the config.

**Comment by lxfind** [comment]
I tried to manually turn on reconfiguration locally without any validator changes. It seems that the network would stuck after recreating the network based on the on-chain state network info (which should stay unchanged). Can you take a look? I think this should be reproducible if you have a end to end test that could manually recreate the network based on genesis on chain system state object.

**Comment by lxfind** [comment]
This is done
