### ISSUE TITLE
Plan and test for crash of majority of validator nodes.

### ISSUE THREAD

**Issue by allan-bailey** [MystenLabs/sui#2707]
There was a side discussion about this, so tracking here.

Currently we have not tested and verified that we can recover from a crash of all or a majority of the validator nodes.

Basically we need to answer some questions and scenarios:
- Internet outage affecting > 2f+1 validators/nodes.
  - What happens when they restart?  What does the consensus recovery look like? (time, b/w, etc)
- Bad transactions that cause nodes to crash.  Do they recover on restart?  Does the bad transaction drop or retry? etc.

**Comment by mystenmark** [comment]
I think one of the most important things we can do to prepare is to have tools that allow us to inspect and repair the validator databases.

**Comment by lxfind** [comment]
narwhal/tusk needs to be able to handle crash recover

**Comment by lxfind** [comment]
Need to scope out the list of eng items to enable this

**Comment by lxfind** [comment]
Need to scope out the list of eng items to enable this
