### ISSUE TITLE
Design and Implement Tally Protocol

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#2796]
1. Validators are able to observe how each other validator is doing during the epoch (i.e. how much work they put in to validating and executing transactions)
2. Near the end of epoch, validators are able to collect each validator's assessment of each other, and use it to determine a gas reward distribution for each validator. All validators should come to the same consistent distribution
3. Such distribution is then passed to the system transaction during reconfiguration to actually distribute gas reward.

design doc: https://www.notion.so/mystenlabs/Tallying-Rule-dd2174c0153a4fe2a271a6b6a6d1735e

**Comment by lxfind** [comment]
@gdanezis @sblackshear @econmysten @emmazzz @longbowlu We can use this issue to track the tally rule work, and use the notion doc to track design and solutions space

**Comment by janetwu11** [comment]
#1 is straight forward can have a simple PR. #2 is more complex and still needs to be designed. For internal readiness would need to dedicate an engineer to write scripts and prepare for this.
