### ISSUE TITLE
Design and Implement Bonding

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#2811]
Validator joining/exit should take some amount of epochs to take effect.
Similar for delegation.
Q: Do we need this? How do we determine the bonding duration?

**Comment by lxfind** [comment]
Withdraw is the primary, but maybe deposit too?
self stake and delegated stake
need to write down pros and cons

**Comment by sblackshear** [comment]
One more note from the meeting: a desire for tokens remaining staked during the unbonding period (e.g., user says "withdraw now", tokens remain staked but locked for N days, then user gets tokens and they are unstaked at the same time)
