### ISSUE TITLE
Update README for sui-framework

### ISSUE THREAD

**Issue by damirka** [MystenLabs/sui#2840]
We still have references of Diem and no mention of `sui-move`

https://github.com/MystenLabs/sui/tree/main/crates/sui-framework

**Comment by Clay-Mysten** [comment]
Yeah, I've never touched (or even seen) this README. Asking @sblackshear and @awelc for guidance as I'm not sure what replaces: https://github.com/diem/diem move-cli

We have Move docs now in:
https://github.com/move-language/move

And a SUI CLI (formerly wallet) coming in:
https://github.com/MystenLabs/sui/pull/2786

So what replaces move-cli? Also, I imagine the `sui_programmability/framework` path under **Building** should also be updated to reflect all of the crates-related moving we've been doing:
```
claymurphy@Clays-MacBook-Pro sui % cd sui_programmability 
claymurphy@Clays-MacBook-Pro sui_programmability % ls
examples
claymurphy@Clays-MacBook-Pro sui_programmability % pwd
/Users/claymurphy/sui/sui_programmability
claymurphy@Clays-MacBook-Pro sui_programmability % 
```

All, please advise. We truly need to better coordinate all of these changes and docs...

**Comment by damirka** [comment]
@Clay-Mysten sorry, I've assigned this buddy to you by default hoping you can ping one of us. We want to use `sui-move` here and not the `move` CLI (the latter just won't compile). I can take it.

**Comment by Clay-Mysten** [comment]
Thanks @damirka. Please note, `sui move` is going away in:
https://github.com/MystenLabs/sui/pull/2786/

Now that I know the intent, I will start the update by merely replacing the manual work with our existing install docs.

**Comment by Clay-Mysten** [comment]
Please take a look:
https://github.com/MystenLabs/sui/pull/2868

**Comment by Clay-Mysten** [comment]
Thanks to @huitseeker for his approval. Glad to have you back!
