### ISSUE TITLE
stake moveCall locked SuiSystemState 

### ISSUE THREAD

**Issue by gegaowp** [MystenLabs/sui#2843]
## Steps to Reproduce Issue

- locally run validator, json-rpc and fullnode
- transfer coins from gas objects to a wallet address like
```
target/debug/wallet switch --gateway http://127.0.0.1:5001
target/debug/wallet gas
                 Object ID                  |  Version   |  Gas Value
----------------------------------------------------------------------
 0x1643e3eba234466aac049eabaa25bda5c419ba61 |     0      |   100000
 0x1c1c06b77e777d41741ded826b37da450ce27862 |     0      |   100000
 0x21c87e7df1769252d328f8f2e516bed3e39fb13a |     0      |   100000
 0x87a25cafb136c1739b88973fd3f31a1759f36242 |     0      |   100000
 0xd5564c0ed7824e531eed87b6ed3abd5487c01f06 |     0      |   100000
target/debug/wallet transfer-coin --coin-object-id 0x1643e3eba234466aac049eabaa25bda5c419ba61 --to 0x627ac02b685d506cbf38cda62cae63cb48a5ec75 --gas-budget 10000
target/debug/wallet transfer-coin --coin-object-id 0x1c1c06b77e777d41741ded826b37da450ce27862 --to 0x627ac02b685d506cbf38cda62cae63cb48a5ec75 --gas-budget 10000
```
- from sdk-test-app repo, replace `first-gas-object-id` and then insert this block of codes to SignerDemo.tsx after `// Test Move call`
```
    const stakeTxn = await signerWithProvider.executeMoveCall({
      packageObjectId: "0x2",
      module: "sui_system",
      function: "request_add_stake",
      typeArguments: [],
      arguments: [
        "0x0000000000000000000000000000000000000005",
        "<first-gas-object-id>",
      ],
      gasBudget: 10000,
    });
```
- in test-sdk-app, run `rm -rf node_modules && yarn && yarn start`, in case it did not pop, go to `http://localhost:3000/`, press F12 to show the console
- then click "get objects Get" -> "Sign"

## Expected Result

The SuiSystemState shared object should not be locked

## Actual Result

In the console, it showed something like
```
json-rpc-provider.ts:187 Uncaught (in promise) Error: Error executing transaction: Error: RPC Error: Failed to execute certificate on a quorum of validators, cause by : [
Error acquiring lock for object(s): [UnexpectedSequenceNumber { object_id: 0x0000000000000000000000000000000000000005, expected_sequence: SequenceNumber(1), given_sequence: SequenceNumber(2) }]",
```

the correct `typeArguments` should be something like ` ["0x2::sui::SUI"]` but otherwise it should not lock the shared object either.

**Comment by 666lcz** [comment]
You can also reproduce this with wallet cli

```
➜ ./wallet call --package 0x2 --module sui_system --function request_add_stake --args 0x0000000000000000000000000000000000000005 0xa2eec59c280fe641904f22ace7cc4eb2c4e7ef65 --gas-budget 2000
RPC call failed: ErrorObject { code: ServerError(-32000), message: "Failed to execute certificate on a quorum of validators, cause by : [\n    \"Error acquiring lock for object(s): [UnexpectedSequenceNumber { object_id: 0x0000000000000000000000000000000000000005, expected_sequence: SequenceNumber(1), given_sequence: SequenceNumber(2) }]\",\n    \"Error acquiring lock for object(s): [UnexpectedSequenceNumber { object_id: 0x0000000000000000000000000000000000000005, expected_sequence: SequenceNumber(1), given_sequence: SequenceNumber(2) }]\",\n    \"Error acquiring lock for object(s): [UnexpectedSequenceNumber { object_id: 0x0000000000000000000000000000000000000005, expected_sequence: SequenceNumber(1), given_sequence: SequenceNumber(2) }]\",\n]", data: None }
```

**Comment by 666lcz** [comment]
@lxfind / @patrickkuo , a separate question: do you know why we don't need to specify type-args in this case?

Given that the [argument contains a generic](https://github.com/MystenLabs/sui/blob/ca37ecc050f3b47d01ad36a550d91b17da524705/crates/sui-framework/sources/governance/sui_system.move#L131), I thought we need to pass in `type_args`, but I am getting an error if I do that

```
./wallet call --package 0x2 --module sui_system --function request_add_stake --args 0x0000000000000000000000000000000000000005 0xa2eec59c280fe641904f22ace7cc4eb2c4e7ef65 --type-args 0x2::SUI::SUI --gas-budget 2000
RPC call failed: ErrorObject { code: ServerError(-32000), message: "ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidFunctionSignature, source: Some(\"Expected 0 type arguments, but found 1\") } }", data: None }
```

**Comment by patrickkuo** [comment]
> @lxfind / @patrickkuo , a separate question: do you know why we don't need to specify type-args in this case?
> 
> Given that the [argument contains a generic](https://github.com/MystenLabs/sui/blob/ca37ecc050f3b47d01ad36a550d91b17da524705/crates/sui-framework/sources/governance/sui_system.move#L131), I thought we need to pass in `type_args`, but I am getting an error if I do that
> 
> ```
> ./wallet call --package 0x2 --module sui_system --function request_add_stake --args 0x0000000000000000000000000000000000000005 0xa2eec59c280fe641904f22ace7cc4eb2c4e7ef65 --type-args 0x2::SUI::SUI --gas-budget 2000
> RPC call failed: ErrorObject { code: ServerError(-32000), message: "ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidFunctionSignature, source: Some(\"Expected 0 type arguments, but found 1\") } }", data: None }
> ```

The type_arg is for function generic, e.g. `fun transfer<T>`
