### ISSUE TITLE
What happens when a validator missed a fragment?

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#2856]
e.g. due to network issue
is it able to fetch it? Would it lead to inconsistent checkpoint result?
@gdanezis @asonnino

**Comment by gdanezis** [comment]
Fragments are processed though the output of consensus. Consensus must ensure that all validators see all outputs and in the same order. Therefore, if our assumptions hold (>2/3 honest etc) all honest validators will see all fragments sequenced and in the same order. Is this what the worry is?

**Comment by asonnino** [comment]
> Fragments are processed as the output of consensus. Consensus must ensure that all validators see all outputs and in the same order. Therefore, if our assumptions hold (>2/3 honest etc) all honest validators will see all fragments sequenced and in the same order. Is this what the worry is?

If this assumption doesn't hold we have bigger problems
