### ISSUE TITLE
wallet-ext: clicking on the transaction tab should not change the size of the wallet window

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#2903]
https://user-images.githubusercontent.com/76067158/176940046-490ba087-2078-4504-adcf-6f2a487135d6.mp4

**Comment by Jibz1** [comment]
@666lcz all the icons increase in size once active, this is intentional . Not sure if it bug. @pchrysochoidis

**Comment by pchrysochoidis** [comment]
Yeah, this should be fixed when we start implementing the new designs. Now it only has a max-height and just adapts to the content.

**Comment by pchrysochoidis** [comment]
> @666lcz all the icons increase in size once active, this is intentional. Not sure if it's a bug more a feature. @pchrysochoidis

this is a feature! :-)
