### ISSUE TITLE
We should not attempt to resolve Move events struct in the Gateway

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#2921]
When we are constructing transaction effect response, we also try to resolve the Move struct of all the events in the effects, from here: https://github.com/MystenLabs/sui/blob/main/crates/sui-core/src/gateway_state.rs#L1048
This is not going to work.
The gateway is not guaranteed to contain the package/module that defined the event struct, and it may fail to obtain the Move struct for every event.
We are also probably over-complicate things here: does the transaction caller really need to see the Move fields of every event in the effects? If they need to do so, they should resolve it on the client by querying the fullnode, not on the gateway.

**Comment by patrickkuo** [comment]
> The gateway is not guaranteed to contain the package/module that defined the event struct ...

When we create a move call transaction in gateway (`create_move_call_transaction_kind`), we assume the gateway knows about the package/module of the move function and we use the package object to resolve the move call args `resolve_move_function_args`. My thought is if the gateway can create the move call transaction, it should have the package object to resolve the event object as well? Or is this a wrong assumption...?

**Comment by lxfind** [comment]
The gateway only assures to know the package it's calling. But if the event struct is not defined in this package, but in a dependent package, there is no guarantee that the gateway will have it.
