### ISSUE TITLE
Explorer: Render fullnode and validator in a map

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#2961]
Map view,
https://www.figma.com/file/OzLaRFzevjxdQAbybWEZk0/Sui-Visualize?node-id=3211%3A75761

"Become a validator" link will be added to ticket tomorrow. (fingers crossed)

**Comment by gegaowp** [comment]
PR to fetch IP addresses and geo locations on Explorer backend
https://github.com/MystenLabs/imgmod-service/pull/2



![Image](https://user-images.githubusercontent.com/106119108/182406828-f61ed87e-9ec9-4594-8906-5eade831d3c3.png)

**Comment by bwann52** [comment]
Application link https://airtable.com/shr3phh3FCZYhZUDF
