### ISSUE TITLE
Improve API rendering

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#2966]
Context: Render APIs directly in docs and move away from playground

We current link playground to our docs side menu, but it’s not an ideal experience.
Ideally we:
render the apis and contents from https://github.com/MystenLabs/sui/blob/main/crates/sui-open-rpc/spec/openrpc.json directly in our docs.
make this still discoverable from our side menu
make this automatic so the docs are pulling the latest info and reduce replication overhead for tech writers

**Comment by bwann52** [comment]
@patrickkuo @longbowlu @Jibz1 
Could we discuss our options here?

**Comment by patrickkuo** [comment]
Maybe we can borrow some idea from OPEN-RPC playground?
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/1888654/177376913-2d4fd4f9-a68b-4fb8-b2bb-16200477782e.png">

**Comment by Jibz1** [comment]
@bwann52 @patrickkuo we can autogenerate the page content like https://docs.solana.com/developing/clients/jsonrpc-api#getaccountinfo from the [JSON](https://github.com/MystenLabs/sui/blob/main/crates/sui-open-rpc/spec/openrpc.json) file, but the open RPC file has to include extra information I can use.

**Comment by bwann52** [comment]
@Jibz1 What extra information do you need?

**Comment by Clay-Mysten** [comment]
Thjs is also done. See:
https://docs.sui.io/sui-jsonrpc

**Comment by Clay-Mysten** [comment]
Thanks to @Jibz1 !
