### ISSUE TITLE
genesis: make genesis a transaction type

### ISSUE THREAD

**Issue by bmwill** [MystenLabs/sui#3061]
Today Genesis is just a bunch of objects that get dumped into a node's database at startup. Instead we'd like to make genesis more of a first-class citizen in sui by making it be a specific transaction type. 

Also include work from #2769, which is folded into this:
> As the reconfiguration process becomes activated, a lot of our reliance on the genesis blob can be refactored away, especially in tests. See https://github.com/MystenLabs/sui/pull/2746#issuecomment-1168231545.

**Comment by todd-mystenlabs** [comment]
Closed out #2769, combining that into this change here.
