### ISSUE TITLE
Suggest versioning the code and docs

### ISSUE THREAD

**Issue by Romainua** [MystenLabs/sui#3135]
The doc does not always correspond to the current backend, I suggest adding the date or version of the last update for the doc at the beginning of the page, this will allow to understand which current version is, we can add the current version of the node/sui-client and documentation 
for e.g. current node version is `0.5.0` current doc vesion for `0.4.0` version what does it mean there may be a discrepancy

**Comment by Clay-Mysten** [comment]
> > Thanks, Roman. The issue is we build docs.sui.io from the `main` upstream branch yet release the downstream `devnet` branch to the public. So the docs are ahead of the code in many ways.
> > See this issue for our proposed solution, namely to allow users to toggle between the two branches in the docs. What do you think? Thanks for the report!
> 
> yes, this is a great solution, it will solve all the issues

Thanks for confirming.
