### ISSUE TITLE
displaying values in sui doc

### ISSUE THREAD

**Issue by Romainua** [MystenLabs/sui#3202]
page https://docs.sui.io/build/sui-json#type-coercion-rules

Version of safari 15.5 (17613.2.7.1.8)
MacOS 12.4, 13-inch display 
![1](https://user-images.githubusercontent.com/44613085/179045302-2e568885-09aa-4e9a-b528-ef7d6255d103.png)
![2](https://user-images.githubusercontent.com/44613085/179045312-f77fdbf3-6a5d-41c4-8d20-8e39098dace1.png)

**Comment by Jibz1** [comment]
I will also take a look today

**Comment by Romainua** [comment]
> Thanks, Roman. May I ask for some specific examples and whether they appear correctly in the source Markdown files? https://github.com/MystenLabs/sui/blob/main/doc/src/build/sui-json.md#type-coercion-rules
> 
> @Jibz1 and @patrickkuo , we may need to convert these HTML tables to Markdown to mitigate formatting issues. Let's wait to hear back from Roman. Thanks, all!

yeah, it looks good in the source
![source](https://user-images.githubusercontent.com/44613085/179219566-61d788de-65a0-447e-b643-6c66b9383466.png)

**Comment by Romainua** [comment]
@Clay-Mysten Hi! Sorry for both you in closed issue. Сan I become your assistant and help develop the sui?
Great desire to become a part of sui!

**Comment by Romainua** [comment]
> > @Clay-Mysten Hi! Sorry for both you in closed issue. Сan I become your assistant and help develop the sui? Great desire to become a part of sui!
> 
> Hi Roman,
> 
> I would love your help! First, note this issue you reported did help trigger the fix: https://docs.sui.io/build/sui-json
> 
> Second, note that if you submit pull requests for a page on docs.sui.io, you are automatically recognized as a contributor at the bottom of any page. See for example all of the contributors at the bottom of this page, some internal some external: https://docs.sui.io/build/move
> 
> Third, we can certainly coordinate more closely, having you review, test, and edit our documents. In fact, I'm doing a Twitch talk next week, on July 27th, about our docs processes that should help.
> 
> @bhenhsi , may I ask how we can invite Roman to our AMA on docs? Thanks!

It will be great!

**Comment by bhenhsi** [comment]
Stay tuned! :)

**Comment by Romainua** [comment]
> Stay tuned! :)

Okay :)

**Comment by Romainua** [comment]
@Clay-Mysten seem something happend?

**Comment by Clay-Mysten** [comment]
> @Clay-Mysten seem something happend?

Yes, we switched the table to Markdown:
https://docs.sui.io/build/sui-json#type-coercion-rules

And we have this AMA scheduled for Wednesday:
https://discord.com/events/916379725201563759/1003614516589895710

@bhenhsi and @losamsel can tell you if we are doing something earlier that day.
