### ISSUE TITLE
Timeouts while running shared object benchmark

### ISSUE THREAD

**Issue by sadhansood** [MystenLabs/sui#3239]
## Steps to Reproduce Issue

```
cargo run --release --package sui-benchmark --bin shared
```
Run the above with target qps of 500

## Expected Result

The benchmark should be long running and should not stop processing requests

## Actual Result

After a few minutes of running the benchmark, we start seeing timeouts from the consensus adapter in sui:
```
RpcError("Failed to hear back from consensus: deadline has elapsed"))
```
The above is SuiError::FailedToHearBackFromConsensus error code. The symptoms of the issue we are seeing is like things just stop working after they have been working just fine for few minutes. I can get a sustained throughput for few minutes, and then I don't see more transactions getting sequenced and hence the timeout on the submit() function. Even if I increase the timeout to 10s, it happens but after running a little bit longer.

Doing a little bit digging on the narwhal side, I also notice the round numbers stop increasing about the same time this happens.

The way shared bench works is - we start the bench a max limit of number of in flight transactions and on getting an error, retry those transactions. When we hit this issue, I can see we have the max number of transactions in flight which now start erroring out due to timeout and keep getting re-submitted but the throughput at this point has degraded a lot.

## System Information

* OS: MacOS

**Comment by huitseeker** [comment]
Update: July 18, this was a misconfigured Narwhal. We should document that `test_and_configure_authority_configs` is not for use in benchmarking or production configurations.

**Comment by sadhansood** [comment]
Agreed, the issue turns out to be misconfigured batch size of 1 byte which caused micro batches to be created i.e 1 transaction per batch too fast. It was fast enough that during voting for a proposed header, non proposing primaries did not find the payload (it was still stuck in tokio channels and hadn't been read yet) and returned missing payload errors. Increasing the batch size to 6400 bytes fixed the problem. Huge thanks to @asonnino and @huitseeker for helping out on this one.
