### ISSUE TITLE
Ability to verify any authenticated data structure from past epochs

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#3279]
Right now we always use the current committee to check any authenticated data structure. This will not work once we support epoch changes. We need to store committee information for each epoch and load the corresponding committee when verifying any authenticated data structure from any epoch.

**Comment by lxfind** [comment]
@punwai Is this something you are going to look at? If not, I will probably need to take a look

**Comment by mystenmark** [comment]
when do we load things from previous epochs?
