### ISSUE TITLE
Create Sui Release Notes

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#3313]
What are the existing URLs containing the issue, if any?
https://docs.sui.io/learn#see-whats-new
https://github.com/MystenLabs/sui/blob/main/RELEASES.md
https://discord.com/channels/916379725201563759/974444055259910174
https://github.com/MystenLabs/sui/releases

How would you describe the issue? (What needs changing?)

We have release-related information everywhere. See above plus Notion pages for each release.

Where should this information land if new? (Learn, Build, Explore, Contribute.)

In a distinct Releases section of Contribute, IMHO. Randall to decide.

What changes are needed to support this new feature or product? (A simple overview, detailed procedures?)

We need a release process, expanding upon the existing internal template. And we need to publish first to the docs and then link from Discord, IMO.

Who is the audience for that information? (App developers, investors, creators, validators, someone else?)

Everyone.

What precisely must they do with it? (Configure a new service? Process some output?)

Get it to everyone.

**Comment by Clay-Mysten** [comment]
I saw this from Francois yesterday for version 0.6.4:
https://github.com/MystenLabs/sui/pull/3692
But the last release we listed on [docs.sui.io](http://docs.sui.io/) is 0.6.1:
https://docs.sui.io/learn#see-whats-new
But I do also see now:
https://github.com/MystenLabs/sui/releases/tag/devnet-0.6.2
https://github.com/MystenLabs/sui/releases/tag/devnet-0.6.3

Do we announce dot releases? I am asking the same question in Slack.

**Comment by Clay-Mysten** [comment]
Related, someone is suggesting a node update channel:
https://discord.com/channels/916379725201563759/916379726640193608/1004519882966171648

**Comment by Clay-Mysten** [comment]
I'm adding @huitseeker for collaboration on announcing releases that may break full nodes.

**Comment by Clay-Mysten** [comment]
Adding @bhenhsi for his help on developing the release notes plan and then distributing updates for releases.

**Comment by randall-Mysten** [comment]
I'd like to explore incorporate a release entry associated with each release in the repo. Would make it easy to find them, and adding info to the release page would be required to push out a new version. Could even link to a page with more details if desired.
https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases

We did this for Amazon Braket: https://github.com/aws/amazon-braket-sdk-python/releases

**Comment by Clay-Mysten** [comment]
> I'd like to explore incorporating a release entry associated with each release in the repo. Would make it easy to find them, and adding info to the release page would be required to push out a new version. Could even link to a page with more details if desired. https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases
> 
> We did this for Amazon Braket: https://github.com/aws/amazon-braket-sdk-python/releases

This looks like:
https://github.com/MystenLabs/sui/releases

Seems like we just need consistency. What was your process?

**Comment by Clay-Mysten** [comment]
> > I'd like to explore incorporating a release entry associated with each release in the repo. Would make it easy to find them, and adding info to the release page would be required to push out a new version. Could even link to a page with more details if desired. https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases
> > We did this for Amazon Braket: https://github.com/aws/amazon-braket-sdk-python/releases
> 
> This looks like: https://github.com/MystenLabs/sui/releases
> 
> Seems like we just need consistency. What was your process?

@randall-Mysten, any progress here? We have another release today.

**Comment by randall-Mysten** [comment]
this is an engineering issue

**Comment by Clay-Mysten** [comment]
> this is an engineering issue

Please explain. You said you helped with release notes previously. And I've certainly done so many times throughout my career. Further, you offered a specific path a la Amazon earlier.

Are you saying you have no intention of helping with release notes?

**Comment by Clay-Mysten** [comment]
While we figure out where and how the canonical release notes will land, let's give folks a persistent path to Discord:
https://github.com/MystenLabs/sui/pull/4103

**Comment by Clay-Mysten** [comment]
Unless there are objections, I will take this back from @randall-Mysten  so we can start to make the excellent process @ebmifa followed last week repeatable. More to come.

**Comment by Clay-Mysten** [comment]
I have now reworked the Release Checklist Template and associated release notes instructions to be much more clear. Now sending out for review.

**Comment by Clay-Mysten** [comment]
And I've raised the issue of redundant docs on the release process internally to see if we can dedupe and archive the old.
