### ISSUE TITLE
Fullnode Pagination support for get_transactions

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#3318]
Right now we return all transaction digests in the [fullnode read API](https://github.com/MystenLabs/sui/blob/main/crates/sui-json-rpc/src/api.rs#L104), but some addresses may have millions of transactions(e.g., faucet). These endpoints should support pagination.

**Comment by il9ue** [comment]
Hi, 
May I take a look into this feature (issue) ?

**Comment by 666lcz** [comment]
@il9ue of course! Thank you for contributing!

**Comment by 666lcz** [comment]
closed by https://github.com/MystenLabs/sui/pull/4919
