### ISSUE TITLE
Security hygiene for keypairs/private keys

### ISSUE THREAD

**Issue by mystenmark** [MystenLabs/sui#3345]
We have a number of hygiene tasks to take care of with regards to private keys:

- [ ] remove Display and Debug impls for KeyPair / private key so it isn't easy to print them out
- [ ] genesis tool must not read private keys from commandline arguments
- [ ] validator can read private key from separate (non config) file
- [ ] final audit of configs to make sure there are no keypairs/private keys in them

This may duplicate some other issues - i did a quick search and couldn't find anything

**Comment by huitseeker** [comment]
/cc @kchalkias @joyqvq @punwai since the pattern of implementation of keys in the system is moving really fast
(see also https://github.com/MystenLabs/narwhal/issues/537 https://github.com/MystenLabs/sui/pull/2994 https://github.com/MystenLabs/sui/pull/3191 )

**Comment by huitseeker** [comment]
related: #1478 which would indicate the last item is done.
