### ISSUE TITLE
Unable to start fullnode/complie

### ISSUE THREAD

**Issue by smartins** [MystenLabs/sui#3346]
I'm following the instructions on https://docs.sui.io/build/fullnode on how to a sui full node.

I'm on Ubuntu 20.04.4

When starting/compiling using the following command:
`cargo run --release --bin sui-node -- --config-path fullnode.yaml`

I get the following error message:

```
error[E0658]: use of unstable library feature 'bool_to_option'
   --> /root/.cargo/git/checkouts/mysten-infra-e26c6e4a001ad289/7e9b756/crates/telemetry-subscribers/src/lib.rs:203:57
    |
203 |         let json_storage_layer = config.json_log_output.then_some(JsonStorageLayer);
    |                                                         ^^^^^^^^^
    |
    = note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `telemetry-subscribers` due to previous error
```

Am I missing something? Thanks!

**Comment by Clay-Mysten** [comment]
> Ah, you are probably using a rust version that's older than the one recommended for use in compiling the project. Here's what the project recommends:
> 
> ```shell
> huitseeker@Garillots-MBP.localdomain➜~/tmp/sui(main✗)» cat rust-toolchain                                                                                                                                                                                                                                                                                     
> 1.62.1
> ```
> 
> Here's how to discover what you have installed:
> 
> ```shell
> huitseeker@Garillots-MBP.localdomain➜~/tmp/sui(main✗)» rustc --version                                                                                                                                                                                                                                                                                        
> rustc 1.62.1 (e092d0b6b 2022-07-16)
> ```
> 
> If you have installed rust with [rustup](https://rustup.rs/), your tooling should pick that up automatically and resolve any issues. If you have installed it with your distro's package manager, I actually recommend uninstalling and installing rustup for an overall nicer experience.
> 
> /cc-ing @Clay-Mysten for a possible need to update our docs.

Ah, per @damirka, we recently updated:
https://docs.sui.io/build/install#rust

To recommend first:
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

Then:
`rustup update stable`

Is this hard-coding the version to 1.2? Should I revert that change?

Also, I'm running into license check errors on merge and wondering if I need to to install cargo-hakari and run: `cargo hakari generate`

Related? Adding folks who should know.

**Comment by Clay-Mysten** [comment]
More reports of fullnode breakage:
https://mysten-labs.slack.com/archives/C03Q0KVGJ9K/p1658360418874029
Namely, a missing Compose file.

**Comment by smartins** [comment]
> 

Thanks I was on 1.59, upgraded to 1.62 and was able to compile and run.

Had to remove cargo first since rustup wasn't installed and I wasn't able to install it with rust already installed.

Here are the steps I used to upgrade to 1.62

```
sudo apt remove cargo
sudo apt autoremove

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

**Comment by Clay-Mysten** [comment]
Thanks, Steven. I still think we can do a better job in the docs. Reopening.
