### ISSUE TITLE
Ensure that db dump tool is always in-sync with the store structure

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#3359]
The db dump tool uses a code copy of the authority store: https://github.com/MystenLabs/sui/blob/6d22210d771ebf4728290a4c811b8a242d886e6a/crates/sui-tool/src/db_tool/db_dump.rs#L51
We change the store frequent enough that the db-tool would go out of sync pretty much each time we need it. We should consolidate the store so that it's always in-sync.

**Comment by mystenmark** [comment]
Isn't the solution just to build the tool at the deployed commit?

**Comment by velvia** [comment]
I think we need something based on macros or similar that is very low overhead so it can keep up with changes that happen frequently

**Comment by lxfind** [comment]
Or just embed the dumping functionality in the store implementation, so that each time anyone changes it must modifies the dump to make it compile

**Comment by oxade** [comment]
@lxfind yes consolidation is being worked on.
The code for the dump tool was initially written to avoid touching the core datastore since we needed velocity.
See [this](https://github.com/MystenLabs/sui/pull/3188#discussion_r922402232) comment in the original PR about this

**Comment by lxfind** [comment]
@oxade Good to know. Do you have a timeline for this? I think we need this asap since it is the best way to debug prod issues when we don't have sufficient logs, and we need to debug issues pretty much every release at this point.

**Comment by oxade** [comment]
@lxfind PR will be out within 24 hours.

**Comment by oxade** [comment]
PR here
https://github.com/MystenLabs/sui/pull/3494

Next step is to use macros to codegen, and to add checkpoints & lock service dump

**Comment by oxade** [comment]
The first phase is done.
Next phases to simplify code are here https://github.com/MystenLabs/sui/issues/3629 and https://github.com/MystenLabs/sui/issues/3630
