### ISSUE TITLE
Build out i18n infrastructure, ready for generic contribution and localization of Sui website contents

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#3380]
Localize doc site

**Comment by Clay-Mysten** [comment]
@losamsel and @bhenhsi , we have someone offering to translate our Smart Contract and Tokenomics white papers in:
https://github.com/MystenLabs/sui/issues/3412

They mention other but don't say which languages. Shall I ask them to try our web pages? Thanks!

**Comment by Clay-Mysten** [comment]
More from Brian, community-submitted tutorials:
https://ethereum.org/en/developers/tutorials/

Thanks, @bhenhsi !

**Comment by Clay-Mysten** [comment]
Here is an example recent external contribution:
https://medium.com/@megalodonear/sui-installing-node-step-by-step-guide-for-beginners-5c766ce94ab9

Find more in:
https://github.com/MystenLabs/sui/issues/1065#issuecomment-1195752640

**Comment by Jibz1** [comment]
@Clay-Mysten and @bhenhsi see https://github.com/ethereum/ethereum-org-website/tree/dev/src/content/translations

**Comment by Clay-Mysten** [comment]
> @Clay-Mysten and @bhenhsi see https://github.com/ethereum/ethereum-org-website/tree/dev/src/content/translations

Thanks. LGTM for our plans long term.

**Comment by Clay-Mysten** [comment]
I'm adding @randall-Mysten since he expressed a desire to edit the docs for localization. I believe some of this is underway. Randall, simply include the PRs here. Thanks!

**Comment by randall-Mysten** [comment]
> @Clay-Mysten and @bhenhsi see https://github.com/ethereum/ethereum-org-website/tree/dev/src/content/translations

Have we already confirmed with a loc vendor that this is the appropriate structure to implement an integration?

**Comment by Clay-Mysten** [comment]
> > @Clay-Mysten and @bhenhsi see https://github.com/ethereum/ethereum-org-website/tree/dev/src/content/translations
> 
> Have we already confirmed with a loc vendor that this is the appropriate structure to implement an integration?

What structure? The subdirectories for languages? That is a norm:
https://stackoverflow.com/questions/8527306/deploying-net-satellite-assemblies-in-specific-folder
https://stackoverflow.com/questions/4864984/separate-folder-for-language-files
https://laravel.io/forum/02-23-2015-localization-load-files-from-subdirectories-at-resourceslanglocale

What did you have in mind?

**Comment by randall-Mysten** [comment]
I'm just trying to understand where things are in the process. There was some discussion of having community-based localization, but then we learned that there are vendors under consideration. I did not know whether this was to prepare for user-based or in response to a vendor discussion.

**Comment by Clay-Mysten** [comment]
I am noting we have an offer from the person below to translate our contents from English and Ukrainian:
Dmitry Bauer (dmitry@amba.team)

**Comment by randall-Mysten** [comment]
closing as duplicate
