### ISSUE TITLE
[chore] remove RUSTSEC-2022-0002 from denylist by updating upstream Move

### ISSUE THREAD

**Issue by sblackshear** [MystenLabs/sui#340]
See https://github.com/MystenLabs/fastnft/pull/339. dashmap 5.0.0 in the upstream Move repo is vulnerable to this. No safe upgrade is available, but once one is, we should upgrade Move + fastX and remove this.

**Comment by huitseeker** [comment]
Closed in https://github.com/MystenLabs/sui/commit/37410be1abf2316b86c11b326c2e5eb7c5627c77
