### ISSUE TITLE
please provide the source file of sui.pdf and tokenomics.pdf  [Feature Request]

### ISSUE THREAD

**Issue by GaoCan702** [MystenLabs/sui#3412]
- What are the existing URLs containing the issue, if any?

**URL: https://github.com/MystenLabs/sui/tree/main/doc/paper**

- How would you describe the issue? (What needs changing?)

I want to translate these documents into other languages, I want to get the source file of the PDF

**Comment by Clay-Mysten** [comment]
Thanks for the offer! I've copied some folks who may be interested in taking you up on this.

**Comment by Clay-Mysten** [comment]
And do you have any appetite for trying out our web pages? For example:
https://github.com/MystenLabs/sui/blob/main/doc/src/learn/index.md

Thanks!

**Comment by limit0x** [comment]
> And do you have any appetite for trying out our web pages? For example: https://github.com/MystenLabs/sui/blob/main/doc/src/learn/index.md
> 
> Thanks!

yes

**Comment by limit0x** [comment]
Sorry for the unclear expression, the target language I want to translate is Chinese
