### ISSUE TITLE
Consistency in crypto representation

### ISSUE THREAD

**Issue by punwai** [MystenLabs/sui#3420]
## Description
We should discuss one canonical way to serialize, deserialize, and represent crypto to users. For example, the keytool file stores the filename as hex, while storing the keys as Base64.

```           
            KeyToolCommand::Generate => {
                let (_address, keypair): (_, AccountKeyPair) = get_key_pair();

                let hex = encode_bytes_hex(keypair.public());
                let file_name = format!("{hex}.key");
                write_keypair_to_file(&keypair, &file_name)?;
                println!("Ed25519 key generated and saved to '{file_name}'");
            }

            KeyToolCommand::Show { file } => {
                let keypair = read_keypair_from_file(file)?;
                println!("Public Key: {}", encode_bytes_hex(keypair.public()));
            }
```

**Comment by joyqvq** [comment]
taking a look at what this is now, the filename is a sui address (hex encoded). the file content is base64 encoded `flag || privkey || pubkey`. such encoding is finalized in sui. 
![image](https://user-images.githubusercontent.com/108701016/207639354-94338101-9766-4dbb-8530-d0c289ab3e3c.png)
