### ISSUE TITLE
[Move] Allow transfer object to signer without consuming the object

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#345]
Move transfer function is defined here: https://github.com/MystenLabs/fastnft/blob/main/fastx_programmability/framework/sources/Transfer.move#L19
When transferring an object, the function takes the object by value, and hence fully consume the object. Such object is no longer usable in the move code in the same session.

This is desired when we transfer an object to another address. However, in the case when we are transferring an object to the signer, there is no reason we couldn't continue using that object.
So we could add a version of transfer that always transfer the object to the signer and takes a mutable reference to the object as input, instead of by-value. This will also needed when we are transferring an object to another object: the transferred object should continue be usable after the transfer, after all, the signer hasn't changed.

The challenge on the implementation is that now we need a way to consume the object at the end of Move execution. We probably can introduce a native function that does that: consume the object, and put it to the owner based on the transfer events we saw earlier.

**Comment by tnowacki** [comment]
Assigning to @lxfind just to triage

**Comment by lxfind** [comment]
We don't really have a need for this. Closing.
