### ISSUE TITLE
[explorer] Refactor pagination component

### ISSUE THREAD

**Issue by stella3d** [MystenLabs/sui#3470]
right now, the pagination component emits the current page state, which leads to its re-use between tables being more difficult than is ideal.

We should refactor the pagination component to instead emit the _current page number_ (0-indexed). This way the higher-level components that use pagination can handle the specifics of updating their state based on the page number.

**Comment by Jordan-Mysten** [comment]
We'll be rebuilding pagination components based on the new UI components, which will have an entirely different API, so going to close this for now.
