### ISSUE TITLE
Create solutions engineering training program

### ISSUE THREAD

**Issue by bholc646** [MystenLabs/sui#3476]
We need a program to onboard and train Move devs who will go out and work hands-on with partners on developing apps on Sui.

The program should involve building working apps on Sui, that demonstrate best practices in Move programming.

**Comment by randall-Mysten** [comment]
I am removing the Type: Documentation label from this issue. We perhaps need some additional labels to categorize, but since Type: Docs is automatically added to PRs for /docs files, and this content would not be in the /docs folder, I am removing the label.
