### ISSUE TITLE
crypto: implement native move function for ECDSA verification and keccak256

### ISSUE THREAD

**Issue by joyqvq** [MystenLabs/sui#3484]
Add a new module (or just pick your existing module you want to add the function to)
Write the signature in the Move file, e.g. public native fun my_cool_hash_function(x: vector<u8>): vector<u8>;
Write the implementation in Rust. In crates/sui-framework/src/natives/<whatever module it is in >.rs and fn <whatever the function is called>
Hook it up in all_natives crates/sui-framework/src/natives/mod.rs
Write some tests in Move

also: document in `crates/sui-framework/src/natives/mod.rs`

**Comment by kchalkias** [comment]
@joyqvq breaking this task into keccak, ecrecover and ecdsa Move native verification
