### ISSUE TITLE
Sui-Gateway fails to building on OSX Monterrey

### ISSUE THREAD

**Issue by Genysys** [MystenLabs/sui#3496]
## Steps to Reproduce Issue

Run 

```bash
curl https://raw.githubusercontent.com/MystenLabs/sui/main/doc/utils/sui-setup.sh -o sui-setup.sh && \
chmod 755 sui-setup.sh && \
./sui-setup.sh
```

## Expected Result

sui-gateway builds successfully. 

## Actual Result

```bash
error: failed to run custom build command for `tonic-health v0.6.0`

Caused by:
  process didn't exit successfully: `/var/folders/s3/nrv22bf104lcg9p6g9jfbryc0000gn/T/cargo-install6ZDDj9/release/build/tonic-health-de7e031b358e718d/build-script-build` (exit status: 1)
  --- stderr
```

In order to fix this :

```bash
brew install protobuf
# add this to dotfile

PROTOC=/usr/local/bin/protoc
PROTOC_INCLUDE=/usr/local/include
```

then run `./sui-setup.sh`

## System Information

* OS: 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 x86_64
* Compiler: rustc 1.62.1 (e092d0b6b 2022-07-16)

**Comment by stefan-mysten** [comment]
Closing this as Sui has evolved a lot since July 2022, so probably this is not valid anymore anyway.
