### ISSUE TITLE
Sui Doc Bug: Make it clear that sui needs to be running in order to run this command

### ISSUE THREAD

**Issue by Genysys** [MystenLabs/sui#3497]
What are the existing URLs containing the issue, if any?

https://docs.sui.io/build/install#sui-tokens

How would you describe the issue? (What needs changing?)

Unable to get client address if sui isnt running.

```
Too many authority errors were detected: [(k#4f8400704ad774a27ba16f87c60c7f558bf488f71a877e8c25fbe2008293b43b, RpcError("error trying to connect: tcp connect error: Connection refused (os error 61)")), (k#f6a0807f14b123b69868e09a3dddb4e0738c799719677391133eb53ab2e1158d, RpcError("error trying to connect: tcp connect error: Connection refused (os error 61)")), (k#e9a5df473b367e33c889fe6f026a7a6281feedf6ccc44f848a762406425c7db0, RpcError("error trying to connect: tcp connect error: Connection refused (os error 61)"))]
```

Where should this information land if new? (Learn, Build, Explore, Contribute.)

- include `sui start` to the instructions. 

What changes are needed to support this new feature or product? (A simple overview, detailed procedures?)

Who is the audience for that information? (App developers, investors, creators, validators, someone else?)

What precisely must they do with it? (Configure a new service? Process some output?)

**Comment by Clay-Mysten** [comment]
Great report! We've started a fix in:
https://github.com/MystenLabs/sui/pull/3503

Thank you!

**Comment by Clay-Mysten** [comment]
Thanks again for the input, @Genysys ! This should be resolved. Please reopen if you have additional input.
