### ISSUE TITLE
Sui Doc Bug : Hyperlink leads to wrong page

### ISSUE THREAD

**Issue by Genysys** [MystenLabs/sui#3522]
What are the existing URLs containing the issue, if any?
https://docs.sui.io/build/move/write-package#defining-the-package 
How would you describe the issue? (What needs changing?)

When i click on [First look at Move source code](https://docs.sui.io/build#first-look-at-move-source-code), I expect to be navigated to page that provides an overview to move source code (https://docs.sui.io/build/move#first-look-at-move-source-code). Instead, I am redirected to this page: [First look at Move source code](https://docs.sui.io/build#first-look-at-move-source-code)

**Comment by Clay-Mysten** [comment]
Thanks for the report! Fixing in:
https://github.com/MystenLabs/sui/pull/3527
