### ISSUE TITLE
Review, validate, and update defined styles for rendering content for Sui

### ISSUE THREAD

**Issue by randall-Mysten** [MystenLabs/sui#3530]
What are the existing URLs containing the issue, if any?
 - this applies globally to the site. Perhaps we could go through and review all of the currently defined styles as a refresh?
 
How would you describe the issue? (What needs changing?)
 - rendered styles of the content. I would like to discuss the following issues:
    - lists are not offset / indented from the left margin. 
    - when the text for a list exceeds the line length for the page, the next line starts at the left margin and not aligned with the indented text from the first line of the list.

`[adding a row between image and text]`
<img width="600" alt="image" src="https://user-images.githubusercontent.com/109545725/181113223-1b82c342-c9e4-41a1-b6ac-757b3e9429e6.png">
`[adding a row between image and text]`

- nested lists are using the same list entry ID format as the parent list

`[adding a row between image and text]`
<img width="800" alt="image" src="https://user-images.githubusercontent.com/109545725/181114850-1ad8f364-a16c-4c8a-a662-a0e6f3a34372.png">
`[adding a row between image and text]`

Where should this information land if new? (Learn, Build, Explore, Contribute.)
 - this is a backend change

What changes are needed to support this new feature or product? (A simple overview, detailed procedures?)
 - n/a

Who is the audience for that information? (App developers, investors, creators, validators, someone else?)
 - all viewers of the site

What precisely must they do with it? (Configure a new service? Process some output?)
 - this is a passive change for users

**Comment by Jibz1** [comment]
@randall-Mysten the fix will up soons

**Comment by randall-Mysten** [comment]
Amazing, thank you!

**Comment by randall-Mysten** [comment]
Is it possible to align the nested lists on the . like it shows in the Git preview? Looks like it is left-aligned on the line margin now?
