### ISSUE TITLE
sui-framework: bug potentially claim multiple rewards for the same epoch

### ISSUE THREAD

**Issue by pchrysochoidis** [MystenLabs/sui#3609]
looking at the code [here](https://github.com/MystenLabs/sui/blob/757df337127da18f60ea2c5a13920be8343a0eb4/crates/sui-framework/sources/governance/delegation.move#L183) it seems there is a way to claim multiple times the reward for the same epoch when the delegation is not active. I think we should check `next_reward_unclaimed_epoch` as well

**Comment by emmazzz** [comment]
Fixed by #3733
