### ISSUE TITLE
Tx Vs SignedTx better naming to logically distinguish for readability

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/sui#3628]
`Transaction` includes user's sig as well, but because we also have a struct called `SignedTransaction`  it always causes confusion when reviewing code on what _Signed_ means. Let's fix that.

Note: We also have `CertifiedTransaction`, this is generally understandable.

**Comment by joyqvq** [comment]
Transaction: user signed => rename to ClientSignedTransaction
Signed Transaction: signed by user and an authority => rename to AuthoritySignedTransaction
Certified Transaction: authority sigs reached 2f+1 and certified

```
pub type Transaction = TransactionEnvelope<EmptySignInfo>;
pub type CertifiedTransaction = TransactionEnvelope<AuthorityStrongQuorumSignInfo>;
pub type SignedTransaction = TransactionEnvelope<AuthoritySignInfo>;
```

**Comment by joyqvq** [comment]
any idea if this is still needed? @lxfind

**Comment by lxfind** [comment]
I would say this is no longer need. We already have SenderSignedData within Transaction
