### ISSUE TITLE
Explorer: Transaction Details Page for `TransferSui`

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#3676]
We are missing the design for the `TransferSui` page. It should look similar to the existing `TransferObject` page except that it will have an extra `amount` field. 

For Eng, the field can be accessed through: https://github.com/MystenLabs/sui/blob/c5cb2e6c7af6bd99318f03e799c6dc8fd2b026cc/sdk/typescript/src/types/transactions.ts#L14

**Comment by mystie711** [comment]
Figma,
https://www.figma.com/file/kSD0qXCIDZA4KQVNepA5hR/02-explorer?node-id=245%3A55192
