### ISSUE TITLE
Explorer: Transaction Details Page for `ChangeEpoch`

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#3677]
`ChangeEpoch` should look similar to the `TransferObject` page(e.g., both have mutated, gas, sender), except that `changeEpoch` should have these extra fields:

```
epoch: 100001;
storage_charge: 12;
computation_charge: 12333;
```

**Comment by mystie711** [comment]
Do we need UI design for this @666lcz ? 
If so, can you provide some spec details?

**Comment by 666lcz** [comment]
@mystie711 Yes we need design for this. Added more details

**Comment by mystie711** [comment]
Figma,
https://www.figma.com/file/kSD0qXCIDZA4KQVNepA5hR/02-explorer?node-id=247%3A55934
