### ISSUE TITLE
[documentation] Document our binaries in a README

### ISSUE THREAD

**Issue by huitseeker** [MystenLabs/sui#370]
We have three, soon-to-be four binaries in our main fastpay `Cargo.toml`. 
- the server,
- the client,
- the benchmark client,
- the CLI (upcoming in #357 as a result of #341 and #353).

The goal of this issue is to add a minimum of documentation for each, including two core pieces of information:
- what it's for,
- what's the minimum amount of setup necessary to launch it.

Our main `README.md` contains at the moment a long-running command line example that might serve as general project workflow doc. This issue is about creating the minimalistic "unit test" version of that to introduce our co-workers to the four binaries in our repo. A good destination for this doc would be the `Readme.md` of the `fastpay` crate.

**Comment by Clay-Mysten** [comment]
Hi François,

I'm writing to see what remains uncovered in this request given the existence of:
https://github.com/MystenLabs/sui/blob/main/doc/src/build/install.md
https://github.com/MystenLabs/sui/blob/main/doc/src/build/wallet.md
https://github.com/MystenLabs/sui/blob/main/doc/src/build/rest-api.md
https://github.com/MystenLabs/sui/blob/main/doc/src/build/move.md

And the forthcoming(?):
https://github.com/MystenLabs/narwhal/blob/main/benchmark/README.md
Per: https://github.com/MystenLabs/Prose/issues/12

Thanks!

**Comment by huitseeker** [comment]
@Clay-Mysten 
1. Those docs have been written with a user in mind that's the user of a blockchain that wants to transact with it. That's all well and good, but we are going to need a different set of docs for a node runner (i.e. somebody running a sui authority + a narwhal authority) That's an entirely new section of the website! 
2. We'll need documentation that's closer to the code too, e.g. rustdoc. 

So, to list some of the things that are documented nowhere: 
- how to run a validator, pass it a genesis config, pass its private key info (or generate it), where to get the genesis config in the first place,
- how to run a narwhal node, link it to the same config and key information, choose a scale-out topology,
- what's in the config, and what parameters there one should tweak when co-deploying Narwhal + Sui.

**Comment by Clay-Mysten** [comment]
Great input. Let's track that in an entirely new issue and close this out:
https://github.com/MystenLabs/sui/issues/1493
