### ISSUE TITLE
[sui-core] Fix bug in `acquire_tx_guard` and action handing

### ISSUE THREAD

**Issue by gdanezis** [MystenLabs/sui#3705]
Currently, `acquire_tx_guard` is written under the assumption that a DBTxGuard may be dropped without a commit only in exceptional circompstances. In fact it prevents re-execution of a certificate that exist without a DBTxGuard commit on the basis this might be a bug in the VM / store etc. 

However this assumption is currently not true: cert execution (owned and shared object) is driven by a future attached to the client connection providing the certificate. At any await point this client future may be dropped, in particular if the client connection is dropped from the client. Therefore, it is entirely within the ability of the client to interrupt certificate transaction processing at any (await) point. 

We have observed this bug in production (see incident 6).

We should fix this in two overlapping ways:
- We should re-design the relationship between the network client futures and the signing / execution in such a way that the client cannot just interrupt it at will. Specifically this will involve passing the active jobs of signing transactions / executing certs from the client connection future to another tokio task that drives their execution and signals back the result. Care should be taken to both reduce the number of tasks (to avoid DoS) but also preserve the current ability to execute on many threads.
- We should then re-examine the assumption the `acquire_tx_guard` makes about how rare such crashes are. And potentially have an automatic way to re-execute transactions with a pending DBTxGuard.

**Comment by lxfind** [comment]
Relevant PRs:
https://github.com/MystenLabs/sui/pull/3713
https://github.com/MystenLabs/sui/pull/3718
https://github.com/MystenLabs/sui/pull/3721

**Comment by mystenmark** [comment]
This should be an easy fix - my plan is just to allow re-execution via user-retries up to some limit (similar to the limit enforced when processing the log at restart), and also have execution driver periodically re-process the queue of failed txes.

**Comment by mystenmark** [comment]
Ah, I see this is mostly fixed already. Thanks!

**Comment by mystenmark** [comment]
The rest of this is fixed by #4060
