### ISSUE TITLE
Explorer: Display object version number

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#3708]
Object version number is useful for debugging - we should have a design for this

For the transaction view, right now we only display the object ids in the mutated and gas object section. But for each object, we should also display their version number (that's incremented by the current transaction).

![CleanShot 2022-08-05 at 12 01 42](https://user-images.githubusercontent.com/76067158/183143966-d8996a82-13da-4f1f-8c8e-7305398f61fb.png)

**Comment by mystie711** [comment]
Figma link,
https://www.figma.com/file/OzLaRFzevjxdQAbybWEZk0/Sui-Visualize?node-id=4694%3A128644

Screenshot attached.
![image](https://user-images.githubusercontent.com/109102528/182880867-36013a4c-4dd3-4ac6-af7c-13b80697bff4.png)

**Comment by mystie711** [comment]
Figma
https://www.figma.com/file/kSD0qXCIDZA4KQVNepA5hR/02-explorer?node-id=327%3A68879
