### ISSUE TITLE
Explorer: show gas breakdown for transactions

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#3709]
Right now we show a flat gas fee, but it can be broken down into three components

![CleanShot 2022-08-02 at 07 53 23](https://user-images.githubusercontent.com/76067158/182405046-398f3f56-ca92-46d1-b276-0c77a5f4cb3c.png)

**Comment by mystie711** [comment]
Figma,
https://www.figma.com/file/kSD0qXCIDZA4KQVNepA5hR/02-explorer?node-id=285%3A61492
