### ISSUE TITLE
Wallet-ext: Show version number for the wallet

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#3723]

**Comment by 666lcz** [comment]
@mystie711 can you work with Dreamten to come up with a design for this? One option is to display the version number at the bottom of hamburger menu:
![CleanShot 2022-08-02 at 13 49 34](https://user-images.githubusercontent.com/76067158/182470749-16440883-c5c4-43f8-af49-c68871b28d3a.png)

cc @bwann52

**Comment by mystie711** [comment]
what is the current version number @666lcz?

**Comment by mystie711** [comment]
Also in figma. Let's use this design.

![image](https://user-images.githubusercontent.com/109102528/182881696-c9ba9624-7957-4516-ad58-f1e0bd502937.png)

**Comment by bwann52** [comment]
Are we able to get the date of the version released on chrome? The dates should match otherwise it may be confusing. If we can't match it I'd rather not show the date since version # is more important anyways.
@mystie711 @666lcz

**Comment by mystie711** [comment]
Makes sense @bwann52

**Comment by mystie711** [comment]
Figma link
https://www.figma.com/file/OzLaRFzevjxdQAbybWEZk0/Sui-Visualize?node-id=4799%3A132314
