### ISSUE TITLE
Enable dark mode on docs.sui.io

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#3745]
What are the existing URLs containing the issue, if any?
docs.sui.io/*

How would you describe the issue? (What needs changing?)
Our light background is difficult for some users. This is particularly hard for me in mobile.

We are requesting a dark mode. Looks available here:
https://color-mode.nuxtjs.org/
https://nuxtjs.org/tutorials/going-dark-with-nuxtjs-color-mode/

Where should this information land if new? (Learn, Build, Explore, Contribute.)
This should be available on every page and be sticky.

What changes are needed to support this new feature or product? (A simple overview, detailed procedures?)
Implement the feature above.

Who is the audience for that information? (App developers, investors, creators, validators, someone else?)
Folks who struggle with the light mode.

What precisely must they do with it? (Configure a new service? Process some output?)
Toggle from one mode to another easily.

**Comment by stefan-mysten** [comment]
Thanks for your suggestion. Since this issue was made, the dark mode was added to docs.sui.io.
