### ISSUE TITLE
Asking for hardware wallet integration test

### ISSUE THREAD

**Issue by BobbyW1028** [MystenLabs/sui#3757]
Hi Sui dev team,

This is Bobby from Keystone hardware wallet. We are asking to be one of the hardware wallet compatible with SUI wallet and the first hardware wallet compatible with SUI ecosystem.

- We are the co-author of BIP-129 (https://github.com/bitcoin/bips/blob/master/bip-0129.mediawiki) and EIP-4527 (https://eips.ethereum.org/EIPS/eip-4527)
- Keystone is the only hardware wallet solution provider of both MetaMask extension and mobile app. (https://www.youtube.com/watch?v=ixRIoGfbmTI)
- Keystone is 100% open source wallet including our security chip (https://github.com/KeystoneHQ/Keystone-cold-app)

We'd like to be the first hardware wallet compatible with Sui Wallet, this is the integration doc on Solana&Ethereum, FYI, hope we could get the opportunity to talk to your tech team.
https://github.com/KeystoneHQ/Keystone-developer-hub/blob/main/research/solana-qr-data-protocol.md
https://github.com/KeystoneHQ/Keystone-developer-hub/blob/main/integration/ethereum.md

Looking forward to hearing from you guys. Thanks!

**Comment by stefan-mysten** [comment]
@BobbyW1028 
Thanks for reaching out. This issue has been stale for over a year, and as part of our process of cleaning up the issues, I will close this one now. Feel free to create a new issue if this is still something desired on your end. Thanks!
