### ISSUE TITLE
When  the validators source code  will it be released？

### ISSUE THREAD

**Issue by bitcard** [MystenLabs/sui#3775]
I want to run test and benchmark using local fullnode +  Validators + Narwhal & Tusk, but now only can build fullnode and sui cli from source, so  when  the Validators source code  will it be released?

**Comment by huitseeker** [comment]
The full source code of the validator is in this repository. We start validators from the `sui-node` binary, with a suitable validator configuration.

This is probably more of a documentation issue, to start jotting dow instructions on how to run such a validator. We plan to have such a configuration (probably with associated `Dockerfile`s) out in the future for testing.
/cc @randall-Mysten @Clay-Mysten

**Comment by Clay-Mysten** [comment]
@bitcard you can see related work underway in:
https://github.com/MystenLabs/sui/issues/1493

**Comment by bitcard** [comment]
> @bitcard you can see related work underway in: #1493

thank you, I will try it. 

thank you for your guide. [huitseeker](https://github.com/huitseeker)
