### ISSUE TITLE
Sui Doc Bug: a horizontal scrollbar on index page

### ISSUE THREAD

**Issue by GreyPK** [MystenLabs/sui#3779]
I found a small frontend bug in you index page https://sui.io/ . It's a unnecessary horizontal scrollbar. I didn't find github repo for index page therefore I can't create pull request, so for fixing bug = removing horizontal scrollbar you need to add to css this code:
```
.main-wrapper {
  max-width: 100%;
}

.bg-top {
  max-width: 100%;
}
```
After it horizontal scrollbar will disappear. My system: win10 x64, browser: lastest chrome x64

**Comment by Clay-Mysten** [comment]
Thank you, Sergey! I've added folks who can confirm and fix. Thanks again for the report!
