### ISSUE TITLE
Fullnode should not download signed effects from 2f+1 validators

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#3834]
Downloading evert signed effects from 2f+1 validators can take a huge amount of network resources, especially if we have 6000+ fullnodes.
Through signed batches (which contains both tx and effect digest), a fullnode should already be able to know that 2f+1 validators have executed the tx. From there, the fullnode should be able to just execute the tx locally and cross-compare the effects digest.

**Comment by gdanezis** [comment]
From what I can tell it is not meant to be downloading them from all right now. But there might be a bug in node_follower that results in this?

**Comment by mystenmark** [comment]
It doesn't download from 2f+1.

It waits for 2f+1 to claim the same execution digests, then it downloads the cert + effects from 1 validator. (It may contact multiple validators if the first times out, but the usual case would be 1 download).

It always needs to download the cert. (of course). Technically it can do without the effects unless it is a shared object tx, but I'm not sure that is worth optimizing right now.

**Comment by gdanezis** [comment]
I think on this basis (and unless we think there is a bug here) we can close this. (I also looked quickly at this code, and nothing obvious jumps up).

**Comment by mystenmark** [comment]
Agreed - closing.
