### ISSUE TITLE
Log number of bytes in/out for each request type on validators

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#3835]
This will help us understand which request is consuming the most network bandwidth.

**Comment by laura-makdah** [comment]
@gdanezis @lxfind I just spoke with @bmwill on this, and based on our assessment, there isn't a way to record the bytes as metrics per route using the GRPC infra that we currently have. I don't see much value in having the bytes recorded among all routes but not filterable. I experimented with a different approach [here](https://github.com/MystenLabs/sui/pull/3920) where we record the memory usage of the struct that we send as requests / responses. However, that approach would give us at best a very rough estimation, and is both resource intensive computationally and hard to maintain. 

Brandon's plans for our next generation networking stack enable tracking this kind of data in a much simpler way. I would propose delaying this until we have migrated away from GRPC, which may be sometime next month.
