### ISSUE TITLE
Update API docs with full type definition

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#3877]
Our API docs (and in particular to the type definitions of key response types like SuiEventEnvelope) are hard to discover in our current docs site. You will only see SuiEventEnvelope if you happen to click on sui_subscribeEvent, and even then you will not see the full type definition. I think our docs should show type definitions in addition to API functions.

context: https://mysten-labs.slack.com/archives/C03GYL579PD/p1659991524419939

**Comment by patrickkuo** [comment]
There are on going work to improve the navigation of the doc, see https://github.com/MystenLabs/sui/issues/1362

also cc @Clay-Mysten

**Comment by Clay-Mysten** [comment]
Also, I think there is work here to expose the full type definition as requested by @sblackshear . Adding @Jibz1 for help.

**Comment by Clay-Mysten** [comment]
@patrickkuo says we can also generate the `curl` commands now shown in our docs. Is this possible, @Jibz1 ? Thanks!

**Comment by Clay-Mysten** [comment]
As well as include some boiler plate text to make requests and responses valid. @patrickkuo can explain more.

**Comment by patrickkuo** [comment]
We can resolve the `$ref` path to get the full type definition. e.g. definition for `EventEnvelope`https://github.com/MystenLabs/sui/blob/db724585021b554742158b44e74e0646fccf6651/crates/sui-open-rpc/spec/openrpc.json#L2248-L2281

Regarding the request/response boilerplate code, I am not sure if this is the right issue to mention that, I will do it here anyway 😅: the request and response in our current api doc is not a valid JSON-RPC request/response.
using `sui_batchTransaction` as an example, the request should looks like
```
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "sui_batchTransaction",
  "params": [
    "0x76a04053bda0a88bda5177b86a15c3b29f559873",
    [
      {
        "moveCallRequestParams": {
          "arguments": [
            "Example NFT",
            "An NFT created by the Sui Command Line Tool",
            "ipfs://bafkreibngqhl3gaa7daob4i2vccziay2jjlp435cf66vhono7nrvww53ty"
          ],
          "function": "mint",
          "module": "devnet_nft",
          "packageObjectId": "0x0000000000000000000000000000000000000002",
          "typeArguments": []
        }
      },
      {
        "transferObjectRequestParams": {
          "objectId": "0x1f6de831e52bfb76e51cca8b4e9016838657edfa",
          "recipient": "0xcb481232299cd5743151ac4b2d63ae198e7bb0a9"
        }
      }
    ],
    "0x011f28e473c95f4013d7d53ec5fbc3b42df8ed10",
    1000
  ]
}
``` 
we can use openrpc playground as an example of how to render the request/response

regarding curl command, I think it's nice to have, we can add it if we have bandwidth

**Comment by Jibz1** [comment]
This is done

**Comment by Clay-Mysten** [comment]
> This is done

Thanks, Godwin!
