### ISSUE TITLE
[wallet-ext][bug] Failure to connect to dapp

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#3881]
few people have flagged that see this error msg when trying to connect the wallet to the test application

![Image](https://user-images.githubusercontent.com/22014917/183714914-a8c1124e-12a6-4911-9d5d-db5eb6e03994.png)

**Comment by gegaowp** [comment]
@bwann52 this is because this is a pending window, they can either close that or approve/reject to unblock.
@pchrysochoidis is it required to have such limitation?

**Comment by jamescarter-le** [comment]
I have found previously you can get the Sui Wallet in such a state that the approval window will not show, and is completely locked up, the only way to get round this is to uninstall/reinstall the extension.

**Comment by pchrysochoidis** [comment]
> is it required to have such limitation?

@gegaowp not really, it was done like this mostly to keep things simple. I will have a look to find a way to fix it
