### ISSUE TITLE
[sui-core] Limit the size of the WAL and the size of memtables for all DBs

### ISSUE THREAD

**Issue by gdanezis** [MystenLabs/sui#3885]
Currently we do not allow users to set in configs the size of the WAL before flush:
https://docs.rs/rocks/latest/rocks/options/struct.DBOptions.html#method.max_total_wal_size
as well as the total size of memtables in memory:
https://docs.rs/rocks/latest/rocks/options/struct.DBOptions.html#method.db_write_buffer_size

Full nodes / gateways and even validators may wish to operate within hardware limits, and therefore we should allow them this control.

**Comment by mwtian** [comment]
What about an env var for easy control?

**Comment by oxade** [comment]
> I can look into configs but passing to all rocksdb creation sites or to typed-store a little bit of work.

@mwtian see this [proposal](https://github.com/MystenLabs/mysten-infra/pull/116). It'll auto generate config structs for all tables. We just have to assign them some values. I don't mind taking this up. Waiting for George to take a look.

**Comment by huitseeker** [comment]
@mwtian landed the defaults for mem & WAL use; https://github.com/MystenLabs/mysten-infra/blob/8d090689be14078f2ca41c356e7bbc0af21f73ab/crates/typed-store/src/rocks/mod.rs#L441-L478

**Comment by mwtian** [comment]
Since we have bumped mysten-infra versions in Narwhal and Sui, I think we can mark this closed.
