### ISSUE TITLE
Rewrite install docs by OS, merge install command from fullnode

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#3897]
What are the existing URLs containing the issue, if any?
https://docs.sui.io/build/install
https://docs.sui.io/build/fullnode
https://docs.sui.io/contribute

How would you describe the issue? (What needs changing?)
We introduced support for Windows 11 yesterday. Although @patrickkuo Patrick and I have gotten the essential information in place, @randall-Mysten believes he can better organize this information by operating system.

This effort should also include bringing in the Linux install command and related guidance for other operating systems from the Fullnode doc, as it is confusing to users to go to multiple places for the same set of steps. Further, @bmwill confirmed long ago these same packages are needed for Sui development with or without Fullnode.

Where should this information land if new? (Learn, Build, Explore, Contribute.)
The existing Install page.

What changes are needed to support this new feature or product? (A simple overview, detailed procedures?)
Reorganization, standardization, simplification.

We should also consider bringing the Docker contents directly into the site:
https://github.com/MystenLabs/sui/tree/main/docker/fullnode#readme

Adding the Fullnode team for guidance there and review of the suggested changes.

Who is the audience for that information? (App developers, investors, creators, validators, someone else?)
Sui developers

What precisely must they do with it? (Configure a new service? Process some output?)
Get up and running in Sui ASAP.

**Comment by Clay-Mysten** [comment]
Also, I failed to mention we should determine whether to fork or not as we do so in Contribute and Fullnode but not Install. Again, Randall has ideas.

**Comment by Clay-Mysten** [comment]
Taking up the forking conversation in Slack with @janetwu11 , @todd-mystenlabs , @lxfind , @randall-Mysten , @bhenhsi and myself.

**Comment by randall-Mysten** [comment]
Closing this issue since this would be included in the site reorg etc.
