### ISSUE TITLE
Develop Sui Explorer user docs for docs.sui.io, link from Explorer

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#3899]
What are the existing URLs containing the issue, if any?
https://docs.sui.io/devnet/explore#sui-explorer
https://github.com/MystenLabs/sui/tree/main/explorer/client#readme
https://docs.sui.io/devnet/explore/devnet#basic-testing

How would you describe the issue? (What needs changing?)
Our only docs about the Explorer on docs.sui.io are in the Devnet page. And our only docs linked from the site is the README covering setup. We need user docs, especially as the product evolves.

And once those docs are live, they should be linked from explorer.devnet.sui.io for help.

Where should this information land if new? (Learn, Build, Explore, Contribute.)
https://docs.sui.io/devnet/explore/sui-explorer

What changes are needed to support this new feature or product? (A simple overview, detailed procedures?)
We need detailed instructions for common uses made up-to-date with the latest features. Again, we have a start on this in the Devnet docs, but I am certain that is woefully out of date.

Who is the audience for that information? (App developers, investors, creators, validators, someone else?)
Folks conducting transactions on the Sui blockchain.

What precisely must they do with it? (Configure a new service? Process some output?)
Find simple instructions for the most common tasks. Bonus points for new screenshots.

**Comment by Clay-Mysten** [comment]
Related work underway in:
https://github.com/MystenLabs/sui/pull/3291
https://github.com/MystenLabs/sui/pull/3837

**Comment by Clay-Mysten** [comment]
I'm noting I'm asking @randall-Mysten to take lead on these docs. Let's get cracking in our dogfooding session today.

**Comment by bhenhsi** [comment]
@AkashaCoin to propose outlines and draft as the next step.
