### ISSUE TITLE
Devnet memory leak in fullnode

### ISSUE THREAD

**Issue by rsilvestre** [MystenLabs/sui#3908]
## Steps to Reproduce Issue

Just start the fullnode from the code source

## Expected Result

The server should to be up and running

## Actual Result

Server or service crash after 12 minutes

![84E2DC5A-37FA-41C1-A518-60B00F5ADC7E](https://user-images.githubusercontent.com/213663/184027069-b12ee8cd-1cbd-424b-a0ed-448a536d55a3.png)

## System Information

* OS: debian 11.4
* Compiler: rustic 1.62.1

**Comment by rsilvestre** [comment]
@huitseeker do you think that your pull request is going to fix that ? : https://github.com/MystenLabs/sui/pull/3905

**Comment by kernelpanic9** [comment]
Experiencing the same.
See memory utilization stats log for sui process.
[sui_mem_leak.log](https://github.com/MystenLabs/sui/files/9305109/sui_mem_leak.log)
.

**Comment by huitseeker** [comment]
This should be fixed in #3874

**Comment by Clay-Mysten** [comment]
I think it's time to revisit our system requirements for fullnode.

**Comment by Clay-Mysten** [comment]
Reopened related:
https://github.com/MystenLabs/sui/issues/1367
