### ISSUE TITLE
error: failed to run custom build command for tonic-health v0.6.0

### ISSUE THREAD

**Issue by boray** [MystenLabs/sui#3917]
error: failed to run custom build command for tonic-health v0.6.0

Caused by:
  process didn't exit successfully: /root/sui/target/release/build/tonic-health-939e32fd3885f979/build-script-build (exit status: 1)
  --- stderr
  Error: Custom { kind: Other, error: "protoc failed: health.proto:18:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".\n" }
warning: build failed, waiting for other jobs to finish...

I am getting this error while installing the Sui full node. 

e.g.
<other function call> returned 41.

## System Information

* OS: Ubuntu 16.04

**Comment by stefan-mysten** [comment]
@boray closing this issue as it's been a while and the error has been fixed. Feel free to create a new issue if you still have problems installing Sui.
