### ISSUE TITLE
signature error: Cannot find key for address

### ISSUE THREAD

**Issue by SebastianPere1ra** [MystenLabs/sui#3918]
sui client transfer-sui --to 0xcc8799d4780db27c677fc34ea0699413f9cf6ca2 --sui-coin-object-id 0xfd6bd9290f69879db94ed73efb6b0c805a6ca961 --gas-budget 100 --amount 111
signature error: Cannot find key for address: [0x813ec1ab1e1797c79d1e1fcbebebc27a1fd21f07]

**Comment by 666lcz** [comment]
This should have been fixed now
