### ISSUE TITLE
Invalid 'use'. Unbound member 'UID' in module '(sui=0x2)::object'

### ISSUE THREAD

**Issue by merdan-9** [MystenLabs/sui#3923]
Hi, I failed to compile this code 
https://github.com/MystenLabs/sui/blob/main/sui_programmability/examples/objects_tutorial/sources/color_object.move

could someone please tell what is wrong?

===>
error[E03003]: unbound module member
  ┌─ ./sources/m1.move:5:29
  │
5 │     use sui::object::{Self, UID};
  │                             ^^^ Invalid 'use'. Unbound member 'UID' in module '(sui=0x2)::object'
  │
  ┌─ ./../sui/crates/sui-framework/sources/object.move:5:13
  │
5 │ module sui::object {
  │             ------ Module '(sui=0x2)::object' declared here

error[E03004]: unbound type
   ┌─ ./sources/m1.move:10:13
   │
10 │         id: UID,
   │             ^^^ Unbound type 'UID' in current scope

Failed to build Move modules: "Compilation error".

**Comment by 0xBeans** [comment]
`UID` is no longer a valid struct inside the `object` module, I suspect this tutorial is out of date. 

To quick fix, change `use sui::object::{Self, UID};` to `use sui::object::{Self, Info};` - `Info` is the current way to declare a Sui storage object with ID.

Then, change all keys from `id` to `info` (e.g. `info: Info`) in all object declarations and unpackings. Now everything should compile :)
