### ISSUE TITLE
sui move build - build from root directory

### ISSUE THREAD

**Issue by SaveliyLipaev** [MystenLabs/sui#3925]
Hello!
I'm trying to make a build as it says in the documentation, I call the command from the directory where the code I want to build is located, but for some reason it tries to build in the /root directory, I can't write the path directly, I didn't find answers in the documentation, thanks! 
sui built today (08/11/2022)
OS: Ubuntu 20
![image](https://user-images.githubusercontent.com/43678404/184172814-d16e0206-e46f-4f74-b704-39e406655f6f.png)

**Comment by 666lcz** [comment]
Verified that this problem has been resolved in `main`
