### ISSUE TITLE
Create section dedicated for developer tools

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#3934]
Similar to the SUI JSON-RPC V 0.6.1, it would be nice to have a section (accessible in side nav menu) where we can also list out our other SDKs, such as TS SDK

**Comment by Clay-Mysten** [comment]
Done!
https://docs.sui.io/build/comms

**Comment by bhenhsi** [comment]
Hi @bwann52 could you take a look at the current structure? Is that what you had in mind?

**Comment by bwann52** [comment]
Yes I was imagine a separate SDK/Tooling section. Let me check with @666lcz and @bholc646 to see what are the timelines. Meanwhile, is it trivial to add such a section as we discussed briefly @Jibz1 ?
