### ISSUE TITLE
Improve TypeScript documentation, bring into docs.sui.io

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#3937]
What are the existing URLs containing the issue, if any?

https://docs.sui.io/build/comms
https://github.com/MystenLabs/sui/tree/main/sdk/typescript

**Comment by Clay-Mysten** [comment]
In meeting with @666lcz, we agreed to:
Document new flag to turn off data validation
Create new user doc for TypeScript SDK and link from the new Talk with Sui (comms) index:
https://docs.sui.io/build/comms

**Comment by Clay-Mysten** [comment]
Addendum, we also will link to Wallet Adapter docs:
https://github.com/MystenLabs/sui/pull/4186/files

**Comment by Clay-Mysten** [comment]
https://github.com/MystenLabs/sui/tree/main/wallet-adapter

**Comment by Clay-Mysten** [comment]
I am noting @sblackshear is suggesting we may need to pull this SDK until we sort out the ordering enhancement needed and reported by Damir.

**Comment by Clay-Mysten** [comment]
Hi @666lcz , let me know when we can work on this. Thanks!

**Comment by Clay-Mysten** [comment]
Just checking in here, @666lcz . Thanks!

**Comment by randall-Mysten** [comment]
Closing this issue. We will address these issues as we rewrite the docs
