### ISSUE TITLE
Explorer: Consistently style the scrollbar

### ISSUE THREAD

**Issue by Jordan-Mysten** [MystenLabs/sui#3938]
Currently, the scrollbar is the system default. We should implement a scrollbar across all platforms that is consistent based on designs.

**Comment by Andrew47** [comment]
So that we do not lose the previous work on implementing current custom scrollbar CSS code that was deleted in PR https://github.com/MystenLabs/sui/pull/4856, the branch `newScrollbars` has been added to this issue.
