### ISSUE TITLE
`AuthorityTemporaryStore` potential inconsistent access of object state

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#394]
In `AuthorityTemporaryStore`, we have two fields that contain object state: `objects` and `written`. `objects` contains the original content of the objects from the input, while `written` contains any mutated object state.
Whenever we are trying to read objects, unless it's read-only, we will need to read from `written` first to see if it's there.
We should also consider renaming `objects` to something like `original_objects` to avoid confusions.

**Comment by awelc** [comment]
This has been addressed in https://github.com/MystenLabs/sui/pull/337 and https://github.com/MystenLabs/sui/pull/436.
