### ISSUE TITLE
librocksdb-sys build failed

### ISSUE THREAD

**Issue by lrinQVQ** [MystenLabs/sui#3943]
## Steps to Reproduce Issue
System: Ubuntu 18.04
Cmake: 3.24.0
Gcc: 7.5.0

Install all dependencies in https://docs.sui.io/devnet/build/fullnode#software-requirements
`$ git clone https://github.com/MystenLabs/sui -b devnet`
`$ RUST_BACKTRACE=full cargo build --release`
## Expected Result
Compiling librocksdb-sys v0.6.1+6.28.2

## Actual Result
https://paste.ubuntu.com/p/FsZ7yczHYq/
Fix after `apt install clang/clang-6.0`

**Comment by mwtian** [comment]
Yeah libclang is a dependency for building Sui. Maybe we can specify a minimum version too.
