### ISSUE TITLE
wallet-ext: Design for empty wallet

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#3951]
We show the following if the wallet is empty. We might want to add some content

<img width="370" alt="CleanShot 2022-08-12 at 12 52 15@2x" src="https://user-images.githubusercontent.com/76067158/184433082-2a19054d-53b7-4036-86e5-880165fabe56.png">
<img width="377" alt="CleanShot 2022-08-12 at 12 52 10@2x" src="https://user-images.githubusercontent.com/76067158/184433088-504fa0a2-b407-461d-aa7b-8e340d6e2387.png">

**Comment by mystie711** [comment]
Figma design solution captured here,
https://www.figma.com/file/xu2VnyPAuruNi74UQzGigW/02-Wallet?node-id=457%3A28709
