### ISSUE TITLE
devnet: Invalid index pointer

### ISSUE THREAD

**Issue by lrinQVQ** [MystenLabs/sui#3959]
https://github.com/MystenLabs/sui/commit/8c16964fa36a09a8c841f6e5bcff82f406e8e6d9 commit points narwhal index to https://github.com/MystenLabs/narwhal/commit/fd070584b57304a8c7b94ee7af656a9375fc2095 but now its [606c3a9e81f18bc65c1ffa99152452e387d081f8](https://github.com/MystenLabs/narwhal/commit/606c3a9e81f18bc65c1ffa99152452e387d081f8) this will cause Cargo to fail to download dependencies, is this expected?

**Comment by e-kolpakov** [comment]
Also had this, temporary workarounds:
```
curl -O https://github.com/lrinQVQ/sui/commit/f7ff151340917aac6231396742babc686141bd05.patch
git am f7ff151340917aac6231396742babc686141bd05.patch
```

Or

```
git checkout 8a29394515eaf520cc6fa54bca8ce0c22db0dbc8
```

... and then `cargo run ...` (or `cargo build ...`)

**Comment by PDPLAN** [comment]
![Uploading sui-ss.png…]()

**Comment by huitseeker** [comment]
Hi folks, I suspect this is a duplicate of #3980 

Our devnet branch was momentarily de-synced from where it should be. It has now been updated. Please retry the install instruction as documented:

`cargo install --locked --git https://github.com/MystenLabs/sui.git --branch "devnet" sui sui-gateway`



@lrinQVQ we should not be using the branch name anywhere to refer to Narwhal, have you found a stray pointer somewhere?
> this will cause Cargo to fail to download dependencies,
How would I reproduce?

**Comment by lrinQVQ** [comment]
> 

Yeah, devnet branch used to use stray pointers, which caused the same issue as #3980, now it's fixed and working,  thanks!
