### ISSUE TITLE
fullnode install error.

### ISSUE THREAD

**Issue by mbzdg** [MystenLabs/sui#3964]
When i try to install, i failed and, error is below.
How can i solve this.

cargo run --release --bin sui-node -- --config-path fullnode.yaml

    Updating git repository `https://github.com/MystenLabs/narwhal`
error: failed to get `config` as a dependency of package `sui-config v0.0.0 (/home/ubuntu/fullnode/sui/crates/sui-config)`

Caused by:
  failed to load source for dependency `config`

Caused by:
  Unable to update https://github.com/MystenLabs/narwhal?rev=fd070584b57304a8c7b94ee7af656a9375fc2095#fd070584

Caused by:
  object not found - no match for id (fd070584b57304a8c7b94ee7af656a9375fc2095); class=Odb (9); code=NotFound (-3)

**Comment by oldguydev** [comment]
Have same problem, any solution?

**Comment by ikky888** [comment]
Same here!

**Comment by HyeongpilChoi** [comment]
same here

**Comment by HyeongpilChoi** [comment]
https://medium.com/coinmonks/tutorial-how-to-install-a-full-node-on-the-sui-network-of-mysten-labs-for-beginners-devnet-e482aa30537a

see part 9

**Comment by mbzdg** [comment]
Thank you, this patch is a solution.

**Comment by ikky888** [comment]
Thank you soooooo much! @HyeongpilChoi
