### ISSUE TITLE
Caused by: failed to load source for dependency 'config'

### ISSUE THREAD

**Issue by ruanling** [MystenLabs/sui#3980]
error when I install SUI: 

`Caused by:
  failed to load source for dependency 'config'`
![image](https://user-images.githubusercontent.com/33116879/184571741-ab7d3b37-bf54-4944-a717-eefe9d5b5b91.png)

**Comment by 0xNonso** [comment]
I was just about to open an issue for this too. I'm on mac and experiencing same issue. 
I already tried rebooting my pc and reinstalling rust as was suggested here - [#3776](https://github.com/MystenLabs/sui/issues/3776#issuecomment-1207404413) but still getting the error

**Comment by KuoKongQingYun** [comment]
same problem.

**Comment by Elsant** [comment]
Me too, as root and non root user for native build

**Comment by ruanling** [comment]
I try running this command and it worked
git checkout 8a29394515eaf520cc6fa54bca8ce0c22db0dbc8

**Comment by joyqvq** [comment]
try `cargo install --locked --git https://github.com/MystenLabs/sui.git --branch "main" sui sui-gateway`

branch `devnet` is under maintenance atm, we will update the doc accordingly.

**Comment by huitseeker** [comment]
Hi folks,
Our `devnet` branch was momentarily de-synced from where it should be. It has now been updated. Please retry the install instruction as documented:

`cargo install --locked --git https://github.com/MystenLabs/sui.git --branch "devnet" sui sui-gateway`
