### ISSUE TITLE
 running cmake: Unknown argument --parallel, Unknown argument 1

### ISSUE THREAD

**Issue by ruanling** [MystenLabs/sui#3991]
cargo run error:   
Unknown argument --parallel
Unknown argument 1
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

![image](https://user-images.githubusercontent.com/33116879/184640532-8559fc63-56ba-4583-99e5-ef51116d88c8.png)

**Comment by ruanling** [comment]
warning: build failed, waiting for other jobs to finish...
error: failed to compile `sui v0.6.2 (https://github.com/MystenLabs/sui.git?branch=devnet#26f9f7ed)`, intermediate artifacts can be found at `/tmp/cargo-install0kgCTM`
error: failed to compile `sui-gateway v0.0.0 (https://github.com/MystenLabs/sui.git?branch=devnet#26f9f7ed)`, intermediate artifacts can be found at `/tmp/cargo-installGpkbrN`
     Summary Failed to install sui, sui-gateway (see error(s) above).
error: some crates failed to install

![image](https://user-images.githubusercontent.com/33116879/184879118-fda06913-0030-4501-bdae-d8fac7fbd06f.png)

**Comment by mwtian** [comment]
What is the OS and cmake version? Upgrading may fix the issue.

**Comment by ruanling** [comment]
> 
OS: Ubuntu 18.04 
cmake version 3.10.2

**Comment by stefan-mysten** [comment]
@ruanling since the report, this problem has likely been fixed. I will close the issue now but feel free to create a new issue if you still encounter problems when installing Sui.
