### ISSUE TITLE
explorer: click to definition should also use the definitions within structs

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#4016]
![CleanShot 2022-08-15 at 13 06 06](https://user-images.githubusercontent.com/76067158/184709400-d5db4933-0ab7-4c6a-beff-bd4f09165f01.png)

We should figure out why UID, RUM, Supply, Balance are not highlighted

**Comment by Jordan-Mysten** [comment]
@666lcz They'll only be highlighted if they're referenced in arguments to functions, we can update the highlighting to also pull out the definitions within structs. The only missing piece after that I believe would be private functions.
