### ISSUE TITLE
[move] Unexpected `test_scenario::take_last_created_owned` failure

### ISSUE THREAD

**Issue by awelc** [MystenLabs/sui#4021]
## Steps to Reproduce Issue

Executing the following code results in an abort in `test_scenario::take_last_created_owned` and I am not sure if this is expected or not. Intuitively (at least to me) this should not fail (we should at least document this).

```
│ error[E11001]: test failure
│     ┌─ ./../../sui/crates/sui-framework/sources/test_scenario.move:150:9
│     │
│ 143 │     public fun take_last_created_owned<T: key>(scenario: &mut Scenario): T {
│     │                ----------------------- In this function in 0x2::test_scenario
│     ·
│ 150 │         assert!(num_objects > 0, EEmptyInventory);
│     │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Test was not expected to abort but it aborted with 3 here
│ 
│ 
│ stack trace
│ 	repo::fails(./sources/repo.move:28)
│ 
└──────────────────
```

```
module mygame::repo {

	use sui::object::{Self, UID};
	use sui::tx_context::{Self, TxContext};
	use sui::transfer;
	const ADMIN: address = @0xC0FFEE;
	struct ExampleObject has key {
		id: UID,
		value: u64
	}

	fun create_example_object(value: u64, ctx: &mut TxContext) {
		transfer::transfer(ExampleObject {
			id: object::new(ctx),
			value: value
		}, tx_context::sender(ctx));
	}

	#[test]
	fun fails() {
		use sui::test_scenario;
		use std::debug;

		let scenario = &mut test_scenario::begin(&ADMIN);
		test_scenario::next_tx(scenario, &ADMIN);
		{
		    create_example_object(1, test_scenario::ctx(scenario));
			let obj = test_scenario::take_last_created_owned<ExampleObject>(scenario);
			debug::print(&obj.value);
			assert!(obj.value == 1, 1);
			test_scenario::return_owned(scenario, obj);
		};
	}
}
```

**Comment by emmazzz** [comment]
This is actually expected behavior. The objects you created/modified in one transaction are only "written" to the storage after the current transaction has passed by calling `test_scenario::next_tx`. So the following code should work (I think):
```rust
let scenario = &mut test_scenario::begin(&ADMIN);
create_example_object(1, test_scenario::ctx(scenario));
test_scenario::next_tx(scenario, &ADMIN);
{
    let obj = test_scenario::take_last_created_owned<ExampleObject>(scenario);
    assert!(obj.value == 1, 1);
    test_scenario::return_owned(scenario, obj);
};
```
I agree it's very confusing and should be better documented. In general, our testing experience has a lot of room for improvement.

**Comment by awelc** [comment]
> This is actually expected behavior. The objects you created/modified in one transaction are only "written" to the storage after the current transaction has passed by calling `test_scenario::next_tx`. 

I expected something like this might be the case but figure I should flag just in case.


> I agree it's very confusing and should be better documented. In general, our testing experience has a lot of room for improvement.

Agreed! I am cc-ing @Clay-Mysten for visibility but closing otherwise.

**Comment by Clay-Mysten** [comment]
Thanks for the pointer, @awelc . And @emmazzz , would it make sense to add this information here?
https://docs.sui.io/devnet/build/transactions

Namely that objects you created/modified in one transaction are written to the storage only after the current transaction has passed by calling `test_scenario::next_tx`? Thank you both!

**Comment by emmazzz** [comment]
> Namely that objects you created/modified in one transaction are written to the storage only after the current transaction has passed by calling test_scenario::next_tx?

This `test_scenario` thing only applies to testing your Move code, not to actual transaction calling. `test_scenario` is a library Move module we have written for simulating actual sequences of transactions in Move unit tests. So this information will be appropriate in a place that documents how testing works in Sui Move, if such place exists.

Besides adding to the documentation, I wonder if we should also make the error message better. It would be nice if we can include a custom message in `assert!` and do something like 
```
assert!(num_objects > 0, EEmptyInventory, "No object in the inventory. Have you tried tx_scenario::next_tx to flush newly created objects to storage");
```
And this custom message will be shown when the code aborts here.

**Comment by awelc** [comment]
> Besides adding to the documentation, I wonder if we should also make the error message better.

That would be cool, but I think it would require some work on core Move side to enhance assertions support. In the meantime, here's a proposal for the docs enhancement (also includes the long-standing addition about `debug::print`).

**Comment by Clay-Mysten** [comment]
I'm noting Adam's changes in the following PR LGTM with some small changes:
https://github.com/MystenLabs/sui/pull/4059/files

I still need to include Adam's changes to `doc/src/build/cli-client.md` as that file has moved. I also still think the proposed explanation above would also clear things up.

**Comment by awelc** [comment]
> I also still think the proposed explanation above would also clear things up.

I agree with @emmazzz that the https://docs.sui.io/devnet/build/transactions location is not the right place for this. We are talking about the testing framework here and mentioning it in the "general" transaction description without context will be rather confusing in my opinion.

**Comment by Clay-Mysten** [comment]
> > I also still think the proposed explanation above would also clear things up.
> 
> I agree with @emmazzz that the https://docs.sui.io/devnet/build/transactions location is not the right place for this. We are talking about the testing framework here and mentioning it in the "general" transaction description without context will be rather confusing in my opinion.

Ack. That covers location. Does the summary help anywhere then?

**Comment by Clay-Mysten** [comment]
Adding @awelc as I believe his doc changes resolve this.
