### ISSUE TITLE
Update Roadmap

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#4052]
https://github.com/MystenLabs/sui/blob/main/ROADMAP.md

This hasn't been updated in a few months and a lot of these upcoming milestones have been reached

**Comment by Clay-Mysten** [comment]
Great. Let us work together to compile updates.  What do you have?

**Comment by Clay-Mysten** [comment]
Adding @sblackshear for additional updates and review of:
https://github.com/MystenLabs/sui/pull/4054

**Comment by Clay-Mysten** [comment]
@losamsel related. See:
https://github.com/MystenLabs/sui/pull/4055

**Comment by Clay-Mysten** [comment]
I believe this work is done. Please reopen if you see something amiss. Thanks for the reminder.
