### ISSUE TITLE
Explorer: Transaction table UI deltas

### ISSUE THREAD

**Issue by Jordan-Mysten** [MystenLabs/sui#4067]
Figma reference: https://www.figma.com/file/kSD0qXCIDZA4KQVNepA5hR/02-Explorer?node-id=67%3A18955
Current state:
![Image](https://user-images.githubusercontent.com/109986297/185000992-6b40738f-2f65-4edf-a436-37aed22e4acf.png)

Context: https://mysten-labs.slack.com/archives/C03DD6MKVHC/p1660675077673429

**Comment by mystie711** [comment]
The exact deltas and the design updates expected are captured here,
https://www.figma.com/file/YJt9Bs4eyhD9PmeZQbFTkf/dev-feedback?node-id=80%3A848
