### ISSUE TITLE
Use authorities that have the cert for authority cert sync

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#407]
Currently when we call `sync_authority_source_to_destination`, the sources we provided are simply the authorities that singed this order in the cert, but not necessarily the authorities that actually are aware of the cert.
We do know which authorities have the cert in the caller chain. So instead of passing above, we should use source authorities that we know have the cert for the sync. This will make it the sync lot faster (one try instead of trying many authorities).

**Comment by gdanezis** [comment]
Not a huge priority, optimisation on the client side.
