### ISSUE TITLE
When running a full node I get RpcError("error trying to connect: tcp connect error:  Connection refused (os error 111)")

### ISSUE THREAD

**Issue by ikky888** [MystenLabs/sui#4074]
## Steps to Reproduce Issue
After install SUI full node following this [guide,](https://docs.sui.io/devnet/build/fullnode) run this command to start it:
cargo run --release --bin sui-node -- --config-path fullnode.yaml

## Expected Result
SUI node started successfully

## Actual Result
I see the following error message being displayed on the terminal:
ERROR sui_core::authority_active::gossip: Peer returned error: RpcError("error trying to connect: tcp connect error:
 Connection refused (os error 111)") 

The firewall from the LightSail Dashboard is inactive and I even setup ufw as follows but still the same error:
ufw allow ssh 
ufw allow https 
ufw allow http 
ufw allow 9000
ufw allow 9184
ufw enable
## System Information

* OS: Ubuntu 20.04 LTS running on AWS LightSail

**Comment by ikky888** [comment]
![Screenshot 2022-08-17 082309](https://user-images.githubusercontent.com/25952660/185007440-2f248eda-d587-42af-b7e6-6e680f3e310a.png)

**Comment by stefan-mysten** [comment]
@ikky888 this has likely been fixed since, but feel free to create a new issue if you still have problems.
