### ISSUE TITLE
docs for better dev experience

### ISSUE THREAD

**Issue by econmysten** [MystenLabs/sui#4097]
a partner noted the following requests for documentation:
- coin type arguments
- parameters for RPC calls
- more documentation for shared objects
- best practices for batching, merging, splitting objects

**Comment by Clay-Mysten** [comment]
@econmysten here are some docs to return to the partner for feedback:
coin type arguments - https://docs.sui.io/devnet/build/programming-with-objects/ch4-object-wrapping#direct-wrapping
parameters for RPC calls - https://docs.sui.io/sui-jsonrpc
more documentation for shared objects - https://examples.sui.io/basics/shared-object.html
best practices for batching, merging, splitting objects - https://docs.sui.io/devnet/build/programming-with-objects

I have also added Sam and Chris, which you copied on the Slack thread, and our wonderful doc leads for other ideas. Regardless, we will likely need more details (such as specific questions and obstacles) to help much further.

**Comment by Clay-Mysten** [comment]
Much more to do here.

**Comment by Clay-Mysten** [comment]
@econmysten can you run the docs above past the partner for feedback and ask for more specifics on where they are struggling? Or put me in touch with them? Thanks!

**Comment by Clay-Mysten** [comment]
Adding @bhenhsi for help on partner outreach. Thanks, Brian!

**Comment by Clay-Mysten** [comment]
@sblackshear I am including an admittedly belated shared object announcement with Bullshark in this change:
https://github.com/MystenLabs/sui/pull/4238

Please let me know if you don't want that in. Thanks!

**Comment by Clay-Mysten** [comment]
@econmysten , also please note @Jibz1 and @patrickkuo have been working to improve the API reference docs with full type definitions per input from @sblackshear:
https://github.com/MystenLabs/sui/issues/3877

I believe that work is complete.

And for my own future work here, Sam suggests we take on the bigger task of refactoring `cli-client.md` to call a function other than `sui::transfer` such as `coin::split_and_transfer`.

Related, @aschran is adding an example for splitting coins into equal parts without needing to specify the individual amount for every new coin in:
https://github.com/MystenLabs/sui/pull/4223

**Comment by Clay-Mysten** [comment]
Moving back to TODO awaiting more partner feedback.

**Comment by randall-Mysten** [comment]
closing as all of this is covered in plans for the site and content overhaul
