### ISSUE TITLE
Type Arguments Error

### ISSUE THREAD

**Issue by bitweed** [MystenLabs/sui#4123]
## Steps to Reproduce Issue

Publish the sui_programmatically example of `defi/pool` And in the CLI, trying to call the `create_pool_` method.

The following command is my command; the object might disappear after the next devnet upgrade. Better to replace with your own objects.

```
sui client call --package 0xe1f9565ef0d24e8194908d8f60acd56a754794e3 --module pool --function create_pool_ --gas-budget 10000 --args 0xba4706ac29a46be29dd4692569fa4aaf1c013e4a 0xc7e9cf1186a2fa3a4c648a3c471f646a1743d78a 0x90708284b86931979d41630462f7851a6b0a874e 1 --type-args 0x2::sui::SUI 0xb98017deb22d367d4de66418fa2a4c16cb8259ba::erc20::ERC20
```

## Expected Result

The pool is successfully created.

## Actual Result

```
RPC call failed: ErrorObject { code: ServerError(-32000), message: "ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: EntryArgumentError(EntryArgumentError { argument_idx: 0, kind: TypeMismatch }), source: Some(\"Expected argument of type T0, but found type 0x2::coin::Coin<0x2::sui::SUI>\") } }", data: None }
```

## System Information

* OS: macOS 12.5
* Compiler: rustc 1.62.1 (e092d0b6b 2022-07-16)

**Comment by bitweed** [comment]
The `ERC20` is a minimal implementation of the custom token, a variation from the official examples.

**Comment by damirka** [comment]
Hey @bitweed, do you mind sharing the code for the ERC20 coin? Is it a `Coin` still?

**Comment by awelc** [comment]
It looks like the list of arguments passed to the entry function does not include the witness argument. I am not sure if it's even possible to pass a witness from CLI at this point (@damirka, @patrickkuo)?

**Comment by damirka** [comment]
Ah! Now I see what's the problem! We can't pass a witness in an entry point. Sorry for that. I should redesign pool to either create a custom LP coin which will target a pool or keep as is just remove entry.
