### ISSUE TITLE
Replace icons on wallet home and tab with new icons

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#4140]

**Comment by gegaowp** [comment]
@mystie711 when you have the new icons, could you add a link here? thanks!

**Comment by mystie711** [comment]
Please grab the icons from here,
https://www.figma.com/file/YJt9Bs4eyhD9PmeZQbFTkf/dev-feedback?node-id=43%3A1726

**NOTE**
The home page button layout has been updated along with the tab bar treatment.
Let's pull in those changes as part of this ticket.

**Comment by bwann52** [comment]
We don't need to add in the stake and earn button until the staking flow is done and working. I think we should not show swap either, but if it's easier it's also ok to show swap but have it grey-ed out.
