### ISSUE TITLE
Sui Cli Bug: URL scheme not supported

### ISSUE THREAD

**Issue by 0xrinegade** [MystenLabs/sui#4164]
## Steps to Reproduce Issue

```
➜  ~ sui client switch --gateway localhost:5001                         
Active gateway switched to localhost:5001
➜  ~ sui client gas --address 0xb72418cc549c097429bbdbabd6ec50b7a88a5899
Networking or low-level protocol error: Invalid Url: URL scheme not supported, expects 'http' or 'https'
➜  ~ sui client switch --gateway https://gateway.devnet.sui.io:443
Networking or low-level protocol error: Invalid Url: URL scheme not supported, expects 'http' or 'https'

```

## Expected Result

CLI shouldn't switch to incorrect URL and should switch back to correct one

## Actual Result

CLI prints error Invalid Url on any command

## System Information

* OS: OS X 12.4
* CLI: sui 0.6.2

**Comment by mwtian** [comment]
cc @patrickkuo

**Comment by 0xrinegade** [comment]
Resolved by deleting local state at `~/.sui`, but bug still there, it shouldn't work like that

**Comment by patrickkuo** [comment]
Ya that’s not right, thanks for reporting @0xrinegade !

we are deprecating the gateway and will be replacing it with the full node, I will make sure this is fixed when we do the switch over.
