### ISSUE TITLE
Disable batch service on fullnodes

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#4167]
The current batch service as it is is not useful on fullnodes. 
We should disable it. It wastes memory resource.
Depends on https://github.com/MystenLabs/sui/issues/4168

**Comment by andll** [comment]
While it is not useful now, in the long run we probably want full nodes to be able to follow each other instead of following validators directly? Should we keep batch service running then?

**Comment by lxfind** [comment]
Yes, but that would be a very different type of service that shouldn't need to create batches (which is what the current batch service do). For instance, it may just be forwarding validator-signed batches to other fullnodes.
