### ISSUE TITLE
Update Wallet Browser docs to reflect redesign

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#4269]
What are the existing URLs containing the issue, if any?

https://docs.sui.io/devnet/explore/wallet-browser

How would you describe the issue? (What needs changing?)

We have a new version of the Sui Wallet Browser Extension coming soon, and we should update the text and screenshots to reflect it.

Where should this information land if new? (Learn, Build, Explore, Contribute.)

Explore section, existing page.

What changes are needed to support this new feature or product? (A simple overview, detailed procedures?)

Line-by-line review and update. Perhaps some new features to document too.

Who is the audience for that information? (App developers, investors, creators, validators, someone else?)

Wallet browser users. :-)

What precisely must they do with it? (Configure a new service? Process some output?)

Use the new version easily upon launch.

**Comment by Clay-Mysten** [comment]
I will take lead and get back to you with questions and drafts. Thanks for the demo today!

**Comment by randall-Mysten** [comment]
this is complete with https://github.com/MystenLabs/sui/pull/4731
