### ISSUE TITLE
Refine and publish end-to-end summary of running local network

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#4305]
What are the existing URLs containing the issue, if any?

https://docs.sui.io/build

How would you describe the issue? (What needs changing?)

@longbowlu has written the brief yet excellent doc below we should consider turning into a real codelab, walking the user through each phase succinctly and clearly:
https://app.golinks.io/local-net-flow

This should not recreate existing materials but rather link out to them for the deeper details. The goal of the doc is to run a local Sui network from end to end.

As such, it will be a shorter version of our very own:
https://docs.sui.io/contribute/cli-client

That exists thanks to @patrickkuo . I intend to work on the two in tandem, as Lu, Patrick and I all agree we can better organize that material, perhaps breaking it down into sub-pages we can then link readily from the codelab.

Where should this information land if new? (Learn, Build, Explore, Contribute.)

Likely Build until we have a Validate or similar section.

What changes are needed to support this new feature or product? (A simple overview, detailed procedures?)

We will need to test and update this doc from beginning to end.

Who is the audience for that information? (App developers, investors, creators, validators, someone else?)

Validators, fullnode runners, the usual. Would love to hear Lu's thoughts here.

What precisely must they do with it? (Configure a new service? Process some output?)

Get a Sui network running in a single sitting, no more than two cups of coffee, and a bagel.

**Comment by Clay-Mysten** [comment]
I'm noting we've already made progress on related work since meeting on this topic yesterday, namely refining our left navigation and carving out a Reference section under Build to house the API and SuiJSON docsets:
https://github.com/MystenLabs/sui/pull/4274
https://github.com/MystenLabs/sui/pull/4290
https://github.com/MystenLabs/sui/pull/4303

In the final PR, I restored CLI Client to the Contribute menu for now while we sort out the placement of it and the summary highlighted here. Much more to come, Thanks, all.

**Comment by Clay-Mysten** [comment]
@lxfind to see if Xun is copied on subsequent messages.

**Comment by Clay-Mysten** [comment]
@longbowlu and @patrickkuo note all is right in the world again with CLI Client being placed below Devnet as an option under Build (and not Contribute):
https://devportal-qa.web.app/build

Thanks!

**Comment by randall-Mysten** [comment]
Closing this as it is covered in other issues.
