### ISSUE TITLE
Improve RPC Error Messaging

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#4314]
What are the existing URLs containing the issue, if any?

N/A - at the command line

How would you describe the issue? (What needs changing?)

@sblackshear reports the following error:

```
Error: Transaction failed with the following error. Error executing transaction: Error: RPC Error: unknown variant bjPrIKdGsoMd/cgVR2Jrcf655B8kTM8S4B3f0RvcutpqjnLgIGSnQydmzjqC3gxIEbGxGVj1hjx7d0CfkCzfBA==, expected ED25519 or Secp256k1 at line 1 column 90}
```

He rightfully points out this is cryptic and not actionable. Ideally, we would inform the user to consider resetting their configuration, namely by removing the `.sui` config directory. We do this in the Devnet docs now:
https://docs.sui.io/build/devnet#set-up-sui-cli-client-connect-to-gateway

Where should this information land if new? (Learn, Build, Explore, Contribute.)

In the CLI output.

What changes are needed to support this new feature or product? (A simple overview, detailed procedures?)

Improved error messaging.

Who is the audience for that information? (App developers, investors, creators, validators, someone else?)

Sui devs.

What precisely must they do with it? (Configure a new service? Process some output?)

Fix their environment for development and testing.

I'm asking @bhenhsi to route this accordingly per Sam. Brian, please help. Sam, please correct me if I got this or the priority wrong.  Thanks!

**Comment by Clay-Mysten** [comment]
I am happy to help form the language here. I just need to understand the error conditions. Thanks!

**Comment by randall-Mysten** [comment]
Closing this issue - we can work with engineering to define and implement a process for error string review as part of the dev cycle.
