### ISSUE TITLE
Put fees for token

### ISSUE THREAD

**Issue by 0xZangetsudev** [MystenLabs/sui#4336]
Hello,

I don’t think it’s possible on Sui to add a fees feature for token transfer and token swap. I’ve been in crypto for 2 years in full time and it’s really important for some protocol in DeFi. Like you can put 1-2% for treasury and it will built up so with it you can compound it in other protocols and then reinvest the stacking rewards into your protocol and people like that.

Could you add the possibilities for the function/struct transfer in sui::coin?

**Comment by sblackshear** [comment]
This is possible to do. See for example:
- https://github.com/MystenLabs/sui/blob/main/sui_programmability/examples/defi/sources/pool.move#L64 (collects a fee each time a user swaps tokens)
- https://github.com/MystenLabs/sui/blob/main/sui_programmability/examples/defi/sources/flash_lender.move#L100 (charges a fee each time a user takes out a loan)
