### ISSUE TITLE
reconfig_end_to_end_test being flaky

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#4337]
The test sometimes take forever.
Looking at the log from a local reproduce, it seems that after a few checkpoints, at some point the checkpoint fragments sent to Narwhal is never heard back.
Log: https://gist.github.com/lxfind/c5408c800682a470b3609bba782008dc

@huitseeker @asonnino @andll @mystenmark @gdanezis

**Comment by dmitri-perelman** [comment]
Afaik @andll volunteered to look at it.
