### ISSUE TITLE
Client / Keytool signature scheme mismatch

### ISSUE THREAD

**Issue by huitseeker** [MystenLabs/sui#4344]
## Steps to Reproduce Issue

```
huitseeker@dapple.localdomain➜~/tmp/sui(main✗)» target/debug/sui client new-address random                                                                                                                                          [13:37:51]
Config file ["/Users/huitseeker/.sui/sui_config/client.yaml"] doesn't exist, do you want to connect to a Sui RPC server [yN]?y
Sui RPC server Url (Default to Sui DevNet if not specified) :
Generating keypair ...

Do you want to generate a secp256k1 keypair instead? [y/N] No will select Ed25519 by default.

Generated new keypair for address with flag 0 [0x19de019c19fc800a6aeba4eb4133f6db91ca7c2c]
Secret Recovery Phrase : [demise online remind celery salon powder kitchen knife argue fabric duty east]
error generating key Unrecognized key scheme
huitseeker@dapple.localdomain➜~/tmp/sui(main✗)» target/debug/sui client new-address secp256k1                                                                                                                                       [13:38:03]
Created new keypair for address with flag 1: [0xd498f8bee1b3b5eb181d655b2b5f0c2d9ec38077]
Secret Recovery Phrase : [mechanic thrive deputy amount reform entire pencil globe joy narrow topic library]
huitseeker@dapple.localdomain➜~/tmp/sui(main✗)» git rev-parse HEAD                                                                                                                                                                  [13:38:28]
5ff71528a37f642a4496bef86167deb5fe2d53bd
```

For context, this used to pass at the introduction of the keytool commands:
https://github.com/MystenLabs/sui/pull/4084

This may be a mismatch between the current set of flags to indicate Ed25519 vs Secp256k1 and the old one. Internally, the client may still be signaling `None` instead of `Some(ed25519)` or some such.

/cc @joyqvq @kchalkias @damirka 

Related: https://github.com/MystenLabs/sui/pull/4169 https://github.com/MystenLabs/sui/pull/3689

**Comment by joyqvq** [comment]
`random` is considered as an invalid option (the screenshot is outdated), it needs to either 1) nothing 2) "ed25519" 3) "secp256k1". 1 and 2 will be interpret as ed25519

**Comment by kchalkias** [comment]
And note that _(1) nothing_ will be deprecated in an upcoming PR, we'll always need the scheme flag, because the default might one day change.

**Comment by huitseeker** [comment]
This is probably more of a doc issue by now, then.

**Comment by kchalkias** [comment]
> This is probably more of a doc issue by now, then.

if there is any doc we didn't or should change plz let us know

**Comment by joyqvq** [comment]
this is resolved by explicitly adding option for key_scheme
