### ISSUE TITLE
Events should not include checkpoint sequence number

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#4345]
Currently when we process events after a transaction is executed, we emit events and use the latest checkpoint sequence number as the checkpoint for the event. This is incorrect. There is no guarantee that the transaction is included by the current checkpoint.

**Comment by lxfind** [comment]
@velvia @longbowlu fyi

**Comment by velvia** [comment]
@lxfind I thought we were planning to not add events until a full node gets certified effects or its equivalent.  Thus, we would no longer have this problem of a transaction not being included, right?

**Comment by lxfind** [comment]
Yes, but there are a few problems. Currently Fullnodes uses state.latest_checkpoint_num to be the checkpoint sequence number of the events. There is no guarantee that the fullnode can get consistent checkpoint number at that specific time point (imagine you are processing events at a checkpoint boundary, and you could be either looking at the current checkpoint, or the next). Plus latest_checkpoint_num is not even set on Fullnodes.
