### ISSUE TITLE
Fix "attemps" and other common misspellings in our code base

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#4353]
What are the existing URLs containing the issue, if any?
https://github.com/search?q=org%3AMystenLabs+attemps&type=code

How would you describe the issue? (What needs changing?)
@Romainua reports:

```
It is the metrics of nodes, URL individual for each, but comments are the same for all. 
http://ip:9184/metrics
I think attemps must be attempts, a minor problem
# HELP gossip_total_attempts_cert_downloads Total number of certs/effects download attemps through gossip/node sync process
Thanks
```

@brad-mysten points to the query above for all such refs.

Where should this information land if new? (Learn, Build, Explore, Contribute.)

In the files above.

What changes are needed to support this new feature or product? (A simple overview, detailed procedures?)

Fix some typos.

Who is the audience for that information? (App developers, investors, creators, validators, someone else?)

All.

What precisely must they do with it? (Configure a new service? Process some output?)

Better understand our code.

**Comment by randall-Mysten** [comment]
Corrected attemps, deferring others for future updates
