### ISSUE TITLE
Docker image for ARM Linux

### ISSUE THREAD

**Issue by imcvampire** [MystenLabs/sui#4358]
It would be nice if there are docker images for ARM Linux

**Comment by stefan-mysten** [comment]
@tharbert @ebmifa is this something that'd we want to support?

**Comment by Sceat** [comment]
@stefan-mysten could we also have the linux Arm release along with X86_ ones ?

![image](https://github.com/user-attachments/assets/84ac1a9b-44b2-4e41-81b2-c80c385d31b1)

**Comment by stefan-mysten** [comment]
@ebmifa this might be something to consider, how difficult would it be to add this?

**Comment by ebmifa** [comment]
I think GH has `ubuntu-22.04-arm64` runner avaialbe to use. We can try and use it for the ubuntu arm64 builds

**Comment by ebmifa** [comment]
https://github.com/MystenLabs/sui/pull/19362
