### ISSUE TITLE
Shared object transactions may never finish the full execution flow

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#4387]
Consider the following scenario: a shared object transaction certificate is being executed, and is able to finish execution and update new object state into db. However before committing effects, the connection is dropped. Latter we would attempt to re-execute this transaction, but then in transaction_input_checker, for shared objects, we only load the latest version, and in this case we would be loading the updated object instead of the object that's supposed to be used in the transaction. Then we check shared object locks, and here we would fail because it will detect that the object version doesn't match with the locked version. The consequence is that we will never be able to finish executing this transaction and never have the effects stored.

**Comment by velvia** [comment]
If we truly have a WAL, then the input objects should be written to the WAL as well for idempotent re-execution.   Basically the WAL should contain everything that is eventually written.
