### ISSUE TITLE
Help explain differences between Sui and other blockchains

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#4435]
https://docs.sui.io/devnet/learn/sui-move-diffs

**Comment by Clay-Mysten** [comment]
Hi @damirka , I have finished my initial edits to the Doc in Suggest mode so you may pick and choose the changes you like. Please let me know how to help. I would love to get this online for persistent reference, perhaps in the file linked above.

**Comment by bhenhsi** [comment]
@AkashaCoin to look into this.
