### ISSUE TITLE
Explorer: Support read/write operations on modules

### ISSUE THREAD

**Issue by Jordan-Mysten** [MystenLabs/sui#4448]
This is blocked by updated designs for the this UI (cc @mystie711).

Add the ability to run transactions for modules. This should use the normalized module to determine which public functions exist.

Wallet connection should use the wallet adapter.

**Comment by mystie711** [comment]
Design proposal,
https://www.figma.com/file/kSD0qXCIDZA4KQVNepA5hR/02-Explorer?node-id=211%3A48503
