### ISSUE TITLE
[Sui Code Bug] Wallet adapter & ui cannot be imported properly following the docs.

### ISSUE THREAD

**Issue by bruceeewong** [MystenLabs/sui#4482]
## Steps to Reproduce Issue

I am trying to integrate SUI wallet adapter into my demo vite Reac-ts project (created straightly from vite CLI). 

Following the instruction of the **Main Branch** [wallet adater docs](https://github.com/MystenLabs/sui/tree/main/wallet-adapter) and installed all the three deps:

```
npm i @mysten/wallet-adapter-all-wallets @mysten/wallet-adapter-react @mysten/wallet-adapter-react-ui
```

npm deps show like these:

```
"@mysten/wallet-adapter-all-wallets": "^0.0.0-experimental-20220822221301",
"@mysten/wallet-adapter-react": "^0.0.0-experimental-20220825172556",
"@mysten/wallet-adapter-react-ui": "^0.0.0-experimental-20220825172556",
```

I followed what the docs saied to import the packages, several errors poped up:

```
import { SuiWalletAdapter } from "@mysten/wallet-adapter-all-wallets";
// error: TS2305: Module '"@mysten/wallet-adapter-all-wallets"' has no exported member 'SuiWalletAdapter'.
```

```
import { WalletWrapper } from '@mysten/wallet-adapter-react-ui';
TS2307: Cannot find module '@mysten/wallet-adapter-react-ui' or its corresponding type declarations.
```

## Expected Result

Expect all the imports work and be available to use in my react project.

## Actual Result

Got serveral import issues from packages:

- @mysten/wallet-adapter-all-wallets
- @mysten/wallet-adapter-react-ui

## System Information

* OS: MacOS 12.3.1
* Compiler: "vite": "^3.1.0"

**Comment by flappys** [comment]
Go to package.json, add  "@testing-library/dom": "^7.21.4" and "@babel/core": "^7.0.0".
Remove all modules having workspace
Go to tsconfig.json add packages include. Also remove "integrations" from all paths

use pnpm install

**Comment by bruceeewong** [comment]
> Go to package.json, add "@testing-library/dom": "^7.21.4" and "@babel/core": "^7.0.0". Remove all modules having workspace Go to tsconfig.json add packages include. Also remove "integrations" from all paths
> 
> use pnpm install

Thanks for the reply. I am not playing with the sui repo actually. I am using the npm package as external users. Maybe it should be the publish problem of the offical sui npm packages.

**Comment by bruceeewong** [comment]
> Go to package.json, add "@testing-library/dom": "^7.21.4" and "@babel/core": "^7.0.0". Remove all modules having workspace Go to tsconfig.json add packages include. Also remove "integrations" from all paths
> 
> use pnpm install

Your instruction works for developing the official repo, thanks!

**Comment by Jordan-Mysten** [comment]
@bruceeewong I'd try installing the versions `@experimental` to get the latest experimental versions that should have this issue resolved.

**Comment by Jordan-Mysten** [comment]
@bruceeewong Just following up before I close this, does using the `@experimental` versions resolve the issue?
