### ISSUE TITLE
[explorer] time not display correctly

### ISSUE THREAD

**Issue by Nelrann** [MystenLabs/sui#4520]
## Steps to Reproduce Issue

install a fullnode with docker

## Expected Result

![image](https://user-images.githubusercontent.com/503587/189062243-30801a57-7a26-4dc2-9891-4c6f15700069.png)

## Actual Result

![image](https://user-images.githubusercontent.com/503587/189062087-ef42fe56-ca64-4704-9a2c-e0861e160340.png)
![image](https://user-images.githubusercontent.com/503587/189092765-19181203-9630-4195-a3bc-657c2b36f316.png)

time is not displayed correctly, the problem seems to be resolved if I restart the node with
"docker compose restart"

you can test my fullnode with https://sui-rpc.nelrann.org in explorer

## System Information

* OS: Ubuntu 20.04

**Comment by Jefferson111** [comment]
Sui is not supported on Ubuntu 20.04 as [stated in documentation](https://docs.sui.io/devnet/build/install#supported-oses). Is the problem replicable in supported OS-es?

**Comment by Jordan-Mysten** [comment]
A lot of the code around timestamps for the explorer has changed, this should work now
