### ISSUE TITLE
"Sui framework version mismatch detected" when only using StdLib but not Sui Framework

### ISSUE THREAD

**Issue by leofisG** [MystenLabs/sui#4589]
## Steps to Reproduce Issue
Create a Move package that doesn't depend on Sui framework but only on Move Standard Library. You will have the following `Move.toml` snippet.
```
[dependencies]
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/deps/move-stdlib/", rev = "df05544fb0cbd6d6db016e71e5facb5e7cc27988" } # devnet commit hash
```
Install the Sui CLI with the corresponding commit hash `df05544fb0cbd6d6db016e71e5facb5e7cc27988`. 

This will cause the following error here: 
```
% sui move build --path package_path
Failed to verify the Move module, reason: "Sui framework version mismatch detected.Make sure that the sui command line tool and the Sui framework codeused as a dependency correspond to the same git commit".
```

I think it's because [this](https://github.com/MystenLabs/sui/blob/c7cb45e662cce1533ca60a69491e1c493784f043/crates/sui-framework/src/lib.rs#L175) line only picks up Sui Framework.

To temporarily fix the above issue, we just need to add Sui Framework into the `Move.toml` file:
```
[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "df05544fb0cbd6d6db016e71e5facb5e7cc27988" }
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/deps/move-stdlib/", rev = "df05544fb0cbd6d6db016e71e5facb5e7cc27988" }
```

## Expected Result

Shouldn't report an error when I don't need the Sui framework.

## Actual Result

Error:
```
% sui move build --path package_path
Failed to verify the Move module, reason: "Sui framework version mismatch detected.Make sure that the sui command line tool and the Sui framework codeused as a dependency correspond to the same git commit".
```

## System Information

* OS: MacOS
* CLI: Sui commit hash `df05544fb0cbd6d6db016e71e5facb5e7cc27988`

**Comment by awelc** [comment]
@leofisG, thank you for the report! And your assessment is correct I believe - I have put together a PR (https://github.com/MystenLabs/sui/pull/4613) that should fix it.
