### ISSUE TITLE
UI updates to Address page : NFTs section

### ISSUE THREAD

**Issue by mystie711** [MystenLabs/sui#4594]
A few updates that will improve the layout and is captured in Figma here,
https://www.figma.com/file/kSD0qXCIDZA4KQVNepA5hR/02-Explorer?node-id=204%3A48379 

- padding between columns -> 40px
- empty placeholder asset when we don’t have an image -> use the assets with the image icon in Figma
- padding between image and text should be 15 (looks a lot more in the screenshot attached to task)
- space between items on mobile - let’s update it to 10px
- ensure correct font style (size/color) is in use for NFT metadata

**Comment by Andrew47** [comment]
@mystie711 --> The following PR targets 'empty placeholder asset when we don't have an image': https://github.com/MystenLabs/sui/pull/4656
