### ISSUE TITLE
Language: Support for Table data structure

### ISSUE THREAD

**Issue by JohnChangUK** [MystenLabs/sui#4646]
Sui Move does not have a concept of a mapping data structure, but currently has a `vec_map` module with a `VecMap` struct. This internally uses a `vector` to keep track of entries, however the problem is that key value look ups are `O(n)` as the `vector` must be iterated over to find the matching key. 
- https://github.com/MystenLabs/sui/blob/760ae2d3c7fe92c0f187497046b36b7eef281b58/crates/sui-framework/sources/vec_map.move

Aptos Move have their own `Table` data structure which has inbuilt native functions for mapping operations `(remove, insert)`. As they are native functions, they are inbuilt into the VM.
- https://github.com/aptos-labs/move/blob/main/language/evm/stdlib/sources/Table.move

As both Sui and Aptos Move compile down to Move byte code, it would be ideal to integrate `Table` into Sui Move, or alternatively create a separate module to accommodate constant look up mappings.

**Comment by sblackshear** [comment]
`Table` depends on some implementation details of the storage model of core Move and cannot be used directly in Sui. However, we are working on dynamic child object access: https://github.com/MystenLabs/sui/issues/4203, a powerful new primitive that can be used to implement tables, heterogenous maps, trees, linked lists, etc. So there will be a table-like API in our stdlib quite soon!
