### ISSUE TITLE
rpc: add convenience endpoints for Coins

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#4652]
Right now to get user balance, it requires two requests:
1. `getObjectsOwnedByAddress` to get object ids; 
2. A batch request `getObjectBatch` to fetch the content for all objectids

We should add `get_coins_by_type` and `get_balance_by_type`

**Comment by patrickkuo** [comment]
We should create a new sets of methods to streamline coin/account balance queries.

the new RPC module should include the following methods.

`sui_getCoins` -- return all coin objects of for a owner address, optionally filtered by coin type.
`sui_getBalance` -- return balance of each coin type owned by an address, optionally filtered by coin type.
`sui_getTotalSupply` -- Total supply of specified coin type


`sui_getCoinMetadata` should be included in the new API module
