### ISSUE TITLE
Wrong comment

### ISSUE THREAD

**Issue by Hikmo** [MystenLabs/sui#4695]
https://github.com/MystenLabs/sui/blob/2aebfd609bc215dd66e74b6505d69afa0b376af6/sui_programmability/examples/defi/sources/flash_lender.move#L174

Comment should be changed to something like return the id of the given Flash Lender object

**Comment by stefan-mysten** [comment]
Fixed in the new `examples` folder. https://github.com/MystenLabs/sui/blob/main/examples/move/flash_lender/sources/example.move#L138C1-L138C48
