### ISSUE TITLE
[Wallet adapter] cannot find module @mui\icons-material\Settings

### ISSUE THREAD

**Issue by BladeRunner713** [MystenLabs/sui#4709]
## Expected Result

No error

## Actual Result

Cannot find module 'C:\xxxxxx\node_modules\@mui\icons-material\Settings' imported from C:\xxxxxx\node_modules\@mysten\wallet-adapter-react-ui\dist\index.mjs

## System Information

"@mysten/sui.js": "^0.1.0",
"@mysten/wallet-adapter-all-wallets": "^0.0.0-experimental-20220919022657",
"@mysten/wallet-adapter-react": "^0.0.0-experimental-20220919022657",
"@mysten/wallet-adapter-react-ui": "^0.0.0-experimental-20220919022657",

**Comment by Jordan-Mysten** [comment]
The `wallet-adapter-react-ui` package has been replaced with our new Wallet Kit package.https://github.com/MystenLabs/sui/tree/main/sdk/wallet-adapter/packages/wallet-kit
