### ISSUE TITLE
[feature-request] Get Object by UID

### ISSUE THREAD

**Issue by punwai** [MystenLabs/sui#4722]
Currently, when an object is stored inside another object, there is no way to query the object's ID from a full-node. This makes the tracking of an asset quite difficult. For example, if you have an NFT, and you wrap it around another Shared Object so that you can use it in an NFT sale, that NFT now becomes unqueriable by its ID. 

A way I've been using to avoid this problem is to listen for events emitted during the wrapping of NFTs and create an NFT ID <-> Wrapper ID mapping within my internal DB -- the next time someone queries for an NFT's ID to display or view, I fetch the ID of its wrapped object. However, in my opinion, this puts a lot of the work on the developers and greatly increases the complexity of the frontends that are built on Sui.

**Comment by 666lcz** [comment]
duplicates https://github.com/MystenLabs/sui/issues/5816
