### ISSUE TITLE
can't connect devnet fullnode's websocket port

### ISSUE THREAD

**Issue by longbowlu** [MystenLabs/sui#4727]
`wscat -c ws://fullnode.devnet.sui.io:9001` returns connection error

I could repro this issue locally - it looks like the [sync-to-checkpoint process](https://github.com/MystenLabs/sui/blob/main/crates/sui-node/src/lib.rs#L199) never returns hence the rpc server does not have a chance to restart. Then I disabled checkpoint, it worked.

however this does not explain why the jsonrpc server is up and running for devnet fullnode, so it could be an entirely different issue. Also if the fullnode starts along with the validators, the checkpoint process should not take long at all.

**Comment by patrickkuo** [comment]
We currently didn't expose the fullnode ws port, our PE team is working on it.

when it's done, you should be able to access it via ws://pubsub.devnet.sui.io:80 or wss://pubsub.devnet.sui.io:443

**Comment by tomfurrier** [comment]
Thank you for the clarification! Looking forward to using the ws api.
