### ISSUE TITLE
Update the existing package

### ISSUE THREAD

**Issue by BladeRunner713** [MystenLabs/sui#4730]
I can't find any document about how I can update the existing package. Is it even possible?

**Comment by randall-Mysten** [comment]
Hi @BladeRunner713 Could you clarify what you mean by update the package? To get the latest version of Sui, clone the Devnet or Main branch.

**Comment by BladeRunner713** [comment]
> Hi @BladeRunner713 Could you clarify what you mean by update the package? To get the latest version of Sui, clone the Devnet or Main branch.

Hi Randall, I want to know if it's possible the update the package or module I published.

**Comment by randall-Mysten** [comment]
Where is it published? I would think you could update and publish it again. Sorry that I am not understanding your specific question.

**Comment by BladeRunner713** [comment]
> Where is it published? I would think you could update and publish it again. Sorry that I am not understanding your specific question.

Suppose I publish a liquidity pool on Sui ledger. Then I realize I have some bugs inside my code. I could publish a new module or package, but how do I deal with these objects on my old module or package?

**Comment by randall-Mysten** [comment]
Ah, OK. Let me get more information about this. Thanks for the additional detail

**Comment by randall-Mysten** [comment]
Looks like they are still working on some of this. There is some info that may be helpful in https://docs.sui.io/devnet/build/move and the additional topics in the same node.
