### ISSUE TITLE
Tx may not be included by batch service in some cases

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#4754]
Here we obtain a ticket for a certificate that's about to be committed: https://github.com/MystenLabs/sui/blob/a677c268d4e5ab43d8fa484ac43e765b614b24a8/crates/sui-core/src/authority.rs#L1839
When the ticket goes out of scope, we have a custom impl of Drop to increment the low watermark: https://github.com/MystenLabs/sui/blob/e59ec64a45449a6d01cdb7226fb69e6d821bc6d3/crates/sui-core/src/authority/authority_notifier.rs#L233
However step (2) above can happen not because the tx was fully committed successfully, but if the thread was killed in between lock service update and effects/executed_sequence update.
Then we are in the situation where the low watermark is past the certificate's sequence number, but the certificate's sequence number is not in executed_sequence nor in effects.
When the batch service comes around and try to make a batch, it will not include this certificate because it's not in executed_sequence yet. And the batch service will never include it because it will stop at low watermark: https://github.com/MystenLabs/sui/blob/e59ec64a45449a6d01cdb7226fb69e6d821bc6d3/crates/sui-core/src/authority/authority_notifier.rs#L133

**Comment by velvia** [comment]
I'll comment in other threads, but it seems to me that there are two problems here:
1. The `executed_sequence` should really be atomic with lock acquisition and writing into the WAL, ie it should be moved up earlier in the sequence of writing.
2. The low watermark should not be advanced until all the writes are done, esp of certificates.

**Comment by lxfind** [comment]
See https://mysten-labs.slack.com/archives/C03GKUEA5PF/p1666165374018769
