### ISSUE TITLE
Replace all hash deps with fastcrypto

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/sui#4760]
Now that fastcrypto implemented all of the hash wrappers we need, we should remove any cargo deps to all of the hash-crates and always use fastcrypto's api, see: @jonas-lj 's PR https://github.com/MystenLabs/fastcrypto/pull/63

**Comment by kchalkias** [comment]
@joy re base64ct, not a bad idea.

**Comment by jonas-lj** [comment]
#5147 removes most of the dependencies but not all. The remains requires a bit more work since it's where the hash functions from dependencies are used as generic arguments. However, it has been solved for hkdf, so it should be possible to do in the remaining cases also.

**Comment by joyqvq** [comment]
https://github.com/MystenLabs/sui/pull/5958
