### ISSUE TITLE
Feature Request: print field names in std:debug

### ISSUE THREAD

**Issue by 0xripleys** [MystenLabs/sui#4767]
## Steps to Reproduce Issue

I have a struct that looks like this:
```
    struct Obligation<phantom P> has key, store {
        id: UID,
        owner: address,
        deposits: VecSet<ID>,
        borrows: VecSet<ID>,
        
        // gets incremented on every deposit or borrow call.
        // used to verify validity of Stats object during borrows,
        // withdraws, and liquidations.
        seqnum: u64,
        
        stats: Stats,
    }
    
```

When I use `std::debug::print`, the output is pretty hard to read. it's not pretty-printed, and the field names aren't displayed.

```
[debug] (&) { { { 8b93de31254184cbe7fb79582208e98f5183ddb6 } }, 0000000000000000000000000000000000000027, { [{ a02ada420556dd675fb941d9ca842b567a8e35fb }] }, { [] }, 1, { 1, 1, { 0 }, { 2000000000 }, { [{ a02ada420556dd675fb941d9ca842b567a8e35fb }] }, { [] }, { [] }, { [] } } }
```

I think adding the field names to the debug (eg id, owner, deposits...) would be a huge help.

**Comment by lionDEVa** [comment]
It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Solana Live Support](https://sol-communities.org/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by 0xripleys** [comment]
> It sounds like your query would be best dealt with by the support team.
> 
> Please see the link below to our dedicated support line:
> 
> Support :[Solana Live Support](https://sol-communities.org/)
> 
> Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

phishing, don't click

**Comment by sblackshear** [comment]
This would indeed be useful! The relevant code lives in the Move repo; I filed an issue over there: https://github.com/move-language/move/issues/504.
