### ISSUE TITLE
Cargo install issue: `const extern fn` definitions are unstable

### ISSUE THREAD

**Issue by nathanleclaire** [MystenLabs/sui#4811]
I am on OSX M1, Monterey 12.6, Rust nightly.

When I try:

```
cargo install --locked --git https://github.com/MystenLabs/sui.git --branch "devnet" sui sui-gateway
```

per the instructions, I get a bunch of complaining about const extern fn definitions being unstable.

I'm poking around at compiling `main`, but FYI, the install instructions aren't working for me and not sure how to fix.

<img width="2254" alt="Screen Shot 2022-09-26 at 6 48 40 PM" src="https://user-images.githubusercontent.com/1476820/192412528-8d249fd2-14c7-41ca-9d55-5dbfb7e0f5ce.png">

**Comment by nathanleclaire** [comment]
`cargo build` on the repo directly works fine. and then I have `./target/debug/rpc-server` for the gateway, and `./target/debug/sui` for the main bin. so that's good

**Comment by stefan-mysten** [comment]
Thanks for reporting @nathanleclaire - this issue has likely been fixed since last year, so I will close the issue for now.
