### ISSUE TITLE
docs(transactions): Inconsistency in SUI token typing

### ISSUE THREAD

**Issue by Cardosaum** [MystenLabs/sui#4819]
[Link to original documentation](https://docs.sui.io/devnet/build/transactions)

In the Transactions section, there is (what I think it is) an inconsistency when using `sui::coin::Coin<sui::sui::SUI>` and `sui::coin::Coin<SUI>`. I'm being super picky here, but wouldn't be better to just adopt one or the other variation for the documentation? 

Both instances appear when talking about the SUI native token, but maybe standardizing one variation would be more adequate?

**Comment by randall-Mysten** [comment]
Closing stale issues, please reopen if the issue still exists
