### ISSUE TITLE
docs(how-sui-works): Wrong linking tree?

### ISSUE THREAD

**Issue by Cardosaum** [MystenLabs/sui#4820]
One thing that I noticed while reading Sui's documentation is that in the [How Sui Works](https://docs.sui.io/devnet/learn/how-sui-works) section, both sub-topics [Objects](https://docs.sui.io/devnet/build/objects) and [Transactions](https://docs.sui.io/devnet/build/transactions) point to apparently nowhere under the Build section (the links work and users can read the desired information).

You can see the difference when clicking in either of these links and then in [Single Writer Apps](https://docs.sui.io/devnet/learn/single-writer-apps). Notice that for the later link we can see the page tree opening correctly and pointing to a subsection of `How Sui Works`, but for the former two links it's not the observed behavior.

**Comment by randall-Mysten** [comment]
Thanks for pointing this out. I also noticed it. I think these 2 were overlooked when someone reorganized the topics. We'll get it corrected. As an FYI, if you choose the [Doc issue template](https://github.com/MystenLabs/sui/issues/new?assignees=randall-Mysten&labels=doc-issue&template=doc-bug.md&title=Sui+doc+content+issue+or+request) it automatically adds the label and assigns it to me. Thanks for your feedback!

**Comment by randall-Mysten** [comment]
I pushed a PR that moves the objects and transactions topics to the Learn folder in the repo. This is live on Latest build version of docs
