### ISSUE TITLE
Pay Transaction should be implemented using Move transaction instead of native transaction type

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#4861]
Currently the Pay Transaction is implemented as native transaction type, where coin objects are manipulated directly in Rust. This is unnecessary complexity and error prone. This should be doable in Move, where we pass a vector of coin objects into a Move function. The remaining coin objects at the end are transferred back to the sender.

**Comment by GrapeBaBa** [comment]
can I take this one?
