### ISSUE TITLE
Failed to install sui, sui-gateway

### ISSUE THREAD

**Issue by rocalex** [MystenLabs/sui#4892]
I tried to install sui cli using
```
cargo install --locked --git https://github.com/MystenLabs/sui.git --branch "devnet" sui sui-gateway
```
but got errors.

```
    Updating git repository `https://github.com/MystenLabs/sui.git`
error: could not find `sui` in https://github.com/MystenLabs/sui.git?branch=devnet with version `*`
    Updating git repository `https://github.com/MystenLabs/sui.git`
error: could not find `sui-gateway` in https://github.com/MystenLabs/sui.git?branch=devnet with version `*`
     Summary Failed to install sui, sui-gateway (see error(s) above).
error: some crates failed to install
```

**Comment by randall-Mysten** [comment]
@rocalex Thanks for submitting this issue. I am looking into it.

**Comment by xs818** [comment]
I tried to run the sui-setup.sh script with the same problem.

**Comment by randall-Mysten** [comment]
@xs818 Thanks for the additional info. I pushed a PR to remove the script until I can sort out the issues.

**Comment by rocalex** [comment]
```
cargo --version
cargo 1.63.0 (fd9c4297c 2022-07-01)
```

**Comment by randall-Mysten** [comment]
not necessarily the issue, but we just used the same command successfully on Rust 1.64. Could you provide any additional details on the specific steps you took prior to running the command?

**Comment by slendermaan** [comment]
this is may a problem about your  cargo version, you can run 
`rustup update `
to make your cargo to the newest version!

**Comment by randall-Mysten** [comment]
we've seen this issue from several people and are looking at additional potential causes
