### ISSUE TITLE
User-facing modifications to support passing vectors of objects to Move entry functions

### ISSUE THREAD

**Issue by awelc** [MystenLabs/sui#4921]
Core Move support for passing vectors of objects to Move entry functions has been recently added in https://github.com/MystenLabs/sui/pull/4526, along with support in Sui JSON (and thus `sui client` CLI).

This task is supposed to track modifications that are needed to enable end-users to take advantage of this functionality, particularly in the SDKs but possibly also in other places I am not aware of. I am assigning folks to this task somewhat arbitrarily, based on some conversations (I believe) we had in the past. Please feel free to divide this into sub-tasks and/or re-assign (perhaps @srinath-mysten can help with this).

**Comment by gegaowp** [comment]
@awelc is there any TODOs here, otherwise shall we close this one?

**Comment by awelc** [comment]
> @awelc is there any TODOs here, otherwise shall we close this one?

I don't know exactly what needs to be done on the user side (SDKs? anything else), that is why I assigned multiple (hopefully relevant) people to this task so that they can provide feedback (@patrickkuo, @gegaowp, @joyqvq, @srinath-mysten?). Please do not close until this is clarified.

**Comment by 666lcz** [comment]
Verified that CLI already supports passing a vector of objects:

```
./sui client call --package 0x70af3dc55b2ee885c63980f7d738540e4539416d --module entry_point_vector --function two_obj_vec_destroy --args "[\"0xdf5aec3f3a2217c98afcda4987d616e74c97f94b\",\"0x8ce4493f033397d6a6f19fdd6ac7d03e8e14b16a\"]" --gas-budget 10000 --gas 0x04f1a86732cb960701eaae4b8d2b76e99bd5f631
```
