### ISSUE TITLE
User-facing modifications to support passing strings to Move entry functions

### ISSUE THREAD

**Issue by awelc** [MystenLabs/sui#4922]
Core Move support for passing strings to Move entry functions has been recently added in https://github.com/MystenLabs/sui/pull/4627, along with support in Sui JSON (and thus `sui client` CLI).

This task is supposed to track modifications that are needed to enable end-users to take advantage of this functionality, particularly in the SDKs but possibly also in other places I am not aware of. I am assigning folks to this task somewhat arbitrarily, based on some conversations (I believe) we had in the past. Please feel free to divide this into sub-tasks and/or re-assign (perhaps @srinath-mysten can help with this).

**Comment by gegaowp** [comment]
@awelc is there any TODOs here, otherwise shall we close this one?

**Comment by awelc** [comment]
> @awelc is there any TODOs here, otherwise shall we close this one?

I don't know exactly what needs to be done on the user side (SDKs? anything else), that is why I assigned multiple (hopefully relevant) people to this task so that they can provide feedback (@patrickkuo, @gegaowp, @joyqvq, @srinath-mysten?). Please do not close until this is clarified.
