### ISSUE TITLE
[doc] RPC quick start out of sync with API description

### ISSUE THREAD

**Issue by awelc** [MystenLabs/sui#4946]
It seems like the "RPC Server & JSON-RPC API Quick Start" section of our docs is out of sync with "Sui JSON-RPC (V 0.6.1)" part.

In particular, see example of `sui_executTransaction` [here](https://docs.sui.io/devnet/build/json-rpc#3-execute-the-transaction-using-the-transaction-data-signature-and-public-key) and [here](https://docs.sui.io/sui-jsonrpc#sui_executeTransaction).

**Comment by randall-Mysten** [comment]
Thanks for reporting this issue, adding it to the queue.

**Comment by randall-Mysten** [comment]
Closing stale issues, please reopen if the issue still exists
