### ISSUE TITLE
[crypto] Easy config + epoch switch between ed25519 and BLS consensus_sig_scheme

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/sui#4959]
Sui recently switched to BLS for validator signatures. There is however a sweet point to about 40-50 validators where, computationally, BLS aggregated verification starts having an advantage against batched ed25519. Similarly, BLS signing is more expensive.

We should have an easy programmatic/config way to provide agility and quick switch at protocol level re validators signature scheme. Obviously either all validators will use ed25519 (i.e., when we expect 2f+1 to be small enough) or BLS12-381.

Multiple PRs should be required for this to work, ie key generation (and genesis) for validators should take that flag into account when generating consensus keys.

**Comment by jonas-lj** [comment]
It is now possible to switch between BLS and Ed25519 programatically by following these steps:
1. Update the default crypto types in Sui (in sui-types/src/crypto.rs),
2. In the same file, make sure all schemes implements `ToObligationSignature`,
3. Update the default crypto types in Narwhal (narwhal/crypto/src/lib),
4. Update the signature verification function used by validators in Move to the correct scheme (in sui-framework/sources/governance/validator.move).
