### ISSUE TITLE
Execution of sequenced shared object certs may race, leading to unnecessary errors

### ISSUE THREAD

**Issue by mystenmark** [MystenLabs/sui#4990]
Here's the situation:

- Suppose consensus adapter has timed out for some number of certs, but those certs have actually made it into consensus.
- A validator will then receive those certs from consensus, sequence them, and put them into the execution driver queue.
- Execution driver wakes up, and attempts to execute all certs in its queue by sending them to NodeSyncState.
- The pending queue is ordered by insert time, so it is guaranteed to preserve the ordering of certs as they arrived from consensus (assuming that none of those certs arrived via some other channel in the meantime).
- However, NodeSyncState parallelizes cert execution, and it is unaware of dependencies among its inputs. Given certs A and B which are sequenced in the order A, B, even though we send A to NodeSyncState first, it will race with B, and B may fail before A is finished, even though it would have completed successfully if A had been executed first.
- This leads to NodeSyncState deciding that parent certs are missing, which causes it to ask other validators to provide it with the cert's effects. Those other validators may be in the same situation.

Some additional observations:

- If a cert was enqueued for execution by the consensus task, then all the shared object dependencies of that cert must have been enqueued previously. If this was the only way that certs were enqueued, then we could be assured that all shared object parents of a cert in the queue must precede it in the queue, or have been previously executed.
- However, certs may also be enqueued by gossip which doesn't provide this guarantee. (Although gossip transmits digests in causal order, validators randomly shuffle their gossip peers, and so may receive a cert via gossip without first receiving that certs parents).
- Additionally, a shared object cert that arrives via consensus may have missing owned object parent certs (e.g. for the gas object), which themselves do not have any shared inputs, and hence will not have arrived via consensus. While the 2f+1 signers of the cert must have executed the missing parent certs, they may not yet be able to execute the cert itself if they have not sequenced it, hence they will not be able to provide TransactionEffects, which is how we normally obtain parent information.
- Because of the above, and also because parallel execution of the pending list will be required to achieve desired throughput, we should treat the execution driver queue as unordered. It's not reliable, and even if it were, it would not be useful since we can't serialize execution of the whole queue.

Proposed solution:

While the execution driver / NodeSyncState lacks explicit parent information (because it does not have TransactionEffects), we can compute a partial ordering of the certs in the queue, as follows:
- Two certs with a shared input in common can be ordered based on the local shared locks. If shared locks are missing the cert is not executable anyway.
- Two certs with an owned input in common can be order based on the version numbers in the inputs.

Note that this is a "partial partial ordering" - we can't detect the case where a cert depends on a newly-created output of some other cert, because that output will not be known until execution, so there may be dependency information not captured here.

Nevertheless, computing this partial order and then executing certs accordingly should greatly increase the throughput of sync, and reduce the frequency with which we call execute_cert_to_true_effects to discover missing parents. But, note that we cannot eliminate the need for that function entirely. It is always possible to receive a cert that has missing owned object parents.

**Comment by mwtian** [comment]
Also IIUC when a validator signs an owned txn the validator must have all parent objs locally.I wonder what happens when the validator does not have the parent objs locally. This also has some parallel to receiving txn from consensus.

**Comment by mwtian** [comment]
In the new world of owned certificate sync via Narwhal, we no longer have a need for `execute_cert_to_true_effects()`, right?

**Comment by andll** [comment]
>In the new world of owned certificate sync via Narwhal, we no longer have a need for execute_cert_to_true_effects(), right?

Can you explain a bit why?

**Comment by mwtian** [comment]
Even before the "owned objects via narwhal" change, I did not have the context about the trade off between executing certificates on other nodes for effect, vs waiting for gossip and checkout to catch up on the missing certificates. I guess the decision comes down to latency.

@andll in the new world of propagating certificates via narwhal, if two validator nodes are running "normally", what is the bound on how long a certificate committed in one node can remaining missing on another node?

**Comment by andll** [comment]
Other node will see certificate when narwhal is committed. If everything is normal then it is around ~commit latency. But of course if node have network connection problems or do not receive narwhal commits for other reasons there is no upper bound
