### ISSUE TITLE
RCP API Request: `sui_getPackagesPublishedByAddress`

### ISSUE THREAD

**Issue by FrankC01** [MystenLabs/sui#5003]
There is currently no way to get package details other by providing the package ID to `sui_getObject` but the owner address is `Immutable` which can not be provided through any JSON RPC API

However; like `sui_getObjectsOwnedByAddress` it would be convenient for SDK and other uses to get the collection of packages by address in one call.

**Comment by sblackshear** [comment]
In the meantime, I think https://docs.sui.io/sui-jsonrpc#sui_getEventsBySender, then filtering the results by `PublishEvent` is a workaround for this.

**Comment by FrankC01** [comment]
Yes, I looked at that but it would mean running constantly else potential for missing the event right? I don't see any option to back process missed events unless I'm missing something?

**Comment by 666lcz** [comment]
@FrankC01 [docs.sui.io/sui-jsonrpc#sui_getEventsBySender](https://docs.sui.io/sui-jsonrpc#sui_getEventsBySender) is a historical event query API(as opposed to event subscription API), and does not require you to run constantly.

**Comment by FrankC01** [comment]
Ahh, that works and thanks. @sblackshear apologies as I associated your response with event processing.
