### ISSUE TITLE
Ed25519 Keypair generates wrong address.

### ISSUE THREAD

**Issue by rocalex** [MystenLabs/sui#5016]
I'm trying to get keypair using `Ed25519Keypair.deriveKeypair` of `@mysten/sui.js` experimental version.

```
const keypair = Ed25519Keypair.deriveKeypair(process.env.SIGNER_MNEMONIC!)
const signer = new RawSigner(keypair, provider)
console.log(await signer.getAddress())
```
The address I got is `008b7d6ac55835878535dc2c2e8e606f86be2fe0`,
but the address which is imported in Sui wallet is `0xe31b70fbb4ed9cd51aa2626f0d7fecafcfb4b065`.
Why are they different?

**Comment by 666lcz** [comment]
@rocalex likely it's because the wallet is using a different version of SDK than the experimental version. Let me know if this still repros.

**Comment by vuadenthuj1** [comment]
Does anyone have solution for this problem?
