### ISSUE TITLE
[New]Sui by example support for multi-language translation

### ISSUE THREAD

**Issue by zhenfeng-zhu** [MystenLabs/sui#5017]
Sui by example doc is awesome! I think it's better to support multi-language translation.

I have made a Chinese version: https://awesomefenix.notion.site/sui-by-example-3fde4ab0446d4fb9ba3a00811d3b37df.

**Comment by randall-Mysten** [comment]
@zhenfeng-zhu Thank you! We are looking at localization solutions

**Comment by zhenfeng-zhu** [comment]
> @zhenfeng-zhu Thank you! We are looking at localization solutions

Looking forward to it!
