### ISSUE TITLE
[wallet-react-kit] kit keeps calling connect method when wallet connect request is rejected by user

### ISSUE THREAD

**Issue by bruceeewong** [MystenLabs/sui#5052]
## Steps to Reproduce Issue

For dapps which use Sui react wallet kit , the kit would keep calling connect method when wallet connection is rejected by user. 

Suspicious codes here: https://github.com/MystenLabs/sui/blob/main/sdk/wallet-adapter/packages/react-providers/src/WalletProvider.tsx#L127

I am represting Suiet Wallet team to report the issue. For our Suiet Wallet Adapter, we throw an Error when user rejected a connection request. [Codes here#](https://github.com/suiet/wallet-adapter/blob/main/src/adapter.ts#L22)

DApps like [Clutchy Marketplace](https://clutchy.io/) which uses your sui react kit can reproduce the issue when connecting to Suiet Wallet.

Steps: 
1. Make sure Suiet Wallet installed. [Chrome store link#](https://chrome.google.com/webstore/detail/suiet/khpkpbbcccdmmclmpigdgddabeilkdpd)
2. Open Clutchy Marketplace: https://clutchy.io/
3. Choose to connect Suiet Wallet
4. Click 'Cancel' Button  on the Connection Request popup window or Close the popup window

And it would popup Connection Request again right after you canceled. 

> What might happen here is that Suiet wallet adapter throws an error to the react kit, and the suspicious hook mentioned above calls `choose` method again.

Hope to get reply and fix!❤️

## Expected Result

Do not call connect method anymore if any wallet adapter throws errors (or say user rejects) during connection request.

## Actual Result

The react kit keeps calling connect method after wallet adapter throws errors during connection request.

## System Information

* OS: <specify OS version>
* Compiler: <specify compiler version>

**Comment by Jordan-Mysten** [comment]
This has been resolved in `main`
