### ISSUE TITLE
[RPC]Add call view function

### ISSUE THREAD

**Issue by uvd** [MystenLabs/sui#5091]
The dapp wants to retrieve the return value of a very complex algorithmic data, which does not involve any changes to the information on the chain, and is only read only ，The dapp side is difficult to implement this algorithm, or the contract provided by others can not implement the algorithm, need to be able to get this return value ,For example

```
public fun get_data(): u64 {
 ///  Very complicated algorithm

}
```

 the dapp wants the return value

**Comment by 666lcz** [comment]
duplicates #4967
