### ISSUE TITLE
sui_getEventsByModule returns no events for my module

### ISSUE THREAD

**Issue by tomfurrier** [MystenLabs/sui#5095]
## Steps to Reproduce Issue

```
curl --location --request POST https://fullnode.devnet.sui.io \
--header 'Content-Type: application/json' \
--data-raw '{  "jsonrpc": "2.0",  "id": 1,  "method": "sui_getEventsByModule",  "params": [    "0xa28c569cb1e272ad0d0c18b5ad2f48fa0c4e425e",    "playerstate_module",    5,    0,    100000000000000  ]}' | json_pp
```

## Expected Result

return the events, e.g. this transaction has the move events I want to get back: [tx exlorer](https://explorer.devnet.sui.io/transactions/szYvcd2eH%2Fv8oYJZdqWxpAkyfnxiB5wrKg7Ua3ZgJtE%3D)

## Actual Result

{
   "id" : 1,
   "jsonrpc" : "2.0",
   "result" : []
}

Having this issue since this morning. I also republished my module multiple times. The strange thing is that the devnet nft module returns some events: 

```
curl --location --request POST https://fullnode.devnet.sui.io \
--header 'Content-Type: application/json' \
--data-raw '{  "jsonrpc": "2.0",  "id": 1,  "method": "sui_getEventsByModule",  "params": [    "0x0000000000000000000000000000000000000002",    "devnet_nft",    5,    0,    100000000000000  ]}' | json_pp
```
```
{
   "id" : 1,
   "jsonrpc" : "2.0",
   "result" : [
      {
         "event" : {
            "moveEvent" : {
               "bcs" : "FE7RsUK52ldXLFJ6qyqGo0wNR+CE95YqNrDaVKZvKKCEBsNjE+ygqQtFeGFtcGxlIE5GVA==",
               "packageId" : "0x0000000000000000000000000000000000000002",
               "sender" : "0x84f7962a36b0da54a66f28a08406c36313eca0a9",
               "transactionModule" : "devnet_nft",
               "type" : "0x2::devnet_nft::MintNFTEvent"
            }
         },
         "timestamp" : 1665392659086,
         "txDigest" : "IlTDmgsiXDc+VaDiHJ3nGyHgVvsTP9wY65JDq228t+c="
      },
      {
....
```
## System Information

* OS: Windows
* Compiler: sui.exe-move 0.1.0

Also tried different languages / platforms, not just curl.

**Comment by 666lcz** [comment]
There is an ongoing problem with the fullnode indexer on DevNet, which might cause transactions/events to be missing from the fullnode

**Comment by tomfurrier** [comment]
Hi there, any update on this? From my tests it seems it is still an ongoing issue, not getting back my events. Devnet explorer seem to have some issues

**Comment by tomfurrier** [comment]
Based on my tests, it seems to be still an ongoing issue, can you confirm please that there are problems on your side?

**Comment by tomfurrier** [comment]
APIs changed, closing this
