### ISSUE TITLE
[New]RPC documents are out of date

### ISSUE THREAD

**Issue by 0xOutOfGas** [MystenLabs/sui#5144]
RPC documents are out of date.

RPC has a **sui_getEventsByTransaction**  API, but the `https://gateway.devnet.sui.io:443` does not suppport.
docs: https://docs.sui.io/sui-jsonrpc#sui_getEventsByTransaction
curl call error
```
$ curl --location --request POST https://gateway.devnet.sui.io:443 \
> --header 'Content-Type: application/json' \
> --data-raw '{
quote>   "jsonrpc": "2.0",
quote>   "id": 1,
quote>   "method": "sui_getEventsByTransaction",
quote>   "params": [
quote>     "KtcneBV8Rbj2NQg33j+6Wxh4dlJNnxgW3sRfJA6Xvic=",
quote>     20
quote>   ]
quote> }'
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1
```

**Comment by patrickkuo** [comment]
We are deprecating gateway, all of the methods in the RPC doc should be available in fullnode after next release.
Can you try `https://fullnode.devnet.sui.io:443`?

**Comment by 0xOutOfGas** [comment]
thanks, tried the fullnode, it works.
