### ISSUE TITLE
Sui Code Bug or Feature Request

### ISSUE THREAD

**Issue by sameul2012** [MystenLabs/sui#5146]
## Steps to Reproduce Issue

1. git clone https://github.com/MystenLabs/sui.git
2. git checkout --track origin/devnet
3. cargo install --path crates/sui

## Expected Result

Install suc.

## Actual Result

Got fail info,  during installation.

cargo install --path crates/sui

![image](https://user-images.githubusercontent.com/106046511/195298080-65d40a60-c0dd-4b94-aeb0-29a1a77b7376.png)

## System Information

* OS: macOS Catalina 10.15.7
* Compiler: <specify compiler version>

**Comment by huitseeker** [comment]
This should be closed by the latest releases of fastcrypt (and the dependency update in the present repo)
