### ISSUE TITLE
Sui Code Bug or Feature Request

### ISSUE THREAD

**Issue by c0wjay** [MystenLabs/sui#5172]
## Steps to Reproduce Issue

1. update sui version to v0.11.0 using `cargo install --locked --git https://github.com/MystenLabs/sui.git --branch "devnet" sui sui-gateway`
2. set rpc server url to devnet
`sui client switch --rpc https://gateway.devnet.sui.io:443`
3. create rpc call to devnet using sui-cli
eg. `sui client gas`, `sui client create-example-nft`, `sui client publish ..`, etc..

## Expected Result

Successful rpc call results

e.g.
```bash
$ sui client gas
                 Object ID                  |  Gas Value 
----------------------------------------------------------------------
 0x6e823357b8c4890c9bff6a23e12eb098bce80677 |  10000000  
```

## Actual Result

Errors

e.g.
```bash
thread 'main' panicked at 'not implemented: Rpc SuiClient does not support WalletSyncApi', /Users/c0wjay/.cargo/git/checkouts/sui-6ac459c53b1b685a/75d8223/crates/sui-sdk/src/lib.rs:572:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## System Information

* OS: M1 macOS Monterey 12.6(21G115)
* Compiler: <specify compiler version>

**Comment by chrisyy2003** [comment]
me too

**Comment by dougEfresh** [comment]
`sui client switch --rpc https://fullnode.devnet.sui.io:443`

^^ This solves the issue
