### ISSUE TITLE
[Question]Rocksdb not sync when write if it is safety on production env？

### ISSUE THREAD

**Issue by GrapeBaBa** [MystenLabs/sui#5185]
After read the code, now it used rocksdb default write options which sync is false when batch written. Is it safety on production env deployment?

**Comment by mwtian** [comment]
Thanks for reporting the issue. We have a discussion thread at https://github.com/MystenLabs/sui/issues/3210

**Comment by GrapeBaBa** [comment]
@mwtian Thanks for response. It seems I opened issue in a wrong repo.
