### ISSUE TITLE
[network] Implement point-to-point authenticated networking

### ISSUE THREAD

**Issue by huitseeker** [MystenLabs/sui#5189]
We need a networking library that offers the following primitives:

- any over-the-wan connection is authenticated cryptographically, thereby reducing the chance of an impersonation attack (external attacker looks like an internal node), or masquerade attack (internal node in one role looks like an internal node with a distinct role) -- roles here are e.g. primary or worker.
- in a second step, the authentication primitives for each message should be accessible to the protocol.

The current plan of attack is a p2p library using QUIC, which comes with built-in TLS:
https://docs.google.com/presentation/d/1NTfb_i29b5VUGAlM7k7aOfsPIoNIRzqjfATEeWA8cfE/edit?usp=sharing

The approach also has the ambition of serving the needs of both Narwhal & FastNFT.

- MystenLabs/narwhal#200

**Comment by bmwill** [comment]
Yep this is completed, we use TLS via QUIC. All narwhal links are now authenticated and encrypted.
