### ISSUE TITLE
[automation] introduce a Makefile (or similar) for local tooling automation 

### ISSUE THREAD

**Issue by akichidis** [MystenLabs/sui#5190]
Currently if someone needs to format the code, run the linter, bootstrap a node etc will need to do it manually. I believe if would have a Makefile (or some other alternative) for all those frequent running process it would really help to ensure that we have all the necessary tooling in one place and ready to be executed easily. We can start with something simple before we do more fancy stuff.

**Comment by stefan-mysten** [comment]
@akichidis is this still relevant? Should we close the issue as it has been stale for close to a year?

**Comment by akichidis** [comment]
> @akichidis is this still relevant? Should we close the issue as it has been stale for close to a year?

Thanks @stefan-mysten , I am closing this, things have changed a lot since then.
