### ISSUE TITLE
[get_collections] introduce end to end (integration) test

### ISSUE THREAD

**Issue by akichidis** [MystenLabs/sui#5194]
Story: MystenLabs/narwhal#67 

Currently we have no way to test the `get_collections` endpoint end to end, meaning to have a primary and worker node boostraped and call the endpoint to fetch the results.

As part of this task we would like to introduce an integration test (preferably via Rust) that will allow us to spin up 2 nodes, feed some transactions and try to call the `get_collections` via a mock client.

**Comment by stefan-mysten** [comment]
@akichidis is this still relevant? If not, let's close it. Thanks
#spring-cleanup
