### ISSUE TITLE
[safety] rate limit peers for pending header parents

### ISSUE THREAD

**Issue by akichidis** [MystenLabs/sui#5197]
### Description

From the issue MystenLabs/narwhal#78 

> We discussed with @asonnino offline about the liveness lock concerns and it seems that we might want to tackle this problem in a different manner to ensure we don't break liveness assumptions that research guarantees. On high level, an adversary that can slow down an honest node which implements the proposed fix, can bring the honest node to a point that will stop operating (acknowledging headers) and basically break the liveness assumptions and make our system susceptible to attacks.
> 
> Instead, we reduced the problem to receiving headers for which we don't manage to get their parents certificates (because the header is basically junk). Keep receiving such headers can lead to getting swamped by messages from potentially dishonest nodes and practically slow down our node. In this case we might want to throttle the peer node and ensure that we put a cap on the number of pending headers (for which we don't have their partner certificates). So if the received headers are junk (very high round number without 2f+1 parents) , we'll eventually stop receiving headers from that peer node until the buffer is cleaned up (this won't affect our ability to receive and process headers from rest of peers). We can probably have mechanisms to eventually clean up / GC those buffers as well. The upside of this method is that we don't break liveness guarantees only because we observe headers with high round numbers (which could be our node catching up) and we limit suspicious activity. If the peer node is honest and we happen to eventually receive those certificates, the buffer will get cleared up and we'll continue processing headers from that node again.

As part of this task we want to introduce the above mechanism to rate limit (throttle) peers when receiving headers for processing for which we are waiting to receive their certificate parents. We want the rate limiting to be independent for each peer and not affect one each other. For example, at the moment if we receive a header from a peer node `A` for processing, and their parents are missing from our internal storage, we first request the parents and then we proceed with the processing. We want to implement a mechanism like a bounded queue or similar, which will represent the maximum number of headers that we can have pending for processing for a specific peer (example `A`) . If the queue has reached its capacity, the we stop processing headers from them until we resolve the references for the existing/pending ones.

Note: based on the GC strategy, it seems that some sort of cleanup is [already happening on the `certificate_waiter`](https://github.com/MystenLabs/narwhal/blob/c13f52217343f5f936b0dfa22680fe413332b6dc/primary/src/certificate_waiter.rs#L122) . So eventually GC will clean up any old requests waiting for parent certificates - irrespective of the node.

**Comment by stefan-mysten** [comment]
@akichidis I assume this is not relevant anymore, so I am closing it. Feel free to re-open if it is still important.
