### ISSUE TITLE
[crypto, network] Wire in TLS to gRPC

### ISSUE THREAD

**Issue by huitseeker** [MystenLabs/sui#5257]
We have a TODO in several places to wire in TLS:

https://github.com/MystenLabs/narwhal/blob/d7963d378102ff7ebf1cc901ab2cc64ec8cd3b07/network/src/primary.rs#L48

And we also have a crate in mysten-infra:
https://github.com/MystenLabs/mysten-infra/tree/main/rccheck

That implements mTLS:
https://www.cloudflare.com/learning/access-management/what-is-mutual-tls/

This task tracks wiring the two together.

**Comment by akichidis** [comment]
I believe this is now complete as Anemo already offers TLS via selfsigned certs. Closing it  as complete.
