### ISSUE TITLE
[synchronizer] Add range requests to the BlockSynchronizer

### ISSUE THREAD

**Issue by huitseeker** [MystenLabs/sui#5268]
The `BlockSynchronizer` supports requesting certificates and block payloads in a batch, we would like to add the ability to receive a range of rounds, for which we should answer with all the blocks in that range.

(see also MystenLabs/sui#5263 MystenLabs/narwhal#209)

**Comment by mwtian** [comment]
Closing since we have range fetch in `CertificateWaiter` now.
