### ISSUE TITLE
the trait `MallocSizeOf` is not implemented for `BLS12381PublicKey`

### ISSUE THREAD

**Issue by sameul2012** [MystenLabs/sui#5269]
## Steps to Reproduce Issue

1.  git clone https://github.com/MystenLabs/sui.git
2. cd sui 
3.  git checkout --track origin/devnet
4.  cargo install --path crates/sui

## Expected Result

install suc

## Actual Result

![image](https://user-images.githubusercontent.com/106046511/195971666-53690327-9ad1-4ae6-bb63-36e64c697156.png)

## System Information

* OS: macOS, Catalina, 10.15.7
* Compiler: <specify compiler version>

**Comment by aschran** [comment]
dupe of #5329
