### ISSUE TITLE
Configuration. Available Websocket methods : ["sui_unsubscribeTransaction", "sui_subscribeTransaction", "rpc.discover"] . But need `sui_subscribeEvent` to work

### ISSUE THREAD

**Issue by bfdays** [MystenLabs/sui#5276]
I've started Sui node using docker setup taken from https://github.com/MystenLabs/sui/tree/main/docker/fullnode#readme .
And after start it outputs:
`2022-10-16T15:24:01.478967Z  INFO sui_json_rpc: Available Websocket methods : ["sui_unsubscribeTransaction", "sui_subscribeTransaction", "rpc.discover"]`
But I need `sui_subscribeEvent` to work - according to https://docs.sui.io/devnet/build/pubsub#subscribe .
After connection to WS and calling
`{"jsonrpc":"2.0", "id": 1, "method": "sui_subscribeEvent", "params": [{"All":[{"EventType":"MoveEvent"}, {"Package":"0x2"}, {"Module":"devnet_nft"}]}]}` it returns ` {"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1}`.
How to activate those methods? Is it something should be added into fullnode-template.yaml  config ?

**Comment by manhkhoa168** [comment]
> I've started Sui node using docker setup taken from https://github.com/MystenLabs/sui/tree/main/docker/fullnode#readme . And after start it outputs: `2022-10-16T15:24:01.478967Z INFO sui_json_rpc: Available Websocket methods : ["sui_unsubscribeTransaction", "sui_subscribeTransaction", "rpc.discover"]` But I need `sui_subscribeEvent` to work - according to https://docs.sui.io/devnet/build/pubsub#subscribe . After connection to WS and calling `{"jsonrpc":"2.0", "id": 1, "method": "sui_subscribeEvent", "params": [{"All":[{"EventType":"MoveEvent"}, {"Package":"0x2"}, {"Module":"devnet_nft"}]}]}` it returns ` {"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1}`. How to activate those methods? Is it something should be added into fullnode-template.yaml config ?

@bfdays Have you solved this problem yet? I am also having the same problem.

**Comment by patrickkuo** [comment]
@bfdays , @manhkhoa168 , have you got `enable-event-processing: true` in your `fullnode-template.yaml`?

**Comment by bfdays** [comment]
> @bfdays , @manhkhoa168 , have you got `enable-event-processing: true` in your `fullnode-template.yaml`?

Tried to and it didnt work. But now it works fine, thanks!
