### ISSUE TITLE
[network] Eliminate double serialization for the internal NW messages

### ISSUE THREAD

**Issue by huitseeker** [MystenLabs/sui#5292]
https://github.com/MystenLabs/sui/pull/1844

We can do something similar for narwhal....except narwhal uses generic types which wont play nicely with the code gen which really wants concrete types. 

The crypto library needs to be generic, but the rest of the code does not => we should make the config of the validator crypto a compile-time parameter.

**Comment by akichidis** [comment]
This is already done to some extend here https://github.com/MystenLabs/sui/blob/cf35a1362682723835ae8fd3d31360b4accc19a2/narwhal/types/build.rs . We continue doing more work. Closing this ticket now
