### ISSUE TITLE
[consensus] Refactor header_size to take into account a limit in # TXs

### ISSUE THREAD

**Issue by huitseeker** [MystenLabs/sui#5307]
`header_size` is a global limit on the size of a header. It is currently a byte limit for benchmarking purposes. 

It should rather be a gas / TX limit (as input to execution) in order to better satisfy the high-level backpressure needs of a downstream execution layer.

/cc @asonnino

**Comment by akichidis** [comment]
We changed the semantics of `header_size` here https://github.com/MystenLabs/sui/pull/5093

We might need to further look into the tx size idea as a further improvement
