### ISSUE TITLE
Support coin transfer without separate gas coin

### ISSUE THREAD

**Issue by sblackshear** [MystenLabs/sui#531]
Imagine the following, probably common scenario:
1. Alice creates a fresh address `A`
2. Bob sends a coin worth 100 to `A`
3. Alice wants to send a coin worth 10 to some other address `C`

Unfortunately, (3) is not currently possible. A transfer transaction (sensibly) wants distinct objects for the coin to be transferred and the coin to pay for gas. Alice actually cannot transfer away any of her coins, only use them to pay for gas in smart contract calls that do not require coin inputs.

This isn't fatal, but it is somewhat annoying. I think we can fix it by making the native transfer a bit more magical: subtract gas and the transferred value from the same coin instead of requiring two. This will also make the CLI and REST API's `transfer` functionality a bit more convenient because you will only need to supply one coin.

**Comment by lxfind** [comment]
https://mysten-labs.slack.com/archives/C02GD7J9HUM/p1652067097691489
We want three modes of transfer:
- deduct gas and transferred amount from single coin object ("magic transfer")
- deduct gas from one coin object, deduct transferred amount from a different coin object (???)
- deduct gas from one coin object, transfer a different coin object (today's transfer)

we should merge these 3 into one Transfer transaction, where it always uses the same coin object for transfer and gas, with an optional amount
