### ISSUE TITLE
Use more informative names for worker tasks.

### ISSUE THREAD

**Issue by mwtian** [MystenLabs/sui#5319]
### Description

In https://github.com/MystenLabs/narwhal/pull/707, we use a `TaskGroup` to manage the tasks in worker. However the task names are not informative right, which would make deciphering them harder in error messages. We should refactor to propagate task names for the tasks in worker.

**Comment by stefan-mysten** [comment]
@mwtian is this still relevant? If not, let's close it. Thanks

**Comment by mwtian** [comment]
This is no longer relevant to Consensus 2.0. Closing.
