### ISSUE TITLE
Migrate pending Narwhal PRs to the Sui repo

### ISSUE THREAD

**Issue by mwtian** [MystenLabs/sui#5328]
We have ~18 PRs currently open in the Narwhal repo. We need to notify PR authors about the upcoming move of Narwhal development to Sui repo, and provide steps or help out moving the PRs over.

## Steps to migrate a pending Narwhal PR to the Sui repo

First, locally rebase the working PR (using MystenLabs/narwhal#1031 as an example). It is also recommended to squash / cleanup working commits.

### If commit history does not matter and there is no deleted file
1. For changed files:
```
git diff --diff-filter=d --name-only main | xargs -I{} cp {} path/to/sui/narwhal/
```
2. For deleted files:
```
git diff --diff-filter=D --name-only main | xargs -I{} rm path/to/sui/narwhal/{}
```

### Otherwise
1. Copy the local narwhal repo to a new directory. The new directory will be irreversibly changed later.
2. Fast forward the working PR into the main branch of the new repo.
```
git merge range-sync-resp --ff-only
```
3. `brew install git-filter-repo`
4. Run the filter repo command:
```
git filter-repo --paths-from-file=./.filter-repo-paths.txt --to-subdirectory-filter=narwhal --force
```
5. Add the current repo as a remote to the Sui repo (after https://github.com/MystenLabs/sui/pull/4884 is merged)
```
git remote add narwhal-filtered path/to/filtered/narwhal
```
6. Commits from the original PR can now be cherry-picked into the Sui repo.

**Comment by akichidis** [comment]
Let's keep this in the SUI repo for historical reasons
