### ISSUE TITLE
the trait `MallocSizeOf` is not implemented for `BLS12381Signature`

### ISSUE THREAD

**Issue by sameul2012** [MystenLabs/sui#5329]
### Description

When running the command of `sui git:(devnet) cargo install --path crates/sui` got the below alarm:

the trait `MallocSizeOf` is not implemented for `BLS12381Signature`

### Steps to reproduce

macOS, Catalina, 10.15.7

1. git clone https://github.com/MystenLabs/sui.git
2. cd sui
3. git checkout --track origin/devnet
4. cargo install --path crates/sui

Snapshot :

![image](https://user-images.githubusercontent.com/106046511/195971536-a2e0160e-b4cc-4b3e-b3c5-0b75a0065dc6.png)

**Comment by akichidis** [comment]
Moved this issue to https://github.com/MystenLabs/sui repo as this is now the new Narwhal's home

**Comment by aschran** [comment]
Is your local repo up to date? This should have been fixed by https://github.com/MystenLabs/sui/commit/a9cbe6ec174339dc6247ec24baef6e4d322c6553

When I run your repro steps with a fresh clone, it works
