### ISSUE TITLE
wallet-standard call adapter's disconnect method in react provider

### ISSUE THREAD

**Issue by younessyk** [MystenLabs/sui#5375]
Steps to Reproduce Issue
Seems your team forget to call adapter's disconnect method in the react provider:

https://github.com/MystenLabs/sui/blob/main/sdk/wallet-adapter/packages/react-providers/src/WalletContext.tsx#L75

Expected Result
react provider can trigger the adapter's disconnect method.

Actual Result
react provider does not trigger the adapter's disconnect method.

System Information
OS:
Compiler:

**Comment by Jordan-Mysten** [comment]
Duplicate of #5178
