### ISSUE TITLE
[RFC][BCS/TS] Support multiple schemas

### ISSUE THREAD

**Issue by amnn** [MystenLabs/sui#5382]
Currently, `bcs` accumulates registered types in a singleton, updated by static functions so it's only possible to have one interface  for each type name.  This proposal suggests adding the ability to create new instances of the `bcs`, each with their own types registered.

## Motivation

#4878 introduces a backwards incompatible change to Sui's BCS schema (the addition of a field, deep within the structure of a Move Call Transaction).  For backwards compatibility, the TypeScript SDK needs to be able to talk to both the old and new schemas.  This was achieved by:

- [Duplicating all the BCS type registrations](https://github.com/MystenLabs/sui/pull/4878/files#r998757747) between `ObjectArg` (the type that changed) and `TransactionData` (the root), through 9 type registrations.

https://github.com/MystenLabs/sui/blob/d379a70a37caf4e2acf7b9aa9cfcf6a1a278aa66/sdk/typescript/src/types/sui-bcs.ts#L316-L363

- Supplying a different root type name during serialization, based on the version advertised by the RPC Provider:

https://github.com/MystenLabs/sui/blob/d379a70a37caf4e2acf7b9aa9cfcf6a1a278aa66/sdk/typescript/src/signers/txn-data-serializers/local-txn-data-serializer.ts#L345-L349

But this is quite error-prone and cumbersome, especially if we need to manage multiple unrelated schema changes.  Ideally, instead of this approach, we could define multiple schemas (or a function that returns a schema, based on RPC version), so the example above becomes:

```typescript
// sui-bcs.ts
function bcsSchema(version: string): BCS {
  const bcs = new BCS();

  /* ... */

  if (version === "0.11.0" || version === "0.12.0") {
    bcs.registerEnumType('ObjectArg', {
      ImmOrOwned: 'SuiObjectRef',
      Shared_Deprecated: 'ObjectID',
    });
  } else {
    bcs.registerStructType('SharedObjectRef', {
      objectId: 'ObjectID',
      initialSharedVersion: 'u64',
    });

    bcs.registerEnumType('ObjectArg', {
      ImmOrOwned: 'SuiObjectRef',
      Shared: 'SharedObjectRef',
    });
  }

 /* ... */

  return bcs;
}

export function bcsForAPI(version: string): BCS {
  /* wrapper to the above, with caching */
}

// local-txn-data-serializer.ts
const dataBytes = bcsForAPI(version).ser('TransactionData', tx, size).toBytes(); 
```

**Comment by stefan-mysten** [comment]
Given that the BCS implementation in TS SDK has received a revamp, I assume this is obsolete now. If so, @amnn / @hayes-mysten we can close this one.

**Comment by amnn** [comment]
Yes we can mark this as complete actually -- the current API where the BCS module exports an object with all the reader/writer implementations fits this bill.
