### ISSUE TITLE
[wallet-adapter] @mysten/wallet-adapter-react-ui doesn't work in Vite dev mode and CRA

### ISSUE THREAD

**Issue by kklas** [MystenLabs/sui#5415]
Using `WalletWrapper` (the connect button) from `@mysten/wallet-adapter-react-ui` doesn't work out of the box with fresh Vite and CRA projects.

## Vite

Note: the following issue only happens with `npm dev`. Hosted app compiled with `npm build` works as expected.

Steps to reproduce:
- create a new Vite project `npm create vite@latest`
- install `@mysten/wallet-adapter-react-ui` and other packages as per https://github.com/MystenLabs/sui/tree/main/sdk/wallet-adapter
- use `WalletWrapper` in your app:
```
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import './App.css'

import { WalletProvider } from "@mysten/wallet-adapter-react";
import { WalletStandardAdapterProvider } from "@mysten/wallet-adapter-all-wallets";
import { WalletWrapper } from "@mysten/wallet-adapter-react-ui";

export function App() {
  const supportedWallets = [
    // Add support for all wallets that adhere to the Wallet Standard:
    new WalletStandardAdapterProvider(),
  ];

  return (
    <WalletProvider adapters={supportedWallets}>
        <WalletWrapper />
    </WalletProvider>
  );
}

export default App
```

- run `yarn dev`
- open the page, click the "connect" button, select the wallet
- app crashes with following error:

![image](https://user-images.githubusercontent.com/7824233/196967932-77a4630a-0f23-4a27-a3a6-5aa7f9d052fa.png)

## CRA

When using create-react-app (setup new project with `pnpx create-react-app cra-app --template typescript` and use the same setup as with Vite above), a different error happens:

```
Module not found: Error: Can't resolve '@mui/icons-material/Settings' in '/home/user/work/tmp/cra-app/node_modules/.pnpm/@mysten+wallet-adapter-react-ui@0.2.1_txnjexkog2jefuxc3ttywdy37m/node_modules/@mysten/wallet-adapter-react-ui/dist'
Did you mean 'Settings.js'?
BREAKING CHANGE: The request '@mui/icons-material/Settings' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

This prevents both `npm start` and `npm build`

## Proposed solution

Lot's of people will be using the `WalletWrapper` component with CRA and VIte, so this should be either fixed so that using the "connect" button works out of the box both with Vite and CRA default projects, or there should be a note in the `README.md` on how to get it to work.

**Comment by kesne** [comment]
I was able to get this running by added `@emotion/styled` and `@emotion/react` as dependencies. https://codesandbox.io/s/blissful-nash-3by239

Let me know if that help you. We can add these as peer dependencies as well.

**Comment by kklas** [comment]
I've added both `@emotion/styled` and `@emotin/react`. The issue is not with getting it running, but when selecting the wallet from the list that pops up when you click 'connect' crashes the app.

I'm not able to test this with the sandbox example you provided because it doesn't detect Sui Wallet although I have it installed.

![image](https://user-images.githubusercontent.com/7824233/197292913-96f9d6e5-0918-46ac-82ce-f9fe3fe1cf95.png)

**Comment by Jordan-Mysten** [comment]
@kklas If you pop it out into its own window, it should work: https://3by239.sse.codesandbox.io/

**Comment by kklas** [comment]
Thanks!

The issue seems to be due to HMR `@vitejs/plugin-react`. This is the `package.json` I'm using (generated by "npm create vite@latest"):
```
{
  "name": "vite-project",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@babel/core": ">=7.0.0 <8.0.0",
    "@emotion/react": "^11.10.4",
    "@emotion/styled": "^11.10.4",
    "@mysten/sui.js": "^0.13.0",
    "@mysten/wallet-adapter-all-wallets": "^0.2.1",
    "@mysten/wallet-adapter-react": "^4.0.0",
    "@mysten/wallet-adapter-react-ui": "^0.2.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.0.2",
    "@types/react-dom": "^18.0.2",,
    "@vitejs/plugin-react": "^2.1.0",
    "typescript": "^4.6.4",
    "vite": "^3.1.0"
  }
}
```
The differences between your sandbox example and my local code are:
- react 17 vs react 18 in my code
- vite 2 vs vite 3 in my code
- plugin-react-refresh vs plugin-react in my code

The problem seems to be `@vitejs/plugin-react`. Once I've switched it to `@vitejs/plugin-react-refresh` (as it is in the sandbox) and changed `vite.config.ts` appropriately, the button worked in my local repo!

Since `plugin-react-refresh` is deprecated ([link](https://www.npmjs.com/package/@vitejs/plugin-react-refresh)), I suggest the code is tested against `plugin-react` / `vite 3` / `react18`.

**Comment by Jordan-Mysten** [comment]
We're released [Sui Wallet Kit](https://github.com/MystenLabs/sui/tree/main/sdk/wallet-adapter/wallet-kit), which should resolve these issues!
