### ISSUE TITLE
`sui move build` and `sui move test` fail when referencing a *tag* `rev` in Move.toml

### ISSUE THREAD

**Issue by kklas** [MystenLabs/sui#5433]
When using a **tag** instead of a branch name or commit hash in the `rev` field in the git syntax for importing a dependency in `Move.toml`, `sui move build` and `sui move test` will result in an error.

e.g. using `rev = "devnet"` (branch name) or `rev = "b8d7434a3"` will succeed, while using `rev = "devnet-0.12.0"` (git tag) will fail. 
## Steps to Reproduce Issue

1. Add `Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet-0.12.0" }` to Move.toml
2. run `sui move build` or `sui move test`
3. errors with `Failed to build Move modules: "Unable to resolve packages for package 'amm'".`

## System Information

* OS: `fedora linux x86_64`
* Compiler: `sui 0.12.0`

**Comment by sblackshear** [comment]
Good catch!

This is a Move language feature, not a Sui-specific one--I filed https://github.com/move-language/move/issues/608 in in the Move repo for this.

I suspect that this was broken by either https://github.com/move-language/move/commit/1b258a06e3c7d2bc9174578aac92cca3ac19de71 or https://github.com/move-language/move/commit/22f016d4470bb8afa6acd31d1c2cfec13f66c4b2 (probably the former given the timing of the breakage).
