### ISSUE TITLE
Sui doc content issue or request

### ISSUE THREAD

**Issue by Eren-1Yeager** [MystenLabs/sui#5481]
In this website which is your document website    https://docs.sui.io/devnet/learn   there is a link which should be your roadmap link but it is invalid.      https://github.com/MystenLabs/sui/blob/main/ROADMAP.md    (this is the link)   It is an honor to help SUI community.

**Comment by randall-Mysten** [comment]
Hi @Eren-1Yeager, indeed there is a broken link. Thank you for taking the time to point it out. I deleted the roadmap file that was out of date, but the PR that fixes it is still under review. You can view the new Roadmap at https://github.com/MystenLabs/sui/blob/main/DEVX_ROADMAP.md

This should get resolved this week. Cheers!

**Comment by kvishalv** [comment]
This issue is now resolved
