### ISSUE TITLE
error: could not compile `fiat-crypto`Sui Code Bug or Feature Request

### ISSUE THREAD

**Issue by josevc1** [MystenLabs/sui#5483]
Hello, im trying to compile Sui binaries but i got this error: 

```
error: could not compile `fiat-crypto`
Caused by:
  process didn't exit successfully: `rustc --crate-name fiat_crypto --edition=2018 /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fiat-crypto-0.1.17/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C debug-assertions=off --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=9923855c3fd07a37 -C extra-filename=-9923855c3fd07a37 --out-dir /tmp/cargo-installcFxSGb/release/deps -C strip=debuginfo -L dependency=/tmp/cargo-installcFxSGb/release/deps --cap-lints allow` (signal: 9, SIGKILL: kill)
error: failed to compile `sui v0.12.2 (https://github.com/MystenLabs/sui.git?branch=devnet#1f6eda49)`, intermediate artifacts can be found at `/tmp/cargo-installHpEn2Z`
error: failed to compile `sui-node v0.12.2 (https://github.com/MystenLabs/sui.git?branch=devnet#1f6eda49)`, intermediate artifacts can be found at `/tmp/cargo-installcFxSGb`

```

I have the lastest version of rust  (1.64.0)
Im installed all the prerequisites mentioned by the installation guide. Could you please help me? Thanks

Im using Ubuntu 20.04

**Comment by joyqvq** [comment]
checking, what is your cargo version?
```
cargo --version 
cargo 1.64.0 (387270bc7 2022-09-16)
```
and the step you took to install is: `cargo install --locked --git https://github.com/MystenLabs/sui.git --branch devnet sui sui-node`
?

**Comment by chrisyy2003** [comment]
> checking, what is your cargo version?
> 
> ```
> cargo --version 
> cargo 1.64.0 (387270bc7 2022-09-16)
> ```
> 
> and the step you took to install is: `cargo install --locked --git https://github.com/MystenLabs/sui.git --branch devnet sui sui-node` ?

hi，Do you know what my problem ([issue](https://github.com/MystenLabs/sui/issues/5480)) is, I just try to install the sui binary, my cargo version is 1.66

**Comment by josevc1** [comment]
> 

Hello, yes, i have Cargo 1.64.0 and i'm using exactly that parameters to install sui.

**Comment by joyqvq** [comment]
it sounds like you may have cargo nightly. confirmed that cargo stable 1.64.0 should work. 

we merged the fix, if you try build from main instead of devnet branch it should work.

**Comment by josevc1** [comment]
> it sounds like you may have cargo nightly. confirmed that cargo stable 1.64.0 should work.
> 
> we merged the fix, if you try build from main instead of devnet branch it should work.

Thanks for your assistance. How i merge it from main? is this the correct line: 
cargo install --locked --git https://github.com/MystenLabs/sui.git --branch mainnet sui sui-node

**Comment by joyqvq** [comment]
change mainnet to main

**Comment by josevc1** [comment]
Thanks, i will try!

**Comment by josevc1** [comment]
I run it and now i got a lightly variation of the same error: 
`error: could not compile `fiat-crypto`

Caused by:
  process didn't exit successfully: `rustc --crate-name fiat_crypto --edition=2018 /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fiat-crypto-0.1.14/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C debug-assertions=off --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=ab8ab94d28e061ed -C extra-filename=-ab8ab94d28e061ed --out-dir /tmp/cargo-installImlNhS/release/deps -C strip=debuginfo -L dependency=/tmp/cargo-installImlNhS/release/deps --cap-lints allow` (signal: 9, SIGKILL: kill)
error: failed to compile `sui v0.13.0 (https://github.com/MystenLabs/sui.git?branch=main#c56de648)`, intermediate artifacts can be found at `/tmp/cargo-installW6EldH`
error: failed to compile `sui-node v0.13.0 (https://github.com/MystenLabs/sui.git?branch=main#c56de648)`, intermediate artifacts can be found at `/tmp/cargo-installImlNhS`
`
Is there a way to exclude fiat-crypto from the installation?

**Comment by josevc1** [comment]
My bad, i was running a VM with only 2GB of memory, i increased it to 8GB and i successfully installed Sui.
Now i'm trying to run it with:
` cargo run --release --bin sui-node -- --config-path fullnode.yaml`
But it can not found Cargo.toml:
`error: could not find `Cargo.toml` in `/root` or any parent directory`
