### ISSUE TITLE
 **New**.Sui doc content issue or request Sui wallet error

### ISSUE THREAD

**Issue by Starlew77** [MystenLabs/sui#5498]
If this is an issue with existing content, provide the URL or GitHub path to the topic. Otherwise, use **New**.

Hi i downloaded wallet extentsion and signed up for sui wallet the wallet uploaded and worked fine then i got a long error message which iv attached screenshots and this message below my email is mediastar1977@gmail.com 07366224426 if needed and can forward images across,  i am not very computer literate when it comes to programming  and building I  hope iv done this right but thought you would want to see the error message ,, im really interested in your project and based in the Uk i have an exstensive background sales and marketing so dont know if you have anything i can do to help contribute to your business module 

. Error fetching owned object: TypeError: Network request failed for address
![20221024_112315](https://user
![20221024_112304](https://user-images.githubusercontent.com/116
![20221024_112254](https://user-images.githubusercontent.com/116558527/197510221-081975f2-ffbe-4152-85e7-e6586fba277b.jpg)
558527/197510195-7dc4f118-98b1-4b14-9842-8434112eae6e.jpg)

![20221024_112357](https://user-images.githubusercontent.com/116558527/197510164-82aabd60-4cec-461b-9065-c2b712e49724.jpg)

![20221024_112326](https://user-images.githubusercontent.com/116558527/197510137-e115171f-379f-4d19-bfb8-59ae65643795.jpg)

![20221024_112346](https://user-images.githubusercontent.com/116558527/197510114-c3f28d7a-eb4d-4d01-a6f1-184644c3df81.jpg)
-images.githubusercontent.com/116558527/197510095-88008af1-0f3e-4a33-ad7f-5f8973a49aac.jpg)

![20221024_112337](https://user-images.githubusercontent.com/116558527/197510061-f4b587a8-207d-4ffe-b4ad-b55acfd5962f.jpg)
 0x3102603cc0119e8eb0dbc5287a43ae1c54b16475eature Request

Thank you for taking the time to let us know about the issue or request. We triage all new issues and requests within 2 business days. We will follow up if we need additional information.

**Comment by randall-Mysten** [comment]
Hi @Starlew77 Thanks for reporting your issue, sorry you are having difficulty. This error is caused by some issues with Devnet that we encountered over the last few days. We are actively working to resolve it. You don't need to do anything other than wait for the fix, if it is not already resolved.

**Comment by Starlew77** [comment]
Hi

Thank for reply and rapid response 🙏 I look forward to when the project
goes live 👍

Kind regards
