### ISSUE TITLE
[docs] Document gas fee estimation process

### ISSUE THREAD

**Issue by awelc** [MystenLabs/sui#5576]
We have been getting questions on our social channels on gas fee estimation and we should have it documented somewhere. If this is already done, let's have a link here so that it's searchable in the issues. Preliminarily assigning @oxade to it as our guru in this space.

**Comment by oxade** [comment]
Working on this. Will sync with @randall-Mysten on how to best document estimation.

**Comment by awelc** [comment]
@oxade, any update on this?

**Comment by oxade** [comment]
@awelc yes. @sblackshear believes we should just point folks to https://docs.sui.io/sui-jsonrpc#sui_dryRunTransaction for now. When the estimators are fleshed out, we can elaborate on the docs.
So for now I can at most add a couple lines in the docs saying how to use dry run approach.

**Comment by awelc** [comment]
> So for now I can at most add a couple lines in the docs saying how to use dry run approach.

I think it would be worthwhile. If possible, please close this issue once these couple of lines are added.
