### ISSUE TITLE
[docs] Add a diagram for TX object dependencies 

### ISSUE THREAD

**Issue by huitseeker** [MystenLabs/sui#564]
A followup to #557, where we noted the explanation of TXes depending on objects output by other TXes could be explained by a diagram.

This example may help:
```mermaid
graph TB;
    A((3))-->|Some label|B((9))
    A-->C((20))
    C-->D((15))
    C-->|another label|E((7))
```

_Originally posted by @huitseeker in https://github.com/MystenLabs/fastnft/pull/557#discussion_r814417251_

**Comment by Clay-Mysten** [comment]
Hi Francois and Xun,

Please see the diagrams Evan has kindly provided to see if we might include them in the programming with objects tutorial or elsewhere:
https://app.golinks.io/sui-storage

Thanks!

**Comment by Clay-Mysten** [comment]
@huitseeker should we work this in to the section beginning with:
"Transactions (and thus, certificates) take objects as input..."

**Comment by randall-Mysten** [comment]
Closing this issue. Will open a new issue if this comes up again
