### ISSUE TITLE
[Move] Move builds appear stuck because of long runtime and lack of output

### ISSUE THREAD

**Issue by amnn** [MystenLabs/sui#5645]
Running `sui move build` can take a long time to run and currently produces no output on success.  This can make it difficult to distinguish a long build that's making progress with a stuck build.  Consider printing out the various stages of the build either always, or under a `--verbose` flag so that people can follow along with the build.

### Repro

```
$ sui move new /tmp/example
$ sui move build -p /tmp/example
```

The first run of this build can take an unnerving amount of time (10s on my local machine, although community reports longer times as well), and produces no output.

**Comment by sblackshear** [comment]
In my experience, the main reason this happens is if you are building a package with git dependencies and need to download the appropriate repos for the first time (they are cached in `~/.move` after that). It would definitely be good for `sui move build` to at least tell the dev what's being downloaded in the default logging so they understand this. I don't think a build with all the source present locally should ever take more than a second or two.

**Comment by awelc** [comment]
> In my experience, the main reason this happens is if you are building a package with git dependencies and need to download the appropriate repos for the first time (they are cached in ~/.move after that).

That's what I was about to write. Unfortunately all this logic is delegated to core Move so all the changes would have to happen there...

**Comment by awelc** [comment]
I looked into core Move side of things real quick and the output (that this type of info could be part of) is done via an explicit write passed as an argument to `compile_package_no_exit` but dependency loading happens deep in the guts of resolution graph construction where the writer is not (easily) available... It looks like it would require a bit more serious refactoring on the core Move side...

**Comment by amnn** [comment]
Sam recently landed #5506 which makes it easier to configure when we get diagnostic information from `move` when called via `sui`.  It's possible that a combination of enabling diagnostics with that and adding the appropriate log messages to `stderr` in Move will achieve what we want here.  It will require some changes to Move, but not too bad.

**Comment by awelc** [comment]
I don't know if it's @sblackshear's recent update or another change, but we now have the same output as core Move when using `sui move build`:
```
~/sui/target/debug/sui move -p ~/sui/sui_programmability/examples/move_tutorial build
INCLUDING DEPENDENCY MoveStdlib
INCLUDING DEPENDENCY Sui
BUILDING MyFirstPackage
```

It's working like this on the main branch but not on devnet so something definitely changed in the meantime. I am pretty sure this was the functionality we had initially but somehow lost it along the way.

The verbose flag, when used with core Move's `move build` does not produce any additional output either (same output as above), unless I am calling things wrong (tried `-v` as a parameter for `move` and for `build` even though only the first seems to make sense:

```
./target/debug/move -v -p ~/tmp/gen_coin build -v
```

**Comment by amnn** [comment]
I'm pretty sure this is @sblackshear's change -- I recall that it changed
the BuildConfig associated with `move build` to print diagnostics.  If the
build needs to pull stdlib or sui framework, will it pause after the
relevant INCLUDING DEPENDENCY line?

**Comment by awelc** [comment]
> If the build needs to pull stdlib or sui framework, will it pause after the relevant INCLUDING DEPENDENCY line?

Sadly no.. As per my conversation with @tnowacki on Slack:

> The “INCLUDING DEPENDENCY ” print is basically a no-op

and

> we should just add some printing ... before invoking the “git” comands

(which should happen in the `download_and_update_if_remote` function but we'd need to thread the writer parameter to that point to do it properly)

**Comment by awelc** [comment]
Modified core Move to print additional diagnostics before un-cached dependencies are retrieved from a remote Git repository in https://github.com/move-language/move/pull/643

Will land in Sui once we update the Move version, which is not trivial at the moment due to core Move changes related to gas cost (@oxade is looking into this).

**Comment by awelc** [comment]
Addressed in https://github.com/move-language/move/pull/643 and merged (by @oxade) in https://github.com/MystenLabs/sui/pull/5910
