### ISSUE TITLE
Docs [Update hardware requirements]

### ISSUE THREAD

**Issue by Nelrann** [MystenLabs/sui#5669]
With the massive influx of new users and the demand for faucet, a machine with 2 CPUs + 8G RAM is no longer enough

Documentation on minimum hardware requirements to run a Sui Fullnode needs to be updated

https://docs.sui.io/build/fullnode#full-node-setup

**Comment by randall-Mysten** [comment]
Hi @Nelrann, We are actively working to identify the proper requirements and will publish updated guidance soon. Thanks for reporting this issue.

**Comment by randall-Mysten** [comment]
hardware info is now updated
