### ISSUE TITLE
Faile to Install Sui binaries

### ISSUE THREAD

**Issue by moraceae** [MystenLabs/sui#5679]
Win 11
rustup 1.25.1 (bb60b1e89 2022-07-12)

error: failed to run custom build command for `librocksdb-sys v0.8.0+7.4.4`

Caused by:
  process didn't exit successfully: `C:\Users\Wes\AppData\Local\Temp\cargo-installl8I2WX\release\build\librocksdb-sys-fc9f37074407e89e\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', C:\Users\Wes\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.60.1\src/lib.rs:2172:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by stefan-mysten** [comment]
@moraceae thanks for reporting this; since then, this has been fixed so I will close this issue. Feel free to create a new issue if you still encounter problems when installing Sui.
