### ISSUE TITLE
[doc] Document the distinct types of transactions and their differences

### ISSUE THREAD

**Issue by huitseeker** [MystenLabs/sui#568]
This came up in https://docs.google.com/document/d/1LYTRODgj5GuufocEqKTqzozJJ7MusFOK_s0f8JKoEaw/edit?disco=AAAAWBkBmgk:

> > The only way to transfer it would be that the bored ape contract defined a transfer API that allows me to call into
> That's correct. In the future, you could imagine (e.g.) a `transfer` ability (and corresponding verifier pass) that allows a programmer to express the intention of this type to be used in unconditional transfers + that would allow us to use the native API on such types.

IOW, native transfers are only available for coin objects. We should document this in https://github.com/MystenLabs/fastnft/blob/main/doc/transactions.md at a high level (at the start of the document), to make the difference between the cold abstract notions of "move call transaction" and "native transaction" more concrete in terms of what they can be used for.

**Comment by Clay-Mysten** [comment]
Adding Janet as she's looking for status on this.
