### ISSUE TITLE
Why does the sui_getTransaction api  not return the sequence number of the transaction

### ISSUE THREAD

**Issue by leezijie** [MystenLabs/sui#5689]
I didn't get the sequence number from the api to get the transaction information. What api can I use to query the transaction to get the sequence number

`{"jsonrpc":"2.0","result":{"certificate":{"transactionDigest":"QjLsxWL/03jJ3XYiiNriu6atr/KVesRza8PLxXrQgaE=","data":{"transactions":[{"TransferSui":{"recipient":"0x91c03f113f196be6eb3e73f1c716838c4b98eaa6","amount":100000}}],"sender":"0xa175cd2c7deb96a3919ae7ccd592fa55a0cb4b5a","gasPayment":{"objectId":"0x1757666cedf9f7d1f4dbda3cf7f12b668ec62e92","version":13,"digest":"b7857QqlkBP+9ycxITLDAudZ41e1bRORvRsQHxdZJRI="},"gasBudget":100},"txSignature":"ALQlmgDG2zl5y/jZFk1jwYRyJ8XFOBmswx9nbWZeaiwiw8D7noTaRc3rzjJgo+8bUlsJdchgi1XbkEGulMyzJgLanKK9zMUS3TdOpsSwXNkd4U6SJQfAX6U83eZLNmPfaQ==","authSignInfo":{"epoch":0,"signature":"iMQ+ipJ4rk1r+uTb82tOavfme7+b/DPZYJK/OvGoNa1Z7urmmxm9c95yQ58o7xj7","signers_map":[58,48,0,0,1,0,0,0,0,0,2,0,16,0,0,0,0,0,1,0,3,0]}},"effects":{"status":{"status":"success"},"gasUsed":{"computationCost":45,"storageCost":48,"storageRebate":32},"transactionDigest":"QjLsxWL/03jJ3XYiiNriu6atr/KVesRza8PLxXrQgaE=","created":[{"owner":{"AddressOwner":"0x91c03f113f196be6eb3e73f1c716838c4b98eaa6"},"reference":{"objectId":"0x008df5bfba8f457d94a94e7393ee4433070783c6","version":1,"digest":"ICu3mP5qatOgwGs5LZcavF0ZqLomwT+eLjyygSE7Pgo="}}],"mutated":[{"owner":{"AddressOwner":"0xa175cd2c7deb96a3919ae7ccd592fa55a0cb4b5a"},"reference":{"objectId":"0x1757666cedf9f7d1f4dbda3cf7f12b668ec62e92","version":14,"digest":"Y2KSe9s09WLBJo5k4v9CKYkCNbaR1a6SZv2SCaFMwN4="}}],"gasObject":{"owner":{"AddressOwner":"0xa175cd2c7deb96a3919ae7ccd592fa55a0cb4b5a"},"reference":{"objectId":"0x1757666cedf9f7d1f4dbda3cf7f12b668ec62e92","version":14,"digest":"Y2KSe9s09WLBJo5k4v9CKYkCNbaR1a6SZv2SCaFMwN4="}},"events":[{"transferObject":{"packageId":"0x0000000000000000000000000000000000000002","transactionModule":"native","sender":"0xa175cd2c7deb96a3919ae7ccd592fa55a0cb4b5a","recipient":{"AddressOwner":"0x91c03f113f196be6eb3e73f1c716838c4b98eaa6"},"objectId":"0x1757666cedf9f7d1f4dbda3cf7f12b668ec62e92","version":13,"type":"Coin","amount":100000}}],"dependencies":["09R4dbHdpmxYlOUmUwidKdkcxoJtEKLQOLxZVIGQKYA="]},"timestamp_ms":1667197046943,"parsed_data":null},"id":1}`

**Comment by patrickkuo** [comment]
the sequence number is local to the full node (causally ordered), so it is not global and different full node will have different transaction sequence for the same transaction. To prevent confusion we intensionally hide the tx seq number.

**Comment by leezijie** [comment]
> the sequence number is local to the full node (causally ordered), so it is not global and different full node will have different transaction sequence for the same transaction. To prevent confusion we intensionally hide the tx seq number.

@patrickkuo I am a developer of an exchange. May I ask what I need to do to scan transactions?Now,I get num through sui_getTotalTransactionNumber,then polling through the sui_getTransactionsInRange.Finally, you can obtain detailed information through the sui_getTransaction.

**Comment by patrickkuo** [comment]
we now have a paginated [sui_getTransactions](https://docs.sui.io/sui-jsonrpc#sui_getTransactions) method, if you have the last known transaction hash, you can get all new transactions with last known transaction digest as cursor.
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "sui_getTransactions",
  "params": [
    "All",
    <Last know transaction digest>,
    1000,
    "Ascending"
  ]
}
```

**Comment by leezijie** [comment]
> we now have a paginated [sui_getTransactions](https://docs.sui.io/sui-jsonrpc#sui_getTransactions) method, if you have the last known transaction hash, you can get all new transactions with last known transaction digest as cursor.
> 
> ```
> {
>   "jsonrpc": "2.0",
>   "id": 1,
>   "method": "sui_getTransactions",
>   "params": [
>     "All",
>     <Last know transaction digest>,
>     1000,
>     "Ascending"
>   ]
> }
> ```

@patrickkuo Yes, if the order is right, that's fine. In addition, I would like to ask whether sui blockchain does not have the concept of height

**Comment by patrickkuo** [comment]
we don't have the concept of blocks as most of the Sui transactions are [confirmed asynchronously](https://docs.sui.io/devnet/learn/sui-compared#suis-approach-to-validating-new-transactions)

However you might be able to use checkpoints when it is available (checkpoint query still under development) to mimic blocks, checkpoints are created periodically (10mins), each checkpoint contains all transactions since last checkpoints and are globally ordered.

**Comment by leezijie** [comment]
> we don't have the concept of blocks as most of the Sui transactions are [confirmed asynchronously](https://docs.sui.io/devnet/learn/sui-compared#suis-approach-to-validating-new-transactions)
> 
> However you might be able to use checkpoints when it is available (checkpoint query still under development) to mimic blocks, checkpoints are created periodically (10mins), each checkpoint contains all transactions since last checkpoints and are globally ordered.

@patrickkuo Thank you for your help. I've got it.
