### ISSUE TITLE
Is there an api to getAllTransactions by time?

### ISSUE THREAD

**Issue by Wangmmx** [MystenLabs/sui#5691]
Hi, I want to get all transaction by time range,  the `sui_getTransactionsInRange ` can get transactions by sequence, but I can not get the sequence in transaction details, It is inconvenient for me to check whether past transactions have been verified. And the `sui_getEventsByTimeRange ` only get transfer SUI transactions, if the transaction type is Pay, I can not get this either, so I missed a lot transactions

**Comment by patrickkuo** [comment]
With the new transaction query API you can query transactions with cursor if you have the last know transaction digest. We will be deprecating `sui_getTransactionsInRange` soon as it can be replaced by the new `sui_getTransactions` method.

Missing events from the new Pay transaction is an known issue and its fixed by this PR https://github.com/MystenLabs/sui/pull/5289, should be available after next devnet update.

**Comment by Wangmmx** [comment]
Thanks for your fast reply,  then I will continue to use the `sui_getEventsByTimeRange` method and wait for the next upgrade, thanks again, closing the issue now

**Comment by Wangmmx** [comment]
Hi, I found `sui_getEventsByTimeRange ` is deprecated? I need to get all transactions by time,  `sui_getTransactions ` can not replace the api I want, will the `sui_getEventsByTimeRange` added again? Or is that possible to add a new one like `sui_getTransactionsByTimeRange`?

**Comment by Wangmmx** [comment]
> Hi, I found `sui_getEventsByTimeRange ` is deprecated? I need to get all transactions by time, `sui_getTransactions ` can not replace the api I want, will the `sui_getEventsByTimeRange` added again? Or is that possible to add a new one like `sui_getTransactionsByTimeRange`?

It still works, only disappear in docs :)

**Comment by Wangmmx** [comment]
sui_getEventsByTimeRange is deprecated, method not found now, any other apis to replace it? I need to get transactions by time, thanks a lot

**Comment by Wangmmx** [comment]
the `sui_getTransactions ` method is complicated with the page params, I need to scan txs from time, so the deprecated one `sui_getEventsByTimeRange ` is ok for me to get all events with a time, because of the large amount of events, I had spent a lot of time optimizing the code, but now it can not work. Is it possible to add an api like get transactions by time range? I really need it, thanks again
