### ISSUE TITLE
Not able to install siu binaries

### ISSUE THREAD

**Issue by bhawikchain** [MystenLabs/sui#5692]
bhawik@Mac-mini suilearning % cargo install --locked --git https://github.com/MystenLabs/sui.git --branch devnet sui sui-node
    Updating git repository `https://github.com/MystenLabs/sui.git`
error: could not find `sui` in https://github.com/MystenLabs/sui.git?branch=devnet with version `*`
    Updating git repository `https://github.com/MystenLabs/sui.git`
error: could not find `sui-node` in https://github.com/MystenLabs/sui.git?branch=devnet with version `*`
     Summary Failed to install sui, sui-node (see error(s) above).
error: some crates failed to install

**Comment by bhawikchain** [comment]
solved

**Comment by yekai9527** [comment]
the same

**Comment by CocDap** [comment]
the same with me
