### ISSUE TITLE
[fastcrypto] List of all Sui crates that use fastcrypto, so versions are aligned

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/sui#5702]
`fastcrypto` is used as a dependency in multiple subcrates inside Sui and mysten-infra repos. Sometimes we might make an incompatible change that should be reflected to every dependent crate atomically to ensure the exact same behavior. Maintaining a list of where fastcrypto is used as a dep would help making atomic changes.

**Comment by jonas-lj** [comment]
In mysten-infra, crates/mysten-util-mem is the only sub crate depending on fastcrypto, and below is a list of all the subcrates in Sui specifying fastcrypto as a dependency:

crates/sui-json-rpc-types/
crates/sui-open-rpc/
crates/sui-keys/
crates/sui-framework-build/
crates/sui-simulator/
crates/sui-json-rpc/
crates/sui-types/
crates/workspace-hack/
crates/sui-cluster-test/
crates/sui-rosetta/
crates/sui/
crates/sui-framework/
crates/sui-core/
crates/sui-config/
narwhal/consensus/
narwhal/crypto/
narwhal/test-utils/
narwhal/types/
narwhal/config/
narwhal/dag/
narwhal/network/
narwhal/storage/
narwhal/executor/
narwhal/node/
narwhal/worker/
narwhal/primary/
