### ISSUE TITLE
Many errors of the "already locked by a different transaction" kind

### ISSUE THREAD

**Issue by awelc** [MystenLabs/sui#5716]
This was reported on Telegram and also discussed internally but I am still not sure if this was related to network instability, user error, or internal error. Assigning to @velvia for a followup.

**Comment by velvia** [comment]
I think this was due to network instability (which is itself some internal errors) due to a bunch of different incidents.

At the same time I think that @longbowlu has a fix related to this.

I'll let her comment on her fix but the network issues have since been resolved.

**Comment by abner-jie** [comment]
I also have this problem

Error in broadcasting after using paySui signature

**Comment by awelc** [comment]
Does not seem to be happening during subsequent DevEx on call. @velvia, @longbowlu - do you think we can close it (particularly if @longbowlu can link a PR to the fix @velvia mentioned in the previous comment)?

**Comment by amnn** [comment]
Checking back in on this as this week's oncall, @velvia and @longbowlu, can we close this now?

**Comment by velvia** [comment]
Yeah, I'll close it.   I think we can attribute it to a combo of "network instability" and a bit of "internal error" - mostly the nodes weren't quite healthy.
