### ISSUE TITLE
Transactions failing due to supposedly missing objects which actually exist

### ISSUE THREAD

**Issue by awelc** [MystenLabs/sui#5717]
This was reported on Discord and also discussed internally. It seems like this may be a problem with two transactions trying to access the same shared object at the same time - one will succeed but the other one will see an out-of-date object version and fail.

From what I understand, we are working on a fix that would make this workflow more reliable.

We may also make the error message a bit more detailed to better explain what the problem is if/when it happens in the future.

Assigning @patrickkuo to follow up, but please feel free to reassign.

**Comment by lxfind** [comment]
Is there anything more concrete? This issue won't be actionable, unless we at least have some logs/object ids that we could look into.

**Comment by awelc** [comment]
@lxfind, it does not look like this is happening still, and you also mentioned that some fixes have been put in for this. Could you please list PRs for these fixes here and close this issue?
