### ISSUE TITLE
error: could not find `sui` when install on ubuntu 20 server

### ISSUE THREAD

**Issue by denniswhte** [MystenLabs/sui#5727]
## Steps to Reproduce Issue

install sui on ubuntu 20 server by this command

```
cargo install --locked --git https://github.com/MystenLabs/sui.git --branch devnet sui sui-node
```

## Expected Result

install successfully

## Actual Result

got error

```
cargo install --locked --git https://github.com/MystenLabs/sui.git --branch devnet sui sui-node
    Updating git repository `https://github.com/MystenLabs/sui.git`
error: could not find `sui` in https://github.com/MystenLabs/sui.git?branch=devnet with version `*`
    Updating git repository `https://github.com/MystenLabs/sui.git`
error: could not find `sui-node` in https://github.com/MystenLabs/sui.git?branch=devnet with version `*`
     Summary Failed to install sui, sui-node (see error(s) above).
```

## System Information

* OS: ubuntu 20
* Compiler: cargo 1.62.1 (a748cf5a3 2022-06-08)

**Comment by stefan-mysten** [comment]
@denniswhte thanks for reporting this problem. Since then, it has likely been fixed so I will close the issue. Feel free to create a new issue if you still encounter problems when installing Sui.
