### ISSUE TITLE
**New** Unable to join discord

### ISSUE THREAD

**Issue by faizalmrub** [MystenLabs/sui#5783]
Trying to follow this documentation , https://docs.sui.io/devnet/build/install

Unable to join the discord channel and generate the tokens. getting error 'Unable to join'.

**Comment by randall-Mysten** [comment]
Hi @faizalmrub Sorry you are having trouble. We had a huge influx of users and the process got clogged. If you've provided a phone and are not using a brand new account, we can check on the status of your account. Please don't provide personal info here.

**Comment by randall-Mysten** [comment]
Yes, you need to include your phone number in your Discord account. It is used for verification to prevent fake accounts

**Comment by randall-Mysten** [comment]
Closing this issue, lmk if it is not resolved
