### ISSUE TITLE
[fastx crypto] audit Object ID derivation

### ISSUE THREAD

**Issue by sblackshear** [MystenLabs/sui#58]
We need to define a `ObjectIDPreimage` struct that holds (transaction_id, new_obj_sequence), then make it `BcsSignable` and use `sha3_hash` to get the digest. This ensures that we have one way to derive hashes (incl. for what we sign) and therefore domain separation is ensured uniformly..

**Comment by kchalkias** [comment]
The `Signable` interface might be deprecated after introducing IntentSigning, which is a unified (lang-agnostic) way to offer domain separation re what we're signing.

**Comment by sblackshear** [comment]
Great news! I will close this, in that case.
