### ISSUE TITLE
Sui doc content issue or request Sui wallet **new**

### ISSUE THREAD

**Issue by Starlew77** [MystenLabs/sui#5813]
**New**.

Logged into sui wallet its been  zeroed  ,all nft i have minted along with all nft rewards  ethos game disappeared plus nft rewards , beefy game record disappeared  plus all my activity disappeared please see attached photos 

I will request further tokens and  test all functions again just concerned that all my activity i have been doing with you is not being shown now :( if you a have any advice that would be great is this just ongoing bugs if you could advise please 

kind regards

stephen  

Thank you for taking the time to let us know about the issue or request. We triage all new issues and requests within 2 business days. We will follow up if we need additional information. 
![20221103_105401](https://user-images.githubusercontent.com/116558527/199704240-5f49a1a7-369c-4273-b65d-e50bc13936c6.jpg)
![20221103_105354](https://user-images.githubusercontent.com/116558527/199704259-130631ed-b53a-
![20221103_105411](https://user-images.githubusercontent.com/116558527/199704290-d30fa7f9-1e1f-4c27-87e5-3dcb1bfddb70.jpg)
4065-bcba-043b58044d1b.jpg)

**Comment by Starlew77** [comment]
![20221103_105354](https://user-images.githubusercontent.com/116558527/199705059-54baacb5-016a-4f0e-b96e-03083ca7d635.jpg)
 activity missing aswell

**Comment by Starlew77** [comment]
Sorry i have just tried to request more tokens but it wont allow me to get any i get this error message please advise 
![20221103_110532](https://user-images.githubusercontent.com/116558527/199705698-616b9d95-db5b-4f5b-851a-73341859929a.jpg)

**Comment by randall-Mysten** [comment]
Hi Steve, this is all normal and expected. Sui is still in test mode, so
nothing in your wallet is real. With each release the Sui Devnet network
resets all data and starts brand new. This means all of the coins, NFTs,
activity, etc. in your wallet are deleted. You are unable to get more coins
at the moment because there is an issue with the faucet. They are actively
working on resolving this. As we get closer to a public Testnet there will
be many updates that cause data wipes.

We announce releases in Discord. If you've not already joined, you can sign
up and then follow the announcements, ask questions like this, and interact
with the over 200K Sui community.

Cheers!

**Comment by Starlew77** [comment]
![20221103_221137](https://user-images.githubusercontent.com/116558527/199846256-47eba7fd-fba0-435f-b942-a5da8b1fbb2f.jpg)
![20221103_221216](https://user-images.githubusercontent.com/116558527/199846265-ba062949-0285-42b7-8209-7e406cbfc177.jpg)
![20221103_221106](https://user-images.githubusercontent.com/116558527/199846284-6ddff9f5-2db1-488a-b30b-81d3b935138a.jpg)

**Comment by Starlew77** [comment]
error in placing bet then when try and refresh and use does not place bet takes fee

**Comment by Starlew77** [comment]
![20221103_222353](https://user-images.githubusercontent.com/116558527/199846483-be759c64-2fec-4ba9-a9b7-686295ed2b5d.jpg)
![20221103_222345](https://user-images.githubusercontent.com/116558527/199846495-e68e3f47-a331-4f84-807d-f36165f0bafb.jpg)


 now the app and wallet dont connect properly no bet error

**Comment by randall-Mysten** [comment]
This is an issue with the site. A new release came out yesterday, so it
takes a day or two for sites to update to the newest version.

**Comment by Starlew77** [comment]
Cool thank you sorry should of giving more time before I tested it for you
, just wish  I could learn more tech stuff my back ground non tech though I
loved to lean so hope this is helping 👍

**Comment by randall-Mysten** [comment]
Appreciate the feedback. Consider setting up a full node:
https://docs.sui.io/devnet/build/fullnode

**Comment by Starlew77** [comment]
Hi

Thank you for getting back to me

Yes I will attempt to set this up I will contact  if I have any issues

Kind regards

Stephen 🙏

**Comment by Starlew77** [comment]
Hi Randall

I'm really sorry iv not been able to do anything at moment

I'm having issues with my pc at moment I was setting up the node and my
computer has broke somehow and said that the connection not secure to set
up node , I am trying to arrange to upgrade the computer and get correct
security in place but due to my position and as your prob aware the  cost
of living at present has caused a delay in this I'm stuck currently ,

 it's so frustrating and i appriciate the opportunity to work with your
platform as I want to learn and work within this industry and with my sales
and marketing background I feel I can contribute a great deal i was hoping
becoming one of your nodes would allow me to work with you guys once we
were up and running  regarding a project/business I want to build and
explore for the meterverse and allinging  shop to run in real world as your
aware I'm not technically savy as its a new industry but I belive this
industry has a massive future, so i want to be involved and your
projections great and  I belive has potential to be a market leader 😀

Once I can get this sorted,  Is  there anyone there i can liase with to
help me make sure everything is done correctly for the setup and running of
the node for your network

Kind regards

Stephen

**Comment by randall-Mysten** [comment]
Hi @Starlew77 , what was the specific error message? I don't think it means you need to upgrade your hardware. I set up a node on a laptop - I wouldn't use it for a production environment and it would probably be slow after a while unless I had a lot of memory, but you can just run a local network to try it out. There are lots of helpful people in Discord too.

**Comment by Starlew77** [comment]
Hi Randall

Unfortunately I was advised not to use discord with any machine I want to
do business on due to previous data attacks on myself 🤦‍♂️

But If you don't mind me asking what type of pc would be best for running
nodes  as its looking like I need to upgrade my current machine and what
would you say is the best security/antiviris software to install that works
well with your network and any further security measures that I van put in
place  so I can Explore building my own project with your network once this
is up and running,

Am sorry for all questions but as said im quite a novice on the tech side
amd want to make sure everything is fully secure

Kind regards

Stephen

**Comment by randall-Mysten** [comment]
Sure, no worries. It depends on what kind of node you want to run. To just try it out, you could run a local network and use the CLI to run command on a low end machine. Mac is the simplest to set up and configure if you don't use a Linux VM. Windows also works. You can run a full node on a mid range computer, we just updated suggested hardware to a 10-core CPU with 32 GB and 1 TB drive space. That is sufficient to run a node for testing but may not be for a persistent full node. If you want to run a full node on the network over time you'll need a higher end computer with 1TB+ of free storage initially. We haven't quite determined minimum and suggested reqs as we're still testing to determine that.

For security software, I have not heard of any issues with any of the most common apps/services out there. I suggest reading reviews and analysis to choose the one you use.

**Comment by Starlew77** [comment]
Hi Randall

Thats great, thank you for the information really helpful I will have a
look around I'm more familiar with windows over a mac , but simpler the
better

Thank you again for info

Steve

**Comment by Starlew77** [comment]
Hello Randall

Sorry for delay again,  I'm definitely interested in running a full node
and im meeting a potential investor tomorrow with regards to my own project
and trying to gain funding for the machine needed for this and as your prob
aware its not cheap 🤦‍♂️ ,

I did have one question with regards to the quantum computer era that's
upon us ,

 A number of chains i.e alogrand , ada  have implemented changes to there
network recently , as apparently quatum computers can cause major security
issues and can even break blockchain  , I know a number of new chains have
not compensated for this possible future problem ,   its prob a silly
question and again remember I'm not a tech guy  😀 but it's important for
my own project going forward and something I think quite important for
future success.

I hope to know how I can move forward towards the end of week,  I can
imagine how busy you are so sorry for the questions but as said I hope to
build a great working relationship with you helping to promote the sui
brand

Kind regards

Stephen

**Comment by Starlew77** [comment]
Also do you have a direct email we can liase via or does it need to come
through github 👍

**Comment by randall-Mysten** [comment]
You can use doc@mystenlabs.com
