### ISSUE TITLE
wallet constructing a move call: Error

### ISSUE THREAD

**Issue by xander988** [MystenLabs/sui#5877]
When I call the function of the smart contract, the wallet prompts "Error constructing a move call: Error: Move call argument serialization error: unknown normalized type{
"TypeParameter": 0
}”“
I guess it's a problem with the construction method of the wallet，But it is not ruled out that it is my problem. If it is, I hope to get your feedback

**Comment by randall-Mysten** [comment]
Hi @xander988 Sorry that I overlooked this issue.
