### ISSUE TITLE
Sui Code Bug or Feature Request

### ISSUE THREAD

**Issue by yoursleepin** [MystenLabs/sui#5901]
Call function
Use the "transfer" button in the window that appears immediately after creating the NFT

Expected result: expected to transfer NFT to the person
Actual Result: 
Error: RPC Error: No function was found with function name transfer for package 0x0000000000000000000000000000000000000002, module devnet_nft and function transfer} args {"arguments":["0xebd88fc303efcde8c8d3d75b4436b7a6ea28797f","0x24582393b16310e563d4be5e354affeade132c25"],"function":"transfer","gasBudget":1000,"module":"devnet_nft","packageObjectId":"0x2","typeArguments":[]}

OS: Win 10
System: intel i3, gtx 750 ti

**Comment by amnn** [comment]
The error suggests that you are trying to call a function called `devnet_nft::transfer`, but unfortunately that doesn't exist.  I looked at our source code and I couldn't find where that was being called, or any recent changes that suggest it might have existed in the past.  Can you help me out by telling me:

- Which app you were using (Our wallet, some other wallet?)
- Whether you were running on devnet or local.
- Version of the network you were running on (if local) or the date of the transaction (if on devnet).

**Comment by amnn** [comment]
Closing as inactive.
