### ISSUE TITLE
Sui Code Bug or Feature Request

### ISSUE THREAD

**Issue by yoursleepin** [MystenLabs/sui#5902]
1. Call function send coins
2. Trying to put some amount using dot

## Expected Result

I can point and send coins

## Actual Result

no dot, only comma

## System Information

* OS: Win10

**Comment by amnn** [comment]
@yoursleepin, can you share some more detailed reproduction instructions? e.g.

- Are you sending the transactions to devnet, or locally?
- What's the version of your Sui Client, and the network?
- Exact instructions for calling the function:
  - (If on devnet) address of the package
  - Name of the module
  - Name of the function
  - Source of the function
  - Arguments you passed (addresses and the values)
- A paste of the actual output

**Comment by amnn** [comment]
Closing as inactive.
