### ISSUE TITLE
[wallet adapter] The property 'wallet' in class StandardWalletAdapter is a private field cause error

### ISSUE THREAD

**Issue by boboox** [MystenLabs/sui#5938]
i am writing a demo , as non-React project, i implementing a wallet connection UI in VUE by used the wallet adapter logic in the React library as reference.
property 'wallet' in class StandardWalletAdapter is a private field
and vue is depends on 'Proxy' deeply so that i can not read some property like [name] in StandardWalletAdapter instance ,
if i do, get a TypeError: Cannot read from private field

**Comment by Jordan-Mysten** [comment]
All of the private properties are available via getters.
