### ISSUE TITLE
Flaky test `test_local_execution_with_missing_parents`

### ISSUE THREAD

**Issue by aschran** [MystenLabs/sui#5957]
It appears `test_local_execution_with_missing_parents`  in `transaction_orchestrator_tests` is flaky. Also, if I replace `#[tokio::test]` with `#[tokio::test(flavor = "current_thread", start_paused = true)]` it fails 100% of the time.

**Comment by longbowlu** [comment]
fixed in https://github.com/MystenLabs/sui/pull/5989
