### ISSUE TITLE
【TS SDK】The getEvents method is not found in ts sdk 0.15.0 

### ISSUE THREAD

**Issue by LB6264** [MystenLabs/sui#5969]
my package.json  has dependencies "@mysten/sui.js": "^0.15.0",

The getEvents method is not found in ts sdk 0.15.0 and would like to add it

**Comment by amnn** [comment]
@LB6264, I am seeing the `getEvents` function in `Provider` as part of our version 0.15.0 release (it was added at this version):

https://github.com/MystenLabs/sui/blob/releases/sui-v0.15.0-release/sdk/typescript/src/providers/provider.ts#L238

Can you double check that you have updated your dependencies after changing your version constraints?

**Comment by LB6264** [comment]
> @LB6264, I am seeing the `getEvents` function in `Provider` as part of our version 0.15.0 release (it was added at this version):
> 
> https://github.com/MystenLabs/sui/blob/releases/sui-v0.15.0-release/sdk/typescript/src/providers/provider.ts#L238
> 
> Can you double check that you have updated your dependencies after changing your version constraints?

https://github.com/MystenLabs/sui/issues/6034   
This is an issue of consent for npm 0.15.0 dependence without getEvents

**Comment by amnn** [comment]
Ah, thanks for explaining -- let me merge this issue into that one, and send this over to our SDK team.  Thanks for reporting!
