### ISSUE TITLE
Bug fix: TypeArguments and LocalTxnDataSerializer

### ISSUE THREAD

**Issue by ItasMattWebb** [MystenLabs/sui#5993]
## Steps to Reproduce Issue

Call a function that uses a typed argument, e.g.

```
    signer.signAndExecuteTransactionWithRequestType({
        kind: "moveCall",
        data: {
            packageObjectId:"0xaddd98a4a0a65523d2d89ed01a395f39aaddd920",
            module:"marketplace_nofee",
            function:"list",
            typeArguments:["0x2::devnet_nft::DevNetNFT","0x2::sui::SUI"],
            arguments:["0x544f427059cd21bd64a05ac32c272c1f2520342e","0x69ce5cbe4062948347f8b1223532f0873a0bff18",1000000000],
            gasBudget:2000,
          }
    });
```

## Expected Result
Successful transaction

## Actual Result

```
Error: Transaction failed with the following error. Error constructing a move call: Error: Unknown call arg type {
  "TypeParameter": 0
} for value "0x69ce5cbe4062948347f8b1223532f0873a0bff18" args {"arguments":["0x544f427059cd21bd64a05ac32c272c1f2520342e","0x69ce5cbe4062948347f8b1223532f0873a0bff18",1000000000],"function":"list","gasBudget":2000,"module":"marketplace_nofee","packageObjectId":"0xaddd98a4a0a65523d2d89ed01a395f39aaddd920","typeArguments":["0x2::devnet_nft::DevNetNFT","0x2::sui::SUI"]}
```

If you instantiate a raw signer like this:
```
const signer = new RawSigner(keypair, provider, new LocalTxnDataSerializer(provider));
```

Then you get the error. If you instantiate it like this:
```
const signer = new RawSigner(keypair, provider);
```
Then you don't.

Thanks to @jaredcosulich for figuring this out

## System Information
@mysten/sui.js: 0.15.0

**Comment by 3of5-IQ** [comment]
Just wondering if there is any timelines on if this is going to be looked at anytime soon? Its a pretty breaking bug for us as we went from one of the only handful of fully functional dapps on Sui to, absolutely not working and our users not being able to do anything anymore

**Comment by 666lcz** [comment]
@3of5-IQ Thanks for following up on this! I will look into this today. Meanwhile, I am curious about the reason why you can't use the `RpcTxnDataSerializer` which does not have this bug?

**Comment by 3of5-IQ** [comment]
The work around only applies to CLI and not the actual wallets themselves. This is something that is a bug with all wallets currently.

**Comment by ItasMattWebb** [comment]
Put the source code in a gist.
https://gist.github.com/ItasMattWebb/77411e3de60754e2bfbc78cabdbcd0a2

You could probably make a simpler function to test to recreate it that doesn't involve making a market. Maybe something like:

    public entry fun list<T: key + store>(
        item: T,
        ctx: &mut TxContext
    ) {
        transfer::transfer(item, tx_context::sender(ctx))
    }

**Comment by 3of5-IQ** [comment]
Hi, Just wondering if there is any more information that we can assist with providing to help increase the chances of tracking down the bug?

**Comment by 666lcz** [comment]
Sorry for the delay - As a temporary fix, I've [turned on the switch](https://github.com/MystenLabs/sui/blob/c7ff34c533a2916674eeb5fe672f52ef7fbb3138/apps/wallet/src/ui/app/ApiProvider.ts#L139-L143) to use `RpcTxnSerializer` in the Sui wallet so this issue should no longer repro on Sui wallet. 

Will put up a PR to fix the root issue by tomorrow
