### ISSUE TITLE
is sui_getEventsByTimeRange depreated?

### ISSUE THREAD

**Issue by Wangmmx** [MystenLabs/sui#5994]
Hi, I used `sui_getEventsByTimeRange` to get all events, but now it got 'Method not found' error, will it be added back? Or is there any other api to get transactions or events by time range? I can not use these like `sui_getEvents` or `sui_getTransactions` cause the page params. Thanks for your help

**Comment by amnn** [comment]
Hi @Wangmmx, I think you're seeing the same issue as in #6034, let me merge your task in there as duplicate -- I've sent that task to our SDK team to investigate.

**Comment by Wangmmx** [comment]
> Hi @Wangmmx, I think you're seeing the same issue as in #6034, let me merge your task in there as duplicate -- I've sent that task to our SDK team to investigate.

I am using the jsonRpc method only, not the SDK, so is the method `sui_getEventsByTimeRange ` deprecated for sure?

**Comment by amnn** [comment]
Ah I see, yes it is, but its functionality should still be available through `sui_getEvents`, by setting the correct query parameter.

**Comment by Wangmmx** [comment]
> Ah I see, yes it is, but its functionality should still be available through `sui_getEvents`, by setting the correct query parameter.


Yes, I read the new api, it is not exactly what I want, I hope to have an distinct number similar to the block, to correspond to the transaction one by one, because there is no such number, so I choose to use the timestamp, according to the previous api  is completely works. The transactions within a period of time can be obtained in time.If there is a period of leakage, historical transactions can also be found according to the timestamp. 

The current api is not very easy to do that, and there is no page numbers returned, The specific page number does not correspond to the transaction very well. Is there a similar api that can be used? The most matching interface is to obtain the transaction within a period of time through the timestamp, such as  `sui_getTransactionsByTimeRange`

Thank you for your reply, I hope you can consider it. I am doing wallet-related app development, now it bother me a lot,  thanks again

**Comment by amnn** [comment]
Hey @Wangmmx, got it -- let me re-open the issue, and pass it on to @patrickkuo who can advise on what options you might have with the new API.

**Comment by patrickkuo** [comment]
> @patrickkuo could you please help me with the new api?

hey @Wangmmx sorry for late reply, you should still be able to query by time range using the event query object.

```
curl --location --request POST 'https://fullnode.devnet.sui.io:443' \
--header 'Content-Type: application/json' \
--header 'Cookie: _cfuvid=ZntddrcCobdve5P6oNoHVqhpUhEOasOYOlqm7ArqOCE-1668389136663-0-604800000' \
--data-raw '{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "sui_getEvents",
  "params": [
    {
      "TimeRange": {"start_time": 1669039504014, "end_time": 1669039604014}
    },
    null,
    10,
    false
  ]
}'
```

the doc is not correct and not rendering the TimeRange query example correctly, I will put in a PR to fix that, I will also make the TimeRange `start_time` and `end_time` camelcase.

**Comment by Wangmmx** [comment]
Thanks for your reply! I will go and try it now
