### ISSUE TITLE
Sui Wallet Activities not availibale

### ISSUE THREAD

**Issue by TNDigital** [MystenLabs/sui#5999]
## Steps to Reproduce Issue
User adress for Test :  0xbba86694749896e2946435aaa5de8e26424ea216Open Sui Wallet 

1. Log on Sui Wallet
2. Go to Activities 

## Expected Result

Expected result a list of all activities (Sending/receiving, Sell, ..)

## Actual Result

Empty 

## System Information

* OS: <specify OS version> Imac

**Comment by amnn** [comment]
@TNDigital, we ran a devnet update yesterday which required a wipe of the database, this is why you aren't seeing your past transactions.  This is something that will happen quite regularly before we launch mainnet.
