### ISSUE TITLE
How to get timestamp in move contract?

### ISSUE THREAD

**Issue by guotie** [MystenLabs/sui#6002]
How to get timestamp in move contract?

**Comment by Linxi-brave** [comment]
你好，邮件已收到，将尽快处理并回复。

**Comment by amnn** [comment]
Hi @guotie, Sui doesn't currently support accessing timestamps from within Sui Move.  It's possible to access the current epoch with the following function:

```
public fun sui::tx_context::epoch(ctx: &TxContext): u64
```

But this will only have a granularity of ~24 hours, once epochs are fully implemented (the team is still working on this).

Timestamps are a commonly requested feature though, so this is on our mind.

**Comment by zengxinhai** [comment]
Time is critical, for those transactions that need to go through consensus, I think it's feasible to get the timestamp. While for single write transactions, it would not be feasible.

**Comment by Linxi-brave** [comment]
你好，邮件已收到，将尽快处理并回复。

**Comment by Linxi-brave** [comment]
你好，邮件已收到，将尽快处理并回复。
