### ISSUE TITLE
[Sui Code Bug] export declare type Ordering = 'Ascending' | 'Descending'; 

### ISSUE THREAD

**Issue by DevJihwan** [MystenLabs/sui#6004]
## Steps to Reproduce Issue
1. Call function => getTransactionsForAddress(param : publickey)
const resultOfdiget = await provider.getTransactionsForAddress(pubkey); 

**## Expected Result**
digests of publickey

e.g.
nWtT9aJrzvjWez5ca6tG6qPS6ZIeJFi8Wg5U5M2NdR4=

**## Actual Result**
{code: -32602, message: 'invalid type: string "Descending", expected a boolean at line 1 column 12'}

**the problem is** 
1. Type of Order 
 * export declare type Ordering = 'Ascending' | 'Descending';
 * (node_modules/@mysten/sui.js/dist/types/transactions.d.ts)
2. Default value of Function 
 * async getTransactionsForAddress(addressID, ordering = "Descending") {
 * node_modules/@mysten/sui.js/dist/index.mjs

**the solution is** 
change to type to boolean : false / true 

**## System Information**
* OS: mac OS monterey 12.6  
* Compiler: "@mysten/sui.js": "^0.15.0",

**Comment by amnn** [comment]
Hi @DevJihwan -- if you update to the latest version of the TS SDK (0.16.0) you will find that the API has been updated.  We had an issue (#6034) where the TS SDK didn't deploy with the new devnet version, and this seems like a symptom of that.  Thanks for reporting!

**Comment by DevJihwan** [comment]
> Hi @DevJihwan -- if you update to the latest version of the TS SDK (0.16.0) you will find that the API has been updated. We had an issue (#6034) where the TS SDK didn't deploy with the new devnet version, and this seems like a symptom of that. Thanks for reporting!

Okay! thanks. i will try it
