### ISSUE TITLE
Typescript SDK Ed25519Keypair fromSecretKey fromSeed misleading names

### ISSUE THREAD

**Issue by Eis-D-Z** [MystenLabs/sui#6006]
## Steps to Reproduce Issue

Create a new ed25519 keypair given sui-client's keystore. 
Keystore holds base64 encoded `|<scheme flag> <public key> <private key>|` with size `| <1 Byte> <32 Bytes> <32 Bytes>|` for a grand total of 65 Bytes.

```sh
# get a base64 encoded string from keystore in a shell
cat ~/.sui/sui_config/sui.keystore
```
```javascript
import { fromBase64 } from '@mysten/bcs';
import { Ed25519Keypair } from '@mysten/sui.js'

const keystore_string = "AFuC5sCeHgsThY3fPoGMZl...(redacted)";
const decoded_array_buffer = fromB64(keystore_string); // this UInt8Array
// split the keys
const decoded_array = Array.from(decoded_array_buffer);
// shift the scheme flag byte which should be 0 since it is ed25519
decoded_array.shift()
const pubkey = UInt8Array.from(decoded_array.slice(0, 32);
const privkey = UInt8Array.from(decoded_array.slice(32, 64);
// this will throw
const keypair = Ed25519Keypair.fromSecretKey(privkey);
// this will work
const keypair = Ed25519Keypair.fromSeed(privkey);
```

## Expected / Actual Result
`Ed25519Keypair.fromSecretKey(privkey);`, due to its name, is the method that was expected to work but it throws.
`Ed25519Keypair.fromSeed(privkey);`, was expected to throw, but it works

I could not find a proper input for `Ed25519Keypair.fromSecretKey` which should be 64 bytes.
64 bytes long, as far as I know, is a signature, but that should not be the case here.

## Proposal
The naming of the methods should change, and by consequence, the comments around the methods .
`Ed25519Keypair.fromSeed` --> `Ed25519Keypair.fromSecretKey`;
`Ed25519Keypair.fromSecretKey` --> Not sure

## System Information

* OS:  Ubuntu

**Comment by joyqvq** [comment]
fixed in #6798
