### ISSUE TITLE
[TS-SDK] support AND filter for getEvents

### ISSUE THREAD

**Issue by BladeRunner713** [MystenLabs/sui#6038]
Currently, we can only specify one type of search criteria. I can't use getEvents to get, for example, the event with object '0x1' sent in the last 24 hours (TimeRange type).

**Comment by amnn** [comment]
Hi @BladeRunner713, thanks for suggesting.  Let me forward this to our SDK team to prioritise.

**Comment by patrickkuo** [comment]
This is in the roadmap https://github.com/MystenLabs/sui/issues/5501

**Comment by amnn** [comment]
Excellent, thanks @patrickkuo, marking as duplicate and closing.
