### ISSUE TITLE
[explorer] Incorrectly displaying dynamic fields

### ISSUE THREAD

**Issue by awelc** [MystenLabs/sui#6067]
I have been playing with dynamic fields creation and noticed that the explorer displays dynamic fields information in what appears to be an NFT section (which should be empty as not NFTs are crated in the example I have been playing with). Here is a screenshot of the explorer window:

![image](https://user-images.githubusercontent.com/1724397/201497990-bccb2ec6-4287-4124-a50d-3c5073ab4a5e.png)

And here is the code I used to create this (parent) object (as you can see, no NFTs):

```rust
module shared_obj::shared_obj {

    struct Parent has key {
        id: sui::object::UID
    }

    struct Child has key, store {
        id: sui::object::UID
    }

    entry fun mint_obj(ctx: &mut sui::tx_context::TxContext) {
        let p = Parent { id: sui::object::new(ctx) };
        let c1 = Child { id: sui::object::new(ctx) };
        sui::dynamic_object_field::add<u64, Child>(&mut p.id, 42, c1);
        let c2 = Child { id: sui::object::new(ctx) };
        sui::dynamic_object_field::add<u64, Child>(&mut p.id, 7, c2);
        sui::transfer::transfer(
            p,
            sui::tx_context::sender(ctx)
        );
    }

}

```

**Comment by stefan-mysten** [comment]
@awelc is this still relevant (for other explorer)? If not, let's close it. Thanks
