### ISSUE TITLE
[Move] allow String, ObjectID, and other structured framework types as entypoint inputs

### ISSUE THREAD

**Issue by sblackshear** [MystenLabs/sui#609]
Today, callers can pass object ID's to entrypoints using the `address` type. This is not ideal in a number of ways:
- The entrypoint or subsequent code must convert the `address` into an object ID
- The intent of the entrypoint is less clear from the signature (especially without parameter names, which are absent in the bytecode)

To address these issues, we can relax the rules on entrypoint arguments to allow `Sui::ID::ID` in addition to parameter types. This change is also consistent with https://github.com/MystenLabs/fastnft/issues/596, which will allow returning object ID's + primitive types from entrypoints.

**Comment by tnowacki** [comment]
See https://github.com/MystenLabs/sui/issues/2049 for further discussions
