### ISSUE TITLE
Can't import sui packages into another project

### ISSUE THREAD

**Issue by maks-ivanov** [MystenLabs/sui#6096]
Since around the time narwhal got migrated into this repo (Sep 7), I cannot import anything from sui repo into my own project. This is an example of the error message.

`error: no matching package named 'sui-json-rpc' found`
`location searched: https://github.com/MystenLabs/sui?rev=42909845758c6d5f5dcdc1e376f14f4386999f48`
This seems dumb/basic but I've tried all I can think of to make this work. There must be something I don't get about how Cargo works.

cc @mwtian I've been searching for ways to DM you but you're not on discord

**Comment by mwtian** [comment]
Hi @maks-ivanov, sorry for the late reply. I have a demo rust project where importing `sui-json-rpc` seems to work: https://github.com/mwtian/hello-world.rs/blob/052a151732f5e388ff3eb848c8bf49515221d08f/Cargo.toml#L9

Can you post more details about the current configuration, ideally with a minimal Cargo.toml that can reproduce the error? Maybe `cargo clean` will help but you probably have already tried that.

**Comment by maks-ivanov** [comment]
This works, somehow! Really bizzare, I was stuck on this for a while and even had a colleague try to do it instead. Perhaps this was a blip in github indexing, though seems unlikely. Anyway, thanks

**Comment by mwtian** [comment]
Great to hear it works now!
