### ISSUE TITLE
How to review package source code on Sui Explorer?

### ISSUE THREAD

**Issue by jasonintju** [MystenLabs/sui#6103]
Hi,
I'm a new comer to Move & Sui. I used to write solidity on Eth. I want to know how to review  the package source code other developers wrote on the Sui Explorer?  Like the source code of solidity smart contracts on the Ethereum Blockchain Explorer.
Many thanks.

**Comment by PaulFidika** [comment]
This is a good feature request; I think Sui only stores the module bytecode. Aptos allows you to optionally include artifacts with your deployment, including your source-code. I'll include this in my feature-tracking list:

https://www.notion.so/Sui-Improvement-Proposals-320851e831564d938b21c717a00058ef

**Comment by jasonintju** [comment]
> This is a good feature request; I think Sui only stores the module bytecode. Aptos allows you to optionally include artifacts with your deployment, including your source-code. I'll include this in my feature-tracking list:
> 
> https://www.notion.so/Sui-Improvement-Proposals-320851e831564d938b21c717a00058ef

looking forward to it
