### ISSUE TITLE
Sui documentation - Explore Sui section

### ISSUE THREAD

**Issue by kristaki90** [MystenLabs/sui#6143]
In the Sui Documentation, in the ["Explore Sui"](https://docs.sui.io/devnet/explore) section the [Tic Tac Toe tutorial](https://docs.sui.io/devnet/explore/tutorials) link is broken.

I get "That page can't be found" error.

**Comment by randall-Mysten** [comment]
Hi @kristaki90 Thanks for reporting this, we'll get it fixed shortly. Cheers!

**Comment by randall-Mysten** [comment]
Hi @kristaki90 I see the link working in both branches. Perhaps a caching issue...please let me know if you still see it not working.
