### ISSUE TITLE
Doc content request on Transactions

### ISSUE THREAD

**Issue by jackcpku** [MystenLabs/sui#6166]
**New**

Hello, I'm currently investigating into the core of SUI. What I want to find out is how `transactionDigest` is computed (since it's used as a random seed when creating a new Object). I didn't find anything about it in the docs, could you provide an explanation?

Btw, it would be nice if you add a detail page on how transactions are consumed from beginning to end, it really helps people understand the big picture.

**Comment by randall-Mysten** [comment]
Hi @jackcpku Thanks for filing this issue. Totally agree, I've added this to the queue. There is some info about this in https://docs.sui.io/learn/objects
