### ISSUE TITLE
[move] Support U256

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#618]
Track the support for U256 per this [comment](https://github.com/MystenLabs/fastnft/pull/616#issuecomment-1056026518)

**Comment by bholc646** [comment]
Do we still have work to do here, or is Aptos and other peeps in the community doing all of this work? @sblackshear @tnowacki

**Comment by tnowacki** [comment]
We have not heard anything from the Move contributor side of things in a while, so not sure

**Comment by a-trepalin** [comment]
Hi! Move merged u256 support: https://github.com/move-language/move/pull/547

**Comment by oxade** [comment]
> Hi! Move merged u256 support: [move-language/move#547](https://github.com/move-language/move/pull/547)

Yes, we're aware. Support in Sui is coming soon.
See the PR: https://github.com/MystenLabs/sui/pull/5659

**Comment by oxade** [comment]
Most of the support will come in this PR
https://github.com/MystenLabs/sui/pull/5659
