### ISSUE TITLE
Where is Sui Wallet SDK？

### ISSUE THREAD

**Issue by e274426380** [MystenLabs/sui#6187]
I didn't find anything in the documentation about how to connect the wallet on the front end.
For example, how do I use the relevant methods in window.suiWallet?
The documentation only says how to use the SuiWallet and not how to access it

**Comment by bruceeewong** [comment]
You can try our Suiet Wallet Kit, connect wallets in secs: https://kit.suiet.app/
Or use official Sui Wallet-Adapter, no docs yet as far as I know: https://github.com/MystenLabs/sui/tree/main/sdk/wallet-adapter

**Comment by jaredcosulich** [comment]
Yes, there's also https://ethoswallet.xyz/dev

**Comment by e274426380** [comment]
> You can try our Suiet Wallet Kit, connect wallets in secs: https://kit.suiet.app/ Or use official Sui Wallet-Adapter, no docs yet as far as I know: https://github.com/MystenLabs/sui/tree/main/sdk/wallet-adapter

Sorry, I'm a Vue developer and don't seem to be able to use these React dependencies. :(

**Comment by Jordan-Mysten** [comment]
@e274426380 We don't currently have a dedicate Vue SDK, or any immediate plans to create one. The core Wallet Adapter packages are usable in any JavaScript project though, so you should be able to use those: https://github.com/MystenLabs/sui/tree/main/sdk/wallet-adapter

**Comment by e274426380** [comment]
> @e274426380 We don't currently have a dedicate Vue SDK, or any immediate plans to create one. The core Wallet Adapter packages are usable in any JavaScript project though, so you should be able to use those: https://github.com/MystenLabs/sui/tree/main/sdk/wallet-adapter
The core Wallet Adapter packages's README makes extensive use of react dependencies and I can't just use it via JS

**Comment by Jordan-Mysten** [comment]
We have recently introduced Sui Wallet Kit, which should make it easy to connect to wallets from React: https://github.com/MystenLabs/sui/tree/main/sdk/wallet-adapter/packages/wallet-kit

For other non-React libraries and frameworks, we're not planning on supporting them in the near-term, but we're looking into generalizing the underlying logic for our UI layer so that it can be used in other frameworks easily: https://github.com/MystenLabs/sui/pull/6577

**Comment by jaredcosulich** [comment]
We've recently released a vue-compatible NPM package if it's helpful:

https://docs.ethoswallet.xyz/example-vue-app

**Comment by e274426380** [comment]
@jaredcosulich this is a good news. I will test the use of this npm package as soon as I can and try to access my project

**Comment by e274426380** [comment]
> We've recently released a vue-compatible NPM package if it's helpful:
> 
> https://docs.ethoswallet.xyz/example-vue-app

sorry, I have added all the code from the Example Vue App into my Vue project and the following error is generated:
```
EthosConnectPlugin.ts:16 Uncaught ReferenceError: exports is not defined
    at node_modules/ethos-connect-vue/dist/index.js (EthosConnectPlugin.ts:16:40)
    at __init (chunk-MALWHLUZ.js?v=16484c4c:45:50)
    at dep:ethos-connect-vue:1:16
```
EthosConnectPlugin.ts:16:40: 
```
// The Install function used by Vue to register the plugin
export const EthosConnectPlugin: Plugin = {
    install(app: App, options: EthosConfiguration) {
        // makes ethosConfig available in your .vue file with const config = inject(VarNames.EthosConfig)
        app.provide(VarNames.EthosConfig, options)

        // register global components, so the NPM package consumers can use it in their app
        app.component('EthosConnectProvider', EthosConnectProvider)
        app.component('AddressWidget', AddressWidget)
    }
}
```

**Comment by jaredcosulich** [comment]
Can you email support@ethoswallet.xyz so we can help you debug?

**Comment by reslear** [comment]
any news about vue support?

**Comment by petvaizAkhtar** [comment]
Good

**Comment by williamrobertson13** [comment]
We're going to be working on a new-and-improved dApp-kit (https://sdk.mystenlabs.com/dapp-kit) in the new year that'll provide better support for non-React UI libraries like Vue. Thanks for your patience as we work on this :)
