### ISSUE TITLE
CLI: add --bcs flag to `sui client object`

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#6220]
Add --bcs flag to `sui client object` to return the bsc serialized version of the object struct.

Code pointer: [https://github.com/MystenLabs/sui/blob/616d2284a793f78d09672f7f83713f9bd8e1f731/crates/sui/src/client_commands.rs#L1045-L1047|https://github.com/MystenLabs/sui/blob/616d2284a793f78d09672f7f83713f9bd8e1f731/crates/sui/src/client_commands.rs#L1045-L1047|smart-link]

we can call {{bcs::to_bytes}} here to print out the bcs encoded struct if {{--bcs}} flag is true

context: [https://mysten-labs.slack.com/archives/C043CJH1HCK/p1668812891540819|https://mysten-labs.slack.com/archives/C043CJH1HCK/p1668812891540819|smart-link]

**Comment by xydas97** [comment]
https://github.com/MystenLabs/sui/pull/6737
