### ISSUE TITLE
[TypeScript SDK] Fix parseStructTypeTag

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#6223]
Address todo item in https://github.com/MystenLabs/sui/blob/4f98acd4bc18abb79826053d2252471d56236e08/sdk/typescript/src/signers/txn-data-serializers/type-tag-serializer.ts#L54-L55

**Comment by doperogue** [comment]
@666lcz  Can you give an example of STRUCT_TYPE_TAG_REGEX, also one example where the "parseStructTypeTag" function is failing?

**Comment by 666lcz** [comment]
@doperogue good question!

This task is basically to re-imlepment the [rust logic](https://github.com/diem/diem/blob/70beea5d804c4e6f637edd5d779b72f2deff44e1/language/move-core/types/src/parser.rs#L256) with TS.

To understand how it works, the easiest way is to add a `console.log` in this [line](https://github.com/MystenLabs/sui/blob/4f98acd4bc18abb79826053d2252471d56236e08/sdk/typescript/src/signers/txn-data-serializers/type-tag-serializer.ts#L49)  and run this [test](https://github.com/MystenLabs/sui/blob/4f98acd4bc18abb79826053d2252471d56236e08/sdk/typescript/test/e2e/txn-serializer.test.ts#L91-L102)(feel free to comment other tests in this file) by 

```
// in terminal 1
pnpm sdk prepare:e2e

// in terminal 2
cd sdk/typescript
vitest 

```

**Comment by 666lcz** [comment]
Fixed in https://github.com/MystenLabs/sui/pull/7055
