### ISSUE TITLE
Investigate time spent after restart in sui / narwhal

### ISSUE THREAD

**Issue by mwtian** [MystenLabs/sui#6227]
## Steps to Reproduce Issue

When a sui-node has ran for sometime, after restart narwhal in the node does not immediately start catching up on certificates. e.g.
<img width="1609" alt="Screenshot 2022-11-20 at 10 22 47 AM" src="https://user-images.githubusercontent.com/81660174/202919150-4d1dad25-6cab-4700-9085-5089c06ada6d.png">

This makes the narwhal catch up after restart much slower than it should. We need to eliminate the inefficiencies here.

## Expected Result

After a node restarts, narwhal soon starts catching up.

## Actual Result

After a node restarts, it seems to be stuck for >20 min before starting to catch up.

**Comment by mwtian** [comment]
CPU profile after a node restarts before it started to catch up:
![perf-dwarf](https://user-images.githubusercontent.com/81660174/202919676-520c3289-9c70-41fd-8097-b618cae70f85.svg)
Only ~110 samples were taken in 10s, so the profile may not be accurate numerically. But we can look into some of the notable usages and check if they are on the critical path of node restart, and how they block narwhal catch up.

**Comment by stefan-mysten** [comment]
@mwtian I assume this is not relevant anymore, so closing it.
