### ISSUE TITLE
error: no matching package named `sui-sdk` found

### ISSUE THREAD

**Issue by huyker** [MystenLabs/sui#6240]
i tried to install dependencies following file: https://docs.sui.io/build/rust-sdk.

cargo version: 1.61.0

But when i add 
```

[dependencies]
sui-sdk = { git = "https://github.com/MystenLabs/sui" }

```

then run cargo build. That showing error : 

```
Updating git repository `https://github.com/MystenLabs/sui`
error: no matching package named `sui-sdk` found
location searched: https://github.com/MystenLabs/sui
required by package `pro v0.1.0 (/home/huynq/Desktop/2022/sui/rust2/pro)
```
please help me install this library. thanks

**Comment by randall-Mysten** [comment]
Hi @huyker Sorry this is not working for you. Mind trying it with Rust 1.65 against the Devnet branch?

**Comment by huyker** [comment]
oh nice! That's worked. Thank you
