### ISSUE TITLE
WIP: Authority Sidecar Blurb

### ISSUE THREAD

**Issue by oxade** [MystenLabs/sui#629]
Idea dump: very early draft

![Screen Shot 2022-03-03 at 02 06 27](https://user-images.githubusercontent.com/93547199/156516416-8f401a91-2494-4ace-b72f-c9d00403e455.png)

It behooves us to keep our authority light and simple as possible.
As we add benchmarking, and read APIs, cross-authority communication, it's critical that we be very selective about what goes into the core authority and if possible, offload as much to the periphery as possible.

I recommend taking some inspiration from the sidecarA (https://www.abhishek-tiwari.com/a-sidecar-for-your-service-mesh/) (https://docs.microsoft.com/en-us/azure/architecture/patterns/sidecar) pattern which allows us do the following:

Short term gains:
1. Benchmarking
2. Serve reads more efficiently by routing read requests away from authority core
3. Handling previously seen tx requests (by caching)
4. Logging

Other benefits:
Reconfiguration, Discoverability, Observability, DoS mitigation

**Short term:**
1. Benchmarking
We would like to benchmark the authorities locally and measure the effects of changes such as shared objects, storage design, etc.
When benchmarking the network as a whole and implementing our Sync feature, we might want to see the effects of taking nodes of different stakes down. Having the circuit breaker allows us simulate a network partition to an authority.

2. Serve reads more efficiently by routing read requests away from authority core
This is straightforward. Authorities should not be dealing with `handle_account_info_request`, `handle_object_info_request`, `handle_transaction_info_request`. These can be intercepted early on by the sidecar.

3. Handling previously seen tx requests (by caching)
As before, we can leverage idempotency and filter previously seen TXes in the sidecar

4. Logging

**Comment by velvia** [comment]
@oxade some designs related to this:
See slide 14
https://docs.google.com/presentation/d/1JEgrURBcQeoDAXtz5xfWEZqQ2vFcyMv5chtapwJyNVM/edit#slide=id.g11aa2132e58_1_68
