### ISSUE TITLE
Sui doc content issue or request for sui::groth16

### ISSUE THREAD

**Issue by jackcpku** [MystenLabs/sui#6317]
**New**.

Please provide more docs / use cases on sui::groth16 , how it works with, say, snarkjs, etc.

**Comment by randall-Mysten** [comment]
Hi @jackcpku Great timing: https://github.com/MystenLabs/sui/pull/6170/files#diff-e6245ac0fde64241892dd99341d0d5b0d175fe86d67bc676014ec0e95ef2dd17

**Comment by chrisyy2003** [comment]
hi, how to genratue PreparedVerifyingKey parameter and proofpoint? with snarkjs or gnarks
