### ISSUE TITLE
[Discuss] Supporting `bcs::from_bytes(..)` in `std::bcs`

### ISSUE THREAD

**Issue by xiyu1984** [MystenLabs/sui#6340]
As only primitive or object types are supported for parameters of an entry function, serialization and deserialization may be useful in some cases. 
I found that the [bcs](https://github.com/diem/bcs/blob/master/src/de.rs) lib supports encoding and decoding.
And we can serialize user-defined data structures through the TypeScript '@mysten/bcs'.

So I'm wondering if @MystenLabs has the plan to support `bcs::from_bytes(...)` in [std::bcs](https://github.com/MystenLabs/sui/blob/main/crates/sui-framework/deps/move-stdlib/sources/bcs.move) of Sui Move?

**Comment by tnowacki** [comment]
`sui::bcs` supports some of the use cases you are after

**Comment by xiyu1984** [comment]
> `sui::bcs` supports some of the use cases you are after

Cool~ This [test](https://github.com/MystenLabs/sui/blob/21c26ce6a5d4e3448abd74323e3164286d3deba6/crates/sui-framework/sources/bcs.move#L392) really makes sense~
