### ISSUE TITLE
[Bug] Deleted objects events are not emitted consistently

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#6361]
this is where we handle deleted object https://github.com/MystenLabs/sui/blob/6fb64397f73606b142de90e01478cda15ceb0522/crates/sui-types/src/temporary_store.rs#L172-L194
If the deleted object is a coin, it will only emit a balance change event but not delete object event…. it should emit both

**Comment by stefan-mysten** [comment]
@666lcz after a brief search, I assume that this is not relevant anymore.
