### ISSUE TITLE
[TS SDK] - Add dynamic field support 

### ISSUE THREAD

**Issue by patrickkuo** [MystenLabs/sui#6373]
`sui_getDynamicFields` and `sui_getDynamicFieldObject` is added in this PR https://github.com/MystenLabs/sui/pull/5882

**Comment by xiaozzz** [comment]
please add. im stuck on it.

**Comment by xiaozzz** [comment]
im still waiting for it. any estimate time?

**Comment by kukabi** [comment]
Looking forward to this.
