### ISSUE TITLE
[ts sdk] react lib that bundles sui ts sdk cannot be used by NextJS@13 app

### ISSUE THREAD

**Issue by bruceeewong** [MystenLabs/sui#6377]
## Steps to Reproduce Issue

The context here is that I am making a react hook lib (using Vite for bundling) which depends on sui ts sdk "@mysten/sui.js". 

When I try NextJS project (SSR with webpack bundling) to use my bundled lib, errors show up at the codes of sui ts sdk that bundled in.

![WX20221124-120046@2x](https://user-images.githubusercontent.com/17715132/203836276-d47c52aa-46cf-4dc3-9d59-f07160d63bd2.png)

Here are steps to reproduce:

environments:
- node v16.14.2
- "vite": "^3.2.3"
- "@mysten/sui.js": "^0.17.1"
- "next": "13.0.5"

1. clone my mini repo: git clone https://github.com/bruceeewong/suisdk-vite-bundle.git
2. at root path of the project, use `pnpm install` to install dependencies
3. at root path of the project, use `pnpm build` to build dist
4. `cd ./with-nextjs`  and use `pnpm dev` to launch the NextJS app.
5. visit `http://localhost:3000` at browser and errors should pop out.

Actually I tried that directly use '@mysten/sui.js' in NextJS and it works fine. So I wonder what problem would there be if '@mysten/sui.js' is bundled by vite. 

Any idea with this workaround? Thank you!

More screenshots:

Implementation for the react lib:

1 - wrap JsonRpcProvider with react hook
![WX20221124-114020](https://user-images.githubusercontent.com/17715132/203838307-a1c78e88-0c97-4a67-9a3e-76f16f63cc32.png)

2 - export only this hook
![WX20221124-114052](https://user-images.githubusercontent.com/17715132/203838388-d1e8b1d2-4992-4c35-8f03-63b8b6aff459.png)

3 - bundle lib with vite as npm package

![WX20221124-114146](https://user-images.githubusercontent.com/17715132/203838517-aa548f94-1352-4df3-a0d4-dda63f5534ec.png)

Usage for NextJS app:

![WX20221124-114342](https://user-images.githubusercontent.com/17715132/203842495-d8d1a198-c296-4a19-8444-59045a2b7957.png)

Error:

![WX20221124-114424](https://user-images.githubusercontent.com/17715132/203842558-769ee018-f50d-4003-af84-35dd78d7d814.png)

## Expected Result

"@mysten/sui.js" ts sdk should work fine after bundled by Vite as React component library for SSR app project like NextJS.

## Actual Result

When I try NextJS@13 project to use my bundled lib, errors show up at the codes of '@mysten/sui.js' that bundled in.

![WX20221124-120046@2x](https://user-images.githubusercontent.com/17715132/203836276-d47c52aa-46cf-4dc3-9d59-f07160d63bd2.png)

## System Information

* OS: macOS 12.3.1
* Compiler: 
- node v16.14.2
- "vite": "^3.2.3"

**Comment by bruceeewong** [comment]
Any idea here?

**Comment by bruceeewong** [comment]
For NextJS@13 project, if I import JsonRpcProvider directly from `@mysten/sui.js`, I get errors too.

```tsx
import {JsonRpcProvider} from '@mysten/sui.js'
import { useEffect } from 'react'

export default function App({ Component, pageProps }: AppProps) {
  useEffect(() => {new JsonRpcProvider()}, [])
  return (
      <Component {...pageProps} />
  )
}
```

errors:

```
SyntaxError: Named export 'sha3_256' not found. The requested module 'js-sha3' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'js-sha3';
const { sha3_256 } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:193:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15) {
  page: '/'
}
```

**Comment by James0x9034** [comment]
the same issue

**Comment by 666lcz** [comment]
Sorry for the delay in reply. This is caused by the usage of `cross-fetch` package in the TS-SDK, will put up a fix by tomorrow.
