### ISSUE TITLE
Thoughts: Why Does assert! need a u64 error-code?

### ISSUE THREAD

**Issue by PaulFidika** [MystenLabs/sui#6390]
`assert!(false, error_code)` requires a u64 as its second-argument (error-code); but why? I think a u8 or a u16 would suffice; there's no way a dev is going to specify more than 255 or 65k error codes in a single module. This also forces all error codes to be like

`const EERROR_NAME: u64 = 0;`

so every error-code is now using up 8 bytes of storage when realistically it could be using up 1. Might help to reduce the size of the compiled code some.

**Comment by PaulFidika** [comment]
Looking at some much older code, I can see that some modules used error codes like:

`const ELENGTH: u64 = 0x20001;`

I'm not sure why though. I'm guessing each module in the Move core was going to get their own error-code space.

**Comment by tnowacki** [comment]
No real way of changing this now, but we are utilizing the bits more 
#16842
