### ISSUE TITLE
Issue building Sui

### ISSUE THREAD

**Issue by Night-Traders-Dev** [MystenLabs/sui#6416]
I've tried to install build Sui using both the preferred method in the documentation and cargo build with these errors 

![Screenshot_20221128-101308_Termux](https://user-images.githubusercontent.com/80061955/204313273-c5c12a38-3452-4974-bd0f-713f34607879.jpg)
![Screenshot_20221128-101514_Termux](https://user-images.githubusercontent.com/80061955/204313427-a23c9881-577b-4781-9ca5-0a0f38e97983.jpg)

**Comment by sean0fire** [comment]
maybe you should reload

**Comment by stefan-mysten** [comment]
@Night-Traders-Dev this has likely been fixed since filing the issue, so I will close it. Feel free to create a new issue if you still encounter problems when installing Sui.
