### ISSUE TITLE
RPC sui_getObjectsOwnedByAddress would be  very slow

### ISSUE THREAD

**Issue by 0x6368616e67** [MystenLabs/sui#6448]
`sui_getObjectsOwnedByAddress ` as it says "Return the list of objects owned by an address"

but if one has a lot of objects, such as 1M object, the RPC will return after a long time, or even tigger the "timeout" of RPC gateway.

so , why 1M object, for example ：small-amount transfer . or a message like dapp use a object to store so much messages.

what if the RPC support a filter condition param.  for example :"type": "0x2::coin::Coin<0x2::sui::SUI>", 
and "index:1 count: 100" etc.

**Comment by patrickkuo** [comment]
related issue - https://github.com/MystenLabs/sui/issues/6370

**Comment by patrickkuo** [comment]
also we are adding dedicated APIs for coins https://github.com/MystenLabs/sui/pull/6532
