### ISSUE TITLE
[Proposal]: Replace SQLite With A Distributed Database

### ISSUE THREAD

**Issue by fenghaojiang** [MystenLabs/sui#6511]
### Proposal: 
Replacing SQLite with a distributed database.
 
### Details 
Our team has been running Sui's full node for a couple of weeks. We notice that Sui uses SQLite to store all the events' data. After a deep investigation of Sui and SQLite, we think SQLite should not be used in a system designed for high concurrency and large throughput.

#### 1. Reason 1: 
SQLite can be easily corrupted when facing high concurrency. SQLite allows simultaneous access from different applications. And where there is heavy use of the SQLite database, then there are hefty chances for database corruption.
Similarly, regular use of the SQLite database leads to a large amount of data. And, when the size increases over the well-defined limit, it ends up in error SQLite Database Disk Image Is Malformed.

This problem occurs when the events.db file grows to about a size of 25G. And since Sui is designed for high concurrency and huge throughput, I think the size of events.db would grow quickly and reach the critical intolerable point in the early stage of the block chain. To avoid this situation, a distributed database that can scale infinitely horizontally may be a good option for Sui.

sqlite> select count(*) from events where object_type like '%coin';
Error: database disk image is malformed

#### 2. Reason 2: 
What's more, reading the database events.db in the early stage of Sui with high concurrency may lead to high CPU load and even with 1 second's interval, the latency could be unacceptable too. Here's my benchmark.

##### Environment：
- OS：Ubuntu
- Core：4 Cores
- Ram：16 G
- Size of events.db When running the test: 15G

##### Test Source Code: 
SQL Example 1: 
```sql
select * from events where event_type = 8 order by seq_num desc limit 0, 10;
```
Benchmark source code: 

```go
package main

import (
    "fmt"
    "net/http"
    "time"

    _ "net/http/pprof"

    "github.com/glebarez/sqlite"
    "gorm.io/gorm"
)

type EventEnvelope struct {
    Timestamp     uint64 `gorm:"column:timestamp"`
    SeqNum        uint64 `gorm:"column:seq_num"`
    EventNum      uint64 `gorm:"column:event_num"`
    TxDigest      string `gorm:"column:tx_digest"`
    EventType     uint64 `gorm:"column:event_type"`
    PackageID     string `gorm:"column:package_id"`
    ModuleName    string `gorm:"column:module_name"`
    Function      string `gorm:"column:function"`
    ObjectType    string `gorm:"column:object_type"`
    ObjectID      string `gorm:"column:object_id"`
    Fields        string `gorm:"column:fields"`
    MoveEventName string `gorm:"column:move_event_name"`
    Contents      []byte `gorm:"column:contents"`
    Sender        []byte `gorm:"column:sender"`
    Recipient     string `gorm:"column:recipient"`
}

func main() {
    dataDir := "/datadir/events.db"
    database, err := gorm.Open(sqlite.Open(dataDir), &gorm.Config{})
    if err != nil {
        fmt.Println(err.Error())
        panic(err)
    }
    go func() {
        for {
            select {
            case <-time.After(1 * time.Second):
                //new object events
                var events []EventEnvelope
                err := database.Table("events").Select("*").Where("event_type = ?", 8).Order("seq_num desc").Offset(0).Limit(10).Scan(&events).Error
                if err != nil {
                    fmt.Println(err.Error())
                } else {
                    for i := range events {
                        fmt.Println(fmt.Sprintf("new object events %+v", events[i]))
                    }
                }
            }
        }
    }()
    http.ListenAndServe(":9999", nil)
}
```

##### Result: 

- SQLite Latency After Runing about 30 mins: 
The latency of simple SQL is growing gradually.
```shell
[431056.581ms] [rows:10] SELECT * FROM events WHERE event_type = 8 ORDER BY seq_num desc  LIMIT 10
[594497.039ms] [rows:10] SELECT * FROM `events` WHERE event_type = 8 ORDER BY seq_num desc  LIMIT 10
[745329.380ms] [rows:10] SELECT * FROM `events` WHERE event_type = 8 ORDER BY seq_num desc  LIMIT 10
[841112.787ms] [rows:10] SELECT * FROM `events` WHERE event_type = 8 ORDER BY seq_num desc  LIMIT 10
[963404.916ms] [rows:10] SELECT * FROM `events` WHERE event_type = 8 ORDER BY seq_num desc  LIMIT 10
[1054361.504ms] [rows:10] SELECT * FROM `events` WHERE event_type = 8 ORDER BY seq_num desc  LIMIT 10
```

- Debug Profile of pprof:
https://github.com/fenghaojiang/sui-benchmark/blob/main/benchmarkresult.svg

- Top 20 Result of pprof:
```shell
(pprof) top20
Showing nodes accounting for 15.50s, 96.69% of 16.03s total
Dropped 63 nodes (cum <= 0.08s)
Showing top 20 nodes out of 34
      flat  flat%   sum%        cum   cum%
     7.56s 47.16% 47.16%     14.67s 91.52%  modernc.org/sqlite/lib.Xsqlite3WalFindFrame
     2.90s 18.09% 65.25%      6.82s 42.55%  modernc.org/libc.AtomicLoadNUint16
     2.11s 13.16% 78.42%      2.13s 13.29%  sync.(*Mutex).Unlock (inline)
     1.78s 11.10% 89.52%      1.78s 11.10%  sync.(*Mutex).Lock (inline)
     0.73s  4.55% 94.07%      0.73s  4.55%  runtime/internal/syscall.Syscall6
     0.11s  0.69% 94.76%      0.11s  0.69%  modernc.org/libc.PostDecInt32 (inline)
     0.10s  0.62% 95.38%     16.01s 99.88%  modernc.org/sqlite/lib.Xsqlite3VdbeExec
     0.07s  0.44% 95.82%      0.12s  0.75%  modernc.org/sqlite/lib.walHashGet
     0.05s  0.31% 96.13%      0.10s  0.62%  runtime.exitsyscall
     0.02s  0.12% 96.26%     15.65s 97.63%  modernc.org/sqlite/lib.getAndInitPage
     0.01s 0.062% 96.32%      0.82s  5.12%  modernc.org/libc.Xread
     0.01s 0.062% 96.38%      0.12s  0.75%  modernc.org/sqlite/lib.Xsqlite3BtreeNext
     0.01s 0.062% 96.44%     15.70s 97.94%  modernc.org/sqlite/lib.Xsqlite3BtreeTableMoveto
     0.01s 0.062% 96.51%     15.66s 97.69%  modernc.org/sqlite/lib.moveToChild
     0.01s 0.062% 96.57%     15.54s 96.94%  modernc.org/sqlite/lib.readDbPage
     0.01s 0.062% 96.63%      0.74s  4.62%  syscall.RawSyscall6
     0.01s 0.062% 96.69%      0.85s  5.30%  syscall.Syscall
         0     0% 96.69%     16.01s 99.88%  database/sql.(*Rows).Next
         0     0% 96.69%     16.01s 99.88%  database/sql.(*Rows).Next.func1
         0     0% 96.69%     16.01s 99.88%  database/sql.(*Rows).nextLocked
```

As we can see from the result, the latency of small reads and even if I set a longer time interval, the situation is still unacceptable. 

### Conclusion: 
Since SQLite shares so many things in common with MySQL & PostgreSQL, I think it's easy to change the database source from SQLite to distributed database using MySQL or PostgreSQL protocol. 
- MySQL Protocol: [TiDB](https://github.com/pingcap/tidb) & [StarRocks ](https://github.com/StarRocks/StarRocks)
- PostgreSQL Protocol: [Cockroachdb](cockroach)

All benchmark source code can be found on my github repository: https://github.com/fenghaojiang/sui-benchmark

**Comment by amnn** [comment]
Hi @fenghaojiang, thanks for the report!  I notice that almost half your time seems to be spent in `WalFindFrame`, which suggests that you're seeing a case of sqlite's writeahead log growing without ever being truncated.  Future reads will then need to scan the WAL to look for updated pages, which is going to slow things down the bigger the WAL gets, and this could also be responsible for the corruption issues.

We recently noticed a similar behaviour ourselves and landed #6169.  I notice your benchmark repo is fairly new, but you have been running a fullnode for a couple of weeks, so I wanted to check whether your findings can be reproduced in the presence of that change?

I believe it is part of our most recent release (`devnet-0.17.0`).

**Comment by sblackshear** [comment]
CC @sadhansood

**Comment by fenghaojiang** [comment]
> Hi @fenghaojiang, thanks for the report! I notice that almost half your time seems to be spent in `WalFindFrame`, which suggests that you're seeing a case of sqlite's writeahead log growing without ever being truncated. Future reads will then need to scan the WAL to look for updated pages, which is going to slow things down the bigger the WAL gets, and this could also be responsible for the corruption issues.
> 
> We recently noticed a similar behaviour ourselves and landed #6169. I notice your benchmark repo is fairly new, but you have been running a fullnode for a couple of weeks, so I wanted to check whether your findings can be reproduced in the presence of that change?
> 
> I believe it is part of our most recent release (`devnet-0.17.0`).

Problem still exists in recent release `devnet-0.17.0`

**Comment by fenghaojiang** [comment]
`WAL checkpoint` should be added while using SQLite.

**Comment by amnn** [comment]
Thanks for clarifying @fenghaojiang, sorry to hear you're still hitting against this issue on the latest version.  Can you confirm that the issues you're seeing when running a fullnode on 0.17.0 are that the WAL is growing without bound? (This is to know whether #6169 worked but you're facing a different problem, or the fix in #6169 didn't work).

> `WAL checkpoint` should be added while using SQLite.

This is what #6169 is [supposed to do](https://github.com/MystenLabs/sui/pull/6169/files#diff-e41094edab7b4639eefb8e9d6048af43806b733506986ff63a65446eb5b62cccR151): run a `PRAGMA wal_checkpoint(TRUNCATE)` every 5 minutes to force the log to flush and truncate down to zero bytes before resuming, as long as there are no active readers.  It should also block new read requests until the checkpoint finishes.

It also intends to set-up auto-checkpointing once the WAL grows larger than 4KB * 400 = 16KiB, but this only works if there are no active transactions reading from the WAL, and doesn't block new readers.

**Comment by fenghaojiang** [comment]
> Thanks for clarifying @fenghaojiang, sorry to hear you're still hitting against this issue on the latest version. Can you confirm that the issues you're seeing when running a fullnode on 0.17.0 are that the WAL is growing without bound? (This is to know whether #6169 worked but you're facing a different problem, or the fix in #6169 didn't work).
> 
> > `WAL checkpoint` should be added while using SQLite.
> 
> This is what #6169 is [supposed to do](https://github.com/MystenLabs/sui/pull/6169/files#diff-e41094edab7b4639eefb8e9d6048af43806b733506986ff63a65446eb5b62cccR151): run a `PRAGMA wal_checkpoint(TRUNCATE)` every 5 minutes to force the log to flush and truncate down to zero bytes before resuming, as long as there are no active readers. It should also block new read requests until the checkpoint finishes.
> 
> It also intends to set-up auto-checkpointing once the WAL grows larger than 4KB * 400 = 16KiB, but this only works if there are no active transactions reading from the WAL, and doesn't block new readers.

Maybe I misuse the SQLite server. I make a new process to read data from SQLite `events.db` while Sui node is processing write & read.

**Comment by amnn** [comment]
Ah okay!  Yes, can you try running it for some time without the separate process to see if it helps?

If it does then we can look into how you can safely extract data from the DB while the fullnode is running.  It could be that you have a particularly long-lived read transaction in that separate process and because it is around, the WAL never gets truncated.

**Comment by fenghaojiang** [comment]
> Ah okay! Yes, can you try running it for some time without the separate process to see if it helps?
> 
> If it does then we can look into how you can safely extract data from the DB while the fullnode is running. It could be that you have a particularly long-lived read transaction in that separate process and because it is around, the WAL never gets truncated.

Really appreciated for your help. But If I want to write my own SQL, are there any other ways to connect the SQLite DB?

**Comment by amnn** [comment]
There should be a way to do it without leaking the WAL -- my suggestion was a step to help confirm the diagnosis.  If the full node runs well (i.e. the WAL remains bounded) when there isn't another process making reads to the DB, then we know that this is what we should focus on solving.

**Comment by zjshen14** [comment]
More info about "Avoiding Excessively Large WAL Files": https://www.sqlite.org/wal.html

**Comment by fenghaojiang** [comment]
> Would suggestion in "Avoiding Excessively Large WAL Files": https://www.sqlite.org/wal.html help? This WAL issue caused us expensive disk usage.

It helps. Thank you.
