### ISSUE TITLE
[TS-SDK] - Some new types are missing from TypeTagSerializer

### ISSUE THREAD

**Issue by patrickkuo** [MystenLabs/sui#6516]
TypeTagSerializer should support all types in TypeTag

Code pointers:
https://github.com/MystenLabs/sui/blob/1c64f63ca84dcbe979c32333c66bbfccf324a79e/sdk/typescript/src/signers/txn-data-serializers/type-tag-serializer.ts#L10-L47

https://github.com/MystenLabs/sui/blob/1c64f63ca84dcbe979c32333c66bbfccf324a79e/sdk/typescript/src/types/sui-bcs.ts#L223-L234

**Comment by oxade** [comment]
Can the assignee please ensure we're not missing other types in this part of the codebase

**Comment by oxade** [comment]
Merged
