### ISSUE TITLE
[Question] sui_config/sui.keystore

### ISSUE THREAD

**Issue by a6-dou** [MystenLabs/sui#6530]
is the sui.keystore encrypted somehow as it's not pain text nor base64?

**Comment by joyqvq** [comment]
it is a base64 encoded string of value `flag || pubkey || privkey`, unencrypted for now

**Comment by a6-dou** [comment]
Thanks! it's clear in the code.

**Comment by a6-dou** [comment]
i was unaware about the flag been serialised and that's what was giving me unexpected results. Thanks again
