### ISSUE TITLE
Sui doc content issue or request

### ISSUE THREAD

**Issue by pmarangone** [MystenLabs/sui#6547]
> If this is an issue with existing content, provide the URL or GitHub path to the topic. Otherwise, use **New**.

New (at least didn't find anything that matches what I'm looking for)

> Describe the issue or request. Provide as much detail as possible. For issues, it is helpful to copy the specific section of the topic into the issue.

I tried running the [end-to-end tutorial](https://github.com/MystenLabs/sui/blob/devnet/doc/src/explore/tutorials.md) but the script looks for something that does not exist anymore. Meaning, it runs:
`echo $certificate | awk -v s="The newly published package object ID:" 'index($0, s) == 1'`

My doubt is about if I'm running the correct branch or if I messed while setting the genesis/start or it's just the docs that are not updated

The script provides the following: 

```bash
----- Certificate ----
Signed Authorities : ...
Transaction Kind : Publish
Gas Budget : 30000
----- Publish Results ----
The newly published package object: (A613A7FF8CB03E0DFC0D157E232BBA50C5F19D17, SequenceNumber(1), o#fb70b9d1ac25250a00e35031289f89cd9c9d739f8663e1cc8ed739095a104e68)
List of objects created by running module initializers: []
Updated Gas : Coin { id: 38B89FE9F4A4823F1406938E87A8767CBD7F0B93, value: 92939 }
```

While I get the following: 
```
----- Certificate ----
Transaction Hash  Rr9X3ualFqYxBDBe2DEpnDE+cgOLCyadK0dcObtxx1Q=
Transaction Signature  AA==@SAWBWv7HxMnCOKtSY5TVBCn/hVrsUdm4P2YmTHh3ZhFFnhcISxupo0jZiHebdaGCkgXBLJV6e8//Ar7DzdaQBA==@17Y3o6J++0wmSwSnn7+f63hsF/JLDgdhJ7HQMW0PTT4=
Signed Authorities Bitmap  RoaringBitmap<[0, 1, 2]>
Transaction Kind   Publish
----- Transaction Effects ----
Status   Success
Created Objects
  - ID  0x272dfa91661b4efeeb723c3f3ea15d967622c738 , Owner  Account Address ( 0x8144d651dc30994f4292943a679c775359cee7b7 )
  - ID  0x336ef64da0bfea04991e85064a681f97fca045f3 , Owner  Immutable
  - ID  0xe32ccf58e3aa2c7376dd65645f5114dc539d632e , Owner  Immutable
  - ID  0xebf807e708d526e7fa0fd67548d30c945b96f66d , Owner  Account Address ( 0x8144d651dc30994f4292943a679c775359cee7b7 )
Mutated Objects
  - ID  0x27cfd5b528c6e153700a5e2b1aeb52361c3c3e75 , Owner  Account Address ( 0x8144d651dc30994f4292943a679c775359cee7b7 )
```

this certificate is generated by:
`sui client publish --path ./sui/sui_programmability/examples/games --gas $ADMIN_GAS --gas-budget 30000`

I'm currently running the devtest branch

> Thank you for taking the time to let us know about the issue or request. We triage all new issues and requests within 2 business days. We will follow up if we need additional information.

**Comment by randall-Mysten** [comment]
Hi @pmarangone Thanks for reporting this. It looks like your request succeeded, so I think the docs are just not updated for recent changes. I'll follow up and verify. Appreciate you taking the time to provide feedback.

**Comment by pmarangone** [comment]
hey @randall-Mysten, just following up to see if you checked on it. Also if it would fit a good first issue because I could work on it if it was in fact because the docs are not updated with the current txs return

**Comment by randall-Mysten** [comment]
I've not yet gotten to this. If you want to submit a PR with the update I can verify and approve so you get the contribution credit.

**Comment by WayneAl** [comment]
My PR #5995 was about this issue
I had worked on it before, but it was not reviewed yet... so I just closed it
Should I reopen it?

**Comment by randall-Mysten** [comment]
Hi @WayneAl Sorry, I dropped the ball on this one. Please do resubmit and I will get to it in the next week
