### ISSUE TITLE
Function to Convert Address to String, and Vice-Versa (debug::print can't read ascii)

### ISSUE THREAD

**Issue by PaulFidika** [MystenLabs/sui#6554]
So, as far as I've been able to do, it's currently impossible to convert an address-type to a string, and a string to an address-type.

If you use `sui::bcs::to_bytes(address)` what you get is a vector of u8s, which debug::print interprets as a pair of hexadecimals, i.e. 253u8 = fd, 154u8 = 9a, etc.

If you use `std::ascii::string` it will accept an array of u8s, however it expects all u8s to be < 128, because ascii-characters are supposed to be 7 bits, so it will throw an error every time it sees a u8 >= 128.

What I did was create a function that splits each byte into an upper and lower half, and then converts those into their corresponding ascii-encoding; this turns a length-20 bcs-encoded address into a length-40 ascii. Unfortunately debug::print will print off an ascii-string of bytes incorrectly; for example 102u8 in ascii is supposed to be printed as = f, however debug::print interprets 102u8 as the hexadecimal pair = 66. 

You can find the ascii and extended ascii charts here:
https://www.rapidtables.com/code/text/ascii-table.html

The problem is that std::ascii::String is really just a generic wrapper of bytes (vector<u8>), without its own print function, and the other modules have their own non-ascii interpretation of how to print those bytes.

**Comment by sblackshear** [comment]
https://github.com/MystenLabs/sui/pull/6714 is working toward addressing this, and we'll also fix the debug printing of ASCII strings on the Move side (thanks for filing that issue over there).

In the meantime, I think you should be able to unblock yourself by creating a UTF8-encoded `std::string::String` from your ASCII-encoded bytes. That should work because UTF8 is a superset of ASCII and `debug::print` knows how to print `std::string::String` correctly.

**Comment by PaulFidika** [comment]
> #6714 is working toward addressing this, and we'll also fix the debug printing of ASCII strings on the Move side (thanks for filing that issue over there).
> 
> In the meantime, I think you should be able to unblock yourself by creating a UTF8-encoded `std::string::String` from your ASCII-encoded bytes. That should work because UTF8 is a superset of ASCII and `debug::print` knows how to print `std::string::String` correctly.

Thanks! I've switched to using utf8 for anything rather than ascii. Unless you can think of a reason I should prefer ascii?
