### ISSUE TITLE
Cannot install sui binaries

### ISSUE THREAD

**Issue by anhdungle93** [MystenLabs/sui#6559]
## Steps to Reproduce Issue

I am trying to install sui binaries with 
cargo install --locked --git https://github.com/MystenLabs/sui.git --branch devnet sui

## Expected Result

Successful installation

## Actual Result
Error 
error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-arch" "x86_64" "-I" "snappy/" "-I" "." "-Wall" "-std=c++11" "-DNDEBUG=1" "-o" "/var/folders/0h/tf8nh7sj20dgzt8dchfgzwj40000gn/T/cargo-install8lFjM1/release/build/librocksdb-sys-6b1b9f93f978fa76/out/snappy/snappy.o" "-c" "snappy/snappy.cc" with args "c++" did not execute successfully (status code exit status: 1).

error: failed to compile `sui v0.17.0 (https://github.com/MystenLabs/sui.git?branch=devnet#79100a56)`, intermediate artifacts can be found at `/var/folders/0h/tf8nh7sj20dgzt8dchfgzwj40000gn/T/cargo-install8lFjM1`

## System Information

* OS: macOS Catalina Version 10.15.7

**Comment by Tsuivivor** [comment]
Hi, I indeed updated my OS and the installation succeeded. Thanks for the help.

**Comment by anhdungle93** [comment]
Thanks I updated the OS to 13.0.1 and the installation succeeded. Thanks for the help
