### ISSUE TITLE
Testnet nodes stopped syncing on transaction 31,344,000

### ISSUE THREAD

**Issue by icohigh** [MystenLabs/sui#6560]
Our Suiscan testnet nodes simultaneously stopped syncing more than 6 hours ago. Last number of transactions 31,344,000.
Suiscan testnet full node endpoint: https://suiscan.xyz/api/sui/testnet
Explorer: https://suiscan.xyz/testnet/transactions
Docker image: `mysten/sui-node:99b4e7ca83b6d1abe312f5afc04840dce331238b`
```
curl -X POST https://suiscan.xyz/api/sui/testnet \
-H "Content-Type: application/json" \
--data '{
    "jsonrpc":"2.0",
    "method":"sui_getTotalTransactionNumber",
    "id":1
}' | jq .result
```
Result is `31,344,000`

We have 1 Error and 2 warnings in the logs:

`ERROR sui_core::safe_client: Client error in handle_batch_stream err=UnknownSigner authority=k#a27bd87f972287e4301b488f3b6f688846b1dce3e1f6902d1a46a2da85651b374afa511d00fd599843222b430f0171c00c6ad6f4962224fda95a4a514c64d2e47e272a7ed980bb07588c0875607986b2b7430002235381925f42e36cb830a623`

`WARN sui_core::node_sync::node_follower: follower task exited with error The service is currently unavailable - error trying to connect: tcp connect error: Connection refused (os error 111) peer=k#90dee97f3ffcba4e0d34a83a6d68d357dc8cc52887c8ce143b6edd8ec866dae7a8001aadd678ab1adc3b436b8077a4fd1566a43691a00326384506708e26e27dd3d7e751f79d4ed83dc9004b409556821a91a6039282144498890e0114d87e2f`

`WARN sui_core::node_sync::node_follower: follower task exited with error Value was not signed by a known authority peer=k#a27bd87f972287e4301b488f3b6f688846b1dce3e1f6902d1a46a2da85651b374afa511d00fd599843222b430f0171c00c6ad6f4962224fda95a4a514c64d2e47e272a7ed980bb07588c0875607986b2b7430002235381925f42e36cb830a623`

Restarts don't solve the problem.
Docker logs in DEBUG mode: [logs.txt](https://github.com/MystenLabs/sui/files/10148548/logs.txt)

**Comment by sblackshear** [comment]
This is expected--testnet wave 1 ended on 12/1 and we shut the network down, so there are no more transactions to sync. Stay tuned for wave 2!
