### ISSUE TITLE
Be able to tell which object wrapped which object in Move execution

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#663]
Today when you wrap an object to another (by embedding it as a field), we know that the object is being wrapped, but we don't know which object it's being wrapped into. This creates all sorts of problems, like there is no way to authenticate objects owned by the wrapped object in future transactions.
We could, inspect the content of each output object from every transaction (like reflection), and look for the wrapped object (based on type and ID). And then we can get the information we needed.

**Comment by gdanezis** [comment]
Is this still an issue?

**Comment by lxfind** [comment]
We probably never need this? I am not sure.
