### ISSUE TITLE
Issues in the SuiJSON section of Sui Docs

### ISSUE THREAD

**Issue by wubuku** [MystenLabs/sui#6658]
See link: https://docs.sui.io/devnet/reference/sui-json

Such a statement as the following is incorrect.

> Move supports U128 and U256 but JSON doesn't...

We need to be clear about the fact that JSON is not the type system of JaveScprit, but rather a text format that is completely language independent.

In terms of the JSON specification, a number can represent a number of any size. see: https://www.json.org/json-en.html

Just from an implementation point of view, we do often see large numbers serialized as JSON strings in order to avoid the serialization/deserialization libraries of JSON in many programming languages that are "too smart" to do the wrong type mappings. 

For example, a Java JSON library might presumptuously deserialize a large JSON number as a Float Java object instead of a BigInteger Java Object.

But in general, this is not a JSON problem, especially not a JSON expressiveness problem, but a problem of language-specific JSON libraries.

**Comment by randall-Mysten** [comment]
Hi @wubuku, Thanks for pointing this out. Great point, we'll follow up on this.
