### ISSUE TITLE
[Feature request] [staking_pool] Add store capability to Delegation.

### ISSUE THREAD

**Issue by rohitna** [MystenLabs/sui#6673]
## Context:

Currently, the `Delegation` struct in the `staking_pool` contract does not have `store`. This makes it really hard for a permissionless liquid staking protocol to exist.

## Requested feature:

1. Change `struct Delegation has key` to `struct Delegation has store, key` in `staking_pool`.

**Comment by georgescharlesbrain** [comment]
The store ability was added to the StakedSui struct, did this solve your challenge?  
Are you still building liquid staking?

**Comment by tnowacki** [comment]
The Delegation struct does not exist anymore, and StakedSui has store. So closing for now. Please open a new issue if you are still blocked @rohitna
