### ISSUE TITLE
Sui doc content issue (text typo error)

### ISSUE THREAD

**Issue by MhizC** [MystenLabs/sui#6735]
https://github.com/MystenLabs/sui/milestone/10

**Objectives**

**Provider users in NA, LATAM, EMEA, APAC with access to Sui tokens**

Replace with;

**Provide users in NA, LATAM, EMEA, APAC with access to Sui tokens**

**Comment by randall-Mysten** [comment]
@MhizC  Fixed, thanks for pointing this out!
