### ISSUE TITLE
how to integrate new wallet into wallet adapter?

### ISSUE THREAD

**Issue by ShaYha271097** [MystenLabs/sui#6766]
If this is an issue with existing content, provide the URL or GitHub path to the topic. Otherwise, use **New**.

Describe the issue or request. Provide as much detail as possible. For issues, it is helpful to copy the specific section of the topic into the issue.

Thank you for taking the time to let us know about the issue or request. We triage all new issues and requests within 2 business days. We will follow up if we need additional information.

**Comment by Jordan-Mysten** [comment]
We recommend using Wallet Kit to connect to your application, let me know if that works for you: https://github.com/MystenLabs/sui/blob/main/sdk/wallet-adapter/wallet-kit/README.md
