### ISSUE TITLE
Loading Application Still Very Slow

### ISSUE THREAD

**Issue by indra1801** [MystenLabs/sui#6813]
It needs to be fixed right away, at least a little bit faster because in my experience this month, Sui Wallet's speed is very slow. it can make users or investors uncomfortable . this should be noticed as soon as possible

**Comment by indra1801** [comment]
lets talk me here

**Comment by georgescharlesbrain** [comment]
Hi,

Thanks for testing out the Sui wallet. Currently, the Sui wallet is still under development. This means that sometimes, some bugs can slip in. However, the bugs are often solved a couple of days later.

Note that the wallet currently communicates to devnet or testnet, which are restarted every couple of weeks. The result is that all assets (which do not hold any value) are wiped.

After a network reset, the following steps could help:

*   Update the wallet
*   Change the language of your Chrome browser to English (and delete other languages)
*   Clear the site data of the website you are having issues with in chrome. (Paste "chrome://settings/content/all?searchSubpage" in your search bar)
*   Delete and reinstall the wallet

Is your issue still not solved? I'd recommend the [Sui Discord](https://discord.gg/sui). The community is often more responsive on wallet issues there.

Have a wonderful day.
