### ISSUE TITLE
win10 系统如何安装 sui 文件

### ISSUE THREAD

**Issue by xiaozhu001** [MystenLabs/sui#6818]
我下载了devnet-0.18.0 版本的sui文件，但是我找不到如何安装到我的电脑相关的文档。
![image](https://user-images.githubusercontent.com/31197436/207795174-f9c2ace9-27d4-4b3b-a439-fcc5a86bafaa.png)

**Comment by YusongWang** [comment]
不支持，用ubuntu20

**Comment by randall-Mysten** [comment]
Hi YusongWang You can find install instructions in the Sui Docs: https://docs.sui.io/devnet/build/install
