### ISSUE TITLE
sui_getEvents ascending order, cursor pagination not working.  many transactions missing 

### ISSUE THREAD

**Issue by sibitha-bijesh** [MystenLabs/sui#6899]
## Steps to Reproduce Issue

I used sui_getEvents RPC endpoint to fetch first 10 records initially, then pass the nextCursor to cursor like "{
            "txSeq": 4516692,
            "eventSeq":6
        }" .  But  I didn't get full events. some event data missed. So didn't get the some transaction

e.g.
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "sui_getEvents",
  "params": [
    {
        "MoveModule": {
        "package": "0x5eeb79fe18f214fcf1bcdb0cf65ef268e4ffc713",
        "module": "proxy"
      }
    },
    null,
    10
  ]
}
``` 
Problem is in fetching ascending order with cursor and MoveModule .  Some transaction in a same package and module not getting

**Comment by bausano** [comment]
I am observing the same issue
