### ISSUE TITLE
[sdk]@mysten/sui.js version 0.17.1 failed to transfer

### ISSUE THREAD

**Issue by ChiuMungZitAlexander** [MystenLabs/sui#6902]
## Steps to Reproduce Issue

We have a function to transfer(or send token) by the implementation of @mysten/sui.js version 0.17.1 as below. (Similar to the implementation of sui wallet).

```
import {
  getTransactionDigest,
  isSuiMoveObject,
  Coin,
} from '@mysten/sui.js'

export const sendTokens = createAsyncThunk<
  TransactionResult,
  SendTokensTXArgs,
  AppThunkConfig
>(
  'sui-objects/send-tokens',
  async (
    { tokenTypeArg, amount, recipientAddress },
    { getState, extra: { api, keypairVault }, dispatch }
  ) => {
    const state = getState()
    const coins: SuiMoveObject[] = accountCoinsSelector(state)
    const signer = api.getSignerInstance(keypairVault.getKeyPair())
    const response = await CoinAPI.transfer(
      signer,
      coins,
      tokenTypeArg,
      amount,
      recipientAddress,
      Coin.computeGasBudgetForPay(
        coins.filter((aCoin) => Coin.getCoinTypeArg(aCoin) === tokenTypeArg),
        amount
      )
    )
    
    return response
  }
)
```

From last week, we received a great number of user reports that the transactions were failed, even though we have NOT changed any code of `sendTokens`. Below is the error message.

`
Error executing transaction with request type: Error: RPC Error: Signature is not valid: signature error
`

I just tested Ethos wallet, Suiet Wallet, and found both of them failed to transfer.

I am not sure if this happened because the sdk was upgraded to version 0.20.0, together with some upgrade of your chain service. And if it is necessary for us to upgrade @mysten/sui.js to version 0.20.0?

* OS: macOS 12.3

**Comment by 666lcz** [comment]
@ChiuMungZitAlexander Yes we introduced a breaking change in the signature in 0.20.0: https://github.com/MystenLabs/sui/blob/main/sdk/typescript/CHANGELOG.md, please upgrade to 0.20.0. In general, it's recommended to upgrade to the latest SDK as long as there's a [Minor](https://github.com/MystenLabs/sui/blob/main/sdk/typescript/CHANGELOG.md) change(representing breaking change in pre alpha versions).
