### ISSUE TITLE
[ts-sdk] 17.0.1 fail to executeTransaction

### ISSUE THREAD

**Issue by bruceeewong** [MystenLabs/sui#6905]
## Steps to Reproduce Issue

We are using ts sdk v17.0.1 right now. Recently the sdk is not working. 

When we send `sui_executeTransaction` via RPC, it responds with error 

```
code:  -32000
message:  "invalid value: integer `84`, expected variant index 0 <= i < 2"
```

Btw, we have upgraded to ts sdk v0.20.0 and change some codes due to the breaking changes of sdk, new errors show up for using `sui_executeTransactionSerializedSig`:

```
"error":{"code":-32000,"message":"Signature is not valid: signature error"}
```

How should we solve this issue?

## System Information

* OS: MacOS@12.3.1 M1 chip

**Comment by 666lcz** [comment]
@bruceeewong thanks for flagging this. It's expected that 0.17.0 does not work with the current DevNet due to the breaking change introduced in [v20.0.0](https://github.com/MystenLabs/sui/blob/main/sdk/typescript/CHANGELOG.md). 

I was not able to repro the invalid signature error with sdk v0.20.0 using the following code: https://github.com/666lcz/sui-sdk-test-scripts/blob/main/index.js. Could you post the repro steps and code?

**Comment by bruceeewong** [comment]
@666lcz I followed your demo and fixed this workaround now, thanks. For the invalid signature issue, I think it might be related to `JsonRpcProvider.executeTransaction`. I used that for my execution before and after I switched to `RawSigner.signAndExecuteTransaction` the issue was gone.

**Comment by 666lcz** [comment]
@bruceeewong Good call out. We added an additional logic when signing the data: https://github.com/MystenLabs/sui/blob/6c3e2bba3f36e647011ca6a374f8bcfac8747857/sdk/typescript/src/signers/signer-with-provider.ts#L112-L117 

cc @joyqvq we should probably move this logic within `signData`

**Comment by joyqvq** [comment]
the `signData` is not aware of the API version to decide whether to append the intent bytes. it is meant to live with the client side (say the version increment to v1 from v0, the client is responsible to set this)

how are you serialize the data to sign? the data the signature is committing to needs to contain the intent bytes, I added more code example here https://github.com/MystenLabs/sui/pull/6445


```
Params
tx_bytes : <Base64> - BCS serialized transaction data bytes without its type tag, as base-64 encoded string.
signature : <Base64> - `flag || signature || pubkey` bytes, as base-64 encoded string, signature is committed to the intent message of the transaction data, as base-64 encoded string.
```

**Comment by dtduong30** [comment]
hi @bruceeewong, i have same error even when switch to `RawSigner.signAndExecuteTransaction`. My function from my publish module is run normally when using Sui CLI. I was wondering if you could reply me how to fix this error? Thanks a lot

**Comment by 666lcz** [comment]
@dtduong30 , could you confirm that you are using the sdk version v.20.0?

**Comment by bruceeewong** [comment]
> hi @bruceeewong, i have same error even when switch to `RawSigner.signAndExecuteTransaction`. My function from my publish module is run normally when using Sui CLI. I was wondering if you could reply me how to fix this error? Thanks a lot

Sure. What I have done is that I created a keypair structure to fit in the input params of signAndExecuteTransaction of RawSigner.

```
  const keypair = createKeypair(vault);
  const signer = new RawSigner(keypair, this.provider, this.serializer);
  return await signer.signAndExecuteTransaction(tx);
```

Note that my keypair uses 'ed25519' scheme.

**Comment by bruceeewong** [comment]
@joyqvq Before this I used my own logic to sign the transaction data. That is, use Base64DataBuffer.getData to serialize the transaction params and use elliptic keypair with ed25519 scheme to sign the bytes.
I think the additional logic of intent bytes is the key to this issue. Kind of confusing to our developer though.
