### ISSUE TITLE
[wallet-standard] support fetching current network (chain) and network-change event emitter

### ISSUE THREAD

**Issue by bruceeewong** [MystenLabs/sui#7013]
## Motivation

For Dapps, we want to subscribe to the network state of Sui Wallet and listen to the network-change event while user changes it in the wallet, such that we dapps could refresh UI and data according to the new network (chain).

## Reference

Suiet Wallet has already supported fetching current network state and network-change event emitter. FYI, we can discuss about the implements here:

- Fetching current network state when connected: https://github.com/suiet/suiet/blob/main/packages/chrome/src/scripts/content/wallet-standard/index.ts#L183
- Subscribe network-change event which is emitted from wallet app: https://github.com/suiet/suiet/blob/main/packages/chrome/src/scripts/content/wallet-standard/index.ts#L253

**Comment by Jordan-Mysten** [comment]
This is a good call out, we do need to implement this through our account interface, thanks for reporting! I think we should probably expose this information in adapters as well (honestly our adapters should look more like the low-level wallet standard object).
