### ISSUE TITLE
[TypeScript SDK] Mismatch in type definition for `getEvents` between TS SDK and RPC

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#7028]
A Discord user reported that they received `The response returned from RPC server does not match the TypeScript definition. This is likely because the SDK version is not compatible with the RPC server. Please update your SDK version to the latest.` when making the following call

Repro

I've been testing getEvents method recently and that warning was from a call below
const events = await provider.getEvents({ MoveModule: { package: '0x2', module: 'pay' }}, { txSeq: 5000000, eventSeq: 1 }, 1000, 'ascending') and it was only from a 1000 events batch in between. Other 1000s worked well.

**Comment by xydas97** [comment]
I tried to reproduce the the error but I couldn't make it. It seems that getEvents work fine without causing any mismatch.
This was probably fixed because the cursor EventId now consists of { txDigest, eventSeq } instead of { txSeq, eventSeq }.
