### ISSUE TITLE
Sui doc content request - information about a sparse node

### ISSUE THREAD

**Issue by georgescharlesbrain** [MystenLabs/sui#7029]
In a YouTube vid, I learned about the concept of a "sparse node". I was hoping to find more information
about it in the docs, but didn't find any.

On Discord, I got a good response which could be added to the docs somewhere.

> Sui's key technical advantage (enabled by its novel data model) is the ability to run a sparse node that only verifies transactions relevant to a set of causal roots (e.g., the set of objects a wallet owns, addresses for all of the players in an on-chain game) instead of a full node that must track everything. The cost of running a sparse node is proportional to the size of the causal roots, not to the overall transactions processed by the validators. For the intended use cases, this cost will be very low--e.g., a mobile wallet can easily be a sparse node for the objects managed by the wallet.

A link to where I can find more information about the progress of the implementation would also be welcome.

**Comment by randall-Mysten** [comment]
Hi @georgescharlesbrain Thanks for your request. We'll follow up on it.
