### ISSUE TITLE
[crypto] Support ECVRF Move api

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/sui#7038]
ECVRF is expected to require less gas than BLS VRFs and it can be an important tool for Satoshi TL-VRF Dice, replacing hash(pre-image secret).

**Comment by jonas-lj** [comment]
We will also need some kind of tool for users to generate keys and proofs to be verified in move, eg. a command line tool. Should this be part of fastcrypto?

**Comment by kchalkias** [comment]
> tool for users
Will create an issue yes!
