### ISSUE TITLE
Sui doc content issue or request

### ISSUE THREAD

**Issue by vantessel** [MystenLabs/sui#7075]
https://github.com/MystenLabs/sui/blob/b8ace6ff5e3045f6e3fdd9a7ff076dfd2c236a61/sui_programmability/examples/defi/sources/pool.move#L77-L78

This is wrong, it should be ```/// that 10000 is 100% and 1 is 0.01%```

**Comment by randall-Mysten** [comment]
Hi @vantessel Thanks for pointing this out. I've added some folks to confirm the update.

**Comment by vantessel** [comment]
this may help: https://www.investopedia.com/terms/b/basispoint.asp

**Comment by randall-Mysten** [comment]
:) Folks are busy with Testnet so I'm approving. Thanks for taking the time to report and provide a fix for this!
