### ISSUE TITLE
[TypeScript SDK & Move Stdlib] Fully qualified type name inconsistency

### ISSUE THREAD

**Issue by admin-aftermath** [MystenLabs/sui#7089]
### TypeScript SDK
Some of the TypeScript SDK functions expect their `TypeArg`'s to not start with zeroes, e.g. if you pass a `TypeArg` of `0x0000000000000000000000000000000000000002` instead of `0x2` to `selectCoinSetWithCombinedBalanceGreaterThanOrEqual` it will not return any SUI Coins the user may in fact have. Similarly, I was unlucky and have my last contract be published with an address of `0x01...` so its respective coins would not be queried from `selectCoinSetWithCombinedBalanceGreaterThanOrEqual` if the fully qualified type name was given.
### Move Stdlib 
However, if you call the Move stdlib's function [`type_name::get`](https://github.com/move-language/move/blob/main/language/move-stdlib/sources/type_name.move#L16-L17) on a specific type it will return the fully qualified type name.

## Issue
A common pattern in our workflow, and I imagine a common pattern in general, is to emit an event on chain that contains one or more results from `type_name::get`. These values can then be read through the TypeScript SDK's [`getEvents`](https://github.com/MystenLabs/sui/blob/main/sdk/typescript/src/providers/json-rpc-provider.ts#L668-L686) function and used on the frontend however needed. If this pattern is used directly with `selectCoinSetWithCombinedBalanceGreaterThanOrEqual` you can potentially run into the above issue.

## Solution
TypeScript SDK functions that accept a `TypeArg` as input should allow for fully qualified type names to be provided.

### Related Issues
- [Inconsistent type of Sui](https://github.com/MystenLabs/sui/issues/5879)

**Comment by stefan-mysten** [comment]
@hayes-mysten I assume this is not relevant anymore, but just wanted to double check with you first.

**Comment by hayes-mysten** [comment]
yes, we can close this
