### ISSUE TITLE
There is an error in the link to the document.

### ISSUE THREAD

**Issue by mattsu2020** [MystenLabs/sui#7115]
The fabfile.py link in the document below is out of date. sui/narwhal/benchmark/fabfile.py is the new file reference, please correct it.

・Target Documents
https://github.com/MystenLabs/sui/tree/main/narwhal

・old link
https://github.com/mystenlabs/narwhal/blob/main/benchmark/fabfile.py

・new link
https://github.com/MystenLabs/sui/blob/main/narwhal/benchmark/fabfile.py

**Comment by randall-Mysten** [comment]
Thanks @mattsu2020 for letting us know about this. I've added a few folks to confirm.

**Comment by mwtian** [comment]
Thanks for reporting @mattsu2020, indeed we should update links away from the archived Narwhal repo.
