### ISSUE TITLE
[CI] Skip Rust test if there's no Rust change

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#7127]
For example, the "rust test" workflow in GitHub CI for https://github.com/MystenLabs/sui/pull/7124 should be skipped since there is not Rust changes

**Comment by andll** [comment]
Even more so - if we could auto attach a label to Pull request depending on whether it have rust changes or not, it would allow to filter out relevant PRs letter for email subscription, etc

**Comment by 666lcz** [comment]
This has been done: https://github.com/MystenLabs/sui/blob/725091192c84ff11e8b9a1f93c62ed033c52609e/.github/workflows/rust.yml#L41
