### ISSUE TITLE
[Bug] Very confusing handling of u64 values in `sui client call`

### ISSUE THREAD

**Issue by tnowacki** [MystenLabs/sui#7142]
Several discord around the syntax for u64s feeling broken with a very confusing error Message.

Using @emmazzz's example, the call:

```
sui client call --package 0x2 --module pay --function divide_and_keep --args 0x33fd99d773d0fa02826bc45202353eef4996e394 3 --gas-budget 10000
```

Yields the error message:
```
"Could not serialize argument of type U64 at 1 into u64. Got error: Unexpected arg 3 for expected type u64"
```

My 2 cents, we should always accept valid Move syntax for primitive arguments. Though I know this might be tricky in some cases.

**Comment by sblackshear** [comment]
I think forcing string inputs is a totally reasonable thing to do for JSON, but we can be a lot more permissive in the CLI. No need to couple these

**Comment by tnowacki** [comment]
> I think forcing string inputs is a totally reasonable thing to do for JSON, but we can be a lot more permissive in the CLI. No need to couple these

Sounds good! Updated the issue title

**Comment by tttlkkkl** [comment]
So what should I do with him？
sui client call --package 0x7d79014936c3f287ec88360a222b3c2f0ca9fcdb --module scale --function airdrop --args 0xc612b7e57db806258b0323d57dc1d5530aab3a24 0x9afaef1f63ce364758684675db5b77d727f0465a 100000 --gas-budget 1000
Could not serialize argument of type U64 at 2 into u64. Got error: Unexpected arg 100000 for expected type u64
