### ISSUE TITLE
[TypeScript SDK] New version bug, Could not serialize argument of type U64 at 7 into u64

### ISSUE THREAD

**Issue by e274426380** [MystenLabs/sui#7146]
![image](https://user-images.githubusercontent.com/75345973/210739961-00d220e9-c736-4f5b-b1b7-b2cdc8b29da6.png)
Methods that worked before now don't work

**Comment by WayneAl** [comment]
it's due to the sui version update,
so you need to trans u64 to hex string

plz check:
https://github.com/MystenLabs/sui/releases/tag/devnet-0.20.0
https://docs.sui.io/build/sui-json

**Comment by e274426380** [comment]
> it's due to the sui version update, so you need to trans u64 to hex string
> 
> plz check: https://github.com/MystenLabs/sui/releases/tag/devnet-0.20.0 https://docs.sui.io/build/sui-json

Thank you for your reply, I have solved the problem.
