### ISSUE TITLE
Sui doc content request - storage fund

### ISSUE THREAD

**Issue by georgescharlesbrain** [MystenLabs/sui#7156]
After reading the docs about the [storage fund](https://docs.sui.io/learn/tokenomics/storage-fund). The following questions came to mind:
Where can I monitor the storage fund?
Where in the repo can I find information about the implementation of the storage fund feature?

**Comment by randall-Mysten** [comment]
Hi @georgescharlesbrain Most of the info in the Tokenomics section describe how Sui is designed to work, but not all of it it implemented yet. We'll provide more information about things like this once we have the feature available

**Comment by georgescharlesbrain** [comment]
Hi,
This comes back to the ROADMAP question I once asked in discord.
It is unclear to me which features already exist and which still need to be implemented.
For https://github.com/MystenLabs/sui/issues/7029 sparse node I had the same challenge.
Do these features maybe have open issues?
