### ISSUE TITLE
Sui doc content request - extra guidance on installation of Sui

### ISSUE THREAD

**Issue by georgescharlesbrain** [MystenLabs/sui#7158]
Concerning [Install Sui binaries](https://docs.sui.io/build/install#install-sui-binaries)

Assuming you don't have Rust and Cargo pre-knowledge, what is happening here? 
A bit more handholding on a 40min install would be nice.
Encountering an error when your 10min in an install is rather demotivating.
Why does this build process take 40min? Can you make it speed up?
What can I expect when I run the "cargo install" command?
More elaborate troubleshooting.

**Comment by randall-Mysten** [comment]
@georgescharlesbrain Yep, great points. For the early phases of Sui we required a bit more domain knowledge and experience to start building on Sui. As we get closer to Mainnet, and more newer folks are exploring the platform, we need to provide more 101 level guidance to provide an easy on ramp to Sui. We're actively working on this content. Thanks for your continued review and contributions. Cheers!
