### ISSUE TITLE
Sui doc content issue - add existing accounts to client

### ISSUE THREAD

**Issue by georgescharlesbrain** [MystenLabs/sui#7173]
Concerning section:
https://docs.sui.io/build/cli-client#add-existing-accounts-to-clientyaml

> To add existing account addresses to your client, such as from a previous installation, edit the client.yaml file and add the accounts section. You must also add key pair to the keystore file.

client.yaml: 
	What should I edit here? 
	How should the content look like after adding the accounts section?

sui.keystore: 
	How to add a key pair to the sui.keystore?
 	Just doing a copy paste of one of the strings from one file to another file?
	How do I add my keypair from my secret recovery phrase?

**Comment by zoroblock** [comment]
sui keytool import <MNEMONIC_PHRASE>
<KEY SCHEME>

use sui keytool import --help for more info
