### ISSUE TITLE
[TypeScript SDK] Expose `Call` API that can call any RPC endpoint

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#7184]
We should add a `call(endpoint, params)` method in https://github.com/MystenLabs/sui/blob/main/sdk/typescript/src/providers/json-rpc-provider.ts that people can use to invoke any RPC endpoint. This will relieve some of our pressure to keep TS SDK in sync with the JSON RPC API

**Comment by xydas97** [comment]
Completed https://github.com/MystenLabs/sui/pull/7384
