### ISSUE TITLE
consensus adapter submit_unchecked can cause unbounded task growth:

### ISSUE THREAD

**Issue by mystenmark** [MystenLabs/sui#7201]
There is a comment in the code indicating that it shouldn't: https://github.com/MystenLabs/sui/blob/releases/sui-v0.20.0-release/crates/sui-core/src/consensus_adapter.rs#L276-L277

And yet it seems to grow without bound:

<img width="1772" alt="image" src="https://user-images.githubusercontent.com/103447440/211101276-3035c69b-c4bb-4c01-aad6-d77b1d95922d.png">

**Comment by andll** [comment]
Ok, so I think this change is what removed the limit for inflight consensus transactions: https://github.com/MystenLabs/sui/pull/6587/files#diff-87bd2349f75c8096f4bd65152a5735a2ea0690f54180196ec497c19486a2f593L408

@mwtian did you have something else in mind to limit? If not, should we just put it back?

**Comment by mwtian** [comment]
I would be more comfortable setting a long timeout on the task that listens to consensus output. I'm not sure if current Narwhal setup can absolutely guarantee a transaction gets included. Even if a transaction becomes part of a Narwhal certificate, the certificate may not become the parent of any other certificate.

If a timeout is used, where should it be set? How about `within_alive_epoch()`? And I assume the timeout would propagate upward to `handle_certificate()`?

**Comment by andll** [comment]
I believe there is now a guarantee from narwhal that once transaction is submitted it will be included(e.g. we do not need the old loop we have with inserting same transaction many times) cc @gdanezis
