### ISSUE TITLE
[Feature] Expand 0x2::bcs to support more peel-types

### ISSUE THREAD

**Issue by PaulFidika** [MystenLabs/sui#7231]
How do you feel about adding:

peel_id
peel_u16
peel_u32
peel_u256
peel_ascii_string
peel_utf8_string

and of course, vector and option-versions of all of these? I could write these up if you guys are down.

**Comment by PaulFidika** [comment]
How do you feel about something like:

borrow_bytes_mut(bcs: &mut BCS): &mut vector<u8>

this would allow external modules to modify a BCS's internal bytes arbitrarily. Which may or may not be desirable...

**Comment by sblackshear** [comment]
My 2c: supporting peeling of more types seems very useful/convenient, would be in support of adding all of these.

> borrow_bytes_mut(bcs: &mut BCS): &mut vector

I think this only makes sense if the `BCS` type does not maintain any internal invariants (since exposing write access into the vector will allow an external module to violate them). @damirka will have a more informed opinion on this.

**Comment by PaulFidika** [comment]
> My 2c: supporting peeling of more types seems very useful/convenient, would be in support of adding all of these.
> 
> > borrow_bytes_mut(bcs: &mut BCS): &mut vector
> 
> I think this only makes sense if the `BCS` type does not maintain any internal invariants (since exposing write access into the vector will allow an external module to violate them). @damirka will have a more informed opinion on this.

Yeah that's what I was thinking too. Exposing the underlying bcs bytes themselves would make it more convenient to do deserialization of custom structs (without having to destroy the bcs wrapper), but it might break something.

**Comment by damirka** [comment]
Hey @PaulFidika, closing this one as a stale. Given that it's almost been a year, and the #18431 is out.
