### ISSUE TITLE
[P1] [gateway/replica] Make client side logic for Follower

### ISSUE THREAD

**Issue by gdanezis** [MystenLabs/sui#729]
Right now we have logic on the authority side for sequencing, batching, a listening to updates. However we need logic on the client side to subscribe and consume such updates. This involves:
- [x] Modify the client logic to allow for a request to subscribe followed by multiple response for updates.
- [x] Fetch for each of these updates (unless it is locally available) a certificate for each transaction digest received.
- [x] Improve the safe client to check hashes and signatures of information received from authority.

**Comment by todd-mystenlabs** [comment]
I think this is part of the follower task @sblackshear was referencing in a comment in #1409. If I got that wrong, let me know.  @laura-makdah - this is a P1 for DevNet, not a P0.  (I bumped it up from Pre-TestNet.)

**Comment by todd-mystenlabs** [comment]
Hey @gdanezis @laura-makdah - I think I may have ended up triggering a change to open this issue back up when I linked it into another umbrella issue.  If this is closed, please close it again.  (It's listed as Done" but not closed, which is an oddball state.)
