### ISSUE TITLE
Verify validator metadata upon join request

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#7323]
In sui_system.move, we provide interface `request_add_validator` for a new validator to join. The metadata provided will eventually be used to create committee and connect network during reconfiguration.
Currently these data are not validated, and during reconfiguration if any of them is invalid we will panic and there is no way to recover. You can find most of the panic points in https://github.com/MystenLabs/sui/blob/main/crates/sui-types/src/sui_system_state.rs (look for expect or unwrap).
Hence we must validate them when we receive the request. We need to implement a native function that takes in a reference to the validator metadata, and attempt to convert all the bytes fields into actual value (e.g. keys, network addresses and etc), and if any of them fail we must reject the join request. This ensures that during reconfiguration we cannot fail.

**Comment by bmwill** [comment]
I think that we should do as much as we can to do onchain verification of this data, although in addition to that we should also teach our validator software to tolerate when that data is incorrect and handle the case when it is incorrect properly instead of crashing.
