### ISSUE TITLE
[fastx dist sys] Design and implement re-configuration

### ISSUE THREAD

**Issue by gdanezis** [MystenLabs/sui#75]
fastx operates in epochs. Within each epoch committee and stake are stable, but between epochs they may change. Between epoch a rec-configuration protocol is ran between validators and a consensus system to ensure safety and liveness. We need to implement this re-configuration mechanism, specifically:
- The logic by which a validator closes an epoch, and asks 2f+1 validators of the next epoch to provide a certificate over the set of certificates processed.
- The logic by which an epoch starts through a validator accepting the first 2f+1 certificates (on the consensus core), initializes its database, and start processing transactions.
- Efficiency improvements to minimize downtime.
- Make decisions and implement the smart contract on an L1/consensus core driving the governance logic, and sequencing the certificates of state between epochs.

**Comment by LefKok** [comment]
Extending on the double-validation idea:

We can split the Sui single-object workflow in two parts: 1) Transaction Validation (TV) and 2)Certificate-Inclusion Promise (CIP). In normal operation TV is the consistent broadcast of the transaction and CIP is the persistent broadcast of the certificate (notice that consistent and persistent broadcast are the same protocol for different functionalities).  

During the epoch change, the TV and the CIP responsibilities of the committee are handovered at different points in the process to the next committee. When the 2nd step (referred as bootstrap new epoch above) appears in consensus the new committee takes the CIP responsibilities, this means that any transaction TVed by the old committee need to get a CIP from the new committee, the old committee stops replying to these messages once it initiates the "epoch-handover" checkpoint. 

When the epoch-handover checkpoint is available the new committee also bootstraps from this and takes over the TV duties. To start replying to TV messages committees members replay all the CIP messages they have acknowledged on their state and only afterward start processing TVs.

**Comment by asonnino** [comment]
What is exactly the “persistent broadcast” part? Is it another echo?

**Comment by asonnino** [comment]
So we only need this persistent broadcast upon committee change/checkpoint or do we need it all time (also as part of normal operations)?

**Comment by LefKok** [comment]
Always. Sui's workflow is 1) Consistent broadcast the transaction and
2)Persistent Broadcast the Certificate. They are both the same protocol (I
can remove the difference if it is confusing), they simple have a different
purpose.

Στις Τρί 22 Μαρ 2022 στις 3:48 μ.μ., ο/η Alberto Sonnino <
***@***.***> έγραψε:

**Comment by asonnino** [comment]
I see, so we have the overhead of making 2 extra round-trips for every transaction in order to support reconfiguration.

**Comment by LefKok** [comment]
No, it is zero overhead. The difference is that the second part of the
transaction (sending the certificate and collecting 2f+1 acks to reach
finality) is done with the new committee after some point.

Στις Τρί 22 Μαρ 2022 στις 6:01 μ.μ., ο/η Alberto Sonnino <
***@***.***> έγραψε:

**Comment by asonnino** [comment]
After that we can workout the details such as cleanup, shared objects, etc

**Comment by asonnino** [comment]
Got it! Makes sense to me, and I think I understand why is is safe. I’m happy to go more formal

**Comment by gdanezis** [comment]
Just caught up on the double validation idea. I think this is viable, can we work out details and a more formal description + argument for safety? I get the intuition but the devil is often in the details. On the side of checkpoints, we will have them, no worries so steps 1, 2 in the post 15 days ago will be taken care of.

**Comment by gdanezis** [comment]
I closed the issue about adding epoch to transactions here: https://github.com/MystenLabs/sui/issues/74
We should work out if we should do this, according to the protocols here.

**Comment by LefKok** [comment]
Summed up the design and provided some proof sketches here: https://docs.google.com/document/d/1qFfT749PpNT20L8MhdNWt-9df90tIQE8M44W_zXzYA0/edit#

**Comment by lxfind** [comment]
Close this one as we have broken down the work to smaller issues
