### ISSUE TITLE
storageRebate is not withdrawn from the gas fee

### ISSUE THREAD

**Issue by Sceat** [MystenLabs/sui#7536]
## Steps to Reproduce Issue

Use the TS sdk to send a transaction and dry run it first

```js
    const signer = new RawSigner(keypair, provider)
    const unsigned_transaction = {
      inputCoins: [some id],
      recipients: [some recipient],
      amounts: [some amount],
      gasBudget: 1000
    }

    const gasBudget = await signer.getGasCostEstimation({
      kind: 'paySui',
      data: unsigned_transaction,
    })

    const transaction = await signer.paySui({
      ...unsigned_transaction,
      gasBudget
    })
```

## Expected Result

The transaction should succeed

## Actual Result

The transaction fails with `InsufficientGas` because `storageRebate` is not withdrawn from the fee as it's indicated [here](https://github.com/MystenLabs/sui/blob/main/sdk/typescript/src/types/transactions.ts#L501)

```js
{ computationCost: 152, storageCost: 64, storageRebate: 32 }
```

## System Information

running SUI localnet from `main` branch

**Comment by oxade** [comment]
This storage rebate is applied after gas is charged. This means if computation is 100 units, and rebate is 10, there should be 100 units available during execution because 100 units will first be charged before the rebate is applied. Hence we should not be counting the rebate in the estimator.

**Comment by oxade** [comment]
@Sceat please feel free to confirm if this does not fix your issue

**Comment by Sceat** [comment]
#7594 does fix the problem yes thanks
