### ISSUE TITLE
[TypeScript SDK] clean up outdated version gated code

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#7541]
search for `major ==` in the Sui Repo and remove the outdated ones. Example: https://github.com/MystenLabs/sui/blob/6d10c699a7e24bc5733634c6096ffc52801ef48b/sdk/typescript/src/signers/signer-with-provider.ts#L180

**Comment by zhenfeng-zhu** [comment]
Hi, I am confused about this issue. Why are there such codes in typescript sdk repo?

**Comment by 666lcz** [comment]
@zhenfeng-zhu The TS-SDK needs to work with multiple RPC versions since the release cycle of TS-SDK is decoupled with the DevNet/TestNet release

**Comment by zhenfeng-zhu** [comment]
@666lcz Thanks for your reply.

> remove the outdated ones.

I see the ts-sdk version is `0.23.0`. So we just remove the statement like this:

```
return generateTransactionDigest(
      data,
      sig.signatureScheme,
      sig.signature,
      sig.pubKey,
      'base58',
      true
    );
```

Is there something wrong with my understanding?

**Comment by 666lcz** [comment]
Your understanding is correct! Are you planning to work on this issue?

**Comment by zhenfeng-zhu** [comment]
@666lcz of course, I can try it!

**Comment by xydas97** [comment]
Issue fixed with this [PR](https://github.com/MystenLabs/sui/pull/7761)
