### ISSUE TITLE
[Typescript SDK]: SuiJsonValue does not support Uint8Array

### ISSUE THREAD

**Issue by PaulFidika** [MystenLabs/sui#7569]
When calling into a function using the Typescript SDK, like:

```
  const moveCallTxn = await signer.executeMoveCall({
    packageObjectId: '0x5b3e7e9f37d8226b7cd54773f1fc5b88163eaaa8',
    module: 'bcs_maybe',
    function: 'give_bcs',
    typeArguments: [],
    arguments: [utf8Bytes],
    gasBudget: 10000
  });
```

The problem is that the Typescript SDK will thorw an error because the sole argument here,  utf8Bytes, is a Uint8Array (raw bytes for an array of utf8 strings in this case). The problem is that the type `MoveCallTransaction` defined in the Typescript SDK requires that its `arguments` field be a `SuiJsonValue[ ]` value, and `SuiJsonValue` is limited to just booleans, numbers, and strings; not Uint8Arrays. As a result I get the error:

`Error: RPC Error: Could not serialize argument of type Vector(U8) at 0 into vector<u8>`

This seems rather bizarre, because anything you serialize in Typescript will be a Uint8Array, and it should be easy to support sending these serialized raw bytes as an argument to an RPC node. Thanks.

**Comment by 666lcz** [comment]
This should be fixed in https://github.com/MystenLabs/sui/pull/7765#pullrequestreview-1277632358
