### ISSUE TITLE
Sui Code Bug or Feature Request

### ISSUE THREAD

**Issue by Favourc** [MystenLabs/sui#7578]
I'm glad to be a part of this wonderful sui community. I'm having issues lately connecting the sui app to suia site, I'm unable to claim suia of different projects on sui

**Comment by Favourc** [comment]
The sui app is also becoming slow I hope it gets fixed

**Comment by georgescharlesbrain** [comment]
Thanks for testing out the Sui wallet. Currently, the app is still under development. This means that sometimes, some bugs can slip in. These are often solved a couple of days later. Should you want instant feedback on the challenges you, face I'd recommend the [Sui Discord](https://discord.gg/sui). The community is often more responsive on wallet issues there. This [Twitter thread](https://twitter.com/SuiGlobal/status/1619020100115337234) could also help.
