### ISSUE TITLE
Issues with connecting to other project site 

### ISSUE THREAD

**Issue by Maureen84** [MystenLabs/sui#7579]
I can't connect sui to a project site, like when it ask to connect a wallet it won't connect with sui, it works well for other app like ethos, suiet, martian

**Comment by georgescharlesbrain** [comment]
Hi,

Thanks for testing out the Sui wallet. Currently, the Sui wallet is still under development. This means that sometimes, some bugs can slip in. However, the bugs are often solved a couple of days later.

Note that the wallet currently communicates to devnet or testnet, which are restarted every couple of weeks. The result is that all assets (which do not hold any value) are wiped.

After a network reset, the following steps could help:

*   Update the wallet
*   Change the language of your Chrome browser to English (and delete other languages)
*   Clear the site data of the website you are having issues with in chrome. (Paste "chrome://settings/content/all?searchSubpage" in your search bar)
*   Delete and reinstall the wallet

Is your issue still not solved? I'd recommend the [Sui Discord](https://discord.gg/sui). The community is often more responsive on wallet issues there.

Have a wonderful day.
