### ISSUE TITLE
Sui keytool feedback improvement

### ISSUE THREAD

**Issue by teohaik** [MystenLabs/sui#7585]
Iam trying to sign a Transaction using keytool and I get a not clear error message. Is there smth wrong with the arguments or a bug?
cc @kchalkias 

`sui keytool sign --address 0xfc952d383d6a3e4f6f9f11234a96be673a5d4eb5 --data AAIAAAAAAAAAAAAAAAAAAAAAAAAAAgEAAAAAAAAAINaXMihjlCd4CQVFRPjcNb7QfYP4wGgQyl1xbplvEKUCA3BheQlzcGxpdF92ZWMBBwAAAAAAAAAAAAAAAAAAAAAAAAACA3N1aQNTVUkAAgEAddbpGlwSqZNhYcXHPCmf33vR6GhDAAAAAAAAACB445CDbY0Le8+NfaOPVhByz0Ku8QEHhkqDAwBixjXzmgAZAxAnAAAAAAAAECcAAAAAAAAQJwAAAAAAAPyVLTg9aj5Pb58RI0qWvmc6XU61ddbpGlwSqZNhYcXHPCmf33vR6GhDAAAAAAAAACB445CDbY0Le8+NfaOPVhByz0Ku8QEHhkqDAwBixjXzmgEAAAAAAAAAECcAAAAAAAA=`

returns:

`invalid value: 2, expected 0`

**Comment by teohaik** [comment]
@kchalkias

**Comment by joyqvq** [comment]
where did you get that tx data bytes from? transaction builder?

**Comment by linziwen** [comment]
I got the similar problem:

my txByte was return by calling sui_paySui

sui keytool sign --address 0x9f3a69cd7e50910ecc1bc291891ebac9e920848c --data AAUFD2C9OKReYlKARllj6XtUBihLP2XvRQoAAAAAACCM2ecz1pQgAwP6l/meXHHLRJiYo4bRSabX3bGsdmtXiDo/aOxOxBMHbsjMQRwzRy4N9zUD70UKAAAAAAAghZXYuenvjSvhpxZiTxy3VnSEjcefgSECzHILhla+q9t0ImotfmCm6uperlza/TzN2ZaqWAoFAAAAAAAAIA4xedIFnnwXwFhkt+aEbI1jURNVrGody1OmUmEZ09avdRAZfUtIMyBYTUCwDVzBLnZxIcMKBQAAAAAAACBcCl2EzkOIKVTIRSrexk5bmyBo+f5INzUB7yU0FL27KKCzZiUQgck8BKUlDB8LKED1pfLiCgUAAAAAAAAg9esEE9qouO+M3b2LnatrkmalsSgHiApsfsv8vglO7OwBvmUnKpLFCLTzg75zP1J1bCnaoqgBgPD6AgAAAACfOmnNflCRDswbwpGJHrrJ6SCEjA9gvTikXmJSgEZZY+l7VAYoSz9l70UKAAAAAAAgjNnnM9aUIAMD+pf5nlxxy0SYmKOG0Umm192xrHZrV4hpAAAAAAAAAIgTAAAAAAAA

return:
Intent message to sign: AAUFD2C9OKReYlKARllj6XtUBihLP2XvRQoAAAAAACCM2ecz1pQgAwP6l/meXHHLRJiYo4bRSabX3bGsdmtXiDo/aOxOxBMHbsjMQRwzRy4N9zUD70UKAAAAAAAghZXYuenvjSvhpxZiTxy3VnSEjcefgSECzHILhla+q9t0ImotfmCm6uperlza/TzN2ZaqWAoFAAAAAAAAIA4xedIFnnwXwFhkt+aEbI1jURNVrGody1OmUmEZ09avdRAZfUtIMyBYTUCwDVzBLnZxIcMKBQAAAAAAACBcCl2EzkOIKVTIRSrexk5bmyBo+f5INzUB7yU0FL27KKCzZiUQgck8BKUlDB8LKED1pfLiCgUAAAAAAAAg9esEE9qouO+M3b2LnatrkmalsSgHiApsfsv8vglO7OwBvmUnKpLFCLTzg75zP1J1bCnaoqgBgPD6AgAAAACfOmnNflCRDswbwpGJHrrJ6SCEjA9gvTikXmJSgEZZY+l7VAYoSz9l70UKAAAAAAAgjNnnM9aUIAMD+pf5nlxxy0SYmKOG0Umm192xrHZrV4hpAAAAAAAAAIgTAAAAAAAA

Signer address: 0x9f3a69cd7e50910ecc1bc291891ebac9e920848c

invalid value: 5, expected 0
