### ISSUE TITLE
[Coin standard] Add check whether an object is coin

### ISSUE THREAD

**Issue by JackyWYX** [MystenLabs/sui#7601]
## Proposal

Add a function in `coin.move` to check whether a given object is of coin type without giving type generic T. 

E.g. 

```
public fun is_coin(object: UID): bool {
    ...
}

public fun get_coin_asset_id(object: UID): vector<u8> {
    ...
}
```

### Rationale

We are looking for a solution to protect user's assets with different permission granularities for transferring coins and transferring objects. However, since coin can also be objects, it is likely that some malicious user may bypass the coin permission by transferring the coin object. We wonder whether there could be an on-chain solution for object coin type assertion.

**Comment by PaulFidika** [comment]
An entry function can't return a value. Is the intention that this is to be consumed by an off-chain process, and that this will be used as a devInspect call? (I call them view-functions.)

I'm not understanding your use-case rationale; could you elaborate?

**Comment by PaulFidika** [comment]
If you pass in a UID, it's not possible to tell what object type contains that UID. But if you pass in a reference to the object itself, I can definitely determine at runtime if that object is a coin or not (regardless of the T type param). I can write up a function like that for you.

**Comment by sblackshear** [comment]
Also, `Typename` may be useful if you have a `Coin<T>` in hand and want to special-case certain `T`'s: https://github.com/MystenLabs/sui/blob/main/crates/sui-framework/deps/move-stdlib/sources/type_name.move

**Comment by JackyWYX** [comment]
> If you pass in a UID, it's not possible to tell what object type contains that UID. But if you pass in a reference to the object itself, I can definitely determine at runtime if that object is a coin or not (regardless of the T type param). I can write up a function like that for you.

Thanks for the swift response. It's actually a public function instead of entry function. I have updated the comment. 

Does the added function need a native function support?

**Comment by JackyWYX** [comment]
> Also, `Typename` may be useful if you have a `Coin<T>` in hand and want to special-case certain `T`'s: https://github.com/MystenLabs/sui/blob/main/crates/sui-framework/deps/move-stdlib/sources/type_name.move

Thanks! Noted!!

**Comment by PaulFidika** [comment]
> 

I wrote this up right here:

https://github.com/0xcapsules/capsules/blob/1cfe5b3c976395e6d6abcf02ca712ee7f024351c/packages/sui_utils/sources/encode.move#L113

I can't guarantee I won't rewrite the API of this module in the near future; I think it needs to be sharpened some. But it's good for now. This won't work on UID, but it will work on any type T you supply.

Could you explain your use-case a little more? There might be a better way to architect it.

**Comment by PaulFidika** [comment]
I think generally what you might want is something like

`object::get_type(uid: &UID): ascii::String`

kind of like a general-purpose function that can tell the type of the containing object (if any--it might not be embedded in anything yet). That would be pretty useful generally.

Does that solve your use-case?

**Comment by sblackshear** [comment]
@PaulFidika: cool stuff re: the `encode` module! Would love to see that go into Sui Move or Move upstream if you're interested in seeing parts of that become canonical.

**Comment by JackyWYX** [comment]
Yep, the generic solution can definitely solve my use case. For this function, it will require the caller to specify input T which can partially solve our use case. But the generic one could be much much better. Looking forward to the generic solution! When do you think we may have it on devnet?

**Comment by PaulFidika** [comment]
> @PaulFidika: cool stuff re: the `encode` module! Would love to see that go into Sui Move or Move upstream if you're interested in seeing parts of that become canonical.

Thanks! I have a lot of functions now that I'd love to add to the sui core; I think most of Sui Utils could be merged into the Sui framework itself:

https://github.com/0xcapsules/capsules/tree/1cfe5b3c976395e6d6abcf02ca712ee7f024351c/packages/sui_utils/sources


> Yep, the generic solution can definitely solve my use case. For this function, it will require the caller to specify input T which can partially solve our use case. But the generic one could be much much better. Looking forward to the generic solution! When do you think we may have it on devnet?

Okay so the function would look something like this perhaps (idk how feasible it is):

`sui::object::type(uid: &UID): ascii::String`

and the string could be parsed to figure out the package-id / module-name / struct-name / generic as needed. Is that what you'd like to see? (Idk how feasible that would be but it would be nice to have I agree.)

**Comment by sblackshear** [comment]
> idk how feasible it is

This would only be possible if the object whose `UID` this is also happens to be a tx input, in which case there are easier ways to get its type. In Sui, the general rule of thumb is: any objects you want to touch or look at either have to be tx inputs or (direct or transitive) dynamic fields of tx inputs.
