### ISSUE TITLE
Sui doc content issue: Object Ownership Link in Object Learn Section

### ISSUE THREAD

**Issue by jnaulty** [MystenLabs/sui#7727]
URL: https://docs.sui.io/devnet/build/programming-with-objects/ch1-object-basics#store-sui-object
[GitHub Code Link](https://github.com/MystenLabs/sui/blame/e37cef7c2711748ff9316d1ba3b4f9f50787bf5a/doc/src/build/programming-with-objects/ch1-object-basics.md#L60)

The `Object Ownership` link returns this URL https://docs.sui.io/devnet/build/learn/objects#object-ownership this returns a `404` error

<img width="806" alt="image" src="https://user-images.githubusercontent.com/6826729/214913594-a40fc74b-3a92-4202-a603-5b4f06bc26a4.png">
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/6826729/214913639-ec4431e6-cbfe-437c-be58-bb8435ec1ff1.png">

**Comment by randall-Mysten** [comment]
Thanks for reporting. I added a commit to your PR to correct the link.
