### ISSUE TITLE
Do not use f64 for STORAGE_REBATE_RATE

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#7732]
https://github.com/MystenLabs/sui/blob/80996ed8f93be1a3c61724c8c96feb614bf4f0df/crates/sui-protocol-constants/src/lib.rs
We should avoid floating point numbers to prevent from nondeterministic computation

**Comment by dariorussi** [comment]
https://github.com/MystenLabs/sui/pull/8102
