### ISSUE TITLE
Consider making gas_price an optional field

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#7735]
And if it's None, just default to reference gas price.

**Comment by PaulFidika** [comment]
What is gas_price and what is the context? I'm assuming that every tx uses up gas_units, and that on devnet we've seen a fixed 1 gas_unit = 1 nanoSUI price, whereas on testnet there is now a 1 gas_unit = <variable> nanoSUI price relationship that changes every epoch.

For the Sui CLI, I find it annoying that I always need to specify `--gas-budget` when in reality I don't care and would prefer if it would default to some large-enough-most-of-the-time value.

**Comment by dariorussi** [comment]
we are considering leaving the `gas_price` as is (non `Optional`).
We have not received much feedback about making it optional, it is something clients (wallet and apps) can hide, and it makes slightly easier to run history transaction.
Not clear there is much benefit.
