### ISSUE TITLE
Wallet import issue

### ISSUE THREAD

**Issue by Romainua** [MystenLabs/sui#7750]
Generate new wallet via `sui client new-address <schema>` it will provide Secret Recovery Phrase
If address was created via secp256r1 or secp256k1 schema and Import as new address into wallet it will be differently address
than was showing on cli.

**Comment by stefan-mysten** [comment]
Only ED25519 keypairs are supported by the Sui Wallet, therefore while you can import a key generated with the two schemas via its recovery phrase, it will be converted into a ED25519 keypair, and thus resulting in a different address.
