### ISSUE TITLE
**new** staking sui 

### ISSUE THREAD

**Issue by Starlew77** [MystenLabs/sui#7768]
Hi 

just went to to test features 

MY Wallet been wiped from yesterday no sui in wallet but no way of being able to stake sui please advise ? how can i take part :)
![20230127_135359](https://user-images.githubusercontent.com/116558527/215103622-44e97f66-546d-49e1-9aa2-6638bde1fe80.jpg)

**Comment by randall-Mysten** [comment]
Hi @Starlew77 Yes there is some confusion here. They removed the button from the wallet and you have to go to the Testnet faucet Discord channel to get tokens now. https://discord.com/channels/916379725201563759/1037811694564560966

**Comment by randall-Mysten** [comment]
You wallet was probably wiped with the release on Wed. The new wallet defaults to Testnet. You can still change it back to Devnet if you want to continue using it

**Comment by Starlew77** [comment]
hi randal thank you
