### ISSUE TITLE
[feature] `sui_devInspectTransaction` foregivness

### ISSUE THREAD

**Issue by FrankC01** [MystenLabs/sui#7770]
Currently (0.23.0): `sui_devInspectTransaction` will fail if the gas coin used does not have enough gas to cover the gas. cost.

Ideally, an additional parameter to the call that 'disables' coin balance checking would allow more flexibility to the caller.

Story:
Before a consumer goes through merging coins to support the real transaction, allow an inspection to verify and get the gas cost for their consideration in committing to the chain.

**Comment by 666lcz** [comment]
Thanks for the suggestion @FrankC01 ! This has been fixed in https://github.com/MystenLabs/sui/pull/7372 where you no longer need to specify a gasPayment for `sui_devInspectTransaction` and will be released in 0.24.0
