### ISSUE TITLE
Sui doc content issue or request

### ISSUE THREAD

**Issue by sangeetapagare** [MystenLabs/sui#7809]
If this is an issue with existing content, provide the URL or GitHub path to the topic. Otherwise, use **New**.

Describe the issue or request. Provide as much detail as possible. For issues, it is helpful to copy the specific section of the topic into the issue.
    
Thank you for taking the time to let us know about the issue or request. We triage all new issues and requests within 2 business days. We will follow up if we need additional information.

**Comment by georgescharlesbrain** [comment]
Hi,

I assume you were trying out the issue creation process here?

Thanks for closing this issue if it's not required anymore.

Note that currently, the Sui wallet is still under development. This means that sometimes, some bugs can slip in. However, the bugs are often solved a couple of days later. Should you want instant feedback on your challenges, I'd recommend contacting the Sui community on [Discord](https://discord.gg/sui). The community is often more responsive on wallet issues there. Deleting and reinstalling the wallet could also help when the network was recently restarted.

Have a wonderful day.

**Comment by georgescharlesbrain** [comment]
Hi,

I assume you were trying out the issue creation process here?

Thanks for closing this issue if it's not required anymore.

Note that currently, the Sui wallet is still under development. This means that sometimes, some bugs can slip in. However, the bugs are often solved a couple of days later. Should you want instant feedback on your challenges, I'd recommend contacting the Sui community on [Discord](https://discord.gg/sui). The community is often more responsive on wallet issues there. Deleting and reinstalling the wallet could also help when the network was recently restarted.

Have a wonderful day.
