### ISSUE TITLE
appearance problem

### ISSUE THREAD

**Issue by yadavpagare** [MystenLabs/sui#7811]
we cant find the options for testing in the app after launce of wave 2 on laptop but those options visible in the phone

**Comment by georgescharlesbrain** [comment]
Hi,

Thanks for testing out the Sui wallet. Currently, the Sui wallet is still under development. This means that sometimes, some bugs can slip in. However, the bugs are often solved a couple of days later.

Note that the wallet currently communicates to devnet or testnet, which are restarted every couple of weeks. The result is that all assets (which do not hold any value) are wiped.

After a network reset, the following steps could help:

*   Update the wallet
*   Change the language of your Chrome browser to English (and delete other languages)
*   Clear the site data of the website you are having issues with in chrome. (Paste "chrome://settings/content/all?searchSubpage" in your search bar)
*   Delete and reinstall the wallet

Is your issue still not solved? I'd recommend the [Sui Discord](https://discord.gg/sui). The community is often more responsive on wallet issues there.

Have a wonderful day.
