### ISSUE TITLE
Sui doc content issue or request

### ISSUE THREAD

**Issue by pagareritesh** [MystenLabs/sui#7866]
we cant find the options for testing in the app after launce of wave 2 on laptop but those options visible in the phonedditional information.

**Comment by pagareritesh** [comment]
we cant find the options for testing in the app after launce of wave 2 on laptop but those options visible in the phone

**Comment by georgescharlesbrain** [comment]
Hi pagareritesh,

Can you provide a screenshot of what you are referring to with "options visible in the phone"?

Thx
