### ISSUE TITLE
Sui doc content issue or request

### ISSUE THREAD

**Issue by aasusoled** [MystenLabs/sui#7871]
If this is an issue with existing content, provide the URL or GitHub path to the topic. Otherwise, use **New**.

Describe the issue or request. Provide as much detail as possible. For issues, it is helpful to copy the specific section of the topic into the issue.

Thank you for taking the time to let us know about the issue or request. We triage all new issues and requests within 2 business days. We will follow up if we need additional information. 
we face some problem to find links in laptop and those links are easly found in the mobile app version

**Comment by aasusoled** [comment]
we face some problem to find links in laptop and those links are easly found in the mobile app version

**Comment by georgescharlesbrain** [comment]
Hi aasusoled,

Do you mean that you can't find something using the search of the docs via the browser?

**Comment by randall-Mysten** [comment]
Hi @aasusoled Do you mean the links in the footed, the side nav? Do you have a screenshot? We're currently re building the site and would appreciate more detail here. Cheers
