### ISSUE TITLE
**new**Sui staking provider

### ISSUE THREAD

**Issue by Starlew77** [MystenLabs/sui#7882]
hi 

this stake provider no  working to be able to stake , when trying to stake just opens wallet but no functon to atually stake 

![20230130_091900](https://user-images.githubusercontent.com/116558527/215436964-0f9cc23c-0690-4338-ae35-9ccba962c218.jpg)
ow up if we need additional information. 

This one staked but wallet has gone blank and as you can see nothing there at all showing in wallet , once closed and reopened has staked coin, and wallet has registered the stake :) if possible if there is anymore coins as unable to use discord :( so i can test further be great thank you :) i

kind regards 

steve 
![20230130_092401](https://user-images.githubusercontent.com/116558527/215438036-c0a374be-4ab4-4bc0-b683-a485f42b07a1.jpg)

**Comment by randall-Mysten** [comment]
I see several similar reports of this behavior, looks like something with the network. Going to wait a day or two to see if resolves

**Comment by Starlew77** [comment]
thank you :)
