### ISSUE TITLE
Sui doc content issue or request

### ISSUE THREAD

**Issue by tryKampgig** [MystenLabs/sui#7884]
With love from a community member, I did the test net wave1 and everything was smooth and running, but my only observation was my capy and my history got deleted after some time. I gave my feedback on the discord group , recently i have been trying to participate in the test net wave 2, but I always observe my faucet request always goes to the devnet instead of testnet, maybe they might be an issue somewhere, i am also trying to run a node following the procedure, here is my wallet address, 
0xb632f24cb6b31580a1b7611738d1256e1dbb1d2b
please your feedback will be important to me

with love from a community member

**Comment by randall-Mysten** [comment]
I @tryKampgig I replied to your email as well. Update the the latest version of the wallet, use the #testnet-faucet channel in Discord during Testnet Wave2, and see the docs on the Latest build for an update to Full node set up for Testnet.
