### ISSUE TITLE
Sui doc content request - reference to a collaborative YouTube playlist

### ISSUE THREAD

**Issue by georgescharlesbrain** [MystenLabs/sui#7886]
Request for a collaborative YouTube playlist under the official Sui channel.

YouTube is full of low-quality airdrop and spam content about Sui. It's difficult to surface the good talks. The official channel has some great AMAs, but I also learned much from external interviews with the founders. The quality content I could find is currently added to [this collaborative playlist](https://www.youtube.com/playlist?list=PLIQc7_iETjBw-SNAbhrfB7RDufbJ5Bi21) under my own personal channel.

YouTube videos can be added to the playlist using [this](https://www.youtube.com/playlist?list=PLIQc7_iETjBw-SNAbhrfB7RDufbJ5Bi21&jct=ZPW7Z71SqDPkWczH4sR2xcGn_yYMzA) link.

**Comment by randall-Mysten** [comment]
Great suggestion. I believe that this is in the works. We'll also link out to official videos from docs at some point. Appreciate the continued feedback!
