### ISSUE TITLE
Rust SDK querying events with leading zero doesn't work

### ISSUE THREAD

**Issue by porkbrain** [MystenLabs/sui#8037]
## Steps to Reproduce Issue

Trying to fetch events with a filter based on the type from a package that starts with leading zero fails. Removing the zero works.

For example, if the package id is `0x0bdc863b06ab02a376d07159f2ad2292e1f208fd`, then this yields events:

```rust
let event = EventQuery::MoveEvent("0xbdc863b06ab02a376d07159f2ad2292e1f208fd::collection::CollectionMintEvent");
sui
  .event_api()
  .get_events_stream(event, cursor, is_descending)
```

while this doesn't:

```rust
let event = EventQuery::MoveEvent("0x0bdc863b06ab02a376d07159f2ad2292e1f208fd::collection::CollectionMintEvent");
sui
  .event_api()
  .get_events_stream(event, cursor, is_descending)
```

## Expected Result

It should work also for leading zero in the package ID.

## System Information

* `devnet-0.23.0`

## Related

- https://github.com/MystenLabs/sui/issues/8017

**Comment by bausano** [comment]
The inconsistency in my automation stems from the fact that the CLI when printing object IDs, prints the pretending zero. E.g.:

```
sui client publish \
  --gas-budget 30000 \
  --json \
  "${package_dir}" | jq -r '.effects.created[] | select( .owner == "Immutable" ) | .reference.objectId'
```

This would print `0x0bdc863b06ab02a376d07159f2ad2292e1f208fd`. It'd be convenient to either accept both hex with or without the pretending zero, or make printing of object IDs consistent,
