### ISSUE TITLE
[crypto] Basic CLI tool (like keytool) to generate ECVRF proofs

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/sui#8069]
let's call it cryptotool and down the road put all useful crypto functionality here, so at least users have a reference.
It's fine for this tool to stay in Sui vs fastcrypto.
cc: @joyqvq @Eis-D-Z @StefPler @geomel @benr-ml

**Comment by joyqvq** [comment]
do we want this to be in sui? ie user needs to build the entire sui binary to use them. if we don't use anything directly depends on sui, does it make sense to put it in fastcrypto? a cli tool to call all fastcrypto apis.

**Comment by kchalkias** [comment]
@joyqvq Anything would work, let's do the easiest and lighter

**Comment by benr-ml** [comment]
+1 for adding it to fastcrypto, and keeping it as light as possible

**Comment by jonas-lj** [comment]
This issue is closed by a PR in fastcrypto: https://github.com/MystenLabs/fastcrypto/pull/405.
