### ISSUE TITLE
[TypeScript SDK] Support more transaction types for local deserialization

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#8071]
Support `paySui` and `payAllSui` and other missing transaction types for deserialization

https://github.com/MystenLabs/sui/blob/devnet-0.24.0/sdk/typescript/src/signers/txn-data-serializers/local-txn-data-serializer.ts#L438

**Comment by healthydeve** [comment]
https://github.com/MystenLabs/sui/commit/ebe6c39453fdd4cc97f2b4869b9a96231825cbed
