### ISSUE TITLE
Is jaeger tracing disabled?

### ISSUE THREAD

**Issue by adjih** [MystenLabs/sui#8074]
This is about the documentation for Telemetry - using sui from the branch devnet (currently 0.24.x) - and Jaeger.

We were trying to use the  `Jaeger` tracing mentioned at: https://docs.sui.io/contribute/observability#jaeger-seeing-distributed-traces
It seems that it had been removed: 
* from looking at commit c0ad722ad97f554a14d7ca54f78df3ed51e4f3a8  
* seeing that `sui start` no longer sends data to Jaeger UDP ports

But it is still currently mentioned at: https://github.com/MystenLabs/sui/blob/devnet/crates/telemetry-subscribers/README.md 
Thus it is not entirely clear if it has been removed, or something else is needed to enable it. (it was necessary to set `TOKIO_JAEGER` env var previously).

**Comment by randall-Mysten** [comment]
Hi @adjih Sorry for the confusion and outdated info in the repo. I'll track this down and make the updates necessary. Appreciate you taking time to let us know about this.
