### ISSUE TITLE
[Move] Make sure that we don't have to re-fetch/deserialize same package during Move call

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#809]
During Move call execution, if a dependent module is needed, right now we would go fetch it from the on-chain store, and the VM would deserialize it and get the relevant module.
Since packages are immutable, we shouldn't need to do this repeat. We should cache it. Ideally the caching should be done in the VM, to avoid both fetching and deserializing.
Not sure if the Move VM already does it, maybe it does? Need to verify.

**Comment by gdanezis** [comment]
Quick Q on this: are all dependent modules passed in as input objects or is the move vm fetching some dynamically as well?

**Comment by lxfind** [comment]
> Quick Q on this: are all dependent modules passed in as input objects or is the move vm fetching some dynamically as well?

Direct dependencies are passed in as input objects. However indirect dependencies (i.e. dependencies or direct dependencies) are not. This is the reason we are passing AuthorityStore to TemporaryAuthorityStore as a backing package store.
