### ISSUE TITLE
[fastx adapter] choose gas costs

### ISSUE THREAD

**Issue by sblackshear** [MystenLabs/sui#81]
There are two kinds of costs for us to reflect: computation, and storage. Some decisions to be made:

# Storage
1. How much do we charge per byte of storage?
2. Do we charge only for the storage of the order itself, or also for the storage of the objects it creates?
3. What should the upper limit on the size of transactions be?
4. What should the upper limit on the total size of objects created by a transaction be?
5. What should the upper limit on the size of an individual object be?

# Computation

1. The Move VM allows us to [configure](https://github.com/diem/diem/blob/main/language/move-vm/types/src/gas_schedule.rs) the gas costs of individual bytecode instructions. What values should we choose?
2. What should we choose for the gas costs of native order types (e.g., transfer)?

**Comment by bholc646** [comment]
I'm guessing most of this has to be figured out or is captured directly in https://github.com/MystenLabs/sui/issues/1122

**Comment by oxade** [comment]
> Can this be closed @oxade?

@bholc646 I'll consolidate all the issues
