### ISSUE TITLE
[bug] sui_devInspectTransaction failing on 0.24.0 devnet

### ISSUE THREAD

**Issue by FrankC01** [MystenLabs/sui#8119]
In order to accommodate the new input to the subject RPC call, I have BCS serialized the SingleTransactionKind(PaySui) whichi produces the following bytes (put in u8 list for convenience):
```rust
[0, 5, 1, 20, 87, 32, 11, 222, 234, 36, 110, 94, 59, 37, 198, 115, 35, 47, 235, 70, 8, 226, 156, 93, 176, 2, 0, 0, 0, 0, 0, 0, 32, 155, 239, 255, 8, 3, 94, 134, 142, 215, 65, 22, 72, 140, 168, 45, 239, 22, 80, 186, 104, 63, 8, 70, 178, 190, 97, 159, 100, 116, 173, 41, 52, 1, 20, 212, 120, 254, 173, 89, 93, 24, 147, 228, 177, 174, 173, 38, 105, 189, 176, 159, 224, 227, 15, 1, 64, 66, 15, 0, 0, 0, 0, 0]
```

And the base64 string from above bytes:
```bash
AAUBFFcgC97qJG5eOyXGcyMv60YI4pxdsAIAAAAAAAAgm+//CANeho7XQRZIjKgt7xZQumg/CEayvmGfZHStKTQBFNR4/q1ZXRiT5LGurSZpvbCf4OMPAUBCDwAAAAAA
```

But I am getting:
`Inspect failure -> {'code': -32000, 'message': 'invalid length 0, expected an byte array of size 32'} `

There are more details in [forum](https://forums.sui.io/t/bcs-transactionkind-for-sui-devinspecttransaction-paysui/4776)

Also, if I just take the tx_bytes result of calling `sui_paySui` and feed the tx_bytes from that into devInspectTransaction, it fails as well.

**Comment by FrankC01** [comment]
@tnowacki @amnn 

I don't know if any `sui_devInspectTransaction` works.

I’ve just tried TransferObject and pretty much get the same results. If I structure it as in crate messages.rs (note that in schema the fields are reversed)
```rust
pub struct TransferObject {
    pub recipient: SuiAddress,
    pub object_ref: ObjectRef,
}
```
I get this array: 
```bash
[0, 0, 20, 212, 120, 254, 173, 89, 93, 24, 147, 228, 177, 174, 173, 38, 105, 189, 176, 159, 224, 227, 15, 20, 87, 32, 11, 222, 234, 36, 110, 94, 59, 37, 198, 115, 35, 47, 235, 70, 8, 226, 156, 93, 176, 2, 0, 0, 0, 0, 0, 0, 32, 155, 239, 255, 8, 3, 94, 134, 142, 215, 65, 22, 72, 140, 168, 45, 239, 22, 80, 186, 104, 63, 8, 70, 178, 190, 97, 159, 100, 116, 173, 41, 52]
```

base64 encoded: 
```bash
AAAU1Hj+rVldGJPksa6tJmm9sJ/g4w8UVyAL3uokbl47JcZzIy/rRgjinF2wAgAAAAAAACCb7/8IA16GjtdBFkiMqC3vFlC6aD8IRrK+YZ9kdK0pNA==
```
And this error: 
`Inspect failure -> {'code': -32000, 'message': 'invalid length 0, expected an byte array of size 32'}`

If I change the field order as in schema:
I get this array: 
```bash
[0, 0, 20, 87, 32, 11, 222, 234, 36, 110, 94, 59, 37, 198, 115, 35, 47, 235, 70, 8, 226, 156, 93, 176, 2, 0, 0, 0, 0, 0, 0, 32, 155, 239, 255, 8, 3, 94, 134, 142, 215, 65, 22, 72, 140, 168, 45, 239, 22, 80, 186, 104, 63, 8, 70, 178, 190, 97, 159, 100, 116, 173, 41, 52, 20, 212, 120, 254, 173, 89, 93, 24, 147, 228, 177, 174, 173, 38, 105, 189, 176, 159, 224, 227, 15]
```
base64 encoded: 
```bash
AAAUVyAL3uokbl47JcZzIy/rRgjinF2wAgAAAAAAACCb7/8IA16GjtdBFkiMqC3vFlC6aD8IRrK+YZ9kdK0pNBTUeP6tWV0Yk+Sxrq0mab2wn+DjDw==
```

This error:
`Inspect failure -> {'code': -32000, 'message': 'unexpected end of input'}`

**Comment by amnn** [comment]
Thanks for flagging @FrankC01, also looping in @666lcz who works on our TypeScript SDK.

**Comment by FrankC01** [comment]
Ok, FYI: This is not through Typescript 
Just wanted to note that.

**Comment by amnn** [comment]
Yep, I get you, but Chris might have visibility on how the serialization changed in v0.24.0, as he will have had to deal with any changes for the TS SDK as well.

**Comment by 666lcz** [comment]
@FrankC01 sorry for the lack of documentation but it's expected that `paySui` and `payAllSui` has not been supported for DevInspect.

I'am pretty sure `moveCall` and `pay`(as opposed to `paySui`) are working well against devnet: https://github.com/MystenLabs/sui/blob/main/sdk/typescript/test/e2e/dev-inspect.test.ts. I'll add tests for the other TransactionKinds as well.

**Comment by FrankC01** [comment]
@666lcz I will try out `pay` and `movecall` and respond to this discussion with results.

**Comment by PaulFidika** [comment]
Glad I'm not the only one; I spent about 8 hours on Sunday trying to get devInspect to work with Typescript SDK and with curl commands, and nothing worked.

Why was the original sui_devInspectMoveCall deprecated in v0,24. That was working fine and was far more convenient. Now with curl commands I need to do two hops; first to get the base64 serialized transaction, and then again to submit the serialized transaction. Seems like the deprecation was a move backwards.

**Comment by FrankC01** [comment]
@666lcz 
`pay` fails with:
```bash
[0, 4, 1, 20, 87, 32, 11, 222, 234, 36, 110, 94, 59, 37, 198, 115, 35, 47, 235, 70, 8, 226, 156, 93, 176, 2, 0, 0, 0, 0, 0, 0, 32, 155, 239, 255, 8, 3, 94, 134, 142, 215, 65, 22, 72, 140, 168, 45, 239, 22, 80, 186, 104, 63, 8, 70, 178, 190, 97, 159, 100, 116, 173, 41, 52, 1, 20, 212, 120, 254, 173, 89, 93, 24, 147, 228, 177, 174, 173, 38, 105, 189, 176, 159, 224, 227, 15, 1, 64, 66, 15, 0, 0, 0, 0, 0]

AAQBFFcgC97qJG5eOyXGcyMv60YI4pxdsAIAAAAAAAAgm+//CANeho7XQRZIjKgt7xZQumg/CEayvmGfZHStKTQBFNR4/q1ZXRiT5LGurSZpvbCf4OMPAUBCDwAAAAAA

Inspect failure -> {'code': -32000, 'message': 'invalid length 0, expected an byte array of size 32'}
```

**Comment by 666lcz** [comment]
@FrankC01 @PaulFidika sorry for the late response since the team is busy at an offsite this week! Thank you for all your valuable feedback and I will try my best to improve the interface and address the concern ASAP (ideally before the next DevNet release)

However, I haven't been able to repro this on DevNet in my first attempt. Here's my [code](https://github.com/666lcz/sui-sdk-test-scripts/pull/1/files) and [output](https://gist.github.com/666lcz/a751c7608a874aa543d89d0dad35b936), including the raw txn input, Transaction kind, BCS bytes, Base64 encoded string, and DevInspect result. @FrankC01 do you mind giving me the raw transaction input? 

Regardless I will keep investigating after the offsite ends tomorrow

**Comment by FrankC01** [comment]
@666lcz 
Good news. I got `Pay` and `Call` working. The order of BCS serialization needs to align to the Rust struct property order and NOT the `rpc.discover` Schema entries for same. 

Tested in 0.25.0
Still having errors for the other SingeTransactionKinds, such as `PaySui` which returns: 
`Inspect failure -> {'code': -32000, 'message': 'SUI payment transactions use first input coin for gas payment, but found a different gas object.'}`

**Comment by jaredcosulich** [comment]
Hi @666lcz - we've seen a number of different errors coming through, including the bcs issue. I'll see if I can't get any into a simpler state, but this one happens consistently. It seems to be related to the inclusion of a type argument. Here is the call data:

```js
{
    "kind": "moveCall",
    "data": {
        "packageObjectId": "0x88f243bedb9a612ba456270e2c62b691f608838a",
        "module": "token_gated_ticket",
        "function": "redeem_ticket",
        "typeArguments": [
            "0x4c10b61966a34d3bb5c8a8f063e6b7445fc41f93::capy::Capy"
        ],
        "arguments": [
            "0xc5c33c1ffc1c52654447ee2aad61ff51d17ea792",
            "0xf7f8750a4fb072868f34d64bac8fa03c4523b0be",
            "0x8493f3bc6da150517bdb012068a07e50e526a0cb"
        ],
        "gasBudget": 30000,
        "gasPayment": "0x05b2878903a3110e9f1a07d01b2634674ca24fff"
    }
}
```

The error is:

```
Encountered error when serializing a moveCall transaction for address d4c4c0f3c6eae1bec838442a49bacc358fdc3c5b for transaction {
  "kind": "moveCall",
  "data": {
    "packageObjectId": "0x88f243bedb9a612ba456270e2c62b691f608838a",
    "module": "token_gated_ticket",
    "function": "redeem_ticket",
    "typeArguments": [
      "0x4c10b61966a34d3bb5c8a8f063e6b7445fc41f93::capy::Capy"
    ],
    "arguments": [
      "0xc5c33c1ffc1c52654447ee2aad61ff51d17ea792",
      "0xf7f8750a4fb072868f34d64bac8fa03c4523b0be",
      "0x8493f3bc6da150517bdb012068a07e50e526a0cb"
    ],
    "gasBudget": 30000,
    "gasPayment": "0x05b2878903a3110e9f1a07d01b2634674ca24fff"
  }
}: Error: Unknown call arg type {
  "Reference": {
    "TypeParameter": 0
  }
} for value "0xc5c33c1ffc1c52654447ee2aad61ff51d17ea792"
```

This transaction goes through fine when actually submitted.

**Comment by FrankC01** [comment]
Here is where I've tested. I did not try `ChangeEpoch` or `Genesis`:
```bash
MoveCall inspect success
Pay inspect success
PaySui inspect failure -> {'code': -32000, 'message': 'SUI payment transactions use first input coin for gas payment, but found a different gas object.'}
PayAllSui inspect failure -> {'code': -32000, 'message': 'SUI payment transactions use first input coin for gas payment, but found a different gas object.'}
TransferObject inspect success
TransferSui inspect success
Publish inspect failure -> {'code': -32000, 'message': 'Transaction kind Transaction Kind : Publish\n is not supported in dev-inspect'}
```

**Comment by FrankC01** [comment]
@jaredcosulich How are you building the BCS encoded TransactionKind for the tx_bytes argument into `sui_devInspectTransaction`?

**Comment by jaredcosulich** [comment]
I'm not, this is going through the typescript SDK `devInspectTransaction`, which takes an `UnserializedSignableTransaction`

**Comment by jaredcosulich** [comment]
So it's certainly possible that the typescript SDK isn't serializing the transaction data properly. I haven't looked closely at the implementation details there.

**Comment by FrankC01** [comment]
@jaredcosulich OK. So there is another trick that works on RPC:
Take the tx_bytes from the submitted (not signed) `sui_moveCall`
1. Decode from base64
2. Encode (back to base64) all of step 1 but the last 97 bytes. These 97 are the budget and gas objects
3. Use the new base64 string as input of bytes in the `sui_devInspectTransaction`

It's a hack but it currently works.

**Comment by jaredcosulich** [comment]
Good to know!

**Comment by FrankC01** [comment]
@amnn @tnowacki @666lcz 
sui_transferSui is an odd one when inspecting.

In the normal call, a `sui_object_id` is identified (required field) however;
The BCS (tx_bytes) returned does **not** contain the coin and
If I construct the BCS, the `TransferSui` only contains the recipient and (optional) amount

Why no `sui_object_id` `ObjectRef` ?

**Comment by tnowacki** [comment]
> @amnn @tnowacki @666lcz sui_transferSui is an odd one when inspecting.
> 
> In the normal call, a `sui_object_id` is identified (required field) however; The BCS (tx_bytes) returned does **not** contain the coin and If I construct the BCS, the `TransferSui` only contains the recipient and (optional) amount
> 
> Why no `sui_object_id` `ObjectRef` ?

transferSui probably should be banned in the current iteration of dev_inspect, since there really isn't a gas coin to transfer. It was banned in some of the Pay variants due to some implementation quirks for those transactions. 

Though it should all work just fine when programmable transactions come along

**Comment by tnowacki** [comment]
> @jaredcosulich OK. So there is another trick that works on RPC: Take the tx_bytes from the submitted (not signed) `sui_moveCall`
> 
> 1. Decode from base64
> 2. Encode (back to base64) all of step 1 but the last 97 bytes. These 97 are the budget and gas objects
> 3. Use the new base64 string as input of bytes in the `sui_devInspectTransaction`
> 
> It's a hack but it currently works.

Thanks for this! This made us realized where exactly the bug was, and should be fixed in 
https://github.com/MystenLabs/sui/pull/8240 
(note dev-inspect isn't supported on non-MoveCall transactions by the Sui JSON RPC transaction builder)

**Comment by FrankC01** [comment]
@tnowacki Can you elaborate what the bug is? How will things change when the PR is merged?

**Comment by FrankC01** [comment]
I either use 
- The tx_bytes return from calling said type (`sui_transferObject`, etc,) and just slice off the last 97 bytes as I provided that hint above. Hack really, but let's call it a "hint" :)
- I construct from bottom up using Python implemented `BCSTransactionKind` etc. etc.

I have confirmed the byte string from both are equal.

And this led me to realize there was no 'object' or 'coin' in the `sui_transferSui`

**Comment by tnowacki** [comment]
> The tx_bytes return from calling said type (sui_transferObject, etc,) and just slice off the last 97 bytes as I provided that hint above. Hack really, but let's call it a "hint" :)

These are the RPC transaction builders right? I'm not as familiar with that space, but we have some further cleanup to help support full transaction payloads. 

> I construct from bottom up using Python implemented BCSTransactionKind etc. etc.

With a local transaction builder, you should just be able to construct only the single transaction kind (without any byte manipulation)

**Comment by FrankC01** [comment]
@tnowacki 

Yes, I have both single and batch working ok, of course Publish, PaySui and PayAllSui are not working yet. Is there a PR for these?
