### ISSUE TITLE
Mutations to dynamic field objects should not show up in effects if execution failed

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#8125]
This is needed to bound the effects size in all cases.

**Comment by lxfind** [comment]
@gdanezis in case I missed anything

**Comment by tnowacki** [comment]
I was mistaken, this should not happen. 

Move VM errors, or other execution errors, propagate via Rust `Result`s. So any dynamic field information will be lost, as we want.

**Comment by stefan-mysten** [comment]
@lxfind is this still relevant? If not, let's close it. Thanks.

**Comment by lxfind** [comment]
Thanks. We can close this.
