### ISSUE TITLE
Sui staking testnet 

### ISSUE THREAD

**Issue by Starlew77** [MystenLabs/sui#8140]
unable to add any funds to stake any sui tokens on all validators  please see attached photo the stake part where you input the amount you wish to stake does not allow anything to be put in on all validators 

![20230207_133930](https://user-images.githubusercontent.com/116558527/217261071-7333e65a-01e5-488a-ab36-246d6753ec49.jpg)

**Comment by Ghazwan697** [comment]
I think you need to update the wallet and give it a try

**Comment by 0xWhiteGod** [comment]
1. Update your wallet: Manage extension---->Developer Mode------>Click on Update

2. Try to stake less amount < 0.1, like 0.05

But it seems like the problem you don't know where to enter amount. White panel above "Staking rewards start"

**Comment by Starlew77** [comment]
Hi ya

I sent a photo with the area highlighted showing where it won't input , did
you see that hopefully that will make it clearer its not letting you put
any amount in 👌

If you could give me another way of getting tokens as explained discord is
not secure and  has a number a security issues so If you could advise where
I can more tokens that will be great

Thank you

**Comment by Starlew77** [comment]
Thank you 😊

**Comment by 0xWhiteGod** [comment]
> 

Give me your wallet ill send you some

**Comment by Starlew77** [comment]
Hi

Great thank you 😊 🙏 I let you know what happens

0x3102603cc0119e8eb0dbc5287a43ae1c54b16475


Kind regards

Steve

**Comment by 0xWhiteGod** [comment]
> 0x3102603cc0119e8eb0dbc5287a43ae1c54b16475

Did 2 transactions

**Comment by Starlew77** [comment]
Thank you

I'm just out at moment but will be back and try it out thank you again its
really appreciated 🙏

**Comment by 0xWhiteGod** [comment]
> Author

No need to do that sir, was glad to help you

**Comment by Starlew77** [comment]
Hi

Thank you for sending coins unfortunately the test net staking still not
working I raised a query and took some screen shots I will try again later
, but again many thanks

One question if I'm not on discord is there any other way of getting coins
as I cant test namesake as my balance is still too low

Thank you again for all help 🙏

**Comment by randall-Mysten** [comment]
Thank you @0xWhiteGod !

**Comment by Starlew77** [comment]
staking working now thank you :)
