### ISSUE TITLE
Capys helmet astro suit bug and cowboy suit

### ISSUE THREAD

**Issue by Starlew77** [MystenLabs/sui#8141]
was able to buy helmet this time and then add to capy as well as suit but then screen flashed and now cant buy helmet or suit and the disappeared not able to do anty space accessorys

cowboy outfit allowed me to buy all then added to capy generation 3 but then when i came out of page deleted all purchases :)

**Comment by Starlew77** [comment]
i just seen in my wallt its actually added the capy with full astro suit but not cowboy how strange

**Comment by Starlew77** [comment]
now astrosuit in my collection , itried to use test net for namesake but its says i have zero sui tokens do i have to have a min amount ?

**Comment by 0xWhiteGod** [comment]
Please use faucet in discord to get test tokens
!faucet your-wallet 

you need Sui to pay gor gas and service

**Comment by Starlew77** [comment]
I can't use discord due to its security issues is there another way please

**Comment by Starlew77** [comment]
resolved and thank you again for advice and help :)
