### ISSUE TITLE
Validator consumes too much resources and that makes the client stalled

### ISSUE THREAD

**Issue by rootwarp** [MystenLabs/sui#8142]
I faced the client stalled problem during wave 2 validator participation.

`sui-node` stalled for 2 minutes and it recovered automatically.
When I faced this issue, CPU and disk write resources consume a lot as I attached below.

<img width="1784" alt="Screenshot 2023-02-07 at 23 20 34" src="https://user-images.githubusercontent.com/9974087/217273550-616c8da2-6ba7-4e35-910e-92d553bc20c6.png">

During this short time, the client's metrics were not collected from the Prometheus agent so the client could be really busy for running or handling some jobs.

Our operating environments are,
- Ubuntu 22.04.1 LTS
- Using Docker

And I also attached logs. This issue happened from 14:17 to 14:19 (UTC).

[sui-node.2023020714_1.log.zip](https://github.com/MystenLabs/sui/files/10676447/sui-node.2023020714_1.log.zip)

**Comment by mwtian** [comment]
Thanks for reporting the issue. After recovery, Sui was spending CPU and disk to catch up, specifically for checkpoint download and execution. The 2min stall was also interesting, but we did not find a root cause.
