### ISSUE TITLE
Sui name service  - devnet 

### ISSUE THREAD

**Issue by Starlew77** [MystenLabs/sui#8183]
error message when registering name 

![20230208_200420](https://user-images.githubusercontent.com/116558527/217639462-12b4342f-970d-4e1e-a2e2-038bcd0adb36.jpg)

keepsake -  issue says all items already purchased but are not :)

**Comment by Starlew77** [comment]
hi randall

tried this today and its still getting same message as above :)

**Comment by Jordan-Mysten** [comment]
This is an issue with the SuiNS Dapp, I'd recommend reaching out to them for support.
