### ISSUE TITLE
Sui transaction error

### ISSUE THREAD

**Issue by Faserx1** [MystenLabs/sui#8184]
Hello, I tested your network, after a large number of transactions, a validator error appeared, the gas commission is not correct.

My wallet - 0x961b6c5408e6be4e508b2c607e36a8e79a85bea9
Wallet my friend - 0x44180f6a62084707f4c50ec131191f7ce4ef3ea5

I send 1 sui and the balance is 5.

Here is such an error when sending.

Error executing transaction with request type: Error: RPC Error: Transaction has non recoverable errors from at least 1/3 of validators: [(GasBalanceTooLowToCoverGasBudget { gas_balance: 56049, gas_budget: 134700, gas_price: 449 }, [k#ad4219c4c52e619b30469011c1f4c17048e210ba419f337219362e021d10873fb87afb1c25fb3377e8da9f05cebc16f504953d3f666eab35d6137fe65d8f7372c1b0bfc0d3a55c8d7e368a1ed5c6a43308aa8c91cf7e9976c920f41c82671fca, k#b3ffca7b4fd6acc77c548316a2839b07b59ba261e14a109eb31c130ca69f614a7dc73b3ebaf111d6a88e0d8a644badf305494866f2ece104daf1739088d3197f55a55e305e526804ad49199f64297060fd87df995cb7ce86dfe59ce3c29208c4, k#8c93e76c3239161d07bbef1e01dc039779b9ca43e34a8ca74b0523592b10a654d831a58d4141f10e21808789f899f81e0bf3ffc8e4e2e51d3386cdfbf78cadcd01cccc918948f862d4be92462fddfb909a21e69854c6c08880f35c0874c430e5, k#8b48ee49ff972a7d00f09dbca41ae6b87888c677e27dd033c2051cbacc16b28357e763cbd452b1f80beb3dc2177f93cd06d6d672a9eaeb49d20e8ac22964e400c154c32fd2c9bda78d869b6f0b132111eae3b01bcec8a1db373b13c8278544d4, k#b1f6a442dffd81ad8d78fabe66097503a8b42ffaf429bda643437382cf9e1ba1766ff067080082e294096eb2b6e08d740392be7e10fbcfe96a84334d7d1977ebccc8b76b7619eec0f022a66bd109fdd3614acd248f3dbed2b80810c424b3c9bf, k#b36d95a3a5f8b8b95ea56c157f34d64aa264abe882dea7016a2b4c45804cc9a69b6afe1709eb07655f8c9597c7617ba91209b5ddc3e0281a3d26a31b40e9ee43243b21ab4fd333427c4623a1dc5b3aef183d67cb5a30bd3ab3049fd632625654, k#85239eeb1da141cdd6a9e576ae96fb1d40683052e2de100a542e0893a9f40abda55a7e20a44842585f611476dd48391d10686d6394991d3ffd4c5fd547536126741a51947901955c8eee5be20a99d08735d5677ff253a88945376d4710abc300, k#8c8cd2f4fe5ddc8c9644358679d3b55227e9a1cb73ecc8b9f21d140c51ef1f51404e2d5f4c0c3d0e4aadbc9732be102100ddf5abf903baf26187b176aeec600932f361ead22187d48943322d138d91312be8fe2a5dc778517a5596d8ce776858, k#8c1f0b28adb3b57c1f5feb9fe245894d67a34439803895f5dd783e8e792dfbc067e57990dd5d7b4fc45723bd38a1421417b848b834678a688dec4ce037c7084123eabdec4a64929d4e7aaaae9402c2b70a0185d94dc2f08b6e44542e9ecc1524, k#96c061fb2473422fa55a4f3f54c83071d84bbb6223f842dffc3cb2864e9349917dfcb3ff5d7f390f5a4ad73ece8012560b289f08a05df2c9b780e258be0531ab1e23958938476bf68090c0cb0d1acf25ceda5b4c1b91d51137032d6110626925, k#8c89a2c99dca058d2736d8f50b4ec9ad3d453fdbf9fea2fec83a746c72f4bbd96c38e92f0e48db2c1112bfd5e1f8500d176c66b015de0a3c5c948fb40fb80dfbcdd2c886fa393b5daa9fa3a5743c0fa1b75f3e940b133ca5bacc649738bf0195, k#a661b673822d259bd90dde2d222a83aa08d68646ffaabae943b49d42de4b4e50c0bc7b5fa3d119b957436dbf63d359640bcc65bcf3f50f8613397b3483f74f3d4755e941d37aa47940a6d6c38e411995c1036d5357b7cb791901764a7a149129, k#aa0bd63a8878f6a688ee28366b6ccf28aa8650e679d9a8ebbd12b46e8f20166323cf8de90160ecb88f0f68b32e3b4c88152fbdcd9e5417da382d9d860d43f550a77e97ab149feacaba6236c536599db855a99e21a599b869d5af769031de1bb1, k#997e9933900f18fc7e7a0b4d358141165378f4ac29f17a0c2b46af8d6dbb08621a3c1202e3352f9f9827519e5e858f63050a171c79a8f28bfe181a61c4070daeb058937d612444a676548d47fb60e1c52955229a583aa3d6bccba76f42011399, k#957d65a242edd7e344e098482b4daaa514b2e7b2b02b33cf7809f1701cec73f061059440609058df3ada20dd0c41717a15dae1c001b3f3e065d88122c7875eeea44d957c083133bc872111638fc4cedc71944b0aa3f796499f47fd42ca8e01ec, k#81cecd3600c88780860105a15a874b3807600485581966271f6fdb51b6ac8af69a23fd1084bc8d4acefc7b6f8f48f8f80d281c48a9c35bdf0f2277c28adb99d8e4c38fdd445af8faf7b7e93e33333b15c0049278ad479b87197faf781b630305], 3412)].

**Comment by Faserx1** [comment]
and I also can't use staking. the button glows gray.

**Comment by leezijie** [comment]
I also encountered this error. When I paid too much object, how should I set gasBudget and gasPrice

**Comment by leezijie** [comment]
I also encountered this error. When I paid too much object, how should I set gasBudget and gasPrice

**Comment by 0xWhiteGod** [comment]
> and I also can't use staking. the button glows gray.

Update wallet to latest version

**Comment by 0xWhiteGod** [comment]
> Hello, I tested your network, after a large number of transactions, a validator error appeared, the gas commission is not correct.
> 
> My wallet - 0x961b6c5408e6be4e508b2c607e36a8e79a85bea9 Wallet my friend - 0x44180f6a62084707f4c50ec131191f7ce4ef3ea5
> 
> I send 1 sui and the balance is 5.
> 
> Here is such an error when sending.
> 
> Error executing transaction with request type: Error: RPC Error: Transaction has non recoverable errors from at least 1/3 of validators: [(GasBalanceTooLowToCoverGasBudget { gas_balance: 56049, gas_budget: 134700, gas_price: 449 }, [k#ad4219c4c52e619b30469011c1f4c17048e210ba419f337219362e021d10873fb87afb1c25fb3377e8da9f05cebc16f504953d3f666eab35d6137fe65d8f7372c1b0bfc0d3a55c8d7e368a1ed5c6a43308aa8c91cf7e9976c920f41c82671fca, k#b3ffca7b4fd6acc77c548316a2839b07b59ba261e14a109eb31c130ca69f614a7dc73b3ebaf111d6a88e0d8a644badf305494866f2ece104daf1739088d3197f55a55e305e526804ad49199f64297060fd87df995cb7ce86dfe59ce3c29208c4, k#8c93e76c3239161d07bbef1e01dc039779b9ca43e34a8ca74b0523592b10a654d831a58d4141f10e21808789f899f81e0bf3ffc8e4e2e51d3386cdfbf78cadcd01cccc918948f862d4be92462fddfb909a21e69854c6c08880f35c0874c430e5, k#8b48ee49ff972a7d00f09dbca41ae6b87888c677e27dd033c2051cbacc16b28357e763cbd452b1f80beb3dc2177f93cd06d6d672a9eaeb49d20e8ac22964e400c154c32fd2c9bda78d869b6f0b132111eae3b01bcec8a1db373b13c8278544d4, k#b1f6a442dffd81ad8d78fabe66097503a8b42ffaf429bda643437382cf9e1ba1766ff067080082e294096eb2b6e08d740392be7e10fbcfe96a84334d7d1977ebccc8b76b7619eec0f022a66bd109fdd3614acd248f3dbed2b80810c424b3c9bf, k#b36d95a3a5f8b8b95ea56c157f34d64aa264abe882dea7016a2b4c45804cc9a69b6afe1709eb07655f8c9597c7617ba91209b5ddc3e0281a3d26a31b40e9ee43243b21ab4fd333427c4623a1dc5b3aef183d67cb5a30bd3ab3049fd632625654, k#85239eeb1da141cdd6a9e576ae96fb1d40683052e2de100a542e0893a9f40abda55a7e20a44842585f611476dd48391d10686d6394991d3ffd4c5fd547536126741a51947901955c8eee5be20a99d08735d5677ff253a88945376d4710abc300, k#8c8cd2f4fe5ddc8c9644358679d3b55227e9a1cb73ecc8b9f21d140c51ef1f51404e2d5f4c0c3d0e4aadbc9732be102100ddf5abf903baf26187b176aeec600932f361ead22187d48943322d138d91312be8fe2a5dc778517a5596d8ce776858, k#8c1f0b28adb3b57c1f5feb9fe245894d67a34439803895f5dd783e8e792dfbc067e57990dd5d7b4fc45723bd38a1421417b848b834678a688dec4ce037c7084123eabdec4a64929d4e7aaaae9402c2b70a0185d94dc2f08b6e44542e9ecc1524, k#96c061fb2473422fa55a4f3f54c83071d84bbb6223f842dffc3cb2864e9349917dfcb3ff5d7f390f5a4ad73ece8012560b289f08a05df2c9b780e258be0531ab1e23958938476bf68090c0cb0d1acf25ceda5b4c1b91d51137032d6110626925, k#8c89a2c99dca058d2736d8f50b4ec9ad3d453fdbf9fea2fec83a746c72f4bbd96c38e92f0e48db2c1112bfd5e1f8500d176c66b015de0a3c5c948fb40fb80dfbcdd2c886fa393b5daa9fa3a5743c0fa1b75f3e940b133ca5bacc649738bf0195, k#a661b673822d259bd90dde2d222a83aa08d68646ffaabae943b49d42de4b4e50c0bc7b5fa3d119b957436dbf63d359640bcc65bcf3f50f8613397b3483f74f3d4755e941d37aa47940a6d6c38e411995c1036d5357b7cb791901764a7a149129, k#aa0bd63a8878f6a688ee28366b6ccf28aa8650e679d9a8ebbd12b46e8f20166323cf8de90160ecb88f0f68b32e3b4c88152fbdcd9e5417da382d9d860d43f550a77e97ab149feacaba6236c536599db855a99e21a599b869d5af769031de1bb1, k#997e9933900f18fc7e7a0b4d358141165378f4ac29f17a0c2b46af8d6dbb08621a3c1202e3352f9f9827519e5e858f63050a171c79a8f28bfe181a61c4070daeb058937d612444a676548d47fb60e1c52955229a583aa3d6bccba76f42011399, k#957d65a242edd7e344e098482b4daaa514b2e7b2b02b33cf7809f1701cec73f061059440609058df3ada20dd0c41717a15dae1c001b3f3e065d88122c7875eeea44d957c083133bc872111638fc4cedc71944b0aa3f796499f47fd42ca8e01ec, k#81cecd3600c88780860105a15a874b3807600485581966271f6fdb51b6ac8af69a23fd1084bc8d4acefc7b6f8f48f8f80d281c48a9c35bdf0f2277c28adb99d8e4c38fdd445af8faf7b7e93e33333b15c0049278ad479b87197faf781b630305], 3412)].

Try to use less Sui for transaction, for example 0.06

**Comment by Faserx1** [comment]
I tried it. The error has not disappeared. =(

**Comment by albinlau** [comment]
same issue

Failed to execute transaction TransactionDigest(6bwXSYaom47BfZLoePN1nFCNWgvoYxMgPXmcq7VBMyCK) with error RpcError(Call(Custom(ErrorObject { code: ServerError(-32000), message: "Transaction has non recoverable errors from at least 1/3 of validators: [(TransactionInputObjectsErrors { errors: [ObjectNotFound { object_id: 0xa3bc2b1a17d8617bda575a3a36e9b69de115f489, version: Some(SequenceNumber(1002672)) }] }, [k#8f00ecad8642577957fa533d6a47aa81ccee0dac3745f9b40a2465220b73e681053e5198b57ec29cc999b81b70f4749b13dd4f2140cf991daced03d71ee86802cb627149d06d800032c42e2f565d036f204b04b1be1d4b12d604e77cc0b95449, k#a57d8fdb22e41fb997965638e457b75ff225524366b9b669732ca2e95eb59bc83fb3d1e69ffbabe765a7c570340c120d1102dc1d5061408279af9fd122c7c7aa6f2fb1a0d5e23863bf09b32f52436477db6c043cd2330830321685d810fc32bb], 5000)].", data: None })))

**Comment by stefan-mysten** [comment]
I'd expect that this has been fixed since March, but if you still encounter problems, feel free to create a fresh issue. Thanks!
