### ISSUE TITLE
Sui Testnet request amount 

### ISSUE THREAD

**Issue by BetDEXben** [MystenLabs/sui#8233]
does anyone sell testnet sui here? i need it about 500-1000 Testnet 
if you can help me i really appreciate you thank you very much
0xb5d4612be7575b75e05dd44eed90842b67d6212c

**Comment by ilyice** [comment]
Please contact me: lajizhongguo702@gmail.com

**Comment by BetDEXben** [comment]
> Please contact me: [dananitainiubi@gmail.com](mailto:dananitainiubi@gmail.com)

What for?
