### ISSUE TITLE
confusion about transaction timestamp

### ISSUE THREAD

**Issue by qiaokan** [MystenLabs/sui#8284]
getTransaction returns a timestamp in the response

However

- It is different than the timestamp of the Checkpoint it belongs to. We observe it has a ~30s diff.
- It is also non-deterministic from different validators. Assuming you have 2 people running some kind of SUI explorer, they will show **different timestamps** for the **exact same transaction**. We verified this by comparing the timestamps from one validator we ran and the public sui testnet endpoint

This could be confusing to anyone who is consuming transactions.
If this is by design, it might be better to explicitly point out that readers should rely on checkpoint timestamp for any given transaction?

**Comment by Jordan-Mysten** [comment]
@gegaowp I believe that we've changed this so that it now returns the checkpoint timestamp, correct?
