### ISSUE TITLE
Potential leak in notify_read

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#8290]
Currently when a validator receives a transaction cert for execution, it (1) first checks whether it has been executed, if not, it (2) enqueues the cert and calls notify_read_effects to wait for execution.
In a rare event, if the cert was executed, and then reverted (due to epoch change) all in-between (1) and (2) above, the call to notify_read_effects could hang forever.

We could consider adding a deadline which would also unregister tx.

**Comment by stefan-mysten** [comment]
@lxfind is this still relevant? If not, let's close it! Thanks
