### ISSUE TITLE
Source verification errors

### ISSUE THREAD

**Issue by Suficio** [MystenLabs/sui#8339]
This issue appeared in `devnet 0.24.0` and remains in `0.26.0`

## Steps to Reproduce Issue

1. Publish dependency contract on chain

In this issue I'm using this pre-published `Originmate` contract:
https://github.com/Origin-Byte/originmate/pull/30

2. Use published contract as dependency in another contract

I'm going to publish OriginByte's `NftProtocol` from this branch:
https://github.com/Origin-Byte/nft-protocol/pull/261

3. Call `sui client publish`

## Expected Result

Expect that `NftProtocol` is published

## Actual Result

```
$ sui client publish --gas-budget 60000
FETCHING GIT DEPENDENCY https://github.com/Origin-Byte/originmate.git
INCLUDING DEPENDENCY MoveStdlib
INCLUDING DEPENDENCY Originmate
INCLUDING DEPENDENCY Sui
BUILDING NftProtocol

Multiple source verification errors found:

- Local dependency did not match its on-chain version at b083e008298643332a463e2563966f4c6f4aa8ae::Originmate::governance
- Local dependency did not match its on-chain version at b083e008298643332a463e2563966f4c6f4aa8ae::Originmate::virtual_block
- Local dependency did not match its on-chain version at b083e008298643332a463e2563966f4c6f4aa8ae::Originmate::quadratic_vesting
- Local dependency did not match its on-chain version at b083e008298643332a463e2563966f4c6f4aa8ae::Originmate::merkle_proof
- Local dependency did not match its on-chain version at b083e008298643332a463e2563966f4c6f4aa8ae::Originmate::pseudorandom
- Local dependency did not match its on-chain version at b083e008298643332a463e2563966f4c6f4aa8ae::Originmate::vectors
```

Calling with `--skip-dependency-verification` results in a fully functioning published contract

## System Information

* OS: 5.15.79.1-microsoft-standard-WSL2 (Ubuntu 22.04.1 LTS)
* Compiler: sui 0.26.0-b63532e

**Comment by amnn** [comment]
Thanks for your report @Suficio -- this is a known problem, I'm working on a fix, which should land in the next release.  Unfortunately, the underlying issue (related to the compiler changing the order of some internal structures based on the values of numerical addresses) was not straight-forward to fix, and our initial simpler fix did not do the job.

**Comment by Suficio** [comment]
Thanks for the info @amnn, good to hear it's getting fixed!
