### ISSUE TITLE
[Package Upgrades] Enable Lock Files

### ISSUE THREAD

**Issue by amnn** [MystenLabs/sui#8342]
**Part of #2045**

Lock files are an important piece for robust source indexing and verification -- we have recently landed support in a stack ending at move-language/move#861, and this requires integration into Sui.

## Steps

- [x] Move bump, past https://github.com/move-language/move/commit/6216ac6d96efd301d9b6ddd839ca26ae3ad2606d to incorporate lock file support.
- [x] Enable lock files, by setting [`BuildConfig::lock_file`](https://github.com/move-language/move/blob/sui-move/language/tools/move-package/src/lib.rs#L122-L125) to the appropriate path (`Move.lock` in the project root). https://github.com/MystenLabs/sui/pull/8565
- [x] Update documentation introducing the concept to the community (lock files are generated by builds, they should be checked in with source, but not modified by hand). Partly done, @ronny-mysten and @randall-Mysten to follow up on [in-progress doc](https://github.com/MystenLabs/sui/pull/8565/files#diff-dce95d3d2cac679debfb4406b548cfe849ed01fc62d0a7d78683eeea3260e1a6). 

## Further Work

Once lock files are ubiquitous, it becomes possible to speed up builds and otherwise improve developer experience by:

- #8344 and parallelising Move package fetches (which now predominantly happen via recursive descent, or linearly).
- https://github.com/MystenLabs/sui/issues/8345

**Comment by rvantonder** [comment]
Draft PR for your thoughts on setting / enabling lock files @amnn: https://github.com/MystenLabs/sui/pull/8565

**Comment by amnn** [comment]
Done!
