### ISSUE TITLE
Sui Testnet Staking error message when staking 

### ISSUE THREAD

**Issue by Starlew77** [MystenLabs/sui#8347]
Hi 

Tried staking please see attrached photos allows you to input stake and approve but then about  2-5 minutes loading and then comes  up with this error message

images.githubusercontent.com/116558527/219395301-8b311916-036d-4bae-9822-8f321dc48fef.jpg)
![20230216_143456](https://user-images.githubusercontent.com/116558527/219395338-95f69dc6-d620-45f9-a2bf-be6748a5483b.jpg)
![20230216_143445](https://user-images.githubusercontent.com/116558527/219395377-1dcb1571-9904-4d3d-9ae6-23d2dfd34ff2.jpg)

its happing with a number of validators 

![20230216_144153](https://
![20230216_144129](https://user-images.githubusercontent.com/116558527/219396319-77f6653e-cc89-43fe-8192-be2a58aa1d10.jpg)
user-images.githubusercontent.com/116558527/219396279-bda619a1-b80a-4822-bbf0-59f877e15a2c.jpg)

**Comment by Starlew77** [comment]
![20230216_143523](https://user-images.githubusercontent.com/116558527/219396859-2f0bf079-66d2-4919-8145-12740e93e585.jpg)
![20230216_144153](https://user-images.githubusercontent.com/116558527/219396938-4c83ad58-da1d-48c2-8c8a-035f2a0087cd.jpg)


sorry the error message was not on photos please find

**Comment by Jordan-Mysten** [comment]
We've resolved these staking issues since this was reported.
