### ISSUE TITLE
sui wallet - missing 

### ISSUE THREAD

**Issue by Starlew77** [MystenLabs/sui#8348]
hi 

after i just reported those issue regarding staking ,  i have just gone back into my wallet no test net avaliable and all my staking coins are gone  and in test net has gone and also now my devent wallet is empty can you advise please 
![20230216_144928](https://user-images.githubusercontent.com/116558527/219398580-92c3aa72-d49a-4b04-acf1-0abb8574c88e.jpg)

**Comment by Jordan-Mysten** [comment]
This is expected as we've disabled Testnet until the next wave. The option should appear again once Testnet is back!
