### ISSUE TITLE
sui capys -  items not adding

### ISSUE THREAD

**Issue by Starlew77** [MystenLabs/sui#8349]
All accessorys adding except,  astro helmet and astro suit ,transaction going through but not adding these 2 items  

please see attached photos 
![20230216_145835](https://user-images.githubusercontent.com/116558527/219401285-72b31785-e13e-4246-81f2-5e07c3c045dc.jpg)
![20230216_145817](https://user-images.githubusercontent.com/116558527/219401328-ccab6f94-10ea-4536-a981-59d0d149d637.jpg)
![20230216_145932](https://user-images.githubusercontent.com/116558527/219401356-af6ac1ab-9e9a-44ec-8eb4-74a79ec36a56.jpg)

**Comment by Starlew77** [comment]
hi checked again today astro helmet and suit not adding :)

**Comment by Mathman14** [comment]
thuis has ended long ago fam
