### ISSUE TITLE
sui-wallet sui mint 

### ISSUE THREAD

**Issue by Starlew77** [MystenLabs/sui#8352]
Minting facilty is just a blank screen now 

![20230216_151849](https://user-images.githubusercontent.com/116558527/219408968-258023c4-ec8d-4141-aa0f-bc15d85dc7f4.jpg)

suin, is working fine now :) registered absoluty fine :)
![20230216_151849](https://user-images.githubusercontent.com/116558527/219409620-53c92601-44cd-494e-a899-17418a657f3f.jpg)

**Comment by Jordan-Mysten** [comment]
This demo site is no longer supported.
