### ISSUE TITLE
Sui doc namesake 

### ISSUE THREAD

**Issue by Starlew77** [MystenLabs/sui#8354]
""new "

i have enough sui tokens but when trying to purchase iteam it sates below saying not enough sui but you can see i have enough sui 

![20230216_153519](https://user-images.githubusercontent.com/116558527/219413652-6ce4e04a-6c4d-4ac5-8d94-afbd332f97f3.jpg)

**Comment by Jordan-Mysten** [comment]
I'd recommend reporting this to the dapp.
