### ISSUE TITLE
Add a sui::object::get_type(&uid) function

### ISSUE THREAD

**Issue by PaulFidika** [MystenLabs/sui#8404]
Would it be possible to add a function to sui::object that is like:

`get_type(uid: &UID): Option<ascii::String>`

(alternatively we could return a std::type_name::TypeName instead of a string (but I like strings more)).

The intention is that, given a UID, you can query what the type is of the object to which it belons (because presumably most UIDs are embedded inside of an object as an id). This would be useful for dynamic fields, which pass around &mut UID's to each other, rather than operating on the object directly.  The `Option<>` portion is because the UID might not be inside of an object at all, in which case we would return option::none().

I suppose this is a rather niche use, but it would be helpful with Capsules, who frequently pass around &mut UIDs to each other so that programs can attach their own custom fields to other program's structs. I think this should be possible to implement within Sui. Thanks.

**Comment by tnowacki** [comment]
A bit more context here: You cannot query information about all objects in Sui, only input objects (and dynamic fields off of those input objects). So such an API would be limited to input objects, but at that point, you could just get the TypeName off of the object itself, which would really limit the usefulness of such a UID-based API.
