### ISSUE TITLE
Why are transfer::freeze_object and transfer::transfer not entry functions?

### ISSUE THREAD

**Issue by PaulFidika** [MystenLabs/sui#8415]
Why not add `entry` to both sui::transfer::freeze and sui::transfer::transfer, so that they can be called directly by external applications? Obviously the call will fail if the owned-object T being passed in does not have `store`.

Although it's not obvious from reading the Move code or comments, there is a hidden Move-VM restriction that restricts these functions to only work on `key + store` generally. If the call comes from within the module itself, then the `store` requirement is relaxed. This is a security feature giving modules greater control over the assets they define.

**Comment by PaulFidika** [comment]
It might have something to do with them being built into the Sui-core directly, so that rather than calling into the Move VM, you call into the Sui core to do these operations. (I don't understand that bit though.) Is that the reason?

**Comment by damirka** [comment]
While I’m still trying to investigate the reasons behind this decision it’s worth mentioning that they will probably go away with the introduction of programmable transactions.

Chances that you will be able to store a return value of a function with one of the transfer calls.
