### ISSUE TITLE
Capy Cat not purchasing after clicking on "approve" in wallet

### ISSUE THREAD

**Issue by tiff0000** [MystenLabs/sui#8433]
## Steps to Reproduce Issue

Fill this in with the concrete steps needed to reproduce the bug. When providing code in the reproduction steps, use the smallest snippe

1. Go to : https://capy.art/item-store/astro%20hat
2. Click on "But for 0.01"
3. Sign on the wallet, then the image below would show. 

![Screen Shot 2023-02-19 at 7 03 30 PM](https://user-images.githubusercontent.com/20705520/219983568-0283de78-4f4b-4ec1-874e-96e25c540b82.png)

4. Click on "approve"
5. Go to "My collections/accessories"
![Screen Shot 2023-02-19 at 7 06 23 PM](https://user-images.githubusercontent.com/20705520/219983685-3c710e90-5973-4992-a13e-5cdd333e2927.png)

**Result:**

The item is not purchased.
![Screen Shot 2023-02-19 at 7 06 48 PM](https://user-images.githubusercontent.com/20705520/219983705-0f8942c7-eb3c-4356-bc96-84bcf81e94d7.png)

Expected: It should show the Astro Hat accessory.

**Comment by Mathman14** [comment]
did you mint from testnet or devnet
