### ISSUE TITLE
Sui doc content request about "sui client publish --doc"

### ISSUE THREAD

**Issue by georgescharlesbrain** [MystenLabs/sui#8579]
Concerning the help of 
`sui client publish --help`

Should the --doc flag do anything?
What's the use of --test and --dev?

**Comment by stefan-mysten** [comment]
Thanks for your question:
`--dev` flag will: _Compile in 'dev' mode. The 'dev-addresses' and 'dev-dependencies' fields will be used if this flag is set. This flag is useful for development of packages that expose named addresses that are not set to a specific value_
`--test` flag will:  _Compile in 'test' mode. The 'dev-addresses' and 'dev-dependencies' fields will be used along with any code in the 'tests' directory_
`--doc` flag should generate the docs for that smart contract package.
