### ISSUE TITLE
Capys And other 

### ISSUE THREAD

**Issue by Starlew77** [MystenLabs/sui#8580]
hi hope your well , iv checked today this is what i have found :) i appriciate some are 3rd parties 

when adding capys this error message comes up but actually added capys to walet but not in capys home page 
![20230223_141745](https://user-images.githubusercontent.com/116558527/220933742-3ecdf208-3f95-4208-880f-01e3127e80a8.jpg)
![20230223_140742](https://user-images.githubusercontent.com/116558527/220933757-58442a03-c99c-499f-9af9-d18ce9d51ba7.jpg)

adding some accesorys only cowboy hat  to wallet but not homepage for capys 

suins error message 
![20230223_140843](https://user-images.githubusercontent.com/116558527/220933889-21b22bba-517b-4886-bc4b-174bbfe3ebc3.jpg)

ethos game - adding progress but once added comes back to to re add to wallet so your claiming same award and duplicating in wallet  
![20230223_142159](https://user-images.githubusercontent.com/116558527/220935526-c96cc059-9a2d-42e2-90cd-70e6a8c54729.jpg)

**Comment by randall-Mysten** [comment]
I think this is due to the release yesterday and Capys needing to update to it. Should resolve this week.

**Comment by Ezebrown** [comment]
It is not due to release that occur yesterday,  it has been like that for a while. During wave 2 testnet too.
All those dapps integrated on sui wallet not working effectively or maybe they are crowded.

**Comment by Starlew77** [comment]
capys adding now except pearls :) apart from that everything seems to  be fine :)

**Comment by randall-Mysten** [comment]
> It is not due to release that occur yesterday, it has been like that for a while. During wave 2 testnet too. All those dapps integrated on sui wallet not working effectively or maybe they are crowded.

Oh, I'll forward to the team for assessment, thanks for letting me know
