### ISSUE TITLE
Smart contract deployment error

### ISSUE THREAD

**Issue by Ezebrown** [MystenLabs/sui#8615]
I ran into this error when deploying smart contract on sui.
![IMG-20230125-WA0052](https://user-images.githubusercontent.com/107863520/221120455-4e26ad7c-5b39-4ea0-8ede-3bfe6a5bc9a8.jpg)

**Comment by randall-Mysten** [comment]
Hi @Ezebrown Sorry you are having this issue. Can you please confirm which OS you are using, and that you've updated Rust and prereqs to the latest version?

**Comment by Ezebrown** [comment]
ok , i will try and redo it
