### ISSUE TITLE
A little SUI JSON-RPC issue

### ISSUE THREAD

**Issue by Romainua** [MystenLabs/sui#8752]
There is a little issue https://docs.sui.io/sui-jsonrpc#sui_moveCall for `arguments` describe. Check screenshot.
![issue](https://user-images.githubusercontent.com/44613085/222222545-d3ce6169-8c41-4157-86df-3754d5d501a4.png)

**Comment by randall-Mysten** [comment]
Hi @Romainua Thanks for letting us know about this. These docs are built from source code so require a change there. I'll add folks to the issue who work directly on that. Cheers!

**Comment by randall-Mysten** [comment]
added PR https://github.com/MystenLabs/sui/pull/8758 to provide an interim fix for this issue
