### ISSUE TITLE
Support Batch Transactions

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#876]
Signature verification is one of the top bottlenecks in our transaction throughput.
On my Mac M1, the throughput between with signature verification and no signature verification is the following:
With signature verification: 17K
Without signature verification: 25K
So we will observe a 50% increase if we can completely eliminate the overhead of signature verification.
The command I used is:
```
cargo run --release --bin=bench -- --num-accounts 100000 --max-in-flight 10000 --tcp-connections 9 --committee-size 4
```

One idea is to support sending a batch of transactions, that are signed altogether, and hence only requires one signature verification per batch, instead of per transaction.
There are two direction to go about this:
1. A batch of transactions is atomic, i.e. either every transaction succeeds, or if any transaction failed the entire batch is considered failed.
2. Each transaction still executes on their own, and some can succeed, some can fail.

Some considerations:
For 1, it is probably easiest to implement, as it still fits into our current data structures, we just need to introduce a new transaction kind, which contains a list of sub-transaction kinds. The transaction itself is still signed as before, we just need to aggregate the effects of a batch and commit them together. In the case when most transactions succeed, this may even be more performance given that it's able to do batch db writes.

For 2, it is more efficient when there is a non-trivial chance of having failing transactions in a batch. The challenge of this approach is then we need to evolve our transaction data structures: each transaction may no longer have a signature.

**Comment by gdanezis** [comment]
This has landed now. Should we close? (nice one @lxfind !)

**Comment by lxfind** [comment]
> This has landed now. Should we close? (nice one @lxfind !)

The backend is done. However we haven't exposed this in Gateway/REST yet.
