### ISSUE TITLE
Feature request: Return unique chain ID in RPC API

### ISSUE THREAD

**Issue by hugmouse** [MystenLabs/sui#8827]
# Feature Description

Return an unique chain ID by using RPC API.

## Rationale

It's not possible to tell what network is currently node is on. I'm creating a node monitoring tool and it would be very useful for me to know what network the node is running on: devnet, testnet or mainnet.

## Proposed Solution

Add this information to the RPC API. Create something like `sui_chainId`, that can return the unique chain ID.

```bash
curl -X POST --data '{"jsonrpc":"2.0","method":"sui_chainId","params":[],"id":69}'

{
  "id": 69,
  "jsonrpc": "2.0",
  "result": "devnet"
}
```

Or even have different chain ID for every genesis.

**Comment by stefan-mysten** [comment]
You can get the chain ID by using calling this RPC function: [`sui_getChainIdentifier`](https://docs.sui.io/sui-api-ref#sui_getchainidentifier)
