### ISSUE TITLE
fullnode template missing option objects-num-latest-versions-to-retain 

### ISSUE THREAD

**Issue by flex-enjoy** [MystenLabs/sui#8943]
After upgrading to devnet-0.27.1, this config template https://github.com/MystenLabs/sui/blob/main/crates/sui-config/data/fullnode-template.yaml will lead to 

`Error: authority-store-pruning-config: missing field 'objects-num-latest-versions-to-retain' at line 15 column 33
`

**Comment by randall-Mysten** [comment]
Thanks for tracking this down
