### ISSUE TITLE
Sui doc content issue or request

### ISSUE THREAD

**Issue by Ak0redey** [MystenLabs/sui#8952]
If this is an issue with existing content, provide the URL or GitHub path to the topic. Otherwise, use **New**.
My request is: I'd like the Sui ecosystem to create an android Sui app for easy user experience. Some of the people I've introduced to the ecosystem are having issues with testing the blockchain on a system since extension apps mainly works better on a computer. Unlike mobile phones, laptops and desktops computer are not potable (so carrying them about is quite burdensome. So it'll be better if a mobile app is created for Sui both on Android and iOS. Thanks for the consideration
Describe the issue or request. Provide as much detail as possible. For issues, it is helpful to copy the specific section of the topic into the issue.

Thank you for taking the time to let us know about the issue or request. We triage all new issues and requests within 2 business days. We will follow up if we need additional information.

**Comment by stefan-mysten** [comment]
Thank you for your suggestion of building a Sui App for mobile - unfortunately, for now there are no plans for dedicated mobile apps.
