### ISSUE TITLE
[crypto][performance] ensure no over-deserialization of validator signatures

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/sui#8982]
Similar to https://github.com/MystenLabs/sui/issues/8930 but for signatures

**Comment by jonas-lj** [comment]
We've solved almost all identified issues. There are two remaining which both require big changes, but from the profiling we've done, they do not matter that much anyway:
1. Signatures in sui_types::certificate_proofs::CertificateProof,
2. Signatures in sui_types::certificate_proofs::ConsensusTransactionKind
