### ISSUE TITLE
Warnings and errors when importing WalletKitProvider

### ISSUE THREAD

**Issue by NickDatLe** [MystenLabs/sui#9041]
I did the following:

```
npx create-react-app suiwallettest
cd suitwallettest
npm install @mysten/wallet-kit
```

imported the wallet kit into App.js:

`import { WalletKitProvider } from "@mysten/wallet-kit";`

`npm start`

and I get the following errors and warnings:

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in ./node_modules/superstruct/dist/index.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/nick/dev/suiwallettest/node_modules/superstruct/src/error.ts' file: Error: ENOENT: no such file or directory, open '/Users/nick/dev/suiwallettest/node_modules/superstruct/src/error.ts'

WARNING in ./node_modules/superstruct/dist/index.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/nick/dev/suiwallettest/node_modules/superstruct/src/struct.ts' file: Error: ENOENT: no such file or directory, open '/Users/nick/dev/suiwallettest/node_modules/superstruct/src/struct.ts'

WARNING in ./node_modules/superstruct/dist/index.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/nick/dev/suiwallettest/node_modules/superstruct/src/structs/coercions.ts' file: Error: ENOENT: no such file or directory, open '/Users/nick/dev/suiwallettest/node_modules/superstruct/src/structs/coercions.ts'

WARNING in ./node_modules/superstruct/dist/index.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/nick/dev/suiwallettest/node_modules/superstruct/src/structs/refinements.ts' file: Error: ENOENT: no such file or directory, open '/Users/nick/dev/suiwallettest/node_modules/superstruct/src/structs/refinements.ts'

WARNING in ./node_modules/superstruct/dist/index.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/nick/dev/suiwallettest/node_modules/superstruct/src/structs/types.ts' file: Error: ENOENT: no such file or directory, open '/Users/nick/dev/suiwallettest/node_modules/superstruct/src/structs/types.ts'

WARNING in ./node_modules/superstruct/dist/index.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/nick/dev/suiwallettest/node_modules/superstruct/src/structs/utilities.ts' file: Error: ENOENT: no such file or directory, open '/Users/nick/dev/suiwallettest/node_modules/superstruct/src/structs/utilities.ts'

WARNING in ./node_modules/superstruct/dist/index.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/nick/dev/suiwallettest/node_modules/superstruct/src/utils.ts' file: Error: ENOENT: no such file or directory, open '/Users/nick/dev/suiwallettest/node_modules/superstruct/src/utils.ts'

WARNING in [eslint] 
src/App.js
  Line 3:10:  'WalletKitProvider' is defined but never used  no-unused-vars

webpack compiled with 8 warnings

Any help?

Here is my full App.js:

```
import logo from './logo.svg';
import './App.css';
import { WalletKitProvider } from "@mysten/wallet-kit";


function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;
```

**Comment by Jordan-Mysten** [comment]
These just look like lint errors and sourcemap errors, are there any issues when actually using the provider in your project?

**Comment by Jordan-Mysten** [comment]
Going to close this, feel free to re-open if you run into this in the future!
