### ISSUE TITLE
Sui doc content issue  need some more clarity on a few topics

### ISSUE THREAD

**Issue by Hasen1506** [MystenLabs/sui#9089]
1.'Each SUI token is divisible up to a large number of decimal places'. Am I right to say that a maximum of only 9 decimals  termed as Mist is the lowest divisible amount that's possible? 

2.More info on the slashing mechanism that sui employs and how it plays out?Will end-user funds be slashed by any chance?

3.Validators voting on transactions to form certificates are these counted as consensus messages like Solana? 

4.'Consequently, validators with more stake earn more stake rewards and the joint term incentivizes validators to increase their share of stake while also operating the network performantly'.
Would there be a limit to this to prevent massive centralization and points of failure? 

5.Contd.'delivering a cost-efficient and decentralized network'
How does this enable a decentralized network?

**Comment by randall-Mysten** [comment]
> 1.'Each SUI token is divisible up to a large number of decimal places'. Am I right to say that a maximum of only 9 decimals  termed as Mist is the lowest divisible amount that's possible?

Correct, this info is in a FAQ: MIST is the smallest unit of a SUI Coin. 1 SUI equals 1 billion MIST, and 1 MIST equals 10^-9 of a SUI.
> 
> 2.More info on the slashing mechanism that sui employs and how it plays out?Will end-user funds be slashed by any chance?

Info on this coming next week hopefully. Users won't be slashed directly, but if the validator they stake with is slashes the rewards may be lower for that epoch.
> 
> 3.Validators voting on transactions to form certificates are these counted as consensus messages like Solana?
See https://docs.sui.io/learn/architecture/validators#quorums
We call the combination of the transaction and the quorum signatures on its bytes a certificate. 
> 
> 4.'Consequently, validators with more stake earn more stake rewards and the joint term incentivizes validators to increase their share of stake while also operating the network performantly'. Would there be a limit to this to prevent massive centralization and points of failure?
Yes. The total voting power in the Sui Network is always 10,000. The voting power of each individual validator is similar to basis points. For example, a voting power of 101 = 1.01%. Sui's quorum threshold (number of votes needed to confirm a transaction) is 6,667 (which is greater than 2/3). The voting power for a single validator is capped at 1,000 (10%) regardless of how much stake the validator has.
> 
> 5.Contd.'delivering a cost-efficient and decentralized network' How does this enable a decentralized network?
I'll follow up on this with more info - some things are changing and if I answer now it may not be accurate

**Comment by Hasen1506** [comment]
With regards to the 4th point,so 7 validators with maximal stake allocated to them will end up controlling the network? and also this capping doesn't neccassarily mean the rewards these validators are subsidised in the initial stages of mainnet would be capped too right?

**Comment by randall-Mysten** [comment]
> With regards to the 4th point,so 7 validators with maximal stake allocated to them will end up controlling the network? and also this capping doesn't neccassarily mean the rewards the validators are subsidised in the initial stages of mainnet would be capped too right? (As in the more the users continuing to stake regardless of threshold,the more the inflationary subsidies are distributed)

We're expecting >100 validators for Mainnet launch. Sui Foundation can grant / delegate tokens to validators to meet the minimum required amount in a staking pool. More information about rewards, caps, and the initial phases of Mainnet are being finalized and will be communicated publicly soon, so I will wait for those details to be public before providing more info.

**Comment by Hasen1506** [comment]
I ask this because of the threshold scenario put up,assuming 2 validators with 80 % stake controlled,their voting power essentially cuts down to 20% limit, effectively causing the remaining 20% to have more threshold in relation,am I right with seeing how this plays out.So a validator 3 with 1% of the remaining stake controlled effectively has a threshold power that's times higher than what it should actually be?

Sure I'll wait for more info if that's the way👍🏻
