### ISSUE TITLE
Clock object referrence as entry function parameter cause transaction error

### ISSUE THREAD

**Issue by ericEnjoy** [MystenLabs/sui#9100]
module test::object {

    use sui::clock::{Self, Clock};
    use sui::tx_context::{TxContext};

    entry fun test(clock: &Clock, _ctx: &mut TxContext) {
        clock::timestamp_ms(clock);
    }
} 
code above use clock object ref as parameter in entry function, but get some devnet transaction bug below

`Failed to execute transaction TransactionDigest(ALFs4cLr97rZjsfnFSvSTCdAqsyiSx78jqyTjWT6G7R9) with error RpcError(Call(Custom(ErrorObject { code: ServerError(-32000), message: "Transaction has non recoverable errors from at least 1/3 of validators: [(TransactionInputObjectsErrors { errors: [ImmutableParameterExpectedError] }, [k#ac6d400a64da2782e92bb39f257fea762a9ccd4896e9f6f71005c33887f11d129c67904d7d648b764d0fe7d3e34509d104092aebc43dab974d70c9f2072710f98dbab81a8f7baf304d1907643066ae7929ad1e68522b789415d7dbcbb55997a0, k#8f00ecad8642577957fa533d6a47aa81ccee0dac3745f9b40a2465220b73e681053e5198b57ec29cc999b81b70f4749b13dd4f2140cf991daced03d71ee86802cb627149d06d800032c42e2f565d036f204b04b1be1d4b12d604e77cc0b95449], 5000)].", data: None })))`

It seems like some immutable parameter errror here, but clock object is shared object, that's confused me.
I use 0x6 as clock object ref on devnet, and I also found it was shared object in sui explorer.
I have read docs https://github.com/MystenLabs/sui/blob/dc611075176c958196fff81e86f92a86569d01e6/doc/in-progress/time.md @amnn posted, seems I am using it correctly.
Is there anything am I understanding wrong?

**Comment by amnn** [comment]
Hi @ericEnjoy,

Support for Time hasn't been formally released yet and there is an extra piece of support you need that is coming in the next release of the TypeScript SDK:

There is a new parameter on shared object transaction inputs that indicates whether the input should be taken mutably or not.  This is set automatically for you by the SDK and the current release always sets this to a mutable parameter, which does not work for `Clock` inputs.  The next SDK release will correctly set this parameter based on the signature of the function you are calling, which addresses this error.

If you are running your test on a local instance of the network built from `main`, then you can also build the SDK from `main` to try out this support.

But note that a lot of things are in flux at the moment so `main` is not a stable target to develop off of!
