### ISSUE TITLE
[Faucet] Skip instead of returning an error when the balance is small

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#9163]
Today we return an Error: https://github.com/MystenLabs/sui/blob/aa1a78e7d5538a017d696fb12b573147d9624bc1/crates/sui-faucet/src/faucet/simple_faucet.rs#L338-L344 when the selected coin does not have insufficient balance. This error should not be visible to the end users. Instead, we should try to [find another coin ](https://github.com/MystenLabs/sui/blob/aa1a78e7d5538a017d696fb12b573147d9624bc1/crates/sui-faucet/src/faucet/simple_faucet.rs#L165) when the balance of current selected coin is too low

**Comment by Eis-D-Z** [comment]
Just finding another coin is enough, or would it be better to merge with the next coin until a coin with sufficient balance is formed?

Or slightly larger refactoring where the prepare_gas_coin would return a vector of coins since paySui works like that?

**Comment by stefan-mysten** [comment]
Is this still something that would be desirable to have? @Eis-D-Z @666lcz
