### ISSUE TITLE
Update wallet w/ blake2 changes

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/sui#9248]
depends on https://github.com/MystenLabs/sui/issues/9225 (so we should do after we merge that)

**Comment by pchrysochoidis** [comment]
In wallet I don't think we do any hashing, but we use our ts sdk that I can see it does hash the public key to get the address ([here](https://github.com/MystenLabs/sui/blob/a0955c47974f73933edb832c664740502d19b55a/sdk/typescript/src/cryptography/ed25519-publickey.ts#L70) and [here](https://github.com/MystenLabs/sui/blob/a0955c47974f73933edb832c664740502d19b55a/sdk/typescript/src/cryptography/secp256k1-publickey.ts#L70)) and the transaction data to get the digest ([here](https://github.com/MystenLabs/sui/blob/47a4ac3dd20889daeb723c38b15a6c8075276174/sdk/typescript/src/builder/TransactionData.ts#L123)). Is there anything we should update? @kchalkias @jonas-lj @666lcz 

Any side effects that we need to consider? 

Does https://www.npmjs.com/package/@noble/hashes#blake2b-blake2s look the right hash to you?

**Comment by jonas-lj** [comment]
Yea, the sdk should be changed to be aligned. And yes, that looks like the right hash. We use Blake2b with 256 bit outputs.

**Comment by joyqvq** [comment]
https://github.com/MystenLabs/sui/pull/9262
