### ISSUE TITLE
[security] Ensure no duplicated validator keys

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/sui#9351]
It is in theory possible for validators to "on purpose" pick the same key, either on consensus or anemo. We typically use this info as peerID, and thus we have to ensure correct behavior when this is happening via some unit-test.
cc: @bmwill as we identified that together in a common thread.

**Comment by benr-ml** [comment]
Shouldn't we just reject duplicated keys like we do for the [consensus keys](https://github.com/MystenLabs/sui/blob/8c54f99c671ebb904c3b5ed9ed4bc0d807c9835a/crates/sui-framework/sources/governance/validator.move#L531-L538)?

**Comment by bmwill** [comment]
Yeah we should probably do that
