### ISSUE TITLE
[ts-sdk] Make more providers methods reject

### ISSUE THREAD

**Issue by Jordan-Mysten** [MystenLabs/sui#9500]
Currently, there's some methods on the provider that resolve, but with a failure status. This is confusing and makes it harder than you would expect to write application code. Instead, we should just make these reject.

Cases I've found so far:
- `executeTransaction`
- `getObject`

**Comment by stefan-mysten** [comment]
@Jordan-Mysten I assume that this is outdated, so let me know if we can close it. Thanks!
