### ISSUE TITLE
[ts-sdk] Transaction Builder improvements

### ISSUE THREAD

**Issue by Jordan-Mysten** [MystenLabs/sui#9501]
Some areas of opportunity for improving the TypeScript transaction builder:

- [ ] Currently, we assign input and command indexes when values are added to the transaction. We could instead use references and lazily assign indexes at serialization. This would allow easy dynamic re-ordering, which can be useful in cases where we want to potentially automatically prepend coin management logic to transactions. Alternatively, we could just add some `addBack` method that handles re-ordering of result indexes in other commands automatically.
- [ ] Return types from commands should be configurable, so that we can tell users when they're using the API correctly.
- [x] Add `objectRef` and `sharedObjectRef` shorthand and encourage folks to use it for more offline processing.
- [ ] Add well-known object IDs, to fast path serializing objects like the system object.
- [ ] Allow for commands to be used directly as command arguments, and automatically insert them into the transaction. This will allow for one `.add()` call that also includes things like a coin split command.

**Comment by stefan-mysten** [comment]
@Jordan-Mysten I assume that this is outdated, so let me know if we can close it. Thanks!
