### ISSUE TITLE
ledgerjs-hw-app-sui not compiling in pnpm

### ISSUE THREAD

**Issue by mattsu2020** [MystenLabs/sui#9515]
## Steps to Reproduce Issue
An error occurs when executing pnpm wallet start because ledgerjs-hw-app-sui is not included in package.json.

https://github.com/MystenLabs/sui/blob/main/package.json

## Expected Result
Add the following line to package.json to link ledgerjs-hw-app-sui.

```
    "ledgerjs-hw-app-sui": "pnpm --filter ./sdk/ledgerjs-hw-app-sui",
```

## Actual Result

      TS2307: Cannot find module '@mysten/ledgerjs-hw-app-sui' or its corresponding type declarations.

## System Information

* OS: Mac 13.2.1
* Compiler: pnpm 7.26.0

**Comment by Jordan-Mysten** [comment]
Resolved this issue on main
