### ISSUE TITLE
Sui Expoloer bug when use custom rpc url option

### ISSUE THREAD

**Issue by xuguoqiang-ascaler** [MystenLabs/sui#9549]
set custom rpc url option "http://195.201.86.12:9000 "

the chrome bug info:

24Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '<URL>'. This request has been blocked; the content must be served over HTTPS.

--------------------------------------------------
curl gives the right response
does the sui full node support https for json rpc?

**Comment by Jordan-Mysten** [comment]
This is expected, the explorer only supports HTTP for localhost, otherwise it needs to be HTTPs.
