### ISSUE TITLE
Gas fee charging / computation issue

### ISSUE THREAD

**Issue by rvantonder** [MystenLabs/sui#9587]
Repro: https://github.com/MystenLabs/sui/pull/9560

```
sui/crates/sui-types/src/temporary_store.rs:746:9 panic.file="sui/crates/sui-types/src/temporary_store.rs" panic.line=746 panic.column=9
<unnamed><unnamed>' panicked at '' panicked at 'assertion failed: `(left == right)`
```

> Repro happens when the gas budget is too low.  Could we be incorrectly mishandling a case where we are not resetting the store (or not accounting for the fact that the store is reset) before the dynamic check?

**Comment by rvantonder** [comment]
@dariorussi feel free to self-assign if / when you look into this.

**Comment by stefan-mysten** [comment]
I expect that this has been solved by now. @rvantonder can you confirm please?
