### ISSUE TITLE
[doc] Lint relative links out of the doc

### ISSUE THREAD

**Issue by huitseeker** [MystenLabs/sui#967]
This is because our website is staging in a place divorced from the repo, right?
If so, as relative links are common in MD, we should probably have a linter that catches errors such as these.

_Originally posted by @huitseeker in https://github.com/MystenLabs/sui/pull/959#pullrequestreview-915119094_

**Comment by Clay-Mysten** [comment]
Hi Francois,

I believe this is addressed. Janet is asking.

**Comment by Clay-Mysten** [comment]
@janetwu11 any update here?

**Comment by Clay-Mysten** [comment]
I believe we have this covered six ways to Sunday given all of the automated and manual link checking we now conduct on source files in GitHub and the output in docs.sui.io. See the *Link check site* section of https://app.golinks.io/dev-portal-work for full details.

**Comment by Clay-Mysten** [comment]
@huitseeker, please correct me and reopen this if I am mistaken that this has been addressed. Thanks!
