### ISSUE TITLE
Sui Faucet Request error 1015%

### ISSUE THREAD

**Issue by tiff0000** [MystenLabs/sui#9752]
## Steps to Reproduce Issue

1. Run the following command (from page: **https://docs.sui.io/build/faucet**)
```curl --location --request POST 'https://faucet.devnet.sui.io/gas' \
--header 'Content-Type: application/json' \
--data-raw '{
    "FixedAmountRequest": {
        "recipient": "<YOUR SUI ADDRESS>"
    }
}'

```
2. check the output

## Expected Result

Should expect receiving tokens

## Actual Result

![Screen Shot 2023-03-23 at 3 29 29 AM](https://user-images.githubusercontent.com/20705520/227133310-8c2f4fc9-9064-4547-92c2-7bfbfbbcdc85.png)

returned Error code:1015%

## System Information

* OS: MacOS Big Sur
* Compiler: haven't used compiler

**Comment by stefan-mysten** [comment]
The faucet is rate limited, thus it will yield a `1015` code when too many requests have been received.
