### ISSUE TITLE
BLS bitmap consistency

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/sui#9816]
Let's check that both Sui and Narwhal (after the recent changes from @akichidis) use using the same ordering of validator indices, ideally we need to be consistent.

**Comment by benr-ml** [comment]
Looks like that given a committee, we use the same order:
- https://github.com/MystenLabs/sui/blob/bf933bfc94963eeccad34df39865177c5157c573/crates/sui-types/src/crypto.rs#L1374-L1381
- https://github.com/MystenLabs/sui/blob/bf933bfc94963eeccad34df39865177c5157c573/narwhal/types/src/primary.rs#L702-L712

And that the committee in NW comes from Sui unmodified.

@akichidis, please confirm it's indeed the case.

**Comment by akichidis** [comment]
> @akichidis can you confirm the above so we close the issue?

@kchalkias @benr-ml we use the same order when we process the votes/signatures in the Narwhal certificates. Just to note that SUI & Narwhal use a different Committee structure, but the ordering of the authorities is the same - based on the PublicKey alphabetical ordering. I've introduced a test https://github.com/MystenLabs/sui/pull/10413 as extra check on this and ensure the expectations in signatures.
