### ISSUE TITLE
Request Devnet SUI Tokens Issue

### ISSUE THREAD

**Issue by AunUlHussain** [MystenLabs/sui#9827]
Hey this is Aun Ul Hussain Talpur and I had just started to join your Sui Wallets and Capys but unfortunatley there is a error. I had made an account on sui wallet but when I request Devnet SUI Tokens this error is coming (Too many requests from this client have been sent to the faucet. Please retry later). Let me know what I do should I have to wait some time or how much time it required to try it again? This is my email you can also contact me there (aunulhussintalpur@gmail.com)
Thanks waiting for a prompt response  
Aun Ul Hussain Talpur 
![Untitled](https://user-images.githubusercontent.com/128789218/227461529-430ff67d-d6b0-4062-a6a4-a782597892a1.png)

**Comment by TheVersatilePro** [comment]
Hi, just experiencing the same thing. It pops up a failure message when requesting Devnet SUI Tokens.

**Comment by AunUlHussain** [comment]
> Hi, just experiencing the same thing. It pops up a failure message when requesting Devnet SUI Tokens.
See this now this error is coming after a few time period
![Capture](https://user-images.githubusercontent.com/128789218/227521516-c866d201-dd4d-453f-b022-1c53cce7bc33.PNG)

**Comment by TheVersatilePro** [comment]
Seems like it is fixed now. The request is now proceeding. Received the devnet SUI tokens upon request.

**Comment by AunUlHussain** [comment]
> Seems like it is fixed now. The request is now proceeding. Received the devnet SUI tokens upon request.

Thanks friend

**Comment by AunUlHussain** [comment]
> <img alt="Screenshot 2023-03-27 at 10 39 18 AM" width="347" src="https://user-images.githubusercontent.com/20705520/227973502-9dc15af3-246d-4b1f-ac19-e56945972e8f.png">
> 
> getting timout.. I saw in discord, sometimes the token request fail too, maybe automatically retry?

Yeah I had faced this problem try later it will be okay.

**Comment by TheVersatilePro** [comment]
devnet is currently upgrading. we need to wait till its done. source: official discord channel.
