### ISSUE TITLE
unable to subscribe to WebSocket events

### ISSUE THREAD

**Issue by tttlkkkl** [MystenLabs/sui#9887]
## Steps to Reproduce Issue
The example code of sui-sdk on the devnet branch fails to run on both macOS and Ubuntu systems. The code being executed is as follows:
https://github.com/MystenLabs/sui/blob/main/crates/sui-sdk/examples/event_subscription.rs
```rust
use futures::StreamExt;
use sui_sdk::rpc_types::SuiEventFilter;
use sui_sdk::SuiClientBuilder;

#[tokio::main]
async fn main() -> Result<(), anyhow::Error> {
    let sui = SuiClientBuilder::default()
        .ws_url("wss://wallet-rpc.devnet.sui.io:443")
        .build("https://wallet-rpc.devnet.sui.io:443")
        .await?;
    let mut subscribe_all = sui
        .event_api()
        .subscribe_event(SuiEventFilter::All(vec![]))
        .await?;
    loop {
        println!("{:?}", subscribe_all.next().await);
    }
}
```
```bash
cargo run --example event_subscription
...
Error: Networking or low-level protocol error: Error in the WebSocket handshake: http version was not 1.1

Caused by:
    0: Error in the WebSocket handshake: http version was not 1.1
    1: http version was not 1.1
```

## Expected Result
I expected to be able to subscribe to message notifications from the SUI node, but after multiple attempts, I was unable to do so.
## System Information

* OS: macos 13.2.1 (22D68) M2
* Compiler: rustc 1.65.0 (897e37553 2022-11-02)

**Comment by sheldonkreger** [comment]
On the previous version of devnet, there was a bug in the code that loaded the config from fullnode.yml. If you changed the port for websocket in fullnode.yml, it was ignored and always ran at port 9000. This sounds like it's a separate issue, but figured it was worth mentioning just in case.

**Comment by mlegner** [comment]
I also get an error when trying to subscribe "manually" via curl:
```console
$ curl http://localhost:9000 -H 'Content-Type: application/json' --data-raw '{"jsonrpc": "2.0", "id": 1, "method": "suix_subscribeEvent", "params": [{"All": []}]}'

{"jsonrpc":"2.0","error":{"code":-32603,"message":"Internal error"},"id":1}
```

The same query for `suix_queryEvents` works without issues.

**Comment by stefan-mysten** [comment]
https://github.com/MystenLabs/sui/issues/14355
