### ISSUE TITLE
Sui 8192 Game problem

### ISSUE THREAD

**Issue by TheVersatilePro** [MystenLabs/sui#9902]
Hi, just went to play the game sui 8192. Right after I connected my wallet, it poped up some error with some JSON which I think might be helpful for the dev team.

![image](https://user-images.githubusercontent.com/57457704/227808380-6132feb8-c513-4fdb-a090-dfbc3e811248.png)

**Comment by Jordan-Mysten** [comment]
We've changed the transaction format, and I expect Sui 8192 has not yet been updated to support it. Please report this with them.
