### ISSUE TITLE
[bug] sui move test failed with strange error 

### ISSUE THREAD

**Issue by 0xOutOfGas** [MystenLabs/sui#9993]
## Steps to Reproduce Issue
Upgrade sui client to 0.29, and run the test case failed.
steps:
1. run command in repo `sui move test test_ABC -g --verbose`, and got the error below:
2. 
```
Failures in 0x0::test_ABC:

┌── test_ABC ──────
│ error[E11001]: test failure
│     ┌─ /Users/edy/.move/https___github_com_MystenLabs_sui_git_devnet/crates/sui-framework/packages/sui-framework/sources/dynamic_field.move:226:31
│     │
│ 226 │     public(friend) native fun borrow_child_object_mut<Child: key>(object: &mut UID, id: address): &mut Child;
│     │                               ^^^^^^^^^^^^^^^^^^^^^^^
│     │                               │
│     │                               Test was not expected to error, but it aborted with code 3 originating in the module 0000000000000000000000000000000000000000000000000000000000000002::dynamic_field rooted here
│     │                               In this function in 0x2::dynamic_field
│ 
│ 
│ ────── Storage state at point of failure ──────
│ <empty>
└──────────────────

Test result: FAILED. Total tests: 4; passed: 0; failed: 4
```

## Expected Result
should report failure or pass, and the error message should be related to the source codes. 

## System Information

* OS: mac, sui 0.29

**Comment by stefan-mysten** [comment]
@0xOutOfGas Thanks for flagging this. Since March, the `sui move test` command has gone through several improvements and actually the `-g` flag does not exist anymore. I will close this issue, but feel free to file a new issue if you encounter any problems.
